### ISSUE TITLE
Can't infer T where T is Mapping[str, int] or Mapping[K, V], but works for sequence

### ISSUE THREAD

**Issue by andy-ms** [python/mypy#7727] opened 2019-10-16 19:29 UTC
* Are you reporting a bug, or opening a feature request?
bug

* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.

```py
from typing import Mapping, Sequence, TypeVar

E = TypeVar("E")
K = TypeVar("K")
V = TypeVar("V")
T = TypeVar("T")

def choose_one_of(a: T, b: T) -> T:
    return a

def empty_sequence() -> Sequence[E]:
    return []

def empty_mapping() -> Mapping[K, V]:
    return {}

def choose_seq(s: Sequence[int]) -> Sequence[int]:
    x = choose_one_of(s, empty_sequence())
    return x

def choose_mapping(m: Mapping[str, int]) -> Mapping[str, int]:
   x = choose_one_of(m, empty_mapping())
   return x

print(choose_seq([]))
print(choose_mapping({}))
```

* What is the actual behavior/output?

`a.py:23: error: Incompatible return value type (got "object", expected "Mapping[str, int]")`

* What is the behavior/output you expect?

No error.

Interestingly, there is no error if `empty_mapping` returns `Mapping[str, V]` (or `Mapping[str, int]`), but there is still an error if it returns `Mapping[K, int]`.

* What are the versions of mypy and Python you are using?
  Do you see the same issue after installing mypy from Git master?

`mypy --version` is `mypy 0.740+dev.222b14d904a0e359bec934fd81d67d981abdada4`
`python --version` is `Python 3.7.4`

* What are the mypy flags you are using? (For example --strict-optional)

None

**Comment by ilevkivskyi** [comment] 2019-10-18 20:17
This is actually related to the fact that `Mapping` is invariant in key type (but not in value type as you observe).

So this is essentially a duplicate of https://github.com/python/typing/issues/445

**Closed by ilevkivskyi** 2019-10-18 20:17 UTC

**Comment by ilevkivskyi** [comment] 2019-10-18 20:18
Note that https://github.com/python/mypy/issues/6613 when applied to mapping key type will also solve this I think.
