### ISSUE TITLE
INTERNAL ERROR occurs when class uses TypeVarTuple and ParamSpec

### ISSUE THREAD

**Issue by erictraut** [python/mypy#17041] opened 2024-03-16 14:07 UTC
The follow code snippet results in an INTERNAL ERROR within mypy 1.9.

[Mypy playground link](https://mypy-play.net/?mypy=latest&python=3.12&gist=ba4e0c5eead4b2d5b0c5036ff93fc985)

```python
from typing import Generic, ParamSpec, TypeVarTuple

Ts = TypeVarTuple("Ts")
P = ParamSpec("P")

class Foo(Generic[*Ts, P]): ...

Foo[int, [str]]
```

A variant of this code appears in the type checker conformance tests, specifically in [this file](https://github.com/python/typing/blob/main/conformance/tests/generics_defaults.py). This crash prevents mypy from running the conformance tests to completion.

Here is the traceback:

```
version: 1.9.0
Traceback (most recent call last):
  File "mypy/semanal.py", line 6550, in accept
  File "mypy/nodes.py", line 1142, in accept
  File "mypy/semanal.py", line 1612, in visit_class_def
  File "mypy/semanal.py", line 1684, in analyze_class
  File "mypy/semanal.py", line 1703, in setup_type_vars
  File "mypy/nodes.py", line 3095, in add_type_vars
AssertionError: Mixing type var tuples and param specs not supported yet
```

So it appears this case is not yet supported.

**Comment by AlexWaygood** [comment] 2024-03-16 14:24
Duplicate of #16695

**Closed by AlexWaygood** 2024-03-16 14:24 UTC
Labels: bug
