### ISSUE TITLE
Crash when using `match` on an object which was annotated via generic `TypeVar`.

### ISSUE THREAD

**Issue by dam5h** [python/mypy#13387] opened 2022-08-11 18:37 UTC
**Crash Report**

Crash when using `match` on an object which was annotated via generic `TypeVar`.

**Traceback**

```
 △ ~/code/edgar mypy scratch/mypy-test.py --show-traceback                                                                                                                                                                                                   ⇡ core-exp-params-attrs 1d ● ⬡
scratch/mypy-test.py:17: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.980+dev.92420469fddfb6b96b1e66ed8ab02ace550bc01c
Traceback (most recent call last):
  File "/home/dave/.pyenv/versions/edgar-3.10/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/home/dave/.pyenv/versions/edgar-3.10/lib/python3.10/site-packages/mypy/__main__.py", line 12, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "/home/dave/.pyenv/versions/edgar-3.10/lib/python3.10/site-packages/mypy/main.py", line 94, in main
    res, messages, blockers = run_build(sources, options, fscache, t0, stdout, stderr)
  File "/home/dave/.pyenv/versions/edgar-3.10/lib/python3.10/site-packages/mypy/main.py", line 173, in run_build
    res = build.build(sources, options, None, flush_errors, fscache, stdout, stderr)
  File "/home/dave/.pyenv/versions/edgar-3.10/lib/python3.10/site-packages/mypy/build.py", line 189, in build
    result = _build(
  File "/home/dave/.pyenv/versions/edgar-3.10/lib/python3.10/site-packages/mypy/build.py", line 273, in _build
    graph = dispatch(sources, manager, stdout)
  File "/home/dave/.pyenv/versions/edgar-3.10/lib/python3.10/site-packages/mypy/build.py", line 2880, in dispatch
    process_graph(graph, manager)
  File "/home/dave/.pyenv/versions/edgar-3.10/lib/python3.10/site-packages/mypy/build.py", line 3264, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/home/dave/.pyenv/versions/edgar-3.10/lib/python3.10/site-packages/mypy/build.py", line 3365, in process_stale_scc
    graph[id].type_check_first_pass()
  File "/home/dave/.pyenv/versions/edgar-3.10/lib/python3.10/site-packages/mypy/build.py", line 2308, in type_check_first_pass
    self.type_checker().check_first_pass()
  File "/home/dave/.pyenv/versions/edgar-3.10/lib/python3.10/site-packages/mypy/checker.py", line 460, in check_first_pass
    self.accept(d)
  File "/home/dave/.pyenv/versions/edgar-3.10/lib/python3.10/site-packages/mypy/checker.py", line 566, in accept
    stmt.accept(self)
  File "/home/dave/.pyenv/versions/edgar-3.10/lib/python3.10/site-packages/mypy/nodes.py", line 811, in accept
    return visitor.visit_func_def(self)
  File "/home/dave/.pyenv/versions/edgar-3.10/lib/python3.10/site-packages/mypy/checker.py", line 930, in visit_func_def
    self._visit_func_def(defn)
  File "/home/dave/.pyenv/versions/edgar-3.10/lib/python3.10/site-packages/mypy/checker.py", line 934, in _visit_func_def
    self.check_func_item(defn, name=defn.name)
  File "/home/dave/.pyenv/versions/edgar-3.10/lib/python3.10/site-packages/mypy/checker.py", line 1003, in check_func_item
    self.check_func_def(defn, typ, name)
  File "/home/dave/.pyenv/versions/edgar-3.10/lib/python3.10/site-packages/mypy/checker.py", line 1023, in check_func_def
    expanded = self.expand_typevars(defn, typ)
  File "/home/dave/.pyenv/versions/edgar-3.10/lib/python3.10/site-packages/mypy/checker.py", line 1650, in expand_typevars
    result.append((expand_func(defn, mapping), expanded))
  File "/home/dave/.pyenv/versions/edgar-3.10/lib/python3.10/site-packages/mypy/checker.py", line 6425, in expand_func
    ret = visitor.node(defn)
  File "/home/dave/.pyenv/versions/edgar-3.10/lib/python3.10/site-packages/mypy/treetransform.py", line 616, in node
    new = node.accept(self)
  File "/home/dave/.pyenv/versions/edgar-3.10/lib/python3.10/site-packages/mypy/nodes.py", line 811, in accept
    return visitor.visit_func_def(self)
  File "/home/dave/.pyenv/versions/edgar-3.10/lib/python3.10/site-packages/mypy/treetransform.py", line 180, in visit_func_def
    self.block(node.body),
  File "/home/dave/.pyenv/versions/edgar-3.10/lib/python3.10/site-packages/mypy/treetransform.py", line 649, in block
    new = self.visit_block(block)
  File "/home/dave/.pyenv/versions/edgar-3.10/lib/python3.10/site-packages/mypy/treetransform.py", line 262, in visit_block
    return Block(self.statements(node.body))
  File "/home/dave/.pyenv/versions/edgar-3.10/lib/python3.10/site-packages/mypy/treetransform.py", line 660, in statements
    return [self.stmt(stmt) for stmt in statements]
  File "/home/dave/.pyenv/versions/edgar-3.10/lib/python3.10/site-packages/mypy/treetransform.py", line 660, in <listcomp>
    return [self.stmt(stmt) for stmt in statements]
  File "/home/dave/.pyenv/versions/edgar-3.10/lib/python3.10/site-packages/mypy/treetransform.py", line 634, in stmt
    assert isinstance(new, Statement)
AssertionError: 
scratch/mypy-test.py:17: : note: use --pdb to drop into pdb
```

**To Reproduce**
```
from __future__ import annotations

from typing import TypeVar


class Foo:
    ...


class Bar:
    ...


T = TypeVar("T", Foo, Bar)


def m(x: T) -> T:

    match x:
        case Foo():
            print("Foo")
        case Bar():
            print("Bar")
    return x
```
**Your Environment**

- Mypy version used: mypy 0.980+dev.92420469fddfb6b96b1e66ed8ab02ace550bc01c (compiled: no)
- Python version used: 3.10.2
- Operating system and version: linux 5.18.16-arch1-1

**Comment by AlexWaygood** [comment] 2022-08-11 21:17
Duplicate of #12448

**Closed by AlexWaygood** 2022-08-11 21:17 UTC
Labels: crash

**Comment by dam5h** [comment] 2022-08-15 21:41
Opps, my bad, I totally spaced on checking for existing issue on this one.  Appreciate the quick response!
