### ISSUE TITLE
ternary of Tuple[builtins.str] / Tuple[] falling to `builtins.object`

### ISSUE THREAD

**Issue by asottile** [python/mypy#5150] opened 2018-06-05 15:37 UTC
### version

```console
$ mypy --version
mypy 0.600
```

### code

```python
import sys

tty = ('--tty',) if sys.stdout.isatty() else ()
#reveal_type(tty)
#reveal_type(('--tty',))
#reveal_type(())
cmd = ('docker', 'run', *tty, 'ubuntu:bionic', 'bash')
```

### run (without revealed types)

```console
$ mypy test.py
test.py:7: error: List or tuple expected as variable arguments
```

### run (with revealed types)

```console
$ mypy test.py
test.py:4: error: Revealed type is 'builtins.object'
test.py:5: error: Revealed type is 'Tuple[builtins.str]'
test.py:6: error: Revealed type is 'Tuple[]'
test.py:7: error: List or tuple expected as variable arguments
```

Possibly related: #5134

**Comment by ethanhs** [comment] 2018-06-05 18:54
I feel that `tuple if bool else tuple` should result in some kind of tuple. I'm not sure which, probably `Tuple[str, ...]` in this case?

**Comment by asottile** [comment] 2018-06-05 19:12
I think `Tuple[str,...] ` would be ideal, though even the `Union[...] ` would probably make this succeed

**Comment by ilevkivskyi** [comment] 2018-06-06 13:34
This is essentially a duplicate of https://github.com/python/mypy/issues/4975, we just need to produce better joins for tuple types.

**Closed by ilevkivskyi** 2018-06-06 13:34 UTC
Labels: bug, false-positive, priority-0-high
