### ISSUE TITLE
__getattr__ support for metaclass

### ISSUE THREAD

**Issue by yuyangguo42** [python/mypy#3840] opened 2017-08-18 00:49 UTC
```
from six import add_metaclass

class MetaFoo(type):
    SOME_DICT = {
        'asdf': 'bbbb',
    }
    def __getattr__(cls, attr):
        # type: (str) -> str
        return MetaFoo.SOME_DICT[attr]

@add_metaclass(MetaFoo)
class Foo(object):
    pass

print(Foo.asdf)  # error: Type[Foo] has no attribute "asdf"
```

So not sure if this is supposed to be supported or the usage pattern should be dis-encouraged anyways ><

**Comment by ilevkivskyi** [comment] 2017-08-18 08:12
This is not very high priority, but on the other hand this should be easy to implement. If you want to make a PR, then please take a look at ``checkmember.analyze_class_attribute_access`` (you can see how to make special treatment of ``__getattr__`` etc. in ``checkmember.analyze_member_var_access``)

**Comment by elazarg** [comment] 2017-08-18 09:02
It's unrelated to member access in metaclasses. mypy simply does not understand `add_metaclass`. It works fine with standard metaclasses, and on the other hand
```python
x = Foo  # type: MetaFoo
```
fails too.

**Comment by elazarg** [comment] 2017-08-18 09:05
So this is duplicate of #3365.

**Comment by ilevkivskyi** [comment] 2017-08-18 09:43
OK, then I am closing this as a duplicate.

**Closed by ilevkivskyi** 2017-08-18 09:43 UTC
Labels: feature, priority-1-normal

**Comment by elazarg** [comment] 2017-08-18 10:39
@yuyangguo42 you may want to try #3842.
