### ISSUE TITLE
Support generic NamedTuples

### ISSUE THREAD

**Issue by ghost** [python/mypy#685] opened 2015-05-18 02:41 UTC
I tried this for a generic NamedTuple:

```
S = TypeVar("S")
T = TypeVar("T")

class Pair(Generic[S, T],
    NamedTuple("Pair",[
        ('fst', S),
        ('second', T)])):
    def show(self):
        print(self.fst, self.second)

p = Pair("ab", 22)  # type: Pair[str, int]
```

Mypy raised an exception: `RuntimeError: TypeVarType is already analysed`.

Related question: is this the right way to define a generic NamedTuple?

Thanks!

**Comment by spkersten** [comment] 2015-05-18 06:09
I think you're seeing the same error as Jukka in #279.

**Comment by JukkaL** [comment] 2015-05-19 03:08
The code should work, but I think that the `NamedTuple` implementation in mypy currently doesn't support generic named tuples (there are also a few other things I left out when implementing named tuples).

I don't think it would be a lot of work to implement, but anything involving generics is at least a little tricky.

**Comment by gvanrossum** [comment] 2016-05-05 00:28
Yeah, still reproducible. Here's a simpler repro:
```
from typing import *
T = TypeVar('T')
class P(Generic[T],
        NamedTuple('P', [('field', T)])):
    pass
p = P("")  # type: P[str]
```
Output:
```
x.py:4: error: 'T' is a type variable and only valid in type context
x.py:6: error: Generic tuple types not supported
```

**Comment by gvanrossum** [comment] 2016-05-05 00:29
But it's no longer an exception in mypy, it just prints an error.

**Comment by JukkaL** [comment] 2017-04-03 10:05
Here is a rough idea how it might be possible to implement generic named tuples (note that I haven't spend a lot of time on this so this might all make no sense):

* Start with a generic class that inherits from `Tuple[...]`. Named tuple should just be a generalization of that.
* The representation of the type would still be `TupleType`, similar to current named tuples. It would be best to *not* make `TupleTupe` itself generic, since it would likely complicate the implementation a lot. Instead, maybe just have the `TupleType` keep the substituted tuple item types. The fallback would be a generic `Instance`.
* The generic bit would be handled by a mostly ordinary generic `TypeInfo` that would also have the `tuple_type` attribute set. `tuple_type` could contain class type variables and these would need to be substituted when creating a corresponding `TupleType`.
* Maybe require all type variable to be covariant in generic named tuples so that covariant tuple subtyping is preserved. Not sure if this is necessary.

**Comment by JelleZijlstra** [comment] 2017-04-03 15:21
I have a partially working implementation of generic namedtuples on top of #3081; I can work more on it once that one is merged. My general approach is just to make namedtuples more and more like normal classes.

**Comment by elazarg** [comment] 2017-04-07 01:35
#3134 too has some support for generic namedtuple falling out of the implementation.

@JelleZijlstra #3081 is indeed conflicting. The general idea is similar, except I do not make the namedtuple look like a class, but rather change it to manipulate the `TypeInfo` of the previously-constructed class (the way metaclasses work). It also reduces some of the existing code duplication, and avoids messing with AST nodes in the analysis.

(I did not mean to overlap with your work; it happened through the course of refactoring. I think I should try to find a way for these PRs to live together.  But I guess #3134 will have hard time to merge anyway due to code churn).

**Comment by ilevkivskyi** [comment] 2017-07-20 17:43
#1682 provides an additional repro that should be added to tests when this is fixed.

**Comment by mitar** [comment] 2017-11-30 23:55
Any progress on this?

**Comment by ilevkivskyi** [comment] 2018-10-23 17:08
Raising priority to normal, since this appeared several times (still not high priority, since the fix is non-trivial).

**Comment by wkschwartz** [comment] 2019-06-25 17:31
Another spelling that would be nice if it worked is

```python
from typing import Generic, NamedTuple, TypeVar
T = TypeVar('T')
class Result(Generic[T], NamedTuple):
	result: T
	other_data: str
result: Result[int] = Result(result=1, other_data='a')
```

As of Mypy version 0.711, this gives the following error:
```
mypy-test.py:6: error: Generic tuple types not supported
mypy-test.py:6: error: Argument "result" to "Result" has incompatible type "int"; expected "T"
```

**Comment by Phlogistique** [comment] 2019-10-17 14:00
As a result of this bug, the type annotation for `concurrent.futures.wait` in the Typeshed is broken; it should be a `DoneAndNotDoneFutures[_T]` named tuple, but this type can not currently be used with mypy.

**Comment by mortoray** [comment] 2021-03-06 07:09
I'd like to see this working. Presently I want this code:

```
RefT = TypeVar('RefT')
class Reference(NamedTuple, Generic[RefT]):
	ref: RefT
	where: List[str]
```

But need to use a dataclass instead, which unfortunately is mutable and can't be deconstructed like a tuple.

```
@dataclass
class Reference(Generic[RefT]):
	ref: RefT
	where: List[str]
```

**Comment by DetachHead** [comment] 2021-12-13 00:57
this seems to also be an issue when attempting to extend `tuple`.

```py
from typing import TypeVar
T = TypeVar("T")


class Foo(tuple[T, T]): pass

a: Foo[int] # error: Generic tuple types not supported  [misc]
```

is this intended behavior? i don't see why this shouldn't be allowed

**Comment by CarliJoy** [comment] 2022-02-18 17:40
> this seems to also be an issue when attempting to extend `tuple`.
> 
> ```python
> from typing import TypeVar
> T = TypeVar("T")
> 
> 
> class Foo(tuple[T, T]): pass
> 
> a: Foo[int] # error: Generic tuple types not supported  [misc]
> ```
> 
> is this intended behavior? i don't see why this shouldn't be allowed

Have the same Problem like @DetachHead is it as compilcated to fix as for NamedTuples? Is it the same error?

**Comment by AlexWaygood** [comment] 2022-05-04 20:08
To update on this issue: generic NamedTuples are now supported by the runtime in 3.11, and https://github.com/python/typing/issues/1174 tracks the progress of a backport via `typing_extensions`. Mypy support for the feature is still missing, however.

**Closed** 2022-08-15 09:04 UTC
Labels: feature, topic-named-tuple, priority-1-normal, false-positive
