### ISSUE TITLE
feature request: explicity metaclass().__getitem__ typing

### ISSUE THREAD

**Issue by Levitanus** [python/mypy#6313] opened 2019-02-04 06:44 UTC
Mypy does well with metaclass ```__getitem__``` when the class is instatiated,
but in case of indexing just the child class, it fails:
```Python
class Other:
    ...

class GenMeta(type):
    def __getitem__(cls, ref: Type[int]) -> Type[Other]:
        return Other

class Gen(metaclass=GenMeta):
    ...

a = Gen[int]  # "Gen" expects no type arguments, but 1 given
reveal_type(a)  # Revealed type is 'Any'
b = Gen[int]()
reveal_type(b)  # Revealed type is 'pyksp.simple_test.Other'


def foo(arg: Gen[int]) -> None:  # "Gen" expects no type arguments, but 1 given
    reveal_type(arg)  # Revealed type is 'pyksp.simple_test.Gen'
```

I think it would be very useful to check, especially in case of function annotations

**Comment by ilevkivskyi** [comment] 2019-02-04 10:04
It is expected that it works in runtime context but doesn't work in type context, because anything that appears in type context should be known statically. Consider a simpler example:
```python
def f() -> Type[int]: ...

x = f()()  # OK, inferred type for x is `int`
y: f()  # Fails
```
The error message however is confusing, but the this is essentially a duplicate of https://github.com/python/mypy/issues/4030

**Closed by ilevkivskyi** 2019-02-04 10:04 UTC

**Comment by ilevkivskyi** [comment] 2019-02-04 10:06
By the way, the workaround for your case is to use `if TYPE_CHECKING: ...`.

**Comment by Levitanus** [comment] 2019-02-04 10:31
Sorry, can you expand the last comment?
If TYPE_CHECKING where?

**Comment by ilevkivskyi** [comment] 2019-02-04 10:37
```python
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    <definition of Gen that would satisfy mypy>
else:
    <your definition that will be executed at runtime>
```

**Comment by A5rocks** [comment] 2023-02-17 22:17
If I understand the reason this can't happen correctly, wouldn't this be solved by a `type` that has an invariant rather than covariant (?) type variable?
