### ISSUE TITLE
Cannot use type(None) as parameter

### ISSUE THREAD

**Issue by mitar** [python/mypy#3992] opened 2017-09-24 00:32 UTC
The following code fails with current master (2bd11f6):

```python
from typing import *

Inputs = List[type(None)]
````

With the following errors:

```
test.py:3: error: Type expected within [...]
test.py:3: error: Invalid type alias
test.py:3: error: Value of type "Type[List[Any]]" is not indexable
```

```python
from typing import *

Inputs = List[None]
````

Works. And the following works as well:

```python
from typing import *

Void = type(None)
Inputs = List[Void]
```

**Comment by ilevkivskyi** [comment] 2017-09-24 07:11
This is a duplicate of https://github.com/python/mypy/issues/640

**Closed by ilevkivskyi** 2017-09-24 07:11 UTC
