### ISSUE TITLE
parse error on functions with type annotations in comments

### ISSUE THREAD

**Issue by rbtcollins** [python/mypy#651] opened 2015-04-20 11:00 UTC
```
MYPYPATH=.../stubs mypy --use-python-path linecache2/__init__.py
linecache2/__init__.py: In function "getlines":
linecache2/__init__.py, line 42: Parse error before "typing"
make: *** [lint] Error 1
```
this is line 42:
```
def getlines(filename, module_globals=None): # type: typing.Function[[str, typing.Dict[str, typing.Any]], int]
```
I'm trying this because I have 2.x code to support, and if I can lint it on 3.2+, thats a win, but I'd rather not use the codec if I don't have to.

**Comment by rockneurotiko** [comment] 2015-04-20 11:11
I think that you can't use the comment annotation in functions, only in variables.

One of the use cases of stub files is to support python 2.x and 3.x, so, instead of inline comment, maybe you can write a stub file.

**Comment by rbtcollins** [comment] 2015-04-20 19:29
If I write a stub file, don't I lose all the in-function annotations?

**Comment by JukkaL** [comment] 2015-04-29 04:37
Currently mypy supports an experimental syntax for giving a function annotation using a comment:

```python
def f(x): # type: (int) -> str
    return str(x * 2)
```

The comment can also be on the line after the colon:

```python
def f(x): 
    # type: (int) -> str
    return str(x * 2)
```

This was intended for Python 2 code and has been around for a long time, but I'm not sure whether this is actually a good idea.

Note that function type comment has a different syntax from variable annotations, even though both use a `# type:` comment. `(int) -> str`, for example, is not a valid type for a variable.

**Comment by rbtcollins** [comment] 2015-04-29 05:26
Ok, thats good to know. Uhm, why isn't that a valid type for a variable? Variables can be functions...

**Comment by gvanrossum** [comment] 2015-04-29 16:36
You should use the Function[[args], result] notation from PEP 484 for
variables/args.

On Tue, Apr 28, 2015 at 10:26 PM, rbtcollins <notifications@github.com>
wrote:

> Ok, thats good to know. Uhm, why isn't that a valid type for a variable?
> Variables can be functions...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JukkaL/mypy/issues/651#issuecomment-97310840>.
>



-- 
--Guido van Rossum (python.org/~guido)

**Comment by rbtcollins** [comment] 2015-04-30 00:50
Ok sure, I'm just confused why there are two notations that both describe the signature of a function.

**Comment by JukkaL** [comment] 2015-05-03 23:54
The alternative notation was intended for code that needs to be Python 2 compatible. That's the only reason why the notation exists.

**Comment by JukkaL** [comment] 2015-05-04 00:00
@rbtcollins Feel free to reopen this if you still have issues with the syntax, closing this now.

**Comment by rbtcollins** [comment] 2015-05-04 00:04
Well I'm still confused. Why shouldn't the Function[[args], result] notation work? {btw there is no 'reopen' for users in github issues}

**Comment by JukkaL** [comment] 2015-05-04 01:13
Ah, sorry I didn't realize that you can't reopen this.

The reason why  `Function[[args], result]` isn't supported is that there's a more convenient notation (`(args) -> result`) and it seems messy to support two notations. 

Besides convenience, the alternative notation is extensible and can also support arguments with default values and things like `*args` and `**kwargs` (and it could support specifying argument names for extra readability for complex functions). `Function[[args], result]` only works for the simplest of function signatures.

Example:

```
def f(x, y=1, **kwargs): # type: (str, int, **float) -> None
    ...
```

We can't use `Function[...]` meaningfully for `f` in the above example, but the alternative syntax works pretty well.

**Comment by rbtcollins** [comment] 2015-05-04 01:42
That explains why the arrow notation is better:)..

it doesn't explain why we have two notations  :- wouldn't replacing the Function[...] notation with the arrow notation grant those same benefits to function variables?

**Comment by gvanrossum** [comment] 2015-05-04 03:20
The `Function[...]` notation exists because in annotations we don't want to introduce new syntax. Type comments don't have that constraint. The `(...) -> ...` notation will not be sanctioned by the PEP (which doesn't directly concern itself with Python 2).

**Comment by gvanrossum** [comment] 2016-04-08 16:51
Closing this again. If you still have a beef with this please open an issue in https://github.com/python/typing/ because it would require changes to the PEP.

IIUC, the crux here is that while Python treats `def foo(x): pass` as an assignment of a function object to `foo`, but that is only at runtime, not syntactically (there's no `=` in the syntax of a function definition).

PEP 484 and mypy continue this syntactic difference by stating that if you define a function variable using `=` you can use `# type: Callable[[args], rtype]` to state its type, but if you define a function using `def` you must use the signature annotation syntax. That's `def foo(a: int) -> str: ...` for Python 3, or
```
def foo(a):
    # type: (int) -> str
    ...
```
for Python 2. (Note that the latter was added to the PEP recently.)

Yet another way to think of the difference is that
```
x = blah  # type: something
```
is a crutch for a future `var` declaration syntax where you might end up being able to write
```
var x: something = blah
```
IOW the `# type: ...` syntax (except for `# type: ignore`) is closely tied to an assignment to a variable.

(Note that it's not likely we'll get exactly the shown `var` syntax, because `var` is way too common as a variable name. But we'll figure something out in the Python 3.7 timeframe.)

**Closed by gvanrossum** 2016-04-08 16:51 UTC
