### ISSUE TITLE
hangs on imports from pydantic v2

### ISSUE THREAD

**Issue by DetachHead** [python/mypy#14627] opened 2023-02-07 00:24 UTC
```py
from pydantic import BaseModel
```
mypy version: 1.0.0
pydantic version: 2.0.0.dev.0 (installed from github https://github.com/pydantic/pydantic/commit/ef3cc495a9c86553b62a95a6052fd9b6ebc045e9)

when running mypy with `-vvv` it gets stuck on:
```
LOG:  Processing SCC singleton (pydantic_core.core_schema) as inherently stale
```

**Comment by KotlinIsland** [comment] 2023-02-07 00:52
Could this be a super massive black hole union: https://github.com/pydantic/pydantic-core/blob/bfb373c269ae2bfcc32c15e4f1e59f2cee30b2ac/pydantic_core/core_schema.py#L2547?

**Comment by JelleZijlstra** [comment] 2023-02-07 03:53
Using the poor man's debugger of running `mypy -vvvvv -c 'from pydantic import BaseModel' --show-traceback` and Ctrl-C-ing, it seems to get stuck somewhere in `is_subtype`:

```
  File "mypy/types.py", line 2330, in accept
  File "mypy/subtypes.py", line 780, in visit_typeddict_type
  File "mypy/subtypes.py", line 233, in is_equivalent
  File "mypy/subtypes.py", line 175, in is_subtype
  File "mypy/subtypes.py", line 335, in _is_subtype
  File "mypy/types.py", line 2673, in accept
  File "mypy/subtypes.py", line 927, in visit_union_type
  File "mypy/subtypes.py", line 388, in _is_subtype
  File "mypy/subtypes.py", line 175, in is_subtype
  File "mypy/subtypes.py", line 335, in _is_subtype
  File "mypy/types.py", line 2673, in accept
  File "mypy/subtypes.py", line 927, in visit_union_type
  File "mypy/subtypes.py", line 388, in _is_subtype
  File "mypy/subtypes.py", line 175, in is_subtype
  File "mypy/subtypes.py", line 300, in _is_subtype
  File "mypy/subtypes.py", line 175, in is_subtype
  File "mypy/subtypes.py", line 300, in _is_subtype
  File "mypy/subtypes.py", line 175, in is_subtype
  File "mypy/subtypes.py", line 335, in _is_subtype
  File "mypy/types.py", line 2330, in accept
  File "mypy/subtypes.py", line 780, in visit_typeddict_type
  File "mypy/subtypes.py", line 233, in is_equivalent
  File "mypy/subtypes.py", line 175, in is_subtype
  File "mypy/subtypes.py", line 335, in _is_subtype
  File "mypy/types.py", line 2673, in accept
  File "mypy/subtypes.py", line 927, in visit_union_type
  File "mypy/subtypes.py", line 388, in _is_subtype
  File "mypy/subtypes.py", line 175, in is_subtype
  File "mypy/subtypes.py", line 300, in _is_subtype
  File "mypy/subtypes.py", line 175, in is_subtype
  File "mypy/subtypes.py", line 335, in _is_subtype
  File "mypy/types.py", line 2330, in accept
  File "mypy/subtypes.py", line 780, in visit_typeddict_type
  File "mypy/subtypes.py", line 240, in is_equivalent
  File "mypy/subtypes.py", line 175, in is_subtype
  File "mypy/subtypes.py", line 335, in _is_subtype
  File "mypy/types.py", line 2673, in accept
  File "mypy/subtypes.py", line 927, in visit_union_type
  File "mypy/subtypes.py", line 388, in _is_subtype
  File "mypy/subtypes.py", line 175, in is_subtype
  File "mypy/subtypes.py", line 300, in _is_subtype
  File "mypy/subtypes.py", line 174, in is_subtype
  File "/Users/jelle/.pyenv/versions/3.11.1/lib/python3.11/contextlib.py", line 284, in helper
    @wraps(func)
```

It's indeed plausible this has something to do with the huge Union.

**Comment by cdce8p** [comment] 2023-02-08 00:43
> Could this be a super massive black hole union: https://github.com/pydantic/pydantic-core/blob/bfb373c269ae2bfcc32c15e4f1e59f2cee30b2ac/pydantic_core/core_schema.py#L2547?

Probably. It's also used recursively in some places which doesn't help either.
I added a common base type which seems to resolve this particular issue. https://github.com/pydantic/pydantic-core/pull/387

As for mypy, it seems there is a performance issue with large unions in particular. That might be something to look into.
Had a similar issue a while back but that was with custom Enum types and a large Union type. Resolved it in a similar way though by adding a base class and using that instead.  https://github.com/home-assistant-libs/zwave-js-server-python/pull/435

**Comment by KotlinIsland** [comment] 2023-02-08 00:55
I had a similar issues here https://github.com/KotlinIsland/basedmypy/issues/399

**Comment by cdce8p** [comment] 2023-02-08 01:00
Maybe a first step could be to add a section to the [Common issues](https://mypy.readthedocs.io/en/stable/common_issues.html) page. That way users could at least find and know about it.

**Comment by samuelcolvin** [comment] 2023-02-08 08:14
This is a duplicate of #14034 I think.

**Closed** 2023-02-08 08:39 UTC
Labels: bug
