### ISSUE TITLE
[feature request] option to assume None as return type

### ISSUE THREAD

**Issue by beauxq** [python/mypy#12695] opened 2022-04-29 04:11 UTC
**Feature**

an option to assume `None` as the return type if there is no return type annotation

(With this option, `disallow-untyped-defs` would only make sure all parameters are typed.)

**Pitch**

Putting `-> None` on every function that doesn't return a value adds a lot of clutter, but it's required in order to enforce that all the parameters are typed.

(And making sure all the parameters are typed is required to get all of the available static typing analysis benefits.)

**Comment by AlexWaygood** [comment] 2022-04-29 04:17
Duplicate of #10149

**Comment by AlexWaygood** [comment] 2022-04-29 05:47
#4409?

**Comment by AlexWaygood** [comment] 2022-04-29 05:52
Okay, I suppose this functionality could be implemented behind a flag. Apologies for the misdiagnosis :)

I think it's highly unlikely that this functionality will be implemented, though, unless you'd like to submit a PR to make it happen (and even then, nothing's guaranteed).

**Comment by pranavrajpal** [comment] 2022-05-01 18:17
This looks like a duplicate of #9413.

**Comment by AlexWaygood** [comment] 2022-05-01 19:25
> This looks like a duplicate of #9413.

Yup. Thanks @pranavrajpal.

**Closed by AlexWaygood** 2022-05-01 19:25 UTC
Labels: feature
