### ISSUE TITLE
MyPy complains about conditional import

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/mypy#8155] opened 2019-12-16 15:35 UTC
MyPy does not understand the common EAFP idiom used for importing backported features:

```
$ mypy t.py 
t.py:4: error: Name 'asynccontextmanager' already defined (possibly by an import)
Found 1 error in 1 file (checked 1 source file)
```
```
$ cat t.py
try:
    from contextlib import asynccontextmanager
except ImportError:  # Python < 3.7
    from async_generator import asynccontextmanager
```
```
$ cat setup.cfg
[mypy-async_generator]
ignore_missing_imports = true
```
```
$ mypy --version
mypy 0.740
```
```
$ python --version
Python 3.7.5
```
Is there a way to pacify MyPy?

**Comment by refi64** [comment] 2019-12-16 17:14
https://github.com/python/mypy/issues/1153

**Comment by ilevkivskyi** [comment] 2019-12-18 13:45
Yes, this is a duplicate of #1153, for now you can either use `if sys.version_info[:2] >= (3, 7): ...` (mypy understands that), or just put `# type: ignore[no-redef]` on the second import.

**Closed by ilevkivskyi** 2019-12-18 13:45 UTC
