### ISSUE TITLE
Doesn't support NamedTuple class syntax with attributes without type annotations

### ISSUE THREAD

**Issue by FichteFoll** [python/mypy#3959] opened 2017-09-15 04:23 UTC
The typing.NamedTuple class syntax only looks at the namespace's `__annotations__` when creating a named tuple, which means that any attribute without a type annotation is not considered to be a field:

https://github.com/python/typing/blob/5841d9ba4ee532c30be8fd13f23f88d0694ecdd5/src/typing.py#L2139-L2140

mypy, however, *does* consider these to be part of the fields and considers them to the function signature of the class's `__new__`. Additionally, it complains about attributes beginning with an underscore that don't have a type annotation, even though the typing module allows this (as they are not actually added as fields).

## Example

```py
from typing import NamedTuple


class MyTuple(NamedTuple):
    non_annotated_attr = True
    _non_annotated_attr_with_underscore = False

    a: str
    b: int = 1


print(MyTuple("x"))
print(MyTuple.__annotations__)
print(MyTuple._fields)
print(MyTuple._non_annotated_attr_with_underscore)
```

```
$ python test.py
MyTuple(a='x', b=1)
OrderedDict([('a', <class 'str'>), ('b', <class 'int'>)])
('a', 'b')
False

$ mypy test.py
test.py:5: error: Invalid statement in NamedTuple definition; expected "field_name: field_type [= default]"
test.py:6: error: NamedTuple field name cannot start with an underscore: _non_annotated_attr_with_underscore
test.py:6: error: Invalid statement in NamedTuple definition; expected "field_name: field_type [= default]"
test.py:12: error: Too few arguments for "MyTuple"
```

---

I cannot tell whether this should be considered a typing bug itself. I personally like that it is possible to set class attributes like this, just like you can define methods.
Either way, mypy should support what typing allows.

**Comment by JukkaL** [comment] 2017-09-15 09:20
This is by design in mypy. Mypy explicitly doesn't support defining attributes like this:

```py
test.py:5: error: Invalid statement in NamedTuple definition; expected "field_name: field_type [= default]"
test.py:6: error: NamedTuple field name cannot start with an underscore: _non_annotated_attr_with_underscore
test.py:6: error: Invalid statement in NamedTuple definition; expected "field_name: field_type [= default]"
```

@ilevkivskyi What do you think about this? Is this a `typing` bug? Attributes without annotations are treated like class attributes by `NamedTuple`, but `ClassVar[x]` annotations are not supported. For consistency, maybe `NamedTuple` should reject non-annotated attributes at runtime. However, it's not clear how these can be distinguished from methods -- a `callable()` check is an option. We could perhaps also support `ClassVar` annotations for declaring class-level attributes.

**Comment by ilevkivskyi** [comment] 2017-09-15 11:38
I think we should just stop torturing ``NamedTuple``s :-) They were designed to be relatively compact immutable classes with optionally few methods and a docstring. For everything else one could just use data classes, see [PEP 557](https://www.python.org/dev/peps/pep-0557/). In particular, there is a special section on ``ClassVar``.

Concerning ``typing`` I think this question appeared during the initial implementation of methods in ``NamedTuple``, but then IIRC we just decided that we can't prohibit _all_ wrong usage, and an error in mypy would be enough.

**Comment by JukkaL** [comment] 2017-09-15 12:44
Ok, let's close this. Mypy won't support the usage pattern, since it's something `NamedTuple` wasn't designed for.

**Closed by JukkaL** 2017-09-15 12:44 UTC
Labels: needs discussion

**Comment by FichteFoll** [comment] 2017-09-15 13:25
PEP 557 looks interesting, being more flexible and especially mutable. I'll resort to using a global or a function local for my purpose instead.

**Comment by gvanrossum** [comment] 2017-09-15 15:12
Honestly I think we should have more compatibility between mypy and typing here.

**Comment by KeynesYouDigIt** [comment] 2020-09-09 17:08
Could this be reopened? It's preventing us from using named tuples as they were designed.

**Comment by gvanrossum** [comment] 2020-09-09 17:30
Can you explain?
