### ISSUE TITLE
"Module has no attribute" when looping over modules

### ISSUE THREAD

**Issue by l0b0** [python/mypy#11085] opened 2021-09-10 01:23 UTC
**Bug Report**

Even if `first.att()` and `second.att()` both exist, `for module in [first, second]: module.att()` results in 'Module has no attribute "att"'.

**To Reproduce**

1. Go to an empty directory
1. Create two files first.py and second.py, both containing just `def att() -> None: pass`
2. Create test_both.py with the following contents:
   ```
   from . import first, second
   
   
   def test_both -> None:
       for module in [first, second]:
           module.att()
   ```
3. `touch __init__.py`
4. Run `mypy .`

**Expected Behavior**

This should pass type inspection.

**Actual Behavior**

```text
test_both.py:6: error: Module has no attribute "att"
Found 1 error in 1 file (checked 4 source files)
```

**Your Environment**

- Mypy version used: 0.910
- Mypy command-line flags: N/A
- Mypy configuration options from `mypy.ini` (and other config files): N/A
- Python version used: Python 3.9.6
- Operating system and version: Arch Linux

**Workaround**

Unravel the loop:

```python
from . import first, second


def test_first() -> None:
    first.att()


def test_second() -> None:
    second.att()
```

**Additional**

Pyright seems to resolve the type to `module: Union[first.py, second.py]`, which is an odd syntax. I don't know what the actual syntax for this would be.

_Update:_ Looks like this might be a dupe of https://github.com/python/mypy/issues/1741, which was [closed due to low priority](https://github.com/python/mypy/issues/1741#issuecomment-390039539). Would it be possible to bump the priority? :)

**Comment by AlexWaygood** [comment] 2022-03-31 11:01
Closing as a duplicate of #9841

**Closed by AlexWaygood** 2022-03-31 11:01 UTC
Labels: bug, topic-join-v-union
