### ISSUE TITLE
Mypy should ignore type conflict between consecutive '_' variable assignments.

### ISSUE THREAD

**Issue by gwk** [python/mypy#3077] opened 2017-03-29 18:13 UTC
The following is fairly typical tuple unpacking code.

```
t = (1, 1, 'a')
i, _, _ = t # error: Incompatible types in assignment (expression has type "str", variable has type "int")
```

Would it be reasonable for mypy to ignore the identifier `_`?

**Comment by kirbyfan64** [comment] 2017-03-29 19:07
Duplicate of #465.

**Closed** 2017-03-29 19:44 UTC
