### ISSUE TITLE
Mypy does not properly type return value of decorator when decorating class

### ISSUE THREAD

**Issue by Lunarmagpie** [python/mypy#13283] opened 2022-07-29 05:06 UTC
**Bug Report**

Same as title. The code example below shows a function being properly typed.

**To Reproduce**
This code produces the bug.

```python
class WorkedAsExpected:
    ...

def deco(a: Any) -> WorkedAsExpected:
    return WorkedAsExpected()

@deco
def function_test() -> None:
    ...

@deco
class ClassTest:
    ...

reveal_type(function_test)  # Revealed type is "test.WorkedAsExpected"
reveal_type(ClassTest)  # Revealed type is "def () -> test.ClassTest"

print(type(function_test))  # <class '__main__.WorkedAsExpected'>
print(type(ClassTest))  #<class '__main__.WorkedAsExpected'>
```

**Expected Behavior**

`reveal_type` should be the same type for the function and class examples. The function example is the expected result.

**Your Environment**

- Mypy version used: 0.971 (compiled: yes)
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): None
- Python version used: 3.8.12
- Operating system and version: 5.18.14-arch1-1

**Comment by JelleZijlstra** [comment] 2022-07-29 05:28
Duplicate of #3135.

**Closed by JelleZijlstra** 2022-07-29 05:28 UTC
Labels: bug
