### ISSUE TITLE
Overly permissive handling of Optional parameters

### ISSUE THREAD

**Issue by markshannon** [python/mypy#1366] opened 2016-04-12 17:03 UTC
According to MyPy, these two functions type check, but they shouldn't:
```
def f(arg:Optional[str])->str:
    return arg

def g(arg:Union[str, None])->str:
    return arg
```

This is (correctly) rejected:
```
def h(arg:Union[str, int])->str:
    return arg
```

**Comment by gvanrossum** [comment] 2016-04-12 17:36
Known issue. We're planning to work on this for the milestone after 0.3.2. Closing as dupe of #359.

**Closed by gvanrossum** 2016-04-12 17:36 UTC
