### ISSUE TITLE
reversed(Enum)

### ISSUE THREAD

**Issue by MeGotsThis** [python/mypy#3349] opened 2017-05-10 06:47 UTC
As a semi-continuation of #2891, using mypy 0.510.

```
import enum

class Letters(enum.Enum):
    A = 0
    B = 1

l: Letters

for l in Letters:
    print(l)
for l in reversed(Letters):
    print(l)
```

Running mypy gives this error
```
enum-test.py:11: error: Incompatible types in assignment (expression has type "Enum", variable has type "Letters")
```

Line 11 is the 2nd for loop.

**Comment by elazarg** [comment] 2017-05-10 08:37
Is it not precisely #3210 ?

**Comment by ilevkivskyi** [comment] 2017-05-10 09:49
It looks very similar, but I propose to keep this open, so that we will not forget to add this example to tests when fixing #3210.

**Comment by gvanrossum** [comment] 2017-09-20 03:12
Explain to me again why this is not a duplicate of #3210? If we want to remember to add both examples to the tests we can just add this example to #3210. E.g.
```py
from enum import Enum

class E(Enum):
    one = 1

reveal_type(list(E))  # 'builtins.list[enum.Enum*]'

reveal_type(reversed(E))  # 'typing.Iterator[enum.Enum*]'
```

**Comment by ilevkivskyi** [comment] 2018-02-13 15:52
All examples in this issue now work correctly on mypy master.

**Closed by ilevkivskyi** 2018-02-13 15:52 UTC
