### ISSUE TITLE
is_subtype is not separate from is_compatible_with

### ISSUE THREAD

**Issue by ddfisher** [python/mypy#2038] opened 2016-08-18 21:56 UTC
We currently do not distinguish subtype relations from compatibility relations.  This causes problems like #2031.  We should separate out subtyping from compatibility checks.

**Comment by JukkaL** [comment] 2016-09-30 09:06
There is `is_proper_subtype` which was intended as a real subtype check, but it's only partially implemented and it's apparently not used anywhere any more.

I'd recommend calling the function `is_compatible` instead of `is_compatible_with`, to be consistent with the current naming convention (for example, we have `is_subtype` instead of `is_subtype_of` or similar).

**Comment by JukkaL** [comment] 2017-05-02 15:04
`is_proper_subtype` is now a separate thing and used in various places, including in union simplification checks, so I'm closing this issue. If there are remaining issues we can create separate issues and refer to this as needed.

**Closed by JukkaL** 2017-05-02 15:04 UTC
Labels: priority-1-normal, refactoring
