### ISSUE TITLE
explicitly iterating over an enum class loses specialization

### ISSUE THREAD

**Issue by benjaminp** [python/mypy#5577] opened 2018-09-05 22:06 UTC
Consider this file:
```
import enum

class MyEnum(enum.Enum):
    pass

for x in MyEnum:
    reveal_type(x)
reveal_type(next(iter(MyEnum)))
```
I would expect both `reveal_type` calls to show the same type, but they don't:
```
$ mypy --version
mypy 0.620
$ mypy --python-version 2.7 enum_example.py 
enum_example.py:7: error: Revealed type is 'enum_example.MyEnum*'
enum_example.py:8: error: Revealed type is 'enum.Enum*'
```

**Comment by ilevkivskyi** [comment] 2018-09-05 22:14
Hm, I can't reproduce this on master, both show `enum_example.MyEnum*`. Maybe it is already fixed? (We will have 0.630 release in few days).

Could you please double check before closing? (We normally close issues fixed on master)

**Comment by benjaminp** [comment] 2018-09-05 22:28
Ah, sorry, I see. It's a Python 2 issue.
```
$ mypy --python-version 2.7 server/enum_example.py 
server/enum_example.py:7: error: Revealed type is 'enum_example.MyEnum*'
server/enum_example.py:8: error: Revealed type is 'enum.Enum*'
```
(Sorry, I had a `mypy.ini` I forgot about.)

**Comment by ilevkivskyi** [comment] 2018-09-05 22:32
Yes, I figured out that you forgot `--py2` :-)

This looks like a typeshed bug I think. The definition of `EnumMeta` in third party should skip explicit bases to get protocol inference, i.e. the stub in `third_party/2` should match the one in `stdlib/3`. I think @JelleZijlstra can help with this.

**Closed** 2018-09-27 16:27 UTC
