### ISSUE TITLE
Unexpected "Type application has too many types"

### ISSUE THREAD

**Issue by arnimarj** [python/mypy#12966] opened 2022-06-10 15:10 UTC
**Bug Report**

I'm not sure if this is related to https://github.com/python/mypy/issues/12211, but I have this simple example:

```python
from typing import Tuple, TypeAlias


class Foo:
	...


_A: TypeAlias = Foo | None | Tuple[str, str]
_B: TypeAlias = Foo | None | tuple[str, str]
_C = Foo | None | Tuple[str, str]
_D = Foo | None | tuple[str, str]
```

...which fails.

**To Reproduce**

Run the above using `mypy --strict alias.py`.

I tried both 0.961 and 0.970-dev using Python 3.10.5. I get these errors:
```shell
$ mypy --strict alias.py 
alias.py:9: error: Type application has too many types (1 expected)
alias.py:11: error: Type application has too many types (1 expected)
Found 2 errors in 1 file (checked 1 source file)
```
**Your Environment**

This was run on Ubuntu 22.04, Python 3.10.5, and mypy 0.961 and 0.970-dev

**Comment by AlexWaygood** [comment] 2022-06-12 20:51
Duplicate of #11098

**Closed by AlexWaygood** 2022-06-12 20:51 UTC
Labels: bug, topic-pep-604
