### ISSUE TITLE
mypy reports error when Enum 2nd arg is variable instead of literal

### ISSUE THREAD

**Issue by cppljevans** [python/mypy#8219] opened 2019-12-30 11:36 UTC
Please provide more information to help us understand the issue:

* Are you reporting a bug, or opening a feature request?

Reporting a bug.

* Please insert below the code you are checking with mypy,

from enum import Enum
Cs = 'C0 C1 C2'
Cn = Enum('Cn', Cs)

* What is the actual behavior/output?

simplest.py:3: error: Enum() expects a string, tuple, list or dict literal as the second argument

* What is the behavior/output you expect?

No errors

* What are the versions of mypy and Python you are using?

python3 --version
Python 3.6.9
mypy --version
mypy 0.560

* Do you see the same issue after installing mypy from Git
  master?
  
Did not try with Git master.  
  
* What are the mypy flags you are using? (For example --strict-optional)

No flags.

* If mypy crashed with a traceback

No crash.

**Comment by DevilXD** [comment] 2020-03-26 14:34
Pretty sure this is due to enums already being special-treated by MyPy, as they're classes that are generated dynamically, so static analysis for those is pretty much already impossible. The reason a literal (not variable) is expected there, is because with a literal, the "special treatment" of enums can somewhat check what members you have defined, and type check based on that. When you put in a variable there (even if it's a non-changeable literal at runtime), MyPy can't tell if the string you're passing in there has changed dynamically before or not (since all it knows is that "it's a string"), so type-checking it accurately is impossible.

I'd say this is working as intended.

**Comment by cppljevans** [comment] 2020-03-26 22:22
On 3/26/20 9:34 AM, DevilXD wrote:
> Pretty sure this is due to enums already being special-treated by MyPy,
> as they're classes that are generated dynamically, so static analysis
> for those is pretty much already impossible. The reason a literal (not
> variable) is expected there, is because with a literal, the "special
> treatment" of enums can somewhat check what members you have defined,
> and type check based on that. When you put in a variable there (even if
> it's a non-changeable literal at runtime), MyPy can't tell if the string
> you're passing in there has changed dynamically before or not (since all
> it knows is that "it's a string"), so type-checking it accurately is
> impossible.

IIUC, c++ can tell if a variable is a constexpr:

  https://en.cppreference.com/w/cpp/language/constexpr

and propagate that conexpr value to all the places that variable
is used. Now, I realize python is an interpreted language,
but surely something like mypy can analyze the code to
determine that a value of a variable has not changed since
it was initially assigned.  There's even a way to specify
that a python variable can never change it's value:


http://code.activestate.com/recipes/65207-constants-in-python/?in=user-97991

so, I'm not convinced that "type-checking it accurately is impossible".

[snip]

-regards,
Larry

**Comment by DevilXD** [comment] 2020-03-27 07:38
> IIUC, c++ can tell if a variable is a constexpr:

This is Python, not C++. Constants in C++ get evaluated and processed at compile time, and there's no such step for Python (the code is "sudo-compiled" right before running). There is no concept of constants in Python, and the only thing you really could do, is to mark a variable as [`typing.final`](https://docs.python.org/3/library/typing.html#typing.final) - but this only says the variable cannot be assigned to from that point onward, and does not guarantee it to be a literal.

I really doubt MyPy would be smart enough to figure out a complex class like in the example you linked, is made solely for the purposes of making constants, and I really doubt anyone maintaining the MyPy project wants to support constants as an idea. The problem here is that the `Cs = 'C0 C1 C2'` line gets an inferred type of `str`, not `Literal['C0 C1 C2']` (although you can mark it as such yourself easily), which is the source of the problem here.

Checking with MyPy, it does appear to ignore this too tho:
```py
from enum import Enum
Cs: Literal['C0 C1 C2'] = 'C0 C1 C2'
Cn = Enum('Cn', Cs)
```
I'm using the latest Git master. This is the thing that should be fixed instead.

**Comment by ethanhs** [comment] 2020-03-27 11:54
Mypy only does static analysis, so we definitely could do a Literal/Final value as the second argument to Enum. It should not be too hard to implement either.

**Comment by vincent-prz** [comment] 2020-04-07 17:32
Picking up this issue.

**Comment by vincent-prz** [comment] 2020-04-21 18:06
I opened this [PR](https://github.com/python/mypy/pull/8664), if someone wants to take a look.

**Closed** 2022-01-07 17:57 UTC
Labels: feature, priority-2-low, good-first-issue, topic-enum

**Comment by MestreLion** [comment] 2023-02-02 19:03
Duplicate of #5317 , which the PR also partially fixes
