### ISSUE TITLE
Generic function as first argument to map fails

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#3193] opened 2017-04-19 12:06 UTC
From https://github.com/python/typeshed/issues/1178:

> `map(tuple, [ [2, 3] ])` throws
>
> `error: Argument 1 to "map" has incompatible type Tuple[_T_co, ...]; expected Callable[[List[int]], Tuple[_T_co, ...]]`
>
> However, this is valid python code.

Here's a more self-contained example that reproduces the problem:

```py
from typing import Callable, TypeVar

T = TypeVar('T')
S = TypeVar('S')

def f(fn: Callable[[T], S], x: T) -> None: pass
def g(x: T) -> T: pass

f(g, 1)  # Argument 1 to "f" has incompatible type Callable[[T], T]; expected Callable[[int], T]
```

**Comment by ilevkivskyi** [comment] 2019-02-11 16:57
I think this is just a duplicate of https://github.com/python/mypy/issues/1317, passing one generic callable as an argument to another generic callable causes type variables leaking.

**Closed** 2019-02-11 16:57 UTC
Labels: bug, false-positive, priority-1-normal, topic-type-variables
