### ISSUE TITLE
Significant speed degradation from 0.931 to 0.941

### ISSUE THREAD

**Issue by brianmedigate** [python/mypy#12408] opened 2022-03-21 11:07 UTC
**Bug Report**

I upgraded from 0.931 to 0.941, and the time it takes to run a full run without a cache on my codebase increased from less than 2 minutes to almost 12 minutes.

I was surprised not to find any issues about this yet, maybe I'm just a relatively early adopter, or maybe something about my configuration or codebase is idiosyncratic, although nothing obvious that I can see.

**To Reproduce**

Not sure exactly how to give enough information to reproduce it, but let's just start with asking if you are aware of an expected performance regression in this version, and if so, if there are any known factors that exacerbate it.

**Your Environment**

Mypy 0.941 (appears to be the same on 0.940)
Python 3.8.10
Ubuntu 20.04.

An extract of the most salient parts of my configuration:
```ini
[mypy]
follow_imports = silent
ignore_missing_imports = True
check_untyped_defs = True
disallow_untyped_defs = True
no_implicit_optional = True
strict_equality = True
warn_redundant_casts = True
python_version = 3.8
platform = linux
plugins = pydantic.mypy
namespace_packages = True
```

My first suspect was the pydantic plugin but I removed it, to no effect.

**Comment by KotlinIsland** [comment] 2022-03-21 11:42
Can you verify that you are using a compiled wheel? run `mypy -v .` and look for:
`LOG:  Compiled:               True`

**Comment by KotlinIsland** [comment] 2022-03-21 13:31
The only other think I could recommend is to try some of the other 0.940+dev wheels here: https://github.com/mypyc/mypy_mypyc-wheels and see if you have any luck or can track down where about the slowdown started.

**Comment by JukkaL** [comment] 2022-03-21 13:38
This is the first report about a performance regression in 0.941 I remember hearing about, so it seems likely that something in your codebase specifically triggers the regression. 

@KotlinIsland's suggestion is a good one. You can also run `mypy -v` to get more verbose logging and see if most of the time is spent processing a specific module, or whether things are slower overall.

**Comment by twoertwein** [comment] 2022-03-21 15:41
Pandas did not see a slowdown: Pandas updated from 0.931 to 0.941 (and at the same time also updated pyright). I'm not certain how much variance there is between github action runs but [before](https://github.com/pandas-dev/pandas/runs/5594728220?check_suite_focus=true) mypy+pyright took 4m 27s and [afterwards](https://github.com/pandas-dev/pandas/runs/5601950216?check_suite_focus=true) 2m 35s.

**Comment by brianmedigate** [comment] 2022-03-22 14:28
Looks like it started being slow in this wheel: https://github.com/mypyc/mypy_mypyc-wheels/releases/tag/v0.940%2Bdev.6c1eb5b36b83ecf959a50100d282ca86186f470f.
Here is the relevant commit (to mypyc): https://github.com/python/mypy/commit/6c1eb5b36b83ecf959a50100d282ca86186f470f
And the commit message mentions:
> this slows down the richards benchmark by about 15%

Sounds like it might be relevant?
kudos to @JukkaL for the excellent commit message btw!

I ran with `--verbose`, and there was a visibly slow SSC of size 111 which took a couple minutes to process, and a couple of visibly slow singletons, but nothing obviously non-proportional to their speeds in the faster version.

Any advice on how to proceed?

**Comment by JukkaL** [comment] 2022-03-22 14:56
> Any advice on how to proceed?

I can see how that PR could affect performance a little, but over 5x performance loss is much worse than I'd expect. Can you double check a few additional wheels before/after the commit to get more confidence that this is the root cause?

Another idea would be to try running mypy on Python 3.10, and maybe on some different hardware, to investigate if the regression is repeatable or specific to certain configuration.

If the slowdown is consistent, I'd suggest profiling the mypy run to see whether there is some particular function causing the regressions, or whether things are slow overall. I can give instructions if you want to try this (it's not difficult).

As mentioned in the commit message, the "always-defined attributes" optimization could help with performance. I have this close to ready for merging. I could focus on getting it finished, and perhaps you could check performance with this optimization. This will probably take at least one or two weeks, however.

**Comment by brianmedigate** [comment] 2022-03-23 13:11
I tried to find a subset of my code which takes a disproportionate amount of time, but unfortunately it is very interconnected, so it's difficult to tease the parts apart. So far I didn't find anything obviously disproportionate.

**Comment by KotlinIsland** [comment] 2022-03-23 14:39
Is the code public? I'm pretty comfortable minifying issues and would be happy to lend a hand.

**Comment by brianmedigate** [comment] 2022-03-23 14:46
Unfortunately no, sorry

**Comment by bersbersbers** [comment] 2022-03-24 19:17
I'd like to mention a potentially related issue here (https://github.com/python/mypy/issues/12225). I first noticed it in 0.931, and it certainly hasn't gotten any better with 0.940. I regularly have to clean my `mypy` cache due to this, maybe that is related and explains why people are having trouble reproducing it.

**Comment by JukkaL** [comment] 2022-03-28 14:34
@brianmedigate @bersbersbers I wrote a wiki page about how to profile compiled mypy. Currently I've only verified that the instructions work in Linux, though: https://github.com/python/mypy/wiki/Profiling-Mypy 

If you can submit profiles collected from both an older (good) mypy version and the latest mypy version, I can have a look at the them.

**Comment by brianmedigate** [comment] 2022-03-28 16:41
Will do, thanks!

**Comment by brianmedigate** [comment] 2022-03-29 10:54
Here are profiles from 0.931 and 0.942 on the same codebase, with no cache:
[profile.tar.gz](https://github.com/python/mypy/files/8370611/profile.tar.gz)

**Comment by bersbersbers** [comment] 2022-03-29 11:00
@JukkaL thanks! I finished profiling the comparisons between 0.942 and 0.931 with no difference in runtime, so this does not appear to be regression (and you will not gain any insight by that comparison). I will use your suggestions to post similar results at #12225 to help investigate that root cause.

**Comment by JukkaL** [comment] 2022-03-30 15:19
@brianmedigate Thanks for the profiles! The regression is clearly visible, but I have no idea how #11940 might have caused this. However, a few other commits look suspicious. 

To move forward, there are few things that could help:
* Collect profiles for https://github.com/python/mypy/commit/6c1eb5b36b83ecf959a50100d282ca86186f470f and the previous commit using wheels from https://github.com/mypyc/mypy_mypyc-wheels. This could confirm the source of the regression.
* Collect profiles also using the non-compiled wheel (`...-py3-none-any.whl`) using the before/after commits, to see whether the regression is specific to compiled mypy. If it reproduces using interpreted mypy, the regression should be easier to debug.

**Comment by JukkaL** [comment] 2022-03-30 15:22
Based on the profile, I suspect that the regression is related to enum types. It may be due to an enum type with a large number values causing large unions with literal types that result in extreme slowdown due to O(n**2) or worse algorithms in mypy. Alternatively, it might be caused by a large union of literal types.

**Comment by brianmedigate** [comment] 2022-03-31 10:17
Here are the profiles: [profile.tar.gz](https://github.com/python/mypy/files/8388133/profile.tar.gz)

Interesting that you mention enums. We do indeed make pretty heavy use of enums. Most of our enums are pretty small (under 10 elements), but we have a couple pretty large enums (with a couple of hundred elements each). I tried commenting out most of the elements of the larger ones, and it indeed helps a lot, but only by a factor of 2 or so (still 3 times slower than 0.930). That doesn't quite align with the whole slowdown being caused by something quadratic or worse, but maybe part of it. If I run mypy just on the files containing the large enums themselves, I get a more dramatic improvement (22 seconds to 3 seconds), but that might also be just caused by the fact that a significant chunk of the lines are commented out.

It might be worthwhile to note that we do some pretty unusual things with subclasses of enums, in order to do things like add methods, assign metadata to each element, support parsing/validation and serialization mechanisms, etc. Maybe of particular interest here: in 0.940 mypy started complaining about a case of diamond enum inheritance, which I `#type: ignore`d. Removing the diamond inheritance doesn't speed things up much, but if something significant changed around how enums are handled, that could maybe explain the idiosyncrasy of our codebase.

**Comment by JukkaL** [comment] 2022-03-31 13:55
@brianmedigate Thanks for the additional profiles! 

I can see the regression also in the non-compiled profile, so the mypyc change is almost certainly not causing this. Could you also try profiling commit 48d810d5ed25f898d4f220a7476b6b267c289b9a? It seems like it could be the root cause. Feel free to only collect the profile using either compiled or interpreted mypy. If we can narrow this down to that particular commit, there might some performance improvements I can implement (or we might want to revert the commit).

**Comment by brianmedigate** [comment] 2022-03-31 15:59
Awesome, nice work!

**Comment by JukkaL** [comment] 2022-04-06 14:36
@brianmedigate Can you double check if the regression has been fixed in the latest GitHub master? Hopefully #12526 helped.

**Comment by brianmedigate** [comment] 2022-04-06 22:16
It's better, but still significantly slower than it was before. Around 7 and a half minutes. Here's the profile:
[profile.tar.gz](https://github.com/python/mypy/files/8433230/profile.tar.gz)

**Comment by JukkaL** [comment] 2022-04-07 18:19
@brianmedigate I landed several additional optimizations. It would be great if you can check 222029b07e0fdcb3c174f15b61915b3b2e1665ca, or a more recent commit. (It will be a few hours at least from now before the wheels are ready.)

**Comment by JukkaL** [comment] 2022-04-08 07:34
@brianmedigate Just to let you know that the wheels were built and are now up-to-date.

**Comment by brianmedigate** [comment] 2022-04-08 10:08
Down a bit more, to just under 7 minutes

**Comment by JukkaL** [comment] 2022-04-08 13:05
The only remaining relatively low-hanging fruit that I see as somewhat likely to help would be the caching of `make_simplified_union` results (more detail in https://github.com/python/mypy/issues/12225#issuecomment-1092825269).

There's also a workaround that you might be able to implement fairly easily in your codebase. Replacing `e.value` calls with `str(e.value)` calls, when `e` has an enum type which has many items, might speed up mypy runs. Even if this isn't an acceptable long-term solution, if you manage to use this to speed up mypy runs, this may help you find a short fragment of code that reproduces the slowdown, making it easier to investigate.

**Comment by brianmedigate** [comment] 2022-04-10 06:59
Unfortunately it's an enum which is used widely throughout the codebase, and the code which does `.value` is also scattered around, and is often deep within a database or serialization layer, so there isn't a convenient way to do that, even as a short-term fix.

I thought about somehow making the enum not an enum, i.e. implementing my own enum metaclass (or even vendoring EnumMeta and changing its name or something) in order to get the runtime behavior of an enum without mypy knowing that it's an enum.

Or maybe it would it be possible to implement a way to somehow mark that enum in order to "opt out" of https://github.com/python/mypy/commit/48d810d5ed25f898d4f220a7476b6b267c289b9a for the offending enum? Or in general a way of explicitly giving up accuracy of checks in order to optimize? It might be a bit of a rabbit hole philosophically for mypy to start making things like that configurable, but it would basically be a cleaner way to achieve "making it an enum without being an enum".

**Comment by brianmedigate** [comment] 2022-04-10 07:07
Hmm, making it not an enum didn't work, which makes sense now that I think about it, because I lost all of the semantics of enums in mypy, and it just thought the elements were literal values rather than instances of the class.

**Comment by brianmedigate** [comment] 2022-04-14 09:11
I was able to just rip out the huge enum and replace it with a class containing constants, without too much damage. Together with your optimizations, the runtime is back down to approximately where it was on 0.930. As far as I'm concerned, this is a stable steady-state; once the next version of mypy is published to pypi I can upgrade.

**Closed** 2022-05-01 23:11 UTC
Labels: bug, performance
