### ISSUE TITLE
`--strict-abstract` to prevent classes that cannot be instantiated

### ISSUE THREAD

**Issue by graingert** [python/mypy#3705] opened 2017-07-12 15:17 UTC
can we get https://github.com/JelleZijlstra/mypy/commit/1fa9c65ea9db9d9024556002e39ab58b5c33997c in mypy for real?

maybe with `--strict-abstract` and fixed with a decorator in mypy_extensions:

```python
@mypy_extensions.abstract
class IncrementalNewlineDecode(???):
    pass
```

"error: Class io.IncrementalNewlineDecode must implement base members ['decode'] or be declared abstract"

**Comment by ilevkivskyi** [comment] 2017-07-12 15:25
I remember we discussed with Jukka ``--strict-implementations`` in the context of protocols, and the decision was not to do this. Mostly because we already have so many flags.

However, the idea with decorator might work (one can call it ``mypy_extensions.ensure_non_abstract`` and emit errors even without the new flag).

**Comment by graingert** [comment] 2017-07-12 15:42
Sounds like you'd have to add ensure_non_abstract to every class

**Comment by gvanrossum** [comment] 2017-07-12 15:43
I think this would be most important for typeshed, but there we should be careful to use something that doesn't upset other users of typeshed stubs, e.g. PyCharm or pytype.

I wonder if a simple solution, requiring no new decorators etc., wouldn't be to just create an instance in the stub (and throw it away). E.g.
```py
class IncrementalNewlineDecode(...):
    pass
IncrementalNewlineDecode()
```
That last line will get an error if the class is abstract.

**Comment by graingert** [comment] 2017-07-12 15:52
@gvanrossum that's the opposite behaviour that I want. I don't want to add extra code for classes intended to be non-abstract.

**Comment by graingert** [comment] 2017-07-12 15:54
the abstract decorator should be typed T -> T and return its arg unchanged, so should not alter the behavior of pytype or PyCharm.

**Comment by JelleZijlstra** [comment] 2017-07-12 16:04
This is basically a duplicate of #3692.

**Comment by gvanrossum** [comment] 2017-07-12 16:04
OK, now I understand (your initial comment was rather cryptic). However I don't think it's much of a priority for the core mypy team.

**Comment by gvanrossum** [comment] 2017-07-12 16:05
Closing as dup.

**Closed by gvanrossum** 2017-07-12 16:05 UTC
