### ISSUE TITLE
Mypy doesn't catch error due to using attribute befor defining it 

### ISSUE THREAD

**Issue by h8hawk** [python/mypy#7756] opened 2019-10-20 16:51 UTC
Consider this code: 

```
from typing import List

class Foo:

    def __init__(self) -> None:
        self.bar()
        self.foo: List[int] = []

    def bar(self) -> None:
        self.foo.append(3)

if __name__ == "__main__":
    foo = Foo()
```

Following code raise `AttributeError` but Mypy consider it valid:
```
$ mypy foo.py --strict
Success: no issues found in 1 source file
```

**Comment by ilevkivskyi** [comment] 2019-10-20 17:01
I think this is essentially a duplicate of https://github.com/python/mypy/issues/4019

**Closed by ilevkivskyi** 2019-10-20 17:01 UTC
