### ISSUE TITLE
Allow --filename with --command

### ISSUE THREAD

**Issue by Kronuz** [python/mypy#5267] opened 2018-06-23 15:46 UTC
### Feature Request

Allow passing a file name when using `--command`, so the tool can be used as an editor linter receiving a possibly user-modified file content *and* its file name so the base directory gets properly resolved.

**Comment by JelleZijlstra** [comment] 2018-06-23 15:56
The `--shadow-file` option is close to what you want, but does require having the file available on disk somewhere.

**Comment by ethanhs** [comment] 2018-06-23 15:59
I agree with Jelle, you almost certainly want `--shadow-file`.

Closing as a duplicate of #2119.

**Closed by ethanhs** 2018-06-23 15:59 UTC

**Comment by Kronuz** [comment] 2018-06-23 17:06
This isn’t the same as `--shadow-file`, although we might certainly reuse the argument name, as it currently is, it’s incomplete; it needs to also set the base directory which `--shadow-file` doesn’t seem to be doing, so it can find relative imports.

This is an example of the missing implementation: https://github.com/Kronuz/mypy/commit/09733a74117d2c33c180bd376062f378e13b3f98#diff-b5e3909c86f7834f70af20bb848acec3R662 ...note line 664, where `base_dir` is configured, for local imports.

I beg you reopen the issue.
