### ISSUE TITLE
Optional[T] in {None,...} does not drop the Optional

### ISSUE THREAD

**Issue by Carreau** [python/mypy#8787] opened 2020-05-07 20:07 UTC
On latest mypy; of course the code can use `if not var:` which would have the same effect.

```
$ cat foo.py
import os

var = os.environ.get('ENV')
if var in {None, ''}:
    var = 'default'
else:
    var =  var.lower()
```

```
$ mypy foo.py
foo.py:7: error: Item "None" of "Optional[str]" has no attribute "lower"
Found 1 error in 1 file (checked 1 source file)
```

```
$ mypy --version
mypy 0.770+dev.2d06ba71aa087e8d8a6eb4a37bb9a6254f7dbb70
```

Thanks

**Comment by EkanshMangal** [comment] 2020-05-07 20:57
Hello Sir
Can i fix this issue?

**Comment by Carreau** [comment] 2020-05-07 21:05
Hi @EkanshMangal, 

I see there is a [Contributing file on this repository](https://github.com/python/mypy/blob/master/CONTRIBUTING.md) I would suggest starting there for instructions.

**Comment by AlexWaygood** [comment] 2022-04-04 16:06
Closing as a duplicate of #10977, which is a newer issue but has a lot more discussion attached to it.

**Closed by AlexWaygood** 2022-04-04 16:06 UTC
Labels: feature, topic-type-narrowing
