### ISSUE TITLE
Add "--use-stdin" 

### ISSUE THREAD

**Issue by kirbyfan64** [python/mypy#3553] opened 2017-06-15 22:47 UTC
Right now I'm trying to add mypy support to [Howl](http://howl.io/), and it's been...*interesting*, to say the least!

The main obstacle I've run into is what to do with files that haven't been saved yet. Right now, I'm writing unsaved files to a temporary file (say `/tmp/foo.py`) and then running mypy on the temporary, but this falls apart when using relative imports.

I think I have a simple solution, though: `--use-stdin`. This would work like so:

```
$ echo the_unwritten_contents | mypy --use-stdin x.py
```

Mypy will use the contents of `sys.stdin` for `x.py`. And...that's all. It's like running mypy on an actual file, but using different contents for it.

Thoughts?

**Comment by ethanhs** [comment] 2017-06-15 23:00
I don't see how this would solve issues with relative imports. Mypy would still follow imports in the source of the file, no? I believe most IDEs store temp copies of files anyway, in case of crashes etc. Also, I have considered suggesting that the api take sources in as StringIO/str in the past, for greater flexibility of input.

**Comment by ddfisher** [comment] 2017-06-15 23:41
I think the hidden `--shadow-file` option might work here.
```
    # --shadow-file a.py tmp.py will typecheck tmp.py in place of a.py.
    # Useful for tools to make transformations to a file to get more
    # information from a mypy run without having to change the file in-place
    # (e.g. by adding a call to reveal_type).
```

**Comment by kirbyfan64** [comment] 2017-06-16 00:03
@ddfisher Oh wow...is there a reason it's hidden?

**Comment by ddfisher** [comment] 2017-06-16 00:05
It's hidden because it's only really for tool writers, and it didn't seem worthwhile for it to appear in the general `--help`.  It'd probably be good if it was actually in the docs somewhere, though. >_>

**Comment by gvanrossum** [comment] 2017-06-16 22:19
I think it needn't be hidden.

**Comment by kirbyfan64** [comment] 2017-06-16 22:48
As a side note, what if `--shadow-file` could take `-` as the shadowing file, in order to read from stdin? Again, it would make it a lot easier to avoid a temporary.

**Comment by ethanhs** [comment] 2017-06-26 17:00
Btw, this is a dupe of #2119. Looks like that might be resolved soon.

**Comment by kirbyfan64** [comment] 2017-06-26 20:52
Ohhh...oops...

**Comment by gvanrossum** [comment] 2017-06-26 21:51
Can we close this then?

**Comment by kirbyfan64** [comment] 2017-06-26 22:34
Haha, sorry, I meant to hit *Close and comment* but missed...

**Closed** 2017-06-26 22:34 UTC
