### ISSUE TITLE
isinstance operator type check incorrect

### ISSUE THREAD

**Issue by thehesiod** [python/mypy#7379] opened 2019-08-22 02:51 UTC
* Are you reporting a bug, or opening a feature request?
Buy

* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.
```python
        if isinstance(first_choice, (str, int, float, Decimal)):
            first_choice = first_choice + first_choice
```

* What is the actual behavior/output?
```
schema.py:213:29: T484 Unsupported operand types for + ("str" and "float")
schema.py:213:29: T484 Unsupported operand types for + ("str" and "Decimal")
schema.py:213:29: T484 Unsupported operand types for + ("float" and "str")
schema.py:213:29: T484 Unsupported operand types for + ("float" and "Decimal")
schema.py:213:29: T484 Unsupported operand types for + ("Decimal" and "str")
schema.py:213:29: T484 Unsupported operand types for + ("Decimal" and "float")
schema.py:213:29: T400 note: Both left and right operands are unions
```

* What is the behavior/output you expect?
Should pass as any one of these types can be appended to itself.

* What are the versions of mypy and Python you are using?
```
Python 3.6.6
flake8-mypy              17.8.0    
mypy                     0.720     
mypy-extensions          0.4.1 
```

* What are the mypy flags you are using? (For example --strict-optional)
flake8 with config:
```
[mypy]
follow_imports = True
cache_dir = /tmp/flake8_mypy
warn_redundant_casts = True
warn_unused_ignores = True
```

**Comment by ilevkivskyi** [comment] 2019-08-22 18:27
This is a duplicate of https://github.com/python/mypy/issues/6478

**Closed by ilevkivskyi** 2019-08-22 18:27 UTC
