### ISSUE TITLE
mypy doesn't narrow type upon assignment

### ISSUE THREAD

**Issue by rhshadrach** [python/mypy#9486] opened 2020-09-25 20:35 UTC
Example:

```
def foo():
    x: Union[str, Dict[str, str]] = {}
    x["a"] = "b"
```

mypy reports `error: Unsupported target for indexed assignment ("Union[str, Dict[str, str]]")`.

Should mypy be able to narrow the type here to realize the assignment is okay? While the function may seem odd, this occurs when you have a long alias where the outer type is a union, e.g.:

```
AggFuncType = Union[
    AggFuncTypeBase,
    List[AggFuncTypeBase],
    Dict[Label, Union[AggFuncTypeBase, List[AggFuncTypeBase]]],
]
```

To solve, one can either add an assert/cast or also alias the inner type. But I was surprised mypy didn't do it automatically, so I thought I'd ask.

**Comment by hauntsaninja** [comment] 2020-09-25 20:39
mypy will accept:
```
def foo() -> None:
    x: Union[str, Dict[str, str]]
    x = {}
    x["a"] = "b"
```

I agree that there being a difference here is surprising. There are a couple issues open about it, as well as a long recent thread in typing-sig.

**Comment by gvanrossum** [comment] 2020-09-26 00:09
So let's call this a duplicate of #2008. I think we should bite the bullet and change mypy so that there's no difference between the two.

**Closed by gvanrossum** 2020-09-26 00:09 UTC
Labels: bug
