### ISSUE TITLE
Cyclic Definition Error for TypedDict

### ISSUE THREAD

**Issue by csenn** [python/mypy#9831] opened 2020-12-22 13:25 UTC
**Bug Report**

I am trying to generate type checking according to a json schema definition.

This issue may be related to [731](https://github.com/python/mypy/issues/731)?

Since I'm using **total=False**, I believe this is a bug?  Also very open to any alternate implementation suggestions :)

**To Reproduce**

```
from typing_extensions import TypedDict

A = TypedDict("A", { "id": B }, total=False)

B = TypedDict("B", { "id": A }, total=False)

a_instance: A = {
    "id": {
        "id": {
            "id": {}
        }
    }
}
```

Also trying using [forward references](https://mypy.readthedocs.io/en/latest/kinds_of_types.html#class-name-forward-references)

```
from typing_extensions import TypedDict

A = TypedDict("A", { "id": "B" }, total=False)

B = TypedDict("B", { "id": "A" }, total=False)

a_instance: A = {
    "id": {
        "id": {
            "id": {}
        }
    }
}
```

**Expected Behavior**
a_instance should be valid 

**Actual Behavior**

Errors
```
test2.py:4: error: Cannot resolve name "B" (possible cyclic definition)
Found 1 error in 1 file (checked 1 source file)
```

**Your Environment**
- mypy 0.790

**Comment by gvanrossum** [comment] 2020-12-22 18:26
This is just a duplicate of #731.

**Closed by gvanrossum** 2020-12-22 18:26 UTC
Labels: bug
