### ISSUE TITLE
Show closest candidates for misspellings

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#824] opened 2015-08-19 20:57 UTC
Instead of just saying `"foobar" undefined` try to look for closest candidates (using edit distance, for example) and give suggestions. For example: `"get_stats" undefined, did you mean "getstats"?`.

**Comment by JukkaL** [comment] 2015-08-19 20:58
This would be useful for at least these things:

* Attribute lookups
* Keyword argument names
* Module imports

**Comment by JukkaL** [comment] 2015-08-23 22:56
There is basic support for attribute lookups in the `hack` branch.

**Comment by JelleZijlstra** [comment] 2017-07-01 19:19
This is done for attribute lookups, but not for the other things Jukka mentions.

**Comment by marcodoordash** [comment] 2019-05-06 15:55
#4934 adds more details and use cases to the **Module imports** part of this issue, pasting those here and closing it as a duplicate of this one.

`Mypy can suggest correct spellings for some attributes, but it doesn't seem to work for module attributes:

```
from subprocess import popen  # Module 'subprocess' has no attribute 'popen'

import subprocess
subprocess.popen  # Module has no attribute "popen"

class Foobar:
    def do_it(self): pass
foobar  # Name 'foobar' is not defined

Foobar().doit()  # "Foobar" has no attribute "doit"; maybe "do_it"?
```
It would be better if mypy would suggest corrections for all of the cases in the above example.`

**Comment by marcodoordash** [comment] 2019-05-06 15:58
looking at this one

**Comment by Wuisch** [comment] 2019-11-05 22:11
I took a shot at the keyword argument name case. Comments are welcome.

**Comment by ilevkivskyi** [comment] 2019-11-23 23:18
This is now fully implemented.

**Closed by ilevkivskyi** 2019-11-23 23:18 UTC
Labels: feature, good-first-issue, priority-1-normal, topic-usability
