### ISSUE TITLE
Variable `typing_extensions.OrderedDict` is not valid as a type

### ISSUE THREAD

**Issue by KotlinIsland** [python/mypy#11528] opened 2021-11-12 01:04 UTC
```py
from typing_extensions import OrderedDict

a: OrderedDict[str, str] = {}  # error: Variable "typing_extensions.OrderedDict" is not valid as a type

class A(OrderedDict[str, str]):  #  error: Invalid base class "OrderedDict"
    ...
```
mypy 0.920+dev.6b9cc4774f7dbd556a655071800a8e17e368282b

**Comment by sobolevn** [comment] 2021-11-12 12:52
This line might be the root cause: https://github.com/python/typeshed/blob/59408d9c9cd1d25e4083707893a1b2f2965c2c0a/stdlib/typing_extensions.pyi#L72-L74

I will try to fix it.

**Comment by sobolevn** [comment] 2021-11-12 12:58
Yes, this code fixes this issue:

```
if sys.version_info < (3, 9):
    from typing import OrderedDict as OrderedDict
else:
    import collections

    class OrderedDict(
        collections.OrderedDict,
        typing.MutableMapping[_T, _KV],
    ):
        ...if sys.version_info < (3, 9):
    from typing import OrderedDict as OrderedDict
else:
    import collections

    class OrderedDict(
        collections.OrderedDict,
        typing.MutableMapping[_T, _KV],
    ):
        ...
```

This is a `typeshed` issue. I will open a PR there, feel free to close this issue!

Thanks for the report 👍 
You have contributed a lot of great bug reports!

**Comment by sobolevn** [comment] 2021-11-12 13:01
Or maybe it is not a typeshed issue 🤔 

Because all other types are also `_Alias()`. But, they work just fine, because `mypy` has special treament for them.
I need some more research.

**Comment by sobolevn** [comment] 2021-11-12 13:37
Yes, this is solvable on mypy's side 👍

**Closed** 2021-11-14 03:14 UTC
Labels: bug
