### ISSUE TITLE
Namedtuple subclasses with class variables confuse mypy

### ISSUE THREAD

**Issue by albertodonato** [python/mypy#5944] opened 2018-11-23 14:58 UTC
When defining a `NamedTuple` subclass with type annotation, if the class contains class variables or properties, mypy thinks they are tuple elements.
For example the following code:

```
from typing import NamedTuple


class MyTuple(NamedTuple):

    a: str
    b: int

    c = property(lambda self: f'{self.a} {self.b}')

    _foo = 'some class variable'


assert MyTuple('foo', 3).c == 'foo 3'
```
yields the following errors:

```
$ mypy sample.py
sample.py:9: error: Invalid statement in NamedTuple definition; expected "field_name: field_type [= default]"
sample.py:11: error: NamedTuple field name cannot start with an underscore: _foo
sample.py:11: error: Invalid statement in NamedTuple definition; expected "field_name: field_type [= default]"
sample.py:14: error: Too few arguments for "MyTuple"
```

even if the code itself works.
Tested with mypy 0.641.

In case it might be relevant, I'm usingthe following config:
```
[mypy]
incremental = False
warn_return_any = True
warn_unused_configs = True
ignore_missing_imports = True
```

**Comment by JelleZijlstra** [comment] 2018-11-23 16:33
Your code also throws an error at runtime: `TypeError: NamedTuple('Name', [(f0, t0), (f1, t1), ...]); each t must be a type Got typing.ClassVar[str].` (tested in 3.6.4 and 3.7.0), so this needs to be fixed in `typing` first.

However, we're unlikely to add more complicated features to `typing.NamedTuple`; you should probably use dataclasses instead.

**Comment by albertodonato** [comment] 2018-11-23 16:45
@JelleZijlstra Ah, that's caused by the `ClassVar` it seems. Removing it makes it work. I had added it to try to make mypy accept it but it doesn't seem to make a difference.

**Comment by albertodonato** [comment] 2018-11-23 16:47
This is the updated mypy error output after removing the `ClassVar`:

```
$ mypy sample.py
sample.py:9: error: Invalid statement in NamedTuple definition; expected "field_name: field_type [= default]"
sample.py:11: error: NamedTuple field name cannot start with an underscore: _foo
sample.py:11: error: Invalid statement in NamedTuple definition; expected "field_name: field_type [= default]"
sample.py:14: error: Too few arguments for "MyTuple"
```

**Comment by ilevkivskyi** [comment] 2018-11-23 16:52
Duplicate of https://github.com/python/mypy/issues/5613, still low priority, better use dataclasses, as suggested above.

**Closed by ilevkivskyi** 2018-11-23 16:52 UTC
