### ISSUE TITLE
Type checking using `type` handled differently than `isinstance`

### ISSUE THREAD

**Issue by NickHackman** [python/mypy#9664] opened 2020-10-30 03:49 UTC
**Bug Report**

Type checking using `type(variable)` isn't properly being interpreted by Mypy in analysis.
I understand that `isinstance` is the more pythonic method for type checking, but that doesn't exclude that `type` is a valid way to do so. I'm not exactly sure how `isintance` is treated, but type should be treated in the same manner if possible.

**To Reproduce**

```python
ffrom typing import Union
import sys

def test() -> Union[str, int]:
    if True:
        return 'hello'
    return 2


result = test()
if type(result) == 'int':
    print(30 /  result)
    sys.exit(0)

print(result + ', hi')
```

**Expected Behavior**

No errors

**Actual Behavior**

```text
test.py:11: error: Unsupported operand types for / ("int" and "str")
test.py:11: note: Right operand is of type "Union[str, int]"
test.py:13: error: Unsupported operand types for + ("int" and "str")
test.py:13: note: Left operand is of type "Union[str, int]"
Found 2 errors in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: 0.782
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): None
- Python version used: 3.8.5
- Operating system and version: Linux nixos 5.8.14 x86_64 GNU/Linux

Sorry if this is a duplicate! Searching for `type` in Mypy makes it hard to find others.

**Comment by JelleZijlstra** [comment] 2020-10-31 00:12
This is a duplicate of #4445 (I don't fault you for not finding it, took me a while just now).

**Closed by JelleZijlstra** 2020-10-31 00:12 UTC
Labels: bug
