### ISSUE TITLE
Incompatible definition between base classes

### ISSUE THREAD

**Issue by squiddy** [python/mypy#2377] opened 2016-10-29 07:18 UTC
Sorry for the rather vague title, but I can't put it more precise. Find below a code example, I tried to keep it relevant for my use case. Note that, while the code shown is python3, the actual usage is in python2. Both versions behave identical though.

``` python
class Window:
    """
    Base class for all elements that act like windows, can be shown and hidden.
    """
    def show(self, **kwargs):
        # this is supposed to be implemented by subclasses
        raise NotImplementedError


class SpecialWidget:
    """
    Widget that shows things, like a table that is updated.
    """
    def show(self):
        # setup gui elements
        pass

    def update_things(self):
        pass


class FooWindow(SpecialWidget, Window): # <-- E: Definition of "show" in base class "SpecialWidget" is incompatible with definition in base class "Window"
    """
    A window that uses the GUI setup of SpecialWidget.
    """
    def update_things(self):
        pass
```

I fully understand the error, however, I'm at a loss on what to do about it. Obviously I could add `**kwargs` to `Specialwidget.show`, that gets rid of the error. But I don't really want to do that.

I tried to add my own `show` implementation in `FooWindow`:

``` python
    def show(self):
        SpecialWidget.show(self)
```

But that doesn't work. I also tried to have mypy ignore the definitions:

``` python
    def show(self): # type: ignore
        # setup gui elements
        pass
```

But that doesn't seem to be working either.

I'd appreciate any pointers, be it help with ignoring the error, fixing it or refactoring the code to avoid this issue.

**Comment by gvanrossum** [comment] 2016-10-29 15:13
I think this is a dupe of #1237. But I'm surprised the `# type: ignore` doesn't work.

**Comment by JukkaL** [comment] 2017-01-16 10:47
This gets rid of the error for me (the comment needs to be on the line where the error is reported):

```
class FooWindow(SpecialWidget, Window): # type: ignore
```

Closing this issue for now; feel free to reopen is this still doesn't address your issue.

**Closed by JukkaL** 2017-01-16 10:47 UTC
