### ISSUE TITLE
mypy should require the optional type to be made explicit.

### ISSUE THREAD

**Issue by vivodi** [python/mypy#12878] opened 2022-05-27 08:45 UTC
**Bug Report**

Quoted from [PEP 484](https://peps.python.org/pep-0484/#union-types:~:text=A%20past%20version,be%20made%20explicit.):
> A past version of [this PEP](https://peps.python.org/pep-0484/#union-types) allowed type checkers to assume an optional type when the default value is None, as in this code:
> 
> ```python
> def handle_employee(e: Employee = None): ...
> ```
> This would have been treated as equivalent to:
> ```python
> def handle_employee(e: Optional[Employee] = None) -> None: ...
> ```
> This is no longer the recommended behavior. Type checkers should move towards requiring the optional type to be made explicit.

**To Reproduce**

1. input the code snippet:
   ```python
   def handle_employee(e: Employee = None): ...
   ```
2. run `mypy handle_employee.py`

**Expected Behavior**

mypy show a warning or an error like this:
```
error: Incompatible default for argument "e" (default has type "None", argument has type "Employee")
```
**Actual Behavior**

No warning or error is given.

**Your Environment**

- Mypy version used: 0.960
- Mypy command-line flags: no flag
- Mypy configuration options from `mypy.ini` (and other config files): I don't set it.
- Python version used: 3.10.4
- Operating system and version: Windows 11

**Comment by AlexWaygood** [comment] 2022-05-27 11:54
Duplicate of #9091

**Closed by AlexWaygood** 2022-05-27 11:54 UTC
Labels: bug
