### ISSUE TITLE
RecursionError while type checking a class with __getattr__

### ISSUE THREAD

**Issue by jreese** [python/mypy#5171] opened 2018-06-08 06:44 UTC
#Running `mypy --python-version 3.6 --show-traceback` on https://github.com/jreese/edi/blob/master/edi/bot.py#L112 results in a recursion error, presumably related to the use of a class that implements `__getattr__` to return instances of the same class: https://github.com/jreese/edi/blob/master/edi/config.py#L16.

* What are the versions of mypy and Python you are using?  mypy 0.600, python 3.6.5
  Do you see the same issue after installing mypy from Git master?  n/a

traceback: https://gist.github.com/jreese/7a8ceda98cec9e36a2c518d43f4def41

Edit:
self-contained repro code and matching traceback: https://gist.github.com/jreese/244de892e5921791a5f28a2c0bede919

**Comment by ethanhs** [comment] 2018-06-08 06:53
That is rather unfortunate. Would you be able to come up with a more minimal reproduction of the issue per chance?

**Comment by ilevkivskyi** [comment] 2018-06-08 10:08
> That is rather unfortunate. Would you be able to come up with a more minimal reproduction of the issue per chance?

Before that could you please paste the full traceback? In looks like the one in the gist is cropped (normally recursion error tracebacks are very long).

**Comment by jreese** [comment] 2018-06-08 17:46
As far as I can tell, that is the full traceback (I piped it to a file and copy-pasted everything there).  I'll see if I can find a minimal repro.

**Comment by jreese** [comment] 2018-06-08 18:21
I have a self-contained repro, including matching traceback: https://gist.github.com/jreese/244de892e5921791a5f28a2c0bede919

**Comment by JelleZijlstra** [comment] 2018-06-08 18:59
Confirmed the crash on master. The traceback is indeed surprisingly short for a recursion error; not sure what's going on there.

**Comment by Michael0x2a** [comment] 2018-06-08 19:38
Maybe the short stack trace is due to some sort of improvement made to the way Python handles error messages?

E.g. doing the following in Python 3.6 results in a short traceback:

```
>>> def f():
...   f()
...
>>> f()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in f
  File "<stdin>", line 2, in f
  File "<stdin>", line 2, in f
  [Previous line repeated 995 more times]
RecursionError: maximum recursion depth exceeded
```

But if you try the same thing in Python 2, the stack trace explodes in length, as expected.

**Comment by ethanhs** [comment] 2018-06-08 19:39
Yes IIRC recursion stack traces were shortened in 3.5 or 3.6.

**Comment by JelleZijlstra** [comment] 2018-06-08 19:50
Right, I missed that there is `  [Previous line repeated 16341 more times]` in the middle of that stack trace. :)

**Comment by gvanrossum** [comment] 2018-06-08 20:15
Perhaps the short traceback is because mypy catches its own exceptions (so
it can print INTERNAL ERROR)?

**Comment by ilevkivskyi** [comment] 2019-04-02 15:16
Closing in favor of https://github.com/python/mypy/issues/6579

**Closed by ilevkivskyi** 2019-04-02 15:16 UTC
Labels: crash, priority-1-normal, topic-plugins
