### ISSUE TITLE
imports in `__init__.py` are not available in modules

### ISSUE THREAD

**Issue by zwergziege** [python/mypy#14999] opened 2023-04-03 12:28 UTC
**Bug Report**

Module imports specified in `__init__.py` are ignored for the module to be checked.

**To Reproduce**

Folder structure:
```
my_pkg\
      \__init__.py
      \A.py
      \B.py
```

File contents:
```python
# __init__.py
from .A import A
from .B import B
```

```python
# A.py
class A:
  pass
```

```python
# B.py
from my_pkg import A
class B:
  def __init__(self, a : A)
    pass
```

**Expected Behavior**

I would expect `mypy my_pkg` to run without errors since executing
```python
from my_pkg import A,B
x = B(A())
```
at top-level works just fine.

**Actual Behavior**

```
my_pkg/B.py:4: error: Module "my_pkg.A" is not valid as a type  [valid-type]
my_pkg/B.py:4: note: Perhaps you meant to use a protocol matching the module structure?
```

**Your Environment**

I used Mypy v1.1.1 without any additional config / flags

**Comment by dgoldstein0** [comment] 2023-04-12 05:54
this is a circular import - __init__.py imports .A and .B, and B importing my_pkg is an import of __init__.py.  Some circular imports do work in python when executed, but I skeptical a static analysis tool like mypy is going to be able to fully match dynamic (execution) behavior for such cases.  The obvious answer is "don't use circular imports" (though in general mypy should try to accept code if it works at runtime in most cases)

I'm not sure that's the only thing going wrong here though.  If it is, at the very least mypy could have a better error message.

**Comment by hauntsaninja** [comment] 2023-04-24 06:31
Thanks, I think this is a duplicate of https://github.com/python/mypy/issues/12681

**Closed** 2023-04-24 06:33 UTC
Labels: bug
