### ISSUE TITLE
Unable to assign a function a method

### ISSUE THREAD

**Issue by rowillia** [python/mypy#2427] opened 2016-11-10 01:46 UTC
For example:

```python
from typing import Any, Optional


class Foo(object):
    def __init__(self):
        # type: () -> None
        self.x = 0

    def get_x(self, a=None, b=None):
        # type: (Optional[int], Optional[int]) -> int
        return self.x + (a or 0) + (b or 0)


def get_x_patch(self, *args, **kwargs):
    #  type: (Foo, *Any, **Any) -> int
    return 42


Foo.get_x = get_x_patch
```
Results:
```
test_method_assignment.py:19: error: Cannot assign to a method
```

This assignment should be legal as any call to `get_x` will be able to call `get_x_patch`.  It looks like https://github.com/python/mypy/commit/3ce8d6a5c72f49e120b354619ab44523fee4de0e explicitly disallowed all method assignments, but there's not a ton of context behind it.

I know monkeypatching is generally frowned upon, but is unfortunately a very popular part of Python.  I can always mark those lines as ignored, but I'd rather be able to test that the patch is compatible with the underlying method with mypy.

**Comment by kirbyfan64** [comment] 2016-11-10 02:01
*I swear*, this is a duplicate, but I can't find the issue # yet...

**Comment by rowillia** [comment] 2016-11-10 03:35
@kirbyfan64 Yeah...I poked around and couldn't find anything.  Happy to close this if it is!

**Comment by gvanrossum** [comment] 2016-11-10 04:13
I think @sixolet might be interesting in this...

**Comment by JukkaL** [comment] 2016-11-10 12:28
The mypy callable type representation isn't expressive enough to to check assignments to methods precisely. In particular, at least bound methods and unbound function objects should be treated differently. Consider this example:

```python
class A:
    def f(self): pass
    def g(self): pass

def h(self): pass

A.f = h   # rvalue has one argument (unbound)
A().f()  # okay
A.f = A().g  # rvalue has no arguments (bound)
A().f()  # okay 
```

When we have value with an annotated callable type, such as `Callable[[A], None]`, mypy can't decide whether this is a bound or unbound function method/function. Static methods and class methods might complicate this further.

I'm pretty sure this is already broken in other contexts, but we may want to resolve this eventually. Some random ideas:

1. Internally keep track whether a callable is bound so that we can do more precise checking. This would work for expressions with inferred types. For values explicitly annotated with a `Callable` type, the value of the flag would be unknown and these couldn't be used for monkey patching (unless the argument types are `...`).
2. Like (1), but make some assumptions about annotated `Callable` types. Either assume that they are unbound, or optimistically assume that they have a compatible 'unboundedness' for any particular context. This is unsafe. This is basically how things work right now, though perhaps not consistently.
2. Add syntax for specifying callables that are always bound or unbound. We'd likely need three different variants: either bound or unbound (likely spelled just `Callable`), bound (for example, `BoundMethod`) and unbound (for example, `UnboundCallable`).

Option (3) doesn't seem worth the added complexity, to be honest, as it's always possible to fall back to `Callable[..., X]`.

**Comment by gvanrossum** [comment] 2016-11-10 15:37
So is the problem that when we see
```python
class C:
    f = None  # type: Callable[[int, int], int]
```
we don't know whether that defines an instance variable or a class variable? Maybe we can use `ClassVar` (introduced by PEP 526 into the typing module)? E.g.
```python
class C:
    f = None  # type: ClassVar[Callable[[int, int], int]]
```
and if ClassVar is not used assume `f` refers to an instance variable.

Of course initializations inside `__init__` are unambiguous. And so are method definitions (with or without `@staticmethod` or `@classmethod`).

I do think mypy ought to be fully aware of bound and unbound methods.

But perhaps the original problem is due to something else? The immediate problem seems to be that we don't try to match `*args, **kwds` against `a=None, b=None`?

**Comment by ilevkivskyi** [comment] 2017-09-27 13:30
Isn't this a duplicate of https://github.com/python/mypy/issues/708?

But maybe it makes sense to keep this open, since this issue contains some additional discussion.

**Comment by gvanrossum** [comment] 2017-09-27 14:12
Not really -- IIUC this seems about monkey-patching a class, whereas #708 is about assigning to function attributes.

**Comment by Jym77** [comment] 2018-04-25 09:00
A case where I keep running into that issue is when writing unit tests and trying to replace methods with `MagicMock()`.

Typically, class `Foo` is defined and tested somewhere and class `FooBar` uses (an instance of) `Foo`, but in order to unit test `FooBar` I don't really need/want to make actual calls to `Foo` methods (which can either take a long time to compute, or require some setup (eg, networking) that isn't here for unit test, …) So, I heavily `Mock()` the methods which allow to test that the correct calls are issued and thus test `FooBar`.

It does feel bad to add a bunch a `# type: ignore` on all these mocks :-(

**Comment by JukkaL** [comment] 2018-04-25 09:50
I prefer `setattr` over using `# type: ignore`. Mypy won't complain about it. This is something we could discuss in the common issues section in the docs.

**Comment by ikelos** [comment] 2019-04-05 12:05
What's the state of this (about monkey patching a method)?  It seems like it needed discussion, has that happened offline?

**Comment by JukkaL** [comment] 2019-04-05 12:50
The has been no progress recently. The workarounds discussed above (`setattr` or `# type: ignore`) are still the recommended ways to deal with this.

**Comment by ikelos** [comment] 2019-04-05 13:22
Cool, thanks for the update.  5:)

**Comment by compwron** [comment] 2019-10-11 01:33
I think that I am running into this. The code that causes the mypy error is `FileDownloader.download = classmethod(lambda a, filename: open(f'tests/fixtures/{filename}', 'rb'))`
The error is `error: Cannot assign to a method`
version is `mypy==0.620`

**Comment by dpinol** [comment] 2019-10-23 08:10
Hi, any progress on this?

**Comment by jbcpollak** [comment] 2020-06-02 03:35
In my case I'm not even monkey-patching (at least, I don't feel like it is), I'm trying to take a function as a parameter of __init__ and use it as a wrapper. Like this (note simplified example, so it might not make entire sense):

```
Adapter = Callable[[S_co], T_contra]

class AdaptingRunner():
    adapter: Adapter
    runner: Runner[T_contra]

    def __init__(self, adapter: Adapter, runner: Runner[T_contra]):
        self.adapter = adapter  # Error here
        self.runner = runner

    def run(self, obj: S_co):
        return self.runner.run(self.adapter(ob))
```

If I remove `adapter: Adapter`, everything is fine, but if I declare it, then I get the referenced error.

**Comment by septatrix** [comment] 2021-06-01 16:55
This also affects the stdlib when trying to assign to `unittest.TestLoader.sortTestMethodsUsing`

**Comment by randolf-scholz** [comment] 2021-09-28 22:42
Here is a MWE that shows that the bug can be caused by adding type hints to the inputs of `__init__`:

<table>
<tr>
<th>error: Cannot assign to a method</th>
<th>Throws no error</th>
</tr>
<tr>
<td>

```python
from typing import Callable

class A:
    f: Callable[..., None]

    def __init__(self, x: int):
        super().__init__()
        self.f = lambda: print(x)
```

</td>
<td>

```python
from typing import Callable

class A:
    f: Callable[..., None]

    def __init__(self, x):
        super().__init__()
        self.f = lambda: print(x)
```

</td>
</tr>
</table>

This is quite annoying because in certain contexts it is quite common to assign `callable` attributes in `__init__` (for example: machine learning / pytorch nn.Modules)

**Comment by gvanrossum** [comment] 2021-09-28 23:09
That's just because un-annotated functions (like the `__init__` on the right) are not analyzed at all. It has nothing to do with the underlying problem, which is that mypy doesn't quite understanding the difference between a class variable with a callable type and a method.

**Comment by randolf-scholz** [comment] 2021-09-28 23:54
> That's just because un-annotated functions (like the `__init__` on the right) are not analyzed at all. It has nothing to do with the underlying problem, which is that mypy doesn't quite understanding the difference between a class variable with a callable type and a method.

Oh! I wasn't aware of that. And I find this quite strange to be honest, since, even when the input types are unknown there could be things happening inside the function body where `mypy` could be useful. Why doesn't `mypy` simply assume `Any` type on all inputs in this case?

For example, consider

```python
def f(x):
    a: str = "abc"
    b: int = 3
    c = a + b
    return x
```

Imo it would be super useful if `mypy` raised an error here, even if `x` is not typed.

**Comment by gvanrossum** [comment] 2021-09-29 00:21
It would be more productive to discuss that here: https://github.com/python/typing/discussions .

**Comment by iainelder** [comment] 2022-01-29 18:35
> I prefer `setattr` over using `# type: ignore`. Mypy won't complain about it. This is something we could discuss in the common issues section in the docs.

It might silence mypy, but it's one of flakeheaven's bugbears.

> `B010 Do not call setattr with a constant attribute value, it is not any safer than normal property access. [flake8-bugbear]`

So I still prefer to use `type:ignore` with a comment about what is being ignored. For example, mypy also more usefully points out when the callable signatures don't match.

**Closed** 2023-02-05 19:34 UTC
Labels: bug, needs discussion, priority-1-normal, false-positive

**Comment by ilevkivskyi** [comment] 2023-02-06 14:51
For posterity, after some offline discussions we agreed that it would be hard to find semantics here that would satisfy everyone, and instead there will be a dedicated error code for this case. If you don't want mypy to complain about assignments to methods, use `--disable-error-code=method-assign` (starting mypy 1.1.0)
