### ISSUE TITLE
Incompatible return type error doesn't quote types

### ISSUE THREAD

**Issue by nematsakis** [python/mypy#3771] opened 2017-07-27 19:51 UTC
The error message for an incompatible return type doesn't have quotation marks around the types.  This makes it difficult to programmatically process the output of mypy to filter "expected" errors.

Example output:
`Error: Incompatible return value type (got List[Type1], expected List[Type2])`

Expected output:
`Error: Incompatible return value type (got "List[Type1]", expected "List[Type2]")`

**Comment by ilevkivskyi** [comment] 2017-07-27 20:04
We actually have a PR #3430 for this, but it looks like @mistermocha is currently busy.
I think this is essentially a duplicate of #3409

**Comment by OddBloke** [comment] 2017-09-03 18:51
I believe this was fixed in #3873.

**Closed** 2017-09-03 19:06 UTC
Labels: topic-usability
