### ISSUE TITLE
Unhelpful message "invalid type"

### ISSUE THREAD

**Issue by ruuda** [python/mypy#5586] opened 2018-09-07 08:54 UTC
Consider the following file:

```python
from tempfile import SpooledTemporaryFile

def make_file() -> SpooledTemporaryFile:
    return SpooledTemporaryFile()

temp_file = make_file()
```

When I typecheck this, I get

```
invalid.py:3: error: Invalid type "tempfile.SpooledTemporaryFile"
invalid.py:6: error: Need type annotation for 'temp_file'
```

This message is not helpful; what does it mean for a type to be "invalid", and why is `SpooledTemporaryFile` invalid?

If I add a type annotation as suggested by the second message, I get the "invalid" message twice:

```
invalid.py:3: error: Invalid type "tempfile.SpooledTemporaryFile"
invalid.py:6: error: Invalid type "tempfile.SpooledTemporaryFile"
```

I am using Mypy 0.620.

**Comment by ruuda** [comment] 2018-09-07 08:59
Looking into this, `SpooledTemporaryFile` is a function [in typeshed](https://github.com/python/typeshed/blob/dc27768401b09e22bcd9756ee8639eae06f55bab/stdlib/3/tempfile.pyi#L29), but it’s a class in my `/usr/lib/python3.6/tempfile.py`. Is the typeshed annotation wrong?

In any case, it would be nice if the error message could indicate that `SpooledTemporaryFile` is not a valid type because it is a function, rather than just saying "invalid type".

**Comment by ilevkivskyi** [comment] 2018-09-07 09:01
For poor error message, this is a duplicate of https://github.com/python/mypy/issues/4030

For the signature, yes, report this to typeshed issue tracker.

**Closed by ilevkivskyi** 2018-09-07 09:01 UTC
