### ISSUE TITLE
Take into account the results of hasattr()/dir(), similarly to isinstance and so on…

### ISSUE THREAD

**Issue by ltworf** [python/mypy#4944] opened 2018-04-19 22:42 UTC
Currently, mypy complains about this code:

It is checking if value is a `NamedTuple`, and in that case doing something.

```
if isinstance(value, tuple) and '_fields' in dir(value):
            value._fields
```

```
error: "Tuple[Any, ...]" has no attribute "_fields"
```

I understand it's a bit dynamic, but the check just happened, so it would be nice if mypy could take into account dir, hasattr.

After all, being instance of something doesn't mean it's not a subclass.

**Comment by gvanrossum** [comment] 2018-04-20 04:04
I don't think mypy is ever going to honor `dir()`. However it does make some sense to infer from `hasattr(x, 'blah')` that `x.blah` should be valid. Would that satisfy you? If not, you may as well close this issue.

**Comment by ltworf** [comment] 2018-04-20 05:26
It would be an improvement, and that check could easily be rewritten to not need the `type: ignore` then.

**Comment by JukkaL** [comment] 2018-04-20 08:49
I only found 7 instances of the `dir()` check in a multi-million line codebase but there were hundreds of `if ... hasattr(...)` instances. Supporting `hasattr()` seems like the way to go. This is still not high priority since the implementation of that check will be a bit tricky as long as mypy doesn't support intersection types.

**Comment by ethanhs** [comment] 2018-04-20 09:13
Since it sounds like we don't want to support `dir()`, at least for now, I think it is safe to close as a duplicate of https://github.com/python/mypy/issues/1424 (which has more ideas and discussion).

**Closed by ethanhs** 2018-04-20 09:13 UTC
Labels: feature, priority-2-low
