### ISSUE TITLE
Type aliasing doesn't work with multiple assignment

### ISSUE THREAD

**Issue by WouldYouKindly** [python/mypy#8092] opened 2019-12-05 15:00 UTC
Hello! I have the following code:
```python
Name, Value = str, str
Map = typing.Dict[Name, Value]


>> error: Variable "Name" is not valid as a type
>> error: Variable "Value" is not valid as a type
```

Is this the intended behaviour or a bug?

mypy==0.750

```
[mypy]
python_version = 3.7
warn_unused_configs = True
warn_unreachable = True
warn_no_return=False
warn_redundant_casts=True
warn_return_any=False
warn_unused_ignores=True

# flake8-mypy expects the two following for sensible formatting
show_column_numbers=True
show_error_context=False

disallow_untyped_defs=True
disallow_untyped_calls=True
disallow_untyped_decorators = True
disallow_incomplete_defs = True
disallow_any_generics = True

strict_optional=True
check_untyped_defs=True
no_implicit_optional = True
```

**Comment by ilevkivskyi** [comment] 2019-12-05 15:07
> Is this the intended behaviour or a bug?

This is intended behavior, but not something I would fight for if you have arguments why multiple assignments for aliases is desirable.

**Comment by WouldYouKindly** [comment] 2019-12-05 15:34
@ilevkivskyi I have no arguments except that it feels that it should work, but doesn't. A bit of a surprise. Also it's not clear what's wrong — at first I thought that I cannot alias types in this way and must use `NewType`.

**Comment by ilevkivskyi** [comment] 2019-12-05 20:26
This is not supported mainly for two reasons:
* Python doesn't have dedicated syntax to distinguish variables with type `Type[...]`, and type aliases, it is better not mix them.
* Supporting this requires some non-trivial effort.

I would therefore propose to close this unless someone disagrees.

**Comment by AndrewUshakov** [comment] 2021-04-28 20:13
@ilevkivskyi: Please consider the code below:
```Python
from typing import Type

IntType = int
IntVar1: Type[int] = int
IntVar2, x = int, 666

reveal_type(IntType)
reveal_type(IntVar1)
reveal_type(IntVar2)
reveal_type(int)

def f1(arg: IntType) -> None:
    ...

def f2(arg: IntVar1) -> None:
    ...

def f3(arg: IntVar2) -> None:
    ...
```
and output of mypy 0.812:
```
(.env) D:\Documents\PycharmProjects\tst_newline>mypy --pretty --strict tst3.py
tst3.py:7: note: Revealed type is 'Overload(def (x: Union[builtins.str, typing.SupportsInt, builtins._SupportsIndex, builtins._SupportsTrunc] =) -> builtins.int*, def (x: Union[builtins.str, builtins.bytes], base: builtins.int) -> builtins.int*)'
tst3.py:8: note: Revealed type is 'Type[builtins.int]'
tst3.py:9: note: Revealed type is 'Overload(def (x: Union[builtins.str, typing.SupportsInt, builtins._SupportsIndex, builtins._SupportsTrunc] =) -> builtins.int*, def (x: Union[builtins.str, builtins.bytes], base: builtins.int) -> builtins.int*)'
tst3.py:10: note: Revealed type is 'Overload(def (x: Union[builtins.str, typing.SupportsInt, builtins._SupportsIndex, builtins._SupportsTrunc] =) -> builtins.int*, def (x: Union[builtins.str, builtins.bytes], base: builtins.int) -> builtins.int*)'
tst3.py:15: error: Variable "tst3.IntVar1" is not valid as a type
    def f2(arg: IntVar1) -> None:
                ^
tst3.py:15: note: See https://mypy.readthedocs.io/en/latest/common_issues.html#variables-vs-type-aliases
tst3.py:18: error: Variable "tst3.IntVar2" is not valid as a type
    def f3(arg: IntVar2) -> None:
                ^
tst3.py:18: note: See https://mypy.readthedocs.io/en/latest/common_issues.html#variables-vs-type-aliases
Found 2 errors in 1 file (checked 1 source file)
```
Please note, that IntVar2 created in line 5 by multiple assignment, according of reveal_type output (line 9), looks exactly like IntType. created in line 3 and int type itself. 

That is, may be this bug could be corrected without significant efforts? If no, could you please correct mypy documentation, mentioned in mypy output?

**Comment by hauntsaninja** [comment] 2021-08-05 01:33
Closing as per Ivan's comment.

**Closed by hauntsaninja** 2021-08-05 01:33 UTC
