### ISSUE TITLE
write-able properties and fields are treated as covariant when they should be invariant

### ISSUE THREAD

**Issue by KotlinIsland** [python/mypy#11975] opened 2022-01-12 02:05 UTC
```py
class A:
    a: int = 10
    @property
    def foo(self) -> int:
        return 1
    @foo.setter
    def foo(self, value: int) -> None:
        ...
class B(A):
    a: bool = True
    @property
    def foo(self) -> bool:
        return True
    
    @foo.setter
    def foo(self, value: bool) -> None:
        ...

def foo(a: A) -> None:
    a.a = 10
    a.foo = 10
    
    
b = B()
foo(b)
reveal_type(b.a)  # bool, at runtime it's int
reveal_type(b.foo)  # bool, at runtime it's int
```
https://mypy-play.net/?mypy=master&python=3.10&flags=strict&gist=9433ff90606ac67ec9728212af1edec1

**Comment by hauntsaninja** [comment] 2022-01-12 09:02
Thanks, duplicate of https://github.com/python/mypy/issues/3208

**Closed by hauntsaninja** 2022-01-12 09:02 UTC
Labels: bug
