### ISSUE TITLE
Nested Function incorrect type inference

### ISSUE THREAD

**Issue by alanhdu** [python/mypy#4399] opened 2017-12-21 18:11 UTC
Running `mypy --strict-optional` on the following code:

```python
from typing import Optional, Sequence

def f(timestamps: Optional[Sequence[float]] = None):
    if timestamps is None:
        timestamps = [0]

    reveal_type(timestamps)
    def index(i: int) -> float:
        return timestamps[i]
    return index(0)
```

fails with

```
test.py:7: error: Revealed type is 'typing.Sequence[builtins.float]'
test.py:9: error: Value of type "Optional[Sequence[float]]" is not indexable
```

This is pretty weird -- MyPy knows that `timestamps` isn't `None` at that point, but complains in the nested function.

**Comment by ethanhs** [comment] 2017-12-21 19:30
It seems type narrowing is not being propagated to closures, but only in function defs (I checked the above with a lamba and the narrowing is propagated). The narrowing stays after the function definition, just not within.

**Comment by ilevkivskyi** [comment] 2017-12-23 12:19
This is a duplicate of #2608

**Closed by ilevkivskyi** 2017-12-23 12:19 UTC
