### ISSUE TITLE
new type inference regression on callable

### ISSUE THREAD

**Issue by bzoracler** [python/mypy#16458] opened 2023-11-11 05:33 UTC
**Bug Report**

The new type inference introduced (default in mypy 1.7) causes the following failure:

**To Reproduce & Actual Behaviour**

[mypy-play.net](https://mypy-play.net/?mypy=master&python=3.11&gist=aedddba93f55368033f2dd4ee9593360)

```python
import typing_extensions as t

T = t.TypeVar("T")
deco: t.Callable[[t.Callable[..., T]], t.Callable[..., T]]

@deco  # mypy: Argument 1 has incompatible type "Callable[[T], T | int]"; expected "Callable[..., Never]" [arg-type]
def func(item: T, /) -> T | int:
    return 0
```

The discovery of this was with `@deco` as `@functools.singledispatch`, which has signature `def singledispatch(func: Callable[..., _T]) -> _SingleDispatchCallable[_T]: ...`.

**Expected Behavior**

No issues (as with mypy 1.6.1 without `--new-type-inference` and 1.7 with `--old-type-inference`)

**Your Environment**

- Mypy version used: `1.6.1` with `--new-type-inference`, `1.7`, `master`, 
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): None
- Python version used: `3.10`, `3.11`

**Comment by ilevkivskyi** [comment] 2023-11-11 12:36
This is a duplicate of https://github.com/python/mypy/issues/16451 (this has a much simpler repro, but that issue is older, so closing this one).

**Closed by ilevkivskyi** 2023-11-11 12:36 UTC
Labels: bug
