### ISSUE TITLE
Variable made by `make_dataclass ` is not valid as a type

### ISSUE THREAD

**Issue by decaz** [python/mypy#8942] opened 2020-06-03 19:58 UTC
Here is example of `make_dataclass` usage and its equivalent from https://docs.python.org/3/library/dataclasses.html#dataclasses.make_dataclass:
```python
import typing
from dataclasses import dataclass, field, make_dataclass

C = make_dataclass('C',
                   [('x', int),
                     'y',
                    ('z', int, field(default=5))],
                   namespace={'add_one': lambda self: self.x + 1})


def f(x: C) -> C:
    return x


@dataclass
class CC:
    x: int
    y: 'typing.Any'
    z: int = 5

    def add_one(self):
        return self.x + 1


def ff(x: CC) -> CC:
    return x
```
And that's what mypy says about it:
```
$ mypy xxx.py
xxx.py:7: error: Argument "default" to "field" has incompatible type "int"; expected "Field[Any]"
xxx.py:11: error: Variable "xxx.C" is not valid as a type
xxx.py:11: note: See https://mypy.readthedocs.io/en/latest/common_issues.html#variables-vs-type-aliases
Found 2 errors in 1 file (checked 1 source file)
```
The most strange error is the second one, - can it be fixed within the current listing?

**Comment by JukkaL** [comment] 2020-06-08 15:19
Closing as duplicate of #6063. If you have suggestions, feel free to add them them to that issue.

**Closed by JukkaL** 2020-06-08 15:19 UTC
Labels: false-positive, feature, priority-2-low
