### ISSUE TITLE
Checking Optional Tuple in an if statement makes mypy think there's dead code.

### ISSUE THREAD

**Issue by ilinum** [python/mypy#3606] opened 2017-06-23 23:35 UTC
In the following code mypy does not analyze the branch of the if statement:
```py
from typing import Tuple, Optional

def f() -> Optional[Tuple[str, int]]:
    return None


v = f()
if not v:
    1 + "boom"  # no error from mypy
```

Here is the output from `mypy` and `python`.
```
$ mypy n.py 
$ python3 n.py 
Traceback (most recent call last):
  File "n.py", line 9, in <module>
    1 + "boom"  # no error from mypy
TypeError: unsupported operand type(s) for +: 'int' and 'str'
```

**Comment by gvanrossum** [comment] 2017-06-24 01:07
It seems to only happen when the type is an optional *tuple*. Updated the issue subject.

**Comment by ilevkivskyi** [comment] 2017-06-27 12:42
I think this is not a bug, just a simple fact that ``--strict-optional`` is not on by default. With ``--strict-optional`` mypy correctly reports an error (also note that ``Tuple[str, int]`` is indeed always ``True``).

**Comment by JukkaL** [comment] 2017-06-27 14:21
But in non-strict-optional mode `v` could still be `None`, so the branch can be taken. In the default mode most thing can be `None`, and mypy shouldn't generally assume that this is not the case. 

This program (that doesn't use `Optional`) should generate an error if not using strict optional checking, but it doesn't:

```py
from typing import Tuple

def f() -> Tuple[str, int]:
    return None

v = f()
if not v:
    1 + "boom"  # no error from mypy
```

**Comment by ilevkivskyi** [comment] 2017-06-27 14:34
> This program (that doesn't use ``Optional``) should generate an error if not using strict optional checking, but it doesn't

Yes, but I still think that it would be a questionable effort to fix this instead of moving towards ``--strict-optional`` on by default.

(As a side note I don't really like the concept of not showing errors in unreachable branches. We could at least make them ``note:``.)

**Comment by ilinum** [comment] 2017-06-27 15:48
@ddfisher, did you have some input on this?

**Comment by AlexWaygood** [comment] 2022-03-24 08:47
Mypy now [emits an error](https://mypy-play.net/?mypy=latest&python=3.10&flags=no-strict-optional&gist=90f9993ae5381dc78d08c2a4ee245988) in the correct place, by default and with the `--no-strict-optional` option.

**Closed by AlexWaygood** 2022-03-24 08:47 UTC
Labels: bug
