### ISSUE TITLE
Can't make mypy work with a class inherited from django

### ISSUE THREAD

**Issue by matthieudesprez** [python/mypy#10270] opened 2021-03-31 12:40 UTC
I have a function, that takes a type as parameter, but if I pass whatever is inheriting from a class from the django module, I got no error at all from mypy

```python
from django.shortcuts import ABCD


class Dice():
    value: str


class Card(ABCD):
    value: str


def play(item: Dice):
    print(item.value)


def main(item: Card):
    reveal_type(item)
    play(item)

```

The reveal_type correctly prints:
```bash
... note: Revealed type is '...Card'
```

When I removed the inheritance from ABCD in Card I get the expected output from mypy:
```bash
error: Argument 1 to "play" has incompatible type "Card"; expected "Dice"
```

I've put ABCD in django.shortcuts like this:

```python
class ABCD:
    pass
```

Initially in my real case scenario it concerns a model that inherits from django.db.models.Model

What could be the issue there ? I can't figure why the typing gets ignored while inheriting something from the django module. Is there some additional option I can pass to mypy to get this covered ?

Thanks

**Comment by JelleZijlstra** [comment] 2021-03-31 13:34
The problem is that mypy doesn't know anything about django.shortcuts, so it interprets the class as Any, and classes that inherit from Any are compatible with anything. To fix it you need to somehow make mypy able to find your django.shortcuts module, perhaps with MYPYPATH or the `--include` flag.

**Comment by sobolevn** [comment] 2021-10-01 10:07
@matthieudesprez  You should probably open this issue in our bugtracker: https://github.com/typeddjango/django-stubs/

**Comment by AlexWaygood** [comment] 2022-04-02 15:52
Closing this issue — it seems like the question has been answered, and/or should be raised with the typeddjango project rather than mypy

**Closed by AlexWaygood** 2022-04-02 15:52 UTC
Labels: question
