### ISSUE TITLE
`mypy /usr/lib/python3.6/typing.py` crashes with an AssertionError

### ISSUE THREAD

**Issue by jleclanche** [python/mypy#4404] opened 2017-12-23 05:53 UTC
Traceback:

```py
<snip>
Traceback (most recent call last):
  File "/usr/bin/mypy", line 11, in <module>
    load_entry_point('mypy==0.560', 'console_scripts', 'mypy')()
  File "/usr/lib/python3.6/site-packages/mypy/__main__.py", line 7, in console_entry
    main(None)
  File "/usr/lib/python3.6/site-packages/mypy/main.py", line 66, in main
    res = type_check_only(sources, bin_dir, options)
  File "/usr/lib/python3.6/site-packages/mypy/main.py", line 119, in type_check_only
    options=options)
  File "/usr/lib/python3.6/site-packages/mypy/build.py", line 218, in build
    graph = dispatch(sources, manager)
  File "/usr/lib/python3.6/site-packages/mypy/build.py", line 1997, in dispatch
    process_graph(graph, manager)
  File "/usr/lib/python3.6/site-packages/mypy/build.py", line 2299, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/usr/lib/python3.6/site-packages/mypy/build.py", line 2475, in process_stale_scc
    graph[id].type_check_first_pass()
  File "/usr/lib/python3.6/site-packages/mypy/build.py", line 1876, in type_check_first_pass
    self.type_checker().check_first_pass()
  File "/usr/lib/python3.6/site-packages/mypy/checker.py", line 196, in check_first_pass
    self.accept(d)
  File "/usr/lib/python3.6/site-packages/mypy/checker.py", line 286, in accept
    stmt.accept(self)
  File "/usr/lib/python3.6/site-packages/mypy/nodes.py", line 800, in accept
    return visitor.visit_assignment_stmt(self)
  File "/usr/lib/python3.6/site-packages/mypy/checker.py", line 1337, in visit_assignment_stmt
    self.check_assignment(s.lvalues[-1], s.rvalue, s.type is None, s.new_syntax)
  File "/usr/lib/python3.6/site-packages/mypy/checker.py", line 1431, in check_assignment
    self.infer_variable_type(inferred, lvalue, self.expr_checker.accept(rvalue),
  File "/usr/lib/python3.6/site-packages/mypy/checkexpr.py", line 2365, in accept
    typ = node.accept(self)
  File "/usr/lib/python3.6/site-packages/mypy/nodes.py", line 1245, in accept
    return visitor.visit_call_expr(self)
  File "/usr/lib/python3.6/site-packages/mypy/checkexpr.py", line 268, in visit_call_expr
    ret_type = self.check_call_expr_with_callee_type(callee_type, e, fullname, object_type)
  File "/usr/lib/python3.6/site-packages/mypy/checkexpr.py", line 505, in check_call_expr_with_callee_type
    object_type=object_type)[0]
  File "/usr/lib/python3.6/site-packages/mypy/checkexpr.py", line 602, in check_call
    arg_types = self.infer_arg_types_in_context(None, args)
  File "/usr/lib/python3.6/site-packages/mypy/checkexpr.py", line 703, in infer_arg_types_in_context
    arg_type = self.accept(arg, ctx)
  File "/usr/lib/python3.6/site-packages/mypy/checkexpr.py", line 2365, in accept
    typ = node.accept(self)
  File "/usr/lib/python3.6/site-packages/mypy/nodes.py", line 1194, in accept
    return visitor.visit_member_expr(self)
  File "/usr/lib/python3.6/site-packages/mypy/checkexpr.py", line 1233, in visit_member_expr
    result = self.analyze_ordinary_member_access(e, False)
  File "/usr/lib/python3.6/site-packages/mypy/checkexpr.py", line 1244, in analyze_ordinary_member_access
    original_type = self.accept(e.expr)
  File "/usr/lib/python3.6/site-packages/mypy/checkexpr.py", line 2365, in accept
    typ = node.accept(self)
  File "/usr/lib/python3.6/site-packages/mypy/nodes.py", line 1154, in accept
    return visitor.visit_name_expr(self)
  File "/usr/lib/python3.6/site-packages/mypy/checkexpr.py", line 129, in visit_name_expr
    result = self.analyze_ref_expr(e)
  File "/usr/lib/python3.6/site-packages/mypy/checkexpr.py", line 167, in analyze_ref_expr
    result = self.named_type('types.ModuleType')
  File "/usr/lib/python3.6/site-packages/mypy/checkexpr.py", line 2389, in named_type
    return self.chk.named_type(name)
  File "/usr/lib/python3.6/site-packages/mypy/checker.py", line 2663, in named_type
    assert isinstance(node, TypeInfo)
AssertionError: 

```

I hit this from vscode mypy recursing into the string library (which in turn went into types, then typing). It said to report so I oblige :)

**Comment by ilevkivskyi** [comment] 2017-12-23 13:12
I think this is essentially a duplicate of https://github.com/python/mypy/issues/1876, special modules like ``typing`` should never be typechecked. Moreover, stdlib modules should not be typechecked directly, they are typed in typeshed.

**Comment by ethanhs** [comment] 2018-02-25 21:15
Yeah, closing as a duplicate of #1876. (Which I am hoping to fix soon).

**Closed by ethanhs** 2018-02-25 21:15 UTC
Labels: crash
