### ISSUE TITLE
sys.exit() is not considered as noreturn

### ISSUE THREAD

**Issue by socketpair** [python/mypy#13592] opened 2022-09-02 09:34 UTC
https://mypy-play.net/?mypy=latest&python=3.10&flags=strict%2Cstrict-equality&gist=e86aa52c05acd36b6c04067cb6f44ce1
```python
import sys

def main() -> int:
    return sys.exit(42)
```
MyPy finds nothing wrong here.

Anyway, this should be valid:

```python
try:
    sys.exit(42)
except SystemExit:
    print('xxx') # this line IS reachable.
```

i.e. this function either raises specific exception or noreturn.

**Comment by JelleZijlstra** [comment] 2022-09-02 19:20
Can you clarify what you think the bug is? Mypy is correct when it doesn't produce any errors on your first sample, because a function that never returns is a valid `Callable[[], int]`.

**Comment by sobolevn** [comment] 2022-09-02 21:33
Looks like `sys.exit` is indeed recognised as returning `NoReturn`: https://mypy-play.net/?mypy=latest&python=3.10&flags=strict%2Cstrict-equality%2Cwarn-unreachable&gist=ef39ea5ba16960f2dd4274349a2c142d

So, it looks fine to me!

**Comment by socketpair** [comment] 2022-09-02 22:02
Using return value of noreturn function is an error, indeed.

**Comment by sobolevn** [comment] 2022-09-03 09:18
Feel free to reopen if you have other questions / problems :)

**Comment by socketpair** [comment] 2022-09-04 04:46
@sobolevn please reopen. It's not fixed actually.

**Comment by sobolevn** [comment] 2022-09-04 08:46
Can you please specify what example is not fixed?

**Comment by socketpair** [comment] 2022-09-04 20:13
The first one. Mypy does not see any errors in using value of noreturn function.

**Comment by erictraut** [comment] 2022-09-04 21:03
The first code sample is not a bug. Mypy is correct in not emitting an error here. `NoReturn` (which is equivalent to the recently-introduced `typing.Never` type) is a bottom type in the Python type system, and it is is compatible with all other types. A return value of type `NoReturn` is compatible with the declared return type `int`.

**Comment by socketpair** [comment] 2022-09-05 02:32
I think, Noreturn must not be compatible with any other type. What the case when it should be compatible ?

**Comment by socketpair** [comment] 2022-09-05 02:37
Should be `def sys.exit(arg: int) -> Never`. Does not it ? That is the same as `-> NoReturn` here.

**Comment by erictraut** [comment] 2022-09-05 03:53
`NoReturn` is another name for `Never`. It is the "bottom type" in Python type system. You can think of it as equivalent to an empty union. `NoReturn` is compatible with all other types. No other type (other than `NoReturn` itself) is compatible with `NoReturn`.

**Comment by socketpair** [comment] 2022-09-06 04:24
Thanks for verbose explanation. I checked TypeScript:

```ts
const sys_exit: (code: number) => never = (code: number) => {
    throw new Error('message');
};

const x: number = sys_exit(42);
```

It also sees nothing wrong here.

![image](https://user-images.githubusercontent.com/1157412/188546521-e07f6c0e-a641-4ff7-921d-f1cf1901365d.png)



I still don't understand why `NoReturn` / `Never` should be compatible with all types. For me, it must not by definition. Seems I don't understand something important in typing system. Will be great if you provide a link.

**Comment by KotlinIsland** [comment] 2022-09-07 02:17
Because `Never` can not exist, it is safe to use as a value of any type.

https://en.wikipedia.org/wiki/Bottom_type

```py
def n() -> Never: raise Exception

print(n() + 1)
```
At runtime, this will not produce a `TypeError`, because this `+` will never be executed.

**Comment by socketpair** [comment] 2022-09-07 03:21
Why not make it incompatible with any type to detect obvious errors like trying to use return value of noreturn functions ?

**Comment by Avasam** [comment] 2022-12-05 03:49
> Why not make it incompatible with any type to detect obvious errors such as trying to use return value of noreturn functions ?

I think what you are asking for is more in the realm of a linting rule\*: `NoReturn` is perfectly type-safe, but using the value of a function that does not return is a code smell and indicative of a potential bug / misunderstanding of the developer about what a function does.

I like the idea for that reason, idk if it belongs in mypy / pyright (maybe as an optional setting?). But few python linters are type-aware. I would personally turn on that rule if I had the option.

\* It wouldn't the be the first time a type-checker has a rule that's not specific to typing (pyright has a few I like).

**Comment by KotlinIsland** [comment] 2022-12-05 06:36
@Avasam Mypy complains on usages of functions that return `None`, so I think it would be make sense if this was included in mypy.

https://mypy-play.net/?mypy=latest&python=3.11&gist=e15787211c8a4115c82687bc15fee244

**Comment by erictraut** [comment] 2023-08-13 19:10
Mypy is working correctly here. This isn't a bug. I recommend closing.

**Closed** 2023-08-13 19:15 UTC
Labels: feature
