### ISSUE TITLE
No support for "callable" decorators

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#1837] opened 2016-07-09 00:17 UTC
This works fine:
```python
F = TypeVar('F', bound=Callable[..., Any])
def outer(f: F) -> F:
    def inner(*args):
        return f(*args)
    return cast(F, inner)

@outer
def foo(a: int) -> str:
    return str(a)
```
However adding this does not work (it reuses the `outer` decorator from above):
```python
def superouter() -> Callable[[F], F]:
    return outer

@superouter()  # E: Argument 1 has incompatible type Callable[[str], int]; expected None
def bar(b: str) -> int:
    return int(b)
```

**Comment by rwbarton** [comment] 2016-07-09 00:25
This is a duplicate of #1551, though the exact errors seem to have changed a little since then.

**Closed** 2016-07-09 00:37 UTC
