### ISSUE TITLE
Plugins are loaded only if the config file is explicitly given

### ISSUE THREAD

**Issue by Tinche** [python/mypy#3769] opened 2017-07-26 15:13 UTC
This is the problem: https://github.com/python/mypy/blob/e4d1dc49091acbf597e60618de5ff4c5443d9c20/mypy/build.py#L353

If I run mypy just using `mypy a.py` with a mypy.ini in the current directory, `options.config_file` will for some reason be `None` and no plugins will be loaded. `options.plugins` will be set properly though.

**Comment by gvanrossum** [comment] 2017-07-26 15:25
Can you send a PR with a fix? The problem is probably somewhere in the processing of the config-file flag.

**Comment by Tinche** [comment] 2017-07-26 15:33
Sure but I don't know exactly how to fix it. `options.config_file` should be set to `mypy.ini` in this case? Or should I check for `setup.cfg` too?

**Comment by gvanrossum** [comment] 2017-07-26 15:43
I think the `parse_config_file()` function in `main.py` needs to set `options.config_file` if it actually finds a config.

**Comment by Tinche** [comment] 2017-07-26 17:18
Alright, I'll put together a PR soon.

**Comment by Tinche** [comment] 2017-07-27 20:09
PR here: https://github.com/python/mypy/pull/3770

**Comment by JelleZijlstra** [comment] 2017-08-10 02:57
Fixed by #3770.

**Closed by JelleZijlstra** 2017-08-10 02:57 UTC
