### ISSUE TITLE
disallow_untyped_defs flags methods defined as overloads as missing type annotations.

### ISSUE THREAD

**Issue by rowillia** [python/mypy#3714] opened 2017-07-13 22:15 UTC
```python
from typing import overload, Optional

@overload
def foo(x: int) -> str: pass

@overload
def foo(x: None) -> None: pass

def foo(x):
    return str(x) if x is not None else None
```

```bash
$ python3.6 -m mypy --disallow-untyped-defs test_overload.py
test_overload.py:9: error: Function is missing a type annotation
```

**Comment by JelleZijlstra** [comment] 2017-07-13 22:23
Duplicate of #3360.

**Closed by JelleZijlstra** 2017-07-13 22:23 UTC
