### ISSUE TITLE
collections.OrderedDict.copy() -> Dict?

### ISSUE THREAD

**Issue by sophie-h** [python/mypy#2093] opened 2016-09-04 16:47 UTC
mypy 0.4.4

```
note: In function "f":
5: error: Incompatible return value type (got Dict[Any, Any], expected OrderedDict[Any, Any])
```

``` py
import collections

def f(x: collections.OrderedDict) -> collections.OrderedDict:
    y = x.copy()
    return y
```

**Comment by elazarg** [comment] 2016-09-04 23:13
Related: #1212

**Comment by elazarg** [comment] 2017-10-19 21:22
This is a duplicate of python/typeshed#1642 (which has been closed by now, but not fixed yet - at least not within mypy)

**Comment by JelleZijlstra** [comment] 2017-10-19 22:58
This is purely a typeshed problem, so let's close this one.

**Closed by JelleZijlstra** 2017-10-19 22:58 UTC
