### ISSUE TITLE
Final and TypedDict

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#5612] opened 2018-09-13 09:46 UTC
I wonder if we should we support `Final` items in a TypedDict.

**Comment by ilevkivskyi** [comment] 2018-09-13 09:49
This looks like a reasonable feature to me. In particular in view of the parallel `obj.attr` vs `obj.__dict__['attr']`.

**Comment by AlexWaygood** [comment] 2023-03-17 09:38
Closing as a duplicate of #7981, which is a newer issue but has much more discussion

**Closed by AlexWaygood** 2023-03-17 09:38 UTC
Labels: feature, topic-typed-dict, priority-1-normal, topic-final
