### ISSUE TITLE
boolean return inferred as `Any` return type

### ISSUE THREAD

**Issue by Avasam** [python/mypy#17007] opened 2024-03-09 20:19 UTC
**Bug Report**

A method returning only boolean values is inferred as returning `Any`

**To Reproduce**

See the following minimal example:
```py
def is_valid_hwnd(hwnd: int):
    if not hwnd:
        return False
    return True
    
reveal_type(is_valid_hwnd(0)) # note: Revealed type is "Any"
```

The real-world example is as such:
```py
def is_valid_hwnd(hwnd: int):
    """Validate the hwnd points to a valid window and not the desktop or whatever window obtained with `""`."""
    if not hwnd:
        return False
    if sys.platform == "win32":
        return bool(win32gui.IsWindow(hwnd) and win32gui.GetWindowText(hwnd))
    return True
```

Which is much more readable than a boolean expression. But even that surprisingly is inferred as Any:
```py
def is_valid_hwnd(hwnd: int):
    return bool(hwnd and (sys.platform != "win32" or (win32gui.IsWindow(hwnd) and win32gui.GetWindowText(hwnd))))
```
**Expected Behavior**

The return type should be inferred as `bool`. Even `Literal[True, False]` or `Literal[True, False] | bool` would be fine.

**Actual Behavior**

Return type is inferred as `Any`

**Your Environment**

- Mypy version used: mypy 1.9.0 (compiled: yes)
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files):
```ini
; We don't run mypy in the CI. This is just to help anyone who would like to use it manually.
; Namely, the mypy_primer tool.
[mypy]
show_column_numbers = true
mypy_path = $MYPY_CONFIG_FILE_DIR/typings
implicit_reexport = true

strict = true
; Implicit return types !
check_untyped_defs = true
disallow_untyped_calls = false
disallow_untyped_defs = false
disallow_incomplete_defs = false
disable_error_code = return

; exclude mypyc build
exclude = .*(build)/.*

; Auto-generated code, not much we can do there
[mypy-gen.*]
disable_error_code = attr-defined, arg-type

; Of course my stubs are going to be incomplete. Otherwise they'd be on typeshed!
; Mypy becomes really whack with its errors inside these stubs though
[mypy-scipy.*]
disable_error_code = attr-defined, import-untyped
```
- Python version used: 3.11.6

**Comment by JelleZijlstra** [comment] 2024-03-09 20:23
Duplicate of #10149

**Closed by JelleZijlstra** 2024-03-09 20:23 UTC
Labels: bug
