### ISSUE TITLE
Assert on Literal field causes spurious "Non-overlapping equality check"

### ISSUE THREAD

**Issue by intgr** [python/mypy#9409] opened 2020-09-03 14:52 UTC
## 🐛 Bug Report

Mypy is overzealous in constraining the possible values of a `Literal` field, assuming that it cannot change after being `assert`ed.

I suppose this can also happen with other types, like `Union` fields, but in the case of `Literal` it's particularly awkward.

## To Reproduce

```python
from dataclasses import dataclass
from typing import Literal


@dataclass
class Data:
    state: Literal["on", "off"]

    def set_state(self, state: Literal["on", "off"]):
        self.state = state


def test_func():
    obj = Data("on")
    assert obj.state == "on"

    obj.set_state("off")
    #   ^^^^^^^^^^^^^^^^ mutation happens here
    assert obj.state == "off"
    #      ^^^^^^^^^
    # mypy: Non-overlapping equality check (left operand type: "Literal['on']", right operand type: "Literal['off']")
```

- Mypy version used: mypy 0.780
- Python version used: 3.8.6

**Comment by hauntsaninja** [comment] 2023-08-13 21:01
Closing as a duplicate of https://github.com/python/mypy/issues/9005

**Closed by hauntsaninja** 2023-08-13 21:01 UTC
Labels: bug, topic-literal-types, topic-overlap
