### ISSUE TITLE
Callback with generic return type should not be accepted without a bound 

### ISSUE THREAD

**Issue by hackaugusto** [python/mypy#10082] opened 2021-02-12 11:50 UTC
**Bug Report**

I believe the following code should not type check:

```python
from typing import TypeVar
from typing_extensions import Protocol

T_co = TypeVar('T_co', covariant=True)

class C(Protocol[T_co]):
    def __call__(self) -> T_co: ...

def f(c: C) -> str:
    return c()
```

**To Reproduce**

Run `mypy` against the example above.

**Expected Behavior**

`f` should not type check, since `c` may return values that are not subtypes of `str`

**Actual Behavior**

The code above type checks. Because of that, I'm allowed to write this:

```python
def g() -> bool:
    return True

f(g)
```

**Your Environment**

- Mypy version used: `mypy 0.820+dev.2160eb5d1d60f8adce9ea1308c9a42a03d93f340`
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): nothing
- Python version used: Python 3.9.1
- Operating system and version: Fedora 33

**Comment by erictraut** [comment] 2023-08-12 02:36
Mypy's behavior is correct here. The problem is that `C` is a generic class that takes a single type argument, but the type annotation for function `f` doesn't supply a type argument. That means mypy (correctly) assumes that `C[Any]` is intended, and the expression `c()` evaluates to `Any`, which is type compatible with `str`.

I recommend closing this issue.

**Closed** 2023-08-12 06:39 UTC
Labels: bug
