### ISSUE TITLE
Type narrowing not working when condition is assigned to a variable

### ISSUE THREAD

**Issue by kwasielew** [python/mypy#12430] opened 2022-03-23 11:59 UTC
Hi all,

Let me share what problem I encounter with mypy.

Relevant code from the class method looks like that:
```python
state = self.board.state
top_card = self.board.discard_pile.top_card

is_battle_card_on_top_and_battle_ongoing = (
    top_card in BATTLE_CARDS and state.name == BATTLE_STATE_NAME
)

...

if is_battle_card_on_top_and_battle_ongoing:
    state.no_of_cards_to_draw += self._calculate_battle_cards_value()
```
and because Board class accepts abstract class of game state:
```python
@dataclass
class Board:
    ...
    state: AbstractGameState
    ...
```

and `no_of_cards_to_draw` field is only defined in specific state class (`BattleState`) inherited from `AbstractGameState`, mypy raises na error:

**Mypy: "AbstractGameState" has no attribute "no_of_cards_to_draw""**

So then I heard about Type narrowing in Mypy, and I have tried to use that:

```python
is_battle_card_on_top_and_battle_ongoing = top_card in BATTLE_CARDS and isinstance(state, BattleState)
```
BUT, it does not work (mypy still complains).

If I use `isinstance` directly in `if` clause, then mypy is fine with this:

```python
if top_card in BATTLE_CARDS and isinstance(state, BattleState):
    state.no_of_cards_to_draw += self._calculate_battle_cards_value()
```

--- 
Why is that? I went through the documentation and googled for similar issues without luck.
Is it proper behavior? 
I find storing complex conditions in properly named variables readable and beneficial.
Is there a way to fix that mypy error, have I missed something?
Thank you

**Comment by JelleZijlstra** [comment] 2022-03-23 20:49
Duplicate of #11979.

**Closed by JelleZijlstra** 2022-03-23 20:49 UTC
Labels: feature, topic-type-narrowing
