### ISSUE TITLE
Nested generic self type error

### ISSUE THREAD

**Issue by alanhdu** [python/mypy#5482] opened 2018-08-15 02:59 UTC
mypy does not seem to like generic self types.  Running mypy 0.620 with Python 3.6.6 on the following code

```python
from typing import Generic, List, TypeVar

T = TypeVar("T")


class Nested(Generic[T]):
    def __init__(self, x: T) -> None:
        self.x = [x]

    def get(self: "Nested[List[T]]") -> T:
        return self.x[0][0]


n = Nested([1])
reveal_type(n)
reveal_type(n.x)
y = n.get()
reveal_type(y)
```

gives us

```python
scratch.py:15: error: Revealed type is 'scratch.Nested[builtins.list*[builtins.int*]]'
scratch.py:16: error: Revealed type is 'builtins.list[builtins.list*[builtins.int*]]'
scratch.py:18: error: Revealed type is 'builtins.list*[builtins.int*]'
```

This is pretty weird -- `y` *should* be an `int`, not `List[int]`, and `mypy` seems to do the type inference in the `get` method just fine.

**Comment by ilevkivskyi** [comment] 2018-08-15 08:49
This doesn't work like this. You can't have arbitrary annotation on self (at least currently). There are similar requests, https://github.com/python/mypy/issues/5320, https://github.com/python/mypy/issues/5305. I am closing this as a duplicate of those.

**Closed by ilevkivskyi** 2018-08-15 08:49 UTC
