### ISSUE TITLE
Incompatible type when specifying Callable with TypeVar in function signature

### ISSUE THREAD

**Issue by pganssle** [python/mypy#14023] opened 2022-11-07 15:20 UTC
**Bug Report**
When a parameter is a `Callable` that takes a `TypeVar`, for whatever reason `mypy` throws the error:

> Argument X has incompatible type "type"; expected "_T"

This does not happen if the variable representing the callable is defined in the function itself, and it doesn't happen with `pytype`.

**To Reproduce**

```python
import typing
from collections.abc import Iterable
from typing import Callable

_T = typing.TypeVar("_T")

def bad_func(
    a: Iterable[int],
    wrapper: Callable[[_T], _T],
) -> None:
    for v in wrapper(a):
        print(v + 2)
```

Running this fails with:

> main.py:11: error: "_T" has no attribute "__iter__" (not iterable)
> main.py:11: error: Argument 1 has incompatible type "Iterable[int]"; expected "_T"

This also fails if you are more explicit about the fact that the `Callable` takes a container and returns the same container, generic over the same type:

```python
def bad_func_iterable(
    a: Iterable[int],
    wrapper: Callable[[Iterable[_T]], Iterable[_T]],
) -> None:
    # error: Argument 1 has incompatible type "Iterable[int]"; expected "Iterable[_T]"
    for v in wrapper(a):
        # error: Unsupported operand types for + ("_T" and "int")
        print(v + 2)

def bad_func_with_list(
    a: list[int],
    wrapper: Callable[[list[_T]], list[_T]],
) -> None:
    # error: Argument 1 has incompatible type "List[int]"; expected "List[_T]"
    for v in wrapper(a):
        # error: Unsupported operand types for + ("_T" and "int")
        print(v + 2)
```

If the variable `wrapper` is moved out of the function signature and into the body of the function, the problem goes away:

```python
def echoer(p: Iterable[_T]) -> Iterable[_T]:
    for v in p:
        print(v)
        yield v


def defined_inline(a: Iterable[int]) -> None:
    wrapper: Callable[[Iterable[_T]], Iterable[_T]] = echoer
    for v in wrapper(a):
        print(v + 2)
```

Here is a playground link including all these versions:
https://mypy-play.net/?mypy=latest&python=3.10&gist=5883bea46dae7d08f35be501d1109283

Sorry if this has been reported before, it's kinda hard to search for this.

**Your Environment**

- Mypy version used: 0.981
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): None
- Python version used: 3.9, 3.10, 3.11

**Comment by erictraut** [comment] 2022-11-07 16:03
The problem is that you're using the type variable `_T` within the function signature `bad_func`. When a TypeVar is used, it must be associated with a particular scope. Scopes can include classes, functions, or type aliases. In your example, there is an ambiguity about whether `_T` is intended to be scoped to `bad_func` or the `Callable` associated with parameter `wrapper`. I think your intent is the latter, but mypy interprets it as the former. I think mypy's interpretation is arguably more correct, and it's how pyright also interprets this code.

If you want `_T` to be scoped to the `Callable`, you can do so by creating a separate type alias, like this:

```python
import typing
from collections.abc import Iterable
from typing import Callable

_T = typing.TypeVar("_T")

Identity = Callable[[_T], _T]

def bad_func(
    a: Iterable[int],
    wrapper: Identity
) -> None:
    for v in wrapper(a):
        print(v + 2)
```

This type checks fine in mypy and pyright.

**Comment by erictraut** [comment] 2022-11-07 16:06
Actually, my analysis above is wrong because the type annotation `Identity` is interpreted as `Identity[Any]` by mypy and pyright (because it's referring to a generic type alias with one type parameter, but no corresponding type argument is provided). That's not what you're looking for.

**Comment by pganssle** [comment] 2022-11-07 17:02
> Actually, my suggested fix is wrong because the type annotation `Identity` is interpreted as `Identity[Any]` by mypy and pyright (because it's referring to a generic type alias with one type parameter, but no corresponding type argument is provided). That's not what you're looking for.
> 
> In any case, I don't think this is a bug in mypy. It is correctly interpreting `_T` as being scoped to `bad_func`, which means that the expression `wrapper(a)` is a type violation.

To be clear, are you saying that this should be a feature request instead of a bug report? It seems like you are saying that there's no way to express the concept "This parameter accepts a function which takes as input something of type `T` and returns something of type `T`" (or all the variations on that, like "This accepts a sequence of T and returns a set of T", etc), or maybe you are just saying that you cannot think of one?

**Comment by pganssle** [comment] 2022-11-07 17:22
> Actually, my suggested fix is wrong because the type annotation `Identity` is interpreted as `Identity[Any]` by mypy and pyright (because it's referring to a generic type alias with one type parameter, but no corresponding type argument is provided). That's not what you're looking for.
> 
> In any case, I don't think this is a bug in mypy. It is correctly interpreting `_T` as being scoped to `bad_func`, which means that the expression `wrapper(a)` is a type violation.

To be clear, are you saying that this should be a feature request instead of a bug report? It seems like you are saying that there's no way to express the concept "This parameter accepts a function which takes as input something of type `T` and returns something of type `T`" (or all the variations on that, like "This accepts a sequence of T and returns a set of T", etc), or maybe you are just saying that you cannot think of one?

I'm also not entirely convinced that there's *nothing* to do here, since at the very least this is a very confusing error message, but also I don't really see the problem with the scoping. Even if we assume that `_T` is scoped to the function, `Callable[[Iterable[_T]], [_T]]` should type check correctly, since we know that the callable is taking an iterable of `_T` and returning an iterable of `_T`. If `_T` shows up elsewhere in the function signature, that would just be a further bound on what `_T` can be (which, admittedly, may be confusing for people who thought that `Callable[[_T], _T]` would be self-contained).

Compare [this](https://mypy-play.net/?mypy=latest&python=3.10&gist=9d106dd94d6f4856b078c7b760c3c6ee) (error):

```python
from typing import Callable, TypeVar, Iterable

T = TypeVar("T")

def f(a: int, g: Callable[[Iterable[T]], Iterable[T]]) -> int:
    for b in g([a] * 3):
        print(b)
    
    return b
```

to [this](https://mypy-play.net/?mypy=latest&python=3.10&gist=fa6795c57dc130db0e4999b7b3dadc3f) (success):

```python
from typing import Callable, TypeVar, Iterable

T = TypeVar("T")

def f(a: T, g: Callable[[Iterable[T]], Iterable[T]]) -> T:
    for b in g([a] * 3):
        print(b)
    
    return b
```

Even if you are scoping `T` to the function, there's no reason that both shouldn't work. `mypy` should be inferring that `T` is `int` in the error case, but it's not.

If this is some situation where `mypy` is trying to save people from accidentally using an incorrectly-scoped function, then at least the error should be in the function definition, saying something like, "Scope of `T` is ambiguous" or something of that nature. From what I can tell, without actually adding another `T` into the function, any attempt to actually *use* the callable would lead to an error, so you may as well be eager about it and not give an error message about the contents not satisfying the bounds despite the fact that they definitely seem to satisfy the bounds.

**Comment by pganssle** [comment] 2022-11-07 19:17
Thinking a bit more deeply about the scoping, I think I understand what's going on. What you are saying about the function scope is that `T` should be the same *for the duration of the function whose signature it is declared in*, so if `T` is scoped to the function, this should be an error:

```python
def f(a: Sequence[int], b: Sequence[str], g: Callable[[T], T]) -> None:
    for a_val in g(a):
        print(a_val)

    for b_val in g(b):
        print(b_val)
```

That is fair, though it still leaves open the question of giving a better error message, and also the question of how to actually express this.

Incidentally, it also seems that this works fine in `pytype`, I even tested [this gist](https://mypy-play.net/?mypy=latest&python=3.11&gist=f48d3f16edf88793d82c41d92098ac17) with `pytype` and it does the right thing, so this doesn't seem like a case where `pytype` is silently turning `Callable[[T], T]` into `Callable[[Any], Any]` like the `Identity` type alias above. I'm curious to know — if `mypy`'s behavior is correct for the specified scoping rules of type hinting, is this actually a bug in `pytype`? Or is this basically undefined or under-defined behavior and `pytype` simply made a different choice?

**Comment by erictraut** [comment] 2022-11-08 02:00
The Python type system doesn't provide a way to specify the scope of a type variable explicitly. PEP 484 discusses the basics of [scoping rules](https://peps.python.org/pep-0484/#scoping-rules-for-type-variables), but it leaves much undefined. In other languages that support generics, the scope of a type variable is always explicit, so there is no ambiguity. In Python, the scope of a type variable is implicit — and in some cases subject to interpretation. Type checkers need to apply their own heuristics or rules in these cases. Draft [PEP 695](https://peps.python.org/pep-0695/) (which I wrote) attempts to make scoping more explicit.

To the best of my knowledge, mypy, pyright and pyre apply the following rules: If a type variable appears within an annotated parameter for a function, it is scoped to that function. If a type variable appears within a return type, it is also generally scoped to the function, but if it appears within a Callable and appears nowhere else outside of the Callable, it is scoped to the Callable.

```python
from typing import Callable, TypeVar

T = TypeVar("T")

def func1(x: T) -> Callable[[T], T]: ... # T is scoped to func1

v1 = func1("")
reveal_type(v1) # (str) -> str

v1_result = v1(3) # type error


def func2(x: str) -> Callable[[T], T]: ... # T is scoped to Callable

v2 = func2("")
reveal_type(v2) # (T) -> T

v2_result = v2(3)
reveal_type(v2_result) # int
```

Pytype appears to differ from the other (more widely-used) type checkers in how it applies scoping rules.

I think the rule used by mypy, pyright and pyre is defensible and principled, so it's unlikely that you will convince the maintainers of these type checkers to switch to the rule used by pytype.

**Comment by glyph** [comment] 2022-11-08 05:22
To restate the desired behavior that @pganssle wants here:

- have a function that takes a callable that is `(anything) -> anything`
- *do not expose the fact* that all that is actually required by the *implementation right now* is `(Iterable[int]) -> Iterable[int]`
- *allow the implementation* to rely on the fact that `Iterable[int]` is in fact a valid `anything` and treat it as such in the appropriate scope.

This cannot be spelled `wrapper: Callable[[T], T]` because by specifying the type var in that position, in mypy's type language, we are specifically saying that *the caller may choose a `T` of their preference*, and so any attempt to wrangle this type variable into different positions will fail, as long as it is present in the function's signature or even its return value: callers are allowed to impose their own expectations on type variables specified in signatures, unless a bound is used (and a bound does the opposite of what we want here; requiring more specific subtypes rather than what we want which is *disallowing* more specific subtypes).

So, to make this happen, we need a separate type variable, specified elsewhere, *outside* of the signature so it is not exposed to callers.  We can in fact use a `bound` for this, by establishing a `bound` on `wrapper` rather than on `_T`.  [Solution on the Mypy playground here](https://mypy-play.net/?mypy=latest&python=3.10&gist=7e240794bc365d5ff6fb13c8ccc192a2&flags=strict):
```python3
from typing import Callable, Iterable, TypeVar

_U = TypeVar("_U")
_W = TypeVar("_W", bound=Callable[[_U], _U])

def good_func(a: Iterable[int], wrapper: _W) -> None:
    for v in wrapper(a):
        print(v + 2)
```

**Comment by glyph** [comment] 2022-11-08 06:35
Playing around with this in TypeScript, I realized that it is the difference between

```typescript
function bad+func<T>(a: Iterable<number>, wrapper: (o: T) => T): void {...}
```

and

```typescript
function good_func(a: Iterable<number>, wrapper: <T>(o: T) => T): void {...}
```

and I wonder if it would be worth allowing for inline `TypeVar` definitions to mirror this possibility.  Perhaps I've just hard-boiled my brain on this little type puzzle, but something like this:

```python3
def good_func(
    a: Iterable[int], wrapper: TypeVar("_W", bound=Callable[[_U := TypeVar("_U")], _U])
):
    ...
```

Technically speaking, this is not even a syntax error…

**Comment by erictraut** [comment] 2022-11-08 07:41
@glyph, I think your summary is correct.

Your proposed solution won't work for a couple of reasons. First, the upper bound of a TypeVar must be concrete. It is not allowed to contain TypeVars. This is specified in PEP 484.

> <type> itself cannot be parameterized by type variables

Second, assignment expressions are not (and should not) be allowed within type annotations.

If you want to suggest or explore extensions to the current type system, it's probably best to do so in the [python/typing discussion](https://github.com/python/typing/discussions) forum rather than a mypy bug report. This would need to be properly spec'ed, reviewed, and agreed upon by all type checkers.

**Comment by glyph** [comment] 2022-11-08 08:59
> Your proposed solution won't work for a couple of reasons. First, the upper bound of a TypeVar must be concrete. It is not allowed to contain TypeVars. This is specified in PEP 484.

That's… interesting, because it *does* work.  Like, mypy type checks it and exits without errors, `reveal_type` gives me the expected types in the body of the function, and I get type errors if I do invalid things with the result.

**Comment by glyph** [comment] 2022-11-08 09:00
(Not my wacky walrus-operator abomination; I realize that is not going to work and maybe it never should)

**Comment by erictraut** [comment] 2023-08-14 00:20
I think mypy is working correctly in this case. I recommend closing.

**Comment by hauntsaninja** [comment] 2023-08-24 08:13
Closing as per above.

I find using an explicit callback protocol can clarify that the type var is scoped only to the call
```
class IdentityFunction(Protocol):
    def __call__(self, __x: _T) -> _T: ...
```

**Closed by hauntsaninja** 2023-08-24 08:13 UTC
Labels: bug
