### ISSUE TITLE
Add typing.FrozenSet

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#641] opened 2015-04-17 05:29 UTC
`typing.FrozenSet` is defined in the PEP 484 draft.

**Comment by gvanrossum** [comment] 2016-08-14 02:37
It's now in typeshed (python/typeshed#474) and in the upstream typing.py (python/typing#261). It's now a simple matter of syncing typeshed and copying the latest typing.py, which we don't track in the tracker.

(Also, duplicate of #1283.)

**Closed by gvanrossum** 2016-08-14 02:37 UTC
Labels: feature, pep484
