### ISSUE TITLE
Running mypy on `import pyspark.sql.functions` results in segmentation fault

### ISSUE THREAD

**Issue by kjun9** [python/mypy#7583] opened 2019-09-30 06:02 UTC
* Are you reporting a bug, or opening a feature request?

Reporting a bug

* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.

`mypy -c 'import pyspark.sql.functions'`

* What is the actual behavior/output?

```
$ mypy -c 'import pyspark.sql.functions'
Segmentation fault: 11
```

* What is the behavior/output you expect?

Assuming there is a problem with `pyspark-stubs` (as I've filed here https://github.com/zero323/pyspark-stubs/issues/245), I would expect `mypy` to produce some sort of actual error rather than a seg fault.

* What are the versions of mypy and Python you are using?

`mypy==0.730` and python 3.7.4
(and `pyspark-stubs==2.4.0.post6` and `pyspark==2.4.3` for the minimal example)

* What are the mypy flags you are using? None

**Comment by zero323** [comment] 2019-09-30 08:20
This is a duplicate of #7243.

**Closed** 2019-09-30 08:22 UTC
