### ISSUE TITLE
Applying Metaclass to int-derived classes gives 'Inconsistent metaclass structure' error.

### ISSUE THREAD

**Issue by isundaylee** [python/mypy#3563] opened 2017-06-16 17:53 UTC
On both `0.510-dev` and `0.520-dev-94e3f9cfc2510e651a0147de2626e084a7433f6d`, I have been running into the following error: 

```
error: Inconsistent metaclass structure for 'BitMask'
```

when trying to apply a metaclass to a class derived from `int` (or `float`). Repro: 

```python
class BitMaskMeta(type):
    pass

class BitMask(int, metaclass=BitMaskMeta):
    pass
```

When I change BitMask to derive from object the error goes away. Is this the expected behavior? Or a potential BUG? 

Thank you! :)

**Comment by ilevkivskyi** [comment] 2017-06-19 22:17
Thanks for reporting!

The problem that ``int`` has ``SupportsAbs``, ``SupportsInt``, etc. in bases in typeshed, this creates a spurious metaclass conflict (since the latter are instances of ``ABCMeta``). This will be super-simple to fix after protocols land (also in typeshed) by just removing those bases.

In the meantime, maybe @elazarg knows some quick workaround?

**Comment by elazarg** [comment] 2017-06-19 22:40
I think inheriting from ABCMeta is a working hack
```python
from abc import ABCMeta
class BitMaskMeta(ABCMeta):
    pass

class BitMask(int, metaclass=BitMaskMeta):
    pass
```
Alternatively, you can use `# type: ignore`:
```python
class BitMask(int, metaclass=BitMaskMeta): # type: ignore
    pass
```

**Comment by elazarg** [comment] 2017-09-15 06:28
python/typeshed#1595

**Comment by viniciusd** [comment] 2019-09-20 21:06
> I think inheriting from ABCMeta is a working hack
> 
> ```python
> from abc import ABCMeta
> class BitMaskMeta(ABCMeta):
>     pass
> 
> class BitMask(int, metaclass=BitMaskMeta):
>     pass
> ```

Tried that in a similar case, but it didn't work. Going with type ignore for now.

**Comment by ilevkivskyi** [comment] 2019-09-21 15:27
This is essentially a duplicate of the typeshed issue (or rather the other way around, but the typeshed one has more discussion). I thin kit doesn't make sense to keep both open.

**Closed by ilevkivskyi** 2019-09-21 15:27 UTC
