### ISSUE TITLE
Allow optionally preventing `bool` from being accepted as a subtype of `int` in MyPy.

### ISSUE THREAD

**Issue by stdedos** [python/mypy#16135] opened 2023-09-18 13:16 UTC
**Feature**

Allow optionally preventing `bool` from being accepted as a subtype of `int` in MyPy.

Might be related? https://github.com/python/mypy/issues/8363

**Pitch**

```py
def increment(x: int) -> int:
    return x + 1

print(increment(True))  # Outputs 2, which can be confusing
```

Python treats `bool` as a subclass of `int`, causing potential bugs when a `bool` is used where an `int` is expected. Adding a MyPy flag to reject this would improve type safety and code reliability.

_Disclaimer: I have read already https://mypy.readthedocs.io/en/stable/builtin_types.html?#simple-types_

**Comment by hauntsaninja** [comment] 2023-09-19 06:55
Yup, this is a duplicate of the feature request in https://github.com/python/mypy/issues/8363

**Closed by hauntsaninja** 2023-09-19 06:55 UTC
Labels: feature
