### ISSUE TITLE
Allow function variants with different signatures to be conditioned on sys.version_info

### ISSUE THREAD

**Issue by elazarg** [python/mypy#1801] opened 2016-07-05 14:18 UTC
Function signature may vary between versions, see e.g. dis.dis. But encoding it on typeshed is not supported by mypy:

    error: All conditional function variants must have identical signatures

**Comment by gvanrossum** [comment] 2016-07-05 16:24
Actually this is a duplicate of #689.

**Closed by gvanrossum** 2016-07-05 16:24 UTC

**Comment by elazarg** [comment] 2016-07-05 16:40
How so? 
"Implement `TypeVar(..., bound=<boundary_type>)`"

**Comment by gvanrossum** [comment] 2016-07-05 16:47
Sorry, the correct issue is #698. I'll delete the irrelevant comments.
