### ISSUE TITLE
Types from the typing module that don't exist in the specified Python version are not detected by Mypy

### ISSUE THREAD

**Issue by matthewslouismarie** [python/mypy#6593] opened 2019-03-26 12:48 UTC
Hello there,

I think this is not the desired behaviour of Mypy. If I set the version of Python to 3.5, it doesn't report Deque imports, even though this type only appeared in Python 3.6.

mypy.ini:
```
[mypy]
python_version = 3.5
```

The python code:
```
from typing import Deque

...
```

This does not report any errors with mypy 0.670.

**Comment by gvanrossum** [comment] 2019-03-26 15:52
Thanks for reporting! But it's not a flaw in mypy itself, it's in typeshed, which has a separate repo: https://github.com/python/typeshed. Please report it there!

**Comment by ilevkivskyi** [comment] 2019-04-01 18:26
These type aliases (`Deque` etc) are added dynamically by mypy for subtle reasons, so this can't be fixed in typeshed. I think we can track this as part of https://github.com/python/mypy/issues/3413 (although it is not the same issue, the two should be probably fixed together).

**Comment by gvanrossum** [comment] 2019-04-01 18:54
OK, reopening.

**Comment by AlexWaygood** [comment] 2022-03-26 13:25
Python 3.5 is no longer supported by mypy, and I can't reproduce this with any other aliases, so I'm closing this.

**Closed by AlexWaygood** 2022-03-26 13:25 UTC
