### ISSUE TITLE
Superclass fields incorrectly assumed to exist

### ISSUE THREAD

**Issue by marcoeilers** [python/mypy#2877] opened 2017-02-17 10:36 UTC
Mypy seems to always assume that classes have all fields defined in their superclass' `__init__` method, even if their own `__init__` never calls the superclass constructor and those fields therefore don't exist. 

```python
class A:
    def __init__(self) -> None:
        self.a = 12


class B(A):
    def __init__(self) -> None:
        self.b = 14


def m() -> int:
    ab = B()
    return ab.a + ab.b  # accepted by mypy, but fails at runtime
```

**Comment by ilevkivskyi** [comment] 2017-02-17 12:31
Thank you for reporting this! I think, it is an example of known behaviour: mypy does not check whether a variable was actually defined, it only checks that a variable was declared, see e.g. https://github.com/python/mypy/issues/2400

**Comment by JukkaL** [comment] 2017-02-24 13:18
Closing as a duplicate of #2400.

**Closed** 2017-02-24 13:18 UTC
