### ISSUE TITLE
Subclassing a contextmanager fails

### ISSUE THREAD

**Issue by euresti** [python/mypy#2469] opened 2016-11-18 23:00 UTC
```
from contextlib import contextmanager
from typing import Iterator

class Foo(object):
    @contextmanager
    def bar(self):
        # type: () -> Iterator[int]
        yield 4

class Bar(Foo):
    @contextmanager
    def bar(self):
        # type: () -> Iterator[int]
        yield 3

reveal_type(Foo.bar)
reveal_type(Bar.bar)
```
Fails thus:
```
t5.py: note: In class "Bar":
t5.py:12: error: Signature of "bar" incompatible with supertype "Foo"
t5.py: note: At top level:
t5.py:17: error: Revealed type is 'def (*Any, **Any) -> contextlib.ContextManager[builtins.int*]'
t5.py:18: error: Revealed type is 'def (*Any, **Any) -> contextlib.ContextManager[builtins.int*]'
```

**Comment by JukkaL** [comment] 2017-01-16 11:56
You can use `# type: ignore` as a workaround.

**Comment by thomasballinger** [comment] 2017-01-19 00:47
Seems like the same bug, if so this is more general than contextmanager.

~~~.py
def arbitrary_decorator(f):
    return f

class Foo(object):
    @arbitrary_decorator
    def bar(self):
        # type: () -> int
        return 4

class Bar(Foo):
    @arbitrary_decorator
    def bar(self):
        # type: () -> int
        return 3

reveal_type(Foo.bar)
reveal_type(Bar.bar)
~~~
gives
~~~
tmp.py:12: error: Signature of "bar" incompatible with supertype "Foo"
tmp.py:16: error: Revealed type is 'Any'
tmp.py:17: error: Revealed type is 'Any'
~~~

**Comment by FuegoFro** [comment] 2017-08-01 18:57
Is this a duplicate of https://github.com/python/mypy/issues/1441? Also is this possibly related to the forward referencing issue listed in https://github.com/python/mypy/issues/2907#issuecomment-284542711?

**Comment by JukkaL** [comment] 2017-08-08 17:22
Yes, this looks like a duplicate of #1441. This likely isn't related to forward references.

**Closed by JukkaL** 2017-08-08 17:22 UTC
Labels: bug, priority-1-normal
