### ISSUE TITLE
dmypy does not recheck files when they are removed and then re-added.

### ISSUE THREAD

**Issue by ramLlama** [python/mypy#5343] opened 2018-07-10 17:06 UTC
* Are you reporting a bug, or opening a feature request?
Bug
* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.

In a folder, have two files `test1.py` and `test2.py`. Contents are:

test1.py:
```
x: str = 1
```

test2.py:
```
y: int = 'hello'
```

* What is the actual behavior/output?
```
$ python -m mypy --follow-imports=skip --ignore-missing-imports --cache-fine-grained test1.py
test1.py:1: error: Incompatible types in assignment (expression has type "int", variable has type "str")
$ python -m mypy --follow-imports=skip --ignore-missing-imports --cache-fine-grained test2.py
test2.py:1: error: Incompatible types in assignment (expression has type "str", variable has type "int")
$ dmypy start -- --follow-imports=skip --ignore-missing-imports --use-fine-grained-cache
Daemon started
$ dmypy check test1.py
test1.py:1: error: Incompatible types in assignment (expression has type "int", variable has type "str")
$ dmypy check test1.py
test1.py:1: error: Incompatible types in assignment (expression has type "int", variable has type "str")
$ dmypy check test2.py
test2.py:1: error: Incompatible types in assignment (expression has type "str", variable has type "int")
$ dmypy check test2.py
test2.py:1: error: Incompatible types in assignment (expression has type "str", variable has type "int")
$ dmypy check test1.py
$ dmypy check test2.py
$
```
* What is the behavior/output you expect?
I expect that files are rechecked and errors re-outputted after being removed and then re-added to `dmypy`.
* What are the versions of mypy and Python you are using?
mypy 0.610, python 3.6.3

**Comment by msullivan** [comment] 2018-11-01 22:15
Self-assigning this because I'm about to rampage through the relevant code and think a fix for this might come out the other end.

**Comment by msullivan** [comment] 2020-06-18 06:48
This might have gotten fixed though?

**Comment by JukkaL** [comment] 2020-06-19 13:24
This still seems to be an issue. I was able to reproduce the problem with using `dmypy run -- <files>`. Increasing priority since this is pretty bad. Also I somehow got errors from typeshed by doing this.

**Closed** 2023-06-15 20:32 UTC
Labels: bug, priority-0-high, topic-daemon, topic-fine-grained-incremental
