### ISSUE TITLE
How sys.platform is imported matters when doing system platform checks

### ISSUE THREAD

**Issue by sajith** [python/mypy#10054] opened 2021-02-09 20:18 UTC
**Bug Report**

According to [Mypy manual](https://mypy.readthedocs.io/en/stable/common_issues.html#python-version-and-system-platform-checks), I should be able to omit checks on whole modules by adding these lines:

```python
import sys
assert sys.platform == 'win32'
```

That works fine, but this does not:

```python
from sys import platform
assert platform == 'win32'
```

**To Reproduce**

I want mypy to omit checking some Windows-specific modules when running it on a non-Windows platform.  This works fine:

```python
# good.py

import sys
assert sys.platform == "win32"

from ctypes import WINFUNCTYPE, windll, WinError, get_last_error
```

But the other equivalent import does not:

```python
# bad.py

from sys import platform
assert platform == "win32"

from ctypes import WINFUNCTYPE, windll, WinError, get_last_error
``` 

Running mypy on the latter would result in some error messages:

```
bad.py:6: error: Module 'ctypes' has no attribute 'WINFUNCTYPE'; maybe "CFUNCTYPE" or "PYFUNCTYPE"?
bad.py:6: error: Module 'ctypes' has no attribute 'windll'
bad.py:6: error: Module 'ctypes' has no attribute 'WinError'
bad.py:6: error: Module 'ctypes' has no attribute 'get_last_error'
Found 4 errors in 1 file (checked 1 source file)
```

**Expected Behavior**

How I import `sys.platform` should not matter.

**Actual Behavior**

How I import `sys.platform` matters.

**Your Environment**

- Mypy version used: 0.800
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): `ignore_missing_imports = True` and `plugins=mypy_zope:plugin`
- Python version used: Python 3.6.5 on Ubuntu, Python 3.9.1 on Debian
- Operating system and version:  Ubuntu 18.04.5 LTS and Debian GNU/Linux bullseye/sid

(The actual error turned up in tahoe-lafs project's CI.  Log should be available [here](https://app.circleci.com/pipelines/github/LeastAuthority/tahoe-lafs/202/workflows/e822884d-6b4f-49eb-b001-4ebf384ae9f2/jobs/3148) or [here](https://circleci.com/api/v1.1/project/github/LeastAuthority/tahoe-lafs/3148/output/102/0?file=true&allocation-id=6022a84439074b22dc196f6e-0-build%2F54861AC1).  Corresponding PR is tahoe-lafs/tahoe-lafs/pull/964.)

**Comment by AlexWaygood** [comment] 2022-04-01 01:52
See discussion in #6189

**Comment by hauntsaninja** [comment] 2023-08-13 20:49
Closing as a duplicate of https://github.com/python/mypy/issues/6189.

**Closed by hauntsaninja** 2023-08-13 20:49 UTC
Labels: feature, priority-2-low
