### ISSUE TITLE
mypi has not been updated to 1.5.1

### ISSUE THREAD

**Issue by timsoftgit** [python/mypy#15885] opened 2023-08-16 08:38 UTC
[mypi](https://pypi.org/project/mypy/#files) is still at 1.5.0.
mypy source on Mypi is use for packaging as git source misses out sub-packages.
Is this automated?. how long does it take for mypi to be updated? it's currently 5 days
thanks, Tim

**Comment by AlexWaygood** [comment] 2023-08-16 09:01
Duplicate of #15857

**Closed by AlexWaygood** 2023-08-16 09:01 UTC

**Comment by timsoftgit** [comment] 2023-08-16 19:41
I got a reply form pypi saying they have increased the project size limit up to 20GB, so hopefully that will allow updates to go to pypi again. :-) (ref https://github.com/pypi/support/issues/3094  )

**Comment by AlexWaygood** [comment] 2023-08-16 19:42
Yes, mypy 1.5.1 has now been uploaded

**Comment by timsoftgit** [comment] 2023-09-20 16:37
thanks
