### ISSUE TITLE
Name `__path__` is not defined (for `__init__.py` module)

### ISSUE THREAD

**Issue by asottile** [python/mypy#5209] opened 2018-06-12 21:48 UTC
Simplest reproduction:

```python
# t/__init__.py
print(__path__)
```

```console
$ python3 -c 'import t'
['/private/tmp/t']
```

```
$ mypy t
t/__init__.py:1: error: Name '__path__' is not defined
```

**Comment by ilevkivskyi** [comment] 2018-06-13 10:59
Duplicate of #1422

**Closed by ilevkivskyi** 2018-06-13 10:59 UTC
