### ISSUE TITLE
False-negative when instantiating a class before its constructor is defined

### ISSUE THREAD

**Issue by megapctr** [python/mypy#2324] opened 2016-10-25 12:50 UTC
I've found a small bug:

```
class Operation:

    @classmethod
    def randomize(cls, config: Config) -> 'Operation':
        return cls(config)

    def __init__(self, config: Config) -> None:
        self.config = config
```

This complains at line 5, `Too many arugments for "Operation"`. Swapping these two methods around (init before randomize) fixed the issue.

Looks like mypy tried to type-check `cls(config)` before learning what `Operation`'s constructor looks like.

**Comment by gvanrossum** [comment] 2016-10-25 17:41
Oh, interesting. This could be dealt with by deferring the first method when the class signature isn't known yet. But we'd need some kind of flag to tell us whether we've processed `__init__` yet (and maybe if there isn't one it should be set to True at the start, by the semantic analyzer).

Do you feel up to trying to submit a PR for this? No pressure!

**Comment by megapctr** [comment] 2016-10-25 21:30
I could work on that, any tips what module/function to begin from?

**Comment by gvanrossum** [comment] 2016-10-27 15:48
Best place to get help would be https://gitter.im/python/mypy.

**Comment by JukkaL** [comment] 2017-12-05 17:48
Bumping priority because this seem to happen with some frequency and the workaround is not easy to figure out.

**Comment by JelleZijlstra** [comment] 2017-12-05 20:02
This is a dupe of #1727, which is older and has more discussion; going to close this one and make the other one high-pri.

**Closed by JelleZijlstra** 2017-12-05 20:02 UTC
Labels: bug, priority-0-high

**Comment by mckaysalisbury** [comment] 2017-12-06 05:02
It seems as if any method can call any method, so a two-pass system might work best. Once to process all of the function signatures, then another to process the code.

**Comment by gvanrossum** [comment] 2017-12-06 15:48
Thanks for the advice.
