### ISSUE TITLE
Specilizing Union method parameters on subclasses

### ISSUE THREAD

**Issue by athoscouto** [python/mypy#6411] opened 2019-02-15 17:31 UTC
**Feature Request**
Extend feature added in https://github.com/python/mypy/issues/424 to allow subclasses to also specialize method parameters that contain `Union` type.

**Code example**
```python
class A():
    def x(self, x: Union[Dict, List]):
        pass


class B(A):
    def x(self, x: Dict):
        pass
```

**mypy output**
` error: Argument 1 of "x" incompatible with supertype "A"`

**Expected output**
Nothing :)

**mypy/python version**
mypy 0.641
Python 3.6.7

**Comment by intgr** [comment] 2020-02-20 10:16
I think this issue is mistaken. The contract of A states "all A classes contain method x that accepts argument `Union[Dict, List]`".

The method B.x violates that contract because it does not accept `List`.

**Comment by intgr** [comment] 2020-02-20 10:23
This is basically duplicate of #1237.

**Comment by JukkaL** [comment] 2020-02-20 11:54
Yeah, the method in `B` violates Liskov substitution principle (https://en.wikipedia.org/wiki/Liskov_substitution_principle).

**Closed by JukkaL** 2020-02-20 11:54 UTC
