### ISSUE TITLE
No way to annotate class definition - inherited classes in a type comment

### ISSUE THREAD

**Issue by nmatthews-asapp** [python/mypy#5824] opened 2018-10-23 16:20 UTC
* Are you reporting a bug, or opening a feature request?
**Feature Request**

* Please insert below the code you are checking with mypy
The following raises a MyPy error
```python
from multiprocessing import Queue
from functools import partial
...

class TestQueue(Queue):
    pass

class TestPartial(partial):
    pass

... # other examples abound

```
In these situations, the temporary MyPy error (typeshed's fault) could be avoided if there were a way to do something like the following:
```python
class TestQueue(Queue):  # type: Queue[str]
```
but to my knowledge this doesn't exist. As a reminder, something like
```python
class TestQueue(Queue[str]):
```
will fail at run time.
https://stackoverflow.com/questions/45414066/mypy-how-to-define-a-generic-subclass

* What is the actual behavior/output?
There does not exist a way to annotate Generic superclasses with comment annotations. End of line type comment and a type comment immediately following the argument both raise a `misplaced type annotation` error

* What is the behavior/output you expect?
A method for using a comment to annotate in this use-case, to avoid lagging typeshed errors

* What are the versions of mypy and Python you are using?
Python 3.6

**Comment by ilevkivskyi** [comment] 2018-10-23 16:54
This is essentially a duplicate of https://github.com/python/mypy/issues/5667

You can use:
```python
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    BaseQueue = Queue[int]
else:
    BaseQueue = Queue
```

**Closed by ilevkivskyi** 2018-10-23 16:54 UTC

**Comment by JukkaL** [comment] 2018-10-24 09:09
Maybe the workaround should be covered in the documentation?

**Comment by ilevkivskyi** [comment] 2018-10-24 10:45
Yes, added the comment in the other issue. I think I will make a PR now.
