### ISSUE TITLE
"Invalid class method type" calling classmethod from instance on NamedTuple

### ISSUE THREAD

**Issue by Daenyth** [python/mypy#3791] opened 2017-08-02 12:21 UTC
mypy==0.521

foo.py:

```python
from typing import *

class Foo(NamedTuple):
    x: int

    @classmethod
    def bar(cls) -> str:
        return cls.__name__

f = Foo(1)
y: str = f.bar() # Line 11 here
```

> foo.py:11: error: Invalid class method type

This is specific to NamedTuples. The following class doesn't trigger the same error:
```python
class Foo:
    def __init__(self, x: int) -> None:
        self.x = x

    @classmethod
    def bar(cls) -> str:
        return cls.__name__
```

**Comment by ilevkivskyi** [comment] 2017-08-02 12:30
This is quite low priority, named tuples are intended to be "minimalistic", for all other things now-discussed dataclasses should be used.

cc @JelleZijlstra

**Comment by Daenyth** [comment] 2017-08-02 12:39
Dataclasses would definitely solve my use case if they were in the version of python I'm using.

**Comment by ilevkivskyi** [comment] 2017-10-25 08:37
FWIW this is fixed in master. I can reproduce the error and revealed types are correct.

**Closed by ilevkivskyi** 2017-10-25 08:37 UTC
Labels: bug, priority-2-low, topic-named-tuple
