### ISSUE TITLE
Allow a type of Zero

### ISSUE THREAD

**Issue by gappleto97** [python/mypy#5203] opened 2018-06-11 23:36 UTC
I am requesting a feature. Often people want to be able to `sum()` their value types together. This is made easiest if their value types can accept an addition of 0. But the signature on such a method implies that it can accept any integer, which is false. The smallest working example would be:

```python
from typing import Union


class Value(object):
    def __init__(self, val: int) -> None:
        self._value = val

    def __add__(self, other: Union[int, 'Value']) -> 'Value':
        if isinstance(other, Value):
            return Value(self._value, other._value)
        elif other == 0:
            return self
        else:
            return NotImplemented

sum((Value(1), Value(3))
```

It would be nice if this code could instead be written as:

```python
from typing import Union, Zero


class Value(object):
    def __init__(self, val: int) -> None:
        self._value = val

    def __add__(self, other: Union[Zero, 'Value']) -> 'Value':
        if isinstance(other, Value):
            return Value(self._value, other._value)
        elif other == 0:
            return self
        else:
            return NotImplemented

sum((Value(1), Value(3))
```

This more clearly communicates the intent of the method.

**Comment by ilevkivskyi** [comment] 2018-06-12 00:56
This is a duplicate of https://github.com/python/mypy/issues/3062 which is already on our short/medium term roadmap. With the literal types you will be able to just write `Zero = Literal[0]`.

**Closed by ilevkivskyi** 2018-06-12 00:56 UTC

**Comment by gvanrossum** [comment] 2018-06-12 01:30
I'm also curious where the convention to just start with `0` comes from. Do you have any examples of real code that uses that? (I understand the principle, I am just wondering who would do such a thing.)

**Comment by gappleto97** [comment] 2018-06-12 02:58
I dont have a real example off the top of my head, except for code I was working on for a book club (Test Driven Development by Example). The book was written with Java in mind, and we decided that we should each implement it in our favorite language.

**Comment by gvanrossum** [comment] 2018-06-12 03:11
OK, thanks.

**Comment by pawelswiecki** [comment] 2018-10-28 11:44
I think `Union[Literal[0], Value]` or `Union[Literal[False], Value]` is analogous to `Union[None, Value]`, that is to `Optional[Value]`.
