### ISSUE TITLE
Spurious "too many arguments" with Callables in dataclasses

### ISSUE THREAD

**Issue by prophile** [python/mypy#6301] opened 2019-02-01 13:38 UTC
mypy produces a spurious "too many arguments" error on the following code:

```python
from dataclasses import dataclass
from typing import Any, Callable

@dataclass
class Foo:
    bar: Callable[[Any], Any]

instance = Foo(bar=print)
instance.bar("Hello, world!")
```

Logs:

```bash
$ python --version
Python 3.7.2
$ mypy --version
mypy 0.660
$ python mypyfail.py
Hello, world!
$ mypy --strict mypyfail.py
mypyfail.py:9: error: Too many arguments
```

This appears to be because mypy treats the first argument as if it were `self`. Changing the type of that first argument to `str` produces the following errors:

```
mypyfail.py:9: error: Invalid self argument "Foo" to attribute function "bar" with type "Callable[[str], Any]"
mypyfail.py:9: error: Too many arguments
```

There is no error when using `NamedTuple`:

```python
from typing import Any, Callable, NamedTuple

class Foo(NamedTuple):
    bar: Callable[[Any], Any]

instance = Foo(bar=print)
instance.bar("Hello, world!")
```

```bash
$ mypy --strict mypyfail_namedtuple.py
$ python mypyfail_namedtuple.py
Hello, world!
```

There is no error when implementing this with plain classes:

```python
from typing import Any, Callable

class Foo:
    def __init__(self, bar: Callable[[Any], Any]) -> None:
        self.bar = bar

instance = Foo(bar=print)
instance.bar("Hello, world!")
```

```bash
$ mypy --strict mypyfail_namedtuple.py
$ python mypyfail_namedtuple.py
Hello, world!
```

**Comment by ilevkivskyi** [comment] 2019-02-01 22:44
This is a duplicate of https://github.com/python/mypy/issues/5485

(also there is a proposed workaround in that issue)

**Closed by ilevkivskyi** 2019-02-01 22:44 UTC
