### ISSUE TITLE
Return type of class decorator is ignored

### ISSUE THREAD

**Issue by NeilGirdhar** [python/mypy#16241] opened 2023-10-09 20:54 UTC
MyPy seems to ignore the return type of class decorators.  @AlexWaygood 's suggested I create a minimal repro of this problem:
```python
from typing import Any

class T:
    y: int

def some_decorator(cls: type[Any]) -> type[T]:
    cls.y = 1
    return cls

@some_decorator
class X:
    a: int

def f(x: X) -> None:
    print(x.y)  # No attribute!
```

 This makes it impossible to define a dataclass transform that produces ordinary dataclasses:
```python
import dataclasses
from dataclasses import replace
from typing import Any, ClassVar, Protocol, dataclass_transform


class DataclassInstance(Protocol):
    __dataclass_fields__: ClassVar[dict[str, dataclasses.Field[Any]]]


@dataclass_transform()
def dataclass(cls: type[Any]) -> type[DataclassInstance]:
    return dataclasses.dataclass(cls)

@dataclass
class X:
    a: int

def f(x: X) -> X:
    return replace(x, a=1)  # Error: dataclass expected
```

**Comment by JelleZijlstra** [comment] 2023-10-09 20:56
Duplicate of #3135?

**Comment by NeilGirdhar** [comment] 2023-10-09 20:57
@JelleZijlstra Not exactly.  If I write it the other way `X = some_decorator(X)`, then I get:
```python
m.py:12: error: Cannot assign to a type  [misc]
m.py:12: error: Incompatible types in assignment (expression has type "type[T]", variable has type "type[X]")  [assignment]
m.py:15: error: "X" has no attribute "y"  [attr-defined]
```

**Comment by NeilGirdhar** [comment] 2023-10-09 21:00
I can see that the decorator is rightly skipping these checks, but the decorator's return type seems to be ignored.  I think it should be assigned to the name it decorates (in this case, `X`)

**Comment by erictraut** [comment] 2023-10-09 21:08
This is covered by #11117.

**Comment by JelleZijlstra** [comment] 2023-10-09 21:15
> Not exactly. If I write it the other way X = some_decorator(X), then I get:

Those errors look correct. After you define a class, mypy won't let you reassign its name.

> I can see that the decorator is rightly skipping these checks, but the decorator's return type seems to be ignored. I think it should be assigned to the name it decorates (in this case, X).

That's #3135, right? In any case I don't think mypy is misinterpreting your code. If you annotate your decorator with `@dataclass_transform`, you assert that it returns the same class with dataclass-like semantics. The return type annotation doesn't matter there.

If your request is that mypy infers an intersection type in this particular case, that seems out of scope until intersections are actually part of the type system.

**Comment by NeilGirdhar** [comment] 2023-10-09 21:57
> Those errors look correct. After you define a class, mypy won't let you reassign its name.

Yeah, both of these checks do make sense.  No argument there.

> That's #3135, right?

Yes, sorry I didn't see [this comment](https://github.com/python/mypy/issues/3135#issuecomment-305407751), which covers my case.

> In any case I don't think mypy is misinterpreting your code. If you annotate your decorator with `@dataclass_transform`, you assert that it returns the same class with dataclass-like semantics. The return type annotation doesn't matter there.

It dependso n what you mean by "dataclass-like semantics".  My problem is that `@dataclass_transform` does not (and should not) assert that it returns the same class, but inheriting from `DataclassLike`—that is, a so-decorated class won't be passable to `fields` and `replace`.  I initially thought so too, but if you look at the referring issue, you see [this comment](https://github.com/python/mypy/issues/15843#issuecomment-1695896735).

> If your request is that mypy infers an intersection type in this particular case, that seems out of scope until intersections are actually part of the type system.

Yes, I know. I'm just pointing that out so that we don't debate about the lost type information (`type[T]`) from applying the decorator.

> This is covered by #11117.

Yes, exactly right, thanks.

In any case, I guess we can close this as a duplicate of #3135.  Seems to me that fixing that should fix the two examples I gave above?

**Closed** 2023-10-09 22:03 UTC
Labels: bug
