### ISSUE TITLE
Type narrowing / type guard fails to work in an inner function

### ISSUE THREAD

**Issue by colinfang** [python/mypy#13020] opened 2022-06-25 12:31 UTC
Mypy: v0.961
Python: v3.10

```python
def f(g: Callable[[str], None] | None = None) -> None:
    g = g or print
    g('a') # type guard works, mypy ok
    def h() -> None:
        g('a') # type guard fails, mypy thinks it could be `None`
    h()
```

**Comment by JelleZijlstra** [comment] 2022-06-25 13:44
Duplicate of #2608 

The other issue has an explanation of why this is tricky.

**Closed by JelleZijlstra** 2022-06-25 13:44 UTC
Labels: bug, topic-type-narrowing
