### ISSUE TITLE
no error issued when calling a decorated function with the wrong argument type

### ISSUE THREAD

**Issue by clo-vis** [python/mypy#10704] opened 2021-06-23 17:32 UTC
**To Reproduce**

Run mypy on this code and then run the code

```
import functools

@functools.cache
def factorial(n: int) -> int:
    return n * factorial(n-1) if n else 1    

def identity(n: int) -> int:        
    return n

if __name__ == '__main__':
    print(factorial.__name__, factorial.__annotations__)
    print(identity.__name__, identity.__annotations__)
    factorial("")
    identity("")
```

The output of the program is:

> factorial {'n': <class 'int'>, 'return': <class 'int'>}
> identity {'n': <class 'int'>, 'return': <class 'int'>}

so type information is available.

**Expected Behavior**

The lines 
_factorial("")_ 
and
_identity("")_
should be both flagged as wrong because the function is called with an incompatible type

**Actual Behavior**

An error is issued for 
_identity("")_ 
but not for
_factorial("")_

As a side note, mypy issues an error 

> _lru_cache_wrapper[int]" has no attribute "__name__" for _print(factorial.__name__, ...)

but this is another issue.

**Your Environment**

- Mypy version used: 0.910
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: 3.9.5
- Operating system and version: Windows 10

**Comment by erictraut** [comment] 2021-06-23 18:15
This appears to be a deficiency in the `functools.pyi` type stub for `_lru_cache_wrapper`.

It is currently defined as follows:

```python
class _lru_cache_wrapper(Generic[_T]):
    __wrapped__: Callable[..., _T]
    def __call__(self, *args: Hashable, **kwargs: Hashable) -> _T: ...
```

Now that typeshed stubs are starting to incorporate PEP 612, it could be updated to the following:

```python
_P = ParamSpec("_P")

class _lru_cache_wrapper(Generic[_P, _T]):
    __wrapped__: Callable[_P, _T]
    def __call__(self, *args: _P.args, **kwargs: _P.kwargs) -> _T: ...
```

Mypy doesn't have full support for ParamSpec (see [this tracking issue](https://github.com/python/mypy/issues/8645)), but once that support is added, this should address the issue you've reported. I confirmed that it works with pyright.

**Comment by hauntsaninja** [comment] 2022-05-23 23:17
Closing, since the change to typeshed is being tracked in typeshed.

**Closed by hauntsaninja** 2022-05-23 23:17 UTC
Labels: bug, topic-paramspec
