### ISSUE TITLE
Tuple in ternary expression treated as object

### ISSUE THREAD

**Issue by pdeblanc** [python/mypy#6433] opened 2019-02-19 14:50 UTC
When checking this code in mypy 0.670:

```
from typing import Union


a: Union[tuple, int] = 3
b = (a,) if isinstance(a, int) else a
reveal_type(b)  # builtins.object
```

The inferred type of `b` is `builtins.object`. It should be some kind of tuple. I believe this example is minimal in that:

1. It works fine if I use `list` instead of `tuple`
2. It works fine if I replace the ternary expression with if/then statements

**Comment by ethanhs** [comment] 2019-02-20 10:15
Hi, this is a duplicate of https://github.com/python/mypy/issues/4975

**Closed by ethanhs** 2019-02-20 10:15 UTC
