### ISSUE TITLE
Variable inside returned lambda loses conditional type information

### ISSUE THREAD

**Issue by gwax** [python/mypy#14997] opened 2023-04-02 08:51 UTC
**Bug Report**

When returning a lambda containing an uncaptured variable, mypy losing conditional information about the type of that variable.

**To Reproduce**

https://mypy-play.net/?mypy=latest&python=3.11&gist=634d85b9f00175d6b4a1f4929d3ba848

```python
from typing import Callable

def foo(i: int) -> int:
    return i
    
def bar(j: int | None) -> Callable[[], int]:
    if j is not None:
        return lambda: foo(j) # <- error
    return lambda: -1
    
def baz(j: int | None) -> Callable[[], int]:
    if j is not None:
        def inner():
            return foo(j)
        return inner
    return lambda: -1
```

**Expected Behavior**

no error for lambda or inner function

**Actual Behavior**

the returned lambda results in an error

```
main.py:8: error: Argument 1 to "foo" has incompatible type "Optional[int]"; expected "int"  [arg-type]
```

**Your Environment**

- Mypy version used: 1.1.1 (mypy-play)
- Python version used: 3.11 (mypy-play)

**Comment by rhithesh** [comment] 2023-04-02 10:43
hey we can use `cast(int,j)` I looked it up online .

**Comment by erictraut** [comment] 2023-04-02 15:25
This is a duplicate of https://github.com/python/mypy/issues/2608.

You can work around this limitation by assigning the narrowed value to a temporary variable.

```python
def bar(j: int | None) -> Callable[[], int]:
    if j is not None:
        j2 = j
        return lambda: foo(j2)
    return lambda: -1
```

**Closed** 2023-04-02 15:32 UTC
Labels: bug
