### ISSUE TITLE
Forward Reference fails to infer type

### ISSUE THREAD

**Issue by cs-cordero** [python/mypy#5169] opened 2018-06-08 00:17 UTC
Please provide more information to help us understand the issue:

* Are you reporting a bug, or opening a feature request?
  - A bug

* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.
```
from enum import Enum
from typing import NamedTuple

class Bar(NamedTuple):
    whatever: str

class Foo(Enum):
    value: Bar
    WTF = Bar(whatever='hello')

def omg(o: 'Security'):
    reveal_type(o)             # 'baz.Security'
    reveal_type(o.type)        # 'Any'
    reveal_type(o.type.value)  # 'Any'
    return None

class Security:
    type = Foo.WTF

def why(o: 'Security'):
    reveal_type(o)             # 'baz.Security'
    reveal_type(o.type)        # 'baz.Foo'
    reveal_type(o.type.value)  # 'Tuple[builtins.str, fallback=baz.Bar]'
    return None
```

* What is the actual behavior/output?
  - Types for `o.type` and `o.type.value` inside the `omg` function are `'Any'`

* What is the behavior/output you expect?
  - They should be what they are in the `why` function, defined later.

* What are the versions of mypy and Python you are using?
  - I've seen this in mypy==0.540 and mypy==0.600, using Python 3.6.5

**Comment by ilevkivskyi** [comment] 2018-06-08 17:20
This is reproducible on master as well. Probably a problem with deferring the node.

**Comment by silviogutierrez** [comment] 2018-09-20 17:59
@ilevkivskyi : any area I could look at to speed this up? Or is it super complex?

Either way: I'm guessing there's no conf setting to at least raise an error when Any is inferred, right? The way TypeScript does.

**Comment by ilevkivskyi** [comment] 2018-09-20 19:26
@silviogutierrez https://mypy.readthedocs.io/en/latest/command_line.html#disallow-dynamic-typing

**Comment by ilevkivskyi** [comment] 2019-09-03 20:49
It looks like this was fixed at some point (probably by the new analyzer). This works on master, so closing.

**Closed by ilevkivskyi** 2019-09-03 20:49 UTC
Labels: bug, priority-1-normal
