### ISSUE TITLE
warn_unused_ignores vs. OS-specific code

### ISSUE THREAD

**Issue by crusaderky** [python/mypy#12768] opened 2022-05-11 14:41 UTC
I'd like to add to my setup.cfg

```
[mypy]
warn_unused_ignores = True
warn_redundant_casts = True
```

However, I can't find a way to make it work because there are developers on the project that need to run mypy on Windows, and in the code there are OS-specific lines, e.g.

```python
import os
import sys

if sys.platform != "win32":
    os.sysconf("SC_IOV_MAX")  # type: ignore
```
See matching lines in typeshed:
https://github.com/python/typeshed/blob/963b8aa2f77187f381f75d9630b3d021aff55132/stdlib/os/__init__.pyi#L990-L994

With ``# type: ignore``, mypy fails on Linux due to warn-unused-ignores.
Without it, it fails on Windows.

Is there a way to make it work, besides manually enabling the flag once in a while, do a one-off clean-up, and then disabling it?

**Comment by AlexWaygood** [comment] 2022-05-11 15:21
I'm closing this as a duplicate of #8823 (it's the same basic issue, I think), but feel free to add a comment to that issue

**Closed by AlexWaygood** 2022-05-11 15:21 UTC
Labels: feature, topic-type-ignore
