### ISSUE TITLE
MyPy typechecking method names that clash with other types

### ISSUE THREAD

**Issue by alanhdu** [python/mypy#4577] opened 2018-02-15 17:57 UTC
Using `mypy 0.560` (and with the current master) and `python 3.6.4`, typechecking the following function:

```python
class A:
    def int(self) -> int:
        return 5
```

fails with:

```
test.py:2: error: Invalid type "test.A.int"
```

In general, it looks like if I define a method with the name of a type, I can no longer use that type in return annotations in that class.

**Comment by ilevkivskyi** [comment] 2018-02-15 18:09
I think this is a duplicate of https://github.com/python/mypy/issues/3775

The workaround is to use `import builtins` and then `builtins.int`.

**Closed by ilevkivskyi** 2018-02-15 18:09 UTC
