### ISSUE TITLE
unpack Tuple[int, AnyStr] to _, Optional[str]

### ISSUE THREAD

**Issue by dfroger** [python/mypy#5147] opened 2018-06-05 12:41 UTC
I have problems with [mkstemp](https://github.com/python/typeshed/blob/eef0b1d562b914ae28433e568b42d9dcf3bf9c04/stdlib/3/tempfile.pyi#L46), which return type is `Tuple[int, AnyStr]`. I can't assign the second returned value to an `Optional[str]`:

```
from typing import Optional
from tempfile import mkstemp

def foo(path: Optional[str]):
    if path is None:
        f, path = mkstemp('f')
```

With `mypy 0.600` and `Python 3.6.2`, I get the error:

```
foo.py:8: error: Value of type variable "AnyStr" of "mkstemp" cannot be "Optional[str]"
```

**Comment by ilevkivskyi** [comment] 2018-06-05 13:09
We are sorry for this. This is yet another duplicate of https://github.com/python/mypy/issues/4872 (already high priority). The current workaround is to use a temporary variable:
```python
from typing import Optional
from tempfile import mkstemp

def foo(path: Optional[str]):
    if path is None:
        f, _path = mkstemp('f')
        path = _path  # add link to this issue for future readers of your code
```

**Closed by ilevkivskyi** 2018-06-05 13:09 UTC

**Comment by dfroger** [comment] 2018-06-05 14:34
@ilevkivskyi great thanks for pointing to the duplicated (I would not have find it by myself) and for the workaround!
