### ISSUE TITLE
Mypy misinterprets callable attribute as method when annotated in abstract base class.

### ISSUE THREAD

**Issue by gwk** [python/mypy#6461] opened 2019-02-21 18:00 UTC
Consider this example, where I am trying to build a class tree in which every instance of `Base` has a callable attribute called `transform`. It is *not* intended to be a method of the subclasses, but rather some callable passed in at construction, e.g. a lambda.

```
from typing import *

Transform = Callable[[Any],Any]

class Base:
  transform:Transform

class Sub(Base):
  def __init__(self, transform:Transform) -> None:
    self.transform = transform

s = Sub(transform=lambda x: x+1)
assert s.transform(0) == 1
```

Python 3.7 passes the assertion. Mypy however misinterprets `transform` as a method, and rejects this code three ways:
```
callable_attr.py:10:5: error: Cannot assign to a method
callable_attr.py:10:5: error: Incompatible types in assignment (expression has type "Callable[[Any], Any]", variable has type "Callable[[], Any]")
callable_attr.py:13:8: error: Too many arguments
```

mypy version: ee1df176
python version: 3.7.2

setup.cfg:
```
[mypy]
python_version = 3.7

check_untyped_defs = True
disallow_subclassing_any = True
disallow_untyped_calls = True
disallow_untyped_defs = False
ignore_missing_imports = False
show_column_numbers = True
show_none_errors = True
strict_optional = True
warn_incomplete_stub = True
warn_no_return = True
warn_redundant_casts = True
warn_return_any = True
warn_unused_configs = True
warn_unused_ignores = True
```

**Comment by gwk** [comment] 2019-02-21 18:03
Note that if I replace the `transform:Transform` in `Base` with an initializer that sets `self.transform = transform` then the error goes away.

**Comment by ilevkivskyi** [comment] 2019-02-21 22:17
I think this is a duplicate of https://github.com/python/mypy/issues/708 (one of the oldest high priority issues). There are also some explanations why this is non-trivial to fix.

**Closed by ilevkivskyi** 2019-02-21 22:17 UTC
