### ISSUE TITLE
Allow error-code specific whole-file `# type: ignore`s

### ISSUE THREAD

**Issue by koenlek** [python/mypy#10304] opened 2021-04-09 22:48 UTC
This issue is half bug report, half feature request ;) 

**The issue**

Whole-file `# type: ignore` was added in: https://github.com/python/mypy/pull/6830
To my surprise, adding `# type: ignore[valid-type]` as the first line of a file doesn't do what I expected. 

It does the exact same as `# type: ignore` as the first line would do, i.e. the `[valid-type]` portion is totally ignored, without printing any error or warning... If this is unsupported syntax, it would be good if mypy errors out on it, because accepting this without warning is misleading (one might think only some errors are suppressed, but in fact all errors are suppressed). 

**The feature request**

Even better would be if we can add support for error-code specific whole-file ignores. I.e. properly support start-of-file annotations like `# type: ignore[valid-type]`

**Pitch**

An example I ran into is a case where a certain framework defines framework types using `=`. E.g. `MyType = CustomType(Foo=BarType)`. This causes many issues with mypy (perhaps for good reasons?), but when fixing the framework is not within our abilities, we should at least have a way to suppress the various error types this causes globally in a file, otherwise I would need to add many line ignores into that file (I have an example hitting tens of valid-type errors in a single file) or ignore the file completely... 

**Other things I've tried**

_1: mypy.ini based ignores_
I tried using this in mypy.ini:
```
[mypy-this-is-my.module]
disable_error_code = valid-type
```

Fails because apparently disable_error_code can only toggle things globally, not per-module.

Doing this at global scope (`[mypy]`) worked, but that's not what I want.

_2: ignore-errors file setting_

Is there any difference between adding: 

```py
# mypy: ignore-errors
```

versus this at the start of a file
```py
# type: ignore
```

Both work for me, but both don't see to allow narrowing down the error...

_3: inline config_

```py
# mypy: disable-error-code="valid_type"
```

Fails because apparently disable_error_code can only toggle things globally, not per-module.

**Comment by DevilXD** [comment] 2021-04-15 15:30
Looks like a duplicate of #9440

**Comment by koenlek** [comment] 2021-04-15 20:03
Mostly duplicates. But this focusses on code comments (applying to the whole file), rather than achieving this through the mypy ini file (though both aren't possible at this time). Perhaps we can extend the discussion in #9440 to cover support on file-level too?

Perhaps once we support:
```
[mypy-tests.*]
disable_error_code = ["valid_type"]
```

We could easily support something like this in files too? Though file-level != module-level so that could challenge implementing this?

```py
# mypy: disable-error-code=["valid_type"]
```

**Comment by hauntsaninja** [comment] 2022-08-25 17:13
Fixed by https://github.com/python/mypy/pull/13502

**Closed by hauntsaninja** 2022-08-25 17:13 UTC
Labels: feature, topic-type-ignore
