### ISSUE TITLE
mypy --install-types Usability Issue

### ISSUE THREAD

**Issue by 12rambau** [python/mypy#15704] opened 2023-07-18 12:35 UTC
**Bug Report**

When no .mypy_cache folder exists and a user runs mypy --install-types --non-interactive ./, mypy may fail on fundamental Python issues but suggest that the failure was because of "no mypy cache directory," confusing the user.

**To Reproduce**

follow the instructions from this repository (thatactually saved me from countless hours of search): https://github.com/tk-woven/mypy-install-types-mre

**Expected Behavior**

Get a meaningful error (in my case the folder argument was not existing)

**Comment by hauntsaninja** [comment] 2023-11-12 22:11
Duplicate of https://github.com/python/mypy/issues/10863 / https://github.com/python/mypy/issues/10768

**Closed by hauntsaninja** 2023-11-12 22:11 UTC
Labels: bug, topic-usability
