### ISSUE TITLE
Calling built-in open() with **args

### ISSUE THREAD

**Issue by warsaw** [python/mypy#4302] opened 2017-11-30 21:15 UTC
I have some code that does this:

```python
        if encoding is None:
            args = dict(mode='rb')
        else:
            args = dict(mode='r', encoding=encoding, errors=errors)
        try:
            return open(full_path, **args)   # type: ignore
```

If I don't include the `# type: ignore` comment, mypy complains:

```
importlib_resources/_py3.py:71: error: Argument 2 to "open" has incompatible type "**Dict[str, str]"; expected "int"
importlib_resources/_py3.py:71: error: Argument 2 to "open" has incompatible type "**Dict[str, str]"; expected "bool"
```

I don't know what if anything can be done about this, short of adding the ignore.  I can imagine it's not so easy to support **keywords.

**Comment by ilevkivskyi** [comment] 2017-11-30 21:33
Another possible workaround is to give an explicit type for ``args``. For example adding this line somewhere at beginning seems to fix the problem:
```python
args: Dict[str, Any]
```
maybe it is possible to give a more precise type using ``TypedDict``. I think the problem is that mypy does not know what are the keys in ``args`` so it tries to substitute a ``str`` for every parameter of ``open``.

**Comment by ethanhs** [comment] 2017-11-30 21:47
Here is a minimal repro.
```
def f(a: str, b: str = '', c: int = 5) -> int:
    ...
args = dict(mode='rb')
f('', **args)
```
If you change the last argument to be eg, `c: str = ''`, the error is no longer reported.

Unfortunately, I'm not sure there is a better alternative than requiring an annotation of `args` or casting, unless we improve our knowledge of the key/value pair types.

**Comment by warsaw** [comment] 2017-11-30 21:48
Thanks.  Unfortunately we also need to support Python 3.4 and 3.5 which don't have [PEP 526](https://www.python.org/dev/peps/pep-0526/).

I'm not sure changing that to

```python
        if encoding is None:
            args = dict(mode='rb')                  # type: Dict[str, Any]
        else:
            args = dict(mode='r', encoding=encoding, errors=errors) # type: Dict[str, Any]
```

is better because it means we still have to import `Dict` and `Any` without actually using them, so then flake8 complains.

**Comment by ethanhs** [comment] 2017-11-30 21:59
You can do

```
from typing import Dict, Any  # noqa
...
        args = dict()  # Dict[str, Any]
        if encoding is None:
            args = dict(mode='rb')
        else:
            args = dict(mode='r', encoding=encoding, errors=errors)
```

**Comment by ethanhs** [comment] 2017-12-02 22:41
I believe mypy did the correct thing here, so I am going to close this. If you have further concerns @warsaw, feel free to comment and I'll reopen.

**Closed by ethanhs** 2017-12-02 22:41 UTC
