### ISSUE TITLE
Tuples that differ only in length are indistinguishable (mypy 0.790)

### ISSUE THREAD

**Issue by kntroh** [python/mypy#9747] opened 2020-11-23 04:43 UTC
**Bug Report**

```Python
from typing import *

TT = TypeVar("TT", Tuple[int, int], Tuple[int, int, int, int])

def func(tt: TT) -> TT:
    if len(tt) == 2:
        tt2 = (tt[0], tt[1])
        return tt2
    elif len(tt) == 4:
        tt4 = (tt[0], tt[1], tt[2], tt[3])
        return tt4
    assert False

print(func((0, 1)))
print(func((0, 1, 2, 3)))
```

Analysis for this code causes the three errors (mypy 0.790):

```
$ mypy mypytest.py
mypytest.py:8: error: Incompatible return value type (got "Tuple[int, int]", expected "Tuple[int, int, int, int]")
mypytest.py:10: error: Tuple index out of range
mypytest.py:11: error: Incompatible return value type (got "Tuple[int, int, Any, Any]", expected "Tuple[int, int]")
Found 3 errors in 1 file (checked 1 source file)
```

I think this is a glitch, but is there a technical reason for not being able to distinguish between these two types of tuples?

**Comment by hauntsaninja** [comment] 2020-11-24 22:33
Duplicate of https://github.com/python/mypy/issues/9171 , https://github.com/python/mypy/issues/1178 and others

**Closed by hauntsaninja** 2020-11-24 22:33 UTC
Labels: bug
