### ISSUE TITLE
AssertionError in sentry_sdk

### ISSUE THREAD

**Issue by sbrandtb** [python/mypy#6874] opened 2019-05-21 15:00 UTC
## Are you reporting a bug, or opening a feature request?
Bug.

## Please insert below the code you are checking with mypy,   or a mock-up repro if the source is private. We would appreciate   if you try to simplify your case to a minimal repro.

https://github.com/sbrandtb/mypy-sentry-crash

## What is the actual behavior/output?

mypy crashes:

```
/path/to/lib/python3.7/site-packages/sentry_sdk/consts.py:13: error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues version: 0.701
/path/to/lib/python3.7/site-packages/sentry_sdk/consts.py:13: : note: please use --show-traceback to print a traceback when reporting a bug
```

## What is the behavior/output you expect?

No crash :slightly_smiling_face: 

## What are the versions of mypy and Python you are using?

Python 3.7.3
mypy 0.701

## Do you see the same issue after installing mypy from Git master?

Yes.

## What are the mypy flags you are using? (For example --strict-optional)

`MYPYPATH=`pipenv --venv`/lib/python3.7/site-packages/`

## If mypy crashed with a traceback, please paste the full traceback below.

```
path/to/site-packages/sentry_sdk/consts.py:13: error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues version: 0.701
Traceback (most recent call last):
  File "path/to/bin/mypy", line 10, in <module>
    sys.exit(console_entry())
  File "mypy/semanal.py", line 3791, in accept
  File "mypy/nodes.py", line 1018, in accept__Node_glue
  File "mypy/nodes.py", line 1019, in accept
  File "mypy/semanal.py", line 1762, in visit_assignment_stmt__StatementVisitor_glue
  File "mypy/semanal.py", line 1774, in visit_assignment_stmt
  File "mypy/semanal_typeddict.py", line 156, in process_typeddict_definition
  File "mypy/semanal_typeddict.py", line 202, in check_typeddict
  File "mypy/semanal_typeddict.py", line 279, in build_typeddict_typeinfo
AssertionError:
path/to/site-packages/sentry_sdk/consts.py:13: : note: use --pdb to drop into pdb
```

**Comment by gvanrossum** [comment] 2019-05-21 15:26
Does this reproduce with the latest revision from master?
-- 
--Guido (mobile)

**Comment by sbrandtb** [comment] 2019-05-21 15:28
@gvanrossum Yes. The stack trace is just longer because it shows the lines of code.

**Comment by gvanrossum** [comment] 2019-05-21 17:52
OK, I can reproduce this, but the root cause seems that you have added site-packages to MYPYPATH. That has unpleasant side effects. Instead, you should ask that the sentry folks add a `py.typed` file to their SDK distribution. See PEP 561 for why. If you do this, mypy can process the sentry_sdk module just fine.

**Comment by sbrandtb** [comment] 2019-05-23 07:59
@gvanrossum Yes, I understand that it is suggested to not add site-packages. However, mypy is crashing with an internal error and suggesting me to open an issue here - that's what I did :smile: 

So, the question here is if it is a bug that should be fixed by mypy or not. Even if it's just to explicitly handle this assertion error in order to display a nice error message and not "please open an issue $here".

Looking at the piece of code in sentry where this happens, this is a piece of code meant to be picked up by mypy only anyways (`if False` block and explicitly importing `TypedDict` from `mypy[-extensions]`).

```py
if False:
    from mypy_extensions import TypedDict
    from typing import Optional
    from typing import Callable
    from typing import Union
    from typing import List

    from sentry_sdk.transport import Transport
    from sentry_sdk.integrations import Integration

    ClientOptions = TypedDict(  # < this is line 13
        "ClientOptions",
        {
            "dsn": Optional[str],
            "with_locals": bool,
            "max_breadcrumbs": int,
            "release": Optional[str],
            "environment": Optional[str],
            "server_name": Optional[str],
            "shutdown_timeout": int,
            "integrations": List[Integration],
            "in_app_include": List[str],
            "in_app_exclude": List[str],
            "default_integrations": bool,
            "dist": Optional[str],
            "transport": Optional[Union[Transport, type, Callable]],
            "sample_rate": int,
            "send_default_pii": bool,
            "http_proxy": Optional[str],
            "https_proxy": Optional[str],
            "ignore_errors": List[type],
            "request_bodies": str,
            "before_send": Optional[Callable],
            "before_breadcrumb": Optional[Callable],
            "debug": bool,
            "attach_stacktrace": bool,
            "ca_certs": Optional[str],
        },
        total=False,
    ) 
```

**Comment by ilevkivskyi** [comment] 2019-05-23 10:13
The assertion fails because mypy can't find a special class (defined in typeshed only), and instead tries to parse the _source_ of `typing_extensions`. So this is a duplicate of https://github.com/python/mypy/issues/1876 (one of the oldest high-prio issues btw).

**Closed by ilevkivskyi** 2019-05-23 10:13 UTC

**Comment by sbrandtb** [comment] 2019-05-23 12:15
@ilevkivskyi thanks for clarifying!

**Comment by tolidano** [comment] 2019-06-19 18:07
If I don't put site-packages on MYPYPATH, I get:

```
13:38 $ mypy handler.py
handler.py:6: error: Cannot find module named 'kafka'
handler.py:6: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
handler.py:7: error: Cannot find module named 'peloconfig'
handler.py:8: error: Cannot find module named 'sentry_sdk'
handler.py:9: error: Cannot find module named 'sentry_sdk.integrations.aws_lambda'
```

When other things (like `pytest`) work well.
