### ISSUE TITLE
(🐞) "Cannot infer type argument" when one of multiple arguments can't be inferred

### ISSUE THREAD

**Issue by KotlinIsland** [python/mypy#16100] opened 2023-09-13 04:08 UTC
```py
from typing import Generic, _T as T
def f1(key: list[T], value: list[T]): ...

f1([1], [])  # Cannot infer type argument 1 of "f"  [misc]
```

**Comment by ilevkivskyi** [comment] 2023-09-14 22:26
Strict duplicate of https://github.com/python/mypy/issues/230

**Closed by ilevkivskyi** 2023-09-14 22:26 UTC
Labels: bug
