### ISSUE TITLE
Error when dynamically constructing classes from reflected metaclass

### ISSUE THREAD

**Issue by PeterJCLaw** [python/mypy#7086] opened 2019-06-27 19:43 UTC
In the following code, the presence of the last line (the call to `foo_meta`) causes `mypy` to emit an error without a line number and which cannot be ignored.
``` python
class FooMeta(type):
    pass
class Foo(metaclass=FooMeta):
    pass

foo_meta = type(Foo)
reveal_type(foo_meta)  # shows: Revealed type is 'Type[def () -> foo.Foo]'

foo_meta("Bar", (Foo,), {})
```
The error is:
```
foo.py: error: Unsupported type Type["Type[Foo]"]
```

I would expect that even if `mypy` were unable to determine the types here I would be able to ignore the error with a suitably placed `# type: ignore` (instead I get a warning about an unused ignore). Ideally the usage wouldn't error at all though.

Python: 3.5.2
`mypy`: 0.701 (verified still an issue under 0.711, the latest at the time of writing)

**Comment by ilevkivskyi** [comment] 2019-08-12 14:10
I think this actually a duplicate of https://github.com/python/mypy/issues/4300

**Closed by ilevkivskyi** 2019-08-12 14:10 UTC
