### ISSUE TITLE
Type inference of arguments like `default: TDefault = None`

### ISSUE THREAD

**Issue by Strilanc** [python/mypy#9432] opened 2020-09-10 02:45 UTC
## 🐛 Bug Report

1. Create a file `tmp.py` with this code:

```
from typing import TypeVar, Union
TDefault = TypeVar('TDefault')

def f(flag: int, default: TDefault = None) -> Union[int, TDefault]:
    if flag == 0:
        return default
    return flag
```

2. Run mypy on the file.

## Expected Behavior

No type errors.

## Actual Behavior

```
tmp.py:6: error: Incompatible return value type (got "Optional[TDefault]", expected "Union[int, TDefault]")
Found 1 error in 1 file (checked 1 source file)
```

To be more specific, mypy fails to realize that the none-returning-path is just a different default-returning-path (where TDefault happens to correspond to NoneType), rather than a mistake.

To avoid the error I have to specify the type information in each case manually using overloads:

```
from typing import TypeVar, Union, overload
TDefault = TypeVar('TDefault')

@overload
def f(flag: int) -> Union[int, None]:
    pass
def f(flag: int, default: TDefault) -> Union[int, TDefault]:
    pass
def f(flag, default = None):
    if flag == 0:
        return default
    return flag
```

## Your Environment

- Mypy version used: 0.782
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): None
- Python version used: 3.8.5
- Operating system and version: gLinux

**Comment by hauntsaninja** [comment] 2020-09-10 02:59
Dupe of #3737, #8708, #8739 and others. First of those has the most discussion

Also for future searchers, if you run with `--strict` note you get a different error message:
```
main.py:4: error: Incompatible default for argument "default" (default has type "None", argument has type "TDefault")
```

**Closed by hauntsaninja** 2020-09-10 02:59 UTC
Labels: bug
