### ISSUE TITLE
object.__new__(cls) fails type check inside generic classes

### ISSUE THREAD

**Issue by pkch** [python/mypy#3120] opened 2017-04-03 22:08 UTC
(Based on #3111)

This fails with `Argument 1 to "__new__" of "object" has incompatible type C[T]; expected "object"`

```
T = TypeVar('T')
class C(Generic[T]):
    def __new__(cls, foo: T) -> 'C[T]':
        obj = object.__new__(cls)
        return obj
    def set(self, x: T) -> None: pass
```

Edit: deleted my own incorrect interpretation.

**Comment by pkch** [comment] 2017-04-20 10:28
This also happens when `__init__` is present and has non-zero arguments in the signature:

```
class C:
    def __init__(self, x: int) -> None:
        pass
    def __new__(cls, *args) -> 'C':
        obj = object.__new__(cls)  # E:  Argument 1 to "__new__" of "object" has incompatible type "C"; expected "object"
        return obj
```

However, this passes:

```
class C:
    def __new__(cls) -> 'C':
        obj = object.__new__(cls)
        return obj
```

Somehow the presence of arguments in the signature prevents mypy from matching the class object to the expected `object` type.

**Comment by msullivan** [comment] 2018-09-19 21:30
#4190 is a dupe of this but I'm closing this one because that one got categorized

**Closed by msullivan** 2018-09-19 21:30 UTC
