### ISSUE TITLE
Doing `variable: typing.Optional[typing.Self] = self` will fail

### ISSUE THREAD

**Issue by McDic** [python/mypy#16418] opened 2023-11-07 07:34 UTC
**Bug Report**

If you do `variable: typing.Optional[typing.Self] = self` in method of your class, you will get a mypy error.

**To Reproduce**

```python
import typing

class TestClass:
    def __init__(self, parent: typing.Optional[typing.Self]) -> None:
        self.parent = parent

    def get_depth(self) -> int:
        current: typing.Optional[typing.Self] = self
        iteration = 0
        while current is not None:
            iteration += 1
            current = current.parent
        return iteration - 1
```

**Expected Behavior**

There should be no error.

**Actual Behavior**

You will get following error on `current = self` part.

```
error: Incompatible types in assignment (expression has type "TestClass", variable has type "Self | None")  [assignment]
```

**Your Environment**

- Mypy version used: 1.6.1
- Mypy command-line flags: `mypy (filename)`
- Mypy configuration options from `mypy.ini` (and other config files): Nothing
- Python version used: 3.11.6

**Comment by ilevkivskyi** [comment] 2023-11-09 00:10
This is duplicate of https://github.com/python/mypy/issues/14075

**Closed by ilevkivskyi** 2023-11-09 00:10 UTC
Labels: bug, topic-self-types
