### ISSUE TITLE
Mypy not detecting type narrowing in another function

### ISSUE THREAD

**Issue by colinschoen** [python/mypy#8224] opened 2019-12-31 22:36 UTC
```
from typing import Optional, List
def is_not_none(lst):
    # type: (Optional[List[str]]) -> bool
    return lst is not None


def get_first_element(lst):
    # type: (Optional[List[str]]) -> str
    if is_not_none(lst):
        return lst[0]
    return 'not found'
```

mypy invocation: `mypy --py2 .`

Expected output:
```
Success: no issues found in 1 source file
```

Actual output
```
ex.py:12: error: Value of type "Optional[List[str]]" is not indexable
Found 1 error in 1 file (checked 1 source file)
```

**Comment by ethanhs** [comment] 2020-01-01 02:22
This is a duplicate of #5206

**Closed by ethanhs** 2020-01-01 02:22 UTC
