### ISSUE TITLE
Type inference of local variable assigned in different branches uses type of assignment in first branch

### ISSUE THREAD

**Issue by syastrov** [python/mypy#7879] opened 2019-11-05 07:10 UTC
* Are you reporting a bug, or opening a feature request?
It's a matter of opinion.

* Please insert below the code you are checking with mypy.
```python
def foo(a: bool) -> None:
  if a:
    b = "blah"
  else:
    b = None
  return None
```

* What is the actual behavior/output?

```
$ mypy a.py
a.py:5: error: Incompatible types in assignment (expression has type "None", variable has type "str")
```

* What is the behavior/output you expect?

Since there is no annotation on `b`, mypy should infer that the variable `b` has the broadest type that matches the possible assignments: `Union[str, None]` (aka `Optional[str]`).
I didn't expect that mypy would just infer the type of the variable based on the first assignment.
FWIW: PyCharm's type inference infers the type `Optional[str]`

If this is not possible, then perhaps mypy could give a more meaningful error and/or hint (e.g. "error: variable `b` is assigned a different type based on different branches" + "hint: provide a type annotation for `b`: Optional[str]").

* What are the versions of mypy and Python you are using?

Python 3.7.4 / mypy 0.750+dev.3fc382321e4531450e91c55fddb6d4ed54611d5e
(git master)

* What are the mypy flags you are using? (For example --strict-optional)
No flags specified, but it also occurs with --strict-optional

Related to #4061

**Comment by ilevkivskyi** [comment] 2019-11-05 11:35
Duplicate of https://github.com/python/mypy/issues/2611

**Closed by ilevkivskyi** 2019-11-05 11:35 UTC
