### ISSUE TITLE
int and float aren't understood to be PEP3141 Reals

### ISSUE THREAD

**Issue by wiml** [python/mypy#10311] opened 2021-04-11 19:49 UTC
**Bug Report**

The [PEP3141](https://www.python.org/dev/peps/pep-3141/) numeric tower defines [types like `Real` and `Integer`](https://docs.python.org/3/library/numbers.html), but mypy doesn't understand them. In particular, even though Python knows that `isinstance(some_float_var, numbers.Real)` is `True`, mypy thinks floats are incompatible with variables declared Real.

Note that `SupportsFloat` isn't the same as `Real` — you can do arithmetic with `Real`s, but the only thing you can do with `SupportsFloat` is cast it to `float`, which you don't necessarily want to do (floats can lose precision w.r.t. other types).

**To Reproduce**

```python

import numbers, typing

v = 10
r: numbers.Real = 10.0

print(isinstance(v, numbers.Real))
print(isinstance(r, numbers.Real))
#reveal_type(v)
#reveal_type(r)
r = v
print(isinstance(r, numbers.Real))

```

**Expected Behavior**

I should be able to declare a variable as a real number and assign the builtin real types to it. Mypy's understanding of the type system should match Python's.

**Actual Behavior**

Mypy rejects these well-typed programs:

```
error: Incompatible types in assignment (expression has type "float", variable has type "Real")  [assignment]
error: Incompatible types in assignment (expression has type "int", variable has type "Real")  [assignment]
```

**Your Environment**

- Mypy version used: 0.812
- Mypy command-line flags: _(none)_
- Python version used: 3.8.8
- Operating system and version: Ubuntu 20.10

**Comment by JelleZijlstra** [comment] 2021-04-11 20:03
Duplicate of #3186

**Closed by JelleZijlstra** 2021-04-11 20:03 UTC
Labels: bug
