### ISSUE TITLE
AssertionError: "mypy/types.py", line 1043, in accept

### ISSUE THREAD

**Issue by ghost** [python/mypy#16789] opened 2024-01-16 07:56 UTC
**Crash Report**

I am running mypy under VSCode (with `mypy` extension) and got a traceback.
I understand that I made a mistake with:
```python
class ResultDict(TypedDict):
    ...
    common_records: []
    ...
```
and if I fix this everything works fine but still `mypy` asks to report an issue in the case of crash\traceback.

**Traceback**

```
[24] Check folder: /home/kav/AK/addons
[24] Using extra arguments: 
[24] Received Python path from Python extension: /home/kav/AK/addons/.venv/bin/python3.11
[24] Running dmypy in folder /home/kav/AK/addons
/home/kav/AK/addons/.venv/bin/python3.11 -m mypy.dmypy --status-file /home/kav/.vscode-server/data/User/workspaceStorage/a8068cd13da0f694756f54232eac4c97/matangover.mypy/dmypy-fc0056dfb9058bb0814f84600edbd4e97398d1d9-3642698.json run --log-file /home/kav/.vscode-server/data/User/workspaceStorage/a8068cd13da0f694756f54232eac4c97/matangover.mypy/dmypy-fc0056dfb9058bb0814f84600edbd4e97398d1d9.log -- --python-executable /home/kav/AK/addons/.venv/bin/python3.11 . --show-error-end --no-error-summary --no-pretty --no-color-output
[24] stdout:
Daemon started
testssl/testssl/testssl.py:13:21:13:21: error: Bracketed expression "[...]" is not valid as a type  [valid-type]

[24] stderr:
./testssl/testssl/testssl.py: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 1.8.0
Daemon crashed!
Traceback (most recent call last):
  File "mypy/dmypy_server.py", line 236, in serve
  File "mypy/dmypy_server.py", line 285, in run_command
  File "mypy/dmypy_server.py", line 353, in cmd_run
  File "mypy/dmypy_server.py", line 424, in check
  File "mypy/dmypy_server.py", line 463, in initialize_fine_grained
  File "mypy/build.py", line 191, in build
  File "mypy/build.py", line 265, in _build
  File "mypy/build.py", line 2943, in dispatch
  File "mypy/build.py", line 3341, in process_graph
  File "mypy/build.py", line 3446, in process_stale_scc
  File "mypy/build.py", line 2406, in finish_passes
  File "mypy/build.py", line 2464, in update_fine_grained_deps
  File "mypy/build.py", line 2452, in compute_fine_grained_deps
  File "mypy/server/deps.py", line 187, in get_dependencies
  File "mypy/nodes.py", line 369, in accept
  File "mypy/server/deps.py", line 250, in visit_mypy_file
  File "mypy/traverser.py", line 115, in visit_mypy_file
  File "mypy/nodes.py", line 1142, in accept
  File "mypy/server/deps.py", line 310, in visit_class_def
  File "mypy/traverser.py", line 151, in visit_class_def
  File "mypy/nodes.py", line 1223, in accept
  File "mypy/server/deps.py", line 429, in visit_block
  File "mypy/traverser.py", line 119, in visit_block
  File "mypy/nodes.py", line 1310, in accept
  File "mypy/server/deps.py", line 490, in visit_assignment_stmt
  File "mypy/server/deps.py", line 887, in add_type_dependencies
  File "mypy/server/deps.py", line 940, in get_type_triggers
  File "mypy/server/deps.py", line 947, in get_type_triggers
  File "mypy/types.py", line 1043, in accept
AssertionError

[24] Error running mypy in /home/kav/AK/addons: the mypy daemon crashed. This is probably a bug in mypy itself, see Output panel for details. The daemon will be restarted automatically.
```

**To Reproduce**

Please see the full file bellow:
```
from typing import TypedDict


class ResultDict(TypedDict):
    total_time: float
    success: bool
    timeout: bool
    return_code: int
    std_error: str
    common_records: []
    ips: dict[str, dict]
```

**Your Environment**

- Mypy version used:
```
$ mypy -V
mypy 1.8.0 (compiled: yes)
```

- Mypy command-line flags:
```
/home/kav/AK/addons/.venv/bin/python3.11 -m mypy.dmypy --status-file /home/kav/.vscode-server/data/User/workspaceStorage/a8068cd13da0f694756f54232eac4c97/matangover.mypy/dmypy-fc0056dfb9058bb0814f84600edbd4e97398d1d9-3642698.json run --log-file /home/kav/.vscode-server/data/User/workspaceStorage/a8068cd13da0f694756f54232eac4c97/matangover.mypy/dmypy-fc0056dfb9058bb0814f84600edbd4e97398d1d9.log -- --python-executable /home/kav/AK/addons/.venv/bin/python3.11 . --show-error-end --no-error-summary --no-pretty --no-color-output
```

- Mypy configuration options from `mypy.ini` (and other config files):
```
there are no such files
```

- Python version used:
```
$ python
Python 3.11.6 (main, Oct 23 2023, 22:48:54) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
```

- Operating system and version:
```
$ uname
Linux

$ lsb_release -a
LSB Version:    core-11.1.0ubuntu4-noarch:security-11.1.0ubuntu4-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
```

**Comment by ilevkivskyi** [comment] 2024-06-29 19:39
This is a duplicate of https://github.com/python/mypy/issues/10007

**Closed by ilevkivskyi** 2024-06-29 19:39 UTC
Labels: crash, topic-typed-dict, topic-daemon
