### ISSUE TITLE
float not understood as numbers.Number

### ISSUE THREAD

**Issue by skinnersBoxy** [python/mypy#7375] opened 2019-08-20 21:54 UTC
Please provide more information to help us understand the issue:

* Are you reporting a bug, or opening a feature request? Reporting a bug
* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.
```python
import numbers

a: float = 5.0
print(isinstance(a, numbers.Number))  # True

def f(a: float) -> numbers.Number:
    return a  # Incompatible return value type (got "float", expected "Number")
```

* What is the actual behavior/output?
Mypy reports the error "Incompatible return value type (got "float", expected "Number")".
* What is the behavior/output you expect?
I expect mypy to report no errors.
* What are the versions of mypy and Python you are using?
mypy 0.660
Python 3.6.8
  Do you see the same issue after installing mypy from Git master?
Yes.
* What are the mypy flags you are using? (For example --strict-optional)
None.

I'm slightly unclear if this is really a bug because I don't really understand what numbers is doing but isinstance() returns true, so I would expect the above code to be fine.

Thanks!

**Comment by ilevkivskyi** [comment] 2019-08-20 23:50
This a (yet another) duplicate of https://github.com/python/mypy/issues/3186

**Closed by ilevkivskyi** 2019-08-20 23:50 UTC
