### ISSUE TITLE
ParamSpec P.args not Iterable; P.kwags does not have "Items"

### ISSUE THREAD

**Issue by rbroderi** [python/mypy#12660] opened 2022-04-23 16:15 UTC
```
P = ParamSpec("P")
R = TypeVar("R")
  def dec_test(func: Callable[P, R]) -> Callable[P, R]:
      @wraps(func)
      def inner(*args: P.args, **kwargs: P.kwargs) -> R:
          for a in args:
              print(a)
          for arg_k, arg_v in kwargs.items():
              print(f"{arg_k},{arg_v}"
          return func(*args, **kwargs)
  
      return inner

```
**Expected Behavior**
P.args should be iterable
P.kwargs should have items()

**Actual Behavior**
"P.args" has no attribute "__iter__" (not iterable)
 "P.kwargs" has no attribute "items"
**Your Environment**

- Mypy version used: 0.931
- Python version used: 3.10.4
- Operating system and version: Windows 10

**Comment by AlexWaygood** [comment] 2022-04-24 02:06
Duplicate of #12386

**Closed by AlexWaygood** 2022-04-24 02:06 UTC
Labels: bug, topic-paramspec
