### ISSUE TITLE
`isinstance(foo, NoneType)` does not narrow `foo` as `None`

### ISSUE THREAD

**Issue by Jasha10** [python/mypy#14394] opened 2023-01-04 19:36 UTC
**Describe the bug**
With a variable `foo` typed as `T | None`, the statement `isinstance(foo, NoneType)` does not narrow `foo` to be `None`.
Similarly, a match statement with a `case NoneType()` arm fails to narrow.

**To Reproduce**
```python
# tmp.py
from random import getrandbits
from types import NoneType
from typing_extensions import assert_never

random_bool = bool(getrandbits(1))

foo: int | None = 123 if random_bool else None

# match statement:
match foo:
    case int():
        ...
    case NoneType():
        ...
    case _:
        assert_never(foo)
```
```text
$ mypy tmp.py
tmp.py:16: error: Argument 1 to "assert_never" has incompatible type "None"; expected "NoReturn"  [arg-type]
Found 1 error in 1 file (checked 1 source file)
```
I get an identical error using a match statement as below:
```python
# match statement:
match foo:
    case int():
        ...
    case NoneType():
        ...
    case _:
        assert_never(foo)  # mypy error: Argument 1 to "assert_never" has incompatible type "None"; expected "NoReturn"  [arg-type]
```

**Expected behavior**
I would not expect mypy to give an error; I'd expect mypy to narrow `foo` as `None` in the second arm of the if-elif block above.

**Additional context**
I've opened a similar issue against pyright: https://github.com/microsoft/pyright/issues/4402.

**Environment**
```
$ mypy --version
mypy 0.991 (compiled: yes)
$ python --version
Python 3.10.8
```

**Comment by hauntsaninja** [comment] 2023-01-04 19:49
Duplicate of #13154

**Closed** 2023-01-04 19:49 UTC
Labels: bug

**Comment by Jasha10** [comment] 2023-01-07 04:48
A workaround for this issue specifically (not for #13154) is to use `case None`:
```python
match foo:
    case int():
        ...
    case None:  # use `None` instead of `NoneType()`
        ...
    case _:
        assert_never(foo)
```
