### ISSUE TITLE
strange behavior of exclude option

### ISSUE THREAD

**Issue by bluebrown** [python/mypy#11190] opened 2021-09-25 08:11 UTC
**Bug Report**

**To Reproduce**
When I run `mypy` from the _command line_, I can see it's using the exclude option specified in `setup.cfg`.

```ini
[mypy]
python_executable = .venv/bin/python
exclude = alembic
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = True
disallow_untyped_decorators = True
warn_redundant_casts = True
warn_unreachable = True
warn_unused_ignores = True
show_column_numbers = True
ignore_missing_imports = True
```

But VS Code is marking the files in the excluded alembic folder still with errors. Providing an additional flag in settings.json didn't help either.

```json
"python.linting.mypyEnabled": true,
"python.linting.mypyArgs": [
  "--exclude=alembic"
],
```

I managed to get it working with `python.linting.ignorePatterns``.

```json
"python.linting.ignorePatterns": [
  "alembic/**/*.py"
],
```

I found out that the same problem occurs with another tool. So this probably unrelated to VS Code. When I run my `pre-commit hook.` All options are picked up, but it's not excluding the pattern given in `exclude.` 

```yaml
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910
  hooks:
    - id: mypy
      additional_dependencies: [tokenize-rt==4.1.0]
```

Providing it with an extra flag there also doesn't help.  Unfortunately, I have found a workaround like in VS Code for the hook so far.

**Your Environment**

- Mypy version used: v0.910
- Python version used: 3.8
- Operating system and version: ubuntu20.04 (wsl2)

**Comment by ethanhs** [comment] 2021-09-25 09:03
> I found out that the same problem occurs with another tool. So this probably unrelated to VS Code.

This would lead me to the opposite conclusion. If the issue happens with and without mypy, wouldn't that mean its more likely VSCode's fault?

**Comment by bluebrown** [comment] 2021-09-25 09:06
No because you can run the pre commit hook outside VS Code. Its completely decoupled. https://github.com/pre-commit/mirrors-mypy.

So two separate tools. VS Code and pre-commit having problems propagating `exclude` to the underlying `mypy` installation.

**Comment by ethanhs** [comment] 2021-09-25 09:54
Ah this seems to be a duplicate of #11094. I'll leave a comment there explaining things.

**Closed by ethanhs** 2021-09-25 09:54 UTC
Labels: bug

**Comment by bluebrown** [comment] 2021-09-25 10:04
It's not a duplicate because the attempt to use the flag was just a result of it not using it from the config file properly. I have seen that issues you linked already. I don't feel it's related to that.  And I have tried multiple ways to provide regex. I.e. /alembic/ should ignore the whole alembic folder, right? It doesnt. Neither does alembic not do it. Neither /alembic.*/ .

You are really quick to close this stuff and the other one you closed too. 

Anywy i dropping this tool for now. Thanks for deflecting this quickly :)

**Comment by bluebrown** [comment] 2021-09-25 11:23
It doesn't seem to be related at all. What makes you think it's a duplicate? 

The linked issue is about excluding a file and then telling mypy to check this file? I am not doing such thing here.  

Only thing they have in common is the word *exclude* in the issue title.
