### ISSUE TITLE
Type inference issue with "map" and "os.path.normcase"

### ISSUE THREAD

**Issue by deveshks** [python/mypy#8961] opened 2020-06-07 21:15 UTC
The following code raises a type error when run with `mypy v0.780`. 

```python
import os

files = ['foo/BAR', 'FOO/baz']
normcased_files = map(os.path.normcase, files)
```

The errors are as follows
```
$ mypy --version
mypy 0.780

$ mypy scratch.py 

scratch.py:4: error: Argument 1 to "map" has incompatible type overloaded function; expected "Callable[[str], AnyStr]"
Found 1 error in 1 file (checked 1 source file)

$ mypy --py2  scratch.py 

scratch.py:4: error: Argument 1 to "map" has incompatible type "Callable[[AnyStr], AnyStr]"; expected "Callable[[str], AnyStr]"
Found 1 error in 1 file (checked 1 source file)
```
 
Note that the error is different when run against python 2 vs python 3, even when the type annotations are same for both [python 3](https://github.com/python/typeshed/blob/master/stdlib/3/os/path.pyi#L60-L63) and [python 2](https://github.com/python/typeshed/blob/master/stdlib/2/os/path.pyi#L60-L63)

**Comment by Kangaroux** [comment] 2020-06-08 15:13
VScode correctly identifies the sig when you hover: `normpath(path: str) -> str`

This works:

```python
import os

def fn(s: str) -> str:
    return os.path.normpath(s)

files = ['foo/BAR', 'FOO/baz']
normcased_files = map(fn, files)


reveal_type(os.path.normpath)
# note: Revealed type is 'Overload(def [AnyStr in (builtins.str, builtins.bytes)] (path: builtins._PathLike[AnyStr`-1]) -> AnyStr`-1, def [AnyStr in (builtins.str, builtins.bytes)] (path: AnyStr`-1) -> AnyStr`-1)'

reveal_type(fn)
# note: Revealed type is 'def (x: builtins.str) -> builtins.str'
```

**Comment by Kangaroux** [comment] 2020-06-08 15:19
You can do this as a one line workaround:

```python
normcased_files = map(lambda x: os.path.normpath(x), files)
```

And if you care about the type:

```python
from typing import List
normcased_files: List[str] = list(map(lambda x: os.path.normpath(x), files))
```

**Comment by Kangaroux** [comment] 2020-06-08 15:22
With regards to the comment on #8962, since the `map` function is using overloads, did you try mypy 0.770 to see if that works?

**Comment by deveshks** [comment] 2020-06-08 15:26
> You can do this as a one line workaround:

Thanks. I was aware of the workaround, but that's not the actual problem here. The original code should  also pass type checks.

> With regards to the comment on #8962, since the map function is using overloads, did you try mypy 0.770 to see if that works?

No, that doesn't work either

```
$ mypy --version
mypy 0.770

$ mypy scratch.py 
scratch.py:4: error: Argument 1 to "map" has incompatible type overloaded function; expected "Callable[[str], AnyStr]"
```

**Comment by AlexWaygood** [comment] 2022-03-25 16:27
Closing as a duplicate of #2389 (although the example is slightly different, the bug appears to be to be the same)

**Closed by AlexWaygood** 2022-03-25 16:27 UTC
