### ISSUE TITLE
@overload and functools.lru_cache causes an internal error

### ISSUE THREAD

**Issue by jacobbogdanov** [python/mypy#10155] opened 2021-03-01 12:55 UTC
**Crash Report**

It seems that combining `@overload` with `functools.lru_cache` causes an internal crash of `mypy.`

**Traceback**

```sh
$ mypy test.py --show-traceback
test.py:7: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.rtfd.io/en/latest/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.820+dev.98c2c1289ff76570457fc547ae254293aea6a019
Traceback (most recent call last):
  File ".pyenv/versions/36/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File ".pyenv/versions/3.6.12/envs/36/lib/python3.6/site-packages/mypy/__main__.py", line 11, in console_entry
    main(None, sys.stdout, sys.stderr)
  File ".pyenv/versions/3.6.12/envs/36/lib/python3.6/site-packages/mypy/main.py", line 98, in main
    res = build.build(sources, options, None, flush_errors, fscache, stdout, stderr)
  File ".pyenv/versions/3.6.12/envs/36/lib/python3.6/site-packages/mypy/build.py", line 180, in build
    sources, options, alt_lib_path, flush_errors, fscache, stdout, stderr, extra_plugins
  File ".pyenv/versions/3.6.12/envs/36/lib/python3.6/site-packages/mypy/build.py", line 253, in _build
    graph = dispatch(sources, manager, stdout)
  File ".pyenv/versions/3.6.12/envs/36/lib/python3.6/site-packages/mypy/build.py", line 2688, in dispatch
    process_graph(graph, manager)
  File ".pyenv/versions/3.6.12/envs/36/lib/python3.6/site-packages/mypy/build.py", line 3012, in process_graph
    process_stale_scc(graph, scc, manager)
  File ".pyenv/versions/3.6.12/envs/36/lib/python3.6/site-packages/mypy/build.py", line 3110, in process_stale_scc
    graph[id].type_check_first_pass()
  File ".pyenv/versions/3.6.12/envs/36/lib/python3.6/site-packages/mypy/build.py", line 2164, in type_check_first_pass
    self.type_checker().check_first_pass()
  File ".pyenv/versions/3.6.12/envs/36/lib/python3.6/site-packages/mypy/checker.py", line 294, in check_first_pass
    self.accept(d)
  File ".pyenv/versions/3.6.12/envs/36/lib/python3.6/site-packages/mypy/checker.py", line 401, in accept
    stmt.accept(self)
  File ".pyenv/versions/3.6.12/envs/36/lib/python3.6/site-packages/mypy/nodes.py", line 526, in accept
    return visitor.visit_overloaded_func_def(self)
  File ".pyenv/versions/3.6.12/envs/36/lib/python3.6/site-packages/mypy/checker.py", line 434, in visit_overloaded_func_def
    self._visit_overloaded_func_def(defn)
  File ".pyenv/versions/3.6.12/envs/36/lib/python3.6/site-packages/mypy/checker.py", line 461, in _visit_overloaded_func_def
    self.check_overlapping_overloads(defn)
  File ".pyenv/versions/3.6.12/envs/36/lib/python3.6/site-packages/mypy/checker.py", line 482, in check_overlapping_overloads
    assert isinstance(inner_type, CallableType)
AssertionError: 
test.py:7: : note: use --pdb to drop into pdb
```

**To Reproduce**

```py
import functools
from typing import Union, overload

from typing_extensions import Literal


@overload  # <- mypy places the error here.
def get_cached(b: Literal[True]) -> int:
    ...


@overload
def get_cached(b: Literal[False]) -> str:
    ...


@functools.lru_cache()  # commenting out this line makes the crash go away.
def get_cached(b: bool) -> Union[str, int]:
    if b:
        return 5
    return "five"


reveal_type(get_cached(True))
reveal_type(get_cached(False))
```

I also tried decorating each overload with `@functools.lru_cache`,
```py
@overload
@functools.lru_cache()
def get_cached(b: Literal[True]) -> int:
    ...
```
but that did not fix anything.

**Your Environment**

- Mypy version used: `0.820+dev.98c2c1289ff76570457fc547ae254293aea6a019`
- Mypy command-line flags: `--traceback`
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: 3.6.12
- Operating system and version: macOS 10.15.7

**Comment by AlexWaygood** [comment] 2022-03-24 14:38
Can't reproduce on mypy 0.920+. Looks like this is now fixed! 🎉🥳

**Closed by AlexWaygood** 2022-03-24 14:38 UTC
Labels: crash
