### ISSUE TITLE
Ternary operator assignment reports type error

### ISSUE THREAD

**Issue by eugene-makunin** [python/mypy#6757] opened 2019-05-03 10:24 UTC
Hi guys! I have this code:

```
def foo(field: Union[str, Tuple[str, ...]]) -> None:
    fields_sequence: Sequence[str] = field if isinstance(field, tuple) else (field,)
    print(fields_sequence)
```

That looks fine for me but mypy reports the next error:

> error: Incompatible types in assignment (expression has type "object", variable has type "Sequence[str]")

Actually, there are two tuples on both ternary operator sides. I think this is a defect.

**Comment by ilevkivskyi** [comment] 2019-05-03 12:07
Duplicate of https://github.com/python/mypy/issues/4975

**Closed by ilevkivskyi** 2019-05-03 12:07 UTC
