### ISSUE TITLE
Reference before assignment errors

### ISSUE THREAD

**Issue by jrab89** [python/mypy#13976] opened 2022-10-31 22:32 UTC
**Bug Report**

mypy doesn't catch "reference before assignment" errors

**To Reproduce**

```python
import os
from typing import Optional


def greet(name: Optional[str]) -> None:
    if name:
        name_str = f", {name}."

    print(f"Hello{name_str}")
    name_str = "bar"


def main() -> None:
    greet(os.environ.get("NAME"))


if __name__ == "__main__":
    main()
```

**Expected Behavior**

If the above program is ran without `NAME` set, it'll crash:

```
$ NAME='Jeff' python reference_before_assign.py
Hello, Jeff.
$ python reference_before_assign.py
Traceback (most recent call last):
  File "/Users/jeff.rabovsky/git_repos/notes/reference_before_assign.py", line 17, in <module>
    main()
  File "/Users/jeff.rabovsky/git_repos/notes/reference_before_assign.py", line 13, in main
    greet(os.environ.get("NAME"))
  File "/Users/jeff.rabovsky/git_repos/notes/reference_before_assign.py", line 9, in greet
    print(f"Hello{name_str}")
UnboundLocalError: local variable 'name_str' referenced before assignment
```

My expectation was that mypy would catch this error.

**Actual Behavior**

```
$ mypy --strict reference_before_assign.py
Success: no issues found in 1 source file
```

**Your Environment**

- Mypy version used: `0.982`
- Mypy command-line flags: `--strict`
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: 3.10.5

Thanks for your help!

**Comment by hauntsaninja** [comment] 2022-10-31 22:34
Thanks, duplicate of https://github.com/python/mypy/issues/2400 , https://github.com/python/mypy/issues/686 , etc. Is actively being worked on these days

**Comment by AlexWaygood** [comment] 2022-10-31 22:36
(Sorry, reopened by accident...)

**Closed** 2022-10-31 22:36 UTC
Labels: bug

**Comment by PeterJCLaw** [comment] 2022-11-29 10:15
Connecting the dots as the linked issues are closed: looks like https://github.com/python/mypy/issues/4019 tracks this case now.
