### ISSUE TITLE
Gets number of arguments to `Callable` fields wrong.

### ISSUE THREAD

**Issue by zuckerruebe** [python/mypy#11021] opened 2021-08-25 11:28 UTC
**Bug Report**

MyPy having issues with `Callable` fields.

**To Reproduce**

Type check the following code:
```python
import typing as _tp
import dataclasses as _dc


class C:
    pass


_PropertyGetter = _tp.Callable[[C], _tp.Union[str, float]]


@_dc.dataclass
class _Property:
    name: str
    getter: _PropertyGetter


p = _Property("foo", lambda _: "bar")


c = C()
print(p.getter(c))

```

**Expected Behavior**

`mypy` should run through without reporting an error.

**Actual Behavior**

I get the following errors:

```
C:\Users\damian.birchler\src\pytrnsys\pytrnsys_gui\venv\Scripts\mypy.exe C:\Users\damian.birchler\dev\pytrnsys\issues\hydraulic-loops\mypy-bug\a.py
C:\Users\damian.birchler\dev\pytrnsys\issues\hydraulic-loops\mypy-bug\a.py:22: error: Invalid self argument "_Property" to attribute function "getter" with type "Callable[[C], Union[str, float]]"
C:\Users\damian.birchler\dev\pytrnsys\issues\hydraulic-loops\mypy-bug\a.py:22: error: Too many arguments
Found 2 errors in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: 0.812
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: Python 3.9.0
- Operating system and version: Windows 10 Education

**Comment by JelleZijlstra** [comment] 2021-08-25 12:47
Duplicate of #9975

**Closed by JelleZijlstra** 2021-08-25 12:47 UTC
Labels: bug
