### ISSUE TITLE
Cannot use alias from class scope

### ISSUE THREAD

**Issue by decaz** [python/mypy#9617] opened 2020-10-20 00:40 UTC
Listing:
```python
class Foo:
    Bar = int

var: Foo.Bar
```
mypy error:
```
$ mypy xxx.py 
xxx.py:4: error: Variable "xxx.Foo.Bar" is not valid as a type
xxx.py:4: note: See https://mypy.readthedocs.io/en/latest/common_issues.html#variables-vs-type-aliases
Found 1 error in 1 file (checked 1 source file)
```
Environment:
```
$ python -V
Python 3.9.0
$ mypy -V
mypy 0.790
```

**Comment by AlexWaygood** [comment] 2022-04-01 19:27
Closing as a duplicate of #9238

**Closed by AlexWaygood** 2022-04-01 19:27 UTC
Labels: bug, topic-type-alias
