### ISSUE TITLE
Property with different type (getter type != setter type)

### ISSUE THREAD

**Issue by elarivie** [python/mypy#4970] opened 2018-04-25 15:18 UTC
With Mypy 0.590 (This was also the case with previous version), using the flag --strict-optional

Would it be possible to handle a different type for the getter/setter of properties.

In below code example I would expect no Mypy errors, but there are errors each time the property message is assigned a None value, even though the setter arguments list mention that message may be provided a None.

```Python
from typing import Optional


class Hello(object):
    @property
    def message(self) -> str:
        """Get the message (Never None)."""
        return self.__message

    @message.setter
    def message(self, value: Optional[str]) -> None:
        """Set the message (Set to empty string if None is provided)."""
        self.__message = "" if value is None else str(value)

    def __init__(self) -> None:
        # Initialize default values of the properties:
        self.message = None   # error: Incompatible types in assignment (expression has type "None", variable has type "str")


x = Hello()
x.message = "World !"
a = "Hello " + x.message
x.message = None  # error: Incompatible types in assignment (expression has type "None", variable has type "str")

```

**Comment by PPACI** [comment] 2018-05-07 07:35
After a quick test, it also affect mypy 0.600 without flag (since --strict-optional is now enabled by default)

**Comment by ethanhs** [comment] 2018-05-07 09:53
Actually this is a duplicate of https://github.com/python/mypy/issues/3004. Closing.

**Closed by ethanhs** 2018-05-07 09:53 UTC
Labels: bug, priority-1-normal
