### ISSUE TITLE
Mypy does not correctly infer type of union typed variable on asignment when on same line as type declaration 

### ISSUE THREAD

**Issue by tblum** [python/mypy#17856] opened 2024-10-01 11:19 UTC
Mypy does not correctly infer the type of in the following example
`i: int | None = 42` 
i's type is int | None

when splitting declaration and assignment it works i.e:
```
i: int | None
i = 42
```
i's type is int

`i: int | None = 42`
makes for nicer code. 

**To Reproduce**

```python
i: int | None = 42
i = i + 1
```

**Expected Behavior**
Should be accepted by mypy

**Actual Behavior**

inone_test.py:2: error: Unsupported operand types for + ("None" and "int")  [operator]
none_test.py:2: note: Left operand is of type "int | None"

**Your Environment**

- Mypy version used: 1.10.0
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): None
- Python version used: 3.12.6

**Comment by hauntsaninja** [comment] 2024-10-01 18:18
Duplicate of https://github.com/python/mypy/issues/2008

(there's consensus mypy should change this and it's a trivial change to make, but it exposes some bugs in the binder)

**Closed by hauntsaninja** 2024-10-01 18:18 UTC
Labels: bug
