### ISSUE TITLE
`module = None` optional import shows error locally but not from tox

### ISSUE THREAD

**Issue by davidism** [python/mypy#10512] opened 2021-05-20 14:40 UTC
[In Flask, we have the following lines:](https://github.com/pallets/flask/blob/2.0.x/src/flask/cli.py#L22-L30)

```python
try:
    import dotenv
except ImportError:
    dotenv = None
```

Running mypy shows an error:

```
src/flask/cli.py:25: error: Incompatible types in assignment (expression has type "None", variable has type Module)
```

However, adding a `# type: ignore` comment, then running mypy through tox shows an error about the ignore:

```
src/flask/cli.py:25: error: unused 'type: ignore' comment
```

Running tox without the comment shows everything passing.

So we're left in the situation where we need to pass in CI, but if anyone runs mypy locally they see this error, fix it, then CI fails for them.

What's extra strange is that right below the failing code is another optional import, with the ignore comment, that passes both locally and through tox.

```python
try:
    import ssl
except ImportError:
    ssl = None  # type: ignore
```

- Mypy version used: 0.812
- Mypy configuration options from `setup.cfg`: https://github.com/pallets/flask/blob/b5518e23f5b85ba6e069a8151ed42209947f3849/setup.cfg#L89-L105
- Python version used: 3.9.1

**Comment by hauntsaninja** [comment] 2021-05-20 17:47
Duplicate of https://github.com/python/mypy/issues/8990#issuecomment-642896800 and https://github.com/python/mypy/issues/8823
`ssl = cast(Any, None)` should be a workaround, if you need an optional type inferred then you could alias and assign or use `if TYPE_CHECKING` to lie. Some more discussion in the linked issues.

**Closed by hauntsaninja** 2021-05-20 17:47 UTC
Labels: bug

**Comment by davidism** [comment] 2021-05-20 17:51
Thanks. I want to make sure we're not doing anything incorrect with our configuration or testing though, it's not clear why it fails with `mypy` but not with `tox -e typing`.
