### ISSUE TITLE
TypedDict using keywords causes "error: Too many arguments for TypedDict()"

### ISSUE THREAD

**Issue by lillekemiker** [python/mypy#11555] opened 2021-11-14 19:52 UTC
**Bug Report**

In the typing docs for `TypedDict` there is an example of defining a `TypedDict` using keywords mapped to types

```
Point2D = TypedDict('Point2D', x=int, y=int, label=str)
```

When running mypy on this exact example, I get the following error:

```
type_test.py:4: error: Too many arguments for TypedDict()
```

If using the alternative definition with a positional dictionary, no error.

```
Point2D = TypedDict('Point2D', {'x': int, 'y': int, 'label': str})
```

Link to docs:
https://docs.python.org/3/library/typing.html#typing.TypedDict

**To Reproduce**

1. Create a file with the above code example and necessary imports
2. Run mypy on file
3. Observe error message

**Expected Behavior**

No error

**Actual Behavior**

Error.

**Your Environment**

- Mypy version used: 0.812 and 0.910 tested
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): ignore_missing_imports=true
- Python version used: 3.9.2
- Operating system and version: macOS 11.6

**Comment by sobolevn** [comment] 2021-11-18 17:38
Duplicate of https://github.com/python/mypy/issues/11047

Will be solved by https://github.com/python/mypy/pull/11206

**Comment by 97littleleaf11** [comment] 2021-12-14 12:28
I opened an issue about this. https://bugs.python.org/issue46066.
I think this syntax is confusing since we have the `total` keyword.

**Comment by 97littleleaf11** [comment] 2021-12-15 15:14
https://github.com/python/mypy/issues/2492#issuecomment-579500959: 
> This doesn't seem feasible now that we have the total=<bool> keyword argument to TypedDict. Also, TypedDict is officially supported in Python and we want to avoid mypy-specific extensions.

**Closed by 97littleleaf11** 2021-12-15 15:14 UTC
Labels: bug, topic-typed-dict
