### ISSUE TITLE
Allow error codes to be disabled inline

### ISSUE THREAD

**Issue by allanlewis** [python/mypy#9989] opened 2021-01-28 15:17 UTC
**Feature**

I have some code like this:

```py
flag = True
if flag:
    var: str = 'foo'
else:
    var: str = 'bar'
```

`mypy` complains about the redefinition of `var`:

```
foo.py:5: error: Name 'var' already defined on line 3
```

I would like `mypy` to _not_ complain about this as long as the types are the same, or "compatible" by some definition.

Needless to say, the code within my `if..else` blocks is more complex than assigning a literal - in one case each branch has a `try..except` block, so I can't just use a ternary.

**Pitch**

The project I'm currently working on is a web app that uses feature flags. We therefore often have code blocks like the one above, and we would like `mypy` to not complain about this type of structure.

**Comment by JelleZijlstra** [comment] 2021-01-28 17:39
As a workaround, you can put `var: str` above the if-else.

**Comment by allanlewis** [comment] 2021-01-29 10:06
Thanks, @JelleZijlstra - that works for me.

**Comment by PeterJCLaw** [comment] 2021-01-31 13:23
You can also skip the annotation on the second assignment:
``` python

**Comment by terencehonles** [comment] 2021-02-03 22:08
This seems to be a dupe of #6223 unless you want to describe how error codes should be disabled inline.

If you are not aware you can use `# type: ignore` and run with `--show-error-codes` in order to be more specific `# type: ignore[error-code]. You should also read what disabling the type checking does https://mypy.readthedocs.io/en/stable/common_issues.html#spurious-errors-and-locally-silencing-the-checker

**Comment by AlexWaygood** [comment] 2022-03-27 21:02
> This seems to be a dupe of #6233 unless you want to describe how error codes should be disabled inline.

I agree. I'm not sure exactly what's being proposed here.

**Closed by AlexWaygood** 2022-03-27 21:02 UTC
Labels: feature
