### ISSUE TITLE
"pytest -n0 mypy/test/testcmdline.py" fails on every test

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#4368] opened 2017-12-15 02:08 UTC
E.g.
```
$ pytest -n0 mypy/test/testcmdline.py -x
================================================= test session starts ==================================================
platform darwin -- Python 3.6.2, pytest-3.3.1, py-1.5.2, pluggy-0.6.0
rootdir: /Users/guido/src/mypy, inifile: pytest.ini
plugins: xdist-1.20.1, forked-0.2, cov-2.5.1
collected 77 items                                                                                                     

mypy/test/testcmdline.py F

======================================================= FAILURES =======================================================
__________________________________________________ testCmdlinePackage __________________________________________________
data: /Users/guido/src/mypy/test-data/unit/cmdline.test:12:
/Users/guido/src/mypy/mypy/test/testcmdline.py:38: in run_case
    test_python_cmdline(testcase)
/Users/guido/src/mypy/mypy/test/testcmdline.py:83: in test_python_cmdline
    testcase.file, testcase.line))
/Users/guido/src/mypy/mypy/test/helpers.py:86: in assert_string_arrays_equal
    raise AssertionFailure(msg)
E   mypy.myunit.AssertionFailure: Invalid output (/Users/guido/src/mypy/test-data/unit/cmdline.test, line 12)
------------------------------------------------- Captured stderr call -------------------------------------------------
Expected:
  pkg/a.py:1: error: Name 'undef' is not defined (diff)
  pkg/subpkg/a.py:1: error: Name 'undef' is not defined (diff)
Actual:
  Traceback (most recent call last):            (diff)
    File "/Users/guido/src/mypy/scripts/mypy", line 4, in <module> (diff)
      from mypy.main import main                (diff)
  ModuleNotFoundError: No module named 'mypy'   (diff)

Alignment of first line difference:
  E: pkg/a.py:1: error: Name 'undef' is not defined
  A: Traceback (most recent call last):
     ^
=============================================== 1 failed in 0.25 seconds ===============================================
```
Every test in that fails this way with `-n0`. Without the `-n0` flag they all pass (which is why this wasn't caught by CI).

**Comment by ethanhs** [comment] 2017-12-15 02:43
This is a duplicate of #4127.

**Closed** 2017-12-15 02:43 UTC
