### ISSUE TITLE
Class with function fields incorrectly thinks first argument is self

### ISSUE THREAD

**Issue by Dentosal** [python/mypy#5485] opened 2018-08-15 11:31 UTC
This is a bug report.

# Minimal repro

```python
from dataclasses import dataclass
from typing import Callable

@dataclass
class Repro:
    fn: Callable[[int], str]

r = Repro(fn=repr)
assert "1" == r.fn(1)
```

Works correctly when dataclass is not used, i.e. when `Repro` is

```python
class Repro:
    def __init__(self, fn: Callable[[int], str]) -> None:
        self.fn = fn
```

## Actual behavior

```python
repro.py:9: error: Invalid self argument "Repro" to attribute function "fn" with type "Callable[[int], str]"
repro.py:9: error: Too many arguments
```

When running with Python, works correctly. Doesn't throw any exceptions.

## Expected behavior

Successful type check

# Environment

## Versions

Tested with two versions, 0.620 and current version from GitHub.

* Python 3.7.0
* mypy 0.620
* mypy 0.630+dev-a2ffde90635baf05e264f8d899f5705c52b27c2a

## Mypy config

```ini
[mypy]
warn_redundant_casts = True
warn_unused_ignores = True
incremental = True

follow_imports = normal
ignore_missing_imports = True
disallow_untyped_calls = True
disallow_untyped_defs = True
check_untyped_defs = True
warn_return_any = True
warn_no_return = True
no_implicit_optional = True
strict_optional = True
```

**Comment by ilevkivskyi** [comment] 2018-08-15 13:25
This is not something specific to dataclasses. There is a simpler repro that gives same errors:
```python
class Repro:
    fn: Callable[[int], str]

r = Repro()
r.fn(1)
```
The problem is the same as in https://github.com/python/mypy/issues/708. I would however _not_ close this as a duplicate, because this issue highlights another aspect of the problem.

**Comment by vim345** [comment] 2018-09-24 20:49
I just came across the same issue. I guess a lot of people are going to face this issue very soon, as it's very easy to reproduce it using dataclasses.

**Comment by ilevkivskyi** [comment] 2018-09-25 01:37
I guess this should be not hard to fix, mypy cares whether a callable was assigned in class (to match what Python does), so we should just tweak the `Var`s in plugin to pretend they were assigned on `self`. But we still need a volunteer who will fix this.

**Comment by ojii** [comment] 2018-11-27 06:04
If someone needs a workaround, this works:

```python
from dataclasses import dataclass
from typing import *

T = TypeVar("T")


@dataclass
class Box(Generic[T]):
    inner: T

    @property
    def unboxed(self) -> T:
        return self.inner


@dataclass
class Repro:
    fn: Box[Callable[[int], str]]


Repro(fn=Box(repr)).fn.unboxed(1)
```

**Comment by s-knibbs** [comment] 2019-03-27 13:48
I've found that another workaround to this is to use a [callback protocol](https://mypy.readthedocs.io/en/latest/protocols.html#callback-protocols) instead of `Callable`

**Comment by rightfold** [comment] 2019-07-17 09:02
When using NamedTuple this problem does not arise.

**Comment by TH3CHARLie** [comment] 2020-01-21 17:54
I am happy to volunteer to fix this and any guidances will be greatly helpful @ilevkivskyi

**Comment by ilevkivskyi** [comment] 2020-01-22 11:19
@TH3CHARLie Fixing this in general may be tricky, but fixing just the dataclass case, should be easy. In any case, please go ahead!

**Comment by Kein** [comment] 2020-12-14 12:35
> Fixing this in general may be tricky,
Taking into account parent issue is from 2015 I'd say that is an understatement of the year :P
Spent hours on this until someone linked me the issue.

**Comment by jordan-bucholtz** [comment] 2021-02-11 01:16
I'm still running into this issue with dataclasses. @TH3CHARLie @ilevkivskyi  Any resolution on this? 😃 

### versions
mypy 0.782
Python 3.8.7

**Comment by altendky** [comment] 2021-02-11 01:26
@jordan-bucholtz i don't know if it makes any difference but fyi there is 0.800 (and 0.790 in between).

https://pypi.org/project/mypy/0.800/

**Comment by NeilGirdhar** [comment] 2021-02-11 01:37
@altendky I've been using 0.800, and I'm pretty sure this is still broken for me.

**Comment by jp-larose** [comment] 2021-02-17 00:28
Wondering if the solution is to somehow flag the Callable instance variable as a static method.  Because that's essentially the intended use.  Now, I'm not sure if the fix should be in mypy or in the typing library.

**Comment by wyfo** [comment] 2021-05-28 22:25
> I guess this should be not hard to fix, mypy cares whether a callable was assigned in class (to match what Python does), so we should just tweak the `Var`s in plugin to pretend they were assigned on `self`. But we still need a volunteer who will fix this.

@ilevkivskyi That's what I've done in #10536 (and I could have saved investigation time if I'd read your comment).

**Comment by wyfo** [comment] 2021-05-28 23:49
I've also started to implement a fix for the general case (not only dataclasses) in #10548.
However, I've found at least 10 tests (listed below) where callable fields are bound as methods as the expected test result.
For example:
```python
# [case testCallableDataAttribute]
from typing import Callable
class A:
    g = None # type: [Callable[[A], None]]
    def __init__(self, f: Callable[[], None]) -> None:
        self.f = f
a = A(None)
a.f()
a.g()
a.f(a) # E: Too many arguments
a.g(a) # E: Too many arguments
```
According to #708 and this very issue, `a.g` should not be bound.

In my fix, I differentiate instance variables from class variables (according to PEP 526 definitions), handling only the last ones as bounded methods when callable.
So I had to fix the previous test like this:
```python
# [case testCallableDataAttribute]
from typing import Callable, ClassVar
class A:
    g = None # type: ClassVar[Callable[[A], None]]
    def __init__(self, f: Callable[[], None]) -> None:
        self.f = f
a = A(None)
a.f()
a.g()
a.f(a) # E: Too many arguments
a.g(a) # E: Too many arguments
```

@ilevkivskyi May I ask you what do you think about this solution (and about the current behavior in the tests)?

The 10 faulty tests:
- mypy/test/testcheck.py::TypeCheckSuite::testSelfTypeProperSupertypeAttribute
- mypy/test/testcheck.py::TypeCheckSuite::testSelfTypeProperSupertypeAttributeTuple 
- mypy/test/testcheck.py::TypeCheckSuite::testSelfTypeProperSupertypeAttributeGeneric
- mypy/test/testcheck.py::TypeCheckSuite::testMethodWithDynamicallyTypedMethodAsDataAttribute
- mypy/test/testcheck.py::TypeCheckSuite::testInvalidMethodAsDataAttributeInGenericClass
- mypy/test/testcheck.py::TypeCheckSuite::testPartiallyTypedSelfInMethodDataAttribute
- mypy/test/testcheck.py::TypeCheckSuite::testCallableDataAttribute
- mypy/test/testcheck.py::TypeCheckSuite::testMethodAsDataAttribute
- mypy/test/testcheck.py::TypeCheckSuite::testMethodWithInvalidMethodAsDataAttribute
- mypy/test/testcheck.py::TypeCheckSuite::testTotalOrderingLambda

**Comment by ilevkivskyi** [comment] 2021-06-05 17:12
@wyfo TBH it has been a while since I last thought about this. I don't have any strong opinions on this now. Probably it is important that correct code like this should be accepted:
```python
def m(self: A) -> None: ...

class A:
    n = m

a = A()
a.n()  # OK
```

@JukkaL is probably a better person to ask about this.

**Comment by wyfo** [comment] 2021-06-05 19:19
> Probably it is important that correct code like this should be accepted:

This use case is fine with the PR, and I've added a test to enforce it.
So let's wait for @JukkaL opinion.

**Comment by jacksonriley** [comment] 2021-07-29 09:19
I'm still hitting this with Python 3.9.4, mypy 0.910, but only if the dataclass is frozen:
```python
from dataclasses import dataclass
from collections.abc import Callable

@dataclass(frozen=True)
class Foo:
    int_to_str: Callable[[int], str]

    def bar(self, number: int) -> str:
        string = self.int_to_str(number)
        return string
```
gives
```
[jacksonriley test]$ python3 --version
Python 3.9.4
[jacksonriley test]$ python3 -m mypy --version
mypy 0.910
[jacksonriley test]$ python3 -m mypy test.py
test.py:9: error: Invalid self argument "Foo" to attribute function "int_to_str" with type "Callable[[int], str]"
test.py:9: error: "str" not callable
Found 2 errors in 1 file (checked 1 source file)
[jacksonriley test]$
```

Replacing `@dataclass(frozen=True)` with `@dataclass()` results in mypy passing.

PS: for what it's worth, the code runs fine with e.g.
```python
def fn(var: int) -> str:
    return str(var)

a = Foo(fn)
print(a.bar(2))
```

**Comment by JukkaL** [comment] 2021-11-17 11:23
The previously merged fix caused some issue and was reverted (#11571). Hopefully the issues can be addressed.

**Comment by nh2** [comment] 2021-11-26 04:07
> I've found that another workaround to this is to use a [callback protocol](https://mypy.readthedocs.io/en/latest/protocols.html#callback-protocols) instead of `Callable`

@s-knibbs Could you make an example?

**Comment by antonagestam** [comment] 2021-12-17 15:38
Bumped into this today, but wanted to fill in some details because it looks to me like the behavior varies on both dataclass vs non-dataclass and between frozen/non-frozen dataclasses. I guess it's expected for the non-dataclass to "eat" the self argument, but what causes frozen and non-frozen dataclasses to behave differently? The non-frozen dataclass seems to get it right here?

```python
from dataclasses import dataclass
from typing import Callable, Generic
from typing import TypeVar

T = TypeVar("T", bound=object, contravariant=True)
Predicate = Callable[[T], bool]


class A(Generic[T]):
    predicate: Predicate[T]

    def __call__(self, /) -> bool:
        reveal_type(self.predicate)  # note: Revealed type is "def () -> builtins.bool"
        return True


@dataclass
class B(Generic[T]):
    predicate: Predicate[T]

    def __call__(self, /) -> bool:
        reveal_type(self.predicate)  # note: Revealed type is "def (T`1) -> builtins.bool"
        return True


@dataclass(frozen=True)
class C(Generic[T]):
    predicate: Predicate[T]

    def __call__(self, /) -> bool:
        reveal_type(self.predicate)  # note: Revealed type is "builtins.bool"
        return True
```

**Comment by asib** [comment] 2022-04-25 10:06
> > I've found that another workaround to this is to use a [callback protocol](https://mypy.readthedocs.io/en/latest/protocols.html#callback-protocols) instead of `Callable`
> 
> @s-knibbs Could you make an example?

Probably too late for parent, but for anyone else who could use an example:

```python
from dataclasses import dataclass
from typing import Callable
from typing_extensions import Protocol

class FunctionType(Protocol):
    def __call__(self, x: int) -> int:
        pass

@dataclass(frozen=True)
class A:
    fn: Callable[[int], int]
    
@dataclass(frozen=True)
class B:
    fn: FunctionType


A(fn=lambda x: x).fn(1) # Invalid self argument "A" to attribute function "fn" with type "Callable[[int], int]"
B(fn=lambda x: x).fn(1)
```

**Comment by eternal-sorrow** [comment] 2022-07-01 12:48
I encoutered this with `pathlib.Path('/my/path').stat().st_size`. I got 
```
Invalid self argument "stat_resut" to attribute function "st_size" with type "Callable[[stat_result], int]"
```
This way I can't use any of the workarounds because I can't modify the standard `stat_result` type.

**Closed** 2022-08-13 01:17 UTC
Labels: bug, priority-1-normal, false-positive, topic-dataclasses
