### ISSUE TITLE
mypy confused by omitted optional argument before kwargs

### ISSUE THREAD

**Issue by jeffkaufman** [python/mypy#2990] opened 2017-03-13 19:39 UTC
When I give mypy:

```
def foo(bar: bool = False, **kwargs: str) -> None:
    print('foo(bar=%s, **kwargs=%s)' % (bar, kwargs))

foo(**{'a': 'a', 'b': 'b'})
```

I get:

    4: error: Argument 1 to "foo" has incompatible type **Dict[str, str]; expected "bool"

On the other hand, these work fine:

```
foo(a='a', b='b')
foo(a='a', b='b', bar=True)
```

Running the code, python has no objection to it:

    $ python ~/tmp.py
    foo(bar=False, **kwargs={'a': 'a', 'b': 'b'})

This is with:

```
$ python --version
Python 3.6.0
$ mypy --version
mypy 0.470```

**Comment by gvanrossum** [comment] 2017-03-13 19:43
I believe this is a duplicate of #1969. @jeffkaufman If you agree can you please close your own issue?

**Comment by jeffkaufman** [comment] 2017-03-13 21:22
Thanks, that does look the same.

**Closed** 2017-03-13 21:22 UTC
