### ISSUE TITLE
Type equality should imply issubclass

### ISSUE THREAD

**Issue by llchan** [python/mypy#6306] opened 2019-02-01 22:24 UTC
It seems that type equality (via `is`) does not currently imply issubclass. Unless there's an edge case I'm not thinking of, it should be a strictly tighter bound so it should be safe to add to mypy's inference rules. 

As a bonus, I have this example that puzzled me at first glance. It appears that mypy is doing exactly the opposite of what it should be doing:

```python
T = TypeVar('T', int, str)


def foo(type_: Type[T]) -> T:
    if type_ is int:
        return foo_int(type_)  # ... incompatible type "Type[str]"; expected "Type[int]"
    elif type_ is str:
        return foo_str(type_)  # ... incompatible type "Type[int]"; expected "Type[str]"
    else:
        return TypeError(f'invalid type_={type_!r}')


def foo_int(type_: Type[int]) -> int:
    assert type_ is int
    return type_()


def foo_str(type_: Type[str]) -> str:
    assert type_ is str
    return type_()
```

The error messages seem to imply that mypy had eliminated exactly the opposite of what it should have.  However, it turns out this is just due to the try-everything way generics are evaluated, combined with the above issue of type equality not implying issubclass.

**Comment by ilevkivskyi** [comment] 2019-02-01 22:41
This is a duplicate of https://github.com/python/mypy/issues/5847

The weird errors you see is because mypy type-checks bodies of functions generic in constrained variables multiple times, once for each constraint value.

**Closed by ilevkivskyi** 2019-02-01 22:41 UTC
