### ISSUE TITLE
Conditional import via try-except renders error for imported type

### ISSUE THREAD

**Issue by tuukkamustonen** [python/mypy#8319] opened 2020-01-23 12:44 UTC
I'm running python 3.5 (mypy `0.761`). `TypedDict` is not in `typing` so I have `typing_extensions` installed (for python < 3.8).

However, the library I'm building supports python up to 3.8, which has `TypedDict` built-in so I might as well use that.

So I tried conditional import:

```python
try:
    from typing import TypedDict  # type: ignore
except ImportError:
    from typing_extensions import TypedDict

Foo = TypedDict('Foo', {
    'id': str,
})

def whatever(data: Foo) -> None:
    pass
```

Results in:

```
typetest.py:12: error: Variable "typetest.Foo" is not valid as a type
```

Adjusting the import as so makes the problem go away:

```python
import sys
if sys.version_info >= (3, 8):
    from typing import TypedDict
else:
    from typing_extensions import TypedDict
```

https://mypy.readthedocs.io/en/stable/common_issues.html#python-version-and-system-platform-checks doesn't at least directly suggest to use this style for imports, though. What is the proper/preferred way to do conditional imports?

**Comment by JelleZijlstra** [comment] 2020-01-23 16:22
Yes, mypy should ideally support the pattern you tried. I am pretty sure there is already an open issue about this, but I can't find it right now.

**Comment by ilevkivskyi** [comment] 2020-01-25 12:14
This is essentially a duplicate of https://github.com/python/mypy/issues/1297

**Closed by ilevkivskyi** 2020-01-25 12:14 UTC
