### ISSUE TITLE
Generics as defaults

### ISSUE THREAD

**Issue by genglandaer** [python/mypy#17067] opened 2024-03-26 22:07 UTC
**Bug Report**

When you use a function as a default in a generic class, its types are not interpreted correctly

(A clear and concise description of what the bug is.)

**To Reproduce**

[LINK TO GIST
](https://mypy-play.net/?mypy=latest&python=3.12&gist=87ab4a6d81265cec4add17de5fd4ba0c)

**Expected Behavior**

When passing in a lambda to return the value passed in, it should interpret that the second generic type is the same as the first.

**Actual Behavior**

It is ok if you pass a lambda in the constructor. It throws an error if you have it as a default in the constructor.

main.py:8: error: Incompatible default for argument "parse_to" (default has type "Callable[[V], V]", argument has type "Callable[[V], K]")  [assignment]
main.py:8: error: Incompatible return value type (got "V", expected "K")  [return-value]

**Comment by hauntsaninja** [comment] 2024-03-27 09:21
Duplicate of #3737

**Closed by hauntsaninja** 2024-03-27 09:21 UTC
Labels: bug
