### ISSUE TITLE
Mistype of empty tuples

### ISSUE THREAD

**Issue by rtpg** [python/mypy#4090] opened 2017-10-10 05:08 UTC
Perhaps I'm missing some subtlety here but mypy complains about two usages for empty tuples that I do not believe are invalid:

```
print( ()  + (2,3,))
foo = True
print( ((1,2,) if foo else ()) + (2,3,))
```

This gives:
```
my_test.py:1: error: Unsupported operand types for + ("Tuple[]" and "Tuple[int, int]")
my_test.py:3: error: Unsupported left operand type for + ("object")
```

Typing this out, it feels like it might be an issue with generics. This started getting reported in 0.530 for me.

**Comment by JelleZijlstra** [comment] 2017-10-10 05:56
I think this is an old issue, #224. Your description makes it sound like this is a regression in 0.530 though, can you confirm that? If so, this should be high priority to fix.

**Comment by rtpg** [comment] 2017-10-10 06:02
This was not getting caught by our CI with `0.521`, but an instance of this started getting caught in `0.530` so I believe it is a regression.

**Comment by gvanrossum** [comment] 2017-10-10 15:32
I tried to bisect this and found it still occurs back with version 0.501, so don't think this is a regression. Probably there was some other reason why the real code that you were checking passed (perhaps some other bug make mypy ignore some code).

FWIW the example I tried was:
```py
a = () + (1,2)
```
This gives two errors:
```
__tmp__.py:1: error: Unsupported operand types for + ("tuple" and "Tuple[int, int]")
__tmp__.py:1: error: Need type annotation for variable
```

**Comment by ilevkivskyi** [comment] 2017-10-10 15:34
Since this is not a regression, I propose to close this as a duplicate of #224

**Closed by ilevkivskyi** 2017-10-10 15:34 UTC
