### ISSUE TITLE
Can't assign dict instance to MutableMapping with Union values

### ISSUE THREAD

**Issue by Danmou** [python/mypy#8136] opened 2019-12-12 12:49 UTC
The following code should pass:
```python
from typing import MutableMapping, Union

foo = {'bar': 1.0}
bar: MutableMapping[str, Union[str, float]] = foo
```
But when checked with mypy it gives the following error:
```
error: Incompatible types in assignment (expression has type "Dict[str, float]", variable has type "MutableMapping[str, Union[str, float]]")  [assignment]
```

If I replace `MutableMapping` with `Mapping` or `Union[str, float]` with `float`, it typechecks fine.

**Comment by msullivan** [comment] 2019-12-12 21:47
This is correct, though certainly annoying. Or rather, it's a broad consequence of our current type inference algorithms.

The inferred type of `foo` here will be `Dict[str, float]`, and so assigning it to `bar` would be incorrect (because a `str` could be written to a value). Annotating `foo` as `Dict[str, Union[str, float]]` would fix the problem.

**Closed by msullivan** 2019-12-12 21:47 UTC

**Comment by Danmou** [comment] 2019-12-13 10:26
I see, although in my case I was directly assigning the result of a function like this:
```python
from typing import Dict, MutableMapping, Union

def foo() -> Dict[str, float]:
    return {'bar': 1.0}

bar: MutableMapping[str, Union[str, float]] = foo()
bar['baz'] = 'string'
```
In this case I'm assigning the only reference to the dict so broadening the type would still be safe, but that's a bit of an edge case. A workaround for is to simply make a copy (which is anyway cheap in my case):
```python
bar: MutableMapping[str, Union[str, float]] = dict(foo())
```

**Comment by msullivan** [comment] 2019-12-13 20:54
Oh, yeah, in this case it is definitely intended behavior because we don't have a way of knowing it is the only reference.

Workarounds without runtime costs include a `cast` or a `# type: ignore`.
