### ISSUE TITLE
Support type inference after using any()

### ISSUE THREAD

**Issue by KazMiddelhoek** [python/mypy#17992] opened 2024-10-18 10:47 UTC
This function:

```
def test(a: int | None, b: int | None) -> int | None:

    if any(x is None for x in [a, b]):
        return None

    return a+b
```

and this function:
```
def test_2(a: int | None, b: int | None) -> int | None:

    if a is None or b is None:
        return None

    return a+b
```
do the same thing. However, for the first one, mpy produces an error:
```
test.py:8: error: Unsupported operand types for + ("int" and "None")  [operator]
test.py:8: error: Unsupported operand types for + ("None" and "int")  [operator]
test.py:8: error: Unsupported left operand type for + ("None")  [operator]
```
while for the second one, the fact that a and b are not None is inferred correctly. 

It would be great to improve the inference for this case!

**Comment by hauntsaninja** [comment] 2024-10-20 21:52
Duplicate of https://github.com/python/mypy/issues/17149

**Closed by hauntsaninja** 2024-10-20 21:52 UTC
Labels: feature, topic-type-narrowing
