### ISSUE TITLE
stack trace on, I think, "except IOError, (errno, strerr):"

### ISSUE THREAD

**Issue by dmankins** [python/mypy#4010] opened 2017-09-26 00:11 UTC
(Version 0.521)

I have a large body of Python 2.7 code that I am first augmenting with mypy and more extensive tests in preparation to converting to Python 3(.7, probably, by the time I get to it).

This code snippet:
--------------------------------------------------------------------------------------------
```python
class adminController(object):
    def handleEULADisplayAndAcceptance(self):
        if answer == "Accept":
            try:
                pass
            except IOError, (errno, strerr):
                self.__ui.infoBox("Error: Unable to write EULA acceptance file; {}: {}."
                                  .format(errno, strerr))
```
--------------------------------------------------------------------------------------------
Invoked:

mypy --py2 --ignore-missing-imports --show-traceback mypy_killer.py

Produces the attached stack-trace.

Having pared it down, it's easy to see how I can work around this.

Thanks for a wonderful tool!

[mypy-backtrace.txt](https://github.com/python/mypy/files/1331303/mypy-backtrace.txt)

**Comment by ethanhs** [comment] 2017-09-26 00:59
Hello, glad you like the tool. This is a duplicate of #3772. Apparently this syntax is not as rare as it seems!

**Closed by ethanhs** 2017-09-26 00:59 UTC
