### ISSUE TITLE
Name resolution in mypy doesn't match Python

### ISSUE THREAD

**Issue by gaborbernat** [python/mypy#3775] opened 2017-07-28 11:11 UTC
For example:

```python
class A(object):

    def float(self):
            # type: () -> float 
           return 1.0
```

gives:

```
mypy -v .
LOG:  Mypy version 0.521
LOG:  Metadata not found for test
LOG:  Parsing ./test.py (test)
LOG:  Processing SCC singleton (test) as inherently stale with stale deps (builtins)
LOG:  No fresh SCCs left in queue
LOG:  Build finished in 0.862 seconds with 10 modules, 2071 types, and 1 errors
test.py:3: error: Invalid type "test.A.float"
```

**Comment by ilevkivskyi** [comment] 2017-07-28 11:34
Unfortunately, this is not an easy (and in fact old) problem. Mypy doesn't record the order of assignments (and other name bindings), so that while you are inside a class, then it finds ``float`` in the class namespace first. There is a simpler  repro of this:
```python
y = x  # no error here
x = 1
```
I am not sure whether we should keep this open or mark it as a duplicate of https://github.com/python/mypy/issues/2788

As a workaround, you can write ``builtins.float`` in the annotation, and add ``import builtins`` at the start (on Python 2 this import needs to be under ``if typing.TYPE_CHECKING: ...``).

**Comment by JukkaL** [comment] 2017-07-28 17:05
Mypy could perhaps detect the issue and give a more informative error message, such as suggesting the `import builtins` trick.

**Comment by ns-cweber** [comment] 2017-08-19 19:19
@JukkaL I'm not sure if this is the same issue, but I'm seeing something similar for this example:

```
import foo

class Bar:
    def foo(f: foo.Foo) -> None:
        pass
```

If this is related, then the error message might need to be more elaborate.

**Comment by ilevkivskyi** [comment] 2017-08-19 19:41
@ns-cweber This is closely related. The problem is that mypy does not follow Python name resolution rules exactly one to one. There is no simple solution for this, but maybe indeed we could make the error message more clear. Anyway, I am raising priority to normal.

**Comment by gaborbernat** [comment] 2017-10-05 09:49
the workaround suggested by @ilevkivskyi works for now well, with only the downside that people unfamiliar with the problem initially may wonder why we used the ``builtins.float``; which can be solved by adding a comment to point it out to this issue.

**Comment by ilevkivskyi** [comment] 2019-01-14 09:41
Raising priority to high since this keeps coming. We can at least try to follow Python rules in most cases. General solution may be hard.

**Comment by erictraut** [comment] 2022-04-08 23:35
The original problem reported in this issue appears to no longer occur.

**Comment by hauntsaninja** [comment] 2022-08-03 08:58
Yup, this appears to have gotten fixed

**Closed by hauntsaninja** 2022-08-03 08:58 UTC
Labels: bug, priority-0-high, topic-usability, false-positive, topic-runtime-semantics, topic-variable-scope
