### ISSUE TITLE
Fine-grained: Failure to propagate change when import changes to another class

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#4600] opened 2018-02-20 17:02 UTC
This fine-grained incremental mode test case fails (no errors generated):

```
[case testIndirectAnnotationChange]
import a
from c import A
a.f(A())
[file a.py]
from b import A
def f(x: A) -> None: pass
[file b.py]
from c import A
[file b.py.2]
from d import A
[file c.py]
class A: pass
[file d.py]
class A: pass
[out]
==
main:3: error: Argument 1 to "f" has incompatible type "c.A"; expected "d.A"
```

My hypothesis is that this is caused by there being no dependency from `a.A` to `a.f`. #4598 might also needed to fix this (but it's not sufficient).

**Comment by msullivan** [comment] 2018-03-20 00:57
Duplicate of #4512

**Closed by msullivan** 2018-03-20 00:57 UTC
Labels: bug, topic-fine-grained-incremental
