### ISSUE TITLE
mypy should reject non-existent fields with dataclasses.replace

### ISSUE THREAD

**Issue by OlegAlexander** [python/mypy#14793] opened 2023-02-26 23:07 UTC
This issue was originally reported by @LunarLanding here:
 
https://github.com/microsoft/pyright/issues/1047

I believe mypy should reject non-existent fields when dataclasses.replace is used.

**To Reproduce**

```python
from dataclasses import dataclass, replace

@dataclass(frozen=True) 
class A:
    x : int
    y : int
    
a = A(0, 1)
b = replace(a, x=1) # ok
c = replace(a, not_a_field=1) # should be: error: "A" has no attribute "not_a_field"  [attr-defined]
```

[Mypy Playground](https://mypy-play.net/?mypy=latest&python=3.11&flags=strict&gist=92f06dd05b42698b961674ce813997e3)

**Expected Behavior**

Error: "A" has no attribute "not_a_field"  [attr-defined]

**Actual Behavior**

No error

**Related Issue**

https://github.com/python/mypy/issues/14525

**Comment by AlexWaygood** [comment] 2023-02-26 23:23
Duplicate of #5152

**Closed by AlexWaygood** 2023-02-26 23:23 UTC
Labels: feature, topic-dataclasses
