### ISSUE TITLE
async def functions with Python2-style type hints that use async features fail to type-check

### ISSUE THREAD

**Issue by edwardcwang** [python/mypy#5730] opened 2018-10-04 00:02 UTC
Python 3.7, mypy 0.630

The following code runs fine but fails to typecheck due to the Python2-style comment type annotation for `async def main`. In contrast, `async def main() -> None:` works fine.

```python
import asyncio

class AsyncContextManager:
    async def __aenter__(self):
        print('entering context')

    async def __aexit__(self, exc_type, exc, tb):
        print('exiting context')

async def f1() -> int:
  return 100

async def main():
  # type: () -> None
  async with AsyncContextManager() as mgr:
    print("bleh")
  print(await f1())

asyncio.run(main())
```

Error message:

```
$ mypy asynctest.py 
asynctest.py:15: error: invalid syntax
```

**Comment by ilevkivskyi** [comment] 2018-10-04 00:18
Duplicate of https://github.com/python/mypy/issues/5431

**Closed by ilevkivskyi** 2018-10-04 00:18 UTC
