### ISSUE TITLE
MyPy crashes with GitPython

### ISSUE THREAD

**Issue by divya-kumari-27** [python/mypy#15833] opened 2023-08-09 10:22 UTC
**Crash Report**

Mypy type-checking started failing after installing GitPython version 3.1.18

**Traceback**

```
INFO: Found 1 target...
ERROR: /home/ubuntu/code/x/e2e/y/BUILD.bazel:6:11: Type-checking //x/e2e/y:some_test failed: (Exit 1): some_test_mypy_exe failed: error executing command 
  (cd /home/ubuntu/.cache/bazel/_bazel_ubuntu/268278c517f5e65ae6e2b568ebe64594/execroot/&& \
  exec env - \
    ANSIBLE_LOCAL_TEMP=/tmp/.ansible/tmp \
    PATH=/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin:/usr/local/go/bin:/usr/local/sbin \
    PYTHONNOUSERSITE=1 \
    SPARK_REPO=external/spark \
    TOOLCHAIN_ACTION_ENV_HASH=5bdd3eda994664ecf901a65fbb2f65f233cf2d8abf271d73405c3a9f8391d76b \
  bazel-out/k8-opt/bin/x/e2e/y/some_test_mypy_exe)
# Configuration: b1fc187e58d81217fb41dc9ee5ef16ed9e295f937e7dfb8737b6a7a047f35667
# Execution platform: //deployment:remote_execution_platform
/usr/local/lib/python3.8/dist-packages/git/cmd.py:93: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.rtfd.io/en/latest/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.750
/usr/local/lib/python3.8/dist-packages/git/cmd.py:93: : note: use --pdb to drop into pdb
Traceback (most recent call last):
  File "mypy/checker.py", line 399, in accept
  File "mypy/nodes.py", line 676, in accept
  File "mypy/checker.py", line 724, in visit_func_def
  File "mypy/checker.py", line 728, in _visit_func_def
  File "mypy/checker.py", line 790, in check_func_item
  File "mypy/checker.py", line 810, in check_func_def
  File "mypy/checker.py", line 1407, in expand_typevars
  File "mypy/checker.py", line 4601, in expand_func
  File "mypy/nodes.py", line 676, in accept
  File "mypy/treetransform.py", line 109, in visit_func_def
  File "mypy/treetransform.py", line 556, in block
  File "mypy/treetransform.py", line 188, in visit_block
  File "mypy/treetransform.py", line 567, in statements
  File "mypy/treetransform.py", line 540, in stmt
  File "mypy/nodes.py", line 1195, in accept
  File "mypy/treetransform.py", line 267, in visit_if_stmt
  File "mypy/treetransform.py", line 577, in blocks
  File "mypy/treetransform.py", line 556, in block
  File "mypy/treetransform.py", line 188, in visit_block
  File "mypy/treetransform.py", line 567, in statements
  File "mypy/treetransform.py", line 540, in stmt
  File "mypy/nodes.py", line 1062, in accept
  File "mypy/treetransform.py", line 225, in visit_assignment_stmt
  File "mypy/treetransform.py", line 230, in duplicate_assignment
  File "mypy/treetransform.py", line 597, in optional_type
  File "mypy/checker.py", line 4612, in type
  File "mypy/expandtype.py", line 16, in expand_type
  File "mypy/types.py", line 1556, in accept
AssertionError: 
Aspect //tools/build_rules:mypy.bzl%mypy_aspect of //x/e2e/y:some_test failed to build
INFO: Build completed, shutting down worker pool...
INFO: Elapsed time: 12.185s, Critical Path: 10.22s
INFO: 3 processes: 3 internal.
INFO: Build Event Protocol files produced successfully.
FAILED: Build did NOT complete successfully
```

**To Reproduce**

Code is very layered and is confidential. Have not reproduced with some dummy code yet. 

**Your Environment**

- Mypy version used: 0.750
- Mypy command-line flags:
- Mypy configuration options from `mypy.ini` (and other config files):
- Python version used: 3.6
- Operating system and version: Ubuntu 20.04.4 LTS

**Comment by JelleZijlstra** [comment] 2023-08-09 13:49
> Mypy version used: 0.750

> Python version used: 3.6

Both of these are no longer supported. Mypy 0.750 is many years old. If you can't reproduce this bug with modern versions of Python and mypy, we'll have to close this.

**Comment by hauntsaninja** [comment] 2023-08-09 22:43
Feel free to re-open if you can reproduce using non ancient mypy

**Closed by hauntsaninja** 2023-08-09 22:43 UTC
Labels: crash
