### ISSUE TITLE
Invalid "unused 'type ignore' comment" messages

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#4288] opened 2017-11-28 11:44 UTC
I've seen invalid complaints about unused 'type ignore' comments recently in incremental mode. Here's an example:

```
$ mypy --config-file mypy_self_check.ini -i mypy scripts/finegrained.py
mypy/server/update.py:188: error: Need more than 3 values to unpack (5 expected)
mypy/server/update.py:195: error: Argument 2 to "calculate_active_triggers" has incompatible type "Dict[str, Optional[Dict[str, Tuple[object, ...]]]]"; expected "Dict[str, Dict[str, Tuple[object, ...]]]"
mypy/test/testmerge.py:82: error: "FineGrainedBuildManager" has no attribute "graph"
mypy/test/testmerge.py:88: error: "FineGrainedBuildManager" has no attribute "graph"
mypy/test/testmerge.py:123: error: "FineGrainedBuildManager" has no attribute "graph"
mypy/test/data.py:10: note: unused 'type: ignore' comment
mypy/report.py:28: note: unused 'type: ignore' comment
mypy/test/testreports.py:7: note: unused 'type: ignore' comment
```

The comments disappeared on the next incremental run. I hadn't touched the files where the messages came from.

I don't have a repro yet -- I'm creating the issue so that I won't lose track of it.

**Comment by gvanrossum** [comment] 2017-11-28 15:47
Hypothesis: some of the errors in the earlier files caused some things to be `Any` that were used in the later files and that stopped errors from occurring in the later files that would have been suppressed by a `# type: ignore`. This sounds like it may not be related to incremental mode. Maybe we should disable that flag when there are errors?

PS. The "warn_unused_ignores" flag can't work reliably in incremental mode anyways, since it won't appear at all for files that are read from the cache.

**Comment by JukkaL** [comment] 2017-11-28 16:01
Not sure about the hypothesis, since those errors shouldn't result in `Any` types in the files that generated the notes. Disabling the flag when there are errors sounds reasonable. 

Could we make it work in incremental mode if we'd include the unused 'type ignore' notes in the cache file? Not working correctly in incremental mode is unfortunate.

**Comment by gvanrossum** [comment] 2017-11-28 19:24
Yeah, we should probably warn when that flag is combined with incremental mode, and silently disable it when there are errors.

Adding those warnings to the cache sounds like it would be a bit complicated -- the warnings are only generated after all processing is done, so it'd have to rewrite the cache file to include the warnings.

(I think it could generate the notes at the end of each SCC, if our hypothesis about cross-file errors is correct -- see #1294. Then it could be included in the cache. But it'd be a fair bit of refactoring before we could do this.)

**Comment by msullivan** [comment] 2018-02-27 22:55
Closing as a dupe of #2960

**Closed by msullivan** 2018-02-27 22:55 UTC
