### ISSUE TITLE
Exit status 2 if mypy bails early

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#3535] opened 2017-06-13 18:32 UTC
Certain errors are considered "blockers" which means that the remaining passes are skipped, e.g. "can't read file" or "Type signature has too many arguments" (that's a weird one). We should use a different exit status when mypy exits due to such a blocker, probably exit 2. That way scripts that expect certain type errors can avoid getting too excited about such errors not occurring. :-)

**Comment by ddfisher** [comment] 2017-06-13 18:48
This is a duplicate of #2754.

**Closed by ddfisher** 2017-06-13 18:48 UTC
