### ISSUE TITLE
Support dict.update(name=x, ...)

### ISSUE THREAD

**Issue by pjenvey** [python/mypy#3118] opened 2017-04-03 21:07 UTC
Like #239 and #984, mypy doesn't seem to know about update w/ kwargs:

```python
from typing import Dict

def t(d):
    # type: (Dict[str, str]) -> None
    d.update(foo='bar', baz='quux')
```

t.py:5: error: No overload variant of "update" of "dict" matches argument types [builtins.str, builtins.str]

**Comment by JukkaL** [comment] 2017-04-04 11:54
This is a duplicate of #1031.

**Closed by JukkaL** 2017-04-04 11:54 UTC
