### ISSUE TITLE
Internal Error when MYPYPATH points to package

### ISSUE THREAD

**Issue by brandon-leapyear** [python/mypy#6717] opened 2019-04-24 18:21 UTC
* Are you reporting a bug, or opening a feature request?
    **bug**
* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.

    ```
    foo
    ├── __init__.py
    ├── bar.py
    └── foo.py
    ```

    ```python
    # foo/bar.py
    def foo(x: int, y: str) -> None:
        print(x, y)
    ```

    ```python
    # foo/foo.py
    import bar

    def foo(x: int) -> None:
        bar.foo(x)
        print(x)
    ```
* What is the actual behavior/output?

```
$ MYPYPATH=foo/ ~/miniconda3/bin/mypy foo/foo.py --show-traceback
foo/foo.py:4: error: Too few arguments for "foo"
foo/foo.py:4: error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues version: 0.701
Traceback (most recent call last):
  File "/Users/brandonchinn/miniconda3/bin/mypy", line 11, in <module>
    sys.exit(console_entry())
  File "mypy/checkexpr.py", line 3250, in accept
  File "mypy/checkexpr.py", line 247, in visit_call_expr
  File "mypy/checkexpr.py", line 317, in visit_call_expr_inner
  File "mypy/checkexpr.py", line 658, in check_call_expr_with_callee_type
  File "mypy/checkexpr.py", line 696, in check_call
  File "mypy/checkexpr.py", line 785, in check_callable_call
  File "mypy/checkexpr.py", line 1135, in check_argument_count
  File "mypy/messages.py", line 651, in too_few_arguments
  File "mypy/messages.py", line 123, in fail
  File "mypy/messages.py", line 115, in report
  File "mypy/errors.py", line 268, in report
  File "mypy/errors.py", line 289, in add_error_info
  File "mypy/errors.py", line 271, in _add_error_info
AssertionError: 
```

* What is the behavior/output you expect?

    Just the first line: `Too few arguments for "foo"`

* What are the versions of mypy and Python you are using?
  Do you see the same issue after installing mypy from Git master?

    * mypy 0.701
    * Python 3.6.4
    * Haven't tried from master

**EDIT: changed `from foo import bar` to just `import bar`

**Comment by gvanrossum** [comment] 2019-04-24 18:51
To begin, you shouldn't be passing `MYPYPATH=foo/` -- this adds the insides of the package to the toplevel search path, and that is asking for trouble. (Though it should not crash.)

**Comment by brandon-leapyear** [comment] 2019-04-24 18:56
I see... the docs aren't very clear. What should I be doing instead?

**Comment by gvanrossum** [comment] 2019-04-24 19:09
Just ‘mypy foo/foo.py’ should do it.

**Comment by brandon-leapyear** [comment] 2019-04-24 19:17
```
$ ~/miniconda3/bin/mypy foo/foo.py 
foo/foo.py:1: error: Cannot find module named 'bar'
foo/foo.py:1: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
```

**Comment by gvanrossum** [comment] 2019-04-24 20:15
That's odd; I cannot repro that. I just get the expected error (`Too few arguments for "foo"`). Do you have a `mypy.ini` somewhere? What does `mypy -v` say?

**Comment by brandon-leapyear** [comment] 2019-04-24 20:20
No `mypy.ini` anywhere.
```
$ ~/miniconda3/bin/mypy -v
usage: mypy [-h] [-v] [-V] [more options; see below]
            [-m MODULE] [-p PACKAGE] [-c PROGRAM_TEXT] [files ...]
mypy: error: Missing target module, package, files, or command.
```
```
$ ~/miniconda3/bin/mypy --version
mypy 0.701
```

**Comment by gvanrossum** [comment] 2019-04-24 20:26
I meant `mypy -v foo/foo.py`.

(For mypy team members: the crash is real though.  With the above setup, `MYPYPATH=foo/ mypy foo/foo.py` does crash.)

**Comment by brandon-leapyear** [comment] 2019-04-24 20:28
```
$ ~/miniconda3/bin/mypy -v foo/foo.py 

LOG:  Mypy version 0.701
LOG:  Could not load cache for foo.foo: foo/foo.meta.json
LOG:  Metadata not found for foo.foo
LOG:  Parsing foo/foo.py (foo.foo)
LOG:  Metadata fresh for foo: file ./foo/__init__.py
LOG:  Metadata fresh for builtins: file /Users/brandonchinn/miniconda3/lib/python3.6/site-packages/mypy/typeshed/stdlib/2and3/builtins.pyi
LOG:  Metadata fresh for typing: file /Users/brandonchinn/miniconda3/lib/python3.6/site-packages/mypy/typeshed/stdlib/3/typing.pyi
LOG:  Metadata fresh for abc: file /Users/brandonchinn/miniconda3/lib/python3.6/site-packages/mypy/typeshed/stdlib/3/abc.pyi
LOG:  Metadata fresh for ast: file /Users/brandonchinn/miniconda3/lib/python3.6/site-packages/mypy/typeshed/stdlib/3/ast.pyi
LOG:  Metadata fresh for types: file /Users/brandonchinn/miniconda3/lib/python3.6/site-packages/mypy/typeshed/stdlib/3/types.pyi
LOG:  Metadata fresh for sys: file /Users/brandonchinn/miniconda3/lib/python3.6/site-packages/mypy/typeshed/stdlib/3/sys.pyi
LOG:  Metadata fresh for collections: file /Users/brandonchinn/miniconda3/lib/python3.6/site-packages/mypy/typeshed/stdlib/3/collections/__init__.pyi
LOG:  Metadata fresh for _ast: file /Users/brandonchinn/miniconda3/lib/python3.6/site-packages/mypy/typeshed/stdlib/3/_ast.pyi
LOG:  Metadata fresh for _importlib_modulespec: file /Users/brandonchinn/miniconda3/lib/python3.6/site-packages/mypy/typeshed/stdlib/3/_importlib_modulespec.pyi
LOG:  Metadata fresh for importlib.abc: file /Users/brandonchinn/miniconda3/lib/python3.6/site-packages/mypy/typeshed/stdlib/3/importlib/abc.pyi
LOG:  Metadata fresh for collections.abc: file /Users/brandonchinn/miniconda3/lib/python3.6/site-packages/mypy/typeshed/stdlib/3/collections/abc.pyi
LOG:  Metadata fresh for importlib: file /Users/brandonchinn/miniconda3/lib/python3.6/site-packages/mypy/typeshed/stdlib/3/importlib/__init__.pyi
LOG:  Metadata fresh for os: file /Users/brandonchinn/miniconda3/lib/python3.6/site-packages/mypy/typeshed/stdlib/3/os/__init__.pyi
LOG:  Metadata fresh for io: file /Users/brandonchinn/miniconda3/lib/python3.6/site-packages/mypy/typeshed/stdlib/3/io.pyi
LOG:  Metadata fresh for os.path: file /Users/brandonchinn/miniconda3/lib/python3.6/site-packages/mypy/typeshed/stdlib/3/os/path.pyi
LOG:  Metadata fresh for posix: file /Users/brandonchinn/miniconda3/lib/python3.6/site-packages/mypy/typeshed/stdlib/3/posix.pyi
LOG:  Metadata fresh for codecs: file /Users/brandonchinn/miniconda3/lib/python3.6/site-packages/mypy/typeshed/stdlib/2and3/codecs.pyi
LOG:  Metadata fresh for mmap: file /Users/brandonchinn/miniconda3/lib/python3.6/site-packages/mypy/typeshed/stdlib/2and3/mmap.pyi
LOG:  Loaded graph with 20 nodes (0.042 sec)
LOG:  Found 3 SCCs; largest has 18 nodes
LOG:  Processing 2 queued fresh SCCs
LOG:  Processing SCC singleton (foo.foo) as inherently stale
foo/foo.py:1: error: Cannot find module named 'bar'
foo/foo.py:1: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
LOG:  Deleting foo.foo foo/foo.py foo/foo.meta.json foo/foo.data.json
LOG:  No fresh SCCs left in queue
LOG:  Build finished in 0.153 seconds with 20 modules, and 2 errors
LOG:  Stats:
LOG:  cache_commit_time:      9.5367431640625e-07
LOG:  data_json_load_time:    0.03351759910583496
LOG:  data_read_time:         0.014200687408447266
LOG:  deserialize_time:       0.02768397331237793
LOG:  files_parsed:           1
LOG:  find_module_calls:      20
LOG:  find_module_time:       0.010039091110229492
LOG:  fm_cache_size:          20
LOG:  fresh_metas:            19
LOG:  fresh_trees:            19
LOG:  graph_load_time:        0.04248404502868652
LOG:  graph_size:             20
LOG:  load_meta_time:         0.00938558578491211
LOG:  load_tree_time:         0.075653076171875
LOG:  modules_parsed:         1
LOG:  nodes_left:             0
LOG:  parse_time:             0.003947019577026367
LOG:  process_fresh_time:     0.09465789794921875
LOG:  sccs_left:              0
LOG:  stubs_found:            18
LOG:  stubs_parsed:           0
LOG:  validate_meta_time:     0.0019979476928710938
LOG:  validate_stat_time:     0.0013332366943359375
```

**Comment by gvanrossum** [comment] 2019-04-24 20:41
So, @brandon-leapyear, this is a legitimate bug in mypy, but it's low priority because it only occurs when you do something nonsensical like passing a package to MYPYPATH. Hopefully this is enough for you to work around it.

Mypy team: apparently it parses foo/foo.py *twice*, and the second time around, the same error message causes the assert to trigger. A simpler repro doesn't need `foo/bar.py` -- it's enough to have a `foo/foo.py` with an error (e.g. `1 + 'a'`), an empty `foo/__init__.py`, and `MYPYPATH=foo`. I haven't traced it further though.

**Comment by brandon-leapyear** [comment] 2019-04-24 20:45
Yeah, I can work around it in the sense that I can fix the mypy error, and the `INTERNAL ERROR` goes away. But how *should*  I be calling mypy? You're saying I'm not supposed to use `MYPYPATH`, but without `MYPYPATH`, i get `cannot find module named 'bar'`.

**Comment by gvanrossum** [comment] 2019-04-24 20:50
So that's a separate issue. When I try to reproduce your test case, mypy *does* find the module `bar` without `MYPYPATH=foo`. What's in `foo/__init__.py`?

Do you still have the same problem if you rename `foo.py` to `baz.py`?

**Comment by brandon-leapyear** [comment] 2019-04-24 20:53
`foo/__init__.py` is empty.
```
$ tree foo
foo
├── __init__.py
├── bar.py
└── baz.py

0 directories, 3 files

$ ~/miniconda3/bin/mypy foo/
foo/baz.py:1: error: Cannot find module named 'bar'
foo/baz.py:1: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
```

**Comment by gvanrossum** [comment] 2019-04-24 20:54
Hm. Is there a __init__.py in the current directory?

**Comment by brandon-leapyear** [comment] 2019-04-24 21:00
Not in the current directory.

**Comment by gvanrossum** [comment] 2019-04-24 21:11
Then I'm stumped. Since I cannot repro this behavior I cannot debug it further. :-(

**Comment by gvanrossum** [comment] 2019-04-24 21:12
(Have you tried `rm -r .mypy_cache`?)

**Comment by brandon-leapyear** [comment] 2019-04-24 21:22
```
$ rm -rf .mypy_cache/
$ ~/miniconda3/bin/mypy foo/
foo/baz.py:1: error: Cannot find module named 'bar'
foo/baz.py:1: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
```

this works:
```
$ cd foo/ && ~/miniconda3/bin/mypy baz.py
baz.py:4: error: Too few arguments for "foo"
```

Here is a complete reproduction in Docker:
```bash
# docker run --rm -it centos:7 /bin/bash

yum install -y epel-release
yum install -y python36
curl -O https://bootstrap.pypa.io/get-pip.py
python3 get-pip.py
pip install mypy
cd ~
mkdir foo
touch foo/__init__.py
cat > foo/bar.py <<EOF
def foo(x:int, y:int):
    print(x,y)
EOF
cat > foo/baz.py <<EOF
import bar
def foo(x:int):
    bar.foo(x)
EOF
mypy foo/baz.py # fails
(cd foo && mypy baz.py) # works
```

**Comment by gvanrossum** [comment] 2019-04-24 21:28
Wait, your initial post said that in foo/foo.py you had `from foo import bar`. But here you have `import bar`. That's not the same (Python 3 does not support such relative imports). With your version of course it fails.

**Comment by brandon-leapyear** [comment] 2019-04-24 21:35
Sorry, I had corrected it locally, but not in the comment. All of my outputs have been with `import bar`

**Comment by gvanrossum** [comment] 2019-04-24 21:42
Yeah, so after correcting that you shouldn't need to set MYPYPATH any more.

**Comment by brandon-leapyear** [comment] 2019-04-24 21:47
hm I'm not sure I understand what you're saying. Here's a minimal example that's closer to my actual work:
```
foo
├── __init__.py
├── bar
    ├── __init__.py
└── baz
    ├── __init__.py
```
```python
# foo/bar/__init__.py
def build(x:int, path:str):
    pass
```
```python
# foo/baz/__init__.py
from foo import bar
def build(x:int, path:str):
    bar.build(x)
```

**Comment by gvanrossum** [comment] 2019-04-24 21:54
I'm sorry, I've already wasted over an hour on this issue. Maybe you can get help on our gitter channel.

**Comment by ilevkivskyi** [comment] 2019-04-25 16:08
This is essentially a duplicate of https://github.com/python/mypy/issues/4881 (because the file appears _twice_ in the source list, once normally, and once from MYPYPATH).

**Closed by ilevkivskyi** 2019-04-25 16:08 UTC
Labels: crash, priority-2-low
