### ISSUE TITLE
Mypy tries to instantiate an abstract class

### ISSUE THREAD

**Issue by tal-zvon** [python/mypy#12624] opened 2022-04-19 12:57 UTC
mypy version `0.942`

With `test.py` like this:

```python
from abc import ABC, abstractmethod

class AbstractClass(ABC):
    @abstractmethod
    def method(self):
        pass

class ConcreteClass1(AbstractClass):
    def method(self):
        print("hello")

class ConcreteClass2(AbstractClass):
    def method(self):
        print("hello")

class ConcreteClass3(AbstractClass):
    def method(self):
        print("hello")

classes = [
    ConcreteClass1,
    ConcreteClass2,
    ConcreteClass3,
]

for c in classes:
    c().method()
```

Mypy shows:

`test.py:27: error: Cannot instantiate abstract class "AbstractClass" with abstract attribute "method"`

Some weird behavior I've noticed:

If, instead of a loop, I do this:

```python
...
ConcreteClass1().method()
ConcreteClass2().method()
ConcreteClass3().method()
```

mypy is happy.

Also, if, instead of 3 classes in the loop, I do 2:

```python
classes = [
    ConcreteClass1,
    ConcreteClass2,
    #ConcreteClass3,
]

for c in classes:
    c().method()

```

mypy is happy with that as well.
I posted this on [stackoverflow](https://stackoverflow.com/questions/71918897/why-is-mypy-trying-to-instantiate-my-abstract-class-in-python), and this seems to be a bug.

This can be worked around by explicitly defining the type of list:

```python
classes: List[Type[AbstractClass]] = [
    ConcreteClass1,
    ConcreteClass2,
    ConcreteClass3,
]
```

**Comment by AlexWaygood** [comment] 2022-04-19 13:28
Duplicate of #3115

**Closed by AlexWaygood** 2022-04-19 13:28 UTC
Labels: bug, topic-join-v-union
