### ISSUE TITLE
Improve type inference for "Optional[T] or T" expression

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#1817] opened 2016-07-07 18:13 UTC
Consider this:
```python
def f(a: Optional[str]) -> str:
    return a or 'default'
```
This should type-check under `--strict-optional`, but currently the type of `a or 'default'` is inferred as `Optional[str]`. It should realize that if a is `None` the right branch is always taken.

**Comment by JukkaL** [comment] 2016-07-07 18:34
Dupe of #1733?

**Closed** 2016-07-08 00:32 UTC
Labels: Strict Optional
