### ISSUE TITLE
overriding attribute with property

### ISSUE THREAD

**Issue by Akuli** [python/mypy#10049] opened 2021-02-08 12:57 UTC
**Bug Report**

**To Reproduce**

```
class Foo:
    blah: int = 123

class Bar(Foo):
    @property               # error: Signature of "blah" incompatible with supertype "Foo"
    def blah(self) -> int:  # error: Signature of "blah" incompatible with supertype "Foo"
        return 123

    @blah.setter
    def blah(self, value: int) -> None:
        pass
```

**Expected Behavior**

I would expect mypy to allow this, even though this is a bit of a hack, or if this is intentional, get an error message saying that this is a bad idea.

**Actual Behavior**

The errors written as comments

**Your Environment**

- Mypy version used: happens with mypy 0.790 and 0.820+dev.2738c73695e2d2f963fbe2a0056329c43a0f6e58
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: 3.7.3
- Operating system and version: debian 10 based linux distro with kernel 4.19.0-14-amd64

**Comment by troiganto** [comment] 2021-08-12 13:49
This is very likely a duplicate of #4125

**Closed** 2021-08-12 15:34 UTC
Labels: bug
