### ISSUE TITLE
Feature request: support common metaclass usage

### ISSUE THREAD

**Issue by Diggsey** [python/mypy#1868] opened 2016-07-14 23:05 UTC
It's common to use meta classes as a way to define models, eg:
```python
class Model(Base):
    my_column = Column(SomeType, ...)
```

This sort of pattern occurs in many places including ORMs and serialisation libraries, basically anything where a schema of some kind is needed.
What they all share is that the RHS of assignments in the class definition describe the *type* of those attributes on instances of the class, rather than the *value* of those attributes.

I think it would be worthwhile special-casing this usage: allow annotating a meta class with a type signature which tells mypy how to handle members. For the example above:
```python
class BaseMeta(type):
    # field-generator: (Column[T]) -> T
    ...
```

This would give mypy the information it needs to determine the correct type of `my_column`.

**Comment by gvanrossum** [comment] 2016-07-15 00:09
I've always assumed this would be a job for plugins.

--Guido (mobile)

**Comment by Diggsey** [comment] 2016-07-15 09:44
That seems reasonable, but there doesn't seem to be any documentation or examples about how to write plugins for mypy. I think I've read most of the documentation and until you mentioned it was unaware that mypy even supported plugins?

**Comment by JukkaL** [comment] 2016-07-15 12:42
There's no way to write mypy plugins yet. We don't even have a concrete plan. See #1240 for some discussion.

**Comment by gvanrossum** [comment] 2016-07-21 21:38
Let's close this as a dupe of the plugins issue (#1240).

**Closed by gvanrossum** 2016-07-21 21:38 UTC
