### ISSUE TITLE
mypy crashes when it encounters a match statement and TypeVar with constraints

### ISSUE THREAD

**Issue by taasan** [python/mypy#12914] opened 2022-05-31 07:12 UTC
**Crash Report**

mypy crashed

**Traceback**

```
bug.py:5: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.970+dev.0628e09ede4c81b913e859c750c581fbb85fa481
bug.py:5: : note: use --pdb to drop into pdb
Traceback (most recent call last):
  File "/mypy-bug/venv/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/mypy-bug/venv/lib/python3.10/site-packages/mypy/__main__.py", line 12, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "/mypy-bug/venv/lib/python3.10/site-packages/mypy/main.py", line 96, in main
    res, messages, blockers = run_build(sources, options, fscache, t0, stdout, stderr)
  File "/mypy-bug/venv/lib/python3.10/site-packages/mypy/main.py", line 173, in run_build
    res = build.build(sources, options, None, flush_errors, fscache, stdout, stderr)
  File "/mypy-bug/venv/lib/python3.10/site-packages/mypy/build.py", line 154, in build
    result = _build(
  File "/mypy-bug/venv/lib/python3.10/site-packages/mypy/build.py", line 230, in _build
    graph = dispatch(sources, manager, stdout)
  File "/mypy-bug/venv/lib/python3.10/site-packages/mypy/build.py", line 2729, in dispatch
    process_graph(graph, manager)
  File "/mypy-bug/venv/lib/python3.10/site-packages/mypy/build.py", line 3087, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/mypy-bug/venv/lib/python3.10/site-packages/mypy/build.py", line 3185, in process_stale_scc
    graph[id].type_check_first_pass()
  File "/mypy-bug/venv/lib/python3.10/site-packages/mypy/build.py", line 2180, in type_check_first_pass
    self.type_checker().check_first_pass()
  File "/mypy-bug/venv/lib/python3.10/site-packages/mypy/checker.py", line 325, in check_first_pass
    self.accept(d)
  File "/mypy-bug/venv/lib/python3.10/site-packages/mypy/checker.py", line 431, in accept
    stmt.accept(self)
  File "/mypy-bug/venv/lib/python3.10/site-packages/mypy/nodes.py", line 748, in accept
    return visitor.visit_func_def(self)
  File "/mypy-bug/venv/lib/python3.10/site-packages/mypy/checker.py", line 782, in visit_func_def
    self._visit_func_def(defn)
  File "/mypy-bug/venv/lib/python3.10/site-packages/mypy/checker.py", line 786, in _visit_func_def
    self.check_func_item(defn, name=defn.name)
  File "/mypy-bug/venv/lib/python3.10/site-packages/mypy/checker.py", line 848, in check_func_item
    self.check_func_def(defn, typ, name)
  File "/mypy-bug/venv/lib/python3.10/site-packages/mypy/checker.py", line 868, in check_func_def
    expanded = self.expand_typevars(defn, typ)
  File "/mypy-bug/venv/lib/python3.10/site-packages/mypy/checker.py", line 1488, in expand_typevars
    result.append((expand_func(defn, mapping), expanded))
  File "/mypy-bug/venv/lib/python3.10/site-packages/mypy/checker.py", line 6064, in expand_func
    ret = defn.accept(visitor)
  File "/mypy-bug/venv/lib/python3.10/site-packages/mypy/nodes.py", line 748, in accept
    return visitor.visit_func_def(self)
  File "/mypy-bug/venv/lib/python3.10/site-packages/mypy/treetransform.py", line 115, in visit_func_def
    self.block(node.body),
  File "/mypy-bug/venv/lib/python3.10/site-packages/mypy/treetransform.py", line 580, in block
    new = self.visit_block(block)
  File "/mypy-bug/venv/lib/python3.10/site-packages/mypy/treetransform.py", line 194, in visit_block
    return Block(self.statements(node.body))
  File "/mypy-bug/venv/lib/python3.10/site-packages/mypy/treetransform.py", line 591, in statements
    return [self.stmt(stmt) for stmt in statements]
  File "/mypy-bug/venv/lib/python3.10/site-packages/mypy/treetransform.py", line 591, in <listcomp>
    return [self.stmt(stmt) for stmt in statements]
  File "/mypy-bug/venv/lib/python3.10/site-packages/mypy/treetransform.py", line 565, in stmt
    assert isinstance(new, Statement)
AssertionError: 
```

**To Reproduce**

`mypy bug.py`

***Contents of bug.py***

```python
from typing import List, TypeVar

T = TypeVar("T", int, str)  # Doesn't crash when T = TypeVar("T")

def get_value(xs: List[T]) -> None:
    x = 12
    match x:
        case _:
            pass
```

**Your Environment**

- Mypy version used: 0.942, 0.950, 0.960, 0.970+dev.0628e09ede4c81b913e859c750c581fbb85fa481
- Mypy command-line flags: No flags
- Mypy configuration options from `mypy.ini` (and other config files): No configuration
- Python version used: 3.10.4
- Operating system and version: Fedora 36

**Comment by AlexWaygood** [comment] 2022-05-31 07:18
Thanks for the report! This is a duplicate of #12448. It's a _slightly_ different reproducer, though, so I'll add a comment to that issue.

**Closed by AlexWaygood** 2022-05-31 07:18 UTC
Labels: crash, topic-match-statement
