### ISSUE TITLE
Internal Error when running with --follow-imports=normal

### ISSUE THREAD

**Issue by hima1701** [python/mypy#16188] opened 2023-09-27 15:00 UTC
I was trying to run mypy on quite few number of files which imports other modules (quite a big repo), but this happens only when I use --follow-imports="normal" / "silent". 

**Crash Report**
/Users/hima/Documents/Deliverect/Backend/venv/lib/python3.11/site-packages/pydantic/env_settings.py:22: error: INTERNAL ERROR

**Traceback**
Below is the traceback : 

```
/Users/hima/Documents/Deliverect/Backend/venv/lib/python3.11/site-packages/pydantic/env_settings.py:22: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 1.5.1
Traceback (most recent call last):
  File "mypy/semanal.py", line 6475, in accept
  File "mypy/nodes.py", line 1141, in accept
  File "mypy/semanal.py", line 1600, in visit_class_def
  File "mypy/semanal.py", line 1685, in analyze_class
  File "mypy/semanal.py", line 1714, in analyze_class_body_common
  File "mypy/semanal.py", line 1801, in apply_class_plugin_hooks
  File "pydantic/mypy.py", line 140, in pydantic.mypy.PydanticPlugin._pydantic_model_class_maker_callback
  File "pydantic/mypy.py", line 284, in pydantic.mypy.PydanticModelTransformer.transform
  File "pydantic/mypy.py", line 463, in pydantic.mypy.PydanticModelTransformer.add_construct_method
TypeError: __init__() missing required argument 'default' (pos 6)
/Users/hima/Documents/Deliverect/Backend/venv/lib/python3.11/site-packages/pydantic/env_settings.py:22: : note: use --pdb to drop into pdb
mypy --show-traceback  9.35s user 1.08s system 92% cpu 11.299 total
```

**To Reproduce**
Run mypy against a set of files which imports few other modules.

**Your Environment**
local

- Mypy version used: 1.51 and 1.4.0
- Mypy command-line flags: mypy against the repo or a set of files
- Mypy configuration options from `mypy.ini` (and other config files): --follow-imports=normal
- Python version used: 3.11
- Operating system and version: MacOS and 13.6

**Comment by AlexWaygood** [comment] 2023-09-27 15:06
Duplicate of #15485. This is an issue with pydantic's mypy plugin that has already been fixed. You'll need to upgrade your pydantic version.

**Closed by AlexWaygood** 2023-09-27 15:06 UTC
Labels: crash

**Comment by hima1701** [comment] 2023-09-27 16:46
Indeed fixed when pydantic has been updated to latest version
