### ISSUE TITLE
False negative with accessing super types private member from sub type

### ISSUE THREAD

**Issue by KotlinIsland** [python/mypy#9446] opened 2020-09-16 03:12 UTC
Following code shows no errors from mypy but will fail at runtime.
```py
class A:
    def __a(self) -> None:
        ...


class B(A):
    def foo(self) -> None:
        self.__a()


B().foo()
```

**Comment by gvanrossum** [comment] 2020-09-16 04:00
Thanks for the report -- this looks like a real bug. Fixing it would probably be fairly involved (we'd have to implement name mangling at the right level in the parser) and private members aren't that popular. So I'm classifying this as low priority.

**Comment by AlexWaygood** [comment] 2022-04-03 02:09
Closing as a duplicate of #8267

**Closed by AlexWaygood** 2022-04-03 02:09 UTC
Labels: bug, priority-2-low, topic-runtime-semantics
