### ISSUE TITLE
false positive if module object is assigned to variable: `error: Module has no attribute`

### ISSUE THREAD

**Issue by carljm** [python/mypy#3414] opened 2017-05-23 01:10 UTC
Simple example:

```
import subprocess
s2 = subprocess
x = s2.Popen
```

This runs fine, but mypy gives `error: Module has no attribute "Popen"`

(The real-world use case in which we encountered this involves a conditional import for cross-version compatibility.)

**Comment by ilevkivskyi** [comment] 2017-05-23 08:53
Thanks for reporting! It looks like this is a duplicate of https://github.com/python/mypy/issues/1778
(feel free to reopen if you think this is a different issue).

**Closed by ilevkivskyi** 2017-05-23 08:53 UTC

**Comment by carljm** [comment] 2017-05-23 16:51
Thanks! Searched but didn't find that. Looks the same.
