### ISSUE TITLE
no __dict__ under Python 2

### ISSUE THREAD

**Issue by gaborbernat** [python/mypy#3811] opened 2017-08-08 17:35 UTC
```python
class A(object):

	def __repr__(self):
		# type: () -> str
		return 'A({})'.format(self.__dict__)
```

```bash
bernat@vm ~/git/test-mypy $ mypy . -V
mypy 0.521
bernat@vm ~/git/test-mypy $ mypy .
bernat@vm ~/git/test-mypy $ mypy .  --py2
test.py:5: error: "A" has no attribute "__dict__"
```

**Comment by ethanhs** [comment] 2017-08-08 18:13
This is a typeshed issue, object needs dunder dict added, I believe.

**Comment by ilevkivskyi** [comment] 2017-08-08 19:52
Indeed, ``object`` has ``__dict__`` in Python 3 but not in Python 2. I have no idea why, but probably just an omission.

@gaborbernat would you like to make a PR to typeshed?

**Comment by gvanrossum** [comment] 2017-08-09 01:30
Technically, object doesn't have a __dict__ attribute, only most classes
derived from it do (unless they use__slots__).

**Comment by ethanhs** [comment] 2017-08-09 03:40
It doesn't?

In my Python 2.7.13 interpreter I can do this:
```python
>>>getattr(object, '__dict__')
... (dictproxy stuff)...
>>>object.__dict__
... (same dictproxy) ...
>>>class A:
...     pass
>>>A.__dict__
{'__module__': '__main__', '__doc__': None}
```
so even classes _without_ inheriting from object seem to have `__dict__`. 

I took a look in object.c, object.h and objimpl.h, and it seems the internal PyObject does not have `__dict__`, but since the dict object does seem to have it (see above) I don't see this being an issue. Unless this would be an issue if you had a C extension.

**Comment by gvanrossum** [comment] 2017-08-09 05:07
You're seeing the *class* `__dict__`. Every class has a dict. I was talking about the *instance* `__dict__`. Instances of `object` don't have one:
```
>>> object().__dict__
object().__dict__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'object' object has no attribute '__dict__'
>>> 
```
That's identical in both Python 2 and Python 3.

AFAICT the OP is talking about the instance dict.

**Comment by gaborbernat** [comment] 2017-08-09 08:25
so yes, my issue talks about the instance dict, is there a way to quantify statically if derived classes from object have it? e.g. in the example I posted in the first post.

**Comment by ethanhs** [comment] 2017-08-09 08:41
Aha, okay that makes much more sense. Thank you for the clear explanation! In that case, I suppose mypy would have to handle this separately?

**Comment by JukkaL** [comment] 2017-08-09 09:48
More generally, instances of primitive types and other types implemented in C don't seem to have a `__dict__`. Mypy currently has no reliable way of knowing whether a particular type defines `__dict__` since we don't know which classes are C types. However, something like this would probably be safe (but incomplete):

> Include a `__dict__` instance attribute if some class in the MRO is defined outside a stub *and* doesn't define `__slots__`.

Anything within a stub could plausibly be a C extension type, so we'd conservatively assume so.

**Comment by JukkaL** [comment] 2017-08-09 09:49
Also, typeshed perhaps shouldn't include `__dict__` in Python 3 `object` either.

**Comment by ilevkivskyi** [comment] 2017-08-09 15:31
TBH, I think this is a bit too complicated. We should ensure that the logic is correct if ``__slots__`` are defined after other methods. Plus ``__dict__`` is not the only attribute that is different between C and Python classes, another example is ``__weakref__``. I would say that it makes sense to have a more complete solution, that would correctly treat ``__slots__`` (if they are string literals), and detect ``__dict__``, ``__weakref__`` etc.

Also I am not sure if we need to keep this open, since we already have https://github.com/python/mypy/issues/1325

**Comment by JukkaL** [comment] 2017-08-09 17:37
Yeah, closing this as a duplicate of #1325.

**Closed by JukkaL** 2017-08-09 17:37 UTC
Labels: feature
