### ISSUE TITLE
map(set, iterable) not inferring correct type

### ISSUE THREAD

**Issue by jonashaag** [python/mypy#13084] opened 2022-07-07 11:49 UTC
**Bug Report**

```py
from typing import cast, TypeVar, List, Dict

T = TypeVar("T")
U = TypeVar("U")

def test(a: U, b: T):
    # a, b are only to bind T, U

    d = cast(List[Dict[U, T]], None)

    # This does not work:
    # Argument 1 to "map" has incompatible type "Type[Set[Any]]"; expected "Callable[[Dict[U, T]], Set[_T]]"
    set.union(*map(set, d))

    # But this does:
    set.union(*map(lambda x: set(x), d))

test(1, 2)
```

**To Reproduce**

Run MyPy on the code above.

**Expected Behavior**

Both versions type check correctly.

**Actual Behavior**

Only one of them works.

**Your Environment**

Python 3.8, mypy 0.961 (compiled: yes)

**Comment by AlexWaygood** [comment] 2022-07-07 17:17
Duplicate of #11682

**Closed by AlexWaygood** 2022-07-07 17:17 UTC
Labels: bug
