### ISSUE TITLE
Invalid type inference in a conditional context manager with `contextlib.nullcontext()`.

### ISSUE THREAD

**Issue by francis-clairicia** [python/mypy#16264] opened 2023-10-14 07:48 UTC
**Bug Report**

When a ternary is used in a `with` or an `async with` statement to determine the final context manager, mypy cannot infer the expression type.

**To Reproduce**

https://mypy-play.net/?mypy=latest&python=3.11&gist=a2db21d63361bc0f1f334ff337509fca

**Expected Behavior**

The expression should lead to `TaskGroup` type.

**Actual Behavior**

The expression lead to `object` type.

**Your Environment**

- Mypy version used: 1.6.0

**Comment by AlexWaygood** [comment] 2023-10-14 08:48
Duplicate of #10109 and #5512

**Closed by AlexWaygood** 2023-10-14 08:48 UTC
Labels: bug, topic-join-v-union
