### ISSUE TITLE
How can I make this `# type: ignore` platform specific?

### ISSUE THREAD

**Issue by evandrocoan** [python/mypy#8547] opened 2020-03-16 15:55 UTC
The project I use, runs both on Windows and Linux. The code is all platform specific, but `mypy` keeps ignoring it:
```python
File: anki/pylib/anki/utils.py
286: def call(argv: List[str], wait: bool = True, **kwargs) -> int:
287:     "Execute a command. If WAIT, return exit code."
288:     # ensure we don't open a separate window for forking process on windows
289:     if isWin:
290:         si = subprocess.STARTUPINFO()
291:         try:
292:             si.dwFlags |= subprocess.STARTF_USESHOWWINDOW
```
1. If I add `# type: ignore` to lines `290` and `292` then, `mypy` works on Linux, but it fails on Windows with `error: unused 'type: ignore' comment`
1. If I remove the `# type: ignore` from the lines `290` and `292` then, `mypy` works on Windows, but it fails on Linux with `error: Module has no attribute "STARTUPINFO"  [attr-defined]`.

The `STARTUPINFO` is not defined for Linux Implementations, but is is for Windows implementation. That is why both of them are both protected by a `if isWin` or `if _mswindows` on this project and on the `subprocess` module implementation:
```python 
File: F:/Python/lib/subprocess.py
164: if _mswindows:
165:     class STARTUPINFO:
```

How can I make this `# type: ignore` platform specific?
```
(pyenv) F:\anki>mypy --version
mypy 0.761
```

**Comment by JelleZijlstra** [comment] 2020-03-19 00:59
If you use a mypy-recognized platform check like `if sys.platform == 'win32'`, mypy should behave as expected.

**Comment by evandrocoan** [comment] 2020-03-19 01:25
The `isWin` Anki uses on the if is this:
```
File: anki/pylib/anki/utils.py
323: isWin = sys.platform.startswith("win32")
```

The only way to `mypy` to work is replacing the `if isWin` by `if sys.platform == 'win32'`? This should be improved.

**Comment by JukkaL** [comment] 2020-03-20 17:10
Mypy supports what specified in PEP 484 (https://www.python.org/dev/peps/pep-0484/#version-and-platform-checking). We could perhaps extend this to cover more cases, but it's hard to decide where we should draw the line, since the platform checks could be arbitrarily creative.

**Comment by ErikBjare** [comment] 2020-07-25 12:08
@JukkaL I'm having problems with a simple case like:

```py
if platform.system() == "Darwin":
    something_platform_specific()  # type: ignore
```

There are plenty of valid cases where you might want to do this, especially for Windows where `sys.platform` can be one of `["win32", "cygwin"]`.

**Comment by JelleZijlstra** [comment] 2020-07-26 05:16
There is an open PR #8461 to add support for `platform.system()`, but it looks like it has stalled.

**Comment by hauntsaninja** [comment] 2020-08-07 02:50
Closing this as a dupe of other issues, basically this entire comment https://github.com/python/mypy/issues/9242#issuecomment-667586397 applies to this issue

**Closed by hauntsaninja** 2020-08-07 02:50 UTC
