### ISSUE TITLE
Mypy shows the error for operators provided via functools.total_ordering decorator

### ISSUE THREAD

**Issue by konradhalas** [python/mypy#4624] opened 2018-02-23 12:02 UTC
Mypy shows the error of an unsupported comparison operator for classes with `@functools.total_ordering` decorator and with implemented `==` and `<`.

Example:

```python
import decimal
import functools
import typing


@functools.total_ordering
class Money:

    def __init__(self, amount: str) -> None:
        self.amount = decimal.Decimal(amount)

    def __eq__(self, other: typing.Any) -> bool:
        if isinstance(other, Money):
            return self.amount == other.amount
        return NotImplemented

    def __lt__(self, other: typing.Any) -> bool:
        if isinstance(other, Money):
            return self.amount < other.amount
        return NotImplemented


assert Money('10.00') <= Money('10.00')
```

Mypy output (`--strict` flag is enabled):

```text
money.py:23: error: Unsupported left operand type for <= ("Money")
```

My configuration:

- Python 3.6.4
- mypy 0.570-dev-3545a71ba11576b08007f70d8407bf7924738886

If it's `typeshed` related issue, please close it and I will post it there.

**Comment by ilevkivskyi** [comment] 2018-02-23 12:04
Duplicate of https://github.com/python/mypy/issues/4610

**Closed by ilevkivskyi** 2018-02-23 12:04 UTC
