### ISSUE TITLE
Should not throw "Value of type "Optional[Match[str]]" is not indexable" error when using Assignment expressions

### ISSUE THREAD

**Issue by dongweiming** [python/mypy#8254] opened 2020-01-07 09:09 UTC
I ’m not sure if it ’s mypy or[ typeshed](https://github.com/python/typeshed/) issue. 

I found [an issue about this](https://github.com/python/typeshed/issues/3010), here is a short example using `Assignment expressions`, it will throw an error:

```python
❯ cat a.py 
import re

if (m := re.search(".", "foo")):
    print(m[0])

❯ mypy a.py 
a.py:4: error: Value of type "Optional[Match[str]]" is not indexable
        print(m[0])
              ^
Found 1 error in 1 file (checked 1 source file)
```

**Comment by TH3CHARLie** [comment] 2020-01-07 11:03
It is a mypy issue, related #7316

**Comment by JelleZijlstra** [comment] 2020-01-07 15:47
Yes, this is a duplicate of #7316.

**Closed by JelleZijlstra** 2020-01-07 15:47 UTC
