### ISSUE TITLE
Unpacking tuples of variable length

### ISSUE THREAD

**Issue by mihneagiurgea** [python/mypy#1178] opened 2016-01-28 00:09 UTC
Given the following code:

```
from typing import Any, Dict, Tuple, Union

VarTuple = Union[Tuple[int, int], Tuple[int, int, int]]

def make_tuple():
    # type: () -> VarTuple
    return None

x = make_tuple()
a = b = c = 0
if len(x) == 3:
    a, b, c = x
else:
    a, b = x
    c = 0
```

mypy complains about the following error:

```
sandbox.py:12: error: 'Union[Tuple[builtins.int, builtins.int], Tuple[builtins.int, builtins.int, builtins.int]]' object is not iterable
sandbox.py:14: error: 'Union[Tuple[builtins.int, builtins.int], Tuple[builtins.int, builtins.int, builtins.int]]' object is not iterable
```

**Comment by JukkaL** [comment] 2016-01-28 13:28
The error message is incorrect. However, mypy may not be able to type check this properly since it doesn't recognize the `len(x) == 3` check. So there seem to be two related issues:

* Union types aren't recognized as iterables when type checking assignment statements.
* `len(x) == n` checks can't be used to narrow down tuple types or unions. These could work similarly to `isinstance` checks.

The recommended way to work around the issue is to use casts:

```
if len(x) == 3:
    a, b, c = cast(Tuple[int, int, int], x)
else:
    a, b = cast(Tuple[int, int], x)
    c = 0
```

**Comment by JukkaL** [comment] 2016-11-30 10:16
Also, mypy could recognize `len(x)` when `x` is a variable-length tuple. Example:

```
def f(x: Tuple[int, ...]) -> None:
    assert len(x) ==3 
    # Type of x should be Tuple[int, int, int] now
    ...
```

**Comment by neiljp** [comment] 2017-08-21 01:23
I just ran into this issue and was going to post the following test case, but didn't realise that len(x) wasn't yet a way to distinguish among unions:
```
def f_4(a: Tuple[int, int, int, int]) -> None:
    pass

def f_2_4(a: Union[Tuple[int, int], Tuple[int, int, int, int]]) -> None:
    if len(a) == 2:
        aa = a + (0,0)
    else:
        aa = a
    f_4(aa)
```

**Comment by pgunn** [comment] 2019-04-04 15:37
I'm getting a different error, but I'm guessing this is the same issue:

```
#!/usr/bin/env python

from typing import Tuple, Union

####################
# test

def patient_caller():
	a,b,c = annoying_returner(calculate_more=True)
	print(f"I got {a}, {b}, {c}")

def annoying_returner(calculate_more:bool=False) -> Union[Tuple[int,int], Tuple[int,int,int]]:
	if calculate_more:
		return 1,2,3
	else:
		return 4,5

def main():
	patient_caller()

##########

main()
```

```scclin009:~/src/caiman_dev-clean$ mypy mypytest.py 
mypytest.py:9: error: Need more than 2 values to unpack (3 expected)```

(I have a mypy.init specifying check_untyped_defs)

**Comment by ilevkivskyi** [comment] 2019-04-04 16:03
@pgunn In your particular case you can use `@overload` on `Literal[True]`/`Literal[False]` for the flag.

**Comment by pgunn** [comment] 2019-04-04 16:07
@ilevkivskyi Will look into that; unfortunate that it's actually necessary, but it's great that it's possible. Thanks.

**Comment by pgunn** [comment] 2019-04-04 16:29
@ilevkivskyi I'm trying to follow the docs here:
https://mypy.readthedocs.io/en/latest/literal_types.html
And I'm getting a

`caiman/components_evaluation.py:539: error: Overloaded function signatures 1 and 2 overlap with incompatible return types`

This is also getting very verbose. Not sure if it's that these are keyword rather than positional arguments that's giving me the problem.

```
# The below tells the type-checker that if return_all is a literal True, it returns 5 values
@overload
def estimate_components_quality(traces, Y, A, C, b, f, final_frate=30, Npeaks=10, r_values_min=.95,
                                fitness_min=-100, fitness_delta_min=-100, return_all:Literal[True]=True, N=5,
                                remove_baseline=True, dview=None, robust_std=False, Athresh=0.1, thresh_C=0.3,                       num_traces_per_group=20) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.array]: ...
# and if it's a literal False, it returns two
@overload
def estimate_components_quality(traces, Y, A, C, b, f, final_frate=30, Npeaks=10, r_values_min=.95,
                                fitness_min=-100, fitness_delta_min=-100, return_all:Literal[False]=False, N=5,
                                remove_baseline=True, dview=None, robust_std=False, Athresh=0.1, thresh_C=0.3,                       num_traces_per_group=20) -> Tuple[np.ndarray, np.ndarray]: ...
# Fallback overload
def estimate_components_quality(traces, Y, A, C, b, f, final_frate=30, Npeaks=10, r_values_min=.95,
                                fitness_min=-100, fitness_delta_min=-100, return_all:bool=False, N=5,
                                remove_baseline=True, dview=None, robust_std=False, Athresh=0.1, thresh_C=0.3,                       num_traces_per_group=20) -> Union[Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.array], Tuple[np.ndarray, np.             ndarray]]: ...

def estimate_components_quality(traces, Y, A, C, b, f, final_frate=30, Npeaks=10, r_values_min=.95,
                                fitness_min=-100, fitness_delta_min=-100, return_all:bool=False, N=5,
                                remove_baseline=True, dview=None, robust_std=False, Athresh=0.1, thresh_C=0.3,                       num_traces_per_group=20) -> Union[Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.array], Tuple[np.ndarray, np.ndarray]]:
     # Function body
```

This may be wandering away from the topic of the issue though; if it's wandered too far I'm fine with not getting an answer; don't want to clutter things for devs.

**Comment by ilevkivskyi** [comment] 2019-04-04 16:38
Yes, this is because they are keyword args, see https://github.com/python/mypy/issues/6580

Anyway, in your case I would just return a less precise type like `Tuple[np.ndarray, ...]` (if this works).

**Comment by pgunn** [comment] 2019-04-04 16:47
@ilevkivskyi It does. Thanks! I have some other code not well-covered by this tack, but perhaps by the time we're ready to switch to requiring mypy to pass in CI before merges, this kind of thing will have a more graceful solution.

**Comment by goodmami** [comment] 2019-10-23 08:18
There seems to be an issue even with fixed-length tuples:

```python
# file: ex.py
from typing import Tuple
points = (1, 2)  # type: Tuple[int, int]
x, y, z = *points, 0
```

This results in incorrect inference about the tuple size:

```console
$ mypy ex.py 
ex.py:4: error: Need more than 2 values to unpack (3 expected)
Found 1 error in 1 file (checked 1 source file)
```

A workaround is to use `cast()`, as @JukkaL suggested earlier in this thread:

```python
x, y, z = cast(Tuple[int, int, int], (*points, 3))
```

**Comment by ethanhs** [comment] 2019-10-23 08:57
@goodmami could you open a new issue for that? It seems like a different (enough) problem.

**Comment by ilevkivskyi** [comment] 2020-08-03 06:56
I think this is a missing feature rather than a bug (although this does cause a false positive).

**Comment by rodo-hf** [comment] 2021-04-15 21:57
If your list to unpack is never greater than your left side and you know how many variables are on the left side, then you can do this (assuming there are 5 variables on the left side):
```python
right = [1, 2, 3]
add_to_right = (5 - len(right)) * [None]

a, b, c, d, e = right + add_to_right

print(a)
print(b)
print(c)
print(d)
print(e)

# ==> 1, 2, 3, None, None
```

**Comment by arvindsree** [comment] 2023-05-02 01:08
Please also consider IndexError while resolving this
 
```
try:
    c = x[2]
except IndexError
    c = 0
```

**Comment by fofoni** [comment] 2023-05-02 13:09
> Please also consider IndexError while resolving this
> 
> ```
> try:
>     c = x[2]
> except IndexError
>     c = 0
> ```

I believe mypy has never taken try/except "guards" into consideration for what otherwise would be typing violations. For example, this has always been forbidden:

```python
x: int = 40
try:
    x + "2"  # error: Unsupported operand types for + ("int" and "str")
             # even though we explicitly catch TypeErrors
except TypeError:
    pass
```

So that I don't see why this would ever be allowed:

```python
x: tuple[()] = ()
try:
    x[0]  # error: Tuple index out of range
          # even though we explicitly catch IndexErrors
except IndexError:
    pass
```

**Comment by arvindsree** [comment] 2023-05-04 00:28
@fofoni. That is different, in your example you pass a different type altogether. Here the typing is consistent.

**Comment by fofoni** [comment] 2023-05-05 19:22
I believe it's not that different. If `x` is declared as `x: tuple[int, str, float]`, then the number of items of `x` is part its type, and therefore accesing `x[999]` is a typing violation just as any other.

Also, length-checking tuples (which are guaranteed to be immutable by the language) is 100% thread-safe.

**Comment by arvindsree** [comment] 2023-05-05 20:45
`Also, length-checking tuples (which are guaranteed to be immutable by the language) is 100% thread-safe.`

Length checking maybe, but the whole block is not. It could be one value during the length check and a different value while indexing

**Comment by JelleZijlstra** [comment] 2023-05-05 20:47
This is getting very off-topic. Let's leave this issue focused on narrowing tuple types with `len()`.

**Comment by w238liu** [comment] 2023-08-25 20:33
Just wondering if this issue has been resolved? I still get a mypy error for the following code snippet:

```python
from typing import Tuple


def f0(n: int) -> Tuple[int, ...]:
    return tuple(range(n))


def f2() -> Tuple[int, int]:
    ret = f0(2)

    assert len(ret) == 2

    return ret


if __name__ == '__main__':
    print(f2())

```

Save the code in `tmp/mypy_test/main.py` and run `mypy tmp/mypy_test/main.py`, I get the following error message:
`tmp/mypy_test/main.py:13: error: Incompatible return value type (got "Tuple[int, ...]", expected "Tuple[int, int]")  [return-value]`

**Comment by JelleZijlstra** [comment] 2023-08-25 20:41
It's not resolved, that's why this issue is still open.

**Comment by w238liu** [comment] 2023-08-25 20:44
Thanks for quick reply. I’ll use the workaround mentioned in this thread
then.

**Closed** 2023-10-21 15:41 UTC
Labels: feature, priority-1-normal, topic-union-types, false-positive, topic-type-narrowing
