### ISSUE TITLE
Reject more covariant overrides

### ISSUE THREAD

**Issue by hauntsaninja** [python/mypy#16455] opened 2023-11-11 01:52 UTC
Follow up to #3208. We should also reject things like:
```
from typing import TypeVar, Generic
T = TypeVar("T", covariant=True)
class Foo(Generic[T]):
    def __init__(self, value: T) -> None:
        self.foo = value
```

**Comment by ilevkivskyi** [comment] 2023-11-11 19:40
Is this a duplicate of https://github.com/python/mypy/issues/735? In particular https://github.com/python/mypy/issues/735#issuecomment-1413401443

**Closed** 2023-11-12 20:48 UTC
Labels: feature
