### ISSUE TITLE
Stubtest not detecting extended `__all__`

### ISSUE THREAD

**Issue by rayzchen** [python/mypy#15448] opened 2023-06-15 19:18 UTC
**Bug Report**

I cannot extend a package `__all__` with a submodule `__all__` when using `from .mod import *`, `from .mod import __all__ as mod_all` and `__all__.extend(mod_all)`

**To Reproduce**

https://github.com/rayzchen/stubtest-bug with `python -m mypy.stubtest foo`

**Expected Behavior**

No error

**Actual Behavior**

```
error: foo.__all__ names exported from the stub do not correspond to the names exported at runtime. This is probably due to things being missing from the stub or an inaccurate `__all__` in the stub
Stub: in file C:\Ray-Data\python\stubtest-bug\foo\__init__.py
Names exported in the stub but not at runtime: []
Runtime:
Names exported at runtime but not in the stub: ['Foo']

error: foo.Foo is not present in stub
Stub: in file C:\Ray-Data\python\stubtest-bug\foo\__init__.py
MISSING
Runtime:
MISSING

Found 2 errors (checked 2 modules)
```

**Your Environment**

- Mypy version used: 1.4.0 (release-1.4 branch)
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): None
- Python version used: 3.10.5

**Comment by hauntsaninja** [comment] 2023-06-15 19:32
Thanks for the report, this is an issue with underlying mypy. So essentially duplicate of https://github.com/python/mypy/issues/15300

**Closed by hauntsaninja** 2023-06-15 19:32 UTC
Labels: bug

**Comment by rayzchen** [comment] 2023-06-15 19:33
My bad, didn't see the existing issue 😅
