### ISSUE TITLE
"incompatible type", but casting to correct type complains "redundant cast"

### ISSUE THREAD

**Issue by sliedes** [python/mypy#16385] opened 2023-11-01 09:57 UTC
**Bug Report**

In this code, mypy --strict is unhappy both with and without a cast [(playground)](https://mypy-play.net/?mypy=latest&python=3.12&flags=strict&gist=5db64c81d029c7abec632b3961244b91):

```python
from typing import cast


def foo(name: str) -> None:
    pass


def bar(
    name: str | None = None,
) -> None:
    if name is None:
        name = "foo"

    a = [lambda: foo(name)]  # incompatible type "str | None"; expected "str"
    b = [lambda: foo(cast(str, name))]  # Redundant cast to "str"

    del a, b
```

**Expected Behavior**

One of the lines should be ok for mypy.

**Actual Behavior**

```
main.py:14: error: Argument 1 to "foo" has incompatible type "str | None"; expected "str"  [arg-type]
main.py:15: error: Redundant cast to "str"  [redundant-cast]
Found 2 errors in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: 1.6.1, master
- Mypy command-line flags: --strict
- Python version used: 3.11, 3.12

**Comment by ilevkivskyi** [comment] 2023-11-01 22:31
This is essentially a duplicate of https://github.com/python/mypy/issues/4297

**Closed by ilevkivskyi** 2023-11-01 22:31 UTC
Labels: bug, topic-casts
