### ISSUE TITLE
`isinstance` with generic type

### ISSUE THREAD

**Issue by jhance** [python/mypy#949] opened 2015-10-17 22:10 UTC
For example

```
class A(Generic[T]):
   pass

class B(Generic[T], A[T]):
   pass

def f(x: A[T]):
    if isinstance(x, B[T]):
        ...
```

is apparently illegal and I'm not sure what replacement I'm supposed to use. It tells me to use a `# type` comment which isn't really applicable here.

Removing the `[T]` causes mypy to be unable to infer that `x` is in fact a `B[T]`.

**Comment by JukkaL** [comment] 2015-10-17 22:33
Hmm this looks like a mypy bug. It should work like this:

```
class A(Generic[T]):
   pass

class B(Generic[T], A[T]):
   pass

def f(x: A[T]):
    if isinstance(x, B):
        # type of B is B[T] here
        ...
```

**Comment by JukkaL** [comment] 2015-10-17 22:34
And if you try to use `isinstance(x, B[T])`, mypy should give a useful error message.

**Comment by jhance** [comment] 2015-10-18 20:06
I don't think that is powerful enough.

What if I have an `A[U,V]` and want to know if its an `A[U,U]`?

**Comment by JukkaL** [comment] 2015-10-18 23:35
We are stuck with `isinstance` semantics here. However, `isinstance` doesn't seem to be used that often with generic types, at least in the code I've looked at.

**Comment by jhance** [comment] 2015-10-19 03:07
The issue is there logically isn't anything we can infer here, as far as I can tell. Since `isinstance` does not respect generics, we can't either. The best we can do is give an error message instructing the user that they need to cast.

**Comment by elazarg** [comment] 2017-04-03 20:08
Related #3037

**Comment by ilevkivskyi** [comment] 2017-05-05 23:01
On current master it behaves like this:
```python
class A(Generic[T]):
   pass

class B(A[T]):
   pass

x: A[int]
if isinstance(x, B):
    reveal_type(x)  # Revealed type is '__main__.B[Any]'
isinstance(x, B[int])  # Parameterized generics cannot be used with class or instance checks
```
It looks like the issue is fixed only partially. I think the revealed type should be ``B[int]`` (even if it is not 100% safe).

**Comment by sobolevn** [comment] 2019-10-26 12:54
Are there any known work-arounds?

**Comment by Stewori** [comment] 2019-10-26 23:37
For the record, typechecking of generics *does* work in pytypes (Python 3.7+ support is almost done but not released as of this writing). The issue linked above rather required type inference which is beyond the scope of pytypes. See the concrete [example](https://github.com/Stewori/pytypes/issues/82#issuecomment-546603223) that was requested and the answers for clarification.

**Comment by AlexWaygood** [comment] 2022-03-27 10:16
In 2022, the way to achieve "slightly unsafe" type-narrowing of generics in this fashion is to use [`typing.TypeGuard`](https://docs.python.org/3/library/typing.html#typing.TypeGuard) (or `typing_extensions.TypeGuard` on Python <=3.9).

**Closed by AlexWaygood** 2022-03-27 10:16 UTC
Labels: bug, topic-type-variables, priority-1-normal
