### ISSUE TITLE
AssertionError at mypy/semanal.py 

### ISSUE THREAD

**Issue by NicholasKobald** [python/mypy#4421] opened 2018-01-03 04:51 UTC
The error message asked me to report a bug, and I couldn't find an exact duplicate 

Traceback: 
```
> mypy example.py --show-traceback
example.py:7: error: Invalid type alias
example.py:7: error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues version: 0.560
Traceback (most recent call last):
  File "/usr/local/bin/mypy", line 11, in <module>
    sys.exit(console_entry())
  File "/usr/local/lib/python3.6/site-packages/mypy/__main__.py", line 7, in console_entry
    main(None)
  File "/usr/local/lib/python3.6/site-packages/mypy/main.py", line 66, in main
    res = type_check_only(sources, bin_dir, options)
  File "/usr/local/lib/python3.6/site-packages/mypy/main.py", line 119, in type_check_only
    options=options)
  File "/usr/local/lib/python3.6/site-packages/mypy/build.py", line 218, in build
    graph = dispatch(sources, manager)
  File "/usr/local/lib/python3.6/site-packages/mypy/build.py", line 1997, in dispatch
    process_graph(graph, manager)
  File "/usr/local/lib/python3.6/site-packages/mypy/build.py", line 2299, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/usr/local/lib/python3.6/site-packages/mypy/build.py", line 2467, in process_stale_scc
    graph[id].semantic_analysis()
  File "/usr/local/lib/python3.6/site-packages/mypy/build.py", line 1855, in semantic_analysis
    self.manager.semantic_analyzer.visit_file(self.tree, self.xpath, self.options, patches)
  File "/usr/local/lib/python3.6/site-packages/mypy/semanal.py", line 287, in visit_file
    self.accept(d)
  File "/usr/local/lib/python3.6/site-packages/mypy/semanal.py", line 3861, in accept
    node.accept(self)
  File "/usr/local/lib/python3.6/site-packages/mypy/nodes.py", line 497, in accept
    return visitor.visit_func_def(self)
  File "/usr/local/lib/python3.6/site-packages/mypy/semanal.py", line 414, in visit_func_def
    self.analyze_function(defn)
  File "/usr/local/lib/python3.6/site-packages/mypy/semanal.py", line 625, in analyze_function
    defn.body.accept(self)
  File "/usr/local/lib/python3.6/site-packages/mypy/nodes.py", line 756, in accept
    return visitor.visit_block(self)
  File "/usr/local/lib/python3.6/site-packages/mypy/semanal.py", line 1610, in visit_block
    self.accept(s)
  File "/usr/local/lib/python3.6/site-packages/mypy/semanal.py", line 3861, in accept
    node.accept(self)
  File "/usr/local/lib/python3.6/site-packages/mypy/nodes.py", line 869, in accept
    return visitor.visit_return_stmt(self)
  File "/usr/local/lib/python3.6/site-packages/mypy/semanal.py", line 2949, in visit_return_stmt
    s.expr.accept(self)
  File "/usr/local/lib/python3.6/site-packages/mypy/nodes.py", line 1288, in accept
    return visitor.visit_index_expr(self)
  File "/usr/local/lib/python3.6/site-packages/mypy/semanal.py", line 3410, in visit_index_expr
    assert res is not None, "Failed analyzing already defined alias"
AssertionError: Failed analyzing already defined alias
``` 

Guilty code: 
```python
from typing import List, TypeVar

T = TypeVar('T', int, str)
student_grades = List[T]

def average_grades(grades: student_grades) -> T:
    return student_grades[0]
``` 
```bash
(.venv) :~/Work> mypy --version
mypy 0.560
(.venv) :~/Work> python3 --version
Python 3.6.3
```

Apologies if this is a duplicate.

**Comment by ethanhs** [comment] 2018-01-03 04:58
For your code:
It appears you are indexing the type and not the variable.

For mypy:
We probably shouldn't crash in this case.

**Comment by gvanrossum** [comment] 2018-01-03 05:02
It should still not crash. But yeah, not a common mistake I guess...

**Comment by NicholasKobald** [comment] 2018-01-03 05:06
If we all agree on that, I'll take a stab at submitting a patch to catch that!

**Comment by ilevkivskyi** [comment] 2018-01-03 15:14
I am almost sure it is caused by one of ``--strict-optional`` PRs. This means it should be easy to fix.

**Comment by ilevkivskyi** [comment] 2018-06-26 11:28
The original code doesn't crash anymore. Instead it gives this error:
```
tstna.py:7: error: Value of type "Type[List[Any]]" is not indexable
tstna.py:7: error: Type expected within [...]
```
which is probably not the clearest one, but the best we can currently give. Probably this was somehow fixed by a recent type alias refactoring. Also please note there is another mistake in the original code, it should be `student_grades[T]`, otherwise the generic alias is expanded to `List[Any]` (you can use `--disallow-any-generics` to catch this).

**Closed by ilevkivskyi** 2018-06-26 11:28 UTC
Labels: crash, priority-1-normal
