### ISSUE TITLE
Pattern matchin crashes mypy 0.910

### ISSUE THREAD

**Issue by CucumisSativus** [python/mypy#11647] opened 2021-11-30 20:40 UTC
**Crash Report**

I was trying to type check simple pattern matching code

**Traceback**

```
pattern_matching.py: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.910
Traceback (most recent call last):
  File "/home/michal/.local/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/home/michal/.local/lib/python3.10/site-packages/mypy/__main__.py", line 11, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "/home/michal/.local/lib/python3.10/site-packages/mypy/main.py", line 87, in main
    res, messages, blockers = run_build(sources, options, fscache, t0, stdout, stderr)
  File "/home/michal/.local/lib/python3.10/site-packages/mypy/main.py", line 165, in run_build
    res = build.build(sources, options, None, flush_errors, fscache, stdout, stderr)
  File "/home/michal/.local/lib/python3.10/site-packages/mypy/build.py", line 179, in build
    result = _build(
  File "/home/michal/.local/lib/python3.10/site-packages/mypy/build.py", line 254, in _build
    graph = dispatch(sources, manager, stdout)
  File "/home/michal/.local/lib/python3.10/site-packages/mypy/build.py", line 2644, in dispatch
    graph = load_graph(sources, manager)
  File "/home/michal/.local/lib/python3.10/site-packages/mypy/build.py", line 2802, in load_graph
    st = State(id=bs.module, path=bs.path, source=bs.text, manager=manager,
  File "/home/michal/.local/lib/python3.10/site-packages/mypy/build.py", line 1888, in __init__
    self.parse_file()
  File "/home/michal/.local/lib/python3.10/site-packages/mypy/build.py", line 2016, in parse_file
    with self.wrap_context():
  File "/usr/lib64/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/michal/.local/lib/python3.10/site-packages/mypy/build.py", line 1955, in wrap_context
    yield
  File "/home/michal/.local/lib/python3.10/site-packages/mypy/build.py", line 2046, in parse_file
    self.tree = manager.parse_file(self.id, self.xpath, source,
  File "/home/michal/.local/lib/python3.10/site-packages/mypy/build.py", line 788, in parse_file
    tree = parse(source, path, id, self.errors, options=options)
  File "/home/michal/.local/lib/python3.10/site-packages/mypy/parse.py", line 25, in parse
    return mypy.fastparse.parse(source,
  File "/home/michal/.local/lib/python3.10/site-packages/mypy/fastparse.py", line 168, in parse
    ).visit(ast)
  File "/home/michal/.local/lib/python3.10/site-packages/mypy/fastparse.py", line 329, in visit
    return visitor(node)
  File "/home/michal/.local/lib/python3.10/site-packages/mypy/fastparse.py", line 496, in visit_Module
    body = self.fix_function_overloads(self.translate_stmt_list(mod.body, ismodule=True))
  File "/home/michal/.local/lib/python3.10/site-packages/mypy/fastparse.py", line 367, in translate_stmt_list
    node = self.visit(stmt)
  File "/home/michal/.local/lib/python3.10/site-packages/mypy/fastparse.py", line 329, in visit
    return visitor(node)
  File "/home/michal/.local/lib/python3.10/site-packages/mypy/fastparse.py", line 509, in visit_FunctionDef
    return self.do_func_def(n)
  File "/home/michal/.local/lib/python3.10/site-packages/mypy/fastparse.py", line 607, in do_func_def
    self.as_required_block(n.body, lineno),
  File "/home/michal/.local/lib/python3.10/site-packages/mypy/fastparse.py", line 439, in as_required_block
    b = Block(self.fix_function_overloads(self.translate_stmt_list(stmts)))
  File "/home/michal/.local/lib/python3.10/site-packages/mypy/fastparse.py", line 367, in translate_stmt_list
    node = self.visit(stmt)
  File "/home/michal/.local/lib/python3.10/site-packages/mypy/fastparse.py", line 327, in visit
    visitor = getattr(self, method)
AttributeError: 'ASTConverter' object has no attribute 'visit_Match'
```

**To Reproduce**

running mypy without any argument and no config on this file

```python
def use_patter_matching(test_string: str):
    match test_string.split():
        case other:
            print(f'captured {other}')

use_patter_matching('other')
```

**Your Environment**

- Mypy version used: 0.910 (master from github)
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): none 
- Python version used: Python 3.10.0 (default, Oct  4 2021, 00:00:00) [GCC 11.2.1 20210728 (Red Hat 11.2.1-1)] on linux
- Operating system and version: Fedora release 35 (Thirty Five) (kernel 5.15.4-201.fc35.x86_64)

**Comment by JelleZijlstra** [comment] 2021-11-30 20:47
Duplicate of #11251.

**Closed by JelleZijlstra** 2021-11-30 20:47 UTC
Labels: crash
