### ISSUE TITLE
Should mypy know that bitwise-or can yield bool?

### ISSUE THREAD

**Issue by tallforasmurf** [python/mypy#2498] opened 2016-11-26 16:41 UTC
CPython at run time knows that *bool*`|`*bool* --> *bool*, e.g.

    >>> type( False | ( 1 < 2 ) )
        <class 'bool'>

However mypy begs to differ, saying that in this sequence,

    hit = False
    hit = hit | ( x < 0 )

the expression is int and incompatible with the type of the variable. Obviously can be gotten around by replacing `|` with `or`, and it can be argued that `or` is what the programmer "really" means anyway. But the CPython runtime "knows" that bitwise-or of bools is bool, so shouldn't mypy?

**Comment by gvanrossum** [comment] 2016-11-26 17:44
It's a known bug. The primary fix should be in typeshed, but there's a nit that needs to be fixed in mypy first. Duplicate of https://github.com/python/typeshed/issues/649

**Closed by gvanrossum** 2016-11-26 17:44 UTC

**Comment by tallforasmurf** [comment] 2016-11-26 17:56
Thanks, I didn't known to look there.
