### ISSUE TITLE
Spurious used-before-def in a specific situation using walrus

### ISSUE THREAD

**Issue by tzaffi** [python/mypy#14683] opened 2023-02-12 20:41 UTC
**Bug Report**

I'm getting the following mypy error `used-before-def` on the code snippet below:

I played around a bit trying to simplify, but there could be other scenarios I haven't explored.

Generalizing what I deem the problem to be: 

### WHEN:
* A function is defined whereby
* it calls a callable object
* AND inside the call there an assignment to a new variable
* AND the call returns another callable object
* AND the other callable object is supplied the new variable defined in the previous call

#### THEN:
the `used-before-def` error is generated even though there is nothing at all incorrect in this scenario since the new variable would _ALWAYS_ be available.

**To Reproduce**

run `mypy` version 1.0 on the following:

```python
from typing import Any


class Reporter:
    def __init__(self, x: Any):
        self.x: Any = x

    def report(self, y: Any = None):
        print(self.x)
        if y is not None:
            print(y)


def foo(z: Any):
    Reporter(x := z).report(x)


for i in range(10):
    foo(i)
```

**Expected Behavior**

No error should be generated.

**Actual Behavior**

```sh
pyteal/walrus.py:15 error: Name "x" is used before definition  [used-before-def]
```

**Your Environment**

Python 3.11.1 running on mac Ventura 13.1

- Mypy version used: 1.0
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): not relevant IMO
- Python version used: 3.11.1

**Comment by AlexWaygood** [comment] 2023-02-12 21:45
Duplicate of #14626

**Comment by AlexWaygood** [comment] 2023-02-12 21:45
A patch release with the fix should hopefully be coming soon! :)

**Closed by AlexWaygood** 2023-02-12 21:45 UTC
Labels: bug, topic-pep-572, topic-partially-defined
