### ISSUE TITLE
Allow Final attributes declared in dataclass body without a default value

### ISSUE THREAD

**Issue by sisp** [python/mypy#10688] opened 2021-06-22 10:33 UTC
**Feature**

It should be allowed to declare a read-only (final) dataclass attribute:

```python
@dataclass
class A:
    x: Final[str]  # error: Final name must be initialized with a value  [misc]
```

**Pitch**

I think it's a common scenario where a dataclass attribute should be read-only once the dataclass has been instantiated. It works fine with a default value

```python
@dataclass
class B:
    x: Final[str] = 'abc'  # ok
```

and with a regular class:

```python
class B:
    x: Final[str]  # ok
    
    def __init__(self, x: str) -> None:
        self.x = x
```

See the full example on the [mypy playground](https://mypy-play.net/?mypy=latest&python=3.9&gist=0aa3cc80982a596870798b658b8662b9).

**Comment by erictraut** [comment] 2021-06-22 14:36
As a simple workaround, you could assign it a field descriptor.

```python
@dataclass
class A:
    x: Final[str] = field()
```

**Comment by sisp** [comment] 2021-06-22 14:39
@erictraut Thanks for suggesting the workaround! A proper fix would still be nice.

**Comment by AlexWaygood** [comment] 2022-03-30 23:33
Closing as a duplicate of #5608

**Closed by AlexWaygood** 2022-03-30 23:33 UTC
Labels: feature, topic-final, topic-dataclasses
