### ISSUE TITLE
Incorrect handling of kwargs when default values are present

### ISSUE THREAD

**Issue by takeda** [python/mypy#5809] opened 2018-10-19 18:06 UTC
I have a following code:

```python
#! /usr/bin/env python

from typing import Any

def function(a, b, c=False, **kwargs):
	# type: (str, int, bool, **Any) -> None

	print "Got the following:", repr(a), repr(b), repr(c), repr(kwargs)

def main():
	# type: () -> None

	function('a', 2, **{'optional1': 1})

if __name__ == '__main__':
	main()
```

When I run it it produces this result:
```
$ ./test.py
Got the following: 'a' 2 False {'optional1': 1}
```

It looks like mypy thinks that the kwargs were passed as argument `c` which is incorrect:
```
$ ../py37/bin/mypy --python-executable ../py27/bin/python test.py
test.py:13: error: Argument 3 to "function" has incompatible type "**Dict[str, int]"; expected "bool"
```

The mypy version is 0.641

**Comment by ilevkivskyi** [comment] 2018-10-21 20:31
For mypy this is just a dictionary, even if it is just a literal, so this is a duplicate of https://github.com/python/mypy/issues/5382.

**Closed by ilevkivskyi** 2018-10-21 20:31 UTC

**Comment by ilevkivskyi** [comment] 2018-12-20 11:52
I looks like I mentioned wrong issue when closing, this is not a duplicate of #5382 but of https://github.com/python/mypy/issues/1969
