### ISSUE TITLE
Incompatible return value type (got "_PydanticBaseModel", expected "MyModel") after update on v1.11.0

### ISSUE THREAD

**Issue by vprud** [python/mypy#17555] opened 2024-07-22 09:16 UTC
**Bug Report**

After updating mypy to version 1.11.0, I get an error:
```bash
Incompatible return value type (got "_PydanticBaseModel", expected "Child")  [return-value]
```

The error is reproduced only when using `construct`

**To Reproduce**

```python
from pydantic import BaseModel


class Parent(BaseModel):
    foo: str


class Child(Parent):
    bar: str


def func() -> Child:
    return Child.construct(foo="foo", bar="bar")

```

**Expected Behavior**

There are no errors

**Actual Behavior**

```bash
error: Incompatible return value type (got "_PydanticBaseModel", expected "Child")  [return-value]
```

**Your Environment**

- Mypy version used: 1.11.0
- Mypy command-line flags: - 
- Mypy configuration options from `mypy.ini` (and other config files): `plugins = pydantic.mypy`
- Python version used: 3.11.4
- Pydantic version used: 1.10.17

**Comment by jonathangreen** [comment] 2024-07-31 17:45
👍🏻 I'm seeing the same thing on `mypy` 1.11.1 and `pydantic` 1.10.17.

**Comment by jonathangreen** [comment] 2024-08-09 00:32
This one looks like a pydantic mypy plugin issue, here is the link to the issue in the pydantic github https://github.com/pydantic/pydantic/issues/10000

**Comment by brianschubert** [comment] 2024-11-11 15:14
I can reproduce this in pydantic 1.10.17, but not in 1.10.18+. Looks like this was fixed in pydantic, likely in https://github.com/pydantic/pydantic/pull/10139

**Closed by brianschubert** 2024-11-11 15:14 UTC
Labels: bug
