### ISSUE TITLE
Proposal: TbdType, UnsupportedType.

### ISSUE THREAD

**Issue by douglas-treadwell** [python/mypy#3736] opened 2017-07-18 23:03 UTC
This is a pattern I'm using while adding MyPy to a large existing codebase, where I don't have time to investigate the type or the type is non-trivial.

from typing import Any as TbdType.

I propose adding an alias TbdType for Any in mypy and including a suggestion for this use in the documentation.  TbdType is sufficiently unlikely to exist in any code aside from this use that it's a useful search key.

This way users will be able to search more easily later for cases where types were TRULY "Any" versus not known at the time and skipped.

As an extension of this, another alias could be provided for "this type is complex enough that MyPy doesn't currently support typing this", so users could periodically review their code for cases like this as MyPy improves.  This could be called AwaitingType, AwaitingSupportForType, UnsupportedType, or something like that.

**Comment by Michael0x2a** [comment] 2017-07-19 00:00
This proposal is probably a better fit for https://github.com/python/typing since you're proposing to change the `typing` module and PEP 484 rather then mypy itself.

That said, idk if making that change is really necessary? If you're trying to eliminate redundancy, you could always create your own `custom_types.py` file where you define those aliases and grep for them later on -- I think that should basically support your use case without requiring changes to the standard library?

**Comment by ilinum** [comment] 2017-07-19 00:58
This seems like a duplicate of #3712

**Comment by gvanrossum** [comment] 2017-07-19 03:38
I also think that you can easily do this yourself if you like this convention (I don't particularly, and we have over 800,000 lines of code annotated so far at Dropbox). So I think we should just reject the feature request.

**Closed by gvanrossum** 2017-07-19 03:38 UTC
