### ISSUE TITLE
Can't use GenericAlias for type hinting

### ISSUE THREAD

**Issue by tierriminator** [python/mypy#14538] opened 2023-01-27 14:26 UTC
**Bug Report**

This issue is somewhat related to #13637.

I've implemented a function, receiving a generic type alias as an argument, which I'm type hinting with `types.GenericAlias`.
However, if I provide an argument to the function, such as a realization of `typing.Callable`, I'm getting an error from Mypy.

See also [my StackOverflow post](https://stackoverflow.com/questions/75236516/how-can-i-type-hint-arbitrary-generic-type-aliases-in-python).

**To Reproduce**

https://mypy-play.net/?mypy=latest&python=3.12&gist=40da631ea66c8f1b6c657cd0c2b848ef

**Expected Behavior**

Mypy should succeed.

**Actual Behavior**

```
Argument 1 to "foo" has incompatible type "object"; expected "GenericAlias"
```

**Your Environment**

- Mypy version used: 0.991
- Python version used: 3.12

**Comment by hauntsaninja** [comment] 2023-01-27 19:59
This is essentially a duplicate of https://github.com/python/mypy/issues/9773

**Closed by hauntsaninja** 2023-01-27 19:59 UTC
Labels: bug
