### ISSUE TITLE
class decorators that change the type don't work

### ISSUE THREAD

**Issue by DetachHead** [python/mypy#11117] opened 2021-09-16 11:36 UTC
```py
def deco(value) -> int:
    ...
    
@deco
class Class:
    ...
    
reveal_type(Class) # note: Revealed type is "def () -> __main__.Class"

@deco
def function(): ...

reveal_type(function) # note: Revealed type is "builtins.int"
```

https://mypy-play.net/?mypy=latest&python=3.10&gist=705baa296d3181f0b670416a405978b4

**Comment by CyanoKobalamyne** [comment] 2021-09-29 05:47
Are there any plans for fixing this? I'm using a class decorator that is a class itself (thereby transforming the original class into an instance of the decorator), and running into issues where mypy is inferring the wrong type.

Here is a simplified example:

```python
from typing import Generic, Type, TypeVar

T = TypeVar("T")

class Deco(Generic[T]):
    def __init__(self, cls: Type[T]):
        self._cls = cls

    def get(self) -> T:
        return self._cls()

@Deco
class Klass:
    ...

reveal_type(Deco)  # note: Revealed type is 'def [T] (cls: Type[T`1]) -> Deco[T`1]'
reveal_type(Deco.get)  # note: Revealed type is 'def [T] (self: Deco[T`1]) -> T`1'
reveal_type(Klass)  # note: Revealed type is 'def () -> Klass'
reveal_type(Klass.get)  # error: "Type[Klass]" has no attribute "get" 
```

**Comment by JelleZijlstra** [comment] 2023-10-09 21:09
Duplicate of #3135

**Closed by JelleZijlstra** 2023-10-09 21:09 UTC
Labels: bug

**Comment by DetachHead** [comment] 2023-10-10 10:32
@JelleZijlstra that looks like a different issue that's since been fixed, since mypy now shows an error on invalid class decorators:

```py
decorator: int = 3

@decorator  # error: "int" not callable  [operator]
class A:
    pass
```
[playground](https://mypy-play.net/?mypy=latest&python=3.11&flags=show-error-context%2Cshow-error-codes%2Cstrict%2Ccheck-untyped-defs%2Cdisallow-any-decorated%2Cdisallow-any-expr%2Cdisallow-any-explicit%2Cdisallow-any-generics%2Cdisallow-any-unimported%2Cdisallow-incomplete-defs%2Cdisallow-subclassing-any%2Cdisallow-untyped-calls%2Cdisallow-untyped-decorators%2Cdisallow-untyped-defs%2Cno-implicit-reexport%2Clocal-partial-types%2Cstrict-equality%2Cwarn-incomplete-stub%2Cwarn-redundant-casts%2Cwarn-return-any%2Cwarn-unreachable%2Cwarn-unused-configs%2Cwarn-unused-ignores%2Cno-implicit-optional&gist=685d8fb20207e89812f303929c5a2ec6)

my issue is that class decorators aren't able to change the type of the class they're decorating:
```py
def decorator(cls: type[object]) -> int: ...


@decorator  
class A:
    pass


reveal_type(A) # `def () -> __main__.A`, should be `int`
```

so i suggest either closing the original issue and re-opening this one, or updating the original issue to match this one

**Comment by SeeFrenchDev** [comment] 2024-08-26 17:56
same issue, does someone knows how to fix it?
