### ISSUE TITLE
In strict mode, Mypy complains about finding attribute on union. [union-attr]

### ISSUE THREAD

**Issue by amirsoroush** [python/mypy#15099] opened 2023-04-21 20:36 UTC
**Bug Report**

Despite assigning a correct type, Mypy complains about finding an attribute when using `--strict` flag.

**To Reproduce**

```python
var: int | None
var = 20

def fn() -> int:
    return var.bit_length()

print(fn())
```

**Expected Behavior**

Is to see "No Issue".

**Actual Behavior**
```none
main.py:5: error: Item "None" of "Optional[int]" has no attribute "bit_length"  [union-attr]
Found 1 error in 1 file (checked 1 source file)
```
**Your Environment**

- Mypy version used: `1.2.0`
- Mypy command-line flags: `--strict`
- Python version used: `3.10.6`, `3.11`, `3.12`

**Comment by erictraut** [comment] 2023-04-21 21:06
This is a duplicate of https://github.com/python/mypy/issues/2608.
is unsafe in the general case. Consider the following minor change to your code, which crashes at runtime.

```python
var: int | None
var = 20

def fn() -> int:
    return var.bit_length()

var = None

print(fn())
```

**Comment by JelleZijlstra** [comment] 2023-04-21 21:09
Agree, mypy is correct here. Even if we change the behavior in #2608, this is a global variable, where it is even harder to reliably narrow the value.

**Closed by JelleZijlstra** 2023-04-21 21:09 UTC
Labels: bug

**Comment by amirsoroush** [comment] 2023-04-21 21:12
@erictraut Reasonable. Thanks for explaining that case. So here it's better to remove the type hint for that global right?

**Comment by erictraut** [comment] 2023-04-21 22:29
Yes, you could remove the type annotation. Another option is to add an assert within the inner scope (`assert var is not None`) to document your assumption for the type checker.
