### ISSUE TITLE
Cannot determine type of attribute class in base class

### ISSUE THREAD

**Issue by OJFord** [python/mypy#4956] opened 2018-04-23 18:51 UTC
```python
class Foo:
    class Thing(object): # type: ignore
        pass

class Thing:
    pass

class Bar:
    Thing = Thing

class FooBar(Foo, Bar):
    pass
```

> scratch.py:11: error: Cannot determine type of 'Thing' in base class 'Foo'

Adding `object` doesn't help, nor `#type: ignore` as shown above.

However, `Bar.Thing` _does_ type check; so there seems only to be a problem typing _literal_ class-valued class attributes, when inherited. (Aside: many thanks if you can tell me the proper terminology for these `Bar.Thing` and `Foo.Thing`s - it's not easy to search for!)

Note `Foo.Thing` is not a problem until the inheriting class is introduced on L11.

**Comment by ilevkivskyi** [comment] 2018-04-24 07:57
This is not a bug but how mypy works. The error message can be made clearer however. The point is that inner classes are treated as types, not variables (i.e. as statically known), they cannot be re-assigned, but can be used in type annotations. On the contrary, an instance variable with type `Type[Thing]` (this is what is created by the assignment in your example) can be re-assigned, but can't be used in type annotations.

**Comment by OJFord** [comment] 2018-04-24 09:31
@ilevkivskyi Many thanks for your reply. I think it might help to explain why this is causing me a problem.

My `Foo` and `Bar` are really Django model 'mixins' (in quotes because they must inherit from Django's `Model` in order to provide extra ORM fields) and the inner class `Thing` is really Django's `Meta`, (_not_ an actual metaclass) necessary to specify `Meta.abstract = True` in order not to create extra database tables for the 'mixin' itself.

The problem then is that, with `Meta` as inner class, mypy cannot determine its type; with `Meta` as instance variable, it conflicts with multiple 'mixins' (inheritance):

```python
class IdMeta:
    abstract = True
    ordering = ('id,')

class Id(Model):
    Meta = IdMeta
    id = IntegerField(...)

class CreatedMeta:
    abstract = True

class Created(Model):
    Meta = CreatedMeta
    created = DateTimeField(...)

class RealModel(Model, Id, Created):
    ...
```

> error: Definition of "Meta" in base class "Created" is incompatible with definition in base class "Id"

**Comment by ilevkivskyi** [comment] 2018-04-24 09:47
Support of Django is a separate project and will require writing a plugin, see https://github.com/python/mypy/issues/3539 (there are too much magic to typecheck normally).

Also it looks like we already have a very similar issue to yours https://github.com/python/mypy/issues/3855 with a similar motivation. So I think we can close this, feel free to re-open if you think this is a separate issue.

**Closed by ilevkivskyi** 2018-04-24 09:47 UTC
Labels: topic-usability

**Comment by OJFord** [comment] 2018-04-24 09:51
Thanks; apologies - it's certainly a duplicate.

Is there any way to workaround this though? At this point I would be quite happy with `# type: ignore`, or similar, but that doesn't work. Or is it simply not possible to use mypy in a Django project with this pattern?

**Comment by ilevkivskyi** [comment] 2018-04-24 17:34
Can you put `# type: ignore` on the line where it is reported? (This is how ignores are supposed to work, they just silence errors.)

**Comment by OJFord** [comment] 2018-04-24 17:49
Oh no - sorry - I'm not sure how I screwed that up, that does work. Many thanks!

**Comment by alexpirine** [comment] 2018-11-08 16:10
FYI, similar issues #2871 #3855
