### ISSUE TITLE
typing.Optional with not None default, should not type check None value until it mutate.

### ISSUE THREAD

**Issue by sileht** [python/mypy#10743] opened 2021-06-30 07:19 UTC
The example is self explicit.
It looks weird that we need to check for `final_params is None` when we just set it explicitly to something else.

```python
import typing

def local_optional_default_not_working(
  params: typing.Optional[typing.Dict[str, str]] = None,
) -> None:
    final_params: typing.Optional[typing.Dict[str, str]] = {"per_page": "100"}
    if params is not None:
        final_params.update(params)


def local_optional_default_workaround1(
  params: typing.Optional[typing.Dict[str, str]] = None,
) -> None:
    final_params: typing.Optional[typing.Dict[str, str]]
    final_params = {"per_page": "100"}

    if params is not None:
        final_params.update(params)

def local_optional_default_workaround2(
  params: typing.Optional[typing.Dict[str, str]] = None,
) -> None:
    final_params: typing.Optional[typing.Dict[str, str]] = {"per_page": "100"}
    if final_params is None:
        raise RuntimeError("final_params can be None really ?")

    if params is not None:
        final_params.update(params)
```

**Expected Behavior**

No mypy error

**Actual Behavior**

```shell
$ mypy --strict optional_local_default.py
optional_local_default.py:8: error: Item "None" of "Optional[Dict[str, str]]" has no attribute "update"
Found 1 error in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: 0.910
- Mypy command-line flags:
- Mypy configuration options from `mypy.ini` (and other config files): strict
- Python version used: 3.9
- Operating system and version: arch

**Comment by hauntsaninja** [comment] 2021-07-01 03:41
Duplicate of https://github.com/python/mypy/issues/2008 (also see the typing-sig thread linked at the end)

**Closed by hauntsaninja** 2021-07-01 03:41 UTC
Labels: bug
