### ISSUE TITLE
Narrow down tuple types with len check

### ISSUE THREAD

**Issue by ikamensh** [python/mypy#14019] opened 2022-11-06 11:05 UTC
**Feature**
I wish mypy understood that following code is actually correct:

```python
def foo(x: tuple[str, str] | tuple[str, str, str]):
  if len(x) == 2:
     obs, info = x  # error: Too many values to unpack (2 expected, 3 provided)  [misc]
  ...
```

**Pitch**

Tuples are universal way to return multiple values in python, and are ubiquitous. It's natural to process cases where data can come in different number of elements with length checks. Currently I could write a custom type guard function (is boilerplate and extra effort) or # type: ignore (but I lose benefit of type checking here)

`pyright` understands this case, and I wish mypy did as well.

**Comment by AlexWaygood** [comment] 2022-11-06 11:08
Duplicate of #1178

**Closed by AlexWaygood** 2022-11-06 11:08 UTC
Labels: feature
