### ISSUE TITLE
Daemon hangs up too early when sending crash information

### ISSUE THREAD

**Issue by ethanhs** [python/mypy#6621] opened 2019-04-03 20:44 UTC
I noticed this while testing the new release, but this has been true for forever.

Currently if I `dmypy run -- test.py --follow-imports=error` on a file that causes mypy to crash, I will just get:
```
Daemon started
<wait>
[WinError 233] No process is on the other end of the pipe
```
Which doesn't tell me much, especially if I don't know what pipes have to do with the daemon.

The problem is the daemon dies, and the client never hears from it, but the error message isn't clear.

To fix this, IMO we should catch `Exception` and try to pass them back to the client. @msullivan, does this make sense to you?

**Comment by ethanhs** [comment] 2019-07-03 18:33
BTW I finally found time to dig into this. This is not a Windows-only bug. It seems the daemon will re-raise exceptions (and hence hang up) before the client has time to hear about crashes.

The relevant code is here: 
https://github.com/python/mypy/blob/master/mypy/dmypy_server.py#L220

Confirmed on Linux and Windows on mypy 0.711.

I'm not sure exactly what the best way to solve this is. Perhaps we can check the pipe is empty before re-raising? Or have the client send an acknowledgement of the error message?

**Comment by msullivan** [comment] 2019-10-01 20:12
Sorry, I missed this! I think that this is a dupe of #4804 and happens when a crash is caught by report_internal_error. dmypy_server does try to catch exceptions and report them back but if they get sent to report_internal_error it prints to stderr and then exits.

I'm going to close this, since I think it is a dupe, but reopen it if my analysis was wrong.

**Closed by msullivan** 2019-10-01 20:12 UTC
Labels: crash, priority-0-high, topic-daemon, topic-usability
