### ISSUE TITLE
TypeDict alternative syntax not supported under Python 3.8

### ISSUE THREAD

**Issue by melassa** [python/mypy#11651] opened 2021-12-02 10:20 UTC
**Documentation**

From [Doc](https://docs.python.org/3/library/typing.html?highlight=typeddict#typing.TypedDict) 

```
To allow using this feature with older versions of Python that do not support PEP 526, 
TypedDict supports two additional equivalent syntactic forms:

Point2D = TypedDict('Point2D', x=int, y=int, label=str)
```

But Mypy 0.910 under Python 3.8:

`Mypy: Too many arguments for TypedDict()`

**Comment by JelleZijlstra** [comment] 2021-12-02 14:47
We just don't support it. This is a duplicate of #11555.

**Closed by JelleZijlstra** 2021-12-02 14:47 UTC
Labels: documentation, topic-typed-dict
