### ISSUE TITLE
MyPy does not consider the setter signature when type-checking assignments of properties

### ISSUE THREAD

**Issue by wjakob** [python/mypy#16957] opened 2024-02-28 08:29 UTC
**Bug Report**
It is a relatively common design pattern that a property setter might be more accepting of various inputs and then perform a conversion internally to conform the input to the right type (in fact, this might be the very reason that a `@property` is used, as opposed to merely storing data in an attribute).

PyRight accepts the following code without warnings or errors. MyPy does not:

**To Reproduce**

```python
class C:
    @property
    def x(self, /) -> int:
        return 1

    @x.setter
    def x(self, value: float | int, /) -> None:
        pass

c = C()
c.x = 3.0
```

**Expected Behavior**

Accepted without errors or warnings.

**Actual Behavior**

```
q.py:11: error: Incompatible types in assignment (expression has type "float", variable has type "int")  [assignment]
Found 1 error in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: mypy 1.8.0 (compiled: yes)
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): N/A
- Python version used: 3.12.2

**Comment by AlexWaygood** [comment] 2024-02-28 08:35
Thanks! Closing as a duplicate of #3004

**Closed by AlexWaygood** 2024-02-28 08:35 UTC
Labels: bug, topic-descriptors
