### ISSUE TITLE
callable protocols can be satisfied by any type object, even ones with nothing to do with their return type or arguments

### ISSUE THREAD

**Issue by glyph** [python/mypy#14544] opened 2023-01-27 23:37 UTC
**Bug Report**

When specifying a callable as a `Protocol`, it seems that any concrete type reference (i.e. `object`, or `class X:...; X`) will pass the check.  However, the same callable specified as a `Callable` will not allow them.

**To Reproduce**

Consider [this code](https://mypy-play.net/?mypy=latest&python=3.11&flags=strict&gist=7737afa48d69debc48bcc73a1bed271c):

```python3
from typing import Callable, Protocol, TypeAlias


class A:
    ...


class B:
    ...


class A2B_P(Protocol):
    def __call__(self, a: A) -> B:
        ...


A2B_C: TypeAlias = Callable[[A], B]


def a2b(a: A) -> B:
    return B()


a2b_p: A2B_P
a2b_c: A2B_C
a2b_p = a2b
a2b_c = a2b
a2b_p = object # ???
a2b_c = object
```

**Expected Behavior**

I'd definitely expect an error here as `object` does not take an `A` and does not produce a `B`.

**Actual Behavior**

The error is the absence of output :).

**Your Environment**

- Mypy version used: 0.991
- Mypy command-line flags: `--strict`
- Mypy configuration options from `mypy.ini` (and other config files): nothing in particular, see playground gist
- Python version used: 3.11

**Comment by markedwards** [comment] 2023-02-27 09:36
The given example seems to be fixed as of mypy 1.0.0.  However, there is still what I think is a related bug when the protocol in question is parameterized:

```
from typing import Protocol, TypeVar

T = TypeVar("T")
T_co = TypeVar("T_co", covariant=True)


class Proto(Protocol[T_co]):
    def __call__(self, *, a: str) -> T_co:
        ...


class InvalidClass:
    def __init__(self, *, a: int) -> None:
        ...


def test(b: Proto[T]) -> T:
    return b(a="0")
    

test(InvalidClass)  # <-- should fail type checking
```

`InvalidClass` is accepted here even though it does not conform to the protocol.  Here's a [more detailed playground gist](https://mypy-play.net/?mypy=latest&python=3.11&flags=strict&gist=87dc69efbf5114d07ce5680507c7c758).

As demonstrated in the gist, the issue does not reproduce when a function is provided, only with a class.  It also does not manifest with assignment, only with arguments.  However, assigning with the parameter set to `Any` also produces an unexpected result, which I expect is somehow related.

Perhaps this variation is different enough that I should open a new issue?

**Comment by hauntsaninja** [comment] 2023-02-27 18:13
Yes, could you open a new issue?

**Comment by markedwards** [comment] 2023-02-27 18:54
@hauntsaninja, opened #14798

**Comment by hauntsaninja** [comment] 2023-02-27 23:36
Thanks! Closing this issue since I think OP's case now correctly issues errors

**Closed by hauntsaninja** 2023-02-27 23:36 UTC
Labels: bug
