### ISSUE TITLE
Do not known how to call the issue. Please fix the subject line.

### ISSUE THREAD

**Issue by socketpair** [python/mypy#9567] opened 2020-10-09 17:30 UTC
```python
src = {
    'test': {
        'a': 1,
        'b': '2',
    },
}
{key: {**value, 'c': False} for key, value in src.items()}
```

gives:

```
main.py:7: error: Argument 1 to "update" of "dict" has incompatible type "Dict[str, object]"; expected "Mapping[str, bool]"
Found 1 error in 1 file (checked 1 source file)
```

but actually works as expected:

```python
In [1]: src = { 
   ...:     'test': { 
   ...:         'a': 1, 
   ...:         'b': '2', 
   ...:     }, 
   ...: } 
   ...: {key: {**value, 'c': False} for key, value in src.items()}                                                                                                           
Out[1]: {'test': {'a': 1, 'b': '2', 'c': False}}
```
https://mypy-play.net/?mypy=latest&python=3.8&gist=b9e421adc95622a33aceae1f2b6fcc6e

**Comment by socketpair** [comment] 2020-10-12 12:57
@JelleZijlstra ?

**Comment by AlexWaygood** [comment] 2022-03-25 20:30
I'm closing this issue. It's very unclear what this code is meant to do, or how you expect mypy to cope with it.

Mypy emits many errors for things which will not necessarily cause type errors at runtime, and this is entirely deliberate.

**Closed by AlexWaygood** 2022-03-25 20:30 UTC

**Comment by socketpair** [comment] 2022-03-25 20:56
emm. Why not to ask me (topicstarter) ?

**Comment by socketpair** [comment] 2022-03-25 20:58
@AlexWaygood Python code in the example has no typing errors. mypy incorrectly thinks that  `{**value, 'c': False}` is `Mapping[str, bool]`

**Comment by JelleZijlstra** [comment] 2022-03-25 20:59
Duplicate of #11604 in that case (and probably others)

**Comment by AlexWaygood** [comment] 2022-03-25 21:02
@socketpair, this stackoverflow Q&A might be helpful: https://stackoverflow.com/questions/68803511/mypy-error-incompatible-types-in-assignment-expression-has-type-dictnothing

The issue is that your code here is pretty dynamic, so mypy doesn't know how to interpret the types of your variables. You can fix the error by adding type annotations.
