### ISSUE TITLE
Can't type a decorator factory that preserves signature

### ISSUE THREAD

**Issue by JelleZijlstra** [python/mypy#2657] opened 2017-01-08 12:51 UTC
There doesn't appear to be a way to type a decorator factory that preserves its arguments (similar to `@functools.wraps()`. This is related to #1927 and the doc example in http://mypy.readthedocs.io/en/latest/generics.html#declaring-decorators but covers a slightly more complicated case.

Example code:
```
$ cat decorator_factory.py 
from typing import Any, Awaitable, Callable, cast, Dict, Tuple, TypeVar

FuncType = Callable[..., Any]
F = TypeVar('F', bound=FuncType)


def memoize() -> Callable[[F], F]:
    def decorator(fn: F) -> F:
        def wrapper(*args: Any, **kwargs: Any) -> Any:
            return fn(args, **kwargs)
        return cast(F, wrapper)

    reveal_type(decorator)
    return cast(Callable[[F], F], decorator)

reveal_type(memoize)
reveal_type(memoize())


@memoize()
def f() -> None:
    pass
$ python3 -m mypy decorator_factory.py 
decorator_factory.py: note: In function "memoize":
decorator_factory.py:13: error: Revealed type is 'def (fn: F`-1) -> F`-1'
decorator_factory.py: note: At top level:
decorator_factory.py:16: error: Revealed type is 'def [F <: def (*Any, **Any) -> Any] () -> def (F`-1) -> F`-1'
decorator_factory.py:17: error: Revealed type is 'def (builtins.None) -> builtins.None'
decorator_factory.py:20: error: Argument 1 has incompatible type Callable[[], None]; expected None
```

I'm guessing mypy doesn't see the F typevars on the outer and inner functions as the same type. Strangely, it looks like the typevar is instantiated as None, even though None is outside its bounds.

I haven't been able to think of a workaround that preserves the signature correctly; any suggestions would be appreciated.

**Comment by roganov** [comment] 2017-01-08 18:18
dupe of https://github.com/python/mypy/issues/1551

> I haven't been able to think of a workaround that preserves the signature correctly; any suggestions would be appreciated.

There is a workaround: https://github.com/python/mypy/issues/1551#issuecomment-253978622

**Comment by gvanrossum** [comment] 2017-01-08 18:33
Yeah, this problem is getting annoying (though it is remarkably hard to fix). But we only need one issue to track it.

**Closed by gvanrossum** 2017-01-08 18:33 UTC
