### ISSUE TITLE
Type of conditional expression is object

### ISSUE THREAD

**Issue by cjolowicz** [python/mypy#8074] opened 2019-12-04 16:08 UTC
The type of the following conditional expression is `object`:

```
s: str = "key=value"
a, b = s.split("=", 1) if "=" in s else ("key", "default")
# main.py:2: error: 'builtins.object' object is not iterable
```

It should be a union type instead, such as `Union[List[str], Tuple[str, str]]`.

(Note that `str.split` returns `List[str]` while the `else` branch has the type `Tuple[str, str]`.)

- [Gist](https://gist.github.com/4d8ef543c0a86d6966fa5722c792e345)
- [Playground](https://mypy-play.net/?mypy=latest&python=3.8&gist=4d8ef543c0a86d6966fa5722c792e345)

This is a follow-up to https://github.com/python/mypy/issues/3487.

**Comment by JukkaL** [comment] 2019-12-04 16:48
Alternatively, inferring `Sequence[str]` for the conditional expression would help in this case.

Inferring a union type would break backward compatibility. If the fallout is not too bad, it may still make sense.

**Comment by ilevkivskyi** [comment] 2019-12-04 17:08
Note that a good fix for https://github.com/python/mypy/issues/4975 may automatically lead to inferring `Sequence` here.

**Comment by cjolowicz** [comment] 2019-12-05 10:01
Here is a simpler reproduction:

```
a, b = [1, 2] if bool() else (1, 2)
```

**Comment by intgr** [comment] 2020-01-26 18:46
This issue is addressed in PR #8335.

**Comment by ethanhs** [comment] 2020-02-03 23:33
Closing as this was fixed by #8335. Thanks @intgr !

**Closed by ethanhs** 2020-02-03 23:33 UTC
Labels: false-positive, needs discussion, priority-1-normal, topic-union-types

**Comment by carlosporta** [comment] 2021-12-12 02:29
I am also facing a similar problem. 

    from typing import Protocol


    class Shape(Protocol):
        def area(self) -> str:
            ...


    class Circle:
        def area(self) -> str:
            return 'π * r²'


    class Square:
        def area(self) -> str:
            return 'w * l'


    class ShapeFactory:
        def create(self, shape_type: str) -> Shape:
            return Circle() if shape_type == 'circle' else Square()  # Here

Mypy shows this error message:
> error: Incompatible return value type (got "object", expected "Shape")

**Comment by intgr** [comment] 2021-12-12 14:38
@carlosporta That's a separate issue. Mypy tries to find the common base class of `Circle` and `Square`; since those two don't subclass `Shape` directly, the common base class happens to be `object`.

**Comment by carlosporta** [comment] 2021-12-12 16:19
@intgr, I understood what is happening, but this only happens using when using a conditional expression. If I change it to a conditional statement mypy identifies the shape protocol correctly as the return type.

This works perfectly, no error messages on mypy:

    class ShapeFactory:
        def create(self, shape_type: str) -> Shape:
            if shape_type == 'circle':
                return Circle() 
            else:
                return Square()

Should I create a new issue (Type of conditional expression is object) or am I facing something similar to this issue?

**Comment by intgr** [comment] 2021-12-12 16:39
@carlosporta I suspect an issue already exists for that, not totally sure. If you don't find one, feel free to open a new one.

But there's a historical background to why the ternary condition works as it does, I believe there's no easy fix: https://github.com/python/mypy/issues/3487 https://github.com/python/mypy/pull/5095

**Comment by carlosporta** [comment] 2021-12-12 20:34
@intgr, I did not find anything related to conditional expression and Protocol, so I created a new issue. If someone goes through a similar problem, here is the issue #11722.

**Comment by hsghori** [comment] 2022-03-01 23:24
I'm still seeing this issue on `mypy==0.910` (which FWICT should include https://github.com/python/mypy/pull/8335).

repro:
```py
from typing import Tuple, List, cast

x: List[Tuple[str, str]] = [("a", "b"), ("c", "d")]

c1, c2 = zip(*x) if len(x) > 0 else ([], [])
```

```
> $ mypy --version                                       
mypy 0.910
                                                                                              
> $ mypy ~/scratch/test_types.py 
/Users/haroon/scratch/test_types.py:5: error: "builtins.object" object is not iterable
Found 1 error in 1 file (checked 1 source file)
```

**Comment by intgr** [comment] 2022-03-02 09:42
@hsghori Please do not report bugs as comments on old bugs, unless you're absolutely certain it's the exact same issue. And when reporting bugs, ensure that your bug is reproducible in the latest git version, or at least latest release version, of the project.

I cannot reproduce this issue with mypy 0.931

```
% cat errobject.py
x: list[tuple[str, str]] = [("a", "b"), ("c", "d")]
c1, c2 = zip(*x) if len(x) > 0 else ([], [])
reveal_type(c1)
reveal_type(c2)
% mypy errobject.py
errobject.py:3: note: Revealed type is "typing.Sequence[Any]"
errobject.py:4: note: Revealed type is "typing.Sequence[Any]"
```
