### ISSUE TITLE
Error when inheriting from a generic dataclass with a generic attribute

### ISSUE THREAD

**Issue by drewm1980** [python/mypy#12063] opened 2022-01-25 10:01 UTC
**Bug Report**

When typechecking the following code:

```
from typing import Generic, TypeVar
from dataclasses import dataclass

T = TypeVar('T', int, str)

class C(Generic[T]):
    pass

@dataclass
class A(Generic[T]):
    x: C[T]

@dataclass
class B(A[int]):
    pass

B(x=C[int]())  # error: Argument "x" to "B" has incompatible type "C[int]"; expected "C[T]"
```

The equivalent code with the parent class NOT a data class:
```
class A_(Generic[T]):        
    x: C[T]

    def __init__(self, x: C[T]):   
        self.x = x

@dataclass
class B_(A_[int]):           
    pass                     

B_(x=C[int]())
```
Does not error.
If A_ is a normal class and B_ is marked as a dataclass, it also does not error. In other words it is the **parent** class that must be "un-dataclassed" as a workaround.

**Your Environment**

I have reproduced this on a recent version of mypy and python, but encountered it first in a python 3.6 environment, so it is not a new regression.

- Mypy version used: Reproduced in mypy 0.910
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): None
- Python version used: 3.9.7
- Operating system and version: Ubuntu, but this was reproduced in a conda environment, not with the system intepreter.

**Comment by drewm1980** [comment] 2022-01-25 10:02
Possible duplicate: https://github.com/python/mypy/issues/12063

**Comment by drewm1980** [comment] 2022-01-25 10:08
@natemcmaster thank you for resolving the previous similar bug, and thanks for your work on mypy. Life in python is so much better with static types.

**Comment by AlexWaygood** [comment] 2022-03-26 14:40
Closing as a duplicate of #10986

**Closed by AlexWaygood** 2022-03-26 14:40 UTC
Labels: bug, topic-inheritance, topic-dataclasses
