### ISSUE TITLE
Constrain/narrow literal type with 'in' checks

### ISSUE THREAD

**Issue by KotlinIsland** [python/mypy#9718] opened 2020-11-13 06:19 UTC
```py
from typing import Literal

a: Literal[1, 2, 3] = 2
assert a in (1, 2)
b: Literal[1, 2] = a
```
```
error: Incompatible types in assignment (expression has type "Union[Literal[1], Literal[2], Literal[3]]", variable has 
type "Union[Literal[1], Literal[2]]")
    b: Literal[1, 2] = a
                       ^
```

**Comment by prayatharth** [comment] 2020-11-13 18:20
What problem exactly  we are facing here ?

**Comment by JelleZijlstra** [comment] 2020-11-13 22:01
The report seems clear enough to me. It's a reasonable request; a PR would be welcome.

**Comment by hauntsaninja** [comment] 2023-11-12 22:20
Duplicate of https://github.com/python/mypy/issues/12535

**Closed by hauntsaninja** 2023-11-12 22:20 UTC
Labels: feature, priority-1-normal, topic-literal-types, topic-type-narrowing
