### ISSUE TITLE
`# type: ignore`d imports aren't picked up when they are added in incremental mode

### ISSUE THREAD

**Issue by msullivan** [python/mypy#4856] opened 2018-04-04 20:26 UTC
```
[case testSuppressedImportAdded1]
import a
[file a.py]
import foo  # type: ignore
[file foo.py.2]
2+'2'
[out]
[out2]
tmp/foo.py:1: error: Unsupported operand types for + ("int" and "str")
```

Reports no error in the second pass.

We *do* pick it up and properly update dependencies to it if it is specified on the command line, so this only comes up when following imports.

**Comment by ilevkivskyi** [comment] 2018-05-19 00:03
I think this is essentially a duplicate of https://github.com/python/mypy/issues/1910

**Closed by ilevkivskyi** 2018-05-19 00:03 UTC
Labels: bug, priority-1-normal, topic-incremental
