### ISSUE TITLE
Accept more generic types as `type[C]`

### ISSUE THREAD

**Issue by eltoder** [python/mypy#15662] opened 2023-07-13 17:37 UTC
**Feature**

It would be nice if the following worked:
```python
from typing import Annotated, List, TypeVar

T = TypeVar("T")

def convert(val: object, ty: type[T]) -> T:
    raise NotImplementedError

reveal_type(convert([1], list[int]))
reveal_type(convert([1], List[int]))
reveal_type(convert(None, int | None))
reveal_type(convert(1, Annotated[int]))
```

Currently the first 2 calls type check as expected, but the following 2 calls fail with
```
type_t.py:10: note: Revealed type is "<nothing>"
type_t.py:10: error: Argument 2 to "convert" has incompatible type "UnionType"; expected "type[<nothing>]"  [arg-type]
type_t.py:11: note: Revealed type is "<nothing>"
type_t.py:11: error: Argument 2 to "convert" has incompatible type "object"; expected "type[<nothing>]"  [arg-type]
```
Technically `int | None` is not a type object, but neither are `List[int]` and `list[int]`. However, they are type specifications recognized by type checkers, and it is clear what the meaning of the call is.

Another option is to provide a new type like `TypeSpec[T]` to use for cases where the value is not necessarily a type object but is a valid type specification, if extending `type` is deemed not appropriate. The difference may be too subtle, though, and `type` already accepts some values which are not types per the example above.

If this works, type checkers can remove special cases for `typing.cast` function. It can be annotated simply as
```python
def cast(typ: type[_T], val: Any) -> _T: ...
```

**Comment by AlexWaygood** [comment] 2023-07-13 17:41
Closing as a duplicate of #9003. See also #9773 for discussion on the broader theme here.

**Closed by AlexWaygood** 2023-07-13 17:41 UTC
Labels: feature, topic-type-form

**Comment by eltoder** [comment] 2023-07-13 20:20
Ah yeah, it's basically a duplicate of #9773. I failed to find it. Thanks.
