### ISSUE TITLE
New semantic analyzer: Name 'MyX' already defined (by an import)

### ISSUE THREAD

**Issue by gregbedwell** [python/mypy#7172] opened 2019-07-08 14:47 UTC
* Are you reporting a bug, or opening a feature request?
Reporting a bug

* Please insert below the code you are checking with mypy,
[reproducer.zip](https://github.com/python/mypy/files/3368891/reproducer.zip)

I'm somewhat new to mypy so I'm sorry if this is a user error.  If nothing else, the error message produced doesn't seem particularly helpful in narrowing down what to do fix it (or what section I might look in in the documentation).  This is an error from one of my projects that builds cleanly with `mypy --strict` as well as pylint, pyflakes, etc.  (with a few suppressions where the different tools take different views over things).  I've reduced it and suitably anonymized it.  There is a kind of circular import taking place where I'm importing the `MyX` class in `MyBase.py` and the `MyBase` class from `MyX.py` but it's never previously caused any issues.

* What is the actual behavior/output?
```
(py3.6) e:\tmp\mypy-issue>python --version
Python 3.6.8

(py3.6) e:\tmp\mypy-issue>mypy --version
mypy 0.711

(py3.6) e:\tmp\mypy-issue>mypy --strict .

(py3.6) e:\tmp\mypy-issue>mypy --strict --new-semantic-analyzer .
outer\inner\MyDerived2.py:1: error: Name 'MyX' already defined (by an import)
outer\inner\MyDerived2.py:8: error: Invalid type "outer.MyX"
```

If I remove the explicit import of `MyX` from `MyDerived2.py` then it obviously fails with:

```
(py3.6) e:\tmp\mypy-issue>mypy --strict --new-semantic-analyzer .
outer\inner\MyDerived2.py:8: error: Name 'MyX' is not defined
```

* What is the behavior/output you expect?
No error with the new semantic analyzer (same as with the old semantic analyzer).

**Comment by Cito** [comment] 2019-07-13 15:33
This looks a bit similar to my issue #7172.

It seems to happen sometimes when an object is called like its containing module.

**Comment by gregbedwell** [comment] 2019-07-13 15:59
I'm guessing you meant issue #7203 ?

**Comment by Cito** [comment] 2019-07-13 17:21
Sorry, yes, #7203.

**Comment by msullivan** [comment] 2019-07-15 20:32
With 0.720 we instead get a `error: Module "outer.inner.MyBase" is not valid as a type`

**Comment by msullivan** [comment] 2019-07-15 20:48
A minimized version:
```
[case testCycleRenames]
# flags: --new-semantic-analyzer
import MyX

[file MyX.py]
from inner import MyBase

class MyX:
    x: MyBase = None

[file inner/__init__.py]
from inner.MyBase import MyBase as MyBase

[file inner/MyBase.py]
from MyX import MyX

class MyBase:
    pass

[file inner/MyDerived1.py]
from inner.MyBase import MyBase

class MyDerived1(MyBase):
    pass
```

This minimized code I think will actually fail at runtime, though, executing `from MyX import MyX`
The original code is similarly dodgy, as one of the imports will actually get the submodule instead of the name.

Giving the classes the same name as modules is a worrisome practice, I think?

**Comment by ilevkivskyi** [comment] 2019-07-15 21:19
@msullivan 
Taking into account minimized repros for both issues I wonder if this is a duplicate (or other way around) of https://github.com/python/mypy/issues/7203 (module function with the same name as containing module -> class with the same name as containing module)?

**Comment by ilevkivskyi** [comment] 2019-08-12 12:34
Closing as a duplicate of #7203

**Closed by ilevkivskyi** 2019-08-12 12:34 UTC
