### ISSUE TITLE
Mypy: Argument 3 to "to_thread" has incompatible type "Path"; expected "_StrOrBytesPathT"

### ISSUE THREAD

**Issue by Helltraitor** [python/mypy#13193] opened 2022-07-19 21:55 UTC
**Bug Report**

I was trying to make async wrapper over `shutil.copyfile` and met a problem:
`Mypy: Argument 3 to "to_thread" has incompatible type "Path"; expected "_StrOrBytesPathT"`

**To Reproduce**

```Python
import asyncio
import shutil

from pathlib import Path


async def aiocopy_file(src: Path, dst: Path) -> None:
    await asyncio.to_thread(shutil.copyfile, src, dst, follow_symlinks=False)
    #                                             ~~~
```

**Expected Behavior**

`dst` argument is acceptable for using (At least I didn't see any problems in code below and while using `copyfile` in console).
But this code passes check:
```Python
def copy(src: Path, dst: Path) -> None:
    shutil.copyfile(src, dst)
```

**Actual Behavior**

For some reason, MyPy says that third argument (which is second for `shutil.copyfile`) is wrong type.

**Your Environment**

- Mypy version used: 0.971
- Mypy command-line flags: I use external tool but doesn't provide any special arguments
- Mypy configuration options from `mypy.ini` (and other config files): no file
- Python version used: 3.10.4
- Operating system and version: Windows 10 Pro (19044.1826 21H1)
- PyCharm CE:
- - PyCharm 2022.1.3 (Community Edition)
- - Build #PC-221.5921.27, built on June 22, 2022
- - Runtime version: 11.0.15+10-b2043.56 amd64
- - VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

**Warning**
I'm not pro with mypy, so try to reproduce this bug and text me if you cannot for some reasons.

**Comment by AlexWaygood** [comment] 2022-07-20 13:13
Duplicate of #12278

**Closed by AlexWaygood** 2022-07-20 13:13 UTC
Labels: bug, topic-paramspec
