### ISSUE TITLE
Error when type annotation shadows import "Invalid type ..."

### ISSUE THREAD

**Issue by asottile** [python/mypy#6188] opened 2019-01-13 21:50 UTC
```python
import datetime
from typing import NamedTuple


class C(NamedTuple):
    datetime: datetime.datetime


print(C.__annotations__)
```

```console
$ python t.py
OrderedDict([('datetime', <class 'datetime.datetime'>)])
```

```console
$ mypy --version
mypy 0.650
$ mypy t.py
t.py:6: error: Invalid type "t.C.datetime"
```

I ended up renaming my attribute, though as far as I can tell this is legal code that mypy is rejecting

**Comment by ilevkivskyi** [comment] 2019-01-14 09:38
This is essentially a duplicate of https://github.com/python/mypy/issues/3775, in particular see this comment https://github.com/python/mypy/issues/3775#issuecomment-323542625

**Closed by ilevkivskyi** 2019-01-14 09:38 UTC
