### ISSUE TITLE
Mypy loses track of module fields on assignment

### ISSUE THREAD

**Issue by rowillia** [python/mypy#2435] opened 2016-11-11 00:30 UTC
test_alias.py:
```python
import requests

class Foo(object):
    def __init__(self):
        self.requests = requests
    def get(path):
        self.requests.get(path)
```

Command:
```
mypy test_alias.py
```

Result:
```
test_alias.py:7: error: "module" has no attribute "get"
```

Mypy appears to be treating `original` as a generic module as opposed to the `requests` module specifically.

**Comment by JukkaL** [comment] 2017-01-16 11:37
This is a duplicate of #1741.

**Closed by JukkaL** 2017-01-16 11:37 UTC
