### ISSUE TITLE
def f() -> AnyStr fails if f returns a str

### ISSUE THREAD

**Issue by andymwood** [python/mypy#7180] opened 2019-07-09 11:38 UTC
I expect mypy to allow the following code to pass:
```python
from typing import AnyStr

def f() -> AnyStr:
    return "abc"
```

Instead, I get this:
```bash
mypy anystr.py
anystr.py:5: error: Incompatible return value type (got "str", expected "bytes")
```

I'm using Python 3.6 and mypy 0.711

**Comment by JelleZijlstra** [comment] 2019-07-09 14:43
Did you mean to use `def f() -> Union[str, bytes]:`? What you write doesn't really make sense because there's nothing to constrain the value of the TypeVar.

**Comment by andymwood** [comment] 2019-07-09 16:18
Thanks for that. It seems I'd misunderstood something. However, there's another possible bug which might have misled me into using `AnyStr`.

The following is closer to what I was originally trying to do:
```python
import os
from typing import Dict, Iterable


def get_files() -> Iterable[os.DirEntry]:
    for f in os.scandir():
        yield f


def get_dict() -> Dict[str, str]:
    return {"a": "b"}


files = get_files()
x = get_dict()
for key in map(os.path.realpath, files):
    val = x.get(key)
    print(key, val)
```

mypy returns this error:
```text
anystr.py:17: error: Argument 1 to "get" of "Mapping" has incompatible type "AnyStr"; expected "str"
```

The error goes away if I change `map(os.realpath, files)` to a list or generator comprehension, or call `os.path.realpath` inside the loop like so:
```
for f in files:
    key = os.path.realpath(f)
```

**Comment by JelleZijlstra** [comment] 2019-07-09 16:35
I think this is because you're missing a type argument on `os.DirEntry`; if you can mypy with `--disallow-any-generics` (a very useful option), mypy would likely tell you that. Try making `get_files()` return `"Iterator[os.DirEntry[str]]"` (you need the quotes because DirEntry is not generic at runtime).

**Comment by andymwood** [comment] 2019-07-10 07:02
Following your advice, I get this:
```bash
mypy --disallow-any-generics anystr.py
anystr.py:16: error: Argument 1 to "map" has incompatible type overloaded function; expected "Callable[[DirEntry[str]], AnyStr]"
anystr.py:17: error: Argument 1 to "get" of "Mapping" has incompatible type "AnyStr"; expected "str"
```

**Comment by ilevkivskyi** [comment] 2019-08-12 11:47
The original problem is not a bug, as Jelle explained. The second issue is a duplicate of https://github.com/python/mypy/issues/1317, passing one generic function (`os.path.realpath` in this case) as an argument to another generic function (`map` in this case) doesn't really work unfortunately.

**Closed by ilevkivskyi** 2019-08-12 11:47 UTC
