### ISSUE TITLE
"too many class plugin hook passes" error on `dataclass` with `Final` property that uses `field`

### ISSUE THREAD

**Issue by DetachHead** [python/mypy#13377] opened 2022-08-11 05:54 UTC
```py
from dataclasses import dataclass, field
from typing import Final

@dataclass
class Foo:
    a: Final = field(default=1)
```
```
Traceback (most recent call last):
  File "/opt/python3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/python3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/__main__.py", line 34, in <module>
    console_entry()
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/__main__.py", line 12, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "mypy/main.py", line 96, in main
  File "mypy/main.py", line 173, in run_build
  File "mypy/build.py", line 154, in build
  File "mypy/build.py", line 230, in _build
  File "mypy/build.py", line 2729, in dispatch
  File "mypy/build.py", line 3087, in process_graph
  File "mypy/build.py", line 3179, in process_stale_scc
  File "mypy/semanal_main.py", line 86, in semantic_analysis_for_scc
  File "mypy/semanal_main.py", line 404, in apply_class_plugin_hooks
AssertionError: Internal error: too many class plugin hook passes
```
[playground](https://mypy-play.net/?mypy=latest&python=3.10&gist=af129da8420a93c4c256d295f674e5c4)

related: #10090

**Comment by AlexWaygood** [comment] 2022-08-11 07:42
Although the repro is slightly different, this is exactly the same traceback as https://github.com/python/mypy/issues/10090#issuecomment-1130175070, so I'm closing it as a duplicate of #10090 so that we can keep the discussion all in one place.

**Closed by AlexWaygood** 2022-08-11 07:42 UTC
Labels: crash, topic-final, topic-dataclasses
