### ISSUE TITLE
Internal mypy error (failed `assert supertype is not None`) on parametrized class

### ISSUE THREAD

**Issue by Dutcho** [python/mypy#13059] opened 2022-07-03 14:32 UTC
I'm playing around with computable unbound sets, i.e. `{1,2,3,...}` (in which `...` is not `Ellipsis`, but 'etc.') and its kin.
On the latest `PyPI` version (0.961), I get 
```
<source>.py:40: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
If this issue continues with mypy master, please report a bug at https://github.com/python/mypy/issues
version: 0.961
discours1.py:40: : note: please use --show-traceback to print a traceback when reporting a bug
```
source file gist URL: https://gist.github.com/0b2320a6eb6223687f490feadb263d2d

The same happens on master, playground URL: https://mypy-play.net/?mypy=master&python=3.10&flags=show-traceback&gist=0b2320a6eb6223687f490feadb263d2d

**WITHOUT** the `test()` function (so just definition, not use of `ComputedSet`), `mypy` reports clean (also in `--strict`). **WITH** instantation of `ComputedSet[...](...)`, `mypy` stops with error.

Pasting the master traceback below:
```
Failed (exit code: 2) (7787 ms)
Traceback (most recent call last):
  File "/opt/python3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/python3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/__main__.py", line 34, in <module>
    console_entry()
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/__main__.py", line 12, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/main.py", line 96, in main
    res, messages, blockers = run_build(sources, options, fscache, t0, stdout, stderr)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/main.py", line 173, in run_build
    res = build.build(sources, options, None, flush_errors, fscache, stdout, stderr)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/build.py", line 154, in build
    result = _build(
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/build.py", line 230, in _build
    graph = dispatch(sources, manager, stdout)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/build.py", line 2729, in dispatch
    process_graph(graph, manager)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/build.py", line 3087, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/build.py", line 3185, in process_stale_scc
    graph[id].type_check_first_pass()
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/build.py", line 2180, in type_check_first_pass
    self.type_checker().check_first_pass()
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/checker.py", line 325, in check_first_pass
    self.accept(d)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/checker.py", line 431, in accept
    stmt.accept(self)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/nodes.py", line 748, in accept
    return visitor.visit_func_def(self)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/checker.py", line 782, in visit_func_def
    self._visit_func_def(defn)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/checker.py", line 786, in _visit_func_def
    self.check_func_item(defn, name=defn.name)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/checker.py", line 848, in check_func_item
    self.check_func_def(defn, typ, name)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/checker.py", line 1033, in check_func_def
    self.accept(item.body)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/checker.py", line 431, in accept
    stmt.accept(self)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/nodes.py", line 1100, in accept
    return visitor.visit_block(self)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/checker.py", line 2178, in visit_block
    self.accept(s)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/checker.py", line 431, in accept
    stmt.accept(self)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/nodes.py", line 1166, in accept
    return visitor.visit_assignment_stmt(self)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/checker.py", line 2220, in visit_assignment_stmt
    self.check_assignment(s.lvalues[-1], s.rvalue, s.type is None, s.new_syntax)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/checker.py", line 2414, in check_assignment
    rvalue_type = self.expr_checker.accept(rvalue)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/checkexpr.py", line 3998, in accept
    typ = node.accept(self)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/nodes.py", line 1761, in accept
    return visitor.visit_call_expr(self)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/checkexpr.py", line 306, in visit_call_expr
    return self.visit_call_expr_inner(e, allow_none_return=allow_none_return)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/checkexpr.py", line 355, in visit_call_expr_inner
    callee_type = get_proper_type(self.accept(e.callee, type_context, always_allow_any=True))
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/checkexpr.py", line 3998, in accept
    typ = node.accept(self)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/nodes.py", line 1814, in accept
    return visitor.visit_index_expr(self)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/checkexpr.py", line 2925, in visit_index_expr
    result = self.visit_index_expr_helper(e)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/checkexpr.py", line 2935, in visit_index_expr_helper
    return self.accept(e.analyzed)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/checkexpr.py", line 3998, in accept
    typ = node.accept(self)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/nodes.py", line 2219, in accept
    return visitor.visit_type_application(self)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/checkexpr.py", line 3191, in visit_type_application
    return self.apply_type_arguments_to_callable(tp, tapp.types, tapp)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/checkexpr.py", line 3272, in apply_type_arguments_to_callable
    return self.apply_generic_arguments(tp, args, ctx)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/checkexpr.py", line 2040, in apply_generic_arguments
    return applytype.apply_generic_arguments(callable, types,
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/applytype.py", line 89, in apply_generic_arguments
    target_type = get_target_type(
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/applytype.py", line 53, in get_target_type
    if not mypy.subtypes.is_subtype(type, upper_bound):
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/subtypes.py", line 97, in is_subtype
    return _is_subtype(left, right,
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/subtypes.py", line 158, in _is_subtype
    return left.accept(SubtypeVisitor(orig_right,
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/types.py", line 1173, in accept
    return visitor.visit_instance(self)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/subtypes.py", line 273, in visit_instance
    if base._promote and any(self._is_subtype(p, self.right)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/subtypes.py", line 273, in <genexpr>
    if base._promote and any(self._is_subtype(p, self.right)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/subtypes.py", line 217, in _is_subtype
    return is_subtype(left, right,
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/subtypes.py", line 97, in is_subtype
    return _is_subtype(left, right,
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/subtypes.py", line 158, in _is_subtype
    return left.accept(SubtypeVisitor(orig_right,
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/types.py", line 1173, in accept
    return visitor.visit_instance(self)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/subtypes.py", line 273, in visit_instance
    if base._promote and any(self._is_subtype(p, self.right)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/subtypes.py", line 273, in <genexpr>
    if base._promote and any(self._is_subtype(p, self.right)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/subtypes.py", line 217, in _is_subtype
    return is_subtype(left, right,
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/subtypes.py", line 97, in is_subtype
    return _is_subtype(left, right,
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/subtypes.py", line 158, in _is_subtype
    return left.accept(SubtypeVisitor(orig_right,
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/types.py", line 1173, in accept
    return visitor.visit_instance(self)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/subtypes.py", line 305, in visit_instance
    if right.type.is_protocol and is_protocol_implementation(left, right):
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/mypy/subtypes.py", line 656, in is_protocol_implementation
    assert supertype is not None
AssertionError: 
main.py:40: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.970+dev.7e38877750c04abfd436e6ad98da23d6deca4e8f
main.py:40: : note: use --pdb to drop into pdb
```

**Comment by denballakh** [comment] 2022-07-03 15:09
Smaller reproducer:
```py

from typing import Protocol, TypeVar

class SomeProtocol(Protocol):
    T = TypeVar('T') # if i remove this line, everything is ok
    pass

ET = TypeVar('ET', bound=SomeProtocol)

class SomeGenericClass(list[ET]):
    pass

# crash here:
SomeGenericClass[int]
```
I can reproduce it on `mypy 0.961`

**Comment by AlexWaygood** [comment] 2022-07-03 15:11
> Smaller reproducer:
> 
> ```python
> from typing import Protocol, TypeVar
> 
> class SomeProtocol(Protocol):
>     T = TypeVar('T') # if i remove this line, everything is ok
>     pass
> 
> ET = TypeVar('ET', bound=SomeProtocol)
> 
> class SomeGenericClass(list[ET]):
>     pass
> 
> # crash here:
> SomeGenericClass[int]
> ```
> 
> I can reproduce it on `mypy 0.961`

Thanks @denballakh, that's super helpful! 😀

**Comment by AlexWaygood** [comment] 2022-07-03 15:13
Duplicate of #12337

**Closed by AlexWaygood** 2022-07-03 15:13 UTC
Labels: crash, topic-protocols
