### ISSUE TITLE
INTERNAL_ERROR with cyclic import

### ISSUE THREAD

**Issue by itsadok** [python/mypy#6094] opened 2018-12-20 14:40 UTC
To reproduce:

```
mkdir subdir
cat > subdir/a.py <<END
import b
class A:
    pass
END

cat > subdir/b.py <<END
import a
o = a.A()
print(o.x)
END

touch subdir/__init__.py
MYPYPATH=subdir mypy subdir/b.py
```

Output:
```
subdir/b.py:5: error: "A" has no attribute "x"
subdir/b.py:5: error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues version: 0.650
subdir/b.py:5: : note: please use --show-traceback to print a traceback when reporting a bug
```

Traceback:
```
Traceback (most recent call last):
  File "/usr/local/bin/mypy", line 11, in <module>
    sys.exit(console_entry())
  File "~/.local/lib/python3.6/site-packages/mypy/__main__.py", line 7, in console_entry
    main(None)
  File "~/.local/lib/python3.6/site-packages/mypy/main.py", line 92, in main
    res = build.build(sources, options, None, flush_errors, fscache)
  File "~/.local/lib/python3.6/site-packages/mypy/build.py", line 156, in build
    result = _build(sources, options, alt_lib_path, flush_errors, fscache)
  File "~/.local/lib/python3.6/site-packages/mypy/build.py", line 206, in _build
    graph = dispatch(sources, manager)
  File "~/.local/lib/python3.6/site-packages/mypy/build.py", line 2232, in dispatch
    process_graph(graph, manager)
  File "~/.local/lib/python3.6/site-packages/mypy/build.py", line 2532, in process_graph
    process_stale_scc(graph, scc, manager)
  File "~/.local/lib/python3.6/site-packages/mypy/build.py", line 2655, in process_stale_scc
    graph[id].type_check_first_pass()
  File "~/.local/lib/python3.6/site-packages/mypy/build.py", line 1791, in type_check_first_pass
    self.type_checker().check_first_pass()
  File "~/.local/lib/python3.6/site-packages/mypy/checker.py", line 282, in check_first_pass
    self.accept(d)
  File "~/.local/lib/python3.6/site-packages/mypy/checker.py", line 393, in accept
    stmt.accept(self)
  File "~/.local/lib/python3.6/site-packages/mypy/nodes.py", line 928, in accept
    return visitor.visit_expression_stmt(self)
  File "~/.local/lib/python3.6/site-packages/mypy/checker.py", line 2623, in visit_expression_stmt
    self.expr_checker.accept(s.expr, allow_none_return=True, always_allow_any=True)
  File "~/.local/lib/python3.6/site-packages/mypy/checkexpr.py", line 3063, in accept
    typ = self.visit_call_expr(node, allow_none_return=True)
  File "~/.local/lib/python3.6/site-packages/mypy/checkexpr.py", line 229, in visit_call_expr
    return self.visit_call_expr_inner(e, allow_none_return=allow_none_return)
  File "~/.local/lib/python3.6/site-packages/mypy/checkexpr.py", line 296, in visit_call_expr_inner
    ret_type = self.check_call_expr_with_callee_type(callee_type, e, fullname, object_type)
  File "~/.local/lib/python3.6/site-packages/mypy/checkexpr.py", line 633, in check_call_expr_with_callee_type
    object_type=object_type)[0]
  File "~/.local/lib/python3.6/site-packages/mypy/checkexpr.py", line 702, in check_call
    callee, args, arg_kinds, formal_to_actual)
  File "~/.local/lib/python3.6/site-packages/mypy/checkexpr.py", line 842, in infer_arg_types_in_context
    res[ai] = self.accept(args[ai], callee.arg_types[i])
  File "~/.local/lib/python3.6/site-packages/mypy/checkexpr.py", line 3067, in accept
    typ = node.accept(self)
  File "~/.local/lib/python3.6/site-packages/mypy/nodes.py", line 1373, in accept
    return visitor.visit_member_expr(self)
  File "~/.local/lib/python3.6/site-packages/mypy/checkexpr.py", line 1694, in visit_member_expr
    result = self.analyze_ordinary_member_access(e, is_lvalue)
  File "~/.local/lib/python3.6/site-packages/mypy/checkexpr.py", line 1709, in analyze_ordinary_member_access
    original_type=original_type, chk=self.chk)
  File "~/.local/lib/python3.6/site-packages/mypy/checkmember.py", line 105, in analyze_member_access
    original_type=original_type, chk=chk)
  File "~/.local/lib/python3.6/site-packages/mypy/checkmember.py", line 319, in analyze_member_var_access
    return msg.has_no_attr(original_type, itype, name, node)
  File "~/.local/lib/python3.6/site-packages/mypy/messages.py", line 492, in has_no_attr
    member, extra), context)
  File "~/.local/lib/python3.6/site-packages/mypy/messages.py", line 198, in fail
    self.report(msg, context, 'error', file=file, origin=origin)
  File "~/.local/lib/python3.6/site-packages/mypy/messages.py", line 193, in report
    origin_line=origin.get_line() if origin else None)
  File "~/.local/lib/python3.6/site-packages/mypy/errors.py", line 262, in report
    self.add_error_info(info)
  File "~/.local/lib/python3.6/site-packages/mypy/errors.py", line 283, in add_error_info
    self._add_error_info(file, info)
  File "~/.local/lib/python3.6/site-packages/mypy/errors.py", line 265, in _add_error_info
    assert file not in self.flushed_files
AssertionError: 
subdir/b.py:5: : note: use --pdb to drop into pdb
```

**Comment by ilevkivskyi** [comment] 2018-12-20 16:14
Duplicate of https://github.com/python/mypy/issues/4881

(Also the cause is not an import cycle, but a file that appears both in command line and `mypy_path`.)

**Closed by ilevkivskyi** 2018-12-20 16:14 UTC
