### ISSUE TITLE
Incorrect type inference in "if ham and spam is None: spam = ham; spam.startswith('/')"

### ISSUE THREAD

**Issue by elprans** [python/mypy#4321] opened 2017-12-04 21:06 UTC
Given the following code (**test.py**):

```python
import typing
import urllib.parse


def _parse_dsn(*, dsn, database) -> dict:
    if dsn:
        parsed = urllib.parse.urlparse(dsn)
        if parsed.path and database is None:
            database = parsed.path
            if database.startswith('/'):  # this is line 10
                database = database[1:]

    return dict(database=database)
```

`$ mypy test.py` fails with:
```
test.py:10: error: "None" has no attribute "startswith"
test.py:11: error: Value of type "None" is not indexable
```

despite `database` provably not being `None`.

**Comment by ilevkivskyi** [comment] 2017-12-05 00:29
I think this is essentially a duplicate of https://github.com/python/mypy/issues/3526 (although a bit special since in this case initial type is also ``Any``).

**Comment by ethanhs** [comment] 2017-12-05 02:01
Agreed. Closing as duplicate of #3526.

**Closed by ethanhs** 2017-12-05 02:01 UTC
