### ISSUE TITLE
AsyncGenerator return type incompatible with supertype if parent body is empty/abstract

### ISSUE THREAD

**Issue by romantolkachyov** [python/mypy#5959] opened 2018-11-27 14:29 UTC
> Are you reporting a bug, or opening a feature request?

Reporting a bug

> Please insert below the code you are checking with mypy

```python
from typing import AsyncGenerator


class MyType:
    pass


class MyAbstract:
    async def some_abstract_method(self) -> AsyncGenerator[MyType, None]:
        pass


class MyImplementation(MyAbstract):
    async def some_abstract_method(self) -> AsyncGenerator[MyType, None]:
        for x in range(1):
            yield MyType()
```

> What is the actual behavior/output?

```
mypy_problem.py:14: error: Return type of "some_abstract_method" incompatible with supertype "MyAbstract"
```

> What is the behavior/output you expect?

It is a valid code and checks must be passed.

> What are the versions of mypy and Python you are using?

```
Python 3.7.0
mypy 0.641
```
> Do you see the same issue after installing mypy from Git master?

Yes.

> What are the mypy flags you are using? (For example --strict-optional)

`ignore_missing_imports=True` used (configured through `mypy.ini`).

**Comment by ilevkivskyi** [comment] 2018-11-27 15:31
Duplicate of https://github.com/python/mypy/issues/5070 (currently use `if False: yield`).

**Closed by ilevkivskyi** 2018-11-27 15:31 UTC

**Comment by romantolkachyov** [comment] 2018-11-27 15:43
Thanks, it helps (if someone found this issue instead of the original one).
