### ISSUE TITLE
Improper inference via length for a union of tuples

### ISSUE THREAD

**Issue by Fulguritude** [python/mypy#12816] opened 2022-05-19 18:06 UTC
**Bug Report**

mypy incorrectly infers a `Tuple index out of range` error when discriminating between two tuples in a union via their length, even when using a literal `int` when analyzing the length of the tuple instance.

**To Reproduce**
```py
from typing import Tuple, Union

Tuple3 = Tuple[str, str, str]
Tuple4 = Tuple[str, str, str, str]
Tuples = Union[Tuple3, Tuple4]

def test_tuples(my_tuple: Tuples) -> None:
    if len(my_tuple) >= 4:
        my_tuple[3]  # misc - Tuple index out of range
```

**Expected Behavior**
Not returning an "index out of range" error, when it is clearly impossible for it to be the case.

**Actual Behavior**
mypy infers `misc - Tuple index out of range`

**Your Environment**

- Mypy version used: 0.950 (compiled: yes)
- Mypy command-line flags: N/A
- Mypy configuration options from `mypy.ini` (and other config files): N/A
- Python version used: 3.10
- Operating system and version: pop-os 22.04

**Comment by JelleZijlstra** [comment] 2022-05-19 18:26
Duplicate of #1178

**Closed by JelleZijlstra** 2022-05-19 18:26 UTC
Labels: feature, topic-type-narrowing
