### ISSUE TITLE
(🐞) mypyc crashes with class defined within function

### ISSUE THREAD

**Issue by KotlinIsland** [python/mypy#16235] opened 2023-10-08 03:58 UTC
```py
def a():
    class B:
        pass
```
```
> mypyc test.py
Traceback (most recent call last):
  File "mypyc/irbuild/builder.py", line 263, in accept
  File "mypy/nodes.py", line 1141, in accept
  File "mypyc/irbuild/visitor.py", line 167, in visit_class_def
  File "mypyc/irbuild/classdef.py", line 88, in transform_class_def
test.py:2: KeyError: <TypeInfo test.B@2>
```

- Similar to #15716

**Comment by JelleZijlstra** [comment] 2023-10-08 04:25
Duplicate of mypyc/mypyc#864.

**Closed by JelleZijlstra** 2023-10-08 04:25 UTC
Labels: crash, topic-mypyc
