### ISSUE TITLE
Discriminated/narrowed Union type of closure’s upvalues does not carry into closure

### ISSUE THREAD

**Issue by amarshall** [python/mypy#5852] opened 2018-10-29 04:03 UTC
Probably best illustrated with an example:

```python
from typing import TypeVar, Union

_T = TypeVar('_T')
_U = TypeVar('_U')

def f(x: Union[_T, int]) -> None:
    if isinstance(x, int):
        reveal_type(x)  # int
        def g1() -> None:
            reveal_type(x)  # Union[_T, int] (but expect int)
    else:
        reveal_type(x)  # _T
        def g2() -> None:
            reveal_type(x)  # Union[_T, int] (but expect _T)
```

The same also happens with `Optional` and `if x is None`, but I presume the type-checker doesn’t treat this as any different, anyway.

Using:

- Python 3.7.0
- mypy 0.641
- mypy config:
  ```cfg
  [mypy]
  check_untyped_defs = True
  disallow_any_decorated = True
  disallow_any_expr = True
  disallow_any_unimported = True
  disallow_incomplete_defs = True
  disallow_subclassing_any = True
  disallow_untyped_calls = True
  disallow_untyped_decorators = True
  disallow_untyped_defs = True
  warn_return_any = True
  warn_unused_ignores = True
  ```

**Comment by ilevkivskyi** [comment] 2018-10-29 09:11
Duplicate of https://github.com/python/mypy/issues/2608

**Closed by ilevkivskyi** 2018-10-29 09:11 UTC

**Comment by amarshall** [comment] 2018-10-29 13:07
Thanks for finding the duplicate; I searched but couldn’t find it myself :)
