### ISSUE TITLE
Multiple assignments to `_` with conflicting types in loops and comprehension results in error

### ISSUE THREAD

**Issue by posita** [python/mypy#4456] opened 2018-01-10 22:50 UTC
The following results in MyPy complaining `Incompatible types in assignment (expression has type "unicode", variable has type "int")`:

```
ints_n_txt = [(1, u'1'), (2, u'2'), (3, u'3')]  # type: List[Tuple[int, Text]]
for _, _ in ints_n_txt:  # _ has two different types
    pass
```

Unsurprisingly, this affects collection comprehension as well:

```
spam = [True for _, _ in ints_n_txt]  # type: List[bool]
```

Explicitly declaring the type of `_` as `Any` "fixes" the error for the `for` loop:

```
_ = None  # type: Any
for _, _ in …
```

But that doesn't work for collection comprehension. (MyPy will still complain, and some linters will  too. For example, `flake8` will complain that `F812 - list comprehension redefines '_' from line …`.)

These seem to work, but both look a little awkward:

```
for (
            _,  # type: ignore
            _,  # type: ignore
        ) in ints_n_txt:
    pass

spam = [
    True for (
        _,  # type: ignore
        _,  # type: ignore
    ) in ints_n_txt
]  # type: List[bool]
```

This may be as intended. I'm wondering if treating `_` in _all_ scopes as type `Any` by default is a bad idea? (Apologies if this is more appropriately filed as an issue with `typeshed`.)

**Comment by ilevkivskyi** [comment] 2018-01-10 23:01
Yes, this idea appeared before, so this is a duplicate of https://github.com/python/mypy/issues/465

**Closed by ilevkivskyi** 2018-01-10 23:01 UTC

**Comment by posita** [comment] 2018-01-10 23:38
Oh jeez! Apologies for missing that! 😞

**Comment by ilevkivskyi** [comment] 2018-01-11 08:02
No problem!
