### ISSUE TITLE
"maximum semantic analysis iteration count" when combining nested dataclass and undefined field.

### ISSUE THREAD

**Issue by jonathanslenders** [python/mypy#11645] opened 2021-11-30 10:06 UTC
**Bug Report**

The following little snippet causes the following error:

> test.py: error: INTERNAL ERROR: maximum semantic analysis iteration count reached

**To Reproduce**

Create the following file. I know several things are *not* correct in this file, but that's absolutely the purpose. 

```python
from dataclasses import dataclass

def func() -> None:
    @dataclass
    class RequestWriter:
        field: bool

        def func() -> None:
            something_not_defined
```
Run mypy over it. This is the output:

```python
 $ mypy client1.py
Deferral trace:
    client1:11
    client1:11
    client1:11
    client1:11
    client1:11
    client1:11
    client1:11
    client1:11
    client1:11
    client1:11
    client1:11
    client1:11
    client1:11
    client1:11
    client1:11
    client1:11
    client1:11
    client1:11
    client1:11
client1.py: error: INTERNAL ERROR: maximum semantic analysis iteration count reached
client1.py:10: error: Method must have at least one argument
Found 2 errors in 1 file (errors prevented further checking)
```
**Expected Behavior**

Mypy should probably point out that:
- ``something_not_defined`` is not defined.

**Your Environment**

- Mypy version used: 0.910
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): None
- Python version used: 3.9.5
- Operating system and version: Ubuntu 20.04.1

**Comment by AlexWaygood** [comment] 2022-03-26 07:50
Thanks for the report! I'm going to close this as a duplicate of #8703

**Closed by AlexWaygood** 2022-03-26 07:50 UTC
Labels: crash, topic-dataclasses
