### ISSUE TITLE
Bad 'Incompatible types in assignment' error for a type alias containing Union

### ISSUE THREAD

**Issue by davire** [python/mypy#2485] opened 2016-11-24 13:46 UTC
There is this code that doesn't typecheck and I don't understand why:
```python
W = Dict[str, Union[bool,int, float]]


def test2() -> W:
    rest = {}  # type: W
    return rest
```

However it typechecks if I remove either one of `bool`, `int`, `float` in the type `W`

**Comment by rwbarton** [comment] 2016-11-24 16:37
Indeed, it's a bug. Duplicate of #1850.

**Closed by rwbarton** 2016-11-24 16:37 UTC
