### ISSUE TITLE
1.7.0 crashes with `Cannot find component 'Buffer' for 'typing_extensions.Buffer'

### ISSUE THREAD

**Issue by jrraymond** [python/mypy#16463] opened 2023-11-11 18:21 UTC
**Crash Report**

Mypy crashes with an assertion error

**Traceback**

```
  File "mypy/main.py", line 95, in main
  File "mypy/main.py", line 174, in run_build
  File "mypy/build.py", line 194, in build
  File "mypy/build.py", line 277, in _build
  File "mypy/build.py", line 2923, in dispatch
  File "mypy/build.py", line 3313, in process_graph
  File "mypy/build.py", line 3394, in process_fresh_modules
  File "mypy/build.py", line 2120, in fix_cross_refs
  File "mypy/fixup.py", line 53, in fixup_module
  File "mypy/fixup.py", line 136, in visit_symbol_table
  File "mypy/fixup.py", line 73, in visit_type_info
  File "mypy/fixup.py", line 138, in visit_symbol_table
  File "mypy/nodes.py", line 774, in accept
  File "mypy/fixup.py", line 146, in visit_func_def
  File "mypy/types.py", line 1867, in accept
  File "mypy/fixup.py", line 242, in visit_callable_type
  File "mypy/types.py", line 2658, in accept
  File "mypy/fixup.py", line 332, in visit_union_type
  File "mypy/types.py", line 1355, in accept
  File "mypy/fixup.py", line 209, in visit_instance
  File "mypy/fixup.py", line 344, in lookup_fully_qualified_typeinfo
  File "mypy/lookup.py", line 49, in lookup_fully_qualified
AssertionError: Cannot find component 'Buffer' for 'typing_extensions.Buffer'
```

**To Reproduce**

I don't have a small reproducible example, but does appear to be related to whether `typing_extensions` is imported.

**Your Environment**

- typing_extensions version: 4.3.0
- Mypy version used: 1.7.0
- Mypy command-line flags:
- Mypy configuration options from `mypy.ini` (and other config files):
- Python version used: 3.10.9
- Operating system and version: RHEL 7.9

The `typing_extensions` extension requirement may need to be updated to `4.6.0`: https://github.com/python/mypy/blob/master/mypy-requirements.txt#L2

4.6.0 added `Buffer`: https://github.com/python/typing_extensions/blob/main/CHANGELOG.md#release-460-may-22-2023

**Comment by ilevkivskyi** [comment] 2023-11-11 19:10
Is this reproducible for you? If yes, could you please check if forcefully installing newer `typing_extensions` (e.g. using `pip install -U`) fixes the issue?

**Comment by christian-steinmeyer** [comment] 2023-11-13 14:14
In my case, this seems to have solved the issue (although I was running mypy through pre-commit, so I had to uninstall the hook garbage collect and then install again).

**Comment by hauntsaninja** [comment] 2024-06-22 08:27
Closing since there isn't a repro, please re-open if you can find one! This may be related to cache, so a repro might look like "run mypy, do something, run mypy again"

**Closed by hauntsaninja** 2024-06-22 08:27 UTC
Labels: crash
