### ISSUE TITLE
Error when trying to construct TypedDict with `**` unpacking

### ISSUE THREAD

**Issue by Dreamsorcerer** [python/mypy#8883] opened 2020-05-25 17:12 UTC
Am I asking too much of Mypy, or am I doing something wrong with this code?

I get `Incompatible types in assignment (expression has type "Dict[str, str]", variable has type "Union[_TokenParamsPassword, _TokenParamsRefresh]")  [assignment]` on the assignment in this function:
```
    async def _get_token(self, data: AuthParams) -> TokenResponse:
        request_data: TokenParams = {
            'client_id': OAUTH_CLIENT_ID,
            'client_secret': OAUTH_CLIENT_SECRET,
            **data
        }
```

The type definitions are:
```
class _AuthParamsPassword(TypedDict):
    grant_type: Literal["password"]
    email: str
    password: str
class _AuthParamsRefresh(TypedDict):
    grant_type: Literal["refresh_token"]
    refresh_token: str
AuthParams = Union[_AuthParamsPassword, _AuthParamsRefresh]

class _TokenParamsPassword(TypedDict):
    grant_type: Literal["password"]
    client_id: str
    client_secret: str
    email: str
    password: str
class _TokenParamsRefresh(TypedDict):
    grant_type: Literal["refresh_token"]
    client_id: str
    client_secret: str
    refresh_token: str
TokenParams = Union[_TokenParamsPassword, _TokenParamsRefresh]
```

So, I'm using the AuthParam, which is a subset of keys of TokenParam, and then building a full TokenParam dictionary from that. Is there a better way to do this?

**Comment by AlexWaygood** [comment] 2022-05-03 14:29
Closing as a duplicate of #9408, which is a more recent issue but has a simpler repro

**Closed by AlexWaygood** 2022-05-03 14:29 UTC
Labels: feature, topic-typed-dict, priority-2-low
