### ISSUE TITLE
Internal ERROR

### ISSUE THREAD

**Issue by arnonkan** [python/mypy#9918] opened 2021-01-17 11:58 UTC
**Crash Report**

buntu20:arnon:scripts%mypy --show-traceback Blocks.py
/export/home/arnon/Kayhut/UEFI/scripts/Disas.py:8: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.rtfd.io/en/latest/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.800+dev.eb0bf114743e4b2a65582e83feacb184eb5c6d64
Traceback (most recent call last):
  File "/usr/local/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/home/arnon/.local/lib/python3.8/site-packages/mypy/__main__.py", line 11, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "/home/arnon/.local/lib/python3.8/site-packages/mypy/main.py", line 90, in main
    res = build.build(sources, options, None, flush_errors, fscache, stdout, stderr)
  File "/home/arnon/.local/lib/python3.8/site-packages/mypy/build.py", line 180, in build
    result = _build(
  File "/home/arnon/.local/lib/python3.8/site-packages/mypy/build.py", line 254, in _build
    graph = dispatch(sources, manager, stdout)
  File "/home/arnon/.local/lib/python3.8/site-packages/mypy/build.py", line 2638, in dispatch
    process_graph(graph, manager)
  File "/home/arnon/.local/lib/python3.8/site-packages/mypy/build.py", line 2964, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/home/arnon/.local/lib/python3.8/site-packages/mypy/build.py", line 3056, in process_stale_scc
    mypy.semanal_main.semantic_analysis_for_scc(graph, scc, manager.errors)
  File "/home/arnon/.local/lib/python3.8/site-packages/mypy/semanal_main.py", line 78, in semantic_analysis_for_scc
    process_top_levels(graph, scc, patches)
  File "/home/arnon/.local/lib/python3.8/site-packages/mypy/semanal_main.py", line 199, in process_top_levels
    deferred, incomplete, progress = semantic_analyze_target(next_id, state,
  File "/home/arnon/.local/lib/python3.8/site-packages/mypy/semanal_main.py", line 326, in semantic_analyze_target
    analyzer.refresh_partial(refresh_node,
  File "/home/arnon/.local/lib/python3.8/site-packages/mypy/semanal.py", line 394, in refresh_partial
    self.refresh_top_level(node)
  File "/home/arnon/.local/lib/python3.8/site-packages/mypy/semanal.py", line 405, in refresh_top_level
    self.accept(d)
  File "/home/arnon/.local/lib/python3.8/site-packages/mypy/semanal.py", line 4833, in accept
    node.accept(self)
  File "/home/arnon/.local/lib/python3.8/site-packages/mypy/nodes.py", line 396, in accept
    return visitor.visit_import_all(self)
  File "/home/arnon/.local/lib/python3.8/site-packages/mypy/semanal.py", line 1949, in visit_import_all
    self.add_imported_symbol(name, node, i,
  File "/home/arnon/.local/lib/python3.8/site-packages/mypy/semanal.py", line 4489, in add_imported_symbol
    self.add_symbol_table_node(name, symbol, context)
  File "/home/arnon/.local/lib/python3.8/site-packages/mypy/semanal.py", line 4394, in add_symbol_table_node
    self.defer(context)
  File "/home/arnon/.local/lib/python3.8/site-packages/mypy/semanal.py", line 4552, in defer
    assert not self.final_iteration, 'Must not defer during final iteration'
AssertionError: Must not defer during final iteration
/export/home/arnon/Kayhut/UEFI/scripts/Disas.py:8: : note: use --pdb to drop into pdb

```
(Insert traceback and other messages from mypy here -- use `--show-traceback`.)
```

**To Reproduce**

(Write what you did to reproduce the crash.  Full source code is
appreciated.  We also very much appreciate it if you try to narrow the
source down to a small stand-alone example.)

**Your Environment**

- Mypy version used:
- Mypy command-line flags:
- Mypy configuration options from `mypy.ini` (and other config files):
- Python version used:
- Operating system and version:

**Comment by JelleZijlstra** [comment] 2021-01-18 01:05
Thanks for the report! What you wrote isn't enough to help us figure out the crash. Do you have more information on the code that crashes? Ideally we'd have a self-contained piece of code that triggers the crash.

**Comment by hauntsaninja** [comment] 2021-09-06 20:10
Closing, since we don't have a repro / as a duplicate of #11064 which has a minimised repro and the same stacktrace

**Closed by hauntsaninja** 2021-09-06 20:10 UTC
Labels: crash
