### ISSUE TITLE
Issue with importing from relative imports (Name <ClassName> already defined)

### ISSUE THREAD

**Issue by darjus** [python/mypy#970] opened 2015-11-06 12:29 UTC
Repro setup:

    ➜  mypy git:(master) ✗ tree relative_root some_other_root
    relative_root 
    ├── __init__.py
    └── inner.py
    some_other_root
    ├── __init__.py
    ├── some_module.py
    ➜  mypy git:(master) ✗ cat relative_root/__init__.py
    from .inner import Inner
    ➜  mypy git:(master) ✗ cat relative_root/inner.py
    class Inner: pass
    ➜  mypy git:(master) ✗ cat some_other_root/__init__.py
    #
    ➜  mypy git:(master) ✗ cat some_other_root/some_module.py
    from relative_root import Inner

And the error:

    ➜  mypy git:(master) ✗ mypy --use-python-path -m some_other_root.some_module
    some_other_root/some_module.py:1: note: In module imported here:
    relative_root/__init__.py:1: error: Name 'Inner' already defined

**Comment by JukkaL** [comment] 2015-11-06 16:13
Thanks for reporting this! Did you have `PYTHONPATH` or `MYPYPATH` defined?

**Comment by darjus** [comment] 2015-11-07 03:29
Hey Jukka, 
Thanks for the quick reply, really excited about the project!

    ➜  mypy git:(master) ✗ echo $PYTHONPATH
    
    ➜  mypy git:(master) ✗ echo $MYPYPATH
    
So, no. BTW: Python3.4 (tried on mac an linux).

**Comment by gvanrossum** [comment] 2016-04-08 16:43
I've got a simpler repro: put the same two files in `relative_root`, but instead of having a separate package, just run `mypy -c 'from relative_root import Inner'`.

It almost feels as if the import (`from relative_root import Inner`) tries to store Inner in the wrong namespace (the globals of `relative_root` instead of `__main__`). Variants where I write `from relative_root import inner` (note lower case 'i') or `import relative_root` don't exhibit the problem.

**Comment by gvanrossum** [comment] 2016-05-19 23:58
Could this be a dupe of #1531?

**Comment by gvanrossum** [comment] 2016-05-20 00:00
Yup.

**Closed by gvanrossum** 2016-05-20 00:00 UTC
Labels: bug
