### ISSUE TITLE
Transitive boolean variables

### ISSUE THREAD

**Issue by lroellin** [python/mypy#5310] opened 2018-07-03 07:18 UTC
* Are you reporting a bug, or opening a feature request? A bug
* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.

This doesn't work:

```python
from typing import Optional


def foo(bla: Optional[str] = None):
    bla_is_none = bla is None
    if bla_is_none:
        bla = "blabla"
    bla.lower()

```

This does work (just inlined `bla_is_none`)

```python
from typing import Optional


def foo(bla: Optional[str] = None):
    if bla is None:
        bla = "blabla"
    bla.lower()

```

* What is the actual behavior/output?
```bash
❯ mypy --ignore-missing-imports test.py
test.py:8: error: Item "None" of "Optional[str]" has no attribute "lower"
```
* What is the behavior/output you expect?
No errors (no output)
* What are the versions of mypy and Python you are using? 0.610 on Python 3.4.8
  Do you see the same issue after installing mypy from Git master? I can't right now, due to a proxy issue (maybe)
* What are the mypy flags you are using? (For example --strict-optional) `--ignore-missing-imports`

**Comment by lroellin** [comment] 2018-07-03 09:37
I'm very open to suggestions why this is not a bug :)! Just something I saw and found a bit weird

**Comment by gvanrossum** [comment] 2018-07-03 15:43
We don't consider it a bug. PEP 484 does not mandate this inference, and it currently doesn't fit well in mypy's internal model of your code: it keeps only the type of variables, not their values.

That said, this is a common issue, and we're planning to do better here. There are just a lot of things to do...

**Comment by hauntsaninja** [comment] 2023-08-13 20:38
Duplicate of https://github.com/python/mypy/issues/11979

**Closed by hauntsaninja** 2023-08-13 20:38 UTC
Labels: feature, priority-2-low, topic-type-narrowing
