### ISSUE TITLE
no error when assigning to non-existent property outside of `__init__`

### ISSUE THREAD

**Issue by DetachHead** [python/mypy#15280] opened 2023-05-22 05:57 UTC
```py
class Foo:
    def foo(self) -> None:
        self.asdf = 1 # no error
```
[playground](https://mypy-play.net/?mypy=latest&python=3.11&flags=strict%2Cdisallow-any-decorated%2Cdisallow-any-expr%2Cdisallow-any-explicit%2Cdisallow-any-generics%2Cdisallow-any-unimported%2Cdisallow-subclassing-any%2Cwarn-return-any%2Cwarn-unreachable&gist=00a21d5dda53eae38e8172fedec8206b)

**Comment by hauntsaninja** [comment] 2023-05-22 09:07
Duplicate of https://github.com/python/mypy/issues/10552

**Closed by hauntsaninja** 2023-05-22 09:07 UTC
Labels: bug
