### ISSUE TITLE
Dataclass classmethods don't work

### ISSUE THREAD

**Issue by catern** [python/mypy#5974] opened 2018-11-29 22:13 UTC
On master and 0.630, the following code fails with `error: Incompatible return value type (got "Foo", expected "T")`:

```
from dataclasses import dataclass
import typing as t

T = t.TypeVar('T', bound="Foo")
@dataclass
class Foo:
    @classmethod
    def make(cls: t.Type[T]) -> T:
        return cls()
```

If I remove the dataclass annotation, it works fine.

**Comment by JelleZijlstra** [comment] 2018-11-29 22:21
cc @euresti since this seems to be due to the dataclasses plugin.

**Comment by euresti** [comment] 2018-11-29 22:46
Hmm. In my code I usually annotate this as:

```
@dataclass
class Foo:
    @classmethod
    def make(cls) -> 'Foo':
        return cls()
```

But I hardly use inheritance.  

Also I don't know why the decorator would break it.  Does it happens with `@attr.s`?

**Comment by ilevkivskyi** [comment] 2018-11-29 23:21
This works on master

**Comment by ilevkivskyi** [comment] 2018-11-29 23:22
Also this is a duplicate of https://github.com/python/mypy/issues/5263 that was fixed by https://github.com/python/mypy/pull/5646

**Closed by ilevkivskyi** 2018-11-29 23:21 UTC
Labels: false-positive, priority-1-normal, topic-plugins
