### ISSUE TITLE
Namespace Package PEP 561 Support

### ISSUE THREAD

**Issue by macbeth322** [python/mypy#5572] opened 2018-09-04 20:56 UTC
The current documentation [here](https://mypy.readthedocs.io/en/latest/installed_packages.html#using-pep-561-compatible-packages-with-mypy) indicates that mypy does not support namespace packages in terms of importing type hint information from packages.

At my org, we use a company wide namespace package for all our packages which effectively means there is currently no way to import type hinting information for our internal libraries.

My question is, is supporting namespace packages a planned feature?

**Comment by gvanrossum** [comment] 2018-09-04 20:58
I think this is a duplicate of https://github.com/python/mypy/issues/1645. Someone started an implementation but never completed it.

**Closed by gvanrossum** 2018-09-04 20:58 UTC
