### ISSUE TITLE
Better error message for rejected protocol subtyping due to mutability

### ISSUE THREAD

**Issue by llchan** [python/mypy#5752] opened 2018-10-08 17:38 UTC
It appears that Union types for Protocol attributes aren't recognized.

Repro example:
```
from typing import Type, Union
from typing_extensions import Protocol


class HasFoo(Protocol):
    # foo: str            # works
    foo: Union[str, int]  # fails


def dec(cls: Type[HasFoo]) -> Type[HasFoo]:
    return cls


@dec
class Thing:
    foo = 'abc'
```

Failing output:
```Argument 1 to "dec" has incompatible type "Type[Thing]"; expected "Type[HasFoo]"```

Misc info:
Tested with both mypy 0.630 and mypy master (e12be3ba9e6be3e9242e3a81ffaa9b3a136876fe), run with `--strict`

**Comment by ilevkivskyi** [comment] 2018-10-08 17:51
This is not a bug, but an actual type error, please read this https://mypy.readthedocs.io/en/latest/common_issues.html#covariant-subtyping-of-mutable-protocol-members-is-rejected

**Comment by ilevkivskyi** [comment] 2018-10-08 17:55
On the second thought, maybe we should add this link to the error message? It is not obvious that this is rejected because of the mutability (especially that mypy allows this for nominal subclasses), but on the other hand it is quite rare case, so I am not sure here.

**Comment by llchan** [comment] 2018-10-08 18:06
Yeah, I was just about comment that it would be helpful if the error message indicated that the protocol was rejected due to mutability. Doesn't make a huge difference to me now that I know, but might be helpful for others that run into this?

**Comment by ilevkivskyi** [comment] 2018-10-08 18:09
OK, let's see what others think. @JukkaL @gvanrossum should we add a note (probably with the link) to this error message?

**Comment by gvanrossum** [comment] 2018-10-08 18:15
I do think the error should be clearer, and if we can link to that section in the docs when we find covariant subtyping might be assumed that would well help.

I wonder if the OP has thought of adding `# type: Union[str, int]` to the initialization of `foo` in `Thing`. (Of course that might cause other problems down the line, but it's still enlightening to realize it.)

**Comment by ilevkivskyi** [comment] 2018-10-08 18:18
OK, I am re-opening with another title.

**Comment by llchan** [comment] 2018-10-08 18:30
Thanks, I really appreciate the responsiveness and the dedication to usability!

**Comment by hauntsaninja** [comment] 2023-02-01 10:13
Closing as a duplicate of https://github.com/python/mypy/issues/6002

**Closed by hauntsaninja** 2023-02-01 10:13 UTC
Labels: priority-1-normal, topic-usability, topic-protocols, topic-error-reporting
