### ISSUE TITLE
Overload with multiple type arguments

### ISSUE THREAD

**Issue by rmcgibbo** [python/mypy#3883] opened 2017-08-28 22:18 UTC
I apologize if this is a dumb question. I'm having trouble getting overload to work properly with generics that take more than one type variable.

Example:
```
from typing import TypeVar, Generic, overload

T1 = TypeVar('T1', covariant=True)
T2 = TypeVar('T2', covariant=True)

class hello1(Generic[T1]): ...
class hello2(Generic[T1, T2]): ...

# Works
@overload
def swap1(a: hello1[float]) -> hello1[int]: ...

@overload
def swap1(a: hello1[int]) -> hello1[float]: ...

# Doesn't work
@overload
def swap2(a: hello2[float, int]) -> hello2[int, float]: ...   # example.pyi:18: error: Overloaded function signatures 1 and 2 overlap with incompatible return types
@overload
def swap2(a: hello2[int, float]) -> hello2[float, int]: ...
```

It's not clear to me why this shouldn't be allowed. Is this expected behavior, or perhaps a bug?

**Comment by ilevkivskyi** [comment] 2017-08-28 22:30
I think this is not a bug, and mypy is right that such overload is not safe. For example, what should be the type of ``y`` in this example (continuing yours):
```python
x: hello2[int, int]
y = swap2(x)
```
Because of covariance ``hello2[int, int]`` is a subtype of both ``hello2[int, float]`` and ``hello2[float, int]``, so depending on which overload variant you apply, you get two mutually incompatible types for ``y``.

Please close the issue if you agree.

**Comment by rmcgibbo** [comment] 2017-08-28 23:12
But it also doesn't work if I change T1 and T2 to being contravariant (in that case neither swap1 nor swap2 works).

**Comment by ilevkivskyi** [comment] 2017-08-29 20:32
For contravariant type variables my exactly same argument applies but with ``hello2[float, float]`` instead of ``hello2[int, int]``. Also for contravariant variable the order of overloads in ``swap1`` should be opposite (the first overload should always have the most narrow argument types).

**Closed** 2017-08-30 03:15 UTC
