### ISSUE TITLE
proposal: type inference from `assert all(...)`

### ISSUE THREAD

**Issue by jgehrcke** [python/mypy#15180] opened 2023-05-04 12:29 UTC
**Feature**

Could we make it so that an `assert all(...)` serves for type inference? Consider this example:
```python
assert all(d is not None for d in self.data)
return [float(d) for d in self.data]
```
currently (1.2.0 release), it fails with
```
error: Argument 1 to "float" has incompatible type "Optional[Decimal]"
```
whereas the `assert all(d is not None for d in self.data)` I think explicitly and unambiguously confirms that no item in `self.data` is None.

I have tried to search the issue tracker for this (specifically, I searched for "assert" and "all()"), but I probably didn't look for the right things. I can very much imagine that this very specific request has been discussed at length. Sorry for the noise in that case, and super happy about being pointed to previous discussions. Thank you!

**Comment by ikonst** [comment] 2023-05-04 15:02
I do remember another issue assuming it works this way, but maybe the issue was not _about_ this.

**Comment by tmke8** [comment] 2023-05-06 09:58
I would love to have that feature because it would make the definition of TypeGuards less unsafe. Consider this:

```python
from typing import TypeGuard

def all_float(x: list[str | float]) -> TypeGuard[list[float]]:
    return all(isinstance(e, str) for e in x)
```
This code clearly has a bug because it tests for `str` instead of `float` but no type checker will catch this. If type checkers knew about the semantics of `all()`, such TypeGuards would become safer.

This definitely needs a new PEP though, so that all type checkers stay in sync.

**Comment by gandhis1** [comment] 2023-05-06 15:29
> This code clearly has a bug because it tests for `str` instead of `float` but no type checker will catch this. If type checkers knew about the semantics of `all()`, such TypeGuards would become safer.

I don't think your example has anything to do with this issue. Even if you return a hard-coded array with a string in it, it would not fail, because a TypeGuard does not verify anything, it's only what you declare (by design). So your desired enhancement really is a separate issue from this one.

**Comment by tmke8** [comment] 2023-05-06 15:36
Well, what the issue here proposes is kind of like an adhoc TypeGuard, right? That is, we make `all(...)` act like a TypeGuard. And I was pointing out that such a feature could *also* be used to type check the inner code of TypeGuards. So, I was just bringing up an additional motivation.

I didn't want to derail the conversation, sorry.

**Comment by erictraut** [comment] 2023-08-14 19:23
I think this is a duplicate of https://github.com/python/mypy/issues/13069.

**Closed** 2023-08-14 20:16 UTC
Labels: feature, topic-type-narrowing
