### ISSUE TITLE
Generic Self classmethod fails for generic types

### ISSUE THREAD

**Issue by rowillia** [python/mypy#3631] opened 2017-06-29 06:20 UTC
Repro:

```python
from typing import Generic, TypeVar, Type

_T = TypeVar('_T')
SelfType = TypeVar('SelfType', bound='Friend')

class Friend(Generic[_T]):
    @classmethod
    def make(cls: Type[SelfType]) -> SelfType:  # E: Unsupported type Type["SelfType"]
        return cls()
```

I suspect the issue is that the type _should_ be:

```python
def make(cls: Type[SelfType[T]]) -> SelfType[T]:
        return cls()
```

But there is no way to express that that I can tell.

Using an instance method behaves as expected:
```
from typing import Generic, TypeVar, Type

_T = TypeVar('_T')
SelfType = TypeVar('SelfType', bound='Friend')

class Friend(Generic[_T]):
    other = None  # type: Friend

    def make(self: SelfType) -> SelfType:
        return self
```

**Comment by ilevkivskyi** [comment] 2017-06-29 08:07
I think this is a duplicate of #3363 and #2354 
I think we could leave only one of these three issues open and raise its priority.

**Comment by rowillia** [comment] 2017-06-29 21:48
@ilevkivskyi I'm fine with that.  AFAICT https://github.com/python/mypy/issues/2354 is effectively fixed, the code example below works great:

```python
from typing import Generic, TypeVar, Type

_T = TypeVar('_T')
SelfType = TypeVar('SelfType', bound='Friend')

class Friend(Generic[_T]):
    other = None  # type: Friend

    def make(self: SelfType) -> SelfType:
        return self

class SuperFriend(Generic[_T], Friend[_T]):
    pass


reveal_type(SuperFriend[int]().make())  # E: Revealed type is 'test_generic_self.SuperFriend[builtins.int]'
```

I'd be fine if `classmethods` had the same behavior.  In fact, @elazarg 's change https://github.com/python/mypy/pull/3633 _mostly_ fixes this issue.  The types are correct but declaring the function `make` still throws an error:

```python
from typing import Generic, TypeVar, Type

_T = TypeVar('_T')
SelfType = TypeVar('SelfType', bound='Friend')

class Friend(Generic[_T]):
    other = None  # type: Friend

    @classmethod
    def make(cls: Type[SelfType]) -> SelfType:  # E: Unsupported type Type["SelfType"]
        return cls()

class SuperFriend(Generic[_T], Friend[_T]):
    pass


reveal_type(SuperFriend[int]().make())  # E:  Revealed type is 'test_generic_self.SuperFriend*[builtins.int*]'
```

**Comment by elazarg** [comment] 2017-06-30 08:38
I think the `Unsupported type Type["SelfType"]` error is a separate issue. It happens even for `staticmethod`, for which there's no specific check for selftype.

**Comment by rowillia** [comment] 2017-06-30 16:57
@elazarg got it.  If you can land https://github.com/python/mypy/issues/2354 I can debug the `Type["SelfType"]` issue.

**Comment by gvanrossum** [comment] 2017-06-30 17:02
Yeah, it gives the same error when `Type[SelfType]` is used outside the
`Friend` class. It's purely because of the use of Type[] with a type
variable that is bound by a generic class.

**Comment by bharel** [comment] 2018-06-29 19:22
I've been [sent here](https://stackoverflow.com/questions/51042452/bound-typevar-on-generic-methods-inside-generic-class) by stackoverflow. Issue is still relevant.

**Closed** 2018-08-02 16:29 UTC
