### ISSUE TITLE
Incorrect "incompatible default for argument" when the hint is a generic type with a TypeVar

### ISSUE THREAD

**Issue by Zac-HD** [python/mypy#6556] opened 2019-03-16 13:43 UTC
I would expect mypy to understand that `(None,)` is a valid default for `Tuple[T, ...]`, but instead I get

    error: Incompatible default for argument "a"
           (default has type "Tuple[None]", argument has type "Tuple[T, ...]")

```python
from typing import List, Tuple, TypeVar
T = TypeVar("T")  # or covariant, or contravariant

def f(a: Tuple[T, ...] = (None,)) -> List[T]:  # Or Tuple[T], Set[T], etc.
    return list(a)
```

This was actually found while working on HypothesisWorks/hypothesis#167, where the signature eventually desugars to `(Callable[..., T], SearchStrategy[T]) -> SearchStrategy[Callable[..., T]]`, but the tuple-to-list example here has the same problem and is much easier to follow.

**Comment by JelleZijlstra** [comment] 2019-03-16 14:43
This is a duplicate of #3737, which has a simpler example.

**Closed by JelleZijlstra** 2019-03-16 14:43 UTC

**Comment by ilevkivskyi** [comment] 2019-03-16 14:46
Note that supporting this would require lower bounds for type variables (currently mypy supports only upper bounds). For `None` it may sound silly, but technically it is still needed. Current workaround is to use overloads, see the original issue.
