### ISSUE TITLE
Only concrete class can be given where "Type[IFoo]" is expected

### ISSUE THREAD

**Issue by solstice333** [python/mypy#9332] opened 2020-08-20 11:23 UTC
This is related to #5374.

Hm, this could be a bug, but since I think the behavior I'm seeing is intended behavior (https://github.com/python/mypy/issues/5374#issuecomment-436638471), it's probably more likely that I'm reporting a feature request

Here's as minimal of a repro case I can make while giving some context of what I'm trying to do:

```python
import typing

from abc import ABC, abstractmethod
from typing import Type, Optional, Callable, Iterable, overload, TypeVar, Any

T = TypeVar('T')
ExceptionCreatorTy = Callable[[Iterable[Type], Any, str], Exception]


def assert_with(cond: bool, err: Exception) -> None:
    if not cond:
        raise err


def any_of(vals: Iterable[T], pred: Callable[[T], bool]) -> bool:
    for val in vals:
        if pred(val):
            return True
    return False


@overload
def cast(
        ty: Type[T],
        val: Any,
        exc_fn: Optional[ExceptionCreatorTy] = None
) -> T:
    pass


@overload
def cast(
        ty: Iterable[Type],
        val: Any,
        exc_fn: Optional[ExceptionCreatorTy] = None
) -> Any:
    pass


@overload
def cast(
        ty: None,
        val: Any,
        exc_fn: Optional[ExceptionCreatorTy] = None
) -> None:
    pass


def cast(ty, val, exc_fn=None):
    ty = type(None) if ty is None else ty
    tys = ty if isinstance(ty, Iterable) else [ty]
    cond = any_of(tys, lambda ty2: isinstance(val, ty2))
    default_error_msg = \
        f"val is type {type(val).__name__} which is " \
        f"not a subtype of any of {[ty.__name__ for ty in tys]}"

    if exc_fn is not None:
        assert callable(exc_fn)
        assert_with(cond, exc_fn(tys, val, default_error_msg))
    else:
        assert cond, default_error_msg
    return val


class IFoo(ABC):
    @abstractmethod
    def func(self) -> None:
        pass


class Foo(IFoo):
    def func(self) -> None:
        print("bar")


def main() -> None:
    foo: Foo = Foo()
    bar: IFoo = foo
    cast(IFoo, bar).func()


if __name__ == '__main__':
    main()
```

In the code above, I thought it'd be clever to have a "dynamic cast" that brings the flow of error messages closer to the front, as opposed to just suppressing the type checker at the call site of the cast. 

Putting the content above in a foo.py and running `python3 -m mypy foo.py` gives

```
foo.py:79: error: Only concrete class can be given where "Type[IFoo]" is expected
Found 1 error in 1 file (checked 1 source file)
```

At first I thought this should be allowed, but I guess the error message says it all since usage of `Type[cls]` guarantees instantiation of `cls`. I was unsuccessful in finding something like `AbstractType[cls]`.

I see a few workarounds:

1. loosening up the argument and return types to `Any`, though obvious type errors would be pushed further to the back towards runtime

2. replacing the cast with two lines: 
```python
assert isinstance(bar, IFoo)
bar.func()
``` 
which is not a bad alternative, though inconsistent and a bit more tedious to type around the codebase

3. scrap the usage of interfaces or abstract base classes

I'm using mypy verison 0.782

I have not tried installing mypy from the master branch. Let me know if this is worth doing.

Feel free to make this low priority. I'm going to go with workaround 2 for now.

**Comment by ilevkivskyi** [comment] 2020-09-08 16:44
Although this is not exactly a duplicate of #5374, I don't think we need to track this separately, because the solution is to just loosen this check in mypy, it causes more pain than it adds safety.

**Closed by ilevkivskyi** 2020-09-08 16:44 UTC
