### ISSUE TITLE
Crash on class using TypeVar defined before bound class

### ISSUE THREAD

**Issue by berzi** [python/mypy#12858] opened 2022-05-23 13:57 UTC
**Crash Report**

Running mypy causes a crash when a class is reached that uses `Generic` with a TypeVar defined before its bound.

**Traceback**

```
src\user\app\stores\base_models.py:46: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.942
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "mypy\semanal.py", line 5220, in accept
  File "mypy\nodes.py", line 739, in accept
  File "mypy\semanal.py", line 630, in visit_func_def
  File "mypy\semanal.py", line 662, in analyze_func_def
  File "mypy\semanal.py", line 4920, in defer
AssertionError: Must not defer during final iteration
src\user\app\stores\base_models.py:46: : note: use --pdb to drop into pdb
```

**To Reproduce**

The class inherits from a couple Pydantic models, Pydantic's `GenericModel` **and typing's `Generic[MyTypeVar]`**, where `MyTypeVar` is just a regular TypeVar bounded to a class in the same file.

If the class in the TypeVar bound is defined after the TypeVar itself, and given as a string, this causes a crash. Moving the TypeVar declaration after the class' declaration causes the crash to go away.

Declaring TypeVar bounds as strings is supported; this is generally done to allow specifying a class that is defined later, but in this case this causes a crash. If this isn't supported, an explicit error should be given to the user, but I believe it's reasonable that it be supported.

**Your Environment**

- Mypy version used: 0.942
- Mypy command-line flags: --no-incremental --show-traceback
- Python version used: 3.9
- Operating system and version: Windows 11

**Comment by AlexWaygood** [comment] 2022-05-23 14:59
Thanks for the report! Are you able to provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that produces the crash?

Also, note that 0.942 is not the latest version of mypy. Could you possibly confirm that this crash also happens on 0.950 (the latest version)?

**Comment by berzi** [comment] 2022-05-24 06:54
Hi. The error occurs on 0.950 too. Here's an example that will trigger it:

```python
from typing import TypeVar, Generic

from pydantic.generics import GenericModel


SomeBoundedType = TypeVar("SomeBoundedType", bound="SomeBound")


class SomeBound:
    pass


class SomeGenericClass(GenericModel, Generic[SomeBoundedType]):
    pass
```

Moving SomeBoundedType after SomeBound makes the error go away.

It seems that the error only occurs if Pydantic's GenericModel is involved.

**Comment by hauntsaninja** [comment] 2022-05-24 17:54
@berzi I can only reproduce with the pydantic plugin. I'd consider reporting to pydantic since they maintain their mypy plugin.

**Comment by AlexWaygood** [comment] 2022-06-13 23:47
> @berzi I can only reproduce with the pydantic plugin. I'd consider reporting to pydantic since they maintain their mypy plugin.

Closing as per @hauntsaninja's comments: this seems like it's probably a pydantic issue rather than a mypy issue, so it should probably be reported over at their issue tracker rather than here. @berzi, if you're able to find a reproducer that doesn't involve the pydantic plugin, I'll happily reopen the issue :)

**Closed by AlexWaygood** 2022-06-13 23:47 UTC
Labels: crash
