### ISSUE TITLE
Relation between enum and its member in Python typing

### ISSUE THREAD

**Issue by kolod1am** [python/mypy#15134] opened 2023-04-25 18:30 UTC
Dear All,

This is to report difficult behaviour of MyPy in typing a generic function that shall accept an enum and its member but not an enum and a member of another enum:

```
from enum import Enum
from typing import TypeVar, Type

class MyEnumA(Enum):
   A = 1

class MyEnumB(Enum):
   A = 1

TE = TypeVar('TE', bound=Enum)
def myfunction(member: TE, e: Type[TE]) -> None:
    pass

myfunction(MyEnumA.A, MyEnumA) # all right
myfunction(MyEnumA.A, MyEnumB) # I expect mypy-error here but it passed

print(type(MyEnumA.A)) # says: <enum 'MyEnumA'>
print(type(MyEnumB.A)) # says: <enum 'MyEnumB'>

print(f'{isinstance(MyEnumA.A, MyEnumA)=}') # says: isinstance(MyEnumA.A, MyEnumA)=True
print(f'{isinstance(MyEnumA.A, MyEnumB)=}') # says: isinstance(MyEnumA.A, MyEnumB)=False

reveal_type(MyEnumA) # mypy: Revealed type is "def (value: builtins.object) -> e.MyEnumA"
reveal_type(MyEnumA.A) # mypy: Revealed type is "Literal[e.MyEnumA.A]?"
```

I have found type signature that does what I expect:
```
P = ParamSpec('P')
def myfunction(member: TE, e: Callable[P, TE]) -> None:
```

MyPy version:

```
$ mypy --version
mypy 1.2.0 (compiled: yes)
```

[Issue discussed at StactOverflow](https://stackoverflow.com/questions/76089319/express-relation-between-enum-and-its-member-in-python-typing/)

**Comment by erictraut** [comment] 2023-08-14 18:33
Mypy is working as intended here. The expression `myfunction(MyEnumA.A, MyEnumB)` doesn't generate a type violation because there are no constraints (such as an upper bound) on the type variable, and mypy's constraint solver is able to find a valid type that satisfies this call. In this case, the type `MyEnumA | MyEnumB` satisfies the constraints. So does `Enum`.

Note that this problem is not specific to enums. Consider the following:

```python
T = TypeVar("T")

def add(a: T, b: T) -> T: ...

add(0, "hi") # Does not generate a type violation
```

Potential solutions to your problem include:
1. Redefine `myfunction` so it doesn't accept two parameters (a type and an instance of that type).
2. Use a constrained TypeVar that restricts the allowed values to a set of defined enum types.

I think mypy is working correctly. I don't see any bug with the above behavior. Recommend closing.

**Closed** 2023-08-14 18:35 UTC
