### ISSUE TITLE
`int` inconsistently considered a subtype of `float`

### ISSUE THREAD

**Issue by decorator-factory** [python/mypy#17223] opened 2024-05-07 23:59 UTC
From [PEP 484](https://peps.python.org/pep-0484/#the-numeric-tower):

> when an argument is annotated as having type `float`, an argument of type `int` is acceptable

So mypy considers this legal (mypy 1.10.0, with `--strict`):
```py
def f(x: float) -> None:
    pass

f(42)
```

But when checking objects with `isinstance`, it thinks a variable annotated with `float` cannot be an `int`:
```py
def f(x: float) -> None:
    if not isinstance(x, float):
        print("💀")  # error: Statement is unreachable  [unreachable]
        reveal_type(x)  # no diagnostics

f(42)
```
I think this is a bug, since `float` is always implicitly `float | int`. I'd expect mypy to not flag this as unreachable and reveal the type of `x` as `int`. (that's the behaviour `pyright` currently has)

Here's another potentially buggy example:
```py
def f(x: float | str) -> None:
    if isinstance(x, float):
        reveal_type(x)  # Revealed type is "builtins.float"
    else:
        reveal_type(x)  # Revealed type is "builtins.str"
```
If you call this function as `f(42)`, which mypy allows, the second branch will be selected at runtime.

**Comment by hauntsaninja** [comment] 2024-05-23 04:40
Closing as a duplicate of https://github.com/python/mypy/issues/11516

**Closed by hauntsaninja** 2024-05-23 04:40 UTC
Labels: bug
