### ISSUE TITLE
Broken reachability checks in match-case

### ISSUE THREAD

**Issue by denballakh** [python/mypy#13989] opened 2022-11-02 08:41 UTC
**Bug Report**
I have two small similar examples for you:
1:
```py
def f(x: object, y: object) -> int | None: # Missing return statement
    match x, y:
        case int(), int() if True:
            return 42
        case _:
            return None
```

2:
```py
def f(x: object, y: object) -> int | None: # Missing return statement
    match x, y:
        case _, _ if True:
            return 42
        case _:
            return None
```
**Expected Behavior**
1. No `Missing return statement` error, because code after `match` statement is unreachable.
2. No `Missing return statement` error and error `statement is unreachable` on line `case _:`
 
**Actual Behavior**
1. Error `Missing return statement`.
2. Error `Missing return statement`. No `statement is unreachable` error on line `case _:`

Error `Missing return statement` will disappear if i remove `if True:` condition (in both cases).
Error `statement is unreachable` will appear if i replace `case _, _:` with `case _:`. Removing condition doesnt help.

**Your Environment**
- Mypy version used: mypy 0.982 (compiled: no)
- Mypy command-line flags: no
- Mypy configuration options from `mypy.ini`: no
- Python version used: 3.11
- Windows 10

**And now for something a bit different**
```py
def f(x: object, y: object) -> int | None:
    match x, y:
        case int(), int():
            return x + y # Unsupported left operand type for + ("object")
        case _:
            return None
```
Mypy cannot narrow types of tuple elements.

**Comment by erictraut** [comment] 2023-08-13 23:35
This is a duplicate of https://github.com/python/mypy/issues/12534.

**Closed** 2023-08-14 23:51 UTC
Labels: bug, topic-match-statement, topic-reachability, topic-type-narrowing
