### ISSUE TITLE
Internal Error when overriding dataclass field with property in inheritence

### ISSUE THREAD

**Issue by MaxG87** [python/mypy#8675] opened 2020-04-15 13:32 UTC
Please consider the following minimum working example:

```python
# mwe.py
from dataclasses import dataclass


@dataclass
class Parent:
    url: str


@dataclass(frozen=True)
class Child(Parent):
    @property
    def url(self):
        pass
```

I execute `mypy mwe.py` in a environment that can be reproduced as follows:
```bash
conda create -n mwe python=3.8
conda activate mwe
python -m pip install mypy
```

When I run mypy, I get:

```bash
mypy --show-traceback mwe.py
mwe.py:10: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.rtfd.io/en/latest/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.770
Traceback (most recent call last):
  File "mypy/semanal.py", line 4679, in accept
  File "mypy/nodes.py", line 939, in accept
  File "mypy/semanal.py", line 1001, in visit_class_def
  File "mypy/semanal.py", line 1078, in analyze_class
  File "mypy/semanal.py", line 1087, in analyze_class_body_common
  File "mypy/semanal.py", line 1133, in apply_class_plugin_hooks
  File "mypy/plugins/dataclasses.py", line 369, in dataclass_class_maker_callback
  File "mypy/plugins/dataclasses.py", line 182, in transform
  File "mypy/plugins/dataclasses.py", line 355, in _freeze
AssertionError:
mwe.py:10: : note: use --pdb to drop into pdb
```

I am aware that the code above is not exactly well formed. However, I think an internal error is not the appropriate reaction of `mypy`. I hope this helps to improve your great tool.

**Comment by TH3CHARLie** [comment] 2020-04-15 17:26
I believe this is a duplicate of #8334.

**Closed** 2020-04-15 18:38 UTC
