### ISSUE TITLE
Spurious "return statement in function which does not return"

### ISSUE THREAD

**Issue by bwo** [python/mypy#13014] opened 2022-06-23 19:02 UTC
Consider:

```python
import sys
from typing import NoReturn, Callable


def foo() -> NoReturn:
    sys.exit(1)


def bar() -> Callable[[], NoReturn]:
    return lambda: foo()   # line 10


def baz() -> Callable[[], NoReturn]:
    return foo
```

Running mypy v 0.961 against a file with these contents gives the error "foo.py:10: error: Return statement in function which does not return".

But, the return statement is in a function which *does* return, returning a function which does not. There are no complaints about the definition of `baz`, presumably because no function is defined in it.

**Comment by AlexWaygood** [comment] 2022-06-23 20:33
Duplicate of #10520

**Closed by AlexWaygood** 2022-06-23 20:33 UTC
Labels: bug
