### ISSUE TITLE
How to add attributes to Callable?

### ISSUE THREAD

**Issue by ze-phyr-us** [python/mypy#3882] opened 2017-08-27 09:51 UTC
I have a simple decorator that just sets an attribute on a function and returns it. The closest I got to checking this is creating a subclass of `Callable` and adding the attribute to it:

```python
from typing import Callable, cast

class RemoteCallable(Callable):
	rpc_name: str = None

def remote(f: Callable) -> RemoteCallable:
	''' Decorator marking a function as callable via the RPC system. '''
	f = cast(RemoteCallable, f)
	f.rpc_name = f.__name__
	return f
```

However, this fails with `rpc.py:3: error: Invalid base class`. What can I do?

**Comment by JelleZijlstra** [comment] 2017-08-27 15:39
This isn't currently supported yet, but @ilevkivskyi came up with an elegant approach recently so we can support it; see #2087. Closing as a duplicate of that issue.

**Closed by JelleZijlstra** 2017-08-27 15:39 UTC
