### ISSUE TITLE
Propper inheritance with staticmethod

### ISSUE THREAD

**Issue by InvisibleHandOfDoom** [python/mypy#7466] opened 2019-09-04 22:05 UTC
If have following code

```
from typing import Type, TypeVar

T = TypeVar("T")

class Foo:
    @classmethod
    def load(cls: Type[T]) -> T: ...

class Bar(Foo):
    @classmethod
    def load(cls: Type[Bar]) -> Bar:
        return cls()
```

which, fails to type check, with:

```
test.pyi:11: error: Return type "Bar" of "load" incompatible with return type <nothing> in supertype "Foo"
```

To my confusion it type check if I modify parent signature to:

```
from typing import Type, TypeVar

T = TypeVar("T")

class Foo:
    @classmethod
    def load(cls: T) -> T: ...

class Bar(Foo):
    @classmethod
    def load(cls: Type[Bar]) -> Bar:
        return cls()
```

- Mypy version mypy-0.730+dev.63380783f032ee17c8cf0560dd81cf734bf36103
- No custom flags

**Comment by ilevkivskyi** [comment] 2019-09-05 14:31
Thanks for reporting!

This looks like another duplicate of https://github.com/python/mypy/issues/2511

**Closed by ilevkivskyi** 2019-09-05 14:31 UTC
