### ISSUE TITLE
Document the suffixes `*` and `?` returned by `reveal_type`

### ISSUE THREAD

**Issue by jwhitlock** [python/mypy#12809] opened 2022-05-18 16:51 UTC
**Documentation**

I have some code (Python 3.9.12) that processes an email, something like this:

```python
from email.message import Message
from typing import Optional


def get_email_contents(email_message: Message) -> tuple[Optional[str], Optional[str]]:
    text_content = None
    html_content = None
    if email_message.is_multipart():
        for part in email_message.walk():
            reveal_type(part)
            if part.get_content_type() == "text/plain":
                text_content = part.get_content()
            if part.get_content_type() == "text/html":
                html_content = part.get_content()
    return text_content, html_content
```

The code works, and is very similar to the [emails.Message.walk](https://docs.python.org/3.9/library/email.message.html#email.message.EmailMessage.walk) example code.

`mypy 0.942` returns:

```
tmp/email.py:10: note: Revealed type is "email.message.Message*"
tmp/email.py:12: error: "Message" has no attribute "get_content"; maybe "get_content_type"?  [attr-defined]
tmp/email.py:14: error: "Message" has no attribute "get_content"; maybe "get_content_type"?  [attr-defined]
```

I can't find in the documentation what the `*` (asterisk, star) at the end of `"email.message.Message*"`, or any tests that return such a message. My guess is that it is an unknown class derived from `email.message.Message`.

I can find tests with a `?` (question mark) suffix, such as:

https://github.com/python/mypy/blob/8dac2210f5afedee1c45c6293f20bf9b5c5ec179/test-data/unit/check-enum.test#L21-L26

Can the documentation include what a `*` or `?` means in the return of `reveal_type`?

**Comment by hauntsaninja** [comment] 2022-05-18 16:57
Duplicate of some issue, for which the resolution is we got rid of the `*` (fwiw it used to mean inferred): https://github.com/python/mypy/pull/12459

The question mark in your main example isn't part of the type, it's a genuine question.

**Closed** 2022-05-18 16:56 UTC
Labels: documentation

**Comment by jwhitlock** [comment] 2022-05-18 20:34
Thanks @JelleZijlstra , that explains `*`, and that `?` may be removed.

> The question mark in your main example isn't part of the type, it's a genuine question.

@hauntsaninja, I was referring to the code in [mypy/test-data/unit/check-enum.test](https://github.com/python/mypy/blob/8dac2210f5afedee1c45c6293f20bf9b5c5ec179/test-data/unit/check-enum.test#L21-L26), equivalent to:

```python
from enum import Enum
from typing import Literal

x: Literal['ANT BEE CAT DOG'] = 'ANT BEE CAT DOG'
Animal = Enum('Animal', x)
reveal_type(Animal.ANT)
reveal_type(Animal.BEE)
reveal_type(Animal.CAT)
reveal_type(Animal.DOG)
```

which returns types with `?` suffixes, and is covered by issue #11519:

```
literal.py:6: note: Revealed type is "Literal[literal.Animal.ANT]?"
literal.py:7: note: Revealed type is "Literal[literal.Animal.BEE]?"
literal.py:8: note: Revealed type is "Literal[literal.Animal.CAT]?"
literal.py:9: note: Revealed type is "Literal[literal.Animal.DOG]?"
```

The "fix" for my code is to add an assertion, since the returned type of `walk` appears wrong:

```python
from email.message import EmailMessage
from typing import Optional


def get_email_contents(
    email_message: EmailMessage,
) -> tuple[Optional[str], Optional[str]]:
    text_content = None
    html_content = None
    if email_message.is_multipart():
        for part in email_message.walk():
            assert isinstance(part, EmailMessage)
            reveal_type(part)
            if part.get_content_type() == "text/plain":
                text_content = part.get_content()
            if part.get_content_type() == "text/html":
                html_content = part.get_content()
    return text_content, html_content
```

The new `mypy` output omits the warnings:
```
email.py:13: note: Revealed type is "email.message.EmailMessage"
```
