### ISSUE TITLE
Mypy 1.0.0 crashes with asyncssh

### ISSUE THREAD

**Issue by julian-r** [python/mypy#14699] opened 2023-02-14 14:49 UTC
**Crash Report**

Updated my project from mypy 0.991 to 1.0.0

**Traceback**

On the top you see the log because my execution with `--verbose`

```
LOG:  Writing asyncssh.connection /Users/julian/Library/Caches/pypoetry/virtualenvs/mypy-asyncssh-issue-ZzvwNVve-py3.11/lib/python3.11/site-packages/asyncssh/connection.py asyncssh/connection.meta.json asyncssh/connection.data.json
LOG:  Build finished in 1.795 seconds with 270 modules, and 0 errors
Traceback (most recent call last):
  File "/Users/julian/Library/Caches/pypoetry/virtualenvs/mypy-asyncssh-issue-ZzvwNVve-py3.11/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
             ^^^^^^^^^^^^^^^
  File "/Users/julian/Library/Caches/pypoetry/virtualenvs/mypy-asyncssh-issue-ZzvwNVve-py3.11/lib/python3.11/site-packages/mypy/__main__.py", line 15, in console_entry
    main()
  File "mypy/main.py", line 95, in main
  File "mypy/main.py", line 174, in run_build
  File "mypy/build.py", line 194, in build
  File "mypy/build.py", line 277, in _build
  File "mypy/build.py", line 2923, in dispatch
  File "mypy/build.py", line 3320, in process_graph
  File "mypy/build.py", line 3443, in process_stale_scc
  File "mypy/build.py", line 2504, in write_cache
  File "mypy/build.py", line 1574, in write_cache
  File "mypy/nodes.py", line 377, in serialize
  File "mypy/nodes.py", line 3841, in serialize
  File "mypy/nodes.py", line 3778, in serialize
  File "mypy/nodes.py", line 3514, in serialize
  File "mypy/types.py", line 2072, in serialize
  File "mypy/types.py", line 605, in serialize
  File "mypy/types.py", line 2876, in serialize
AssertionError: Internal error: unresolved placeholder type None
```

**To Reproduce**

I've provided a poetry-based project which will cause the error when 

```
poetry run mypy --verbose --show-traceback .
```

**Your Environment**

Project to reproduce:
https://github.com/julian-r/mypy-asyncssh-issue

- Mypy version used: 1.0.0
- Mypy command-line flags: --verbose --show-traceback 
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: 3.11.2
- Operating system and version: macOS 13.1 (22C65) M1

**Comment by AlexWaygood** [comment] 2023-02-14 15:34
Duplicate of #14631

**Comment by AlexWaygood** [comment] 2023-02-14 15:34
A patch release with the fix should be coming soon!

**Closed by AlexWaygood** 2023-02-14 15:34 UTC
Labels: crash

**Comment by julian-r** [comment] 2023-02-14 15:48
Thank you! You are doing awesome work! :)
