### ISSUE TITLE
*args leads to  "error: Too many positional arguments" for print()

### ISSUE THREAD

**Issue by jdelic** [python/mypy#2081] opened 2016-09-01 20:59 UTC
I apologize for the unspecific title, but I haven't yet really dug into this issue. Using `master` (@7b3ad9d and python/typeshed@23c44d3e respectively) on the following example:

```
bin/mypy -s --disallow-untyped-calls --disallow-untyped-defs test.py
```

```python
# test.py
from typing import Any

def printception(*args: Any, **kwargs: Any) -> None:
    print(*args, **kwargs)

def myfunc(*args: Any, **kwargs: Any) -> None:
    pass

def funception(*args: Any, **kwargs: Any) -> None:
    myfunc(*args, **kwargs)
```

leads to the following result:

```
test.py: note: In function "printception":
test.py:4: error: Too many positional arguments for "print"
```

`print()` is defined in [builtins.py#L709](https://github.com/python/typeshed/blob/23c44d3e3617a0d59e29d1cf40457d39c7924a72/stdlib/3/builtins.pyi#L709)

```python
def print(*values: Any, sep: str = ' ', end: str = '\n', file: IO[str] = None, flush: bool = False) -> None: ...
```

Since `*values: Any` and `*args: Any` should be equal, this leads me to believe that there's a bug.

**Comment by elazarg** [comment] 2016-09-10 23:55
This was actually a duplicate of #142 and was fixed in #2099

**Closed** 2016-09-11 00:07 UTC
Labels: duplicate
