### ISSUE TITLE
does not infer a list of coroutines as awaitables

### ISSUE THREAD

**Issue by carljm** [python/mypy#4170] opened 2017-10-27 04:24 UTC
Given this example:

```
import asyncio
awaitables = [one(), two()]
asyncio.gather(*awaitables)
async def one() -> int: ...
async def two() -> str: ...
```

mypy gives:

```
awaitables.py:7: error: No overload variant of "gather" matches argument types [builtins.list[builtins.object*]] 
```

It seems like mypy is inferring the type of the list based on the eventual return types of the async functions, rather than based on the fact that they both return coroutines.

**Comment by gvanrossum** [comment] 2017-10-27 16:24
The problem is that Awaitable is generic. Apparently join of A[int] and A[str] is not A[Any] or A[object] but just object. I think this is a weakness in mypy's join operation that could be addressed if someone cared enough.

**Comment by ilevkivskyi** [comment] 2017-10-28 21:58
This is actually not hard to fix, we just need to add few special cases in ``join.join_instances`` for co-/conta- variant instances.

**Comment by yottacto** [comment] 2018-08-31 05:52
Does it fixed?

**Comment by ilevkivskyi** [comment] 2018-08-31 08:36
Not yet. Btw, we have now a more general issue about this https://github.com/python/mypy/issues/5269
So I propose to close this in favour of https://github.com/python/mypy/issues/5269 that has some ideas for fixing.

**Closed by ilevkivskyi** 2018-08-31 08:36 UTC
Labels: feature, priority-1-normal
