### ISSUE TITLE
Specific output type of default function argument incompatible with generic output

### ISSUE THREAD

**Issue by Strilanc** [python/mypy#5273] opened 2018-06-25 01:29 UTC
mypy believes that a function with a specific output type can not be used as the default value for a method expecting a function with a generic output type. It interprets the difference as a *problem* instead of as a *constraint*.

## Repro code

```python
T = TypeVar('T')

def make_zero() -> int:
    return 0

def produce_many(amount: int,
                 producer: Callable[[], T] = make_zero) -> Tuple[T, ...]:
    return tuple(producer() for _ in range(amount))
```

## Expected output

No type error. When the default value for `producer` is used, the type variable `T` is inferred to be `int`.

## Actual output

```
Incompatible default for argument "producer" (default has type "Callable[[], int]", argument has type "Callable[[], T]")
```

**Comment by ilevkivskyi** [comment] 2018-06-25 09:42
This a duplicate of https://github.com/python/mypy/issues/3737

**Closed by ilevkivskyi** 2018-06-25 09:42 UTC
