### ISSUE TITLE
Type for dataclass

### ISSUE THREAD

**Issue by ayroblu** [python/mypy#8564] opened 2020-03-20 13:57 UTC
Hi, sorry if this is answered somewhere already, there's a lot of questions on dataclasses and I didn't see this specific one, I was just wondering if there's a type for all dataclasses i.e. like:

```python
from dataclasses import asdict
from typing import DataClass

def dataclass_to_dict(dc: DataClass) -> Dict[str, Any]:
    return asdict(dc)
```

**Comment by JelleZijlstra** [comment] 2020-03-20 16:05
There isn't one. `asdict` is typed in typeshed as just `def asdict(obj: Any) -> Dict[str, Any]: ...`.

**Comment by JukkaL** [comment] 2020-03-20 17:08
Maybe we could make it possible to use a protocol that contains `__dataclass_fields__` to distinguish dataclasses on a type level? Currently mypy doesn't recognize that this attribute exists (and I'm not sure if we can rely on it being always defined).

**Comment by ethanhs** [comment] 2020-03-22 21:08
I think this is essentially a duplicate of https://github.com/python/mypy/issues/6568

**Closed by ethanhs** 2020-03-22 21:08 UTC
Labels: needs discussion
