### ISSUE TITLE
Can't alias a union of tuples

### ISSUE THREAD

**Issue by dmoisset** [python/mypy#14132] opened 2022-11-18 16:06 UTC
**Bug Report**

When I create a type alias with a union of two tuple types, I get an error about the tuple type being applied to too many generic arguments.

**To Reproduce**

```python
from typing import TypeAlias

mypair = tuple[int, int] | tuple[str, str]
```

https://mypy-play.net/?mypy=latest&python=3.10&gist=f2a322b4ac47de32fe0d3c06a2fa6fc8

**Expected Behavior**

The above program should type check correctly and define an alias

**Actual Behavior**

```
main.py:3: error: Type application has too many types (1 expected)  [misc]
Found 1 error in 1 file (checked 1 source file)
```

**Your Environment**

- mypy 0.990
- no command line flags
- no configuration file
- Python version used: 3.11

**Comment by AlexWaygood** [comment] 2022-11-18 16:25
Duplicate of #11098

**Closed by AlexWaygood** 2022-11-18 16:25 UTC
Labels: bug, topic-pep-585, topic-pep-604
