### ISSUE TITLE
`try from typing import ParamSpec except from typing_ext import ParamSpec` not working

### ISSUE THREAD

**Issue by gamecss** [python/mypy#16903] opened 2024-02-11 12:45 UTC
**Bug Report**
try-except imported ParamSpec is unusable.
```python
try:
    from typing import ParamSpec
except ImportError:
    from typing_extensions import ParamSpec
```
This makes `ParamSpec("P")` become an invaild type.

**To Reproduce**

```python
from typing import Callable

try:
    from typing import ParamSpec  # type: ignore[attr-defined,unused-ignore]
except ImportError:
    from typing_extensions import ParamSpec  # type: ignore[import,unused-ignore]

P = ParamSpec("P")

def func(arg: Callable[P, None]) -> None:
    return None
```

**Expected Behavior**
No error

**Actual Behavior**
`error: The first argument to Callable must be a list of types, parameter specification, or "..."  [valid-type]`

**Your Environment**
- OS: `Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-94-generic x86_64)`
- Mypy version used: `1.8.0 (compiled: yes)`
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): None
- Python version used: `3.8.18`

[Reproduce repository](https://github.com/gamecss/reproduce2)

**Comment by hamdanal** [comment] 2024-02-11 16:44
This way of conditional import is not currently supported by mypy. You'll have to use a version check to do the import.
This code achieves the same thing and type checks correctly by mypy:
```python
import sys
from typing import Callable

if sys.version_info >= (3, 10):
    from typing import ParamSpec
else:
    from typing_extensions import ParamSpec

P = ParamSpec("P")

def func(arg: Callable[P, None]) -> None:
    return None
```

You can read more about it here
https://mypy.readthedocs.io/en/stable/runtime_troubles.html#using-new-additions-to-the-typing-module

**Comment by AlexWaygood** [comment] 2024-02-12 13:28
Duplicate of #14220

**Closed by AlexWaygood** 2024-02-12 13:28 UTC
Labels: bug

**Comment by gamecss** [comment] 2024-02-12 13:32
Hmm... it doesn't works very well.
Once I use `from sys import ...`:
```python
from sys import version_info

if version_info >= (3, 10):
    from typing import ParamSpec
else:
    from typing_extensions import ParamSpec
```
Mypy says `6:5: error: Incompatible import of "ParamSpec" (imported name has type "type[typing_extensions.ParamSpec]", local name has type "type[typing.ParamSpec]")  [assignment]`

**Comment by AlexWaygood** [comment] 2024-02-12 13:38
Correct. You need to do this:

```py
import sys

if sys.version_info >= (3, 10):
    from typing import ParamSpec
else:
    from typing_extensions import ParamSpec
```

You can't do `from sys import version_info` and expect mypy to understand it in the same way, I'm afraid. It doesn't have the ability to understand arbitrary constructs like this; only a small selection of special-cased constructs are supported. See the relevant section in PEP 484: https://peps.python.org/pep-0484/#version-and-platform-checking
