### ISSUE TITLE
How to get inferred type of arbitrary names in AST?

### ISSUE THREAD

**Issue by tmshn** [python/mypy#8977] opened 2020-06-09 14:45 UTC
I love the great power of static-typing mypy provides, and am planning to develop some code formatter/linter which makes use of type information.
However, there is little information about how to use mypy programmatically, especially how to extract type inference of source code.

Here's minimal example: I want to know type of `world` (if possible)

```python
def greet() -> str:
    world = "世界"  # <- Is it possible to know inferred type of `world`?
    return f"Hello, {world}"

greeting = greet()
print(greeting)
```

Here's what I tried

```python
>>> # above files is located at `snippets/main.py`
>>> files, opt = process_options(['snippets'])
>>> result = build(files, options=opt)
>>> result.graph['main'].load_tree()
>>> result.graph['main'].tree
<mypy.nodes.MypyFile at 0x103f55230>

>>> result.graph['main'].tree.names['greet']
<mypy.nodes.SymbolTableNode at 0x105184750>

>>> result.graph['main'].tree.names['greet'].node
<mypy.nodes.FuncDef at 0x105fb52c0>

>>> result.graph['main'].tree.names['greet'].node.body
<mypy.nodes.Block at 0x10418c590>

>>> result.graph['main'].tree.names['greet'].node.body.body
[]  # <- why is this empty???
```

* Are you reporting a bug, or opening a feature request?
    * No, it's a question
* What is the actual behavior/output?
    * Example shown above
* What is the behavior/output you expect?
    * In the example above, I expected the block body to contain some statements (assignment and return)
* What are the versions of mypy and Python you are using?
  Do you see the same issue after installing mypy from Git master?

```console
$ poetry run python -V
Python 3.7.7
$ poetry run mypy -V
mypy 0.780
```

* What are the mypy flags you are using? (For example --strict-optional)
    * Nothing

**Comment by Kangaroux** [comment] 2020-06-09 17:52
Would this be what you're looking for? https://mypy.readthedocs.io/en/stable/common_issues.html#reveal-type

**Comment by tmshn** [comment] 2020-06-10 02:17
I haven't know there's such functionality!
...but, hmmm, it requires to modify target code before mypy runs. That's not I want.

**Comment by 13570248114** [comment] 2020-06-10 07:10
i want to know how to extract type inference of source code too, if you solve it , please tell me

**Comment by 13570248114** [comment] 2020-06-11 08:56
> I love the great power of static-typing mypy provides, and am planning to develop some code formatter/linter which makes use of type information.
> However, there is little information about how to use mypy programmatically, especially how to extract type inference of source code.
> 
> Here's minimal example: I want to know type of `world` (if possible)
> 
> ```python
> def greet() -> str:
>     world = "世界"  # <- Is it possible to know inferred type of `world`?
>     return f"Hello, {world}"
> 
> greeting = greet()
> print(greeting)
> ```
> 
> Here's what I tried
> 
> ```python
> >>> # above files is located at `snippets/main.py`
> >>> files, opt = process_options(['snippets'])
> >>> result = build(files, options=opt)
> >>> result.graph['main'].load_tree()
> >>> result.graph['main'].tree
> <mypy.nodes.MypyFile at 0x103f55230>
> 
> >>> result.graph['main'].tree.names['greet']
> <mypy.nodes.SymbolTableNode at 0x105184750>
> 
> >>> result.graph['main'].tree.names['greet'].node
> <mypy.nodes.FuncDef at 0x105fb52c0>
> 
> >>> result.graph['main'].tree.names['greet'].node.body
> <mypy.nodes.Block at 0x10418c590>
> 
> >>> result.graph['main'].tree.names['greet'].node.body.body
> []  # <- why is this empty???
> ```
> 
> * Are you reporting a bug, or opening a feature request?
>   
>   * No, it's a question
> * What is the actual behavior/output?
>   
>   * Example shown above
> * What is the behavior/output you expect?
>   
>   * In the example above, I expected the block body to contain some statements (assignment and return)
> * What are the versions of mypy and Python you are using?
>   Do you see the same issue after installing mypy from Git master?
> 
> ```
> $ poetry run python -V
> Python 3.7.7
> $ poetry run mypy -V
> mypy 0.780
> ```
> 
> * What are the mypy flags you are using? (For example --strict-optional)
>   
>   * Nothing

I do something in mypy/build.py,  lineno = 2151, it work~
```
            # if not manager.options.fine_grained_incremental and not manager.options.preserve_asts:
            #     free_tree(self.tree)
```
This is my test and the rest:
```
def greet() -> str:
    world = "hello"
    hi = 1
    t = time.time()
    r = random.randint(0, 10)
    return "Hello, world"
```
```
print(result.graph['main'].tree.names['greet'].node.body.body)

[<mypy.nodes.AssignmentStmt object at 0x7ff0dbdf68f0>, <mypy.nodes.AssignmentStmt object at 0x7ff0dbdf69b0>, <mypy.nodes.AssignmentStmt object at 0x7ff0dbdf6a10>, <mypy.nodes.AssignmentStmt object at 0x7ff0dbdf6b30>, <mypy.nodes.ReturnStmt object at 0x7ff0dbdf6bf0>]
```

**Comment by tmshn** [comment] 2020-06-11 14:10
@13570248114 Thank you, it's a great progress!

I was able to get statements in the function body, too, by setting `opt.preserve_asts = True` before passing it to `build`.

---

Let me point out one thing for those who reading: if you have run mypy previously, you have to delete it (or somehow ignore that). Otherwise, mypy uses that, which might not contain those statements information.

Just `rm -r .mypy_cache` will do for quick test, but need to think some better handling of this once I write program...

**Comment by tmshn** [comment] 2020-06-11 14:19
Or we should set `fine_grained_incremental` so that mypy holds "fine grained" cache, but it seems very experimental feature (and only avaialble for daemon mode?)
I'll take a look (on weekend, maybe...)

**Comment by 13570248114** [comment] 2020-06-11 15:06
@tmshn if you have good idea to handle .mypy_cache,  please tell me, I  am doing the same thing as you now

**Comment by tmshn** [comment] 2020-06-12 16:43
Okay, some findings

- If cache is used (for that tree), you cannot get those statements
- If you specify `opt.fine_grained_incremental = True`, it **_does not_** use cache and always gives desired result
- If you specify `opt.preserve_asts = True` **_and_** cache is not used, then you can get desired result

**Comment by tmshn** [comment] 2020-06-12 16:44
Mistakenly closed

**Comment by tmshn** [comment] 2020-06-12 16:58
Daemon mode (dmypy) runs other process to handle type checking, and has very limited variety of interface available for client (through IPC). It seems hard to use my usecase.

**Comment by JelleZijlstra** [comment] 2022-03-19 16:01
Duplicate of #4868

**Closed by JelleZijlstra** 2022-03-19 16:01 UTC
