### ISSUE TITLE
`self` argument is not assignable to variable typed as `Self`

### ISSUE THREAD

**Issue by DetachHead** [python/mypy#17760] opened 2024-09-12 04:57 UTC
```py
from typing import Self

class Foo:
    def foo(self) -> None:
        asdf: Self = self
```
```
main.py:5: error: Incompatible types in assignment (expression has type "Foo", variable has type "Self")  [assignment]
Found 1 error in 1 file (checked 1 source file)
```
[playground](https://mypy-play.net/?mypy=latest&python=3.12&flags=show-error-codes%2Cstrict%2Ccheck-untyped-defs%2Cdisallow-any-decorated%2Cdisallow-any-expr%2Cdisallow-any-explicit%2Cdisallow-any-generics%2Cdisallow-any-unimported%2Cdisallow-incomplete-defs%2Cdisallow-subclassing-any%2Cdisallow-untyped-calls%2Cdisallow-untyped-decorators%2Cdisallow-untyped-defs%2Cno-implicit-reexport%2Clocal-partial-types%2Cwarn-redundant-casts%2Cwarn-return-any%2Cwarn-unreachable%2Cwarn-unused-configs%2Cwarn-unused-ignores&gist=d40f340394baec52a7ef3fb35c99d123)

**Comment by JamesParrott** [comment] 2024-09-12 10:44
I agree this could be improved.  FYI, typing `self: Self` works:

https://mypy-play.net/?mypy=latest&python=3.12&flags=show-error-codes%2Cstrict%2Ccheck-untyped-defs%2Cdisallow-any-decorated%2Cdisallow-any-expr%2Cdisallow-any-explicit%2Cdisallow-any-generics%2Cdisallow-any-unimported%2Cdisallow-incomplete-defs%2Cdisallow-subclassing-any%2Cdisallow-untyped-calls%2Cdisallow-untyped-decorators%2Cdisallow-untyped-defs%2Cno-implicit-reexport%2Clocal-partial-types%2Cwarn-redundant-casts%2Cwarn-return-any%2Cwarn-unreachable%2Cwarn-unused-configs%2Cwarn-unused-ignores&gist=f8ed2c5a1271e07d676f60f1ba6d06a1

**Comment by brianschubert** [comment] 2024-09-26 01:26
I took a stab at making `self` have an implicit type of `Self` instead of `Foo` to see what would happen (for posterity sake, the relevant logic is [here](https://github.com/python/mypy/blob/7f3d7f8f10938618bcf8648d92f6a3da0a01117f/mypy/semanal.py#L1041-L1050)). 

It turns out there's a test against that:

https://github.com/python/mypy/blob/f6520c84746072e72e8a017963d3d2a3a9361771/test-data/unit/check-selftype.test#L1815-L1830

I'm not sure I understand the comment about this being a PEP 484 requirement. It seems that pyright gets away making the type of an unannotated `self` compatible/identical to `Self`: [Pyright playground](https://pyright-play.net/?pythonVersion=3.12&strict=true&code=GYJw9gtgBALgngBwJYDsDmUkQWEMoDKApgDbACwAUFQMYkCGAzo1AGJhgBcVUvUAJkWBRgHABSNSwAJRQAtAD4oAOTAoi3Sn21QQRAG5F6JAPrwERCVOk8dvAB6dCUqAF4oksrbt7Dxs4iW9tJAA)

**Comment by hauntsaninja** [comment] 2024-09-27 01:52
There's a sentence in PEP 484 about not needing to annotate self and treat it as the type of the containing class. Looks like that sentence is in the current spec too and we should maybe change that: https://typing.readthedocs.io/en/latest/spec/annotations.html#annotating-instance-and-class-methods

I don't think that's too much of an issue though, I seem to remember folks were concerned about performance. Let me dig up a reference...

**Comment by hauntsaninja** [comment] 2024-09-27 02:02
Yeah, see https://github.com/python/mypy/issues/14075 (closing this as a duplicate of that)

**Closed by hauntsaninja** 2024-09-27 02:02 UTC
Labels: bug

**Comment by hauntsaninja** [comment] 2024-09-27 02:03
Let's also change the spec to be clearer about this https://github.com/python/typing/pull/1860
