### ISSUE TITLE
Generic NamedTuple not working

### ISSUE THREAD

**Issue by phdowling** [python/mypy#5112] opened 2018-05-25 13:56 UTC
First of all, I hope this is the right place for this, if not, just let me know.

I'm trying to create a generic version of a NamedTuple, as follows:
```python
T1 = TypeVar("T1")
T2 = TypeVar("T2")

class Group(NamedTuple, Generic[T1, T2]):
    key: T1
    group: List[T2]

g = Group(1, [""])  # expecting type to be G[int, str]
```
However, I get the following error:
```TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases```

I'm not sure how else to achieve what I'm trying to do here, or if this might be a bug in the typing mechanism on some level.

Any help?

**Comment by ilevkivskyi** [comment] 2018-05-25 14:51
Generic tuple types are not supported in mypy, see https://github.com/python/mypy/issues/685

In Python 3.7 this should work at runtime, but mypy will still not be type check this. Closing as a duplicate of https://github.com/python/mypy/issues/685

**Closed by ilevkivskyi** 2018-05-25 14:51 UTC
