### ISSUE TITLE
Option to disallow comment-based annotation syntax

### ISSUE THREAD

**Issue by lambdanis** [python/mypy#5538] opened 2018-08-30 00:04 UTC
When running mypy on python>=3.5 codebase, it checks types specified with python3 syntax as well as those specified with comment syntax (erroring on duplicated annotations).

I think it would be useful to have a flag (e.g. `--disallow-comment-syntax`, default to false) that causes mypy to error on comment type annotations. It could help when migrating annotated codebase from python2 to python3. It could also prevent inserting comment annotations into a project using only python3 syntax.

**Comment by gvanrossum** [comment] 2018-08-30 00:47
What use do you have for forbidding type comments? AFAIK there's no downside to leaving them in (other than triggering some people's OCD :-).

Instead you may want to invest in a tool that converts type comments to annotations. Perhaps you can help completing https://github.com/ilevkivskyi/com2ann? (It currently only translates type comments on variable assignments.)

**Comment by JelleZijlstra** [comment] 2018-08-30 04:04
I think we had an issue about this before and concluded that it was out of scope for mypy, because it's very easy to just do `grep '# type: (?!ignore)'` or something on your codebase to find type comments.

**Comment by ethanhs** [comment] 2018-08-30 05:59
Yes, this is a duplicate of https://github.com/python/mypy/issues/5137.

I am going to close this as a duplicate/out of scope.

**Closed by ethanhs** 2018-08-30 05:59 UTC

**Comment by lambdanis** [comment] 2018-08-30 23:40
Thank you for the responses, I didn't find this previous issue.

My reason to disallow type comments is indeed to make sure the code is consistent. I thought it would be nice to have it checked by mypy as it's already run on CI in many projects, but you're right, adding a separate check using grep would be very easy as well.

Thanks Guido for the link! I'll take a look at this project.
