### ISSUE TITLE
TypedDict gets converted into something weird with TypeVar

### ISSUE THREAD

**Issue by Dreamsorcerer** [python/mypy#12609] opened 2022-04-17 12:56 UTC
```
class D(TypedDict):
    a: int

T = TypeVar("T")
def t(t: Type[T]) -> T: ...

d = t(D)
reveal_type(d["a"])
```

The output is `Revealed type is "builtins.object*"`

If I try to annotate the argument with: `args1: D = t(D)`
Then I get a weird error: `Incompatible types in assignment (expression has type "D", variable has type "D")`

It seems that the return type of the function is some modified version of `D` where all the values have been reduced to `object`.

Not sure if this might be related to #9003 or #8620.

- Mypy version used: 0.942
- Python version used: 3.8/3.9

**Comment by AlexWaygood** [comment] 2022-04-17 13:02
Closing as this is basically a duplicate of #12385 (it has the same root cause, anyhow), but feel free to add a comment to that issue.

**Closed by AlexWaygood** 2022-04-17 13:02 UTC
Labels: bug, topic-type-variables, topic-typed-dict
