### ISSUE TITLE
Mypy infers type var `E` as `Optional[E]` wrongly.

### ISSUE THREAD

**Issue by mitsuse** [python/mypy#5049] opened 2018-05-15 05:50 UTC
Mypy infers a type var `E` as `Optional[E]` wrongly.

## Input

I tried type checking on the file as below with `mypy --strict`.

```python
#!/usr/bin/env python3

from typing import Callable
from typing import Iterable
from typing import Optional
from typing import TypeVar

E = TypeVar('E')


def first(
        predicate: Callable[['E'], bool],
        iterable: Iterable['E'],
) -> Optional['E']:
    for element in iterable:
        if predicate(element):
            return element
    return None


def test() -> Optional[int]:
    l = [0, 1, 2, 3]
    return first(lambda x: x > 1, l)
```

### Expected 

I expect that type var `E` is inferred as `int` at the line 23 on the above file.

## Actual

I got an error from mypy as below:

```
first.py:23: error: Unsupported operand types for < ("int" and "Optional[int]")
```

## Other Information

I observed this behavior under the following environment:

- CPython 3.6.5
- Mypy 0.6000
- macOS 10.13.4

**Comment by ilevkivskyi** [comment] 2018-05-15 11:47
I think this is a duplicate of https://github.com/python/mypy/issues/4872 (second example in the description), feel free to reopen if you think this is a different issue.

**Closed by ilevkivskyi** 2018-05-15 11:47 UTC
