### ISSUE TITLE
Support type-safe composition pattern

### ISSUE THREAD

**Issue by pkch** [python/mypy#6311] opened 2019-02-03 19:48 UTC
Naive switching from inheritance to composition loses type safety:

```
#  Inheritance is type-safe
class X:
    def __init__(self) -> None:
        self.x = 1
        self.z = 'z'

class Y(X):
    ...

def f(y: Y) -> None:
    y.y  # error: "Y" has no attribute "y"
```

```
# Naive composition is not type safe
class X:
    def __init__(self) -> None:
        self.x = 1
        self.z = 'z'

class Y:
    def __init__(self, x: X) -> None:
        self._x = x

    # Have to annotate Any because X has many different attributes
    def __getattr__(self, a: str) -> Any:
        return getattr(self._x, a)

def f(y: Y) -> None:
    print(y.y)  # no error
```

A user could explicitly forward each attribute, but with a dozen attributes in `X`, it's unlikely they will want to.

A protocol would also work, but it's far too heavy if no other class besides `X` and `Y` implement it.

I don't see a simple solution, but composition is often so much better than inheritance, that I almost feel it's worth creating special support for that.

**Comment by oremanj** [comment] 2019-02-03 21:10
You might find https://glyph.twistedmatrix.com/2017/05/the-sororicide-antipattern.html to be an interesting read.

I am not a mypy dev, but I suspect the response is likely to be:
* if the fact that your Y is implemented using an X is part of its public interface, you may as well expose the X as a public attribute
* if not, you should proxy just the attributes that are part of your public interface

**Comment by ilevkivskyi** [comment] 2019-02-03 21:55
Duplicate of https://github.com/python/mypy/issues/5523

**Closed by ilevkivskyi** 2019-02-03 21:55 UTC
