### ISSUE TITLE
Errors when using union type aliases with `isinstance`

### ISSUE THREAD

**Issue by jrab89** [python/mypy#14242] opened 2022-12-03 23:05 UTC
**Bug Report**

I'm getting errors when using an alias of a union type as the second argument to `isinstance`

**To Reproduce**

```python
IntOrStr = int | str

foo = 0
bar = ""

if isinstance(foo, IntOrStr):
    print("foo is an IntOrStr")

if isinstance(bar, int | str):
    print("bar is an IntOrStr")
```

**Expected Behavior**

mypy shouldn't output any errors

**Actual Behavior**

```
mypy_isinstance_with_union_alias_issue.py:6: error: Parameterized generics cannot be used with class or instance checks  [misc]
mypy_isinstance_with_union_alias_issue.py:6: error: Argument 2 to "isinstance" has incompatible type "object"; expected "Union[type, UnionType, Tuple[Union[type, UnionType, Tuple[Any, ...]], ...]]"  [arg-type]
```

**Your Environment**

- Mypy version used: 0.991
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: 3.11.0

Thanks!

**Comment by ngnpope** [comment] 2024-05-03 19:23
This looks like a duplicate of #11673.

**Closed** 2024-05-03 19:35 UTC
Labels: bug, topic-pep-604, topic-type-alias
