### ISSUE TITLE
Mypy crashes with follow_imports = normal

### ISSUE THREAD

**Issue by javier-alvarez** [python/mypy#7253] opened 2019-07-23 16:33 UTC
I am using modules with no __init__.py and I think imports are not working properly. 

[mypy]
python_version = 3.7
scripts_are_modules = True
namespace_packages =True
show_traceback = True
mypy_path = .
files = **/*.py
follow_imports = normal
ignore_missing_imports = True
follow_imports_for_stubs=False
disallow_untyped_calls=False
disallow_untyped_defs=True
strict_optional=True

mypy --config-file mypy.ini --new-semantic-analyzer

The line that makes it crash:
result: float = 1 - 2 * torch.mean(intersection / sum_squares)

Please report a bug at https://github.com/python/mypy/issues
version: 0.730+dev.0a7cb9422d105c7099fdf4ef6a84765ffdcf3058
Traceback (most recent call last):
  File "\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "\Scripts\mypy.exe\__main__.py", line 9, in <module>
    sys.exit(console_entry())
  File "\lib\site-packages\mypy\__main__.py", line 8, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "\lib\site-packages\mypy\main.py", line 83, in main
    res = build.build(sources, options, None, flush_errors, fscache, stdout, stderr)
  File "\lib\site-packages\mypy\build.py", line 164, in build
    result = _build(sources, options, alt_lib_path, flush_errors, fscache, stdout, stderr)
  File "\lib\site-packages\mypy\build.py", line 224, in _build
    graph = dispatch(sources, manager, stdout)
  File "\lib\site-packages\mypy\build.py", line 2606, in dispatch
    process_graph(graph, manager)
  File "\lib\site-packages\mypy\build.py", line 2916, in process_graph
    process_stale_scc(graph, scc, manager)
  File "\lib\site-packages\mypy\build.py", line 3023, in process_stale_scc
    graph[id].type_check_first_pass()
  File "\lib\site-packages\mypy\build.py", line 2133, in type_check_first_pass
    self.type_checker().check_first_pass()
  File "\lib\site-packages\mypy\checker.py", line 285, in check_first_pass
    self.accept(d)
  File "\lib\site-packages\mypy\checker.py", line 396, in accept
    stmt.accept(self)
  File "\lib\site-packages\mypy\nodes.py", line 922, in accept
    return visitor.visit_class_def(self)
  File "\lib\site-packages\mypy\checker.py", line 1636, in visit_class_def
    self.accept(defn.defs)
  File "\lib\site-packages\mypy\checker.py", line 396, in accept
    stmt.accept(self)
  File "\lib\site-packages\mypy\nodes.py", line 987, in accept
    return visitor.visit_block(self)
  File "\lib\site-packages\mypy\checker.py", line 1832, in visit_block
    self.accept(s)
  File "\lib\site-packages\mypy\checker.py", line 396, in accept
    stmt.accept(self)
  File "\lib\site-packages\mypy\nodes.py", line 663, in accept
    return visitor.visit_func_def(self)
  File "\lib\site-packages\mypy\checker.py", line 707, in visit_func_def
    self._visit_func_def(defn)
  File "\lib\site-packages\mypy\checker.py", line 711, in _visit_func_def
    self.check_func_item(defn, name=defn.name())
  File "\lib\site-packages\mypy\checker.py", line 773, in check_func_item
    self.check_func_def(defn, typ, name)
  File "\lib\site-packages\mypy\checker.py", line 954, in check_func_def
    self.accept(item.body)
  File "\lib\site-packages\mypy\checker.py", line 396, in accept
    stmt.accept(self)
  File "\lib\site-packages\mypy\nodes.py", line 987, in accept
    return visitor.visit_block(self)
  File "\lib\site-packages\mypy\checker.py", line 1832, in visit_block
    self.accept(s)
  File "\lib\site-packages\mypy\checker.py", line 396, in accept
    stmt.accept(self)
  File "\lib\site-packages\mypy\nodes.py", line 1045, in accept
    return visitor.visit_assignment_stmt(self)
  File "\lib\site-packages\mypy\checker.py", line 1866, in visit_assignment_stmt
    self.check_assignment(s.lvalues[-1], s.rvalue, s.type is None, s.new_syntax)
  File "\lib\site-packages\mypy\checker.py", line 1974, in check_assignment
    rvalue_type = self.check_simple_assignment(lvalue_type, rvalue, lvalue)
  File "\lib\site-packages\mypy\checker.py", line 2678, in check_simple_assignment
    always_allow_any=always_allow_any)
  File "\lib\site-packages\mypy\checkexpr.py", line 3404, in accept
    typ = node.accept(self)
  File "\lib\site-packages\mypy\nodes.py", line 1708, in accept
    return visitor.visit_op_expr(self)
  File "\lib\site-packages\mypy\checkexpr.py", line 1917, in visit_op_expr
    allow_reverse=True)
  File "\lib\site-packages\mypy\checkexpr.py", line 2397, in check_op
    self.msg.add_errors(msg)
  File "\lib\site-packages\mypy\messages.py", line 96, in add_errors
    self.errors.add_error_info(info)
  File "\lib\site-packages\mypy\errors.py", line 306, in add_error_info
    self._add_error_info(file, info)
  File "\lib\site-packages\mypy\errors.py", line 278, in _add_error_info
    assert file not in self.flushed_files

**Comment by JukkaL** [comment] 2019-07-24 14:43
That line by itself doesn't seem to be enough to cause a crash -- I wasn't able to reproduce it. Could you try to create a small, self-contained example that demonstrates the crash?

**Comment by msullivan** [comment] 2019-07-24 16:28
I think that this is #4881

**Comment by JukkaL** [comment] 2019-07-25 12:24
Closing as duplicate of #4881.

**Closed by JukkaL** 2019-07-25 12:24 UTC
