### ISSUE TITLE
properties can't narrow the type of their setter

### ISSUE THREAD

**Issue by glyph** [python/mypy#9180] opened 2020-07-21 07:20 UTC
* Are you reporting a bug, or opening a feature request?

Bug, I think.  `__setattr__` should be a method like any other, right?

* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.

```python3
from typing import Optional


class NoneByDefaultButNotLater(object):

    def __init__(self) -> None:
        self._starts_as_none: Optional[str] = None

    @property
    def starts_as_none(self) -> Optional[str]:
        return self._starts_as_none

    @starts_as_none.setter
    def starts_as_none(self, value: str) -> None:
        self._starts_as_none = value


x = NoneByDefaultButNotLater()
x.starts_as_none = "test"
x.starts_as_none = None
```

* What is the actual behavior/output?

No error.

* What is the behavior/output you expect?

I would expect the last line to be an error.

* What are the versions of mypy and Python you are using?

0.782, 3.8.2

  Do you see the same issue after installing mypy from Git master?

Have not tried.

* What are the mypy flags you are using? (For example --strict-optional)
```
incremental=True
follow_imports=normal
warn_redundant_casts=True
warn_unused_ignores=True
strict_optional=True
strict_equality=True
no_implicit_optional=True
disallow_untyped_defs=True
disallow_any_generics=True
```

**Comment by dsuch** [comment] 2020-07-21 10:12
I am also interested in this use-case. It happens very often that things are set to None in ```__init__``` only but other than that they are always of meaningful values and I would very much like to learn how to express it in mypy.

Using mypy 0.790+dev.28829fbb684d7535680934b401c05698db5b4d85 and Python 3.6.9 I have only observed that the setter is somehow not taken into account - that is how I interpret it.

Here the setter expects a float but neither str nor None is rejected.

```python
from typing import Optional

class C:
    def __init__(self) -> None:
        self._x = None # type: Optional[str]

    @property
    def x(self) -> Optional[str]:
        return self._x

    @x.setter
    def x(self, value:float) -> None:
        self._x = 'zxc' # Otherwise mypy correctly reports than a float cannot be assigned to a str

c = C()
c.x = 'test'
c.x = None

```

Below, it appears that the ```c.x = 'test'``` assignment is checked against ```@property``` rather than ```@x.setter```.

```python
from typing import Optional

class C:
    def __init__(self) -> None:
        self._x = None # type: Optional[int]

    @property
    def x(self) -> Optional[bytes]:
        return self._x

    @x.setter
    def x(self, value:float) -> None:
        self._x = 123

c = C()
c.x = 'test' 
c.x = None
```

```
mypy3.py:9: error: Incompatible return value type (got "Optional[int]", expected "Optional[bytes]")
mypy3.py:16: error: Incompatible types in assignment (expression has type "str", variable has type "Optional[bytes]")
Found 2 errors in 1 file (checked 1 source file)
$
```

**Comment by JelleZijlstra** [comment] 2020-07-22 05:21
Duplicate of #3004.

**Closed by JelleZijlstra** 2020-07-22 05:21 UTC
