### ISSUE TITLE
Type inference does not work for inherited Literal properties

### ISSUE THREAD

**Issue by antonagestam** [python/mypy#6824] opened 2019-05-12 14:39 UTC
I expected mypy to be able to infer that the literal in the subtype is a subtype of the property in its ancestor. Should this be allowed? I didn't find anything in the PEP defining the behavior here, but it seems like a really useful thing to be able to do.

```python
from typing_extensions import Literal
from typing import Union


HTTPMethodName = Union[
    Literal['GET'],
    Literal['POST'],
]


class A:
    method: HTTPMethodName


class B(A):
    # works if the subclass also annotates the property
    method: HTTPMethodName = 'POST' 


class C(A):
    # error: Incompatible types in assignment (expression has type "str", base class "A" defined the type as "Union[Literal['GET'], Literal['POST']]")
    method = 'POST'
```

`setup.cfg`:
```
[mypy]
ignore_missing_imports = True
strict_optional = True
no_implicit_optional = True
check_untyped_defs = True
disallow_incomplete_defs = True
```

```bash
$ mypy --version
mypy 0.710+dev.b53dae73eebf72e3fe1f868dfa9ad008204c5701
```

**Comment by Michael0x2a** [comment] 2019-05-12 16:42
Yeah, this does seem like a bug -- I suspect we're not taking the parent type/existing type into account when determining if we're in a literal context while performing type inference.

I'll dig a little deeper into this later today.

**Comment by ilevkivskyi** [comment] 2019-05-13 10:28
@Michael0x2a I first wanted to close this as a duplicate of https://github.com/python/mypy/issues/4547, but it is up to you whether to track the effect on literal types separately.

@antonagestam You can use `Literal['GET', 'POST']` instead of the union.

**Comment by hiaselhans** [comment] 2022-10-12 21:27
mypy also fails to infer the type as literal for this simple example:


``` python
from typing import Literal


def test(a: Literal["a", "b"]) -> None:
    return a + "-test"


def test2() -> None:
    x="a"
    test(x) # error: Argument 1 to "test" has incompatible type "str"; expected "Literal['a', 'b']"
```

**Comment by antonagestam** [comment] 2022-10-13 06:12
@hiaselhans That's a quite different issue, and I think it's to be considered. FWIW, it works if you make `x` final.

**Comment by erictraut** [comment] 2023-08-11 00:48
This bug appears to have been fixed. The error is no longer emitted by the latest version of mypy.

**Closed** 2023-08-12 07:47 UTC
Labels: priority-1-normal, topic-usability, false-positive, topic-literal-types
