### ISSUE TITLE
non-contiguous @property definitions don't work

### ISSUE THREAD

**Issue by ddfisher** [python/mypy#1713] opened 2016-06-15 21:17 UTC
Mypy's parser combines all contiguous decorated function definitions with the same name into an `OverloadedFuncDef`.  Mypy relies on this behavior later e.g. when understanding  \@property checks.

So if you write:

``` py
class C:
  @property
  def x(self) -> str: pass

  z = 0  # or any other irrelevant definition

  @x.setter
  def x(self, str) -> None: pass
```

mypy complains:

```
test.py: note: In class "C":
test.py:7: error: Callable[[C], str] has no attribute "setter"
```

**Comment by ddfisher** [comment] 2016-06-15 21:18
Came across this while investigating #1708.

**Comment by ddfisher** [comment] 2016-06-15 23:50
I'm pretty sure this will also be a problem if e.g. the setter method has a different name.

**Comment by carljm** [comment] 2017-06-04 20:51
This is a duplicate of #1465.

**Comment by ilevkivskyi** [comment] 2017-06-04 21:00
Indeed, this looks like a duplicate.

**Closed by ilevkivskyi** 2017-06-04 21:00 UTC
