### ISSUE TITLE
mypy doesn't complain about Forward References

### ISSUE THREAD

**Issue by rowillia** [python/mypy#1025] opened 2015-11-30 17:56 UTC
The following code passes through mypy no problem:

``` py
class Foo:
    def __init__(self):
        self.foo = 123

    def get_me(self) -> Foo:
        return self
```

According to https://www.python.org/dev/peps/pep-0484/#forward-references, this should be written as:

``` py
class Foo:
    def __init__(self):
        self.foo = 123

    def get_me(self) -> 'Foo':
        return self
```

**Comment by JukkaL** [comment] 2015-12-01 04:21
Yeah, mypy should catch this issue. I think that there may be a duplicate issue about this open already. At least I remember a discussion about this.

**Comment by ilevkivskyi** [comment] 2017-09-29 09:18
Duplicate of #3088

**Closed by ilevkivskyi** 2017-09-29 09:18 UTC
Labels: bug
