### ISSUE TITLE
Detect unbound variable access

### ISSUE THREAD

**Issue by rowillia** [python/mypy#2482] opened 2016-11-23 17:33 UTC
```python
if False:
    foo = 'hello world'
reveal_type(foo)  # Revealed type is 'builtins.str'
```

In the above example, `foo` should be undefined as not all branches define `foo`

**Comment by rwbarton** [comment] 2016-11-23 17:39
Duplicate of #2400.

**Closed by rwbarton** 2016-11-23 17:39 UTC
