### ISSUE TITLE
[stubgen] Union is not defined

### ISSUE THREAD

**Issue by matejsp** [python/mypy#13779] opened 2022-09-30 06:43 UTC
Another stubgen issue

Stubgen for following code:
```
def get_country_code(country_code):
    # type: (str) -> str | None
```

generated:
```
def get_country_code(country_code: str) -> Union[str, None]: ...
```

But Union is not defined as import.

**Your Environment**

- Mypy version used: v0.981
- Mypy command-line flags: /
- Mypy configuration options from `mypy.ini` (and other config files): /
- Python version used: 3.8.13

**Comment by hauntsaninja** [comment] 2022-09-30 06:57
Duplicate of https://github.com/python/mypy/issues/12929

**Closed by hauntsaninja** 2022-09-30 06:57 UTC
Labels: bug
