### ISSUE TITLE
Name already defined when importing in try ... except

### ISSUE THREAD

**Issue by ilevkivskyi** [python/mypy#2556] opened 2016-12-12 14:31 UTC
If I write:
```python
try:
    import collections.abc as collections_abc
except ImportError:
    import collections as collections_abc
```
Then I get:
```
Name 'collections_abc' already defined
```
This is similar to what happens in conditional class definition in #1874

**Comment by JukkaL** [comment] 2016-12-12 16:18
This is a duplicate of #1153.

**Closed by JukkaL** 2016-12-12 16:18 UTC
