### ISSUE TITLE
Mypy cannot infer type of `[[], [1]]`

### ISSUE THREAD

**Issue by squiddy** [python/mypy#2255] opened 2016-10-14 20:43 UTC
mypy 0.4.5, CPython 3.4.4

Running the code with mypy results in an error:

``` python
x = [[], [1]]
for b in x:
    reveal_type(b) # error: Revealed type is 'builtins.object*'
    b + [1]  # error: Unsupported left operand type for + ("object")
```

This might be me misunderstanding the type system, but I would have expected mypy to ask for type annotations if it can't infer the type, e.g.:

>  error: Need type annotation for variable

I'm also wondering why it infers an object, when it could (should?) be a list instead.

**Comment by gvanrossum** [comment] 2016-10-14 20:52
Thanks for the report. It's not directly related to the `for` loop, it's just that in this case the item type of the outer list is inferred as the join of (the types of) `[]` and `[1]` and for obscure reasons that becomes object instead of list. E.g.
```python
a = [[], [1]]
reveal_type(a)
```
shows that the type of `a` is `builtins.list[builtins.object*]`.

You're not getting the error `Need type annotation for variable` because that is only used for "partial types" (that's a mypy-internal term), and partial types are only inferred for variables directly assigned from `None` or an empty container. Here we've got something more complicated and it tries to directly infer a type for the outer list, and failing to notice the similarity between an empty list and a list of integers.

I think we can fix this though I'm not sure how important it is or how soon it'll happen.

**Comment by rwbarton** [comment] 2016-10-15 17:31
The workaround is to add an explicit type signature to `x`:
```
x = [[], [1]] # type: List[List[int]]
```

**Comment by gvanrossum** [comment] 2016-10-20 22:01
Since this can be worked around by adding annotations I don't consider this very urgent, and it's hard to fix (see the closed PR :-).

**Comment by Alberth289346** [comment] 2020-05-15 11:48
Looks like the same issue as #5045

**Comment by ilevkivskyi** [comment] 2023-09-14 22:31
Duplicate of https://github.com/python/mypy/issues/230

**Closed by ilevkivskyi** 2023-09-14 22:31 UTC
Labels: bug, priority-2-low, false-positive
