### ISSUE TITLE
`Only concrete class can be given where "Type[Abstract]" is expected` when creating a list comprehension of an ABC's concrete subclasses

### ISSUE THREAD

**Issue by CalebMDMI** [python/mypy#16442] opened 2023-11-09 22:16 UTC
I'm getting an error when creating a list of classes using a comprehension. The classes are concrete subclasses of an abstract base class.

```python
from abc import ABC, abstractmethod
from typing import Type

class Abstract(ABC):
    @abstractmethod
    def method(self):
        ...

class Concrete1(Abstract):
    def method(self):
        pass

class Concrete2(Abstract):
    def method(self):
        pass

literal_registry: list[Type[Abstract]] = [Concrete1, Concrete2]  # no error

generated_registry: list[Type[Abstract]] = [
    cls for cls in (Concrete1, Concrete2)  # error: Only concrete class can be given where "Type[Abstract]" is expected  [type-abstract]
]
```
This error disappears if I remove the `@abstractmethod` decorator.

There is also no error if I only iterate over a tuple with only one element, like so:

```python
generated_registry: list[Type[Abstract]] = [cls for cls in (Concrete1,)]  # no error
```
 
- Mypy version used: 1.3.0
- Python version used: 3.10.5

**Comment by AlexWaygood** [comment] 2023-11-09 22:19
Duplicate of #3115, I think

**Closed by AlexWaygood** 2023-11-09 22:19 UTC
Labels: bug, topic-join-v-union

**Comment by CalebMDMI** [comment] 2023-11-09 22:22
Yep, looks like it. Sorry about that. Searched around but couldn't find anything.

**Comment by joooeey** [comment] 2024-08-12 16:36
The code above raises no errors now. I just checked a similar case, where the newest version of MyPy is not great at inferring the correct type:

```
from abc import ABC, abstractmethod
from typing import Type

class Abstract(ABC):
    @abstractmethod
    def method(self):
        ...

class Concrete1(Abstract):
    def method(self):
        pass

class Concrete2(Abstract):
    def method(self):
        pass

list_of_concrete_classes: list[Type[Abstract]] = [Concrete1, Concrete2]  # mandatory type hint

index: int = 1

one_concrete_class = list_of_concrete_classes[index]

def function(cls: type[Abstract]):
    ...

function(Concrete1)  # no error
function(one_concrete_class)  # error [type-abstract] if the mandatory type hint is missing
```

The annotation for `list_of_concrete_classes` is necessary here to silence MyPy.
