### ISSUE TITLE
Default parameters for arguments of generic type do not typecheck

### ISSUE THREAD

**Issue by rkr-at-dbx** [python/mypy#4261] opened 2017-11-17 21:05 UTC
In the following example, the marked line does not typecheck:

```
from typing import Generic, TypeVar

_U = TypeVar('_U')

class Thing(Generic[_U]):
    def __init__(self, u):
        # type: (_U) -> None
        pass

def foo(param=3):
    # type: (_U) -> Thing[_U]
    return Thing(param)  # <--
```

This results in:
```error: Incompatible default for argument "param" (default has type "int", argument has type "_U")```, even though `int` is a valid value for `_U`.

**Comment by ilevkivskyi** [comment] 2017-11-17 21:15
Duplicate of https://github.com/python/mypy/issues/3737.

(https://github.com/python/mypy/issues/4236 is also related).

**Closed by ilevkivskyi** 2017-11-17 21:15 UTC
