### ISSUE TITLE
Command line checking of typeshed stubs is inconsistent between -p and -m

### ISSUE THREAD

**Issue by turlando** [python/mypy#9809] opened 2020-12-16 08:32 UTC
**Bug Report**

mypy doesn't seem to correctly find the modules inside a package.

**To Reproduce**

1. Install mypy
2. `mypy -m logging` returns `Success: no issues found in 1 source file`
3. `mypy -p logging` returns `Can't find package 'logging'`

**Expected Behavior**

As per documentation it should recursively check all the modules contained in the package.

**Actual Behavior**

mypy can't find the package.

**Your Environment**

- Mypy version used: 0.790
- Mypy command-line flags: _none_
- Mypy configuration options from `mypy.ini` (and other config files): _none_
- Python version used: 3.8.6
- Operating system and version: Linux x64

**Comment by gvanrossum** [comment] 2020-12-16 17:43
Reproduced with Python 3.9 on master.

**Comment by hauntsaninja** [comment] 2020-12-16 20:40
The difference here comes down to this TODO: https://github.com/python/mypy/blob/990b6a6f03ad82c10cb8edbe70508b943336f7f3/mypy/main.py#L940
BuildManager uses slightly different search paths, in particular, it'll also look in typeshed: https://github.com/python/mypy/blob/990b6a6f03ad82c10cb8edbe70508b943336f7f3/mypy/build.py#L211

As far as I can tell, the difference doesn't matter too much, since I'm not sure that most users would be expecting mypy to check the typeshed stub with a command like `mypy -m logging` (which is what is happening). To my first glance, the obvious sounding fix of using the same search paths in BuildManager and main.py doesn't work, since BuildManager's search paths depend on the BuildSources, which is what main.py is producing.

An alternative fix is to use `cache.find_module` in main.py to get a BuildSource in the `-m` case, instead of just directly constructing the BuildSource. This would mean that we could make `mypy -m logging` also error.

**Comment by turlando** [comment] 2020-12-17 07:27
@hauntsaninja Thank for your reply. I just want to point out that this issue is not strictly related to the stdlib typesheds. I found out this while working on a personal project and narrowed it down to a simple reproducible test case on Python's stdlib. I should have been clearer in the first place.

As far as I tested, this issue applies to any case. [Here](https://github.com/turlando/mypy-test) you can find a simple test project. `-m` works perfectly while `-p` fails.

**Comment by hauntsaninja** [comment] 2020-12-17 16:53
Thanks for the clarification / the repro! This was fixed in https://github.com/python/mypy/pull/9387 by huguesb :-)

**Comment by turlando** [comment] 2020-12-17 17:09
Thank you for pointing it out. Looking at the merge date I thought that that patch did make it into v0.790 but looking the history more carefully it doesn't seem to be the case.

**Closed** 2022-05-01 21:08 UTC
Labels: bug, priority-2-low, topic-configuration
