### ISSUE TITLE
Module '<namespace package>' has no attribute '<module/pkg in namespace>'

### ISSUE THREAD

**Issue by jaraco** [python/mypy#9619] opened 2020-10-20 16:17 UTC
**Bug Report**

Attempting to run mypy on `jaraco.ui`, I'm getting an error:

```
_________________________________________________ jaraco/ui/cmdline.py _________________________________________________
5: error: Module 'jaraco' has no attribute 'text'
```

Here is the [pertinent code](https://github.com/jaraco/jaraco.ui/blob/10e844c03f3afb3d37bd5d727ba9334af2547fcf/jaraco/ui/cmdline.py#L5), namely:

```
from jaraco import text
```

The module `text` is supplied by a separate package [jaraco.text](https://pypi.org/project/jaraco.text). The `jaraco` namespace uses the `pkgutil` style namespaces (mostly for historical reasons as the code is Python 3-only now, but could still interact with older builds).

This issue is related to #9393, although that issue indicates a different failure mode. Also possibly relevant #6385, #7029.

**To Reproduce**

```
git clone https://github.com/jaraco/jaraco.ui
cd jaraco.ui
git checkout eacca37
tox -- -k cmdline
```

**Expected Behavior**

mypy should recognize working implementations of extant modules and not fail.

**Actual Behavior**

Error reported above is emitted.

**Your Environment**

- Mypy version used: 0.790
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files):
  ignore_missing_imports = True
- Python version used: 3.9.0
- Operating system and version: macOS 10.15

**Comment by jaraco** [comment] 2020-10-20 19:27
Interestingly, even though I've started running mypy on all of the projects I maintain, including many importing the `jaraco.*` namespace, only this one line has given me grief, so the issue may be isolated to the `from <namespace> import <module>` syntax.

**Comment by vbarbaresi** [comment] 2020-10-25 10:18
The `tox` command didn't work for me, I ran `pip install . mypy` and 
`python -m mypy . --ignore-missing-imports`
Then I was able to reproduce the issue with mypy v0.790

I tried using mypy from the latest master branch: there's a different error pointing to the source of the problem:
```
python -m mypy . --ignore-missing-imports
venv/lib/python3.8/site-packages/jaraco/__init__.py: error: Duplicate module named 'jaraco' (also at './jaraco/__init__.py')
venv/lib/python3.8/site-packages/jaraco/__init__.py: error: Are you missing an __init__.py?
```
I traced it back to https://github.com/python/mypy/pull/9614 (which is related to one of the issues you mentioned)

It doesn't really solve the original issue though, it reappears when running:
`mypy jaraco/ui/cmdline.py` or `mypy -p jaraco`
Adding `--namespace-packages` doesn't change anything
I don't know how to fix that, it seems tricky

**Comment by hauntsaninja** [comment] 2022-08-03 07:33
This is a duplicate of https://github.com/python/mypy/issues/9393

**Closed by hauntsaninja** 2022-08-03 07:33 UTC
Labels: bug

**Comment by jaraco** [comment] 2022-08-03 12:10
Since my original post, the `jaraco` namespace has migrated away from pkgutil-style namespaces (to native PEP 420 namespaces).
