### ISSUE TITLE
globl "type: ignore"  ignores too much

### ISSUE THREAD

**Issue by socketpair** [python/mypy#13435] opened 2022-08-16 15:08 UTC
Structure:

`sample_proj/__init__.py`:
```python
from sample_proj.commons import some_const
from sample_proj.some_file import SomeClass
```

`sample_proj/comons.py`:
```python
some_const = 'qwe'
```

`sample_proj/some_file.py`:
```python
# type: ignore

from sample_proj.commons import some_const


class SomeClass:
    def fun(self, param=some_const):
        pass
```

```
$ mypy sample_proj
sample_proj/__init__.py:2: error: Module "sample_proj.some_file" has no attribute "SomeClass"
Found 1 error in 1 file (checked 3 source files)
```

 I think it's a bug.

Removing `# type: ignore[union-attr]` helps. I wanted this comment to ignore only this exact error in the whole file.

```
$ mypy --version
mypy 0.942
$ python3 --version
Python 3.10.5

```

**Comment by hauntsaninja** [comment] 2022-08-16 16:57
Duplicate of https://github.com/python/mypy/issues/12076

**Comment by socketpair** [comment] 2022-08-16 22:24
@hauntsaninja seems it's another bug. It's not about ignoring specific rule. Please reopen

**Comment by socketpair** [comment] 2022-08-16 22:35
@hauntsaninja I have checked. Yes, just global ignore line still reproduces the bug (and I edited the example). Who to trigger for this issue ?

**Comment by hauntsaninja** [comment] 2022-08-16 22:39
I think this is just the documented behaviour? https://mypy.readthedocs.io/en/stable/common_issues.html#ignoring-a-whole-file

**Comment by socketpair** [comment] 2022-08-16 22:50
@hauntsaninja I think no:

![image](https://user-images.githubusercontent.com/1157412/184998461-e171ac38-fdc0-4e97-9596-224cf12c571b.png)


I understand as `has the effect of ignoring [all type errors in] the entire module.`

In my case, something different happens.

**Comment by hauntsaninja** [comment] 2022-08-17 19:24
Yes, in your case mypy ignores that entire module.

You probably want the ignore_errors configuration: 
https://mypy.readthedocs.io/en/stable/config_file.html#confval-ignore_errors
You can do this inline using:
https://mypy.readthedocs.io/en/stable/inline_config.html

So something like `# mypy: ignore-errors` should do what you want.

I agree that this is confusing, but not sure how to change in a backward compatible manner. (I'm also here for fun and am not personally motivated to fix confusing mypy configuration)

**Comment by socketpair** [comment] 2022-08-17 19:40
OK I will try. But could you fix the documentation? I mean correcting the ambiguity of the phrase above.

**Closed** 2022-08-26 19:28 UTC
Labels: bug, documentation, topic-type-ignore
