### ISSUE TITLE
Assignment into unpacked tuple including ignored variables unexpectedly errors

### ISSUE THREAD

**Issue by rotemdan** [python/mypy#4621] opened 2018-02-22 12:18 UTC
Sorry if duplicate! I couldn't find anything similar:
(using `mypy 0.560`)

```py
from typing import Tuple

def getTuple() -> Tuple[str, str, int]:
    return ('Hello', 'World', 123)
	
(s, _, _) = getTuple() # Error: Incompatible types in assignment 
                       # (expression has type "int", variable has type "str")
```
Seems like the unpacked tuple is inferred as `(str, str, str)`. For this case I would assume it would infer `(str, str, int)`  or `(str, Any, Any)` .

For comparison, in the more general case:
```py
(s1, s2 , i) = getTuple()
```
The receiving tuple is inferred as `(str, str, int)`.

**Comment by ilevkivskyi** [comment] 2018-02-22 12:20
Sorry for this! We have heard about this often so the priority has been raised to high.

Closing as duplicate of https://github.com/python/mypy/issues/465

**Closed by ilevkivskyi** 2018-02-22 12:20 UTC

**Comment by rotemdan** [comment] 2018-02-22 12:23
Thanks for the quick response! Sorry I couldn't find the duplicate. I didn't search with the right keywords, I guess.
