### ISSUE TITLE
Argument 2 to pop of MutableMapping has incompatible type

### ISSUE THREAD

**Issue by NiklasRosenstein** [python/mypy#10152] opened 2021-02-28 12:36 UTC
**Bug Report**

Using `MutableMapping.pop(key, default)` inconsistently results in an error for the type of the `default` argument.

**To Reproduce**

```python
import typing as t
T = t.TypeVar('T')
V = t.TypeVar('V')
def test(key: T, value: V):
  values: t.Dict[T, V] = {}
  print(values.pop(key, None))  # ok
  values.pop(key, value)        # ok
  values.pop(key, None)         # error: Argument 2 to "pop" of "MutableMapping" has incompatible type "None"; expected "V"
  values.pop(key, 42)           # error: Argument 2 to "pop" of "MutableMapping" has incompatible type "int"; expected "V"
```

**Expected Behavior**

I expect no errors when checking the above code with Mypy. The definition of `MutableMapping.pop()` allows using a different type for the `default` argument value (in which case a union of the map's value type and the default argument's type is returned).

```python
class MutableMapping(Mapping[_KT, _VT], Generic[_KT, _VT]):
    # ....
    @overload
    def pop(self, key: _KT, default: Union[_VT, _T] = ...) -> Union[_VT, _T]: ...
```

What is curious is that the line with `print()` does not result in an error, even though the `.pop()` call is the same as two lines below.

**Your Environment**

- Mypy version used: 0.782, 0.812
- Mypy command-line flags: N/a
- Mypy configuration options from `mypy.ini` (and other config files): N/a
- Python version used: CPython 3.7.3
- Operating system and version: WSL Debian 10

**Comment by JukkaL** [comment] 2021-03-05 12:28
This only seems to be an issue if the value type is a type variable. There's probably some confusion between type variables in `pop` and `values`.

**Comment by AlexWaygood** [comment] 2022-04-21 22:06
On 0.942 (and master) [you now get](https://mypy-play.net/?mypy=latest&python=3.10&gist=ff9aefb386269b280bb82ef026a57660) three false-positive errors instead of just two:

```python
import typing as t
T = t.TypeVar('T')
V = t.TypeVar('V')
def test(key: T, value: V):
  values: t.Dict[T, V] = {}
  print(values.pop(key, None))  # error: Argument 2 to "pop" of "MutableMapping" has incompatible type "None"; expected "V"
  values.pop(key, value)        # ok
  values.pop(key, None)         # error: Argument 2 to "pop" of "MutableMapping" has incompatible type "None"; expected "V"
  values.pop(key, 42)           # error: Argument 2 to "pop" of "MutableMapping" has incompatible type "int"; expected "V"
```

**Comment by bhperry** [comment] 2024-06-03 18:40
This does not appear to be fixed for dicts in 1.8.0, although I'm having trouble figuring out exactly what conditions lead to it happening. Seems fine in simple examples, but in more complex code (some of which uses typevars, other parts do not but still trigger this) I get this
```
error: Argument 2 to "pop" of "dict" has incompatible type "None"; expected "str"  [arg-type]
```

**Comment by alicederyn** [comment] 2024-12-12 11:50
I can reproduce the old error like this:

```python
import sys

values_by_name = {"one": 1, "two": 2}
for value in values_by_name.values():
  assert value > 0
if value := values_by_name.pop(sys.argv[1], None):
  print(value)
else:
  print("Not found")
```

```text
example.py:6: error: Argument 2 to "pop" of "dict" has incompatible type "None"; expected "int"  [arg-type]
```

Significantly, this only happens if mypy has already decided that the RHS of the assignment is of type `int`, which makes me believe this is just a bug in the error message that's being emitted &mdash; something to do with overload resolution? I would expect to see:

```text
example.py:6: error: Incompatible types in assignment (expression has type "int | None", variable has type "int")  [assignment]
```

**Comment by alicederyn** [comment] 2024-12-12 11:50
@bhperry Does this possibly explain what you were seeing?

**Comment by alicederyn** [comment] 2024-12-12 22:59
@finite-state-machine should this be split off to a separate issue, or leave this one open to cover it?

**Comment by brianschubert** [comment] 2024-12-13 18:10
Closing since this issue no longer reproduces as of v1.6.0 (specifically after the typeshed sync #15792).

@bhperry @alicederyn Feel free to open a new issue. At a glance, it looks like this falls in the bucket of cases where bidirectional inference can have bad results when there's a union of type variables in the return type. You'll find some related issues under the https://github.com/python/mypy/labels/topic-type-context label.

**Closed by brianschubert** 2024-12-13 18:10 UTC
Labels: bug, topic-type-variables, false-positive
