### ISSUE TITLE
When `a` has type `Any`, after `assert a is None`, the rest of the block is considered dead code

### ISSUE THREAD

**Issue by benkuhn** [python/mypy#2970] opened 2017-03-06 23:13 UTC
Steps to reproduce:

1. Check out [this repo](https://github.com/benkuhn/mypy-repro)
2. Install the packages from `requirements.txt`
3. Run `mypy repro.py` from the repo root.

Expected output:
```
repro.py:4: error: Revealed type is 'Any'
repro.py:6: error: Revealed type is 'builtins.None'
```

Actual output:
```
repro.py:4: error: Revealed type is 'Any'
```

The issue goes away if you disable strict Optional checking.

This is preventing a significant amount of our codebase from being checked right now, so I would appreciate any suggestions for a workaround!

**Comment by gvanrossum** [comment] 2017-03-06 23:29
So the crux of the repro is simply:
```python
from typing import Any, Optional

def foo(a: Any) -> None:
    reveal_type(a)
    assert a is None
reveal_type(None)
```
Thanks for reporting. This definitely is a bug. It seems related to (but is not a duplicate of) #2776.

**Comment by gvanrossum** [comment] 2017-03-06 23:31
Adding a strict-optional label since this is only a problem with strict-optional. @ddfisher any idea?

**Comment by benkuhn** [comment] 2017-03-06 23:36
As a workaround/general safety measure, is there a way to force Mypy to analyze all "dead" code after asserts? Our codebase has very little actual dead code, and comparatively many places where I'm worried that mypy would erroneously declare the code dead due to an assert like this.

**Comment by gvanrossum** [comment] 2017-03-06 23:40
I'm not aware of any. Note that it's not every assert, only very specific asserts. You could also refrain from using strict-optional for now (it's still very much experimental).

**Comment by benkuhn** [comment] 2017-03-07 02:34
OK, I couldn't help poking around to see what the issue was, and I think I may have found the right place to fix it--let me know what you think!

**Comment by benkuhn** [comment] 2017-03-09 16:12
Any thoughts on the pull request I submitted?

**Comment by gvanrossum** [comment] 2017-03-09 17:40
Yes, that I'm way behind on the queue.

**Closed** 2017-03-15 20:00 UTC
Labels: bug, topic-affects-strict-optional
