### ISSUE TITLE
`Counter` not accepted as `TypedDict`

### ISSUE THREAD

**Issue by KotlinIsland** [python/mypy#12080] opened 2022-01-27 00:02 UTC
```py
class Thing(TypedDict):
    number: int

thing: Thing = Counter({"number": 2})
```
a `Counter[T]` is a `dict[T, int]` so this seems perfectly valid to me

**Comment by erictraut** [comment] 2022-01-27 00:22
Mypy's behavior is correct here. A `dict[str, int]` is not a subtype of `TypedDict`.

The following is also a type violation.

```python
thing: Thing = dict({"number": 2})
```

**Comment by KotlinIsland** [comment] 2022-01-27 00:40
What about?
```py
thing: Thing = dict(
  cast(Thing, {"number": 2})
)
```

**Comment by hauntsaninja** [comment] 2022-02-17 09:41
Basically a duplicate of #12081

**Closed by hauntsaninja** 2022-02-17 09:41 UTC
Labels: bug, topic-typed-dict
