### ISSUE TITLE
[BUG] Type test doesn't work with indexed access

### ISSUE THREAD

**Issue by deniscostadsc** [python/mypy#9038] opened 2020-06-24 00:43 UTC
Not sure this is a actual bug or not, but reporting anyway.

I wrote a code similar to this:

```python
from typing import List, Optional


def foo(numbers: List[Optional[int]]) -> List[Optional[int]]:
    for index, number in enumerate(numbers):
        if isinstance(numbers[index], int) and numbers[index] > 2:
            pass
    return numbers
```
This code show the following error:

```
mypy_issue.py:6: error: Unsupported operand types for < ("int" and "None")
mypy_issue.py:6: note: Left operand is of type "Optional[int]"
Found 1 error in 1 file (checked 1 source file)
```

If written you change the code to something like the code bellow, the error is fixed:

```python
from typing import List, Optional


def foo(numbers: List[Optional[int]]) -> List[Optional[int]]:
    for number in enumerate(numbers):
        if isinstance(number, int) and number > 2:
            pass
    return numbers
```

Although the code is fixable, it seems to me, both versions should behave in the same way. 

[Here](https://github.com/deniscostadsc/mypy_issue) there is a docker based executable version of this code to see the error.

Python version: 3.8.3
Mypy version: 0.782
Mypy command: mypy file.py
Behaviour in git master: the same

**Comment by hauntsaninja** [comment] 2020-06-26 02:21
Dupe of #7339 and #2458

**Closed** 2020-06-26 04:45 UTC
