### ISSUE TITLE
a wrapper has ParamSpec + more args = error

### ISSUE THREAD

**Issue by hydrargyrum** [python/mypy#16402] opened 2023-11-03 16:02 UTC
**Bug Report**

The following snippet generates a `main.py:7: error: ParamSpec must have "*args" typed as "P.args" and "**kwargs" typed as "P.kwargs"  [valid-type]` error, though the suggestion is followed

It's supposed to be a wrapper that schedules a call for later (typically for dispatching to a job queue)

**To Reproduce**

https://mypy-play.net/?mypy=latest&python=3.11&gist=e0bea0d9c56d64d145b87c80bd003c77

```python
from typing import Callable, ParamSpec, TypeVar

P = ParamSpec("P")
R = TypeVar("R")


def schedule(
    func: Callable[P, R],
    useless: bool = True,
    *args: P.args,
    timeout: int = 0,
    **kwargs: P.kwargs
) -> None:
    func(*args, **kwargs)

```

**Expected Behavior**

There should be no error:
- the wrapper takes a callback, its arguments, plus some additional ones
- the wrapper calls the callback with the appropriate args (though it should schedule the call for later, but that's another story)

**Actual Behavior**

`main.py:7: error: ParamSpec must have "*args" typed as "P.args" and "**kwargs" typed as "P.kwargs"  [valid-type]`

**Your Environment**

- Mypy version used: latest, see playground
- Mypy command-line flags:
- Mypy configuration options from `mypy.ini` (and other config files): from playground
- Python version used: 3.11

**Comment by erictraut** [comment] 2023-11-03 16:21
This is related to #13966.

PEP 612, which introduced `ParamSpec` to the type system, specifies that a `*args: P.args` and `**kwargs: P.kwargs` parameter must be located next to each other. You cannot insert additional keyword arguments between them, as you have done in your example. Mypy's error message here could be improved.

**Comment by ilevkivskyi** [comment] 2023-11-13 19:39
Duplicate of https://github.com/python/mypy/issues/13966

**Closed by ilevkivskyi** 2023-11-13 19:39 UTC
Labels: bug, topic-paramspec
