### ISSUE TITLE
feature request/idea: tuple length inference from assertions/tests on len()

### ISSUE THREAD

**Issue by aecay** [python/mypy#9120] opened 2020-07-09 16:48 UTC
Consider this code:

```python
from typing import List, Any, Tuple

def fn_returning_sequence() -> List[Any]:
    return [1, 2, 3]

x = tuple(fn_returning_sequence())
assert len(x) == 3
reveal_type(x)
```

It would be nice if mypy's type inference was extended so that it knew that `x` was a `Tuple[Any, Any, Any]` rather than the less specific `Tuple[Any, ...]`.  And similarly for cases like `if len(x) == 2: ...`; in the body of the `if` mypy can be sure that `x` is a `Tuple[Any, Any]`.

(Confusingly, the actual value printed by `reveal_type` in the example is `builtins.tuple[Any]`, but as far as I can tell this is a synonym of `Tuple[Any, ...]`)

**Comment by hauntsaninja** [comment] 2020-07-11 01:18
Similar to https://github.com/python/mypy/issues/7509 and https://github.com/python/mypy/issues/8733

**Comment by JukkaL** [comment] 2020-07-22 13:58
Closing as duplicate of #8733.

**Closed by JukkaL** 2020-07-22 13:58 UTC
