### ISSUE TITLE
Mypy does not catch possibly undefined variables

### ISSUE THREAD

**Issue by Dakkaron** [python/mypy#2495] opened 2016-11-24 16:49 UTC
Mypy does not catch variables that might not be defined due to ifs and therelike:

```
if False:
	a = "Test"

print(a)
```
This happens both in Python2- and Python3-mode
I remember in an earlier version I always had to define them before the if, so that the variables are always defined:

```
a = ""

if condition:
	a = "Test"

print(a)
```

**Comment by rwbarton** [comment] 2016-11-24 17:00
Duplicate of #2400.

**Closed by rwbarton** 2016-11-24 17:00 UTC
