### ISSUE TITLE
TypedDict has no key when checking for key

### ISSUE THREAD

**Issue by Dreamsorcerer** [python/mypy#8887] opened 2020-05-25 20:32 UTC
Minimal test case:
```
[case testTaggedUnionByKey]
from mypy_extensions import TypedDict
from typing import Union
class A(TypedDict):
    foo: int
class B(TypedDict):
    bar: str
def a(a: Union[A, B]):
    return a["foo"] if "foo" in a else None
[builtins fixtures/tuple.pyi]
```

The code is checking if the key is present, so this should pass correctly, but instead fails with `error: TypedDict "B" has no key 'foo'`.

**Comment by Dreamsorcerer** [comment] 2020-10-19 14:15
Coming back to this, it looks like this should be support by the tagged union pattern documented here:
https://mypy.readthedocs.io/en/stable/literal_types.html#tagged-unions

That documentation uses different Literal values on a key, but we should be able to achieve the same thing by testing whether a key exists or not.

**Comment by Dreamsorcerer** [comment] 2020-11-13 15:44
Curiously, I can't even get the documented tagged union functionality to work in a test case, or find any code related to the feature. For example, this still fails:

```
[case testTaggedUnion]
from mypy_extensions import TypedDict
from typing import Union
from typing_extensions import Literal
class A(TypedDict):
    foo: Literal[2]
class B(TypedDict):
    foo: Literal[3]
    bar: str
def a(a: Union[A, B]):
    return a["foo"] if a["foo"] == 2 else None
[builtins fixtures/tuple.pyi]
```

**Comment by hauntsaninja** [comment] 2020-11-14 23:18
Your second example passes for me when I run mypy on it as a file; maybe you need a different fixture or something. You might be interested in https://github.com/python/mypy/pull/8151

**Comment by Dreamsorcerer** [comment] 2020-11-14 23:23
Thanks for digging that up, must just have been something wrong with the way I was running the test. I'm sure I've used the feature in my code before.

**Comment by AlexWaygood** [comment] 2022-05-03 14:52
I'm closing this issue, as the root cause of the mypy error here is discussed more precisely in #9953

**Closed by AlexWaygood** 2022-05-03 14:52 UTC
Labels: topic-typed-dict, topic-type-narrowing
