### ISSUE TITLE
signal/slot patternmaking function signatures generic

### ISSUE THREAD

**Issue by chadrik** [python/mypy#5115] opened 2018-05-27 21:26 UTC
I'm trying to design a simple signal/slot package that is pep484-compatible, but it's proving trickier than I thought.   The problem is that the type-checked signatures of the generic class's methods should vary depending on its parameterization. 

Here's a naive rough draft:

```python
# file: signal.py
from typing import Any, Callable, TypeVar, List

T = TypeVar('T')

class Signal(Callable[T, Any]):
    def __init__(self):
        self.slots: List[Callable[T, Any]] = []

    def connect(self, func: Callable[T, Any]):
        self.slots.append(func)

    def __call__(self, *args, **kwargs):
        "emit the signal"
        for slot in self.slots:
            slot(*args, **kwargs)
```

```python
# file: signal.pyi
from typing import Any, Callable, TypeVar

T = TypeVar('T')

class Signal(Callable[T, Any]):
    def connect(self, func: Callable[T, Any]) -> None: ...
```

```python
# file: main.py
from signal import Signal

IntStrSignal = Signal[[int, str]]
sig = IntStrSignal()

def cb(a: int, b: str):
    pass

sig.connect(cb)

sig(1, 'foo')
```

Any advice on the best way to proceed is greatly appreciated, esp. any low-hanging issues that could unlock this functionality. 

Related to https://github.com/python/mypy/issues/4031

edit:  removed `emit` method in favor of the callable's `__call__` method

**Comment by chadrik** [comment] 2018-05-27 21:37
It looks like I accidentally submitted this issue long before I was done editing, so if you got it by email you should click the link to the issue.  Sorry!

**Comment by JelleZijlstra** [comment] 2018-05-27 21:44
I don't know if this fixes your problem, but don't you want `Callable[[T], Any]` instead of `Callable[T, Any]`? The latter is invalid.

**Comment by chadrik** [comment] 2018-05-27 21:57
>  I don't know if this fixes your problem, but don't you want Callable[[T], Any] instead of Callable[T, Any]? The latter is invalid.

Yes, it is invalid, but that's part of the problem in terms of expressive limitations.  I don't want to limit `Signal` to callables with one argument.  I want to capture the types of *all* of the args, and use that to restrict/overload the signatures of `emit` and `connect`.  For example, in main.py I want `T` to hold `[int, str]`, such that `sig.emit(1, 'foo')` is valid and `sig.emit(1, 2)` is not.

**Comment by ilevkivskyi** [comment] 2018-05-27 22:32
This is a duplicate of https://github.com/python/typing/issues/264 (you can cast your vote in favour of special `OtherArgs` variadic type variable there, it is exactly what you want).

**Closed by ilevkivskyi** 2018-05-27 22:32 UTC
