### ISSUE TITLE
Dynamic base classes are not handled

### ISSUE THREAD

**Issue by snakescott** [python/mypy#2477] opened 2016-11-22 17:20 UTC
repro:

* set some $BASEDIR for files
* git clone https://github.com/python/typeshed.git $BASEDIR/typeshed
* cd $BASEDIR/typeshed; git checkout f36d7a3cd3a77c1199fd6cc657ea4eb4b4416e56; rm -rf third_party/2/sqlalchemy/ (note: sqlalchemy stubs are incomplete, so ignore them)
* put the following code at $BASEDIR/failure.py

```from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, String
Base = declarative_base()

class Foo(Base):
  __tablename__ = 'foo'
  key = Column(String, primary_key=True)
```

* install mypy 0.4.6
* run mypy --py2 -v -v -v --fast-parser -s --custom-typeshed-dir $BASEDIR/typeshed $BASEDIR/failure.py

Output is something like
```
failure.py:33: error: Invalid type "failure.Base"
failure.py:33: error: Invalid base class
```
when it should be clean

**Comment by gvanrossum** [comment] 2016-11-24 00:47
Simpler repro (without the typeshed/sqlalchemy stuff):
```python
from nowhere import func
Base = func()
class C(Base): pass  # errors on this line
```
Errors:
```
x.py:3: error: Invalid type "x.Base"
x.py:3: error: Invalid base class
```

**Comment by JukkaL** [comment] 2016-11-24 09:50
The reason this doesn't work is that the type of `Base` is not yet inferred during semantic analysis, and that's when we process base classes. You can add an annotation as a workaround:

```
from typing import Any

def func(): pass
Base = func()  # type: Any
class C(Base): pass  # now works

**Comment by gvanrossum** [comment] 2016-11-24 17:14
Should we close this then or update the docs somewhere? Maybe the error message could also be better.

**Comment by JukkaL** [comment] 2016-11-24 17:26
I think that we should at least see if we can make the error message better.

**Comment by snakescott** [comment] 2016-11-24 17:59
improved error message would be helpful. I did discover ```# type: Any``` as a workaround but it is good to be aware this is a known issue.

Is there a github issue I should be tracking for the semantic analysis improvement, or just watch the release notes?

**Comment by JukkaL** [comment] 2017-01-16 12:51
Let's use this issue to track both the error message and the underlying semantic analysis issue for now.

**Comment by Deimos** [comment] 2017-01-19 03:24
I seem to have hit a very similar bug that's a bit more convoluted (involving `Optional` and importing), but probably has a related base cause. It also makes it so the `Any` trick above doesn't work. It happened to me originally with sqlalchemy's `declarative_base()` as well, but this was my attempt to find a simple reproduction (Python 3.6):

file1.py:

```python
from typing import Any

Base: Any
```

file2.py:

```python
from typing import Optional
from .file1 import Base

class SubClass(Base):
    pass

def optional_return_func() -> Optional[SubClass]:
    return SubClass()

def should_fail() -> int:
    test_var = optional_return_func()
    reveal_type(test_var)

    if not test_var:
        return 1

    return 'not an int'
```

When I run mypy on this, the result is `error: Revealed type is 'builtins.None'`

The expected result should be `Revealed type is 'Union[file2.SubClass, builtins.None]'` along with an `Incompatible return value type` error, but since mypy is certain that `test_var` is `None`, it considers that unreachable.

Hope that makes sense, let me know if any more information would be helpful.

**Comment by Deimos** [comment] 2017-01-30 19:43
@JukkaL sorry for the ping, but I just wanted to check and see if you think the issue I described above is similar enough that leaving it as part of this one is good, or if I should open a new, separate issue for it.

**Comment by JukkaL** [comment] 2017-01-31 10:52
@Deimos The `builtins.None` issue seems to be fixed on github master -- can you verify that it works for you? It's unrelated to the original issue, but no need to create an issue if it already works.

**Comment by Deimos** [comment] 2017-01-31 19:55
Oh, yes, it does seem to be fixed using current github master. That's great, thanks (and sorry for bothering you about something that was already fixed).

**Comment by libre-man** [comment] 2017-07-09 22:15
But if I add a `Any` annotation the problem is that it thinks the class can be anything, so doing stuff like

```python
import typing as t
base: t.Any = make_base()
class A(base): pass

def make_list() -> t.Sequence[A]:
    return A()
```

does not yield an error which makes anything using this class (`A` in this case) not typesafe anymore.

**Comment by gvanrossum** [comment] 2017-07-10 00:03
But what would you expect? Except for a few trivial edge cases, when the base class is computed dynamically, mypy is unable to understand the structure of your class. That's why it gives an error when you use a dynamic base class -- if you shut it up using `Any`, literally "Any"thing can happen. :-)

[I changed the issue topic because it has nothing to do with sqlalchemy.]

**Comment by libre-man** [comment] 2017-07-10 01:46
I understand that mypy can't determine the class, however it might be nice to give mypy a typehint of some sort. Capturing all the possibilities of the base are probably still not possible, however it would be possible to check somethings.

I suspected that doing `Type[cls]` would do this, but this does not work. This also feels somewhat inconsistent as
```python
class A: pass
Base = A
Base2: Type[A] = A
class B(Base): pass
class C(A): pass
class D(Base2): pass
```
only gives an error for class `D` but passing `A` to a function like `def e(cls: Type[A])` works as expected.

**Comment by gvanrossum** [comment] 2017-07-10 02:10
If you have a base class that you think would make for a suitable static substitute for the dynamic base, you could try this (I am using `object` here for the static substitute):
```py
base = object
def make_base(): pass
base = make_base() # type: ignore
class C(base):
  def foo(self): pass
c = C()
c.foo()
c.bar()  # Error, proving static type checking honors the `base = object`.
```
You might also do something with `typing.TYPE_CHECKING`:
```py
from typing import TYPE_CHECKING
def make_base(): pass
if TYPE_CHECKING:
  base = object
else:
  base = make_base()
class C(base):
  def foo(self): pass
c = C()
c.foo()
c.bar()  # Error again
```

**Comment by ilevkivskyi** [comment] 2017-07-11 08:51
@libre-man 
> This also feels somewhat inconsistent

It is important to make a distinction between type aliases and variables with type ``Type[...]``:
```python
B = A  # makes a type alias
C: Type[A]  # creates a variable
```
The point is that for aliases we know the _value_ statically since type alias cannot be re-bound, so that it can be used in the type context (like an annotation or a base class). In contrast we don't know the value of a variable statically. Consider this example:
```python
class C1: ...
class C2: ...

A: Type[Union[C1, C2]]

class B(A): ...
```
it is not clear what would this mean, since one cannot subclass a union.

I like the idea of using ``TYPE_CHECKING`` proposed by Guido, since it clearly indicates the purpose.

**Comment by w0rp** [comment] 2017-09-05 09:03
I was looking for an existing GitHub issue for a problem I was having, and I think this might be the one. I've been trying to define types for Django where the stub files use generic types for `Manager` and `QuerySet`, even though the real types currently do not. It works pretty well for me, but I have encountered a problem with trying to define the `from_queryset` method, which is commonly used for creating Django `Manager` classes from QuerySet classes, with most of the methods copied across. The code looks roughly like this.

```python
from typing import Any, Generic, TypeVar

ModelType = TypeVar('ModelType')


class Foo:
    pass


class QuerySet(Generic[ModelType]):
    pass


class Manager(Generic[ModelType]):
    @classmethod
    def from_queryset(cls, queryset_class: QuerySet[Any]) -> 'Manager[ModelType]':
        ...


class Bar(Manager.from_queryset(QuerySet)):
    pass
```

That's enough code to reproduce the problem. `mypy` will complain with the "invalid base class" error for `class Bar`.

So far, my workaround is to define `Manager` and `QuerySet` classes the old way, by defining methods in two places.

**Comment by gvanrossum** [comment] 2017-09-05 14:44
@w0rp: *anything* with an expression that's not a simple class reference
will cause that error. Do you have a specific question?

**Comment by w0rp** [comment] 2017-09-05 15:14
No sorry, I just thought I'd mention my use case here in case any other Django users notice the same issue I did.

**Comment by boompig** [comment] 2018-05-30 17:59
Any updates on this issue?

**Comment by germaniumhq** [comment] 2018-11-02 07:33
This also does not work:
```py
def model(base: Any) -> Callable[...,T]:
    class ModelProxy(base):  # fails
        # ....
```

While this does:
```py
def model(base: Any) -> Callable[...,T]:
    wut: Any = base
    class ModelProxy(wut):  # works
        # ....
```

**Comment by JukkaL** [comment] 2018-11-02 10:32
@germaniumhq Created #5865 to track that particular issue.

**Comment by ilevkivskyi** [comment] 2019-02-11 08:48
Currently mypy supports writing plugins, including using `get_dynamic_class_hook()`, see [the docs](https://mypy.readthedocs.io/en/latest/extending_mypy.html#current-list-of-plugin-hooks). In particular, [SQLAlchemy plugin](https://github.com/dropbox/sqlalchemy-stubs/) already supports the definitions like in the original example. I am not sure about the [Django plugin](https://github.com/mkurnikov/django-stubs), if it doesn't support this yet, you can open an issue on their tracker.

I don't think we need to keep this open. One should either use plugins for supported frameworks, or the `if TYPE_CHECKING: ...` workaround for not yet supported ones.

**Closed by ilevkivskyi** 2019-02-11 08:48 UTC
Labels: needs discussion, priority-1-normal

**Comment by revmischa** [comment] 2019-06-18 11:21
If mypy can't parse it, it is unhelpful to say it's a type error

**Comment by w0rp** [comment] 2019-06-18 14:50
In case others are interested in the Django type checking issues I mentioned here and they find this thread, I'd like to point to this plugin for mypy: https://github.com/mkurnikov/django-stubs I haven't started using it yet, but it should solve a lot of Django type checking issues.

**Comment by dms-cat** [comment] 2019-07-11 22:24
I can't get [this](https://github.com/python/mypy/issues/2477#issuecomment-462253330) to work:

```python
if TYPE_CHECKING:
    test_mixin_class = TestCase
else:
    test_mixin_class = object


class CanCreateTestMixin(test_mixin_class):
```

I get

> Invalid base class

on the `class` line with mypy 0.711 and the following configuration:

```
[mypy]
check_untyped_defs = true
disallow_untyped_defs = true
ignore_missing_imports = true
no_implicit_optional = true
warn_redundant_casts = true
warn_return_any = true
warn_unused_ignores = true
```

**Comment by blueyed** [comment] 2019-11-07 17:57
@dms-cat 
Is this inside of a function?

Note the workaround from Guido above does not work when wrapped in a function in general:
```python
def foo():
    from typing import TYPE_CHECKING
    def make_base(): pass
    if TYPE_CHECKING:
      base = object
    else:
      base = make_base()
    class C(base):  # !! Variable "base" is not valid as a type
      def foo(self): pass
    c = C()
    c.foo()
    c.bar()  # Error again
```

Simpler:
```python
import pdb


if True:  # works
    base = pdb.Pdb

    class C(base):
        pass


def f():
    base = pdb.Pdb

    class C(base):  # Variable "base" is not valid as a type / Invalid base class "base"
        pass
```

**Comment by micahjsmith** [comment] 2020-10-03 18:09
For anyone who comes across this via the original report, a simple way to address sqlalchemy/mypy issues is to also import DeclarativeMeta.

```
from sqalalchemy.ext.declarative import declarative_base, DeclarativeMeta
Base: DeclarativeMeta = declarative_base()
...
```

**Comment by kevlarr** [comment] 2020-12-09 20:50
Thanks @micahjsmith, just ran into this for the first time (on a 2-yo project, no clue why it was never reporting before). `Base: Declarative = ...` is way better than `Base = ... # type: ignore`

**Comment by quantumpacket** [comment] 2021-04-12 14:53
Hi @micahjsmith I ended up using DeclarativeMeta as well, but I then get the following mypy error:

> models.py:9: error: Type of variable becomes "Any" due to an unfollowed import
    Base: DeclarativeMeta = declarative_base()

Did you come across this same issue?
