### ISSUE TITLE
Protocol method parameter names are not validated

### ISSUE THREAD

**Issue by ThirVondukr** [python/mypy#16546] opened 2023-11-23 12:01 UTC
**Bug Report**

Protocol method parameter names are not validated in assignment/subclasses, you seem to be able to use a different parameter name, even though it would lead to runtime errors.
In this case I'm able to use different name for parameter `a`, this works even if we explicitly inherit from a protocol

**To Reproduce**

Gist URL: https://gist.github.com/mypy-play/c286a373c6d6c8b2f0bc7f9418d9cb05
Playground URL: https://mypy-play.net/?mypy=latest&python=3.11&gist=c286a373c6d6c8b2f0bc7f9418d9cb05
```python
from typing import Protocol


class Testable(Protocol):
    def test(self, a: str) -> bool:
        ...


class Concrete:
    def test(self, b: str) -> bool:
        return bool(b)


instance: Testable = Concrete()
instance.test(a="")
```

**Expected Behavior**

`Concrete` should not be assignable to `Testable` since method signatures don't match

**Actual Behavior**

Type checking succeeds

**Your Environment**

- Mypy version used: 1.7.0
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): Empty, this is reproducable on mypy playground
- Python version used: 3.11.6

**Comment by ThirVondukr** [comment] 2023-11-26 19:20
@JelleZijlstra Sorry for pinging you, but could you please confirm my suspicion that this is a bug or not?

**Comment by AlexWaygood** [comment] 2023-11-26 19:32
I think this is a duplicate of  #6709 (or, well, it's another symptom of the broader issue that is #6709 — mypy in general doesn't check parameter names at all currently when it comes to determining if one type is a subtype of another)

**Comment by ThirVondukr** [comment] 2023-11-26 19:38
Thank you, it seems like it. I tried searching for issues related to protocols but didn't found anything

**Closed** 2023-11-26 19:39 UTC
Labels: bug

**Comment by JelleZijlstra** [comment] 2023-11-26 19:46
Alex is right, but I thought somehow that we *did* check parameter names for protocols (since they were added later). Maybe I misremembered.
