### ISSUE TITLE
Document why basestring is usually a bad idea

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#4131] opened 2017-10-18 13:12 UTC
This could go into common issues, as problems with `basestring` come up pretty frequently.

Also recommend using `Union[bytes, Text]` or `Union[bytes, str]` instead (or `AnyStr`).

**Comment by ethanhs** [comment] 2017-12-02 22:33
Closing as duplicate of #1537 since that issue has more discussion.

**Closed by ethanhs** 2017-12-02 22:33 UTC
Labels: documentation, priority-1-normal
