### ISSUE TITLE
mypy 0.620 does not recurse into namespace packages

### ISSUE THREAD

**Issue by warsaw** [python/mypy#5575] opened 2018-09-05 18:03 UTC
For regular packages, mypy recurses as documented into subdirectories:

```
$ ls -lR src
total 0
drwxrwxr-x  4 bwarsaw  wheel  128 Sep  5 11:00 flufl/

src/flufl:
total 0
-rw-rw-r--  1 bwarsaw  wheel    0 Sep  5 11:00 __init__.py
drwxrwxr-x  4 bwarsaw  wheel  128 Sep  5 11:00 foo/

src/flufl/foo:
total 0
-rw-rw-r--  1 bwarsaw  wheel  0 Sep  5 10:59 __init__.py
-rw-rw-r--  1 bwarsaw  wheel  0 Sep  5 11:00 baz.py

$ mypy src
$
```

However, if I remove the `__init__.py` from the top level namespace package, mypy fails to recurse:

```
$ rm -f src/flufl/__init__.py 
$ mypy src
There are no .py[i] files in directory 'src'
```

**Comment by ilevkivskyi** [comment] 2018-09-05 18:14
Thanks for reporting!

This is a duplicate of https://github.com/python/mypy/issues/1645 (already high priority).

**Closed by ilevkivskyi** 2018-09-05 18:14 UTC
