### ISSUE TITLE
Cannot assign real numbers to Real

### ISSUE THREAD

**Issue by DMR-coding** [python/mypy#7104] opened 2019-06-28 22:55 UTC
* Are you reporting a bug, or opening a feature request?
Reporting a bug

* Minimal repro:
```
from numbers import Real


def double(n: Real) -> float:
    return n * 2.0


print(double(1))
print(double(1.0))
```

* What is the actual behavior/output?
```
min_repro.py:8: error: Argument 1 to "double" has incompatible type "int"; expected "Real"
min_repro.py:9: error: Argument 1 to "double" has incompatible type "float"; expected "Real"
```
* What is the behavior/output you expect?
No output-- isinstance(1, Real) and isinstance(1.0, Real) are both true.

* What are the versions of mypy and Python you are using?
I am using 0.711. (I was not able to successfully install from master.)

* What are the mypy flags you are using? (For example --strict-optional)
No flags

**Comment by ilevkivskyi** [comment] 2019-08-12 13:27
Duplicate of https://github.com/python/mypy/issues/3186

**Closed by ilevkivskyi** 2019-08-12 13:27 UTC
