### ISSUE TITLE
str-bytes-safe displays position in line incorrectly

### ISSUE THREAD

**Issue by jolaf** [python/mypy#7740] opened 2019-10-17 18:13 UTC
The following code:
```python3
s = '%s%s' % (b''.decode(), b'')
```
produces the following output:
```python3
$ python3 Test.py
$ mypy --show-column-numbers --pretty --show-error-codes Test.py 
Test.py:1:15: error: On Python 3 '%s' % b'abc' produces "b'abc'"; use %r if this is a desired behavior  [str-bytes-safe]
    s = '%s%s' % (b''.decode(), b'')
                  ^
Found 1 error in 1 file (checked 1 source file)
$ mypy --version
mypy 0.740
$ python3 --version
Python 3.6.8
```
Note that the indicated position of the error in the line is pointing to the first argument (`b''.decode()`) instead of the seconds one (`b''`) which is highly misleading.

**Comment by ilevkivskyi** [comment] 2019-10-17 18:53
Duplicate of https://github.com/python/mypy/issues/7528

**Closed by ilevkivskyi** 2019-10-17 18:53 UTC
