### ISSUE TITLE
isinstance and TypeVar 

### ISSUE THREAD

**Issue by johnburnett** [python/mypy#13492] opened 2022-08-24 00:10 UTC
**Bug Report**

Run mypy against the following:

```
from typing import TypeVar

T = TypeVar("T")

def _checkType(arg: T, typ: type) -> T:
    if isinstance(arg, typ):
        return arg
    raise TypeError(f"Argument is not a {typ}.")

reveal_type(_checkType(42, int))
```

**Expected Behavior**

Type checks to pass

**Actual Behavior**

The following error is printed: `error: Incompatible return value type (got "object", expected "T")`

Additionally, these two variants work around the issue (and pass without error):

```
def _checkType_cast(arg: T, typ: type) -> T:
    if isinstance(arg, typ):
        return cast(T, arg)
    raise TypeError(f"Argument is not a {typ}.")

def _checkType_backup(arg: T, typ: type) -> T:
    backup = arg
    if isinstance(arg, typ):
        return backup
    raise TypeError(f"Argument is not a {typ}.")
```

**Your Environment**

- Mypy version used: 0.971
- Python version used: 3.9.7

**Comment by ilinum** [comment] 2022-09-04 19:28
Duplicate of #13462.

**Closed by ilinum** 2022-09-04 19:28 UTC
Labels: bug
