### ISSUE TITLE
Passing on Kwargs to Functions with Complex Types

### ISSUE THREAD

**Issue by rmorshea** [python/mypy#6552] opened 2019-03-15 21:46 UTC
Consider the following attempt at adding type hints to the functions `downstream` and `upstream`:

```python
def downstream(*, a: Type1, b: Type2):
    ...

def upstream(*, c: Type3, d: Type4, **kwargs):
    downstream(**kwargs)
    ...
```

MyPy complains that `kwargs` has the type `Dict[str, Any]` but that the arguments `a` and `b` of `downstream` require `Type1` and `Type2` respectively.

I understand that the solution to this error is to rewrite `upstream` in the following way:

```python
def upstream(*, a: Type1, b: Type2, c: Type3, d: Type4, **kwargs):
    parent(a=a, b=b)
    ...
```

However what if the argument list of parent is much longer, or there is function `further_upstream` which has its own argument list and must call `upstream`? Are you required to enumerate the arguments and their types from all the downstream functions? Or is there a graceful way to handle the "per-key" typing of `**kwargs` that I'm not seeing?

This problem is further compounded when dealing with overwritten methods in subclasses because MyPy will complain that the signature of the overwritten method is incompatible with the signature from the supertype.

**Comment by ilevkivskyi** [comment] 2019-03-15 22:20
This is essentially a duplicate of https://github.com/python/mypy/issues/4441 (which likely will be implemented in near future), see also https://github.com/python/typing/issues/270

**Closed by ilevkivskyi** 2019-03-15 22:20 UTC

**Comment by rmorshea** [comment] 2019-03-15 22:22
@ilevkivskyi using `TypedDict` was actually my first guess at how to solve this. Thanks!
