### ISSUE TITLE
error: Value of type variable "_AnyPath" of "copyfile" cannot be "Union[str, Path]"

### ISSUE THREAD

**Issue by petsuter** [python/mypy#7082] opened 2019-06-27 15:02 UTC
I have this code which was accepted in a older version (0.6xx?) of mypy:

```
import pathlib
import shutil
from typing import Union

def f(x: Union[str, pathlib.Path]):
    shutil.copyfile("bla", x)
```
But is not accepted by mypy 0.710:

```
error: Value of type variable "_AnyPath" of "copyfile" cannot be "Union[str, Path]"
```

How should I fix my type annotations?
I tried this:

```
import os
import shutil
from typing import TypeVar

_AnyPath = TypeVar("_AnyPath", str, os.PathLike)

def f(x: _AnyPath):
    shutil.copyfile("bla", x)
```

And that seems to work.

----
I [asked this on StackOverflow](https://stackoverflow.com/questions/56736338/mypy-error-value-of-type-variable-anypath-of-copyfile-cannot-be-unionstr?noredirect=1#comment100038824_56736338) but it was suggested to open a "bug/missing feature issue" here.

**Comment by Michael0x2a** [comment] 2019-06-27 15:43
More specifically, I think the root cause is that we don't properly perform union math on functions containing TypeVars with value restrictions:

```
from typing import TypeVar, Union

T = TypeVar('T', int, str)

def test(x: T) -> T:
    return x

y: Union[int, str]
test(y)
```

We get a `Value of type variable "T" of "test" cannot be "Union[int, str]"` error on the final line, which I think is suboptimal -- `test` is morally equivalent to an overload, and we'd accept a call of `test(Union[int, str])` there.

Here, `shutil.copyfile(...)` accepts a TypeVar with value restriction for the second arg, and fails when passed a union.

...it's a little surprising to me that we don't have an issue for this already, actually. I tried searching for one before suggesting OP file an issue here, but no dice.

**Comment by ilevkivskyi** [comment] 2019-06-27 15:49
Duplicate of https://github.com/python/mypy/issues/1533

**Closed by ilevkivskyi** 2019-06-27 15:49 UTC
