### ISSUE TITLE
"None" has no attribute "foo"

### ISSUE THREAD

**Issue by matthiaskramm** [python/mypy#4538] opened 2018-02-03 03:30 UTC
Given

```
x = None
if x is not None:
  x.foo()
```

running `mypy file.py` reports:

```
file.py:3: error: "None" has no attribute "foo"
```

mypy version: `mypy 0.570-dev-8ec7046787f92bf7b00d0c70f570fcb5d75e4b53`

Passing `--strict-optional` makes the problem go away.

**Comment by bwo** [comment] 2018-02-05 22:20
seems like this is related: https://github.com/python/mypy/issues/4520

**Comment by ethanhs** [comment] 2018-02-25 23:04
I think this is in fact a duplicate of #4520, closing this as that issue has more discussion.

**Closed by ethanhs** 2018-02-25 23:04 UTC
Labels: bug, priority-0-high
