### ISSUE TITLE
error: "Callable[..., Any]" not callable  (how is this even possible?)

### ISSUE THREAD

**Issue by randolf-scholz** [python/mypy#14751] opened 2023-02-21 16:38 UTC
**Bug Report**

MyPy says a callable is not callable...

**To Reproduce**

https://mypy-play.net/?mypy=master&python=3.11&gist=f3a073087c600a0875ef54149ef27e24

```python
from types import FunctionType
from typing import Callable


def show_annotations(func: Callable) -> None:
    if isinstance(func, FunctionType):
        print(func.__annotations__)
    else:
        print(func.__call__.__annotations__)  # ✘ error [operator]


class Foo:
    def __call__(self) -> None:
        pass


def foo() -> None:
    pass


show_annotations(foo)
show_annotations(Foo())
```

**Expected Behavior**

The code looks good to me, typing-wise.

**Actual Behavior**

> main.py:9: error: "Callable[..., Any]" not callable  [operator]
> Found 1 error in 1 file (checked 1 source file)

**Comment by AlexWaygood** [comment] 2023-02-21 17:13
Duplicate of #5079

**Closed by AlexWaygood** 2023-02-21 17:13 UTC
Labels: bug
