### ISSUE TITLE
Type erased with TypeAlias on higher ordered functions

### ISSUE THREAD

**Issue by tyoung-patreon** [python/mypy#16530] opened 2023-11-20 22:40 UTC
**Bug Report**

Mypy appears to lose type information simply by using a TypeAlias with generics. I'm trying to define a re-usable type for `Decorator` throughout my codebase so that I don't have to recreate `Callable[[Callable[P, A]], Callable[P, A]]` and can instead just use `Decorator[P, A]`. However, when I do this the type is silently replaced with Never.

**To Reproduce**

```python
from typing import Callable
from typing import TypeVar
from typing_extensions import ParamSpec
from typing_extensions import TypeAlias

A = TypeVar("A")
P = ParamSpec("P")

Decorator: TypeAlias = Callable[[Callable[P, A]], Callable[P, A]]


def my_decorator(f: Callable[P, A]) -> Callable[P, A]:
    return f


def my_decorator_factory() -> Decorator[P, A]:
    return my_decorator


@my_decorator_factory()
def x(i: int) -> int:
    return i


reveal_type(my_decorator)
reveal_type(my_decorator_factory)
reveal_type(my_decorator_factory())
reveal_type(x)

# Revealed type is "def [P, A] (f: def (*P.args, **P.kwargs) -> A`-2) -> def (*P.args, **P.kwargs) -> A`-2"
# Revealed type is "def [P, A] () -> def (def (*P.args, **P.kwargs) -> A`-2) -> def (*P.args, **P.kwargs) -> A`-2"
# Revealed type is "def (def (*Never, **Never) -> Never) -> def (*Never, **Never) -> Never"
# Revealed type is "def (*Never, **Never) -> Never"
```

**Expected Behavior**

I expect mypy to to reveal that `x` has a type of `Revealed type is "def (i: builtins.int) -> builtins.int"`. This is what I get when I do not use the `TypeAlias` for Decorator

**Actual Behavior**

Instead I get that `Revealed type is "def (*Never, **Never) -> Never"`.

**Your Environment**

- Mypy version used: 1.7.0
- Mypy command-line flags:
- Mypy configuration options from `mypy.ini` (and other config files):
- Python version used: 3.9

**Comment by ilevkivskyi** [comment] 2023-11-22 15:38
Duplicate of https://github.com/python/mypy/issues/3924

**Closed by ilevkivskyi** 2023-11-22 15:38 UTC
Labels: bug
