### ISSUE TITLE
attrs-plugin: wrapped attrib is dropped from __init__ signature

### ISSUE THREAD

**Issue by tombo315** [python/mypy#5867] opened 2018-11-02 22:08 UTC
System Information:
```
mypy --version
mypy 0.650+dev.0b61e5476520c6e2b8d0136fab645cb3414e412f
```
From http://www.attrs.org/en/stable/extending.html
```python
import attr
  
TA = '__my_type_metadata'
def typed(cls, default=attr.NOTHING, validator=None, repr=True, cmp=True, hash=None, init=True, convert=None, metadata={}):
     metadata = dict() if not metadata else metadata
     metadata[MY_TYPE_METADATA] = cls
     return attr.ib(default, validator, repr, cmp, hash, init, convert, metadata)

@attr.s
class C(object):
     x = typed(int, default=1, init=False)

C(10)
C(x=10)
```
Output:
```
$ mypy attrs_init.py 
attrs_init.py:13: error: Too many arguments for "C"
attrs_init.py:14: error: Unexpected keyword argument "x" for "C"
```
Expected:
`<nil>`

**Comment by ilevkivskyi** [comment] 2018-11-02 23:32
This is a known limitation, see https://mypy.readthedocs.io/en/latest/additional_features.html#id1
Sometimes you can work around this by using:
```python
if typing.TYPE_CHECKING:
    typed = attr.ib
else:
    # actual definition
```

Closing as a duplicate of https://github.com/python/mypy/issues/5406

**Closed by ilevkivskyi** 2018-11-02 23:32 UTC
