### ISSUE TITLE
Wrong type inferred for union containing restricted type variable

### ISSUE THREAD

**Issue by jboning** [python/mypy#2534] opened 2016-12-07 20:58 UTC
```
from typing import Generic, TypeVar, Union

T = TypeVar('T')
class G(Generic[T]): pass
class A(object): pass
class B(object): pass
g_a = None  # type: G[A]
g_b = None  # type: G[B]

AB = TypeVar('AB', A, B)
def f(x):
    # type: (Union[G[AB],AB]) -> G[AB]
    pass

f(A())
f(B())
f(g_a)
f(g_b)  # E: Argument 1 to "f" has incompatible type G[B]; expected "Union[G[A], A]"
```

The error is incorrect--`f(g_b)` should be valid.

Swapping `A` and `B` in the definition of `AB` results in an error on the `f(g_a)` call instead.

I'm not sure this title clearly describes the issue; improvements welcome.

**Comment by ilevkivskyi** [comment] 2019-02-24 11:00
This is a duplicate of https://github.com/python/mypy/issues/3644 (or rather the other way around, but the other issue has more discussion).

**Closed by ilevkivskyi** 2019-02-24 11:00 UTC
Labels: bug, false-positive, priority-1-normal, topic-union-types
