### ISSUE TITLE
Add Sequence to documentation

### ISSUE THREAD

**Issue by alexchamberlain** [python/mypy#6536] opened 2019-03-12 07:46 UTC
Apologies in advance if I've failed to search the docs. As far as I can tell, Sequence isn't formally documented - it would fit quite nicely in [Predefined Protocols][1] I think.

I will look to make this change myself over the next couple of days, but I wanted to raise the issue first in case I had a complete fail with the docs.

[1]: https://mypy.readthedocs.io/en/stable/protocols.html#predefined-protocols

**Comment by alexchamberlain** [comment] 2019-03-12 07:50
After some searching, it is documented at https://docs.python.org/3/library/typing.html#typing.Sequence and implemented at https://github.com/python/cpython/blob/3.7/Lib/typing.py#L1220

**Comment by JelleZijlstra** [comment] 2019-03-12 15:15
It's not listed as a Protocol because it's not actually a Protocol. There might be another place in the mypy docs where it could usefully be mentioned though.

**Comment by ilevkivskyi** [comment] 2019-03-12 17:16
Yes, it is not a protocol. The remainder is essentially a duplicate of https://github.com/python/mypy/issues/31

**Closed by ilevkivskyi** 2019-03-12 17:16 UTC

**Comment by vectro** [comment] 2023-03-01 04:23
Apologies for necro-posting, but *why* isn't it a protocol? The fact that it's not means you can't do something like:
```python
@typing.runtime_checkable
class HashableProtocol(
    typing.Protocol[T_co], typing.Hashable, typing.Sequence[T_co]
):
    pass
```

**Comment by TeamSpen210** [comment] 2023-03-01 05:30
@vectro, the reason the more complicated ABCs aren't protocols is that they don't just imply that specific method signatures exist, they imply behaviours that can't just be inferred. For instance if `len(seq) > i`, `seq[i]` won't raise an exception. In particular, distinguishing between `Sequence` and `Mapping` isn't possible just from methods. See this paragraph in the `collections.abc` docs:

> ... Interfaces specify semantics and relationships between methods that cannot be inferred solely from the presence of specific method names. For example, knowing that a class supplies `__getitem__`, `__len__`, and `__iter__` is insufficient for distinguishing a [Sequence](https://docs.python.org/3/library/collections.abc.html#collections.abc.Sequence) from a [Mapping](https://docs.python.org/3/library/collections.abc.html#collections.abc.Mapping).
