### ISSUE TITLE
Type narrowing is not applied to closures

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/mypy#7357] opened 2019-08-16 18:13 UTC
In the following code
```
from typing import Callable, List, Optional
def f(x: Optional[List[int]] = None) -> Callable[[], None]:
    if x is None:
        x = []
    x.append(1)
    def g() -> None:
        x.append(2)
    return g
```
MyPy is smart enough to not report an error in the first `.append()`, but it reports an error in the second one.
```
f.py:7: error: Item "None" of "Optional[List[int]]" has no attribute "append"
```

**Comment by ilevkivskyi** [comment] 2019-08-16 18:18
This is a duplicate of https://github.com/python/mypy/issues/2608

**Closed by ilevkivskyi** 2019-08-16 18:18 UTC
