### ISSUE TITLE
Converting str to Literal["a", "b", ...

### ISSUE THREAD

**Issue by sometato** [python/mypy#11363] opened 2021-10-19 20:59 UTC
Let's say we have a function that takes multiple Literal arguments.

```
def takes_a_literal(foo: Literal["a", "b"]) -> None:
    print(foo)
```

And we call that function, from a function that takes a string.

```
def does_something(foo: str) -> None:
    takes_a_literal(foo)
```

Obviously, this will fail because `foo` can be anything. But what if we want to be assertive?

`assert foo in ["a", "b]`, `reveal_type(foo)` is still `str`.

I can't even cast it: `cast(Literal["a", "b"], foo)` -- `reveal_type(foo)` still says `str`.

The only thing I've found that works is this:

```
literal_foo: Literal["a", "b"]
if foo == "a":
    literal_foo = "a"
elif foo == "b":
    literal_foo = "b"
```

Then passing `literal_foo`. This gets quite wordy with more than a couple of Literals.

Is there another way to do this?

**Comment by JelleZijlstra** [comment] 2021-10-19 21:54
This is a duplicate of #10977.

**Closed by JelleZijlstra** 2021-10-19 21:54 UTC
Labels: question
