### ISSUE TITLE
issues with type inference with overlapping types in a union

### ISSUE THREAD

**Issue by efenka** [python/mypy#7231] opened 2019-07-17 12:26 UTC
I have an issue a where type inference is not working as I would expect. Not sure if this a known limitation or a bug. I assume it has to do with the with overlapping types in a union. 

``` python3
#!/usr/bin/env python3


from typing import *

T = TypeVar('T')


def ensure_list(item: Union[T, Iterable[T]]) -> List[T]:

    if isinstance(item, Iterable):
        return [_f for _f in item]

    else:
        return [item]

reveal_type(ensure_list([1]))
```

gives 

``` 
type_issue.py:18: note: Revealed type is 'builtins.list[<nothing>]'
type_issue.py:18: error: Argument 1 to "ensure_list" has incompatible type "List[int]"; expected "Iterable[<nothing>]"
```

What i want to achieve is that mypy knows that if give `List[int]` or `int` into my function the result is `List[int]`, but if i give `List[str]`, `str` or `Generator[str, None, None]` into my function it returns a `List[str]`. The revealed type should be 'List[T]'.

I'm using mypy==0.720 (no config, no flags) and python==3.6.5.

**Comment by ilevkivskyi** [comment] 2019-07-17 12:35
Duplicate of https://github.com/python/mypy/issues/6417. You can use overloads for now, see my comment there.

**Closed by ilevkivskyi** 2019-07-17 12:35 UTC

**Comment by efenka** [comment] 2019-07-17 18:34
Wow, thanks a lot! 

I type-annotated so many thousand lines of code now but never saw this @overload decorator. Problem solved. Sorry I stole your time with this.
