### ISSUE TITLE
deprecate implicit optional / make `no_implicit_optional` the default

### ISSUE THREAD

**Issue by DetachHead** [python/mypy#11371] opened 2021-10-21 03:11 UTC
as discussed in https://github.com/python/mypy/issues/10987#issuecomment-900677771, implicit optional is deprecated, but it's still the default behavior and the documentation doesn't say it's deprecated

**Comment by AlexWaygood** [comment] 2022-05-27 11:55
Duplicate of #9091

**Closed by AlexWaygood** 2022-05-27 11:55 UTC
Labels: documentation
