### ISSUE TITLE
Inherit type from functions default value

### ISSUE THREAD

**Issue by dpinol** [python/mypy#9545] opened 2020-10-07 13:44 UTC
**Feature**
I would expect that default valued argument inherit the value type. Hence the following code would fail because "f" is called with a str instead of an int, and because it internally assigns to an str.
Personally I would implement this by default, but having a flag to enable it could also be an option.
```
def f(a=5) -> None:
    a="ads"

def g() -> None:
    f("asd")
```

**Pitch**
My rationale for adding the check:

1. That's the way it works in other languages (eg. typescript)
1. default values are typically literals (since mutable objects are not good defaults), and it's rare that providing  eg. an int default, an str would be also accepted. So, the most common case will require shorter code.
1. If the developer wants to set a default value but wants to allow other types, it feels more natural to have to explicitly add ": Any" 
1. Mypy already reports "Incompatible types in assignment" for the code below, which is quite conceptually similar.
```
class A:
    a=5

A.a = "asd"
```
1. Tools like pycharm automatically inherit the type from the default value. See snapshot
![image](https://user-images.githubusercontent.com/1954955/95338957-c871c700-08b3-11eb-92a2-9beaae40cd76.png)

thanks!

**Comment by gvanrossum** [comment] 2020-10-07 15:55
Arguably this should be discussed on typing-sig first.

**Comment by hauntsaninja** [comment] 2023-04-14 09:26
Basically a duplicate of https://github.com/python/mypy/issues/10149

**Closed by hauntsaninja** 2023-04-14 09:26 UTC
Labels: feature, needs discussion
