### ISSUE TITLE
[mypyc] native dataclass codegen

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [python/mypy#12902] opened 2022-05-29 09:22 UTC
**Feature**

instead of letting dataclasses of the stdlib implement generated dataclasses,
compile the dataclasses generated methods to actual extension methods

**Pitch**

my understanding is, that dataclasses support currently just prepares what the dataclass decorator needs to make it work
however that implies all the generated methods being runtime generated python methods instead of extension methods

which in turn costs import time when generating them at startup and runtime when running python code for the generated methods

**Comment by 97littleleaf11** [comment] 2022-05-29 16:54
duplicate of https://github.com/mypyc/mypyc/issues/817.

**Closed** 2022-05-29 16:55 UTC
Labels: feature, performance, topic-dataclasses, topic-mypyc
