### ISSUE TITLE
Instance Checks fail for Special Forms

### ISSUE THREAD

**Issue by seandstewart** [python/mypy#17070] opened 2024-03-28 13:16 UTC
**Bug Report**

When I use `isintance(val, <SpecialForm>)`, I receive an error stating that `isinstance` is incompatible with special forms.

**To Reproduce**

Here is a mypy playground: https://mypy-play.net/?mypy=master&python=3.12&gist=f1753407761c9a9ebcb6bddd54120068

**Expected Behavior**

Instance checks should pass and allow for type-narrowing.

**Actual Behavior**

```
main.py:6: error: Argument 2 to "isinstance" has incompatible type "<typing special form>"; expected "_ClassInfo"  [arg-type]
```

**Your Environment**

I have tested against mypy 1.0 -> 1.9 and python 3.8 -> 3.12, I'm guessing this may be an issue with an updated type stub, given all versions report this error.

**Comment by JelleZijlstra** [comment] 2024-03-28 14:53
Your bug mentions "special forms" in general, but the example involves Callable, and Callable is probably the only special form for which isinstance check makes sense. As such, this is probably a duplicate of #11071.

**Closed by JelleZijlstra** 2024-03-28 14:53 UTC
Labels: bug

**Comment by seandstewart** [comment] 2024-03-29 23:57
I think there is a misunderstanding here - apologies if this is unclear - this issue shows itself even with collections.abc items. I don't think this is the same issue.

**Comment by leoncleonc** [comment] 2025-01-08 17:16
Looks like it still does not work correctly with collections.abc.Callable
```python
from typing_extensions import reveal_type
from collections.abc import Callable

val: str | Callable
if isinstance(val, Callable):
    reveal_type(val)
```
Returns:
```
main.py:6: error: Argument 2 to "isinstance" has incompatible type "<typing special form>"; expected "_ClassInfo"  [arg-type]
main.py:7: note: Revealed type is "Union[builtins.str, def (*Any, **Any) -> Any]"
Found 1 error in 1 file (checked 1 source file)
```
playground: https://mypy-play.net/?mypy=latest&python=3.13&gist=38617ad46276f47d7b8b844e9eb66d68

**Comment by marksteward** [comment] 2026-06-24 02:21
Also affects [type unions in cryptography](https://github.com/pyca/cryptography/issues/8039), e.g. `PKCS7PrivateKeyTypes`. Can this be reopened?
