### ISSUE TITLE
(🎁) Report when generic base class specified multiple times with incompatible types

### ISSUE THREAD

**Issue by KotlinIsland** [python/mypy#15348] opened 2023-06-02 00:35 UTC
```py
from typing import Generic, TypeVar

T = TypeVar("T")

class A(Generic[T]): 
    a: T

class B(A[float], A[int])  # error

class C(A[float]):
    pass 

class D(C, A[int]):  # no error
    pass

d = D()
d.a = 1.1  # What the heck?
c: C = d  # fishy
c.a = 1.1
```

This scenario seems quite fishy (🐟). What do you think? Leave a comment below.

**Comment by ilevkivskyi** [comment] 2023-06-10 22:17
This is a duplicate of https://github.com/python/mypy/issues/6184

**Closed by ilevkivskyi** 2023-06-10 22:17 UTC
Labels: feature
