### ISSUE TITLE
False positive error?

### ISSUE THREAD

**Issue by oriontvv** [python/mypy#5835] opened 2018-10-24 15:16 UTC
I see error for code:
```
def func(choice: str, default: str='y') -> bool:
    values = ('yes', '') if default == 'y' else ('yes',) # error: Unsupported right operand type for in ("object")
    # values = ('yes', '') if True else ('yes',) # ok (!)
    return choice in values
```
Is it a bug? mypy version is `0.641`

**Comment by ilevkivskyi** [comment] 2018-10-24 16:08
This is a known bug, duplicate of https://github.com/python/mypy/issues/4975.

Workaround is to use lists instead of tuples (or use `# type: ignore` on that line to silence mypy).

**Closed by ilevkivskyi** 2018-10-24 16:08 UTC
