### ISSUE TITLE
Type narrowing doesn't work for "my_dict[key]"

### ISSUE THREAD

**Issue by csurfer** [python/mypy#7670] opened 2019-10-09 20:08 UTC
Python versions tested on 2.7, 3.7
mypy version being used 0.730

Consider the following snippet of code in python2.7

```python
from typing import List, Dict, Optional
from collections import defaultdict

my_dict = defaultdict(lambda: None) # type: Dict[int, Optional[str]]
my_dict[1] = "a"
my_dict[2] = "b"
my_dict[3] = "c"

test_list = [] # type: List[str]
for key in [1, 2, 3, 4, 5]:
    if my_dict[key] is not None:
        test_list.append(my_dict[key])
```

or the corresponding snippet of code in python3.7

```python
from typing import List, Dict, Optional
from collections import defaultdict

my_dict: Dict[int, Optional[str]] = defaultdict(lambda: None)
my_dict[1] = "a"
my_dict[2] = "b"
my_dict[3] = "c"

test_list: List[str] = []
for key in [1, 2, 3, 4, 5]:
    if my_dict[key] is not None:
        test_list.append(my_dict[key])
```

Both `mypy` and `mypy --py2` fail on the inspection of the above code with error

```
test.py:12: error: Argument 1 to "append" of "list" has incompatible type "Optional[str]"; expected "str"
Found 1 error in 1 file (checked 1 source file)
```

complaining that the `test_list` expects its arguments to be `str` but the append comprehension is providing it with `Optional[str]` which in reality is avoided by the line `if my_dict[key] is not None` preceding it.

**Comment by gvanrossum** [comment] 2019-10-09 20:30
This has nothing to do with defaultdict. I guess mypy isn't smart enough to realize that in
```py
    if my_dict[key] is not None:
        test_list.append(my_dict[key])
```
the value appended can't be None.

The solution for that is to write it like this:
```py
    value = my_dict[key]
    if value is not None:
        test_list.append(value)
```
I'm not sure I want to consider this a bug.

**Comment by JukkaL** [comment] 2019-10-10 16:39
@forrestchang We don't have concrete plans, but it's possible that we'll improve it at some point. Sorry for being vague :-)

**Comment by ilevkivskyi** [comment] 2019-10-14 14:17
Closing as a duplicate of https://github.com/python/mypy/issues/7339 that has a bit more context.

**Closed by ilevkivskyi** 2019-10-14 14:17 UTC
Labels: false-positive, feature, priority-1-normal
