### ISSUE TITLE
Isinstance checks against Type[SomeProtocol] unexpectedly fails

### ISSUE THREAD

**Issue by Michael0x2a** [python/mypy#7932] opened 2019-11-12 05:29 UTC
Apologies in advance if this is a duplicate issue.

When I try type-checking this program, the final line is inferred to be unreachable. This was a bit surprising to me: I expected to get a "Revealed type is 'SupportsLookup'" note instead.

```python
from typing import Type
from typing_extensions import Protocol

class SupportsLookup(Protocol):
    def lookup(self, key: str) -> int: ...

class Parent: pass

class Child(Parent):
    def lookup(self, key: str) -> int: ...

def cast_and_use(template: Type[SupportsLookup], x: Parent) -> None:
    if isinstance(x, template):
        reveal_type(x)
```

Somewhat curiously, if I make `x` be of type `object` instead of `Parent`, everything works as expected.

This seems a bit inconsistent to me. Assuming I'm not overlooking some type safety issue in my example, I think it'd be better to always narrow `x` to `SupportsLookup` regardless of how it's originally typed as long as the protocol doesn't directly conflict with any signatures defined in `Parent`.

Note: this issue is a simplification of the root cause of the mypyc error I had in https://github.com/python/mypy/pull/7917 -- my original version of `make_indexing_replay_lookup_func` had this issue.

**Comment by ilevkivskyi** [comment] 2019-11-12 09:39
First of all mypyc doesn't support protocols yet, see https://github.com/mypyc/mypyc/issues/586

About mypy issue itself, this is essentially a duplicate of https://github.com/python/mypy/issues/3830 (also tangentially related to https://github.com/python/mypy/issues/3827 and https://github.com/python/mypy/issues/3603).

This is actually not so obvious, we can't say that `meet(SupportsLookup, Parent)` is `SupportsLookup` because the latter is not a subtype of `Parent`, and we can't use `Parent` either. The best solution is probably to implement internal intersection-like generated `TypeInfo`s that were proposed several times elsewhere, but they may be not easy to implement.

**Closed by ilevkivskyi** 2019-11-12 09:39 UTC
