### ISSUE TITLE
Support narrowing Union of List types via index and isinstance

### ISSUE THREAD

**Issue by sbdchd** [python/mypy#9362] opened 2020-08-26 21:24 UTC
It would be nice to be able to narrow a union of two different list types via indexing into the array and using an `isinstance` check

```python
from typing import Union, List

x: Union[List[str], List[int]] = [10]

if isinstance(x[0], str):
    reveal_type(x)
    # expected: builtins.list[builtins.str]
    # actual: Union[builtins.list[builtins.str], builtins.list[builtins.int]]
else:
    reveal_type(x)
    # expected: builtins.list[builtins.int]
    # actual: Union[builtins.list[builtins.str], builtins.list[builtins.int]]
```

One caveat is that the array could be empty, but let's assume we make an emptiness check before indexing

**Comment by gvanrossum** [comment] 2020-08-26 23:32
This is a special case in mypy. If you rewrite the initialization like this it works:
```
x: Union[List[str], List[int]]
x = [10]
```
Honestly I don't think this is documented very well -- you might be able to infer this from [Explicit types for variables](https://mypy.readthedocs.io/en/stable/type_inference_and_annotations.html#explicit-types-for-variables) but it could be more explicit.

**Comment by sbdchd** [comment] 2020-08-27 00:16
I think I may have made my example too simple.

In my current use case I parse some data from a network response which is a union of two different list types: `Union[List[List[str]], List[SearchResult]]`

I'm hoping to refine this response via indexing and an `isinstance` check

```python
from typing import Union, List
from dataclasses import dataclass


@dataclass
class SearchResult:
    id: str
    score: float
    match: str


def get_search_results() -> Union[List[List[str]], List[SearchResult]]:
    ...


x = get_search_results()

if isinstance(x[0], SearchResult):
    reveal_type(x)
    # expected: builtins.list[main.SearchResult]
    # actual: Union[builtins.list[builtins.list[builtins.str]], builtins.list[main.SearchResult]]
else:
    reveal_type(x)
    # expected: builtins.list[builtins.str]
    # actual: Union[builtins.list[builtins.list[builtins.str]], builtins.list[main.SearchResult]]

```


which I think can be simplified to the following as a test case

```python
from typing import Union, List


def foo() -> Union[List[str], List[int]]:
    ...


x = foo()

if isinstance(x[0], str):
    reveal_type(x)
    # expected: builtins.list[builtins.str]
    # actual: Union[builtins.list[builtins.str], builtins.list[builtins.int]]
else:
    reveal_type(x)
    # expected: builtins.list[builtins.int]
    # actual: Union[builtins.list[builtins.str], builtins.list[builtins.int]]
```

**Comment by gvanrossum** [comment] 2020-08-27 01:14
Ah, okay. I think this is a feature request.

**Comment by hauntsaninja** [comment] 2021-08-03 23:03
Duplicate of #7339 and #2458

**Closed by hauntsaninja** 2021-08-03 23:03 UTC
Labels: feature
