### ISSUE TITLE
Internal error with Protocol

### ISSUE THREAD

**Issue by jtrakk** [python/mypy#6850] opened 2019-05-16 20:07 UTC
Hello, I got an internal error on this code. Deleting the protocol makes the error go away.

```python
import contextlib
import enum
import types
import typing as t
import sys

import attr
import typing_extensions


@attr.s(auto_attribs=True)
class TraceFunction(typing_extensions.Protocol):
    def __call__(
        self, frame: types.FrameType, event: str, args: t.Any
    ) -> t.Optional["TraceFunction"]:
        ...


@attr.s(auto_attribs=True)
class TraceFunctionStack:
    stack: t.List[TraceFunction]

    def __call__(self, frame: types.FrameType, event: str, args: t.Any):

        for func in self.stack:
            # XXX What should we do with the returned value?
            returned = func(frame, event, args)

        return self


def loud_trace(frame, event, args):
    print(frame.f_locals, event, "AAAAAAAAAAAAAAAAAAAAAAAAA")


tfs = TraceFunctionStack([loud_trace])


```

```python-traceback
mypy --new-semantic-analyzer --show-traceback ~/tmp/tracer.py
/home/user/tmp/tracer.py:36: error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues version: 0.701
Traceback (most recent call last):
  File "/home/user/.local/pipx/venvs/ipython/bin/mypy", line 10, in <module>
    sys.exit(console_entry())
  File "mypy/checkexpr.py", line 3254, in accept
  File "mypy/nodes.py", line 1803, in accept
  File "mypy/checkexpr.py", line 2724, in visit_list_expr__ExpressionVisitor_glue
  File "mypy/checkexpr.py", line 2726, in visit_list_expr
  File "mypy/checkexpr.py", line 2747, in check_lst_expr
  File "mypy/checkexpr.py", line 696, in check_call
  File "mypy/checkexpr.py", line 779, in check_callable_call
  File "mypy/checkexpr.py", line 993, in infer_function_type_arguments
  File "mypy/infer.py", line 30, in infer_function_type_arguments
  File "mypy/constraints.py", line 67, in infer_constraints_for_callable
  File "mypy/constraints.py", line 144, in infer_constraints
  File "mypy/types.py", line 625, in accept
  File "mypy/constraints.py", line 280, in visit_instance__TypeVisitor_glue
  File "mypy/constraints.py", line 347, in visit_instance
  File "mypy/subtypes.py", line 482, in is_protocol_implementation
AssertionError:

```

```
mypy --version                                               
mypy 0.701
 
Python 3.7.1

```

**Comment by JelleZijlstra** [comment] 2019-05-16 20:55
Does this also happen with the old semantic analyzer?

**Comment by jtrakk** [comment] 2019-05-16 21:08
Yes

**Comment by ilevkivskyi** [comment] 2019-05-19 09:16
I think this is a duplicate of https://github.com/python/mypy/issues/6801

**Closed by ilevkivskyi** 2019-05-19 09:16 UTC
Labels: crash, new-semantic-analyzer
