### ISSUE TITLE
dataclasses.field(default=None) causes error: "field" does not return a value

### ISSUE THREAD

**Issue by ojii** [python/mypy#5596] opened 2018-09-11 07:45 UTC
mypy 0.620
python 3.7.0

code:

```python
from dataclasses import dataclass, field

@dataclass
class Foo:
    bar: None = field(default=None)
```

Errors with `error: "field" does not return a value` on the last line. (A more realistic example would be `bar: Optional[...]`, which gives the same error)

However, non-None types work fine:

```

```python
from dataclasses import dataclass, field

@dataclass
class Foo:
    bar: str = field(default='')
```

**Comment by vim345** [comment] 2018-09-21 00:02
I am facing the same issue.

**Comment by ilevkivskyi** [comment] 2018-09-21 00:21
This is actually a duplicate of https://github.com/python/mypy/issues/4214.

I will close this one, I will raise priority of the other issue to high.

**Closed by ilevkivskyi** 2018-09-21 00:21 UTC
Labels: false-positive, priority-0-high
