### ISSUE TITLE
Mypy failing to understand `ProgressBar` and `contextlib.nullcontext()` are both context managers

### ISSUE THREAD

**Issue by jamesbraza** [python/mypy#16892] opened 2024-02-08 00:10 UTC
**Bug Report**

Mypy 1.8 seems to be failing to combine `prompt-toolkit`'s `ProgressBar` with `contextlib.nullcontext()` into a context manager object.

**To Reproduce**

```python
import contextlib

from prompt_toolkit.shortcuts import ProgressBar

debug_print: bool = True
cm = ProgressBar() if debug_print else contextlib.nullcontext()
reveal_type(cm)  # Revealed type is "builtins.object"
with cm:
    pass
```

**Expected Behavior**

No type errors

**Actual Behavior**

```none
a.py:7:13: note: Revealed type is "builtins.object"
a.py:8:6: error: "object" has no attribute "__enter__"  [attr-defined]
a.py:8:6: error: "object" has no attribute "__exit__"  [attr-defined]
```

**Your Environment**

- Mypy version used: 1.8
- Mypy command-line flags:
- Mypy configuration options from `mypy.ini` (and other config files):
- Python version used: 3.12.1

**Comment by AlexWaygood** [comment] 2024-02-08 00:29
Duplicate of #5512 and #10109.

You can work around the mypy limitation here by using two branches rather than the ternary; for unfortunate historical reasons, mypy has different inference rules for the two ways of writing the same thing:

```py
import contextlib

from prompt_toolkit.shortcuts import ProgressBar

debug_print: bool = True
cm: contextlib.AbstractContextManager[object]
if debug_print:
    cm = ProgressBar()
else:
    cm = contextlib.nullcontext()
reveal_type(cm)  # Revealed type is "builtins.object"
with cm:
    pass
```

**Closed by AlexWaygood** 2024-02-08 00:29 UTC
Labels: bug, topic-join-v-union
