### ISSUE TITLE
1.12/1.13 Release Tracking Issue

### ISSUE THREAD

**Issue by hauntsaninja** [python/mypy#17815] opened 2024-09-24 04:30 UTC
It would be nice to make a release. It's been about two months since 1.11. We have a couple nice changes in there and it'd be great to release a version of mypyc that should work on Python 3.13.0 (which should be released in about a week).

Do any of the Dropbox folk have time to drive a release?

**Comment by cdce8p** [comment] 2024-09-24 09:48
Just to clarify, would you like a new release now (before 3.13.0) or afterwards with compiled binaries for 3.13? For the later, we'd probably need to wait for cibuildwheel to be updated.

**Comment by JukkaL** [comment] 2024-09-24 09:58
I was already planning to start the release process this week :-)

I was waiting for Python 3.12 type parameter syntax to be officially supported and enabled by default. Mypyc support for 3.13 and compiled binaries for 3.13 would a great addition!

I'm planning to cut the release branch by the end of the week.

> Just to clarify, would you like a new release now (before 3.13.0) or afterwards with compiled binaries for 3.13?

It looks like the planned release date for 3.13.0 is Oct 1. 1.12 won't be released before Oct 1, so it's possible that we could include compiled binaries for 3.13. If cibuildwheel doesn't get updated soon enough, we can make a 1.12.1 release afterwards.

**Comment by mr-c** [comment] 2024-09-24 10:04
> For the later, we'd probably need to wait for cibuildwheel to be updated.

I was curious about this and found https://github.com/mypyc/mypy_mypyc-wheels/pull/82 which is failing against https://github.com/python/mypy/commit/5c38427a53f409bae068c314e119fecc77730d76 from September 16th. 

Testing Python 3.13 mypy  wheels won't work until Python 3.13.0 final (with the recently merged https://github.com/python/cpython/pull/124273) is released, and cibuildwheel is updated to use it.

However, that requires no code changes, one can upload additional wheels to PyPI at any time. 

As a downstream packager of mypy for Debian and the recipient of many Dependabot notifications, I would request that there isn't a "1.12.1" mypy release without code changes. 

So hopefully mypy 1.12.0 can be released with Python3.13 wheels, or those wheels can be built & uploaded later without needing a "no-change" 1.12.1 mypy release.

**Comment by JukkaL** [comment] 2024-09-24 12:54
> However, that requires no code changes, one can upload additional wheels to PyPI at any time.

I guess we can upload new wheels, but only if they become available within a few days of the mypy release -- otherwise it could be confusing.

> As a downstream packager of mypy for Debian and the recipient of many Dependabot notifications, I would request that there isn't a "1.12.1" mypy release without code changes.

Is the issue the busywork caused by such a release, or is there something else?

**Comment by JukkaL** [comment] 2024-09-24 14:45
> Hmm.. I don't see why it would be confusing?

There is a small risk that the initial compiled binary for 3.13 would contain bugs specific to the compiled version, so anybody that has been using mypy pinned to 1.12.0 on Python 3.13 would suddenly start experiencing new issues.

**Comment by hauntsaninja** [comment] 2024-09-25 07:11
As of https://github.com/python/mypy/pull/17812 we know for sure that the test suite passes with a mypyc-compiled mypy on latest Python 3.13

I feel good about the odds that our 3.13 build stack is ready for us by the time we release 1.12. And thank you to cdce8p for keeping cibuildwheel up-to-date / handling the cibuildwheel regression

**Comment by cdce8p** [comment] 2024-09-26 10:41
Just did one more typeshed sync before the release branch is cut:
- #17833

**Comment by JukkaL** [comment] 2024-09-27 10:04
I've been testing the latest master, and I've found one release blocker so far:
 * https://github.com/python/mypy/issues/17841

**Comment by JukkaL** [comment] 2024-09-27 10:07
This release will fix many false negatives in an internal codebase I'm using for testing. This is great, but it slows down the testing process, since I want to check that any new errors actually were false negatives.

**Comment by JukkaL** [comment] 2024-09-27 10:28
Our internal mypy runner scripts can download wheels from [mypy_mypyc-wheels](https://github.com/mypyc/mypy_mypyc-wheels), so testing them is already fairly easy (but it's still manual). I think I'll spot check new errors generated by PRs known to fix false negatives, and will carefully scrutinize new errors caused by other PRs only.

**Comment by JukkaL** [comment] 2024-09-27 10:43
I'm looking into fixing (at least partially) this performance issue before cutting the release branch:
* https://github.com/python/mypy/issues/17231

**Comment by cdce8p** [comment] 2024-09-28 09:19
> I feel good about the odds that our 3.13 build stack is ready for us by the time we release 1.12.

It was announced a few hours ago that the 3.13 release would be delayed by a week and we'll get another release candidate on Monday instead. It depends when the next cibuildwheels release will be but we might even be able to have a 3.13 compatible version out before the actual release 🤞🏻

https://discuss.python.org/t/incremental-gc-and-pushing-back-the-3-13-0-release/65285

**Comment by JukkaL** [comment] 2024-09-30 15:30
The performance issue I mentioned above (#17231) takes a bit more effort than I initially thought, so a full fix likely won't make into the release.

I've been testing mypy with an internal codebase, and there seem to be some regressions that I need to investigate more. #17427 seems to expose some bugs related to edge cases in mypy's union type implementation, as it increases the number of inferred union types. So far I have seen no evidence that #17427 itself misbehaves.

**Comment by JukkaL** [comment] 2024-10-04 08:03
It looks like we can have 3.13 support in this release! A new version of cibuildwheel was just released, and it supports 3.13.0rc3: https://github.com/pypa/cibuildwheel/commit/f1859528322d7b29d4493ee241a167807661dfb4


I'm still investigating one potential small regression.

**Comment by cdce8p** [comment] 2024-10-04 08:06
> It looks like we can have 3.13 support in this release! A new version of cibuildwheel was just released, and it supports 3.13.0rc3: [pypa/cibuildwheel@f185952](https://github.com/pypa/cibuildwheel/commit/f1859528322d7b29d4493ee241a167807661dfb4)

We started building wheels for `3.13` yesterday. See https://github.com/mypyc/mypy_mypyc-wheels/pull/82 :)
> I'm still investigating one potential small regression.

With cibuildwheel?

**Comment by JukkaL** [comment] 2024-10-04 08:08
We also need documentation for the recently merged TypedDict ReadOnly support (#17644). It doesn't block cutting the release branch, as it can be cherry-picked.

One more thing: I'd like mypy to generate an error when using the new syntax for type parameter defaults, since it looks like we won't have support for this yet in this release. 

> With cibuildwheel?

No, a new error which may be a false positive (I haven't created an issue for it yet).

**Comment by JukkaL** [comment] 2024-10-04 16:15
I've created the release branch. ETA for the release is by Oct 11, assuming no major regressions are found.

**Comment by ilevkivskyi** [comment] 2024-10-06 10:10
Btw @JukkaL should we announce in the release blog post that support for 3.8 will be dropped in the next release? See https://github.com/python/mypy/pull/17492

**Comment by ilevkivskyi** [comment] 2024-10-06 20:33
As a suggestion, it may be worth cherry-picking https://github.com/python/mypy/pull/17883. It is not a new bug, but it is quite nasty and I bet a good chunk of existing daemon issues were caused by this.

**Comment by JukkaL** [comment] 2024-10-07 09:22
I cherry-picked #17883. I agree that this is an important fix.

**Comment by JukkaL** [comment] 2024-10-08 09:17
Additional cherry-picks:
* #17891
* #17889

**Comment by JukkaL** [comment] 2024-10-08 15:42
There are various recent issues reported about `functools.partial`, which got improved support in mypy 1.11. I'll look at fixing some of these:
* https://github.com/python/mypy/pull/17297
* https://github.com/python/mypy/issues/17741
* https://github.com/python/mypy/issues/17659
* https://github.com/python/mypy/issues/17620
* https://github.com/python/mypy/issues/17585
* https://github.com/python/mypy/issues/17569
* https://github.com/python/mypy/issues/17556
* https://github.com/python/mypy/issues/17411

Any help is also appreciated! I'll assign myself when I start working on any of the above issues.

**Comment by JukkaL** [comment] 2024-10-08 16:34
Another regression that would be good to fix (in 1.11):
* #17551

**Comment by hauntsaninja** [comment] 2024-10-08 19:43
https://github.com/python/mypy/pull/17898 will fix https://github.com/python/mypy/issues/17556 and https://github.com/python/mypy/issues/17659

I also closed https://github.com/python/mypy/issues/17569 as "as designed" and not really relevant to functools.partial (existing mypy behaviour, we get errors now that functools.partial is actually checked). I closed https://github.com/python/mypy/pull/17297 as a duplicate

https://github.com/python/mypy/issues/17585 is not a regression (older mypy handles the case the same), but is a missing feature. Same with https://github.com/python/mypy/issues/17620, Ivan had suggestion on how to fix that I linked in the issue.

If you wanted to look at something, it could be interesting to look at https://github.com/python/mypy/issues/17741 or https://github.com/python/mypy/issues/17620

**Comment by JukkaL** [comment] 2024-10-09 08:59
Cherry-pick:
 * #17898

**Comment by JukkaL** [comment] 2024-10-09 10:31
This should be fixed before the release is out:
* #17901

I'll look into this tomorrow.

**Comment by JukkaL** [comment] 2024-10-09 13:05
Cherry-pick:
 * #17882

**Comment by JukkaL** [comment] 2024-10-09 13:06
I will cherry-pick this fix to ReadOnly once merge:
 *  #17904

**Comment by JukkaL** [comment] 2024-10-09 13:58
More cherry-picks:
 * #17904
 * #17905

**Comment by ilevkivskyi** [comment] 2024-10-10 08:20
@JukkaL I left a comment on https://github.com/python/mypy/issues/17551. This is not really a regression, it now "correctly" exposes an old bug. I will try to work on https://github.com/python/mypy/issues/17411 today/tomorrow.

**Comment by JukkaL** [comment] 2024-10-10 08:38
> This is not really a regression, it now "correctly" exposes an old bug. 

Thanks for looking into this! We don't need to block the release on this, but it will okay to include a fix in a point release (if the fix is simple enough).

**Comment by JukkaL** [comment] 2024-10-10 09:43
Another cherry-pick:
 * #17903

**Comment by JukkaL** [comment] 2024-10-11 07:49
Cherry-pick:
 * #17921
 
 My current plan is to publish the release on Monday. We can still cherry-pick low-risk fixes until Monday morning (UTC).

**Comment by JukkaL** [comment] 2024-10-14 09:30
Final cherry-picked fix before the release:
 * #17925 

I'm now waiting for the final 1.12.0 wheels to build.

**Comment by JukkaL** [comment] 2024-10-14 11:54
Mypy 1.12 is now out: https://mypy-lang.blogspot.com/2024/10/mypy-112-released.html

**Comment by ilevkivskyi** [comment] 2024-10-14 14:03
It looks like the new syntax `f[...](...)` confuses markdown parser in the blogspot post. The very first line of the example is rendered incorrectly as a link, this is how I see it.
![Screenshot from 2024-10-14 15-02-13](https://github.com/user-attachments/assets/7ec502c2-b53b-4939-b9c1-190c3747b467)

**Comment by JukkaL** [comment] 2024-10-14 14:57
Fixed the example.

**Comment by hauntsaninja** [comment] 2024-10-15 09:10
We've had a few regressions reported:
- https://github.com/python/mypy/issues/17945
- https://github.com/python/mypy/issues/17942
- https://github.com/python/mypy/issues/17952
- https://github.com/python/mypy/issues/17954

For cherry picks, it would be great to get this out:
- https://github.com/python/mypy/pull/17920 (it makes mypy 1.5x faster in my work environment)

Less urgent than that one, but would also be nice to release these other perf wins:
- https://github.com/python/mypy/pull/17950
- https://github.com/python/mypy/pull/17949
- https://github.com/python/mypy/pull/17953

**Comment by hauntsaninja** [comment] 2024-10-18 02:27
We now have fixes for 3/5 regressions, so it's worth making a release. I'd also like to release the performance improvements that target my work environment.

I could release those in a 1.12.1, but it feels a little out of line with what we traditionally release in patches, e.g. we have a new extra for using orjson, if the optimisations are buggy it feels sketchy to introduce them in a patch, etc

Options:
- I can make a 1.12.1 that has just the regression fixes
- I can make a 1.12.1 that has just the regression fixes + perf improvements
- I can do that, but just call it 1.13 (i.e. base it off the 1.12 branch) <-- option I'm leaning towards
- I just wait till actual next release

**Comment by JukkaL** [comment] 2024-10-18 08:29
My preference would be to make a 1.12.1 with just the regression fixes first. We could then make 1.13 based on the 1.12 branch with perf improvements, or wait for the next normal release (either way works for me). My reasoning is that several regressions were reported soon after the release, so making a pure bugfix release seems like a good thing to do.

**Comment by JukkaL** [comment] 2024-10-18 10:05
Fix to another regression:
 * https://github.com/python/mypy/pull/17991

**Comment by hauntsaninja** [comment] 2024-10-18 21:05
I cherrypicked the existing patches to the 1.12 branch and opened https://github.com/python/mypy/pull/17995 for the typeshed revert on 1.12 (reverted on mypy master in https://github.com/python/mypy/pull/17988)

**Comment by hauntsaninja** [comment] 2024-10-19 01:06
I'll cut a 1.12.1 and a 1.13.0 in the next few days!

**Comment by mr-c** [comment] 2024-10-19 09:27
I'm very glad for 1.12.1 to be released with fixes for the regressions, but on behalf of the maintainers of the over 250,000 repositories that use mypy, please don't release 1.13 right away.

![Screenshot_20241019-090138~2](https://github.com/user-attachments/assets/0670fa34-e348-4c60-9cd7-d4200beead30)


https://github.com/python/mypy/network/dependents

Users who want the bleeding edge can instead depend on https://github.com/cdce8p/mypy-dev / https://pypi.org/project/mypy-dev/

As a compromise,  you can make a pre-release of 1.13.0 to PyPI and on GitHub. That will be ignored by Dependabot (and perhaps other auto-updaters), but still be available for installing by those who wish to opt-in.

(None of the above is said with my Debian hat on. If a pre-release of 1.13 is made I will update the Debian package to use it)

**Comment by hauntsaninja** [comment] 2024-10-19 23:12
I will be releasing a 1.13. I got into contributing to mypy because mypy makes my life better, it feels silly to be sitting on unreleased patches that make mypy 2.2x faster in the environment I use mypy in most often, and probably 10%-15% faster for many users.

[Like I said above](https://github.com/python/mypy/issues/17815#issuecomment-2421137009), 1.13 will just be cherry picks on top of 1.12.1 and not include type checking related changes, so hopefully it should be fairly smooth! — likely smoother than 1.12.0 -> 1.12.1 which will affect type checking. If you have a specific concern, we can figure out if there's a way to mitigate it. I'm not sure a pre-release makes sense if we don't have an actual release corresponding to that pre-release and it's unclear to me what problem it solves.

**Comment by hauntsaninja** [comment] 2024-10-20 00:43
1.12.1 is out.

https://github.com/python/mypy/tree/release-1.13 is the branch for 1.13. https://github.com/python/mypy/pull/18000 is changelog PR. I'm planning on release 1.13 on Monday (pending any discussion in this thread)

**Comment by DanielNoord** [comment] 2024-10-20 06:02
As somebody involved in updating dependencies within my company and some of those packages, please keep releasing like this.

It is silly to recommend work arounds to update to new versions as it only increases the amount of work needed to do dependency updates (for example, when do I switch back of the main repository). Besides, releasing often means that releases are smaller and investigating regressions is easier. 

I understand that for distribution maintainers the situation is slightly different as they don't have Dependabot and friends, but packages that depend on `mypy` and have some sort of automatic updates set up (which many platforms offer free of charge to OS packages) would likely benefit from frequent smaller releases than one big breaking release.

Due to the importance of `mypy` in daily developer workflows (we're all waiting of CI) I actually find myself eagerly checking release tracking issues as almost every release has something that unblocks one of my colleagues. Having less frequent releases would only hurt me and those dependent on the updates I do.

**Comment by JukkaL** [comment] 2024-10-21 15:35
The most recent commits (including 5c4d2db7009fa9035b8b3fcffe25182aaa4dc846) in the v1.13.0 branch don't have wheels, so there is no easy way to test the compiled wheels. I'd like to run it against a big internal codebase.

**Comment by hauntsaninja** [comment] 2024-10-21 20:13
I cherry picked the changelog update to the branch, so bc0386b is latest on release-1.13. Wheel build is now running here: https://github.com/mypyc/mypy_mypyc-wheels/actions/runs/11447856493

I'll wait to hear back from you before making the 1.13 release.

**Comment by JukkaL** [comment] 2024-10-22 09:17
I did some quick testing, and the 1.13.0 branch worked without issues, and it was about 6% faster type checking a big codebase at work, compared to 1.12. This is a nice improvement, considering the codebase doesn't have the bottlenecks that were the focus of the recent perf improvements!

**Comment by hauntsaninja** [comment] 2024-10-22 21:54
1.13 is released!

**Comment by hauntsaninja** [comment] 2024-10-24 20:16
A few more regressions have been reported:
- https://github.com/python/mypy/issues/18029
- https://github.com/python/mypy/issues/18027
- https://github.com/python/mypy/issues/18036

**Comment by JukkaL** [comment] 2024-10-28 09:57
Published 1.13 blog post (slightly delayed): https://mypy-lang.blogspot.com/2024/10/mypy-113-released.html

**Closed** 2024-11-19 15:37 UTC
Labels: meta
