### ISSUE TITLE
Non generic subclass of generic class do not resolve type correctly

### ISSUE THREAD

**Issue by dswistowski** [python/mypy#5831] opened 2018-10-24 10:54 UTC
I have code
```python
from abc import ABC, abstractmethod
from typing import TypeVar, Generic, Dict, Type

T = TypeVar('T')


class GenericClass(Generic[T], ABC):
    children: Dict[str, Type[T]]

    @classmethod
    def by_name(cls, name: str) -> T:
        return cls.children[name]()

    def __init_subclass__(cls):
        super().__init_subclass__()
        try:
            cls.children[cls.__name__.lower()] = cls
        except AttributeError:
            cls.children = {}


class NonGenericBase(GenericClass['NonGenericBase'], ABC):
    @abstractmethod
    def my_method(self) -> bool:
        pass


class Child(NonGenericBase):
    def my_method(self) -> bool:
        return True


NonGenericBase.by_name('child').my_method()
```
Checking that code with mypy generates:
`test.py:33: error: "T" has no attribute "my_method"`

From my understanding type of `NonGenericBase.by_name` should be `Callable[[str], NonGenericBase]` (because `NonGenericBase` is `GenericClass['NonGenericBase']`) but it looks like it is `Callable[[str], T]`

**Comment by ilevkivskyi** [comment] 2018-10-24 11:01
This is a duplicate of https://github.com/python/mypy/issues/3645 (we already have a PR that aims to fix this, so hopefully this will be fixed in the next release).

**Closed by ilevkivskyi** 2018-10-24 11:01 UTC
