### ISSUE TITLE
Problems with Enums: iteration, __new__

### ISSUE THREAD

**Issue by ilinum** [python/mypy#3622] opened 2017-06-27 22:57 UTC
Consider the following perfectly valid python code:

```py
from enum import IntEnum, Enum

class Colors(IntEnum):
    RED = 0
    BLUE = 1

class Colors2(int, Enum):  # E: Definition of "__new__" in base class "int" is incompatible with definition in base class "Enum"
    GREEN = 0
    PURPLE = 1

for color in Colors:  # E: Type[Colors] has no attribute "__iter__"
    print(color.name)

for color in Colors2:  # E: Type[Colors2] has no attribute "__iter__"
    print(color.name)
```

This probably has to do with support for metaclasses. Here is the output from mypy and python.

```
$ mypy e.py
e.py:7: error: Definition of "__new__" in base class "int" is incompatible with definition in base class "Enum"
e.py:11: error: Iterable expected
e.py:11: error: Type[Colors] has no attribute "__iter__"
e.py:14: error: Iterable expected
e.py:14: error: Type[Colors2] has no attribute "__iter__"
$ mypy e.py --py2
e.py:7: error: Definition of "__new__" in base class "int" is incompatible with definition in base class "Enum"
e.py:11: error: Iterable expected
e.py:11: error: Type[Colors] has no attribute "__iter__"
e.py:14: error: Iterable expected
e.py:14: error: Type[Colors2] has no attribute "__iter__"
$ python3 e.py
RED
BLUE
GREEN
PURPLE
$ python e.py
RED
BLUE
GREEN
PURPLE
```

**Comment by gvanrossum** [comment] 2017-06-27 23:03
The `__new__` problem is probably separate; the lack of iteration is because IntEnum doesn't have the right metaclass (EnumMeta), and trying to add it gives a different error:
```
__tmp__.py:8: error: Inconsistent metaclass structure for 'Colors2'
```

**Comment by ilevkivskyi** [comment] 2017-06-28 13:20
This seems to be partially related to #3210, and as I mentioned there, this may be solved easily by structural subtyping. However, the ``__new__`` part looks harder to fix.

**Comment by ilinum** [comment] 2017-07-07 17:38
The `__new__` issue seems to be addressed here: https://github.com/python/typeshed/issues/1464

**Comment by JelleZijlstra** [comment] 2017-07-07 17:46
Oh right, this is a near-duplicate of the typeshed issue I opened. I think there may be more regressions here since the last mypy release, so I'll look into this more (hopefully tonight).

**Comment by elazarg** [comment] 2017-09-08 09:04
I believe this is a duplicate of #2824

**Comment by elazarg** [comment] 2017-09-08 15:29
More general: python/typeshed#1595

**Comment by ethanhs** [comment] 2017-09-08 18:42
Closing as a duplicate of #2824

**Closed by ethanhs** 2017-09-08 18:42 UTC
Labels: bug, priority-1-normal
