### ISSUE TITLE
Missing Liskov error for subclass with subclass field

### ISSUE THREAD

**Issue by NoamNol** [python/mypy#11720] opened 2021-12-12 12:19 UTC
**Mypy is ok with the following code. why?**

```python
class Animal():
    pass

class Bird(Animal):
    def fly(self):
        print("fly")

class Farm():
    animal = Animal()

class FarmWithBirds(Farm):
    animal = Bird() # why mypy is ok?

def func(f: Farm):
    f.animal = Animal() # the magic

f = FarmWithBirds()
f.animal.fly() # print "fly"
func(f)
f.animal.fly() # AttributeError: 'Animal' object has no attribute 'fly'
```

Related: #2984, [Incompatible overrides](https://mypy.readthedocs.io/en/latest/common_issues.html?highlight=Liskov#incompatible-overrides)

**Comment by intgr** [comment] 2021-12-12 16:04
Note that this works as I expected when you assign the `animal` attribute in `__init__`:

```python
class Animal():
    pass

class Bird(Animal):
    def fly(self):
        print("fly")

class Farm():
    def __init__(self):   # <-- added
        self.animal = Animal()

class FarmWithBirds(Farm):
    def __init__(self):   # <-- added
        self.animal = Bird()

def func(f: Farm):
    f.animal = Animal() # the magic

f = FarmWithBirds()
reveal_type(f.animal) # note: Revealed type is "issue11720.Animal"
f.animal.fly() # error: "Animal" has no attribute "fly"
```

Not sure why class variables are handled differently in this case.

**Comment by AlexWaygood** [comment] 2022-04-02 15:45
Mypy also [does not emit](https://mypy-play.net/?mypy=latest&python=3.10&flags=strict%2Ccheck-untyped-defs&gist=972d3d84e7febd49485eddf388f8dd25) any errors for this variation:

```python
from typing import ClassVar

class Animal:
    pass

class Bird(Animal):
    def fly(self) -> None:
        print("fly")

class Farm:
    animal: ClassVar[Animal] = Animal()

class FarmWithBirds(Farm):
    animal: ClassVar[Bird] = Bird() # why mypy is ok?

def func(f: type[Farm]) -> None:
    f.animal = Animal() # the magic

f = FarmWithBirds
f.animal.fly() # print "fly"
func(f)
f.animal.fly() # AttributeError: 'Animal' object has no attribute 'fly'
```

I think this is a bug.

**Comment by hauntsaninja** [comment] 2023-08-13 21:01
Duplicate of https://github.com/python/mypy/issues/3208

**Closed by hauntsaninja** 2023-08-13 21:01 UTC
Labels: bug, topic-inheritance
