### ISSUE TITLE
Incorrect type if annotation comes before assignment

### ISSUE THREAD

**Issue by Dreamsorcerer** [python/mypy#11837] opened 2021-12-23 13:04 UTC
```
        method: Optional[Callable[[], Awaitable[StreamResponse]]]
        method = getattr(self, self.request.method.lower(), None)
        reveal_type(method)
```
```
aiohttp/web_urldispatcher.py:934: note: Revealed type is "Union[Any, None]"
```

vs.

```
        method: Optional[Callable[[], Awaitable[StreamResponse]]] = getattr(
            self, self.request.method.lower(), None)
        reveal_type(method)
```
```
aiohttp/web_urldispatcher.py:934: note: Revealed type is "Union[def () -> typing.Awaitable[aiohttp.web_response.StreamResponse], None]"
```

Expectation is that both versions should have the same type (and not be `Any`).

Tested with mypy 0.930.

Full code at: https://github.com/aio-libs/aiohttp/pull/6452/files#diff-9632858c8fdd45d817126b2735f763b9a2e24fb2800122eb2cb0c9a3b89c85c1

**Comment by erictraut** [comment] 2023-08-12 21:33
Mypy doesn't currently apply narrowing to assignments if the assignment occurs on the same line as the type annotation.

This is a duplicate of https://github.com/python/mypy/issues/2008.

**Closed** 2023-08-13 02:56 UTC
Labels: bug
