### ISSUE TITLE
Overloaded functions and aliases not working together

### ISSUE THREAD

**Issue by canepan** [python/mypy#8216] opened 2019-12-29 07:55 UTC
Please provide more information to help us understand the issue:

* Reporting a bug
* failing (mock) code:
```
class CustomType:
    myattr: str = ''

def _custom_repr(v: CustomType) -> str:
    return v.myattr

@attr.s
class MyClass(object)
    myvar: CustomType = attr.ib(repr=_custom_repr)
```
* the actual output: `error: No overload variant matches argument type "Callable[[Any], str]"`
* the behavior/output I expect: mypy should succeed
* mypy 0.720
* mypy flags: `--python-version 3.6 --python-executable python3.6`
* mypy flags (from config): `ignore_missing_imports = True`
* If mypy crashed with a traceback, please paste
  the full traceback below.

possibly related to: https://github.com/python/mypy/issues/6157 , https://github.com/python/mypy/issues/8092

**Comment by AlexWaygood** [comment] 2022-03-28 23:40
I tried running mypy on this snippet locally:

```python
import attr

class CustomType:
    myattr: str = ''

def _custom_repr(v: CustomType) -> str:
    return v.myattr

@attr.s
class MyClass(object):
    myvar: CustomType = attr.ib(repr=_custom_repr)
```

But I could not reproduce the error with version 0.942 of mypy. So I assume that this issue is now fixed.

**Closed by AlexWaygood** 2022-03-28 23:40 UTC
