### ISSUE TITLE
Type Inference with for loop incorrect

### ISSUE THREAD

**Issue by alanhdu** [python/mypy#8272] opened 2020-01-10 20:44 UTC
Using `mypy 0.761` on Python 3.6, the following code, running `mypy --warn-unreachable` on the following code fails:

```python
from typing import Sequence, List


def remove_duplicates(xs: Sequence[int]) -> Sequence[int]:
    output: List[int] = []

    prev = None
    for x in xs:
        reveal_type(prev)

        if prev == x:
            continue
        elif prev is not None and prev != 999:
            output.append(prev)
        prev = x

        reveal_type(prev)
    reveal_type(prev)
    return output
```

with

```
$ mypy --warn-unreachable scratch.py 
scratch.py:9: note: Revealed type is 'None'
scratch.py:13: error: Right operand of 'and' is never evaluated
scratch.py:14: error: Statement is unreachable
scratch.py:17: note: Revealed type is 'builtins.int*'
scratch.py:18: note: Revealed type is 'Union[builtins.int*, None]'
```

This is clearly false -- it is possible for the `prev != 999` to actually run. The `reveal_type`s indicate that this has something to do with type inference: although `mypy` successfully infers that `prev` is `Optional[int]` after the for loop, it does not combine the `int` and `None` types *during* the for loop.

**Comment by msullivan** [comment] 2020-01-10 21:26
Yeah this is a bad one. Duplicate of https://github.com/python/mypy/issues/5423. Thanks for the report!

**Closed by msullivan** 2020-01-10 21:26 UTC
