### ISSUE TITLE
Narrow literal type iterating fixed container

### ISSUE THREAD

**Issue by mixilchenko** [python/mypy#13558] opened 2022-08-30 11:32 UTC
Code to run static analysis on
```python
from typing import Final, Literal

for x1 in ('a', 'b'):
    reveal_type(x1)
    
xs2: tuple[Literal['a', 'b'], ...] = ('a', 'b')
for x2 in xs2:
    reveal_type(x2)

xs3: Final = ('a', 'b')
for x3 in xs3:
    reveal_type(x3)

x4: Literal['a', 'b']
for x4 in ('a', 'b'):
    reveal_type(x4)
```

Mypy (master and 0.971) result
```
main.py:4: note: Revealed type is "builtins.str"
main.py:8: note: Revealed type is "Union[Literal['a'], Literal['b']]"
main.py:12: note: Revealed type is "builtins.str"
main.py:15: error: Incompatible types in assignment (expression has type "str", variable has type "Literal['a', 'b']")
main.py:16: note: Revealed type is "Union[Literal['a'], Literal['b']]"
```

Expected Mypy result
```
main.py:4: note: Revealed type is "Union[Literal['a'], Literal['b']]"
main.py:8: note: Revealed type is "Union[Literal['a'], Literal['b']]"
main.py:12: note: Revealed type is "Union[Literal['a'], Literal['b']]"
main.py:16: note: Revealed type is "Union[Literal['a'], Literal['b']]"
```

**Comment by AlexWaygood** [comment] 2022-09-02 13:12
Duplicate of #12535

**Closed by AlexWaygood** 2022-09-02 13:12 UTC
Labels: feature, topic-literal-types, topic-type-narrowing
