### ISSUE TITLE
(regression: 1.5.1) mypy thinks TypeVar bound to DataclassInstance is not bound to dataclass

### ISSUE THREAD

**Issue by JSS95** [python/mypy#16155] opened 2023-09-21 13:49 UTC
**Bug Report**

`TypeVar("T", bound=DataclassInstance)` is clearly bound to dataclass, but mypy thinks otherwise.

**To Reproduce**

```python
import dataclasses
from typing import TypeVar, Generic, TYPE_CHECKING

if TYPE_CHECKING:
    from _typeshed import DataclassInstance


T = TypeVar("T", bound=DataclassInstance)


class MyGeneric(Generic[T]):
    Dcls: T

    def foo(self) -> T:
        return dataclasses.replace(self.Dcls)
```

[mypy playground link](https://mypy-play.net/?mypy=latest&python=3.11&gist=e76eff43325eb0a48ce0b43267628dac)

**Expected Behavior**

mypy check should pass. (It was OK until 1.4.1)

**Actual Behavior**

```
main.py:15: error: Argument 1 to "replace" has a variable type "T" not bound to a dataclass  [misc]
Found 1 error in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: 1.5.1
- Mypy command-line flags: no flag
- Mypy configuration options from `mypy.ini` (and other config files): no config
- Python version used: 3.11.5

**Comment by AlexWaygood** [comment] 2023-09-21 13:54
Duplicate of #15843. The fix probably won't make it into mypy 1.6, but should make it into mypy 1.7.

**Closed by AlexWaygood** 2023-09-21 13:54 UTC
Labels: bug
