### ISSUE TITLE
File checking with following relative imports fails if working directory is too specific

### ISSUE THREAD

**Issue by FichteFoll** [python/mypy#3958] opened 2017-09-15 01:59 UTC
Considering the following file structure:
```
/tmp/mypytest
├── config.py
├── __init__.py
└── util.py
```
with `config.py` having the following contents:

```py
from . imort util
```

Running the following raises an exception:
```
$ cd /tmp/mypytest
$ mypy config.py                                                                          
Traceback (most recent call last):
  File "/usr/bin/mypy", line 11, in <module>
    load_entry_point('mypy==0.521', 'console_scripts', 'mypy')()
  File "/usr/lib/python3.6/site-packages/mypy/__main__.py", line 7, in console_entry
    main(None)
  File "/usr/lib/python3.6/site-packages/mypy/main.py", line 50, in main
    res = type_check_only(sources, bin_dir, options)
  File "/usr/lib/python3.6/site-packages/mypy/main.py", line 97, in type_check_only
    options=options)
  File "/usr/lib/python3.6/site-packages/mypy/build.py", line 196, in build
    graph = dispatch(sources, manager)
  File "/usr/lib/python3.6/site-packages/mypy/build.py", line 1793, in dispatch
    graph = load_graph(sources, manager)
  File "/usr/lib/python3.6/site-packages/mypy/build.py", line 1902, in load_graph
    ancestor_for=st)
  File "/usr/lib/python3.6/site-packages/mypy/build.py", line 1347, in __init__
    assert id or path or source is not None, "Neither id, path nor source given"
AssertionError: Neither id, path nor source given
```

It works if you cd outside of `mypytest`.

The suspected problem is that mypy cannot work with the relative import because it does not consider `mypytest` to be a package when it is run within that directory already.
Imo, mypy should consider the current working directory and all parent folders as packages, if they contain `__init__.py`.

The context of this issue is tooling. For now, I will add a workaround to the tooling code that changes the working dir to the first dir without an `__init__.py` file.

---
python 3.6.2; mypy: 0.521; typed_ast: 1.1.0
OS: Arch

**Comment by gvanrossum** [comment] 2017-09-15 02:10
Duplicate of #2974.

**Closed by gvanrossum** 2017-09-15 02:10 UTC

**Comment by FichteFoll** [comment] 2017-09-15 02:49
My bad, I searched for things related to the "working directory" instead of the error message of the exception.

Just for the record: I am fine with the decision not to implement a workaround for this case and require the running conditions to be sane instead.

**Comment by gvanrossum** [comment] 2017-09-15 04:04
Honestly I wish it gave a reasonable error message rather than crashing.

**Comment by ethanhs** [comment] 2017-09-15 05:31
I think I have an idea of how that could be done, I just need to test it.
