### ISSUE TITLE
loop over literal tuple of final lose type

### ISSUE THREAD

**Issue by ZeeD** [python/mypy#10332] opened 2021-04-16 09:21 UTC
example file:

```python
from typing import Final, Literal

FOO: Final[Literal['foo']] = 'foo'
BAR: Final[Literal['bar']] = 'bar'


foo = FOO
bar = BAR
reveal_type(foo)
reveal_type(bar)
for foo_or_bar in (FOO, BAR):
    reveal_type(foo_or_bar)
```

expected behavior:

```bat
>mypy f.py
f.py:9: note: Revealed type is 'Literal['foo']'
f.py:10: note: Revealed type is 'Literal['bar']'
f.py:12: note: Revealed type is 'Union[Literal['foo'], Literal['bar']]'
>
```

actual behavior:

```bat
>mypy f.py
f.py:9: note: Revealed type is 'Literal['foo']'
f.py:10: note: Revealed type is 'Literal['bar']'
f.py:12: note: Revealed type is 'builtins.str'
>
```

**Comment by Akuli** [comment] 2021-04-19 16:40
Duplicate of #9230

**Closed** 2021-04-19 19:25 UTC
Labels: bug
