### ISSUE TITLE
Generic Self Type

### ISSUE THREAD

**Issue by jboning** [python/mypy#2537] opened 2016-12-08 00:22 UTC
This is a followup issue to #1212. #2193 enabled method type annotations to refer to the type of `self`, but (intentionally) didn't address generic classes. In many cases, the self types added there meet the needs of generic classes, but not always.

A motivating example is typeshed's AbstractClass:
```
class AbstractSet(Sized, Iterable[_T_co], Container[_T_co], Generic[_T_co]):
    def __and__(self, s: AbstractSet[Any]) -> AbstractSet[_T_co]: ...
    def __or__(self, s: AbstractSet[_T]) -> AbstractSet[Union[_T_co, _T]]: ...
```

With #2193 we can annotate `__and__`, and it works beautifully:
```
    def __and__(self: SelfT, s: AbstractSet[Any]) -> SelfT: ...
```
```
def f(s, fs):
    # type: (MutableSet[str], FrozenSet[str]) -> None
    reveal_type(s.__and__)  # Revealed type is 'def (typing.AbstractSet[Any]) -> typing.MutableSet[builtins.str]'
    reveal_type(fs.__and__)  # Revealed type is 'def (typing.AbstractSet[Any]) -> typing.FrozenSet[builtins.str]'
```

But, we don't have the tools to give `__or__` a similarly specific type. To do this, we need some way to talk about the "generic" part of the self type.

**Comment by JukkaL** [comment] 2016-12-08 00:59
This feels like a duplicate of #2354, but the example raises somewhat different concerns. Maybe we should copy the example to #2354 and close this issue?

**Comment by jboning** [comment] 2016-12-08 01:02
Oh, indeed! I failed to find that. I'll do that when I'm at a keyboard
later (or feel free to preempt me)

**Closed** 2016-12-08 18:21 UTC
