### ISSUE TITLE
Mypy incorrectly accepts `pass` as returning `List[int]`

### ISSUE THREAD

**Issue by marmistrz** [python/mypy#6139] opened 2019-01-04 11:36 UTC
mypy 0.650

Take the following source:

```test.py
from typing import List

def foo(x: int) -> List[int]:
    pass

print(foo(3)[0])
```

Lint with `mypy --strict test.py` - nothing reported. 
During runtime:
```
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    print(foo(3)[0])
TypeError: 'NoneType' object is not subscriptable
```

`return None` instead of `pass` raises an error, though.

**Comment by ilevkivskyi** [comment] 2019-01-04 12:09
This is a duplicate of https://github.com/python/mypy/issues/2350

**Closed by ilevkivskyi** 2019-01-04 12:09 UTC
