### ISSUE TITLE
Exhaustiveness check on match fails if subject is function call

### ISSUE THREAD

**Issue by schuelermine** [python/mypy#16106] opened 2023-09-13 21:24 UTC
**Bug Report**

 Exhaustiveness check on match fails if checked expression is function call

**To Reproduce**

https://mypy-play.net/?mypy=latest&python=3.11&gist=e12e8ee00b037639ff0887ef65d01d11
is rejected, but
https://mypy-play.net/?mypy=latest&python=3.11&gist=22dc06422f5873e2193134da6fa574a1
is accepted

This also happens with enums

**Expected Behavior**

Both programs should be accepted

**Actual Behavior**

```
main.py:4: error: Missing return statement  [return]
Found 1 error in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: 1.5.1
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: 3.11

**Comment by gandhis1** [comment] 2023-10-31 14:19
This is a duplicate of https://github.com/python/mypy/issues/16276. Technically this issue was first, but that one got more attention.

**Comment by hauntsaninja** [comment] 2023-11-01 06:28
Yup, duplicate

**Closed by hauntsaninja** 2023-11-01 06:28 UTC
Labels: bug
