### ISSUE TITLE
generic parameter with None default populates its TypeVar as Optional when it should just be None sometimes

### ISSUE THREAD

**Issue by glyph** [python/mypy#9468] opened 2020-09-22 20:12 UTC
**Bug Report**

This program

```python3
from typing import TypeVar
T = TypeVar("T")

def returner(x: T = None) -> T:
    return x
```

produces this error

...:5: error: Incompatible return value type (got "Optional[T]", expected "T")

But `returner(None)` is not `Optional`; it should just populate `T` as `None` in that case and carry on.  I don't want it to be `Optional` for other types since that just complicates passing through `T`.

If I change the `None` to, say, `0`, I get instead:

```python3
...:4: error: Incompatible default for argument "x" (default has type "int", argument has type "T")
```

I assume the way to work around this for now is with overrides, but I don't understand if there's some type-theoretic underpinning to this behavior or it's just a bug.

**Your Environment**

- Mypy version used: 0.782
- Mypy command-line flags: (None)
- Mypy configuration options from `mypy.ini` (and other config files): (None)
- Python version used: 3.8.5
- Operating system and version: 
```
ProductName:	Mac OS X
ProductVersion:	10.15.6
BuildVersion:	19G2021
```

**Comment by hauntsaninja** [comment] 2020-09-22 20:18
Dupe of #3737, #8708, #8739, #9179, #9432 and others. First of those has the most discussion (see Guido's and Anders' comments)

**Comment by glyph** [comment] 2020-09-22 20:18
Thank you @hauntsaninja.  I swear I looked for those first, and I did have a feeling they were there :)

**Closed by hauntsaninja** 2020-09-22 20:18 UTC
Labels: bug
