### ISSUE TITLE
Error with `Optional[tuple]` and new match syntax

### ISSUE THREAD

**Issue by grahamjenson** [python/mypy#12801] opened 2022-05-16 21:58 UTC
**Bug Report**

(A clear and concise description of what the bug is.)

**To Reproduce**

code

```
from typing import Optional

def fn(x: Optional[tuple[int, int]]) -> tuple[int, int]:
    match x:
        case (_, 1):
            return x
```

when running:

mypy version 0.950
python 3.10.4

`mypy test.py --show-traceback`

errors with:

```
test.py:5: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.950
Traceback (most recent call last):
  File "mypy/checker.py", line 425, in accept
  File "mypy/nodes.py", line 1408, in accept
  File "mypy/checker.py", line 4149, in visit_match_stmt
  File "mypy/checkpattern.py", line 107, in accept
  File "mypy/patterns.py", line 87, in accept
  File "mypy/checkpattern.py", line 301, in visit_sequence_pattern
  File "mypy/checkpattern.py", line 655, in construct_sequence_child
  File "mypy/checkpattern.py", line 662, in construct_sequence_child
AssertionError: 
test.py:5: : note: use --pdb to drop into pdb
```

**Your Environment**

- Mypy version used: 0.950
- Mypy command-line flags: as above
- Mypy configuration options from `mypy.ini` (and other config files): shouldnt matter
- Python version used: 3.10.4
- Operating system and version: linux ubuntu

**Comment by JelleZijlstra** [comment] 2022-05-16 22:12
Duplicate of #12533

**Closed by JelleZijlstra** 2022-05-16 22:12 UTC
Labels: bug, crash, topic-match-statement
