### ISSUE TITLE
Inheriting type hints from abstract parents

### ISSUE THREAD

**Issue by MaxHalford** [python/mypy#8492] opened 2020-03-04 21:56 UTC
I have a usecase where I have a few interfaces which are classes that each inherit from `abc.ABC`. Each interface defines a set of abstract methods to implement in order to satisfy said interface. I then have several hundred classes that inherit from one of these interfaces. I like this because the interfaces give a clear view of the API. I would really like it if the type hints that I define in my interfaces apply to the classes that inherit from them. 

Basically, I would like `mypy` to raise an error for the following script:

```python
import abc


class Foo(abc.ABC):

    @abc.abstractmethod
    def speak(self, msg: str) -> None:
        pass


class Bar(Foo):

    def speak(self, msg):
        print(msg)


b = Bar()
b.speak(1)  # not a str!
```

I'm aware that I can copy/paste the type hint from `Foo.speak` into `Bar.speak`, but I find that inelegant, error-prone, and less efficient from a code maintenance perspective.

Sorry if this is a duplicate; I tried to search for a similar issue but didn't find one. Feel free to point me to a relevant issue and to close this issue if so.

**Comment by ilevkivskyi** [comment] 2020-03-06 19:39
This is essentially a duplicate of https://github.com/python/mypy/issues/3903

Note there was an earlier attempt to fix it in https://github.com/python/mypy/pull/7548

**Closed by ilevkivskyi** 2020-03-06 19:39 UTC
