### ISSUE TITLE
False negative with calling a TypeVar

### ISSUE THREAD

**Issue by KotlinIsland** [python/mypy#9497] opened 2020-09-29 00:24 UTC
```py
from typing import TypeVar

T = TypeVar("T")
T() # runtime error: TypeError: 'TypeVar' object is not callable
```

**Comment by hauntsaninja** [comment] 2020-09-29 00:40
Thanks, duplicate of #9244

**Closed by hauntsaninja** 2020-09-29 00:40 UTC
Labels: bug

**Comment by hauntsaninja** [comment] 2020-09-29 01:25
Opened a PR with a fix! Thanks again :-)
