### ISSUE TITLE
Forcefully follow import to site-package, despite no py.typed file

### ISSUE THREAD

**Issue by sebastian-philipp** [python/mypy#8421] opened 2020-02-20 14:49 UTC
If I manually do a

`touch .tox/mypy/lib/python3.6/site-packages/kubernetes/py.typed`

 I can

1. increase my testing coverage and
2. remove mypy's 
    ```ini
    [mypy-kubernetes.*]
    ignore_missing_imports=True
    ```

I'm missing a way to force following the import to `kubernetes`. 

Right now, my super ugly workaround in tox is:

```ini
[testenv:mypy]
basepython = python3
deps =
    -r requirements.txt
    mypy
whitelist_externals = touch
commands = touch {envsitepackagesdir}/kubernetes/py.typed
           mypy --config-file=../../mypy.ini \
             -m ... \
```

**Comment by Vozf** [comment] 2020-11-07 09:34
Are there any plans for this? This seems like a super useful feature. There are a lot of packages which have type annotations but forget\don't know about py.typed. Now I need to create a pr to each of those packages, but this is not actually necessary as they already have type annotations, there is only py.typed missing. 
This feature doesn't seem complex but can be very useful

**Comment by ethanhs** [comment] 2020-11-07 14:16
Oh this is a duplicate of https://github.com/python/mypy/issues/8545. I think there seems to be some desire for this feature so I think I will look over the PR related to that issue.

**Closed by ethanhs** 2020-11-07 14:16 UTC
Labels: feature, needs discussion, priority-2-low
