### ISSUE TITLE
must/should-use return values

### ISSUE THREAD

**Issue by ojii** [python/mypy#5597] opened 2018-09-11 09:32 UTC
I would like to suggest a type-hint for return values that must (or maybe should) be used. This would be useful to type-hint immutable objects which are "manipulated" by calling methods on them that return new instances.

Consider the following

```python
s = "hello"
s.replace("e", "a")
assert s == "hallo"
```

This will fail because Python strings are immutable, but a type-checker like mypy would be perfectly happy.

`str.replace` has the following signature (from typeshed):

`def replace(self, old: str, new: str, count: int = ...) -> str: ...`

I would suggest something like:

`def replace(self, old: str, new: str, count: int = ...) -> MustUse[str]: ...`

To indicate that the returned value should be used (rather than assuming the object itself changed).

**Comment by JelleZijlstra** [comment] 2018-09-11 15:31
This is similar to #2499.

**Comment by JukkaL** [comment] 2018-09-11 15:43
I can see how this could be useful. To get the most out of this feature, I wonder if every function without side effects should be annotated with `MustUse[...]`? This would greatly decrease the usefulness of this, I think. But maybe only a small subset of functions are likely to be misused in this way.

To support the original use case, we'd need to use `MustUse[...]` in typeshed, where introducing new features is hard since it's used by multiple tools. Basically this would almost have to be a Python stdlib feature, or at least a generally accepted extension -- you can propose it as such at https://github.com/python/typing.

Another way to accomplish a similar result would be to declare that function has no side effects using something like `@pure`, though this would be way harder to implement in a useful way, at least if we'd try to verify that the body of a function has no side effects.

**Comment by Michael0x2a** [comment] 2018-09-11 16:26
We might not even need to add a custom type or decorator -- it might be sufficient to just check and make sure all functions that return a non-None value are assigned to something. In the case that you genuinely don't need the return value, you could pretty easily silence the warning by doing `_ = foo(...)` or something.

Maybe this is something we could support via the plugins API? I'm thinking the logic I describe above would probably end up being pretty noisy in larger codebases if enabled by default, and we want to minimize the number of new flags we add, so maybe it makes sense to have these sorts of checks live outside the mypy codebase.

(I've actually been tossing around the idea of making an unofficial library that contains a variety of different strictness plugins that would be a home for these sorts of "that would be cool but we don't want to add a flag/don't want to enable by default/this is experimental" sorts of checks. Not sure yet if this is a good idea or not/worth the trouble.)

**Comment by ojii** [comment] 2018-09-12 02:11
> We might not even need to add a custom type or decorator -- it might be sufficient to just check and make sure all functions that return a non-None value are assigned to something. In the case that you genuinely don't need the return value, you could pretty easily silence the warning by doing `_ = foo(...)` or something.

If the default should be flipped, I think there still needs to be a new type to indicate that a result can be discarded, similar to `discardableResult` in [Swift](https://docs.swift.org/swift-book/ReferenceManual/Attributes.html), so `def foo() -> bar:` would be `def foo() -> Discardable[bar]:`.

**Comment by hauntsaninja** [comment] 2023-09-06 22:46
Closing as a duplicate of #6936

**Closed by hauntsaninja** 2023-09-06 22:46 UTC
Labels: feature, priority-2-low
