### ISSUE TITLE
NamedTuple subclasses do not pick up __new__'s signature

### ISSUE THREAD

**Issue by toolforger** [python/mypy#5194] opened 2018-06-11 06:08 UTC
mypy inspects the field names instead of looking at the signature of `__new__`.
(I didn't try `__init__`, that wasn't my use case.)

Mypy 0.610, Python 3.6.3.
Not tried Mypy from git master (haven't checked how to do that).

Code:

```Python
#! /usr/bin/env python3

from typing import List, NamedTuple

class Command(NamedTuple):
    subcommands: List[str]

class HelpCommand(Command):
    def __new__(cls):
        return Command.__new__(cls, subcommands=[])

HelpCommand() # fails in mypy, works in Python
HelpCommand(subcommands=[]) # works in mypy, fails in Python
```

Command: `python3 -m mypy typetest.py`

Output:
```
typetest.py:12: error: Too few arguments for "HelpCommand"
```

Python has a different idea about what should work and what shouldn't:

```
$ ./typetest.py 
Traceback (most recent call last):
  File "./typetest.py", line 12, in <module>
    HelpCommand(subcommands=[]) # works
TypeError: __new__() got an unexpected keyword argument 'subcommands'
```

**Comment by ethanhs** [comment] 2018-06-11 06:22
Closing as a duplicate of #1279.

**Closed by ethanhs** 2018-06-11 06:22 UTC
