### ISSUE TITLE
Show ignored errors

### ISSUE THREAD

**Issue by EduMorenoJ** [python/mypy#12055] opened 2022-01-24 14:57 UTC
**Feature**
It would be quite useful to log as warnings the error that you told mypy to ignore.

**Pitch**
We can configure mypy to ignore any error code with the _disable_error_code_ flag. But we can not see anymore the information of those errors. It would be quite useful to turn that errors into warnings for old codebases that we want to start typing. So we can configure mypy in our ci pipeline to just fail on the errors that we have fixed. Also, see the errors that we still have to fix as warnings and the pipeline can continue.

**Comment by hauntsaninja** [comment] 2022-08-03 08:47
Duplicate of #13201

**Closed by hauntsaninja** 2022-08-03 08:47 UTC
Labels: feature
