### ISSUE TITLE
Change in behavior with  __import__('pkgutil').extend_path()  # type: Iterable[str] 

### ISSUE THREAD

**Issue by ericvw** [python/mypy#7582] opened 2019-09-29 20:14 UTC
I noticed a change in behavior between versions 0.720 and 0.730 when using `pkgutil`-style namespace packages.

For the following `__init__.py` file:

```python
__path__ = __import__('pkgutil').extend_path(__path__, __name__)
```

`mypy == 0.720` will report:

```
$ mypy --version
mypy 0.720

$ mypy --show-traceback __init__.py
__init__.py:2: error: Cannot determine type of '__path__'
```

Thus, I "resolved" this with the following in, in `0.720`:

```python
from typing import Iterable
__path__ = __import__('pkgutil').extend_path(__path__, __name__)  # type: Iterable[str]
``` 

With `mypy ==0.730`, I get the following:

```
$ mypy --version
mypy 0.730

mypy --show-traceback __init__.py
__init__.py:2: error: Module has no attribute "extend_path"
Found 1 error in 1 file (checked 1 source file)
```

When researching this issue, https://github.com/python/mypy/issues/7501#issuecomment-530979414 indicates that `__import__` is not followed.  However, I don't fully understand the change in behavior and had trouble using `git-bisect` to narrow it down.

**Comment by gvanrossum** [comment] 2019-09-29 22:29
The root cause is in python/typeshed#3188, which was incorporated into mypy 0.730. Before that PR, `__import__()` was declared as returning `Any`. Now it's declared as `ModuleType`. While `Any` was to wide (we do know that it will return a module), `ModuleType` is probably too narrow, at least in case the argument is a literal.

I'm thinking that maybe this should be rolled back -- it doesn't make sense to try and do strict type checking on the module returned by `__import__`.

@srittau @ilevkivskyi @JukkaL Thoughts?

**Comment by ilevkivskyi** [comment] 2019-09-30 10:50
I am fine either way. Short term we can set it back to `Any` and later probably add some special casing if the argument is a literal string or a final value (low priority probably).

**Comment by gvanrossum** [comment] 2019-10-01 04:27
@ericvw If you can submit a PR to typeshed to change the return type of `__import__` to `Any` (link to this issue) that would help.

**Comment by msullivan** [comment] 2019-10-01 20:47
I think making it return `Any` is a good idea, since that is probably needed for most uses. I don't think that it is even close to worth trying to support this properly as a special case.

**Comment by msullivan** [comment] 2019-10-01 20:49
So I'm going to close this issue, but I will merge a typeshed PR to change the return type of `__import__`.

**Closed by msullivan** 2019-10-01 20:49 UTC

**Comment by ericvw** [comment] 2019-10-17 19:58
I have created https://github.com/python/typeshed/pull/3383.  Thanks!

**Comment by tigerjack** [comment] 2020-06-30 09:19
I'm having the same behavior in my `__init__.py` file containing

```
from pkgutil import extend_path
__path__ = extend_path(__path__, __name__)
```

and `mypy 0.780`

**Comment by PymZoR** [comment] 2020-07-27 09:37
Same with `mypy 0.782`.
This is troublesome when working on [ROS](https://www.ros.org/) because every catkin packages uses the following template for python modules: https://github.com/ros/catkin/blob/noetic-devel/cmake/templates/__init__.py.in

**Comment by mfarrugi** [comment] 2020-08-12 02:40
Is there a workaround for this that doesn't require annotating every `__path__` reference?

**Comment by gvanrossum** [comment] 2020-08-12 14:46
The last two comments seem to be about an unrelated issue. This issue is only about the type returned by ‘__import__’.

**Comment by mfarrugi** [comment] 2020-08-12 19:34
Ah, looks like we're complaining specifically about `__init__.py:2: error: Cannot determine type of '__path__'` which fits into https://github.com/python/mypy/issues/1422.
