### ISSUE TITLE
self type narrowing not being checked

### ISSUE THREAD

**Issue by graingert** [python/mypy#10763] opened 2021-07-02 22:57 UTC
**Bug Report**

**To Reproduce**

```python
from typing import *

import asyncio

class Readable(Protocol):
    def read(self) -> bytes:
        pass
    
class Seekable(Readable, Protocol):
    def seek(self, v: int) -> int:
        pass
    
T_readable = TypeVar("T_readable", bound=Readable)
T_seekable = TypeVar("T_seekable", bound=Seekable)


class AsyncFile(Generic[T_readable]):
    def __init__(self, v: T_readable):
        self._v = v
        
    async def seek(self: AsyncFile[T_seekable], v: int) -> int:
        return await asyncio.to_thread(self._v.seek, v)
        
    async def read(self) -> bytes:
        return await asyncio.to_thread(self._v.read)
        
        
class Foo:
    def read(self) -> bytes:
        return b"foo"
        
async def amain() -> None:
    af = AsyncFile(Foo())
    reveal_type(AsyncFile)  # note: Revealed type is "def [T_readable <: main.Readable] (v: T_readable`1) -> main.AsyncFile[T_readable`1]"
    await af.read()
    await af.seek(0)
```

**Expected Behavior**

I expected the `await af.seek(0)` line to fail because Foo is Readable but not Seekable

(Write what you thought would happen.)

**Actual Behavior**
https://mypy-play.net/?mypy=latest&python=3.10&flags=strict&gist=16f87d40c290e628b34111d5ed44e6a7

**Your Environment**

Any

**Comment by hauntsaninja** [comment] 2021-07-02 23:52
Note, you can get the error you expect with `async def seek(self: AsyncFile[Seekable], v: int) -> int:`

**Comment by graingert** [comment] 2021-07-03 00:13
@hauntsaninja ah that works and is probably what I should use. Now I don't know what the expected behaviour is.

probably an error here: `async def seek(self: AsyncFile[T_seekable], v: int) -> int:` because there's no way to pass the generic parameter?

**Comment by graingert** [comment] 2021-07-03 16:13
in a similar gist do you know what's happening here?

https://mypy-play.net/?mypy=latest&python=3.10&flags=strict&gist=eb70340e67af5bc97e3dae61078ec345

```python
from typing import Protocol, AnyStr, Generic, TypeVar

import asyncio
import io

T = TypeVar("T")
U = TypeVar("U")
T_co = TypeVar("T_co", covariant=True)


class Readable(Protocol[T_co]):
    def read(self, n: int = ...) -> T_co: ...


class AsyncFile(Generic[T]):
    def __init__(self, fp: T) -> None:
        self._fp = fp
        
    async def read(self: AsyncFile[Readable[T]]) -> T:
        return await asyncio.to_thread(self._fp.read)


async def amain() -> None:
    with open("foo") as fp:
        afp = AsyncFile(fp)
        afp2: AsyncFile[Readable[str]] = AsyncFile(fp)
        reveal_type(await afp2.read())  # why does this work
        reveal_type(await afp.read())  # but this fails?
    
    
    with open("foo", "b") as fpb:
        afpb: AsyncFile[Readable[bytes]] = AsyncFile(fpb)
        reveal_type(await afpb.read())
```

**Comment by erictraut** [comment] 2021-07-03 16:30
I wouldn't expect any of the calls to `read` to pass type checking. All of the calls to `read` generate errors in pyright. I'm not sure why some of them are working in mypy. That looks like a bug.

When you instantiate `AsyncFile`, you are specializing the generic class, effectively replacing all instances of the type variable `T` with a concrete type.

In the case of `afp = AsyncFile(fp)`, `T` is replaced with `TextIoWrapper`. That means the `self` parameter in the `read` method gets the specialized type `AsyncFile[Readable[TextIoWrapper]]`. I don't think that's what you intend.

In the case of `afp2: AsyncFile[Readable[str]] = AsyncFile(fp)`, `T` is replaced with `Readable[str]`. That means the `self` parameter in the `read` method gets the type `AsyncFile[Readable[Readable[str]]`. Once again, I don't think that's what you intend.

You should be able to annotate the `self` parameter with the type `AsyncFile[Readable[Any]]`. That works fine in pyright, but mypy still generates an error. So I think there are still some bugs here that need to be addressed.

**Comment by graingert** [comment] 2021-07-03 16:47
I tried with `AsyncFile[Readable[U]] -> U` and that also failed:

https://mypy-play.net/?mypy=latest&python=3.10&flags=strict&gist=ac15e7f9901b3c97b736721a6dc256b4

**Comment by ilevkivskyi** [comment] 2023-06-28 21:12
I think this is a duplicate of https://github.com/python/mypy/issues/14243 (or actually vice versa, but that issue has a nicer repro).

**Closed by ilevkivskyi** 2023-06-28 21:12 UTC
Labels: bug, topic-self-types
