### ISSUE TITLE
no error when accessing instance variable from class

### ISSUE THREAD

**Issue by DetachHead** [python/mypy#11832] opened 2021-12-23 08:37 UTC
```py
class Foo:
    def __init__(self) -> None:
        self.foo = 1
        
Foo.foo # no error
```
https://mypy-play.net/?mypy=latest&python=3.10&flags=show-error-context%2Cshow-error-codes%2Cstrict%2Ccheck-untyped-defs%2Cdisallow-any-decorated%2Cdisallow-any-expr%2Cdisallow-any-explicit%2Cdisallow-any-generics%2Cdisallow-any-unimported%2Cdisallow-incomplete-defs%2Cdisallow-subclassing-any%2Cdisallow-untyped-calls%2Cdisallow-untyped-decorators%2Cdisallow-untyped-defs%2Cno-implicit-optional%2Cno-implicit-reexport%2Clocal-partial-types%2Cstrict-equality%2Cwarn-incomplete-stub%2Cwarn-redundant-casts%2Cwarn-return-any%2Cwarn-unreachable%2Cwarn-unused-configs%2Cwarn-unused-ignores&gist=266f012831ff5553b5f373ceeff9f77e

**Comment by sobolevn** [comment] 2021-12-23 11:53
It happens because `mypy` does not know which variables are `class-` and which are `instance-` level.

**Comment by AlexWaygood** [comment] 2022-03-29 01:06
Closing as a duplicate of #4886.

**Closed by AlexWaygood** 2022-03-29 01:06 UTC
Labels: bug
