### ISSUE TITLE
self.x: str = 1000. Why is this not an error?

### ISSUE THREAD

**Issue by kurtgn** [python/mypy#7857] opened 2019-11-02 08:07 UTC
The question is basically in the header.

Why is this an error:
```
count: str = 1000  # expression has type "int", variable has type "str"
```

and this is not:

```
class Counter:
    def __init__(self):
        self.count: str = 1000
c = Counter()
```

I have the latest mypy as of today:
```
mypy 0.740 
├── mypy-extensions 0.4.3 
├── typed-ast 1.4.0
└── typing-extensions 3.7.4.1
```

**Comment by ethanhs** [comment] 2019-11-02 08:43
Hi, it looks like `__init__` is not annotated, thus mypy will skip it by default. I recommend that you check out [the docs](https://mypy.readthedocs.io/en/latest/getting_started.html#function-signatures-and-dynamic-vs-static-typing) to learn more.

**Comment by JelleZijlstra** [comment] 2019-11-02 16:02
I feel like it'd be reasonable to change the behavior though. The intent behind mypy's behavior of not type checking unannotated methods is to enable gradual typing: users can gradually add more typing to their codebase, without worrying about type errors in functions that don't have annotations yet. But clearly if the user put a variable annotation in the function, they did intend to apply typing to the function and would expect mypy to typecheck it.

**Comment by ethanhs** [comment] 2019-11-03 07:35
>But clearly if the user put a variable annotation in the function, they did intend to apply typing to the function and would expect mypy to typecheck it.

Yeah, I think this is a reasonable idea.

**Comment by ilevkivskyi** [comment] 2019-11-03 09:16
> Yeah, I think this is a reasonable idea.

This is then essentially a duplicate of https://github.com/python/mypy/issues/3948

**Closed by ilevkivskyi** 2019-11-03 09:16 UTC
