### ISSUE TITLE
Incorrect type inferred for @property decorated functions

### ISSUE THREAD

**Issue by mthuurne** [python/mypy#7974] opened 2019-11-19 03:11 UTC
When mypy 0.740 is run on the following code:
```py
class C:
    @property
    def prop(self) -> int:
        return 123

c = C()
print(c.prop)
getter = C.prop.__get__
print(getter(c))
```
It reports:
```
8: error: "Callable[[C], int]" has no attribute "__get__"
```

I think the problem is that, in general, mypy assumes decorators don't change the signature of the decorated function. When I ask it to reveal the type of `C.prop`, it reports `def (self: testcase.C) -> builtins.int`, which is the signature of the undecorated function, not of the property.

Since the `property` decorator is a built-in, it would be useful to have dedicated support for it in mypy.

**Comment by JukkaL** [comment] 2019-11-19 11:12
This is essentially a duplicate of #6185.

**Closed by JukkaL** 2019-11-19 11:12 UTC
