### ISSUE TITLE
--no-implicit-reexport does not respect calculated __all__ when calculating exports.

### ISSUE THREAD

**Issue by futursolo** [python/mypy#8859] opened 2020-05-20 09:19 UTC
* Are you reporting a bug, or opening a feature request?
This is a bug.

* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.

directory:
```
- /
  |- main.py
  |- test/
     |- __init__.py
     |- a.py
     |- b.py
```

main.py:
```python3
import test


class C(test.A, test.B):
    pass
```

test/__init__.py:
```python3
from .a import *
from .b import *

from . import a
from . import b


__all__ = a.__all__ + b.__all__
```

test/a.py:
```python3
class A:
    pass


__all__ = ["A"]
```

test/b.py:
```python3
class B:
    pass


__all__ = ["B"]
```

Python Interactive Shell:
```
Python 3.8.2 (default, Apr 19 2020, 23:32:12) 
[Clang 11.0.3 (clang-1103.0.32.59)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from test import *
>>> "A" in vars()
True
>>> "B" in vars()
True
>>> 
```

* What is the actual behavior/output?
```
main.py:4: error: Name 'test.A' is not defined
main.py: note: In class "C":
main.py:4: error: Class cannot subclass 'A' (has type 'Any')
main.py: note: At top level:
main.py:4: error: Name 'test.B' is not defined
main.py: note: In class "C":
main.py:4: error: Class cannot subclass 'B' (has type 'Any')
```
* What is the behavior/output you expect?
```
Success: no issues found in 1 source file
```

which can be reproduced by swapping `__all__ = a.__all__ + b.__all__` in `main.py` with `__all__ = ["A", "B"]`.
* What are the versions of mypy and Python you are using?
```
mypy 0.770+dev.85897bd16427a1599e92ee639588795951cac8a0
Python 3.8.2
```

- Do you see the same issue after installing mypy from Git master?
Yeah.

* What are the mypy flags you are using? (For example --strict-optional)
```shell
mypy --python-version 3.8 --strict --show-traceback --ignore-missing-imports --show-error-context main.py
```

**Comment by JukkaL** [comment] 2020-05-22 15:21
Yeah, we could support some forms of `__all__` where the value is a "non-literal" expression. There's no way we can support all cases, however. One open question is what exactly should be supported.

**Comment by dyc3** [comment] 2021-05-18 22:00
I think this would be really beneficial to support. Additionally, I think it would be incredibly powerful to support the use case described here: https://stackoverflow.com/a/67561931/3315164

**Comment by hauntsaninja** [comment] 2022-08-03 08:13
Going to mark this as a duplicate of https://github.com/python/mypy/issues/12582#issuecomment-1111525059

There was a typing-sig discussion that led to pyright's choice of expressions to support

**Closed by hauntsaninja** 2022-08-03 08:13 UTC
Labels: feature, needs discussion, false-positive
