### ISSUE TITLE
``strict``  is global option in config file

### ISSUE THREAD

**Issue by tsangwpx** [python/mypy#16387] opened 2023-11-01 14:59 UTC
**Bug Report**

Currently, ``strict`` was mentioned along with other global/per-module options in the [documentation][1].

[1]: https://mypy.readthedocs.io/en/stable/config_file.html#confval-strict

I believe it is supposed to be both global and per-module option.

**To Reproduce**

If we have ``pyproject.toml``:

```toml
[tool.mypy]

[[tool.mypy.overrides]]
module = ["hello"]
strict = true
strict_equality = false
```

`mypy -vv does_not_exist 2>&1 | less` output like this:
```
TRACE: Options({
 'per_module_options': {'hello': {'disable_error_code': [],
                                  'enable_error_code': [],
                                  'strict_equality': False}},
 'strict_equality': True,
 'warn_return_any': True,
})
```

**Expected Behavior**
the strict option inside ``[[tool.mypy.overrides]]`` is expected to turn on strict options in "hello" module only.
keep the global options unchanged.

`mypy -vv does_not_exist 2>&1 | less` should output like this:

```
TRACE: Options({
 'per_module_options': {'hello': {'disable_error_code': [],
                                  'enable_error_code': [],
                                  'strict_equality': False,
                                  'warn_return_any': True, 
                                  ...}},
 'strict_equality': False,
 'warn_return_any': False,
})
```

EDIT: the ordering of keys may not be preserved in TOML. `strict_equality` value depend on the design.

**Environment**

- Mypy version used: mypy 1.6.1 (compiled: yes)
- Python version used: 3.11.2 (debian bookworm)

**More**

``strict`` is implemented as a trigger which set all strict options in the global section wherever it occurs.

https://github.com/python/mypy/blob/6a8365484e62b9f05817f04aec144d9b783442fe/mypy/main.py#L1234-L1240

**Comment by hauntsaninja** [comment] 2023-11-01 17:59
Duplicate of https://github.com/python/mypy/issues/11401 ; PR welcome!

**Closed by hauntsaninja** 2023-11-01 17:59 UTC
Labels: bug
