### ISSUE TITLE
Default value of Type[T]-argument

### ISSUE THREAD

**Issue by galcik** [python/mypy#5802] opened 2018-10-19 08:58 UTC
```
from typing import Type, TypeVar

T = TypeVar("T", bound="Base")


class Base(object):
    pass


class Subclass(Base):
    pass


def create_instance(instance_type: Type[T] = Base) -> T:
    return instance_type()
```

Mypy (0.641) fails with:
```
Incompatible default for argument "instance_type" (default has type "Type[Base]", argument has type "Type[T]")
```

Revealed types of return values:
```
create_instance()  # <nothing>, but I would expect Base*
create_instance(Base)  # Base*, OK
create_instance(Subclass)  # Subclass*, OK
```

**Comment by ilevkivskyi** [comment] 2018-10-19 09:29
@galcik All behaviour you is expected. What you want is lower bound, while mypy only support upper bounds for type variables, see discussions at the end of https://github.com/python/mypy/issues/3737, which I think this issue is a duplicate of.

**Closed by ilevkivskyi** 2018-10-19 09:29 UTC
