### ISSUE TITLE
`isinstance` doesn't work on type aliases that use a union

### ISSUE THREAD

**Issue by DetachHead** [python/mypy#11673] opened 2021-12-07 01:46 UTC
```py
Foo = int | str

foo: object

isinstance(foo, Foo) # error
isinstance(foo, int | str) # no error
```
https://mypy-play.net/?mypy=master&python=3.10&gist=da37bef9ace54d59c18631a0a9f5bef2

**Comment by sobolevn** [comment] 2021-12-07 18:30
I've also added explicit `TypeAlias` to this example, it also raises an error:

```python
from typing import TypeAlias

A = int | str
B: TypeAlias = int | str

foo: object

isinstance(foo, A)  # error
isinstance(foo, B)  # error 
isinstance(foo, int | str)  # no error, but should be?
```

Output:

```
out/ex.py:8: error: Parameterized generics cannot be used with class or instance checks
out/ex.py:8: error: Argument 2 to "isinstance" has incompatible type "object"; expected "Union[type, UnionType, Tuple[Union[type, UnionType, Tuple[Any, ...]], ...]]"
out/ex.py:9: error: Parameterized generics cannot be used with class or instance checks
out/ex.py:9: error: Argument 2 to "isinstance" has incompatible type "object"; expected "Union[type, UnionType, Tuple[Union[type, UnionType, Tuple[Any, ...]], ...]]"
```

**Comment by sobolevn** [comment] 2021-12-07 18:33
In runtime `isinstance(1, int | str)` works just fine:

```python
>>> isinstance(1, int | str)
True
>>> isinstance(b'', int | str)
False
```

So, I guess the problem is that `isinstance(foo, A)` raises. In my opinion `B` should not be used as a value, when having explicit `TypeAlias` declaration.

**Comment by esoma** [comment] 2021-12-08 01:35
Half of this is fixed in https://github.com/python/mypy/pull/11650

`error: Parameterized generics cannot be used with class or instance checks` will still occur if that is merged. It's something I looked into early on, but didn't want to complicate that PR further.

**Comment by sobolevn** [comment] 2021-12-08 08:43
@esoma awesome! Thank you! 👍

**Comment by dgutson** [comment] 2023-05-04 16:47
> Half of this is fixed in #11650
> 
> `error: Parameterized generics cannot be used with class or instance checks` will still occur if that is merged. It's something I looked into early on, but didn't want to complicate that PR further.

@esoma so what's next? This is indeed still happening.
CC @qequ

**Comment by esoma** [comment] 2023-05-04 18:58
@dgutson That PR didn't receive much attention and I don't use mypy anymore so I haven't pursued it any further.

**Comment by Gunni** [comment] 2023-11-13 09:59
This is still broken.

> error: Parameterized generics cannot be used with class or instance checks  [misc]

> error: Argument 2 to "isinstance" has incompatible type "<typing special form>"; expected "_ClassInfo"  [arg-type]

```py
import ipaddress as i
from typing import TypeAlias, TypeVar, Iterable

IPAddress: TypeAlias = i.IPv4Address | i.IPv6Address
IPInterface: TypeAlias = i.IPv4Interface | i.IPv6Interface

_T = TypeVar('_T', bound=IPInterface | IPAddress)

def get_sort_key(ip: _T) -> tuple[int, IPAddress]:
	# https://github.com/python/mypy/issues/11673
	if isinstance(ip, IPInterface):
		ipaddr = ip.ip
	elif isinstance(ip, IPAddress):
		ipaddr = ip
	else:
		raise ValueError("Unsupported IP type")

	return i.get_mixed_type_key(ipaddr)


def sort_ips(addresses: set[_T]) -> list[_T]:
	return sorted(addresses, key=get_sort_key)
```

**Comment by DetachHead** [comment] 2023-11-13 10:23
@esoma out of curiosity, which type checker did you switch to?

**Comment by sobolevn** [comment] 2023-11-13 11:00
The main problem is that we don't pass `uses_pep604_syntax` information anywhere in the code.
So, it is impossible to separate `Union[str, int]` from `int | str` later in the code, where this error happens.

**Comment by esoma** [comment] 2023-11-13 14:41
@DetachHead 
I probably should have said I _generally_ don't use the python typing system anymore -- don't want to derail this issue with details. When I do I still use mypy.

**Closed** 2024-06-13 21:17 UTC
Labels: bug, topic-pep-604, topic-type-alias, topic-runtime-semantics
