### ISSUE TITLE
1.9.0 Release Tracking Issue

### ISSUE THREAD

**Issue by jhance** [python/mypy#16843] opened 2024-01-31 19:07 UTC
I will be cutting the release branch today (truly a January release!) and probably actually release sometime next week.

Please comment here if there are any outstanding PRs you wish to ensure are in the release branch. I will cherry-pick them if they are not merged before I cut the branch.

**Comment by AlexWaygood** [comment] 2024-01-31 19:10
We haven't done a typeshed sync in a while; we might want to do one before the next release. The automated one two weeks ago failed due to merge conflicts with the cherry-picked commits: https://github.com/python/mypy/actions/runs/7522542054

**Comment by cdce8p** [comment] 2024-01-31 20:23
I would really love to see this one included. It's a simple one line fix, that just needs a review.
- #16803

This here would be nice as well, although I need to investigate one small issue first
- #16832

**Comment by jhance** [comment] 2024-01-31 20:39
https://github.com/python/mypy/pull/16844 for typeshed sync. Thanks for pointing that out.

**Comment by hauntsaninja** [comment] 2024-01-31 21:42
Could be nice to have https://github.com/python/mypy/pull/15043 in 1.9

**Comment by jhance** [comment] 2024-02-06 19:39
The release branch is up (delayed due to typeshed 3.7 issue). So far it looks pretty good.

**Comment by hauntsaninja** [comment] 2024-02-07 19:19
It might be worth cherry picking https://github.com/python/typeshed/pull/11353

**Comment by AlexWaygood** [comment] 2024-02-07 19:23
> It might be worth cherry picking [python/typeshed#11353](https://github.com/python/typeshed/pull/11353)

No need — it's already in the release branch (we did two typeshed syncs in quick succession)

**Comment by cdce8p** [comment] 2024-02-07 23:24
Not sure if it's worth mentioning yet. The release will include support for basic TypeVar defaults [PEP 696](https://peps.python.org/pep-0696/). Would be great to have some more early testers. An example from the PEP

```py
T = TypeVar("T", default=int)

@dataclass
class Box(Generic[T]):
    value: T | None = None

reveal_type(Box())                      # type is Box[int]
reveal_type(Box(value="Hello World!"))  # type is Box[str]
```


> [!IMPORTANT] 
> Not yet working / supported 
> - Defaults for `TypeVarTuples`
> - Defaults which reference other TypeVars
> - _The new syntax but I think that is obvious as mypy doesn't support PEP 695 yet._

**Comment by cdce8p** [comment] 2024-02-10 06:29
Opened two cherry-pick PRs for `1.9`:
- #16899 
- #16900

**Comment by cdce8p** [comment] 2024-02-12 22:30
@jhance What's the current status? Anything we can help with? AFAICT it's just removing the `+dev` version suffix and the blog post. Would be awesome to get the release down soon 🔥🚀

**Comment by jhance** [comment] 2024-03-01 20:04
Unfortunately I was distracted by other problems at work, followed by on PTO, followed by being sick. But I am back now. And opening a PR for the changelog now. (The good news is that we actually updated our pin internally to upgrade for Dropbox a few weeks ago, so the harder part was already done).

**Comment by JelleZijlstra** [comment] 2024-03-08 19:58
The release went out today, thanks!

#17001 reported an issue with the self-check, which was fixed on master (#16949), but not in the release branch. It's probably not worth a bugfix release on its own, but if we do make a 1.9.1, it would be good to include that fix.

**Comment by JelleZijlstra** [comment] 2024-03-11 15:44
For similar reasons, #16928 might be worth backporting (see #17005).

**Comment by hauntsaninja** [comment] 2024-03-11 15:46
https://github.com/python/mypy/pull/17003 fixes a minor regression in 1.9

**Comment by DanielNoord** [comment] 2024-03-13 12:55
Could it be that the git `tag` was misnamed? All versions use `vX.X.X` whereas `1.9.0` doesn't include the `v`. I don't see anything in the changelog about this.
This probably breaks some workflows that use the naming scheme of the tags to build from source (this is how I found out as well).

**Comment by svalentin** [comment] 2024-03-25 11:34
Closing this issue since the 1.9.0 release is done!

**Closed by svalentin** 2024-03-25 11:34 UTC
Labels: meta

**Comment by kloczek** [comment] 2024-04-12 09:14
> Could it be that the git `tag` was misnamed? All versions use `vX.X.X` whereas `1.9.0` doesn't include the `v`. I don't see anything in the changelog about this. This probably breaks some workflows that use the naming scheme of the tags to build from source (this is how I found out as well).

Yeah it broke mine 😋 
My automation relies on exact versioning pattern.
I'm not against tagging patter changes but it would be good to know is that new pattern or just typo on tagging 😃
