### ISSUE TITLE
collections.abc.Iterable[int] does not fail

### ISSUE THREAD

**Issue by ilevkivskyi** [python/mypy#3003] opened 2017-03-14 23:51 UTC
This code:
```python
from collections.abc import Iterable

it: Iterable[int]
```
passes mypy silently, although obviously fails at runtime. This is similar to #2428 but the reason is a bit different: it is related to how typeshed stubs are organized. This is also a bit more difficult to fix than #2428.

**Comment by hauntsaninja** [comment] 2021-05-09 22:16
Duplicate of https://github.com/python/mypy/issues/948

**Closed by hauntsaninja** 2021-05-09 22:16 UTC
Labels: bug, priority-2-low
