### ISSUE TITLE
Crash with TypeVar with bound and @dataclass

### ISSUE THREAD

**Issue by morph-dev** [python/mypy#10705] opened 2021-06-23 18:41 UTC
**Crash Report**
I experienced the crash when using some (I guess uncommon) combination of:
- TypeVar with bound
- @dataclas

**Traceback**
```
generics_test.py:11: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.910
Traceback (most recent call last):
  File "mypy/semanal.py", line 4872, in accept
  File "mypy/nodes.py", line 687, in accept
  File "mypy/semanal.py", line 577, in visit_func_def
  File "mypy/semanal.py", line 609, in analyze_func_def
  File "mypy/semanal.py", line 4583, in defer
AssertionError: Must not defer during final iteration
generics_test.py:11: : note: use --pdb to drop into pdb
```

**To Reproduce**

```
from typing import TypeVar, Generic
from dataclasses import dataclass

T = TypeVar('T', bound='X')

@dataclass
class X:
    x: int

@dataclass
class A(Generic[T]):
    a: int
```

Few things that don't make it crash:
- Moving `T = TypeVar(...)` after `Class X:`
- Adding member of type T to class A

**Your Environment**

- Mypy version used: 0.910
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): N/A
- Python version used: 3.9
- Operating system and version: Ubuntu 20.04.2 LTS

**Comment by morp007** [comment] 2021-08-09 08:21
Hello. Please, explain:
1. why do you consider that this behavior is an error?
1. why do you think that there should be no error?

As for me: I didn't see any error in that behavior in this code, because its strange, because there no forward declaration.

P.S. Sorry for my awful language, its not my native.

**Comment by morph-dev** [comment] 2021-08-09 10:07
> 1. why do you consider that this behavior is an error?
Well, I think that mypy shouldn't crash no matter the code.
It's fine to show error if code is not valid, but it shouldn't crash.

> 2. why do you think that there should be no error?
As said above, it shouldn't crash, no matter the code.

This particular example is a bit weird, since type T is not used inside A, and I don't remember exactly why I needed it (my real use case was more complicated and here I posted minimal reproducible code).

Also, as said in the post, moving TypeVar after class X, makes everything fine, so it makes sense that everything should be fine in this specific order as well.

I hope this gives a bit more clarity.

**Comment by morp007** [comment] 2021-08-12 08:20
Thanks for explanation. I definitely agree with this:
> mypy shouldn't crash no matter the code

**Comment by hauntsaninja** [comment] 2021-09-06 20:11
Thanks for reporting, duplicate of #10140

**Closed by hauntsaninja** 2021-09-06 20:11 UTC
Labels: crash
