### ISSUE TITLE
Not respecting isinstance for type narrowing using boolean short circuit 

### ISSUE THREAD

**Issue by john-dicarlo** [python/mypy#16373] opened 2023-10-30 18:23 UTC
```python
# example.py

foo: list[str | int] = [0,1,2,3,'strings', 'as', 'well', 'here', 'bar', 'baz']

for i in range(len(foo)-1):
    if (isinstance(foo[i+1], str) and foo[i+1].upper() == 'BAR'): #  error: Item "int" of "str | int" has no attribute "upper"  [union-attr]
        print('FOOBAR')

```

I figure this type test is simple enough that mypy should know `foo[i+1]` must be a `str`.

**Your Environment**

mypy 1.6.1 (compiled: yes)
Python 3.10.12

mypy --strict ~/example.py

**Comment by ilevkivskyi** [comment] 2023-11-01 22:44
Duplicate of https://github.com/python/mypy/issues/7339

**Closed by ilevkivskyi** 2023-11-01 22:44 UTC
Labels: bug
