### ISSUE TITLE
Overloads are not inferred

### ISSUE THREAD

**Issue by fabiopicchi** [python/mypy#14995] opened 2023-04-01 17:45 UTC
**Bug Report**

If an overloaded function is called, its return type is not inferred by the types of its arguments if its arguments types are themselves a `Union` of types.

**To Reproduce**

```python
from typing import overload, Union
T = Union[str, int]

@overload
def base(a: int) -> int: ...
@overload
def base(a: str) -> str: ...
def base(a: T) -> T:
    if isinstance(a, int):
        return a + 1
    return a + f",{a}"

def top(b: T) -> T:
    return b + base(b)

```

**Expected Behavior**

No errors

**Actual Behavior**

test.py:14: error: Unsupported operand types for + ("str" and "int")  [operator]
test.py:14: error: Unsupported operand types for + ("int" and "str")  [operator]
test.py:14: note: Both left and right operands are unions
Found 2 errors in 1 file (checked 1 source file)

**Your Environment**

- Mypy version used: mypy 1.1.1 (compiled: yes)
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): defaults
- Python version used: Python 3.9.15

**Comment by tyralla** [comment] 2023-04-03 04:40
I think this is not about the overloaded `base` function but the definition of your `top` function.  Mypy gives the hint that a union is given.  If you switch to a [type variable with value restriction](https://mypy.readthedocs.io/en/stable/generics.html#type-variables-with-value-restriction), everything works as expected:

```python
from typing import overload, TypeVar, Union

U = Union[str, int]
T = TypeVar("T", str, int)

@overload
def base(a: int) -> int: ...
@overload
def base(a: str) -> str: ...
def base(a: U) -> U:
    return a

def top(b: T) -> T:
    return b + base(b)  # no errors

reveal_type(top(1))  # note: Revealed type is "builtins.int"
reveal_type(top("x"))  # note: Revealed type is "builtins.str"
```

**Comment by ssfabiopicchi** [comment] 2023-04-03 09:59
Thanks a lot for the comment and for pointing out the solution.

Before I close this issue, though, I would still like to ask why it was decided that Union doesn't behave as TypeVar in this case.

I feel that the concepts are somehow overlapping. I had only used TypeVar before for Generics and bound types.

**Comment by tyralla** [comment] 2023-04-03 19:40
Yes, it definitely takes some time to gain the necessary intuition about when Unions and when TypeVars (and the different kinds of TypeVars) are best suited.  But after a while (and, at least in my case, some headaches), the small differences become clearer.

As far as I know, Mypy never tries to check the different items of a union separately as it does of the individual items for a TypeVar with value restriction when processing functions.  For your simple example, one could eventually think of implementing such a strategy.  However, I guess one would run into many problems with more complex function bodies.

For illustration, one small extension of your example where Mypy reports a definite error (that occurs in 50 % of all function calls):

```python
from typing import overload, TypeVar, Union
from random import random

U = Union[str, int]

@overload
def base1(a: int) -> int: ...
@overload
def base1(a: str) -> str: ...
def base1(a: U) -> U:
    return a

def base2(a: U) -> U:
    return 1 if random() < 0.5 else "x"

def top1(b: U) -> U:
    b = base1(b)
    return b + base2(b)
```

If Mypy would process Unions like TypeVars, it would need to report an error for line `b = base1(b)`, as it could switch an `int` to a `str` and vice versa.  Or it would need to "re-widen" the type of `b` to the Union in some way so that the original error would be reported, making the whole topic possibly even more opaque.  Seems like much implementation effort for presumably little advantages, given that type variables with value restrictions exist.  But that's just my first thought - no typing pro myself...

**Comment by erictraut** [comment] 2023-08-14 17:19
It looks to me like mypy is working as intended here. Is there anything actionable, or can this issue be closed?

**Closed** 2023-08-14 21:27 UTC
Labels: bug
