### ISSUE TITLE
mypy seems to report fallback imports as redefining the type

### ISSUE THREAD

**Issue by takeda** [python/mypy#5438] opened 2018-08-08 23:21 UTC
When performing a check I am getting this error: `error: Name 'json' already defined (by an import)`

The error points to the last line of these statements:

```
try:
    import simplejson as json
except ImportError:
    import json
```

Here's how I'm running the check: `../py37/bin/mypy --py2 --python-executable ../py27/bin/python --ignore-missing-imports <file>`

**Comment by ilevkivskyi** [comment] 2018-08-09 13:25
Thanks for reporting!

This is a duplicate of a known issue https://github.com/python/mypy/issues/1153

**Closed by ilevkivskyi** 2018-08-09 13:25 UTC

**Comment by ilevkivskyi** [comment] 2018-08-09 13:27
The current solution is to put `# type: ignore` on the second import, this will just silence the error.
