### ISSUE TITLE
Fast parser doesn't complain about signature type comment missing `*` or `**`

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#1997] opened 2016-08-08 16:53 UTC
The following is incorrect:

``` python
def f(*a):
    # type: (int) -> None
    pass
```

and with the old parser I get:

```
__tmp__.py: note: In function "f":
__tmp__.py:1: error: Inconsistent use of '*' in function signature
```

However the new parser is silent about the error.

Ditto for `**`.

(To clarify, the correct type comment would be `# type: (*int) -> None`.)

**Comment by afrieder** [comment] 2017-01-28 04:48
This appears to be impossible to replicate with ast35. In slow parser, type comments were parsed into a type and a kind (ie star arg, kwarg, etc), but in fast parser, only the type is kept, so `str`, `*str`, and `**str` are indistinguishable.

**Comment by ethanhs** [comment] 2017-11-14 11:07
I was looking into this and it appears that the Python AST has no construct that can handle `*int` to mean what it did in the old parser. This is due to the nodes being `test` nodes. The star is traditionally meant to be placed before a `NAME`. We could modify the grammer to support "starred tests" which would allow this, and only use that in this special case.

**Comment by gvanrossum** [comment] 2017-11-14 18:09
Modifying the grammar would be against the plan of only reusing Python's AST module. (It would have to be re-added when we port to each new Python version.)

How is the '*' currently even accepted? (Because when it's there it is accepted.)

**Comment by ethanhs** [comment] 2017-11-14 21:29
I may have been incorrect, I think we could get away with just modifying things locally to where we parse it.
(here: https://github.com/python/typed_ast/blob/f74d9f3f231110639752c30c0ae5fbebe870ebc6/ast3/Python/ast.c#L890).

**Comment by gvanrossum** [comment] 2017-11-14 21:40
Oh, that must be some of the code that was added anyway to support this. I think the grammar rule named 'typelist' (at the end of both Grammar files, `ast{27,3}/Grammar/Grammar`) is used for this, and that code just pulls out the `test` pieces.

**Comment by ethanhs** [comment] 2017-11-14 21:51
Yes, that is what is happening. I thought (and now I'm less sure) that pulling out the star(s) as well would require a grammer modification.

**Comment by gvanrossum** [comment] 2017-11-14 22:28
I guess it'll just require adding some flags somewhere.

**Comment by AlexWaygood** [comment] 2022-04-03 16:07
This [still reproduces](https://mypy-play.net/?mypy=latest&python=3.10&flags=show-column-numbers&gist=4cbafd1557aec57fce053eb2d56a2c15) on mypy 0.941, but I'm changing the priority to "low", since type comments are rarely used in modern Python (parameter and variable annotations are generally preferred nowadays)

**Comment by erictraut** [comment] 2023-08-17 03:44
I think it has been said elsewhere that old-style type comments are considered deprecated. If so, it's probably OK to close this as "won't fix".

**Comment by JelleZijlstra** [comment] 2023-08-17 03:46
Agree, this isn't worth fixing.

**Closed by JelleZijlstra** 2023-08-17 03:46 UTC
Labels: bug, topic-parser, priority-2-low
