### ISSUE TITLE
Generic type alias with param spec

### ISSUE THREAD

**Issue by bersbersbers** [python/mypy#15545] opened 2023-06-29 07:48 UTC
**Bug Report**

In the code below, `decorator_pass` works fine while `decorator_fail` fails. The only difference between the two is that I extracted `Callable[[Method[C, P, T]], Method[C, P, T]]` into its own variable (a generic type alias, if I am not mistaken).

I had expected this to be a duplicate of #11855, but that one is presumably fixed now.

**To Reproduce**

https://mypy-play.net/?mypy=latest&python=3.11&gist=077268582efbbbc19e671b7477cdadda

```python
from typing import Any, Callable, Concatenate, ParamSpec, TypeVar

C = TypeVar("C")
P = ParamSpec("P")
T = TypeVar("T")
Method = Callable[Concatenate[C, P], T | None]

def decorator_pass() -> Callable[[Method[C, P, T]], Method[C, P, T]]:
    def decorator(func: Method[C, P, T]) -> Method[C, P, T]:
        def wrapper(self: C, /, *args: Any, **kwargs: Any) -> T | None:  # noqa: ANN401
            return func(self, *args, **kwargs)
        return wrapper
    return decorator

Wrapper = Callable[[Method[C, P, T]], Method[C, P, T]]
def decorator_fail() -> Wrapper[C, P, T]:
    def decorator(func: Method[C, P, T]) -> Method[C, P, T]:
        def wrapper(self: C, /, *args: Any, **kwargs: Any) -> T | None:  # noqa: ANN401
            return func(self, *args, **kwargs)
        return wrapper
    return decorator

class Class:
    @decorator_pass()
    def fun_pass(self, /) -> None:
        pass

    @decorator_fail()
    def fun_fail(self, /) -> None:
        pass
```

**Expected Behavior**

No error

**Actual Behavior**

> main.py:28: error: Argument 1 has incompatible type "Callable[[Class], None]"; expected "Callable[[<nothing>, VarArg(<nothing>), KwArg(<nothing>)], <nothing> | None]"  [arg-type]

**Your Environment**

- Mypy version used: 1.4.0
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): None
- Python version used: 3.11.4

**Comment by ilevkivskyi** [comment] 2023-08-18 12:03
This is a duplicate of https://github.com/python/mypy/issues/3924

**Closed by ilevkivskyi** 2023-08-18 12:03 UTC
Labels: bug

**Comment by hauntsaninja** [comment] 2023-08-19 21:45
@bersbersbers is the project you were running into this on open source?

**Comment by bersbersbers** [comment] 2023-08-20 05:00
> @bersbersbers is the project you were running into this on open source?

It may be one day, but if so, that day will be far out. So unfortunately, no.
