### ISSUE TITLE
Types not narrowed with constrained TypeVar and walrus

### ISSUE THREAD

**Issue by 0xallie** [python/mypy#12190] opened 2022-02-16 10:58 UTC
**Bug Report**

It's not entirely clear to me if the existing issues regarding the walrus operator are about the same issue, feel free to close this if they are.

With the following code:
```py
if m := re.search(pattern, string):
    return m.group(group)
```
I get this error:
```
Item "None" of "Optional[Match[Any]]" has no attribute "group"  [union-attr]
```
Even though it's impossible for `m` to be `None`, because we just checked its value in the `if`.

There are no errors with this code:
```py
m = re.search(pattern, string)
if m:
    return m.group(group)
```

**Your Environment**

- Mypy version used: 0.931, mypy 0.940+dev.777885f2c26cce195f6d23c80fefae1e66dfaac2
- Mypy command-line flags:
- Mypy configuration options from `mypy.ini` (and other config files):
  ```toml
  python_version = '3.8'
  follow_imports = 'silent'
  ignore_missing_imports = true
  ```
- Python version used: 3.8
- Operating system and version: Debian 11

**Comment by hauntsaninja** [comment] 2022-02-17 02:05
Hmm, this should work, and I can't repro:
https://mypy-play.net/?mypy=latest&python=3.10&gist=873656796bacd5961b0fd6fd721e83b9

Closing because I'm fairly confident mypy supports this, but feel free to re-open if you have a playground link like^ or a self-contained script that reproduces.

**Comment by nyuszika7h** [comment] 2022-02-17 15:05
Looks like it only happens with `AnyStr`:
https://mypy-play.net/?mypy=latest&python=3.10&gist=a21042456be940f5ef61ca090d6d3210

**Comment by hauntsaninja** [comment] 2022-02-17 20:08
Thanks!
Note that that overload doesn't actually work... mypy (and other type checkers) only use the overloads to check callers of the function, not the body of the function. The actual body of your function is untyped, so the params are just treated as Any. If you used `--strict` (which prevents code from going untyped), it would complain about this.

**Comment by shartzog** [comment] 2023-05-31 23:54
I have a related issue with mypy==1.3.0, python 3.10.4.  Given test_mypy.py containing:
```python
test = ['a', 'b', 'c']
if any((_t := itm) == 'c' for itm in test):
    print(f'{_t=}')
else:
    _t = None
print(_t)
```
output:
```cmd
>mypy test_mypy.py
test_mypy.py:3: error: Name "_t" is used before definition  [used-before-def]
Found 1 error in 1 file (checked 1 source file)
```
Let me know if the problem is unique enough warrant it's own issue (or if such an issue already exists) or if it's not a problem for some reason I'm not seeing...

**Comment by shartzog** [comment] 2023-06-01 00:32
The issue I described doesn't seem to fit with the type-narrowing tag, so I'm opening a new one for this.

**Comment by hauntsaninja** [comment] 2023-06-01 01:21
This issue was fixed in https://github.com/python/mypy/pull/14135

**Closed by hauntsaninja** 2023-06-01 01:21 UTC
Labels: bug, topic-pep-572, topic-type-narrowing
