### ISSUE TITLE
The type of class objects is not typechecked properly with unbound TypeVars

### ISSUE THREAD

**Issue by roganov** [python/mypy#1901] opened 2016-07-18 19:45 UTC
Following shouldn't typecheck
```python
import typing


T = typing.TypeVar('T')


class A:
    def __init__(self, x):
        self.x = x


def create(cls: typing.Type[T]) -> T:
    return cls()


create(A)
```

**Comment by gvanrossum** [comment] 2016-07-19 00:15
Hm, yeah. Typically the type variable used for such a function has an upper bound, e.g.
```python
T = TypeVar('T', bound=A)
```
Then you will get an error. See also #1831 (possibly this would be considered a duplicate for that).

**Comment by gvanrossum** [comment] 2016-07-21 22:04
Let's close as a dupe of #1831.

**Closed by gvanrossum** 2016-07-21 22:04 UTC
