### ISSUE TITLE
Mypy doesn't ensure self types are reasonable

### ISSUE THREAD

**Issue by ddfisher** [python/mypy#2374] opened 2016-10-28 23:52 UTC
For example, this typechecks cleanly:

``` py
class C:
    def f(self: str) -> None:
        self.capitalize()
```

Related to #2193.

**Comment by ddfisher** [comment] 2016-10-28 23:54
@elazarg

**Comment by elazarg** [comment] 2016-10-29 23:22
Based on the above issue, this seems like a good idea... :)

**Comment by JukkaL** [comment] 2016-10-31 10:08
This looks like a dupe of #16, but I'll leave this open since there's a PR that references this.

One thought from the discussion at #16: It may be reasonable to have a first argument (at least one not spelled as `self`) with an arbitrary annotation, but that function will not be a proper instance method and should only be callable within the class body. Example:

```
class A:
    def f(x: str) -> int:   # ok
        return int(x)

    a = f('123')  # ok

A().f()  # error, f is not a method
```

#16 has more discussion.

**Comment by gvanrossum** [comment] 2016-10-31 15:45
Hm. Having fixed a bunch of issues the latest master found in both of our
internal repos and typeshed, I would say that the fear of the pattern
(functions without 'self' in classes) is exaggerated. The only thing we
found was an interface (IMetadataProvider) in pkg_resources.py, which was
meant for documentation only.

**Comment by elazarg** [comment] 2016-10-31 22:52
IMO, ideally we would only allow use of such a function from within the class' scope. We would report an error for functions that are used from the outside (as suggested by Jukka), and also for functions that are unused from the inside.

However, personally I would vote for requiring an explicit hint for such functions, keeping the policy and implementation simpler.

**Comment by gvanrossum** [comment] 2016-10-31 23:11
What would such an explicit hint look like?

**Comment by elazarg** [comment] 2016-11-01 11:04
I was thinking about `type: ignore`... But of course it can be something else. And you can use `@staticmethod` I guess.

**Comment by gvanrossum** [comment] 2016-11-01 14:45
Static methods can't be called without a class.
```
>>> @staticmethod
... def f(): pass
...
>>> f()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'staticmethod' object is not callable
>>>
```

**Closed** 2016-11-02 16:45 UTC
