### ISSUE TITLE
No error reported when passing an optional type to a generic function

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#1864] opened 2016-07-14 14:35 UTC
The call to `f` below is accepted, even though it should be an error:

```
from typing import AnyStr, Optional

def f(x: AnyStr, y: AnyStr) -> AnyStr:
    return x + y

def g(x: str, y: str) -> str:
    return x + y

def h(s: Optional[str]) -> None:
    f(s, '')  # No error, even though this is not valid!
    g(s, '')  # Generates error, as expected
```

**Comment by gnprice** [comment] 2016-07-29 01:03
(To be explicit: the OP describes the situation under `--strict-optional`. Without `--strict-optional`, no error is reported at either call, and that's the expected behavior.)

**Comment by ddfisher** [comment] 2016-08-08 23:08
It looks to me like the issue has been fixed!
```
test.py: note: In function "h":
test.py:10: error: Type argument 1 of "f" has incompatible value "Optional[str]"
test.py:11: error: Argument 1 to "g" has incompatible type "Optional[str]"; expected "str"
```

**Comment by ddfisher** [comment] 2016-10-24 19:21
Closing because no longer an issue.

**Closed by ddfisher** 2016-10-24 19:21 UTC
Labels: affects/strict-optional
