### ISSUE TITLE
version 0.930 regression: INTERNAL ERROR AttributeError: attribute 'arguments' of 'FuncDef' undefined

### ISSUE THREAD

**Issue by arielf** [python/mypy#11899] opened 2022-01-04 21:24 UTC
Just sharing a regression I just hit on code that used to pass mypy before.

Unfortunately, updating from git is not an option in my env.

Line 273 in source I can't fully share is the first (def) line below which is one (override) method in a big class:
```
    def update(self,  # type: ignore
               name: Optional[str] = None,
               description: Optional[str] = None,
               metric: Optional[SyntheticObject] = None,
               category: Optional[UserDefinedObjectRequestcategoryEnum] = None,
               cacherefreshseconds: Optional[int] = None,
               refreshDataType: Optional[bool] = None,
               properties: Optional[ColumnParamsR] = None,
               keyEntity: Optional[str] = None,
               dataType: Optional[SomePrivateDataType] = None,
               initialCollection: Optional[str] = None) -> EntityProperty:
```

Stack trace when running mypy is:

```
.../entityproperty.py:273: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.930
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "mypy/checker.py", line 420, in accept
  File "mypy/nodes.py", line 727, in accept
  File "mypy/checker.py", line 770, in visit_func_def
  File "mypy/checker.py", line 781, in _visit_func_def
  File "mypy/checker.py", line 1469, in check_method_override
  File "mypy/checker.py", line 1497, in check_method_or_accessor_override_for_base
  File "mypy/checker.py", line 1583, in check_method_override_for_base_with_name
  File "mypy/checker.py", line 1745, in check_override
  File "mypy/messages.py", line 839, in signature_incompatible_with_supertype
  File "mypy/messages.py", line 861, in pretty_callable_or_overload
  File "mypy/messages.py", line 1937, in pretty_callable
AttributeError: attribute 'arguments' of 'FuncDef' undefined
.../entityproperty.py:273: : note: use --pdb to drop into pdb
```

**Comment by A5rocks** [comment] 2022-01-05 00:08
Looks to me like it's saying your class has a method (I assume this `update` method?) which is incompatible with the class it is inheriting from. And then, when it tries to print the superclass method, it... the superclass method isn't fully cached or something?

Not sure -- does clearing the cache fix this?

**Comment by arielf** [comment] 2022-01-05 03:15
Thank you so much!

Confirming.  Both of the below solutions worked for me:

1) Downgrade to mypy-0.920 while keeping the existing mypy cache
```
python3 -m pip install --user mypy==0.920
```

2) Upgrade back to mypy-0.930 AND clear the mypy cache:
```
python3 -m pip install --user mypy==0.930

rm -rf .mypy_cache
```

Thanks again. This comment was very helpful.

**Comment by arielf** [comment] 2022-01-05 22:59
Sorry I have to take workaround (2) above back.

It solved the issue only for the 1st run (empty cache)

If I rerun mypy, even on a fresh cache (created by mypy-0.930) I get the INTERNAL ERROR again.

so the only real workaroud is (1) above: downgrade back to mypy-0.920

**Comment by hauntsaninja** [comment] 2022-01-07 01:40
I've been running into some mypy crashes that look similar, but have been a little bit tricky to reproduce.

With 0.930
```
/Users/shantanu/.virtualenvs/openai-cbqc/lib/python3.9/site-packages/./transformers/trainer.py:1481: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.930
Traceback (most recent call last):
  File "mypy/checkexpr.py", line 3962, in accept
  File "mypy/nodes.py", line 1633, in accept
  File "mypy/checkexpr.py", line 2078, in visit_member_expr
  File "mypy/checkexpr.py", line 2096, in analyze_ordinary_member_access
  File "mypy/checkmember.py", line 129, in analyze_member_access
  File "mypy/checkmember.py", line 146, in _analyze_member_access
  File "mypy/checkmember.py", line 224, in analyze_instance_member_access
  File "mypy/maptype.py", line 20, in map_instance_to_supertype
AttributeError: attribute 'type_vars' of 'TypeInfo' undefined
/Users/shantanu/.virtualenvs/openai-cbqc/lib/python3.9/site-packages/./transformers/trainer.py:1481: : note: use --pdb to drop into pdb
```

On master
```
  File "/Users/shantanu/dev/mypy/mypy/nodes.py", line 1633, in accept
    return visitor.visit_member_expr(self)
  File "/Users/shantanu/dev/mypy/mypy/checkexpr.py", line 2078, in visit_member_expr
    result = self.analyze_ordinary_member_access(e, is_lvalue)
  File "/Users/shantanu/dev/mypy/mypy/checkexpr.py", line 2096, in analyze_ordinary_member_access
    member_type = analyze_member_access(
  File "/Users/shantanu/dev/mypy/mypy/checkmember.py", line 129, in analyze_member_access
    result = _analyze_member_access(name, typ, mx, override_info)
  File "/Users/shantanu/dev/mypy/mypy/checkmember.py", line 146, in _analyze_member_access
    return analyze_instance_member_access(name, typ, mx, override_info)
  File "/Users/shantanu/dev/mypy/mypy/checkmember.py", line 224, in analyze_instance_member_access
    typ = map_instance_to_supertype(typ, method.info)
  File "/Users/shantanu/dev/mypy/mypy/maptype.py", line 20, in map_instance_to_supertype
    if not superclass.type_vars:
  File "/Users/shantanu/dev/mypy/mypy/nodes.py", line 2880, in __getattribute__
    raise AssertionError(object.__getattribute__(self, 'msg'))
AssertionError: FuncBase for non-methods lack info
/Users/shantanu/.virtualenvs/mypy-fpoc/lib/python3.9/site-packages/transformers/trainer.py:1511: : note: use --pdb to drop into pdb
```

**Comment by hauntsaninja** [comment] 2022-01-07 01:45
Okay, not fully minimal, but I think at least the following should get you a crash:
```
python -m pip install 'mypy==0.930' 'ray[default]==1.9.1' 'transformers==4.15.0' 'pytorch_lightning==1.5.3'
python -m mypy -c 'import ray; reveal_type((ray.get, ray.init, ray.remote))' --show-traceback --ignore-missing-imports --check-untyped-defs
```

**Comment by A5rocks** [comment] 2022-01-07 02:25
I think @hauntsaninja's bug is https://github.com/python/mypy/issues/7045 -- though if it's a 0.930 regression then maybe not.

**Comment by hauntsaninja** [comment] 2022-01-07 02:57
Nice spot! Yeah, that should account for the second stacktrace. The first stacktrace, which is what the repro gives is #10521 and #9081 . It's not a regression since 0.930, I just got fooled by the timing of it popping up in this codebase.

**Comment by fperrin** [comment] 2022-03-09 18:14
I believe I have a small repro case for this internal crash:

```
mkdir app
touch app/__init__.py
cat > app/a.py <<EOF
class Foo:
    def frobnicate(self, *args, **kwargs): pass
EOF

cat > app/b.py <<EOF
from app.a import Foo
class Bar(Foo):
    def frobnicate(self) -> None: pass
EOF
```

Then run `mypy -m app.b` twice. The first one will fail with `Signature of "frobnicate" incompatible with supertype` as expected, the second time triggers an INTERNAL ERROR:

```
(3.9.4-devtools) fperrin-laptop:/tmp/repro-11899% mypy -m app.b
app/b.py:3: error: Signature of "frobnicate" incompatible with supertype "Foo"
app/b.py:3: note:      Superclass:
app/b.py:3: note:          def frobnicate(self, *args: Any, **kwargs: Any) -> Any
app/b.py:3: note:      Subclass:
app/b.py:3: note:          def frobnicate(self) -> None
Found 1 error in 1 file (checked 1 source file)
zsh: exit 1     mypy -m app.b
(3.9.4-devtools) fperrin-laptop:/tmp/repro-11899% mypy -m app.b
app/b.py:3: error: Signature of "frobnicate" incompatible with supertype "Foo"
app/b.py:3: note:      Superclass:
/private/tmp/repro-11899/app/b.py:3: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
If this issue continues with mypy master, please report a bug at https://github.com/python/mypy/issues
version: 0.950+dev.4a744b35e28277e2193feb78de90d3b3cbb3169b
/private/tmp/repro-11899/app/b.py:3: : note: please use --show-traceback to print a traceback when reporting a bug
zsh: exit 2     mypy -m app.b
```

I just tried with `version: 0.950+dev.4a744b35e28277e2193feb78de90d3b3cbb3169b`.

**Comment by KotlinIsland** [comment] 2022-05-20 09:25
This looks like it could be a duplicate of #11899

**Comment by fperrin** [comment] 2022-05-20 10:56
> This looks like a duplicate of #11449

It does indeed. I have a proposed fix in https://github.com/python/mypy/pull/12324, I need to rebase because after recent changes to mypy master.

**Comment by AlexWaygood** [comment] 2022-05-27 17:52
Since we upgraded to mypy 0.960 over at typeshed, I now (for some reason) hit this crash every time I run `mypy_test.py` twice in a row locally. It's always the exact same traceback as in this issue, and it always occurs when mypy runs on our `Flask-SQLAlchemy` stubs.

**Closed** 2022-06-29 12:28 UTC
Labels: crash
