### ISSUE TITLE
Overriding a property with method is not flagged

### ISSUE THREAD

**Issue by ottmihkel** [python/mypy#8386] opened 2020-02-10 13:26 UTC
I recently ran into an issue by accidentally omitting a @property decorator when overriding a property, like eg:

class A:
    @property
    def foo(self) -> bool:
        return True
        
class B(A):
    def foo(self) -> bool:
        return False
        
b = B()

bool(b.foo)
True

Wouldn't it make sense to have mypy emit a warning, at least optionally?

**Comment by ilevkivskyi** [comment] 2020-02-12 23:11
This is essentially a duplicate of https://github.com/python/mypy/issues/7565

**Closed by ilevkivskyi** 2020-02-12 23:11 UTC
