### ISSUE TITLE
bug in not-None inference for list items

### ISSUE THREAD

**Issue by davidszotten** [python/mypy#9304] opened 2020-08-14 09:02 UTC
Apologies if this is already reported, it's hard to know what words to look for

I think this is a bug in the "not None inference"

source:
```
from typing import List, Optional

idx = 0
lst: List[Optional[int]] = []

lst[0] is not None and reveal_type(lst[0])
lst[idx] is not None and reveal_type(lst[idx])
```

```
$ mypy foo.py
foo.py:6: note: Revealed type is 'builtins.int'
foo.py:7: note: Revealed type is 'Union[builtins.int, None]'
```

i would have expected mypy to also tell that the index lookup is identical when it's using a var `idx` and infer the type to be not-None 

```
$ mypy --version
mypy 0.790+dev.fbc45aabdf46c820e81e3fc85e3d50b3ebf28ad0
```

**Comment by JukkaL** [comment] 2020-08-14 11:24
Closing as duplicate of #2199.

**Closed by JukkaL** 2020-08-14 11:24 UTC
