### ISSUE TITLE
Type inference by container membership

### ISSUE THREAD

**Issue by kojiromike** [python/mypy#15855] opened 2023-08-11 20:39 UTC
**Feature**

If `a` is contained by `B[T]`, then `a` must be of type `T`. I think mypy should make this inference, but it does not do so today.

```
from typing import Container


def check(o: object, c: Container[str]) -> str | None:
    if o in c:
        return o  # Incompatible return value type (got "object", expected "Optional[str]")
    return None
```

In the above case, I think it's clear that if `o in c` is `True`, then `o` must have the generic of `c`, in this case `str`.

**Pitch**

Any opportunity to correctly infer a type improves mypy and typechecking in general. This is just such an opportunity.

**Comment by AlexWaygood** [comment] 2023-08-11 20:45
Duplicate of #10977

**Closed by AlexWaygood** 2023-08-11 20:45 UTC
Labels: feature
