### ISSUE TITLE
mypy fails to report issues when PYTHONPATH is set to cwd and absolute path to file is provided

### ISSUE THREAD

**Issue by solstice333** [python/mypy#14066] opened 2022-11-11 05:22 UTC
**Bug Report**

(A clear and concise description of what the bug is.)

**To Reproduce**

- set PYTHONPATH to cwd. In powershell, this would be `$env:PYTHONPATH = (pwd).Path`. In bash, this would be `export PYTHONPATH=$(pwd)`
- run `python -m mypy <absolute path to target file>` where the file specified by `<absolute path to target file>` has an error in it, like `x: int = "foo"`

**Expected Behavior**

mypy should report issues and exit nonzero. 

**Actual Behavior**

Instead, it reports "Success: no issues found in 1 source file" and exits zero

**Your Environment**

- OS: Microsoft Windows 10 Pro, 10.0.18362, Build 18362
- Mypy version used: 0.990
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): None
- Python version used: 3.10.4

**Comment by AlexWaygood** [comment] 2022-11-11 08:31
Duplicate of #14042

**Comment by AlexWaygood** [comment] 2022-11-11 08:32
It's already fixed on master; a patch release with the fix should be coming soon :)

**Closed by AlexWaygood** 2022-11-11 08:31 UTC
Labels: bug

**Comment by solstice333** [comment] 2022-11-11 19:24
@AlexWaygood thanks!
