### ISSUE TITLE
Allow access to nested class using instance

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#235] opened 2013-07-14 16:33 UTC
Accessing a nested class is not possible via an instance (in statically typed code), even though it's fine in Python:

```
import typing
class A:
    class B: pass
    def f(self) -> None:
        self.B()   # error
        A.B()  # ok
```

**Comment by ilevkivskyi** [comment] 2017-05-04 11:22
Actually this is probably a duplicate of #259

**Closed by ilevkivskyi** 2017-05-04 11:22 UTC
Labels: feature
