### ISSUE TITLE
treat a package as if it had py.typed

### ISSUE THREAD

**Issue by davidism** [python/mypy#10783] opened 2021-07-07 17:35 UTC
I would like to be able to force mypy to look at the types provided by a package even if it does not provide a py.typed file. I've found that some packages I use have added good type annotations, but didn't realize they needed to provide a py.typed file as well. Some of these packages are only lightly maintained, so they may not get a new release with the file included any time soon.

mypy will ignore typing if py.typed isn't present, but it seems like that's something that should be overridable, just like you can tell mypy to `ignore_missing_imports` if a package doesn't have typing. I suggest a corresponding configuration such as `assume_typed_imports`.

An example of such a package is [inflect](https://github.com/jaraco/inflect). I opened an issue https://github.com/jaraco/inflect/issues/133 and PR https://github.com/jaraco/inflect/issues/135 to add the file, but it hasn't received attention. I have to add `ignore_missing_imports` currently.

**Comment by ethanhs** [comment] 2021-07-07 23:56
I believe this is a duplicate of #8545.

**Closed by ethanhs** 2021-07-07 23:56 UTC
Labels: feature
