### ISSUE TITLE
TypeDict in bound TypeVar assumes parameter values are of type "object"

### ISSUE THREAD

**Issue by rmorshea** [python/mypy#8231] opened 2020-01-02 21:16 UTC
# Bug Report?

I may be misunderstanding how `TypeVar` works, but it seems to me that the following usage with `TypeDict` should be valid, however I get the error indicated in the comment:

```python
from typing import TypedDict, TypeVar


class Data(TypedDict):
    x: int


T = TypeVar("T", bound=Data)


def f(data: T) -> int:
    return data["x"] + 1  # E: Unsupported operand types for + ("object" and "int")
    

assert f(Data(x=1)) == 2
```

## Report Details

- have you tried it on `master`: no
- what version of MyPy: 0.761
- what flags are you using: none

**Comment by msullivan** [comment] 2020-01-08 23:12
This does look like a bug, yeah. I think the issue is that when doing indexing on a type variable with a typeddict bound, checks it just as a call to `__getitem__` and ends up operating on the typeddict's "fallback" type, which is `typing._TypedDict`, which inherits from `Mapping[str, object]`.

I think it should be pretty easy to make `visit_index_with_type` in `checkexpr.py` try recursively indexing into its bound, if you want to take a shot at fixing it.

**Comment by rmorshea** [comment] 2020-01-09 18:33
I'll take a shot at it.

**Comment by np-hg** [comment] 2020-02-26 19:16
I believe I'm having this issue with non typed dict too (if that's intended).  Some code to reproduce

```python
from typing import Dict, List

someList = ["a", "b", "c", "c", "d"]
d: Dict[str, int] = {}

for x in someList:
    if v := d.get(x):
        v += 1
        d[x] = v
    else:
        d[x] = 1
```

**Comment by JelleZijlstra** [comment] 2020-02-26 19:35
@np-hg that's a different issue, probably related to type narrowing.

**Comment by np-hg** [comment] 2020-02-26 19:36
Should I move it to a new issue? I didn't want to open one without being sure its not a duplicate.

**Comment by JukkaL** [comment] 2020-02-28 15:52
@np-hg Your issue seems to be fixed on GitHub master.

**Comment by ilyalabun** [comment] 2021-11-02 21:45
I gave it a shot. Thanks @msullivan for the tip!

**Closed** 2021-11-09 17:59 UTC
Labels: bug, topic-type-variables, topic-typed-dict, priority-2-low
