### ISSUE TITLE
(🐞) Subscripted `type` with new union syntax in `TypeAlias` incorrectly reports 'Value of type "Type[type]" is not indexable'

### ISSUE THREAD

**Issue by KotlinIsland** [python/mypy#12978] opened 2022-06-13 12:32 UTC
```py
from typing import TypeAlias, Union

A: TypeAlias = type[object] | object  # error: Value of type "Type[type]" is not indexable
B = type[object] | object  # error: Value of type "Type[type]" is not indexable
```

[playground](https://mypy-play.net/?mypy=latest&python=3.10&gist=e3676e4db4dbfd4ad61e548392badd7c)

**Comment by AlexWaygood** [comment] 2022-06-13 14:11
Duplicate of #12392

**Closed by AlexWaygood** 2022-06-13 14:11 UTC
Labels: bug
