### ISSUE TITLE
typed_ast package not automatically installed as dependency by conda (Python 3.7)

### ISSUE THREAD

**Issue by lriesebos** [python/mypy#10714] opened 2021-06-25 14:31 UTC
**Bug Report**

The `typed-ast` package used to be installed automatically as a dependency when using Python 3.7, but not anymore since mypy v0.910 (was still fine for v0.902). Is this expected behavior?

**To Reproduce**

```yml
name: mypy37
channels:
  - defaults
  - conda-forge
dependencies:
  - python<3.8
  - mypy
```

```sh
(base) leon@ubuntu-2004:~$ conda --version
conda 4.10.1
(base) leon@ubuntu-2004:~$ conda env create -f env.yml
Collecting package metadata (repodata.json): done
Solving environment: done
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate mypy37
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) leon@ubuntu-2004:~$ conda activate mypy37
(mypy37) leon@ubuntu-2004:~$ python --version
Python 3.7.10
(mypy37) leon@ubuntu-2004:~$ mypy --version
The typed_ast package is not installed.
You can install it with `python3 -m pip install typed-ast`.
```

**Expected Behavior**

mypy version is printed after command `mypy --version`

**Actual Behavior**

Error message:
```
The typed_ast package is not installed.
You can install it with `python3 -m pip install typed-ast`.
```

**Your Environment**

- Mypy version used: 0.910
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): None
- Python version used: 3.7.10
- Operating system and version: Ubuntu 20.04

**Comment by JelleZijlstra** [comment] 2021-06-25 14:39
This is generally expected behavior: see the "Python 2 Support is Opt-in" section in https://mypy-lang.blogspot.com/2021/06/mypy-0900-released.html.

But it's strange that you run into this with just `mypy --version`, so we may need to improve things here.

**Comment by lriesebos** [comment] 2021-06-25 14:51
Ok I see, tnx for the info!

In my case, I am not trying to check Python 2 code, so I would not need the `typed-ast` package then. So I guess the bug is more about the fact that the error is unnecessarily raised. I used `mypy --version` for demonstrative purposes, but the same exception is also raised when I try to do actual type checking with mypy (targeting Python 3.7 code).

**Comment by hauntsaninja** [comment] 2021-06-27 00:11
Jelle isn't quite right. We still require typed-ast for Python 3.7 and below, regardless of whether you're checking Python 2 or not. This is reflected in the [PEP 508](https://www.python.org/dev/peps/pep-0508/) install requirement here: https://github.com/python/mypy/blob/3dcccf221ead4b3143208fc2a1631336d6186e45/setup.py#L193

For what it's worth I can't repro using pip:
```
(venv) ~/tmp/venv λ python3 --version
Python 3.7.7
(venv) ~/tmp/venv λ python3 -m pip install mypy         
Collecting mypy
  Using cached mypy-0.910-cp37-cp37m-macosx_10_9_x86_64.whl (8.8 MB)
Collecting toml
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting typing-extensions>=3.7.4
  Using cached typing_extensions-3.10.0.0-py3-none-any.whl (26 kB)
Collecting mypy-extensions<0.5.0,>=0.4.3
  Using cached mypy_extensions-0.4.3-py2.py3-none-any.whl (4.5 kB)
Collecting typed-ast<1.5.0,>=1.4.0
  Using cached typed_ast-1.4.3-cp37-cp37m-macosx_10_9_x86_64.whl (224 kB)
Installing collected packages: typing-extensions, typed-ast, toml, mypy-extensions, mypy
Successfully installed mypy-0.910 mypy-extensions-0.4.3 toml-0.10.2 typed-ast-1.4.3 typing-extensions-3.10.0.0
WARNING: You are using pip version 21.1.2; however, version 21.1.3 is available.
You should consider upgrading via the '/Users/shantanu/.virtualenvs/venv/bin/python3 -m pip install --upgrade pip' command.
(venv) ~/tmp/venv λ python3 -m pip list        
Package           Version
----------------- --------
mypy              0.910
mypy-extensions   0.4.3
pip               21.1.2
setuptools        57.0.0
toml              0.10.2
typed-ast         1.4.3
typing-extensions 3.10.0.0
wheel             0.36.2
WARNING: You are using pip version 21.1.2; however, version 21.1.3 is available.
You should consider upgrading via the '/Users/shantanu/.virtualenvs/venv/bin/python3 -m pip install --upgrade pip' command.
(venv) ~/tmp/venv λ python3 -m mypy --version
mypy 0.910
```
I'm not familiar enough with conda to know what it's doing.

**Comment by lriesebos** [comment] 2021-06-28 01:49
Interesting. I also can't reproduce the problem when using venv and pip. I am not very familiar with Conda, but it might be that it does not read the dependencies from `setup.py` but from a Conda package specification. Just tried it again with just mypy and python 3.7 and the output is shown below. I also tried with Conda and python 3.5/3.6. With python 3.5, the typing-ast package is added, but not for 3.6.

```
leon@ubuntu-2004:~$ conda --version
conda 4.10.1
leon@ubuntu-2004:~$ conda create -n mypy_test mypy "python<3.8"
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/leon/miniconda3/envs/mypy_test

  added / updated specs:
    - mypy
    - python[version='<3.8']


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    python-3.7.10              |       h12debd9_4        44.0 MB
    ------------------------------------------------------------
                                           Total:        44.0 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  _openmp_mutex      pkgs/main/linux-64::_openmp_mutex-4.5-1_gnu
  ca-certificates    pkgs/main/linux-64::ca-certificates-2021.5.25-h06a4308_1
  certifi            pkgs/main/linux-64::certifi-2021.5.30-py37h06a4308_0
  ld_impl_linux-64   pkgs/main/linux-64::ld_impl_linux-64-2.35.1-h7274673_9
  libffi             pkgs/main/linux-64::libffi-3.3-he6710b0_2
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-9.3.0-h5101ec6_17
  libgomp            pkgs/main/linux-64::libgomp-9.3.0-h5101ec6_17
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-9.3.0-hd4cf53a_17
  mypy               pkgs/main/noarch::mypy-0.910-pyhd3eb1b0_0
  mypy_extensions    pkgs/main/linux-64::mypy_extensions-0.4.3-py37_0
  ncurses            pkgs/main/linux-64::ncurses-6.2-he6710b0_1
  openssl            pkgs/main/linux-64::openssl-1.1.1k-h27cfd23_0
  pip                pkgs/main/linux-64::pip-21.1.2-py37h06a4308_0
  psutil             pkgs/main/linux-64::psutil-5.8.0-py37h27cfd23_1
  python             pkgs/main/linux-64::python-3.7.10-h12debd9_4
  readline           pkgs/main/linux-64::readline-8.1-h27cfd23_0
  setuptools         pkgs/main/linux-64::setuptools-52.0.0-py37h06a4308_0
  sqlite             pkgs/main/linux-64::sqlite-3.36.0-hc218d9a_0
  tk                 pkgs/main/linux-64::tk-8.6.10-hbc83047_0
  toml               pkgs/main/noarch::toml-0.10.2-pyhd3eb1b0_0
  typing_extensions  pkgs/main/noarch::typing_extensions-3.7.4.3-pyha847dfd_0
  wheel              pkgs/main/noarch::wheel-0.36.2-pyhd3eb1b0_0
  xz                 pkgs/main/linux-64::xz-5.2.5-h7b6447c_0
  zlib               pkgs/main/linux-64::zlib-1.2.11-h7b6447c_3


Proceed ([y]/n)?
```

**Comment by hauntsaninja** [comment] 2021-07-01 02:02
I see https://github.com/conda-forge/mypy-feedstock is a thing, maybe that's what conda's looking at? cc @nehaljwani in case you're the right person for this.

**Comment by nehaljwani** [comment] 2021-07-01 02:47
The problem is with the package in the main (a.k.a defaults) channel:
```zsh
/t/nwani_1624637356 ❯❯❯ conda search --info defaults::mypy=0.910
Loading channels: done
mypy 0.910 pyhd3eb1b0_0
-----------------------
file name   : mypy-0.910-pyhd3eb1b0_0.conda
name        : mypy
version     : 0.910
build       : pyhd3eb1b0_0
build number: 0
size        : 1.3 MB
license     : MIT
subdir      : noarch
url         : https://repo.anaconda.com/pkgs/main/noarch/mypy-0.910-pyhd3eb1b0_0.conda
md5         : 10a6d732158367392816b1a0164102e8
timestamp   : 2021-06-24 08:08:50 UTC
dependencies: 
  - mypy_extensions >=0.4.3,<0.5.0
  - psutil >=4.0
  - python >=3.6
  - toml
  - typing_extensions >=3.7.4
```

The package at conda-forge is correct:
```zsh
/t/nwani_1624637356 ❯❯❯ conda search --info 'conda-forge::mypy=0.910=*py37*'
Loading channels: done
mypy 0.910 py37h5e8e339_0
-------------------------
file name   : mypy-0.910-py37h5e8e339_0.tar.bz2
name        : mypy
version     : 0.910
build       : py37h5e8e339_0
build number: 0
size        : 8.1 MB
license     : MIT
subdir      : linux-64
url         : https://conda.anaconda.org/conda-forge/linux-64/mypy-0.910-py37h5e8e339_0.tar.bz2
md5         : e29e50bbe4003710a5e952b32c5b769f
timestamp   : 2021-06-22 21:36:46 UTC
dependencies: 
  - libgcc-ng >=9.3.0
  - mypy_extensions >=0.4.3,<0.5.0
  - psutil >=4.0
  - python >=3.7,<3.8.0a0
  - python_abi 3.7.* *_cp37m
  - toml
  - typed-ast >=1.4.0,<1.5.0
  - typing_extensions >=3.7.4
```

The feedstock for the defaults channel is available at: https://github.com/AnacondaRecipes/mypy-feedstock . Please open an issue there and the devs at Anaconda, Inc will look into it. Till the issue is fixed at their end, you can opt to use the following environment file instead:
```yaml
name: mypy37
channels:
  - defaults
  - conda-forge
dependencies:
  - python<3.8
  - conda-forge::mypy
```

**Comment by hauntsaninja** [comment] 2021-07-01 03:18
Thank you so much! Seems like there's nothing for mypy itself to do here, so closing the issue

**Closed by hauntsaninja** 2021-07-01 03:18 UTC
Labels: bug
