### ISSUE TITLE
Internal Error: NoneType object is not iterable

### ISSUE THREAD

**Issue by coxley** [python/mypy#3756] opened 2017-07-22 01:55 UTC
Was asked by `mypy` to report this as a bug

```
XXX.py:202: error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues version: 0.520-dev
Traceback (most recent call last):
  File "/mnt/xarfuse/uid-113271/d60148e6-ns-4026531840/__run_xar_main__.py", line 138, in <module>
    __invoke_main()
  File "/mnt/xarfuse/uid-113271/d60148e6-ns-4026531840/__run_xar_main__.py", line 135, in __invoke_main
    runpy._run_module_as_main(module, False)
  File "PATH/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "PATH/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "tools/mypy/main.py", line 6, in <module>
  File "mypy/main.py", line 50, in main
  File "mypy/main.py", line 97, in type_check_only
  File "mypy/build.py", line 189, in build
  File "mypy/build.py", line 1597, in dispatch
  File "mypy/build.py", line 1840, in process_graph
  File "mypy/build.py", line 1939, in process_stale_scc
  File "mypy/build.py", line 1512, in type_check_first_pass
  File "mypy/checker.py", line 183, in check_first_pass
  File "mypy/checker.py", line 270, in accept
  File "mypy/nodes.py", line 565, in accept
  File "mypy/checker.py", line 516, in visit_func_def
  File "mypy/checker.py", line 575, in check_func_item
  File "mypy/checker.py", line 725, in check_func_def
  File "mypy/checker.py", line 270, in accept
  File "mypy/nodes.py", line 812, in accept
  File "mypy/checker.py", line 1189, in visit_block
  File "mypy/checker.py", line 270, in accept
  File "mypy/nodes.py", line 909, in accept
  File "mypy/checker.py", line 2159, in visit_for_stmt
  File "mypy/checker.py", line 286, in accept_loop
  File "mypy/checker.py", line 270, in accept
  File "mypy/nodes.py", line 812, in accept
  File "mypy/checker.py", line 1189, in visit_block
  File "mypy/checker.py", line 270, in accept
  File "mypy/nodes.py", line 971, in accept
  File "mypy/checker.py", line 1938, in visit_if_stmt
  File "mypy/checker.py", line 270, in accept
  File "mypy/nodes.py", line 812, in accept
  File "mypy/checker.py", line 1189, in visit_block
  File "mypy/checker.py", line 270, in accept
  File "mypy/nodes.py", line 856, in accept
  File "mypy/checker.py", line 1196, in visit_assignment_stmt
  File "mypy/checker.py", line 1258, in check_assignment
  File "mypy/checker.py", line 1720, in check_simple_assignment
  File "mypy/checkexpr.py", line 2203, in accept
  File "mypy/nodes.py", line 1900, in accept
  File "mypy/checkexpr.py", line 2289, in visit_await_expr
  File "mypy/checkexpr.py", line 2203, in accept
  File "mypy/nodes.py", line 1304, in accept
  File "mypy/checkexpr.py", line 238, in visit_call_expr
  File "mypy/checkexpr.py", line 446, in check_call_expr_with_callee_type
  File "mypy/checkexpr.py", line 552, in check_call
  File "mypy/types.py", line 1065, in make_simplified_union
  File "mypy/subtypes.py", line 558, in is_proper_subtype
  File "mypy/types.py", line 411, in accept
  File "mypy/subtypes.py", line 594, in visit_instance
TypeError: 'NoneType' object is not iterable
XXX.py:202: note: use --pdb to drop into pdb
```

**Comment by ethanhs** [comment] 2017-07-22 02:36
Hm, that seems to be an incomplete traceback. Based on the source however, I can conclude based on [this comment](https://github.com/python/mypy/blob/0619e26d13ef8c6d3e49baf08eef16fbe55bad9b/mypy/subtypes.py#L133) that [this line](https://github.com/python/mypy/blob/0619e26d13ef8c6d3e49baf08eef16fbe55bad9b/mypy/subtypes.py#L605) needs to be checked for None. Could you provide either a full traceback or run with PDB and verify that is the line throwing an error?

**Comment by gvanrossum** [comment] 2017-07-22 04:51
So probably a dupe of https://github.com/python/mypy/issues/3419.

**Comment by ilevkivskyi** [comment] 2017-07-28 18:44
Yes, I think this is a duplicate of #3419. I am closing this one, I raised the priority of #3419 to high, since this keeps coming.

**Closed by ilevkivskyi** 2017-07-28 18:44 UTC
Labels: crash
