### ISSUE TITLE
False negative with NamedTuple with wrong typename

### ISSUE THREAD

**Issue by KotlinIsland** [python/mypy#9514] opened 2020-10-01 00:27 UTC
```py
from typing import NamedTuple

A = NamedTuple('B', [('a', int)])  # no error
```
`Success: no issues found in 1 source file`

**Comment by gvanrossum** [comment] 2020-10-01 00:35
This one seems simple to fix -- do you want to give it a try?

**Comment by KotlinIsland** [comment] 2020-10-01 00:35
Sure :), where should I start?

**Comment by gvanrossum** [comment] 2020-10-01 00:39
Grep the source code in the mypy subdirectory for NamedTuple to find the code where NamedTuple is handled.

**Comment by momohatt** [comment] 2020-10-05 04:24
I think this is a duplicate of #4589

**Closed** 2020-10-05 04:38 UTC
Labels: bug
