### ISSUE TITLE
Issue with the functools standard library module

### ISSUE THREAD

**Issue by sfermigier** [python/mypy#2590] opened 2016-12-19 17:45 UTC
(I'm just starting with mypy and I've hit the following issue. Sorry if it's a misunderstanding on my side.)

Here's a python module with just an import from the `functools` standard module:

```
➜  /tmp cat toto.py
from functools import singledispatch
```

Mypy fails to check it:

```
➜  /tmp mypy toto.py
toto.py:1: error: Module 'functools' has no attribute 'singledispatch'
```

But this is valid Python code:

```
➜  /tmp python3 toto.py
```

Additional context:

```
➜  /tmp which python3
/usr/local/bin/python3
➜  /tmp which mypy
/usr/local/bin/mypy
➜  /tmp head /usr/local/bin/mypy
#!/usr/local/opt/python3/bin/python3.5
"""Mypy type checker command line tool."""
```

**Comment by ambv** [comment] 2016-12-19 17:50
Thanks for using Mypy and thanks for using singledispatch \o/

The issue is actually with https://github.com/python/typeshed/ which is our "database" for type hints of the standard library and third-party libraries. `singledispatch` is missing from the functools type stub for Python 3:
`https://github.com/python/typeshed/blob/master/stdlib/3/functools.pyi`.

I'm going to go ahead and fix that for you now.

**Comment by ambv** [comment] 2016-12-19 21:04
Alright, fixed in typeshed. We'll need to update the typeshed submodule link and release a new Mypy version for you to see those changes. In the mean time, you can close the python/typeshed repo and point Mypy at it, like this:
```
mypy --custom-typeshed-dir /path/to/your/typeshed --fast-parser ...
```

**Comment by ambv** [comment] 2016-12-19 21:12
cc @gvanrossum: this only needs updating the symlink and can be closed.

**Comment by gvanrossum** [comment] 2016-12-23 21:08
> updating the symlink

I suppose you mean what we refer to (in the commit messages) as "sync typeshed", right? I don't want to say "update the submodule" because the `git submodule update` command does the opposite. The process is closer to (from within the mypy repo) `cd typeshed; git checkout main; git pull; cd ..; git commit typeshed` but that commit should be made on a branch and turned into a proper Pull Request, which should then be merged using the usual procedure. (I've taken shortcuts here and broken the master branch a few times so I don't recommend shortcuts. :-)

**Closed by gvanrossum** 2016-12-23 21:08 UTC
