### ISSUE TITLE
Incompatible return value type (got "function", expected "Callable[..., Any]")

### ISSUE THREAD

**Issue by gcaria** [python/mypy#12053] opened 2022-01-24 10:53 UTC
```python
import glob
from typing import Callable, List


def fun1(b: str) -> List[str]:
    return ["a", "b"] + [b]


def fun(a: str) -> Callable:
    return fun1 if a == "hello" else glob.glob
```
Running mypy (v 0.931) on this file gives:

```python
error: Incompatible return value type (got "function", expected "Callable[..., Any]")  [return-value]
```

Crossposting from [stackoverflow](https://stackoverflow.com/questions/70831013/mypy-got-function-expected-callable-any/70832391#70832391) where an answer suggests that this problem is limited to using the ternary operator, but a bug nevertheless.

**Comment by AlexWaygood** [comment] 2022-03-27 20:59
I'm closing this as a duplicate of #10740, as it's nearly exactly the same behaviour on display

**Closed by AlexWaygood** 2022-03-27 20:59 UTC
Labels: bug, topic-join-v-union, topic-ternary-expression
