### ISSUE TITLE
latest numpy is failing build with `"syntax error"` that cannot be disabled

### ISSUE THREAD

**Issue by squarewave24** [python/mypy#13642] opened 2022-09-09 16:56 UTC
while running mypy getting the following on site-packages/numpy 

```
mypy src --show-error-codes     

/poetry_venv/lib/python3.10/site-packages/numpy/__init__.pyi:636: error: Positional-only parameters are only supported in Python 3.8 and greater  [syntax]
Found 1 error in 1 file (errors prevented further checking)
ERROR: 2
```

versions:

```
[[package]]
name = "mypy"
version = "0.942"
description = "Optional static typing for Python"
category = "dev"
optional = false
python-versions = ">=3.6"
```

```
[[package]]
name = "numpy"
version = "1.23.2"
description = "NumPy is the fundamental package for array computing with Python."
category = "main"
optional = false
python-versions = ">=3.8"

```

tool config:
```
[tool.mypy]
ignore_missing_imports = true
plugins = "sqlalchemy.ext.mypy.plugin"

```

**Comment by AlexWaygood** [comment] 2022-09-09 17:00
Duplicate of #13627, a pinned issue :)

**Closed by AlexWaygood** 2022-09-09 17:00 UTC
Labels: bug
