### ISSUE TITLE
Treat class as frozen if __setattr__ is annotated with NoReturn

### ISSUE THREAD

**Issue by ilevkivskyi** [python/mypy#4572] opened 2018-02-14 16:33 UTC
Sometimes it is convenient to get warning from mypy before they appear as crashes at runtime.
For example:
```python
class Immutable:
    def __setattr__(self, attr: str, val: Any) -> NoReturn:
        raise AttributeError("Not with this class!")

class C(Immutable):
    def __init__(self, val: int) -> None:
        object.__setattr__(self, 'val', val)

c = C(42)
if random() < 0.001:
    c.val = 0  # Ideally mypy should say 'Class "C" is frozen' or similar
```

**Comment by gvanrossum** [comment] 2018-02-14 16:52
This will also be useful once we implement `@dataclass(frozen=True)`.

**Comment by emmatyping** [comment] 2024-12-27 07:29
This looks to be a duplicate of https://github.com/python/mypy/issues/1052

**Closed by emmatyping** 2024-12-27 07:29 UTC
Labels: feature, priority-1-normal
