### ISSUE TITLE
Mypy 1.5 Release Planning

### ISSUE THREAD

**Issue by svalentin** [python/mypy#15588] opened 2023-07-04 16:38 UTC
Planning to make the 1.5 release around middle of July.

Please post here any issues you'd like to see fixed in the release, or PRs you'd like to have merged. Will make the release branch as release-1.5.

**Comment by svalentin** [comment] 2023-07-04 17:11
Looks like typeshed syncing is having a conflict when cherry picking "Remove use of LiteralString in builtins" ([6f913a148](https://github.com/python/mypy/commit/6f913a148e1c1ec126d2009272a4a26ff61b8195))
https://github.com/python/mypy/actions/workflows/sync_typeshed.yml

**Comment by AlexWaygood** [comment] 2023-07-04 17:24
> Looks like typeshed syncing is having a conflict when cherry picking "Remove use of LiteralString in builtins" ([6f913a148](https://github.com/python/mypy/commit/6f913a148e1c1ec126d2009272a4a26ff61b8195)) https://github.com/python/mypy/actions/workflows/sync_typeshed.yml

Here you go:

- #15590

I'm pretty seasoned with these by now 😆

**Comment by svalentin** [comment] 2023-07-04 17:27
Ah, thanks! :D

**Comment by cdce8p** [comment] 2023-07-05 10:42
I would like to see this included. It's just missing a final review.
- #15512

**Comment by cdce8p** [comment] 2023-07-09 11:46
Small fix for a sqlalchemy issue with the PEP 681 implementation
- #15628

**Comment by ikonst** [comment] 2023-07-12 05:49
Fixes a crash introduced in 1.4:
- https://github.com/python/mypy/pull/15629

**Comment by svalentin** [comment] 2023-07-13 18:25
Looks like we have a typeshed bug:
```
from unittest.mock import patch

def addition(a: int, b:int) -> int:
    return a+b

@patch('test.addition')
def patch_test(mock):
    print(mock)

if __name__ == "__main__":
    patch_test()
```

In this simple example mypy says:
```
test.py:12: error: Missing positional argument "mock" in call to "patch_test"  [call-arg]
```

Undoing https://github.com/python/typeshed/commit/9e86c6026a00a7bcc6c77ec8f7925a99930ee983 fixes it

**Comment by cdce8p** [comment] 2023-07-13 20:00
A usability improvement with invalid generic instances. This PR reuses existing args whenever possible instead of replacing everything with `Any`. This would match the pyright behavior.
- #15656

**Comment by svalentin** [comment] 2023-07-14 10:50
I think it's best if we leave https://github.com/python/mypy/pull/15668 for the next release

**Comment by svalentin** [comment] 2023-07-14 11:13
Created the [release-1.5 branch](https://github.com/python/mypy/tree/release-1.5)

**Comment by svalentin** [comment] 2023-07-14 13:00
Hmm, I think we have an issue, but can't find out what changed. Did we remove typeshed for `attr` or something like that?

For this example
```lang=python
import attr

@attr.s(frozen=True)
class SomeProperties(object):
    x = attr.ib(type=str)
    y = attr.ib(type=int)

for field in attr.fields(SomeProperties):
    print(field.name)
    print(field.metadata)
```

mypy-1.4.1 find no issues, but master (and release-1.5):
```
test2.py:9: error: "object" has no attribute "name"  [attr-defined]
test2.py:10: error: "object" has no attribute "metadata"  [attr-defined]
Found 2 errors in 1 file (checked 1 source file)
```

**Comment by svalentin** [comment] 2023-07-14 13:01
The issue is type should be `attr.Attribute`, not object

**Comment by svalentin** [comment] 2023-07-14 13:02
Ah, thanks!

**Comment by AlexWaygood** [comment] 2023-07-14 13:04
> Did we remove typeshed for `attr` or something like that?

(`attrs` hasn't had stubs in typeshed for quite a while; they're a `py.typed` package and bundle their own stubs :)

**Comment by svalentin** [comment] 2023-07-14 13:20
I made https://github.com/python/mypy/pull/15674 to revert it for 1.5 too. But we should probably figure out a more permanent solution. If we are going to keep reverting the change for every release, might as well revert it in master too.

**Comment by AlexWaygood** [comment] 2023-07-16 15:48
This PR fixes a new stubtest false positive that would be somewhat annoying for typeshed -- would be great to get it (or an alternative fix) in for v1.5:

- #15689

**Comment by AlexWaygood** [comment] 2023-07-17 17:19
> This PR fixes a new stubtest false positive that would be somewhat annoying for typeshed -- would be great to get it (or an alternative fix) in for v1.5:
> 
> * [Stubtest: Fix `__mypy-replace` false positives #15689](https://github.com/python/mypy/pull/15689)

There's some discussion on the PR about whether this is the correct fix or not. It would only cause two false positives for typeshed's CI, which can be fairly easily suppressed, so maybe it shouldn't block the release. (Having said that, it might also cause false positives for other projects using stubtest as well, if they're using dataclasses.)

**Comment by AlexWaygood** [comment] 2023-07-22 11:53
It would be great if we could cherry-pick https://github.com/python/typeshed/commit/f577c4c133ae6bb57cade534179b41ef04b5731f onto the 1.5 release branch, so that mypy users will be able to use the latest typing_extensions features -- `typing_extensions 4.7.0` has been out for about a month now

**Comment by AlexWaygood** [comment] 2023-07-22 12:06
> It would be great if we could cherry-pick [python/typeshed@f577c4c](https://github.com/python/typeshed/commit/f577c4c133ae6bb57cade534179b41ef04b5731f) onto the 1.5 release branch, so that mypy users will be able to use the latest typing_extensions features -- `typing_extensions 4.7.0` has been out for about a month now

Opened #15745 to do that

**Comment by hauntsaninja** [comment] 2023-07-22 18:32
I merged your cherry pick, but it looks like the tag was already made. We'll see what happens, worst case we can do a 1.5.1

**Comment by AlexWaygood** [comment] 2023-07-22 18:38
> I merged your cherry pick

Thanks!

> but it looks like the tag was already made.

Ah, I didn't spot that :/

**Comment by svalentin** [comment] 2023-07-22 20:18
Ah, sorry, I didn't realize that creating the tag could cause problems. Thinking about it now, it makes sense. Some people might follow the git tags for releases instead of blog announcements.

**Comment by svalentin** [comment] 2023-08-10 09:59
Thanks for the offer, but we should be good to go. I was waiting for Jukka to help with the blog post as he has context on all the mypy works. He was on vacation until recently. Yesterday he did finish the blog post and we’re unblocked.
I’m looking to finish the release today!

**Comment by svalentin** [comment] 2023-08-10 13:07
mypy 1.5 is out!
Read the blog post here - https://mypy-lang.blogspot.com/2023/08/mypy-15-released.html
Also updated the news on the website https://mypy-lang.org/

**Closed** 2023-08-10 13:09 UTC
Labels: meta

**Comment by svalentin** [comment] 2023-08-10 13:10
Closing this issue as the release is "done". Of course, if there's any issues please post them and we can reopen for a point release!

**Comment by AlexWaygood** [comment] 2023-08-11 10:47
@svalentin I think something's gone wrong with https://github.com/python/mypy/pull/15751 (which backported a stubtest fix to the `release-1.5` branch).

I can see the change included in the `1.5.0` tag and the `release-1.5` branch on GitHub. But if I actually `pip install mypy==1.5` into a virtual environment and then open up `Lib/site-packages/mypy/stubtest.py`, the change isn't there. That means I've got a very red CI for my PR trying to upgrade typeshed's mypy pin :(

- https://github.com/python/typeshed/pull/10559

**Comment by svalentin** [comment] 2023-08-11 12:45
Hmm, yes, I see it too.

Commit [7a9418356](https://github.com/python/mypy/commit/7a9418356)  is in. That's the commit in where we branched off from main for release 1.5.
Commit [9dd0d396e](https://github.com/python/mypy/commit/9dd0d396e) is in as well.
But [373b73abe](https://github.com/python/mypy/commit/373b73abe) or [2ff7c0de5](https://github.com/python/mypy/commit/2ff7c0de5) are not.

I think it maybe grabbed the wrong wheels to upload for pypi.

Let me check with Jukka. We might have to do a 1.5.1 release to pick up those two commits as well as they fix regressions.

**Comment by svalentin** [comment] 2023-08-11 12:50
Will make a 1.5.1 release to pick them up!

**Comment by svalentin** [comment] 2023-08-11 15:10
Unfortunately we hit a 10GB limit for the pypi project.
Jukka filed an issue to increase this limit - https://github.com/pypi/support/issues/3094

We don't think the regressions are serious enough to warrant us deleting some old version of mypy to make room for this point release _right now_. We can probably wait until pypi increases our limits. Hopefully it shouldn't be longer than a few days.

**Comment by erictraut** [comment] 2023-08-14 22:03
Is there anything remaining for the 1.5 release, or can this be closed?

**Comment by JelleZijlstra** [comment] 2023-08-14 22:18
We should probably keep this open for the 1.5.1 release (currently blocked on PyPI size limits) and potentially for another bugfix release if there are further regressions.

**Comment by AlexWaygood** [comment] 2023-08-16 15:40
The PyPI project limit has been bumped to 20GB: https://github.com/pypi/support/issues/3094#issuecomment-1680748325

**Comment by svalentin** [comment] 2023-08-16 16:55
Uploaded v1.5.1 to PyPI!

**Comment by AlexWaygood** [comment] 2023-08-16 21:44
And we've successfully upgraded over at typeshed: https://github.com/python/typeshed/commit/ef758b66c0947a73f6225cac0568f3f068cd61d4

Thanks @svalentin! 🥳
