### ISSUE TITLE
Tuple[A, B] + Tuple[C] = Tuple[Any, …] instead of Tuple[A, B, C]

### ISSUE THREAD

**Issue by bwo** [python/mypy#4604] opened 2018-02-20 20:30 UTC
```python
from typing import Tuple 

x = (1, 't', 2)  # type: Tuple[int, str, int]

z = ('t', 3)  # type: Tuple[str, int]

xz = x + z  # type: Tuple[int, str, int, str, int]
```

Not only is `Tuple[Any, …]` the inferred type of `xz`, mypy won't accept the provided annotation:

```
error: Incompatible types in assignment (expression has type "Tuple[Any, ...]", variable has type "Tuple[int, str, int, str, int]")
```

Running this program through mypy:

```
from typing import TypeVar, Type, Mapping, Sequence, Generator, Tuple  # noqa


x = (1, 't', 2)  # type: Tuple[int, str, int]

z = ('t', 3)  # type: Tuple[str, int]

xz = x + z

reveal_type(xz[0])
```

shows that the type of `xz[0]` is now `Any` (consistent with the inferred type).

IMO if it's not type-theoretically onerous the inferred type of `xz` should be `Tuple[int, str, int, str, int]`.

**Comment by JukkaL** [comment] 2018-02-21 10:53
Closing as duplicate of #224.

**Closed by JukkaL** 2018-02-21 10:53 UTC
Labels: feature
