### ISSUE TITLE
configuration with wildcards cannot match modules?

### ISSUE THREAD

**Issue by asottile** [python/mypy#5449] opened 2018-08-10 22:30 UTC
My goal: enforce `disallow_untyped_defs` in my application but not in my tests.

Here's my setup:

```
mypy.ini
app
├── __init__.py
└── app.py
tests
├── __init__.py
├── subdir
│   └── test_two.py
└── test_one.py
```

The important contents:

```python
# tests/test_one.py
def test_one():
    pass
```

```python
# tests/subdir/test_two.py
def test_two():
    pass
```

And either of these two `mypy.ini` files:

```ini
[mypy]
disallow_untyped_defs = true

[mypy-tests.*]
disallow_untyped_defs = false
```

```ini
[mypy]
disallow_untyped_defs = true

[mypy-tests.*]
disallow_untyped_defs = false

[mypy-tests.subdir.*]
disallow_untyped_defs = false
```

I expect this command to produce no errors:

```console
$ mypy app/__init__.py app/app.py tests/__init__.py tests/subdir/test_two.py tests/test_one.py
tests/subdir/test_two.py:1: error: Function is missing a type annotation
```

### version info

```
$ mypy --version
mypy 0.620
```

CC @ethanhs  since we chatted about this in IRC/slack

**Comment by asottile** [comment] 2018-08-10 22:32
A workaround is to `touch tests/subdir/__init__.py`

though this should not be necessary due to [PEP 420](https://docs.python.org/3/whatsnew/3.3.html#pep-420-implicit-namespace-packages)

**Comment by ethanhs** [comment] 2018-08-10 22:53
This is a duplicate of #1645. I'll bump priority to high over there.

**Closed by ethanhs** 2018-08-10 22:53 UTC
