### ISSUE TITLE
Narrow Union based on tuple fixed length check

### ISSUE THREAD

**Issue by mthuurne** [python/mypy#9171] opened 2020-07-18 22:49 UTC
When mypy 0.782 checks the following code:
```py
from typing import Tuple, Union

def weird_cat(values: Union[Tuple[str, str], Tuple[str, str, str]]) -> str:
    if len(values) == 2:
        return values[0] + values[1]
    else:
        return values[0] + values[2] + values[1]
```
It reports:
```
testcase.py:7: error: Tuple index out of range  [misc]
            return values[0] + values[2] + values[1]
                               ^
```
There is no need to report an error here, since the tuple will always have a third element if the second `return` statement is reached.

I think mypy could filter the `Union` options using the `len(values) == 2` guard, which is always true for `Tuple[str, str]` and always false for `Tuple[str, str, str]`.

The example in [this comment](https://github.com/python/mypy/issues/8733#issuecomment-657241406) from @abey79 looks equivalent to this issue, but the test case for #8733 itself also includes a `List`, so it has to deal with runtime length rather than the static length of a tuple type.

**Comment by ilevkivskyi** [comment] 2020-08-03 06:56
Duplicate of https://github.com/python/mypy/issues/1178

**Closed by ilevkivskyi** 2020-08-03 06:56 UTC
