### ISSUE TITLE
Reassigning variable with `functools.partial` results in `<nothing>`

### ISSUE THREAD

**Issue by GideonBear** [python/mypy#14024] opened 2022-11-07 15:30 UTC
This is a possible duplicate of #12130

**Bug Report**

Reassigning a variable with `functools.partial` results in `<nothing>`
This can be avoided by giving the resulting variable a different name

**To Reproduce**

https://mypy-play.net/?mypy=latest&python=3.10&gist=58ed41f271198877ca999fa669f648fd

**Expected Behavior**

```
main.py:7: note: Revealed type is "def (a: builtins.int, b: builtins.int) -> builtins.int"
main.py:9: note: Revealed type is "functools.partial[builtins.int]"
```

**Actual Behavior**

```
main.py:7: note: Revealed type is "def (a: builtins.int, b: builtins.int) -> builtins.int"
main.py:9: note: Revealed type is "<nothing>"
main.py:10: error: <nothing> not callable
```

**Comment by erictraut** [comment] 2022-11-07 16:22
I think the problem is that your code is assigning the result of `partial(f, 1)` back to the symbol `f`, which already has a declared type that is incompatible with the type you are assigning to it. Mypy's error message is confusing here.

If you assign the result of `partial(f, 1)` to a new variable, say `g`, then it type checks without error and results in the expected behavior.

```python
from functools import partial

def f(a: int, b: int) -> int:
    return a + b

reveal_type(f)
g = partial(f, 1)
reveal_type(g)
assert g(2) == 3
```

**Comment by GideonBear** [comment] 2022-11-07 17:32
> I think the problem is that your code is assigning the result of `partial(f, 1)` back to the symbol `f`, which already has a declare

Ah, but then shouldn't mypy say so when reassigning it? Or is there a specific option to enable errors for that?

Should I close this issue?

**Closed** 2024-07-01 23:36 UTC
Labels: bug
