### ISSUE TITLE
Incorrect inference of `Callable` generic typing

### ISSUE THREAD

**Issue by asottile** [python/mypy#5199] opened 2018-06-11 20:43 UTC
```python
from typing import Callable
from typing import Iterable
from typing import List
from typing import Optional
from typing import TypeVar


class C:
    x: str


T = TypeVar('T')


def f(i: Iterable[T], c: Callable[[T], bool]) -> Optional[T]:
    for x in i:
        if c(x):
            return x
    else:
        return None


def g(l: List[C], x: str) -> Optional[C]:
    return f(l, lambda d: d.x == x)
```

```
$ mypy test.py
test.py:24: error: Item "None" of "Optional[C]" has no attribute "x"
$ mypy --version
mypy 0.610
```

A little bit complicated, though I believe the lambda should be inferenced as `Callable[[C], bool]` though it appears to instead be inferenced as `Callable[[Optional[C]], bool]`

A related, less-lambda-y reproduction:

```python
from typing import Callable
from typing import Iterable
from typing import List
from typing import Optional
from typing import TypeVar


class C:
    x: str


T = TypeVar('T')


def f(i: Iterable[T], c: Callable[[T], bool]) -> Optional[T]:
    for x in i:
        if c(x):
            return x
    else:
        return None


def g(l: List[C], x: str) -> Optional[C]:
    def pred(d: C) -> bool:
        return d.x == x

    return f(l, pred)
```

```
$ mypy test2.py
test2.py:27: error: Argument 2 to "f" has incompatible type "Callable[[C], bool]"; expected "Callable[[Optional[C]], bool]"
```

**Comment by ilevkivskyi** [comment] 2018-06-12 01:05
I believe this is a duplicate of https://github.com/python/mypy/issues/4872. It looks like just another example where mypy inference engine is being to "greedy".

Actually after some thinking it looks like fixing these particular examples might be tricky, so I would like to keep this one open.

**Comment by mantognini** [comment] 2018-06-26 14:35
I'm also interested in a fix for this as I encountered exactly the same issue today. :)

**Closed** 2018-10-02 11:44 UTC
Labels: bug, false-positive, priority-1-normal, topic-type-variables
