### ISSUE TITLE
Type promotion by issubclass doesn't always work

### ISSUE THREAD

**Issue by mthuurne** [python/mypy#6099] opened 2018-12-22 07:08 UTC
When running mypy on the following code:
```py
class C:
    @classmethod
    def cm(cls):
        return 1

def f(t: type) -> int:
    if issubclass(t, C):
        reveal_type(t)
        return t.cm()
    return 0
```
It reports:
```
8: error: Revealed type is 'builtins.type'
9: error: "type" has no attribute "cm"
```
So in the `if` body, mypy considers the type of `t` to be `type`, while the fact that `issubclass` returned `True` indicates that `t` is of type `C`.

Using `issubclass` in this way is the topic of #2909, but that issue was fixed, so there is probably something different in my use case that isn't covered by the existing unit tests.

I'm using a mypy 0.660 dev snapshot.

**Comment by ilevkivskyi** [comment] 2018-12-22 13:33
This is a duplicate of https://github.com/python/mypy/issues/4616

**Closed by ilevkivskyi** 2018-12-22 13:33 UTC
