### ISSUE TITLE
no error for missing return

### ISSUE THREAD

**Issue by Akuli** [python/mypy#12830] opened 2022-05-20 19:35 UTC
mypy 0.950 with `--strict`. Please emit an error for this code. It took a while to track down where the `None` came from...

```python3
class Foo:
    def fix_moving_square(self) -> int:
        pass
```

**Comment by AlexWaygood** [comment] 2022-05-20 20:50
Duplicate of #2350 ://

**Closed by AlexWaygood** 2022-05-20 20:50 UTC
Labels: bug
