### ISSUE TITLE
Type errors using (x, _, _) = (1, 2, "3")

### ISSUE THREAD

**Issue by timabbott** [python/mypy#1649] opened 2016-06-04 22:48 UTC
It's a common pattern to use assignment to `_` in code to ignore variables that aren't used, and mypy doesn't support that:

`/home/tabbott/foo.py:2: error: Incompatible types in assignment (expression has type "str", variable has type "int")`

In my real code the usage looks more like this:

```
for (email, _, _, _) in users:                                                                                                                                     
    ...
```

Not sure whether the right answer is to change the code, but I think I'd flag this as an interesting case that may be somewhat common.

**Comment by gvanrossum** [comment] 2016-06-04 22:58
It's common enough to flag a few variable names as special as targets: `_`, `__`, and `unused` have all been recommended at various times.

**Comment by JelleZijlstra** [comment] 2017-07-01 19:31
This is a duplicate of #465.

**Comment by ilevkivskyi** [comment] 2017-07-01 22:04
Yes, it looks like this is a duplicate. I think it makes sense to only keep one of them open.

**Closed by ilevkivskyi** 2017-07-01 22:04 UTC
