### ISSUE TITLE
python version checks don't seem to work with 0.780

### ISSUE THREAD

**Issue by samuelcolvin** [python/mypy#8990] opened 2020-06-11 12:57 UTC
Upgrading to mypy 0.780 from 0.770, I can't find a way to get the following lines to pass with both python 3.6 and 3.7.

If I try ignoring different lines with `# type: ignore` I get either errors or `unused 'type: ignore' comment` from one version of python or the other.

```py
if sys.version_info < (3, 7):
    from typing import _ForwardRef as ForwardRef
else:
    from typing import ForwardRef
```

Is this a problem with 0.780 or am I doing something wrong.

**Comment by srittau** [comment] 2020-06-11 13:26
This is a typeshed issue. `ForwardRef` is only defined for Python 3.7+, since it was added then under that name. The previous `_ForwardRef` name is not represented. PR for typeshed welcome that adds it.

**Comment by samuelcolvin** [comment] 2020-06-11 13:30
okay, but is there any way around this using `# type: ignore` for both python 3.6 and 3.7?

I don't understand why the errors are different between python versions.

There seems no way to specify a "type ignore" that only applies to one python version.

Linked PR on pydantic https://github.com/samuelcolvin/pydantic/pull/1598

**Comment by hauntsaninja** [comment] 2020-06-11 19:45
You can use the workaround described in https://github.com/python/mypy/issues/8823 (of which this issue is a dupe, typeshed-specific details aside).

**Comment by hauntsaninja** [comment] 2020-06-11 19:56
Basically a dupe of https://github.com/python/mypy/issues/8823 (typeshed-specific details aside)

You should be able to work around with something like:
```
from typing import Any, TYPE_CHECKING

if TYPE_CHECKING:
    ForwardRef: Any
else:
    from typing import ...
```
which isn't ideal, since mypy will now treat ForwardRef as Any.

**Comment by ilevkivskyi** [comment] 2020-06-12 16:33
It doesn't look like there is a (new) action item for mypy here, so closing.

**Closed by ilevkivskyi** 2020-06-12 16:33 UTC

**Comment by samuelcolvin** [comment] 2020-06-25 17:35
@hauntsaninja thanks for pointing to the other issue. Unfortunately you `ForwardRef = cast(Any, typing)._ForwardRef` solution doesn't work - this is currently preventing pydantic from upgrading latest mypy.
