### ISSUE TITLE
Cannot infer type argument in function chaining

### ISSUE THREAD

**Issue by MartinAltmayer** [python/mypy#6220] opened 2019-01-18 12:58 UTC
Hi,

the example below should pass type checks, but is not accepted by mypy. The example defines a simple generic function that chains two other functions (f1, f2 -> f2 ∘ f1). When I pass a generic function as `f2`, mypy fails with:
```
test.py:25: error: Cannot infer type argument 1 of "chain"
```

This is surprising: Given that the first argument to `chain` does not contain type variables, mypy should be able to figure out that T1=str.

Tested with mypy 0.660

```
from typing import Callable, TypeVar, Any, List

T = TypeVar('T')
T1 = TypeVar('T1')
T2 = TypeVar('T2')


def chain(f1: Callable[[Any],T1], f2: Callable[[T1], T2]) -> Callable[[Any], T2]:
    def chained(x: Any) -> T2:
        return f2(f1(x))

    return chained


# Two toy functions
def identity(x: T) -> T: 
    return x


def to_str(x: Any) -> str:
    return str(x)


# (mypy: "Cannot infer type argument 1 of chain")
chained = chain(to_str, identity)
str_var: str = chained(123)
print(str_var)
```

Motivation: I'm working on a data validation library that should allow mypy to statically infer the resulting types. Often one will chain several validation/conversion functions (e.g. to_str). Some of these functions will just perform some check on the received value and either raise an exception or return the value unchanged (similar to `identity` above). It would be great if mypy could automatically infer the resulting type and also check that the chained functions are compatible.

**Comment by exarkun** [comment] 2022-04-25 23:34
I can confirm this behavior remains in mypy 0.942.  I also came across it with similar code but a slightly different use-case.  I tried to implement a basic function composition function.  The resulting values do not type check:

```
from typing import Callable, TypeVar

A = TypeVar("A")
B = TypeVar("B")
C = TypeVar("C")


def compose(fx: Callable[[B], C], fy: Callable[[A], B]) -> Callable[[A], C]:
    def g(a: A) -> C:
        return fx(fy(a))

    return g


def b_to_c(b: B) -> str:
    return "foo"


def a_to_b(a: int) -> None:
    return None


void: Callable[[int], str] = compose(
    b_to_c,
    a_to_b,
)
```

I would expect `a_to_b` to provide enough information to bind A and B and `b_to_c` to provide enough information to bind C.

**Comment by glyph** [comment] 2024-01-12 19:33
I just upgraded Twisted to 1.8 and it looks like this is at least partially fixed now? I had to remove a type:ignore that referenced this bug, at least :)

**Comment by hauntsaninja** [comment] 2024-01-13 06:33
Thanks, yeah I think this is fixed (probably from `--new-type-inference`)

**Closed by hauntsaninja** 2024-01-13 06:33 UTC
Labels: bug, topic-inference
