### ISSUE TITLE
mypy matching **kwargs positionally instead of by name

### ISSUE THREAD

**Issue by reggied** [python/mypy#7088] opened 2019-06-27 23:27 UTC
I am reporting a bug illustrated by the following code.
```
from typing import Any


def caller() -> None:
    kwargs = dict(a=object(), b=object(), c=object())
    func(1, **kwargs)
    func(**kwargs)

def func(optional:int = 0, **kwargs:Any) -> None:
    pass
```
When I run version **0.670** of `mypy` with Python 3.7.1, I get:

`a.py:7: error: Argument 1 to "func" has incompatible type "**Dict[str, object]"; expected "int"`

It seems to be trying to match the `**kwargs` positionally instead of using the names. I would not expect mypy to produce an error on this code. You can see in line 6 that if I specify the `optional` argument explicitly, there is no error.

This same type of behavior was described in issue #1969, but I'm still getting the behavior with version 0.670, which includes those changes.

**Comment by ilevkivskyi** [comment] 2019-08-12 13:39
Mypy is technically right because it doesn't record which keys are present in a dictionary, it is just `Dict[str, object]`. One could potentially use `TypedDict` to avoid this, but then this is a duplicate of https://github.com/python/mypy/issues/5382.

**Closed by ilevkivskyi** 2019-08-12 13:39 UTC
