### ISSUE TITLE
mypy doesn't understand that Optional is no longer Optional in an 'if' clause

### ISSUE THREAD

**Issue by 1st1** [python/mypy#8000] opened 2019-11-21 23:26 UTC
mypy doesn't understand that Optional is no longer Optional in an 'if' clause:

test.py:

```python
from typing import *


class Item:
    pass


class Foo:
    def __init__(self, ignore: Optional[AbstractSet[Item]] = None) -> None:
        self.ignore = ignore

    def do(self, commands: Sequence[Item]) -> None:
        if self.ignore:
            commands = list(filter(lambda c: c in self.ignore, commands))
```

```
$ mypy --version
mypy 0.740

$ mypy --strict test.py
test.py:14: error: Unsupported right operand type for in ("Optional[AbstractSet[Item]]")
Found 1 error in 1 file (checked 1 source file)
```

**Comment by ethanhs** [comment] 2019-11-22 00:01
Hi Yury! You need to do `if self.ignore is None` for mypy to pick up that you want `self.ignore` to be non-`None`.

There has been previous discussion about allowing `if var` to narrow `var`, but I believe we decided to not go down that route as it could get complicated?

**Comment by msullivan** [comment] 2019-11-22 00:09
We do support narrowing with `if var`. The issue here is that the use is in
a lambda, which could get called after the value is changed.

**Comment by 1st1** [comment] 2019-11-22 00:12
> Hi Yury! You need to do if self.ignore is None

> We do support narrowing with `if var`.

Yeah, changing to `if is not None` doesn't help.

> a lambda, which could get called after the value is changed.

Not sure I follow. `self.ignore` isn't changed anywhere. It's non-None inside the `if` clause and the `filter()` function is called right away.

**Comment by ilevkivskyi** [comment] 2019-11-22 00:19
Duplicate of https://github.com/python/mypy/issues/4973 (which is itself a special case of https://github.com/python/mypy/issues/2608).

**Closed by ilevkivskyi** 2019-11-22 00:19 UTC
Labels: question

**Comment by ethanhs** [comment] 2019-11-22 00:21
>We do support narrowing with `if var`

Oh huh, I must have missed that, apologies!

**Comment by ilevkivskyi** [comment] 2019-11-22 00:23
> Would it be possible to fix this?

Definitelly possible, but it may be non-trivial and I am not sure we will have time for this, but PRs are very welcome.
> Or should our code be rewritten to close over a temp variable?

Yep, a temp variable is a quick and simple workaround.

**Comment by 1st1** [comment] 2019-11-22 00:26
Thank you, guys for a quick turnaround!

**Comment by alan-isaac** [comment] 2023-02-02 19:01
Alternatively, adding an assertion also seems to satisfy mypy. Is that reliable?

I'm finding this problem generally emerges when an instance variable must be initialized to `None` but will never be gotten until after a value is set. What is the preferred way to communicate this to mypy?

**Comment by hauntsaninja** [comment] 2023-02-02 19:08
Yes, an assertion works well. 

For the instance variable thing you can lie to mypy and just give it a non-None type and use type ignore. Then it's on you to make sure your init logic is right. 

Alternatively, you could use a @property that contains an assert and returns a non-Optional type
