### ISSUE TITLE
classmethod and selftype: incompatible with supertype

### ISSUE THREAD

**Issue by thomascellerier** [python/mypy#2511] opened 2016-11-30 10:45 UTC
I am defining some classes capable of returning an (optional) instance of themselves based on a configuration (a dictionary).

In the base class I use the new SelfType capability to define the generic classmethod. I wanted to use a metaclass with abc.abstractclassmethod but mypy doesn't seem to support that.

In the subclass I now use the narrower type for cls and the return value but mypy gives me an error:

```sh
$ ./virtualenv/bin/python3 -m mypy --version
mypy 0.4.6
$ ./virtualenv/bin/python3 -m mypy repro.py 
repro.py: note: In class "B":
repro.py:15: error: Return type of "from_config" incompatible with supertype "A"
```

repro.py:
```Python
from typing import TypeVar, Type, Optional

AT = TypeVar('AT', bound='A')

class A:
    @classmethod 
    def from_config(cls: Type[AT], config: dict) -> Optional[AT]:
        return None

class B(A):
    @classmethod
    def from_config(cls: Type[B], config: dict) -> Optional[B]:
        return B()
```

I could only make it work by defining B like this which looks quite ugly and requires passing around the type variable:
```Python
from typing import cast

class B(A):
    @classmethod
    def from_config(cls: Type[AT], config: dict) -> Optional[AT]:
        return cast(AT, B())
```

Is that the intended result?

**Comment by JukkaL** [comment] 2016-11-30 11:29
This is a known issue with self types: #2353

**Comment by JukkaL** [comment] 2016-11-30 11:29
Closed as duplicate.

**Comment by ilevkivskyi** [comment] 2018-11-07 23:07
I think this is not a duplicate of #2353. In that issue mypy allows unsafe override, while here mypy prohibits a safe override. Also this example is specific to `@classmethod`, with normal self type it works. Then it is probably easier to fix.

**Comment by dsully** [comment] 2019-03-29 03:54
Still seeing this with mypy 0.670

**Comment by JukkaL** [comment] 2019-08-29 12:03
#7401 has a slightly different example (no annotation for `cls` in the method override).

**Comment by ilevkivskyi** [comment] 2019-09-05 14:32
https://github.com/python/mypy/issues/7466 looks like yet another duplicate. Raising priority to high, since this started to come up more often and a fix might be not hard.

**Closed** 2019-09-05 21:18 UTC
Labels: bug, false-positive, priority-0-high
