### ISSUE TITLE
`TypedDict` marked as `@final` not assignable to `Mapping`

### ISSUE THREAD

**Issue by DetachHead** [python/mypy#14441] opened 2023-01-13 03:29 UTC
```py
from typing import Mapping, TypedDict, final

@final
class Foo(TypedDict):
    foo: int
    
foo: Foo

bar: Mapping[str, int] = foo # error: Incompatible types in assignment (expression has type "Foo", variable has type "Mapping[str, int]")  [assignment]
```
[playground](https://mypy-play.net/?mypy=latest&python=3.11&flags=show-error-context%2Cshow-column-numbers%2Cshow-error-codes%2Cstrict%2Ccheck-untyped-defs%2Cdisallow-any-decorated%2Cdisallow-any-expr%2Cdisallow-any-explicit%2Cdisallow-any-generics%2Cdisallow-any-unimported%2Cdisallow-incomplete-defs%2Cdisallow-subclassing-any%2Cdisallow-untyped-calls%2Cdisallow-untyped-decorators%2Cdisallow-untyped-defs%2Cno-implicit-optional%2Cno-implicit-reexport%2Cno-strict-optional%2Cstrict-equality%2Cwarn-incomplete-stub%2Cwarn-redundant-casts%2Cwarn-return-any%2Cwarn-unreachable%2Cwarn-unused-configs%2Cwarn-unused-ignores&gist=cabe2e2a3e9f991a4afbbf6c410b7790)

**Comment by erictraut** [comment] 2023-01-13 03:36
Mypy is correct in generating an error here. A `TypedDict` may have subtypes that include additional keys that are not specified in the parent class, so it's unsafe to assume that `foo` is compatible with `Mapping[str, int]`.

If a `TypedDict` were marked as `@final`, it would be safe to assume that it is compatible with `Mapping[str, <union or join of all value types>]`, but it's rare to see `@final` TypedDicts, and no Python type checkers currently implement this special-case logic. That would be an enhancement request rather than a bug report.

**Comment by DetachHead** [comment] 2023-01-13 03:52
oops i don't know how i missed that

**Comment by AlexWaygood** [comment] 2023-01-13 14:44
Closing, since the basic feature request here is "support `TypedDict`s decorated with `@final`", which is a duplicate of #7981.

**Closed by AlexWaygood** 2023-01-13 14:44 UTC
Labels: feature, topic-typed-dict, topic-final
