### ISSUE TITLE
Should mypy check existence of module attributes for unannotated modules?

### ISSUE THREAD

**Issue by DeinAlptraum** [python/mypy#17701] opened 2024-08-21 20:10 UTC
**Feature**

Report `name-defined` errors for unannotated modules.

**Pitch**

I believe it would be reasonable and very helpful, and I assume possible, to report `name-defined` errors for unannotated modules.

A simple example to motivate this:

```
import sympy
foo: sympy.expr = 3
```
The module `sympy` is not annotated and does not have an attribute `expr` (this is a typo, `sympy.Expr`exists)  which is currently not detected by mypy. I assume missing names should be detectable even without type annotations for the module, so I would like this to produce 
`error: Name "sympy.expr" is not defined  [name-defined]`
when checked with mypy

**Comment by hauntsaninja** [comment] 2024-08-21 22:22
This is a duplicate of https://github.com/python/mypy/issues/8545

**Closed by hauntsaninja** 2024-08-21 22:22 UTC
Labels: feature
