### ISSUE TITLE
Support an `implicit-reexport` that only reexports things in `__init__.py` files

### ISSUE THREAD

**Issue by KotlinIsland** [python/mypy#11527] opened 2021-11-11 23:48 UTC
**Feature**

`implicit_reexport = false` is a based one imo, but it's very idiomatic to reexport everything in `__init__.py` files.

**Pitch**
What about:
`implicit_reexport = "init"`

**Comment by mikeroll** [comment] 2022-04-28 16:14
Looks like a duplicate of https://github.com/python/mypy/issues/10198

**Comment by AlexWaygood** [comment] 2022-04-28 16:44
> Looks like a duplicate of #10198

Yup.

**Closed by AlexWaygood** 2022-04-28 16:44 UTC
Labels: feature, topic-implicit-reexport
