### ISSUE TITLE
add an output format option (e.g. csv and json) to the command line

### ISSUE THREAD

**Issue by PVMPATCH** [python/mypy#13874] opened 2022-10-12 07:15 UTC
**Feature**

I suggest MyPy to add an **output format option** to the command line, 
users can choose to output the detection report in json or csv format. 
I've been doing some empirical research using MyPy recently. 
MyPy is a great tool, but it doesn't facilitate data extraction and statistics. 
I tried to output MyPy's detection report to *.log and then perform text extraction and data sorting through regular expressions, 
but the results were not good.

**Pitch**

The same type of tool gives many useful data output format options, FYI.
[Pyright](https://github.com/microsoft/pyright/blob/main/docs/command-line.md#:~:text=If%20the%20%E2%80%9C%2D%2Doutputjson%E2%80%9D%20option%20is%20specified%20on%20the%20command%20line%2C%20diagnostics%20are%20output%20in%20JSON%20format.%20The%20JSON%20structure%20is%20as%20follows%3A)
`pyright scikit-learn/ --outputjson >pyright_out.json`
[Pyre](https://pyre-check.org/docs/getting-started/)
`pyre --output json >pyre_out.json`

**Comment by erictraut** [comment] 2022-10-12 15:29
I think this is a duplicate of https://github.com/python/mypy/issues/10816.

**Closed as not planned** 2022-10-12 17:17 UTC
Labels: feature

**Comment by PVMPATCH** [comment] 2022-10-13 06:11
Thanks！
