### ISSUE TITLE
Type Narrowing is Incorrect for Attributes

### ISSUE THREAD

**Issue by Derekmod** [python/mypy#14543] opened 2023-01-27 23:03 UTC
**Bug Report**

Type checker breaks by incorrectly narrowing object attributes.

**To Reproduce**

```python
from typing import Optional

class A:
    _cache: Optional[bool] = None
    
    def get_value(self) -> bool:
        if self._cache is not None:
            self.print_value()
            return self._cache
            
        self._cache = True
        return self._cache
        
    def print_value(self) -> None:
        print("invalidating cache muahaha")
        self._cache = None
```

reproduces locally and in the [mypy playground](https://mypy-play.net/?mypy=latest&python=3.11)

**Expected Behavior**

Right after the `print_value()` statement, cannot return `self._cache` because it has type `Optional[bool]` which does not match return type `bool`!

**Actual Behavior**

No errors.

**Your Environment**

reproduces in every version of mypy in the mypy playground.

**Suggested Fix**

EITHER
1. Never type narrow object attributes in strict mode.
2. Try to prove that the attribute never changes. You would have to trace every function call, and every function call in those function calls and see if anything sets the value of the attribute. And even then you would miss things like `setattr(self, "_cache", None)`

I suggest number 1

**Comment by hauntsaninja** [comment] 2023-01-27 23:22
Duplicate of https://github.com/python/mypy/issues/14010 https://github.com/python/mypy/issues/9457

**Closed by hauntsaninja** 2023-01-27 23:22 UTC
Labels: bug
