### ISSUE TITLE
Allow the use of types.ModuleType

### ISSUE THREAD

**Issue by pkch** [python/mypy#3106] opened 2017-04-02 04:01 UTC
Based on this [SO question](http://stackoverflow.com/questions/39827307/mypy-class-module-annotation), I tried this code:

```
import types
def f() -> types.ModuleType:
    return types
```

and it failed type check with ` Incompatible return value type (got "module", expected "ModuleType")`. I think names exported in `types.*` are appropriate for cases like this?

**Comment by ilevkivskyi** [comment] 2017-04-02 07:57
I think this is just a duplicate of https://github.com/python/mypy/issues/1498

**Comment by ilevkivskyi** [comment] 2017-04-02 08:02
I am closing this now, I also updated the description of your PR to mention the existing #1498

**Comment by pkch** [comment] 2017-04-02 08:02
Yup it is... I hope only the issue is a duplicate, not my PR 😆

**Closed by ilevkivskyi** 2017-04-02 08:02 UTC
