### ISSUE TITLE
"error: Invalid type" when inheriting from a generic class with not all type variables fixed

### ISSUE THREAD

**Issue by jstasiak** [python/mypy#1936] opened 2016-07-25 11:27 UTC
Code taken straight from typing documentation (https://docs.python.org/3/library/typing.html#typing.Generic):

```python
from typing import TypeVar, Mapping

T = TypeVar('T')

class MyDict(Mapping[str, T]):
    pass
```

Outcome (with both latest mypy from PyPI and development version):

```
% python -m mypy qwe.py
qwe.py:5: error: Invalid type "qwe.T"
```

**Comment by rwbarton** [comment] 2016-07-25 13:23
IMO, the example is wrong, and should be `class MyDict(Mapping[str, T], Generic[T]): ...`.

**Comment by JukkaL** [comment] 2016-07-25 13:36
In many cases `Generic` should be optional: https://www.python.org/dev/peps/pep-0484/#arbitrary-generic-types-as-base-classes

Closing as a duplicate of #302.

**Closed by JukkaL** 2016-07-25 13:36 UTC
