### ISSUE TITLE
mypy infers nonexistent class attribute from instance attribute

### ISSUE THREAD

**Issue by untitaker** [python/mypy#7524] opened 2019-09-17 21:01 UTC
The following typechecks correctly with mypy 0.720, but blows up at runtime:

```python
from typing import Type

class A(object):
    both = 42  # type: int

    def __init__(self):
        # type: () -> None
        self.instance_only = 42  # type: int


a = A()  # type: A
b = A  # type: Type[A]

print(a.both)
print(b.both)

print(a.instance_only)
print(b.instance_only)  # AttributeError
```

**Comment by JukkaL** [comment] 2019-09-20 18:57
Closing as duplicate of #1097.

**Closed by JukkaL** 2019-09-20 18:57 UTC
