### ISSUE TITLE
Host mypy-lang.org over HTTPS

### ISSUE THREAD

**Issue by johnthagen** [python/mypy#10638] opened 2021-06-13 11:59 UTC
**Documentation**

It's currently considered best practice to host all content over HTTPS wherever possible. Currently it is not possible to browse https://mypy-lang.org to securely view the Mypy website. 

Could HTTPS support be added to the website?

**Comment by ethanhs** [comment] 2021-06-13 19:24
Duplicate of https://github.com/JukkaL/mypy-website/issues/12

**Closed by ethanhs** 2021-06-13 19:24 UTC
Labels: documentation
