### ISSUE TITLE
Can't use TypedDict as generic

### ISSUE THREAD

**Issue by sallyruthstruik** [python/mypy#8326] opened 2020-01-24 09:43 UTC
Please provide more information to help us understand the issue:

* **Are you reporting a bug, or opening a feature request?**
  
  I suppose it to be a bug

* **Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.**

	```python
	import typing as t 
	from mypy_extensions import TypedDict

	T = t.TypeVar("T")

	def cast_to_typedict(o: t.Dict, tp: t.Type[T]) -> T: pass

	MyDict = TypedDict("MyDict", {"key": str})

	val: MyDict = cast_to_typedict({}, MyDict)
	```

* **What is the actual behavior/output?**
	
	I got an error:
	```
	11: error: Incompatible types in assignment (expression has type "MyDict", variable has type "MyDict")
	```

* **What is the behavior/output you expect?**

	No error

* **What are the versions of mypy and Python you are using?
  Do you see the same issue after installing mypy from Git master?**

	```
	Python 3.6.8

	mypy 0.761
	```
	The same when installed mypy from git master (`mypy 0.770+dev.d56d90087ea98fed32b908f466f950d3fad952af`)

* **What are the mypy flags you are using? (For example --strict-optional)**

	No special flags

**Comment by ethanhs** [comment] 2020-01-24 10:56
Duplicate of #7255

**Closed by ethanhs** 2020-01-24 10:56 UTC
