### ISSUE TITLE
Problem in tracking variable definition in condition

### ISSUE THREAD

**Issue by h8hawk** [python/mypy#8132] opened 2019-12-11 11:31 UTC
mypy validate this code without any issue :

```
def foo(b: bool) -> int:
    if b: 
        a = 9
    return a
```

**Comment by msullivan** [comment] 2019-12-12 00:39
mypy doesn't really track variable definedness, which is a known bug. I am certain that this must be filed already but I can't find it so I guess I'll triage this one for now!

**Comment by hauntsaninja** [comment] 2021-08-05 01:52
Duplicate of #2400

**Closed by hauntsaninja** 2021-08-05 01:52 UTC
Labels: bug, priority-1-normal
