### ISSUE TITLE
Unhelpful error "Invalid base class mypy(error)"

### ISSUE THREAD

**Issue by vivaldus** [python/mypy#6372] opened 2019-02-11 04:00 UTC
The following sql-entity class was generated by sqlalchemy -- so this is the standard way to create such a class and operate it. However, `mypy` calls Base here an `Invalid base class`. But why? No further details are given, I see no such error described in mypy documentation, and googling "Invalid base class" doesn't lead me to any obvious results. I have no way to diagnose the problem. 

```python
from sqlalchemy.ext.declarative import declarative_base
Base = declarative_base()

class SomeClass(Base)
    ....
```

mypy version 0.660
python version 3.7.2

**Comment by ethanhs** [comment] 2019-02-11 06:08
In this case it is because the Base class is dynamic, therefore mypy cannot use it for static analysis.

Also this is a duplicate of https://github.com/python/mypy/issues/2477 (the issue is tracking a better error message and add support for dynamic base classes https://github.com/python/mypy/issues/2477#issuecomment-272854531).

**Closed by ethanhs** 2019-02-11 06:08 UTC

**Comment by ilevkivskyi** [comment] 2019-02-11 08:53
@vivaldus As I mentioned in my closing notice for #2477 you should use [SQLAlchemy plugin](https://github.com/dropbox/sqlalchemy-stubs/). The error message is now tracked in https://github.com/python/mypy/issues/4030.
