### ISSUE TITLE
Dunder methods should allow overriding to None

### ISSUE THREAD

**Issue by JelleZijlstra** [python/mypy#5217] opened 2018-06-14 14:26 UTC
This should be legal:
```python
class A:
    def __hash__(self) -> int: ...
class B(A):
    __hash__ = None
```
See here for more python/typeshed#2148.

**Comment by ethanhs** [comment] 2018-06-14 21:35
Isn't this essentially a duplicate of #4266?

**Comment by ilevkivskyi** [comment] 2018-06-15 01:30
Yes, I think this is a duplicate.

**Closed by ilevkivskyi** 2018-06-15 01:30 UTC
