### ISSUE TITLE
Using generic self in a generic class

### ISSUE THREAD

**Issue by cyang1** [python/mypy#3363] opened 2017-05-15 18:53 UTC
The recommended method for writing a factory method is to type the `cls` argument as `Type[T]` (http://mypy.readthedocs.io/en/latest/generics.html#generic-methods-and-generic-self). However, this doesn't seem to be able to handle the case where the factory class itself is generic.

In the example below, if we just specify `bound=FactoryBase` on the `_FactoryBase` typevar, mypy gives `error: Argument 1 to "make" of "FactoryBase" has incompatible type "int"; expected "T"`.
```python
from typing import (
    Any,
    Generic,
    TypeVar,
    Type,
)

T = TypeVar('T')
_FactoryBase = TypeVar('_FactoryBase', ???)

class FactoryBase(Generic[T]):
    def __init__(self, obj):
        # type: (T) -> None
        pass

    @classmethod
    def make(cls, obj):
        # type: (Type[_FactoryBase], T) -> _FactoryBase
        return cls(obj)

class Factory(FactoryBase[int]):
    pass

Factory.make(2)
```

**Comment by ilevkivskyi** [comment] 2017-05-16 08:41
It looks like this is a duplicate of #2354 (although I am not 100% sure).

**Comment by ilevkivskyi** [comment] 2017-05-16 08:43
Maybe it makes to copy this example (i.e. with ``@classmethod``) to the original issue an close this one?

**Comment by ilevkivskyi** [comment] 2019-06-11 11:13
FWIW the original example (with `bound=FactoryBase`) works correctly on master.

**Closed by ilevkivskyi** 2019-06-11 11:13 UTC
