### ISSUE TITLE
Using getattr() does not prevent attr-defined error

### ISSUE THREAD

**Issue by jolaf** [python/mypy#11348] opened 2021-10-17 16:41 UTC
The following code:
```python3
class A:
    pass

a = A()

if hasattr(a, 'v'):
    print(a.v)

print("OK")
```
produces the following ouput:
```bash
$ python3 test.py
OK

$ mypy test.py
test.py:7:11: error: "A" has no attribute "v"  [attr-defined]
        print(a.v)
              ^
Found 1 error in 1 file (checked 1 source file)

$ mypy --version
mypy 0.910

$ python3 --version
Python 3.8.10

$ cat /etc/issue
Ubuntu 20.04.3 LTS \n \l

$ uname -a
Linux ubuntu 5.4.0-88-generic #99-Ubuntu SMP Thu Sep 23 17:29:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by ethanhs** [comment] 2021-10-17 17:34
Duplicate of https://github.com/python/mypy/issues/1424

**Closed by ethanhs** 2021-10-17 17:34 UTC
Labels: bug
