### ISSUE TITLE
Type annotation of the property setter is ignored

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/mypy#9774] opened 2020-12-02 10:27 UTC
It seems that the type annotation of the property setter is ignored. For example:
```python
from typing import Union

class A:
    def __init__(self) -> None:
        self._x: int = 0
    @property
    def x(self) -> int:
        return self._x
    @x.setter
    def x(self, value: Union[int, str]) -> None:
        self._x = int(value)

a = A()
a.x = '42'
```
```
$ mypy property.py 
property.py:14: error: Incompatible types in assignment (expression has type "str", variable has type "int")
```
The getter returns `int`, and the setter accepts both `int` and `str`. But MyPy ignores it and expect that setter accepts the same type as returned by getter.

**Comment by hauntsaninja** [comment] 2020-12-02 19:34
Thanks, duplicate of #3004

**Closed by hauntsaninja** 2020-12-02 19:34 UTC
Labels: bug
