### ISSUE TITLE
Strictly match all the possibilities in if-else blocks

### ISSUE THREAD

**Issue by sayanarijit** [python/mypy#9748] opened 2020-11-23 05:38 UTC
**Feature**

Inspired by the `match` statement in modern languages like Rust, Elm, Haskell etc., I would like the if-else blocks in Python to be stricter and make us match all the possibilities either explicitly or by enforcing the else block or by enforcing the usage of `>` / `<` to cover all the possibilities.

**Pitch**

I have attempted to gain this strictness to some degree (only for enums) by [creating this library](https://github.com/sayanarijit/enumatch). However, hacks like these aren't static and requires us to run the program to identify the missing possibilities.

Here's my proposal:

* For values with finite possibilities (e.g. `bool`, `Enum` etc.), the `else` block isn't required, but it can be used as a wildcard matcher.

e.g.

```python
class Color(Enum):
    red: auto()
    green: auto()
    blue: auto()

color = Color.red

# Valid
if color == Color.red:
    ...
elif color == Color.green:
    ...
elif color == Color.blue:
    ...

# Also valid
if color == Color.red or color == Color.green:
    ...
elif color == Color.blue:
    ...

# Also valid
if color in [Color.red, Color.green]:
    ...
elif color == Color.blue:
    ...

# Also valid
if color == Color.red:
    ...
else:
    ...

# Invalid (missing possibility: Color.blue)
if color == Color.red:
    ...
elif color == Color.green:
    ...
```

* For values with infinite possibilities (e.g. `str`, `int` etc.), must either use the else block or use `>` / `<` to cover all the possibilities.

e.g.

```python
x = 10

# Valid
if x == 10:
    ...
else:
    ...

# Also valid
if x == 10:
    ...
elif x < 10:
    ...
elif x > 10:
    ...

# Also valid
if x in range(10, 20):
    ...
elif x < 10:
    ...
elif x >= 20:
    ...

# Invalid (Missing possibilities where x != 10 and x != 11)
if x == 10:
   ...
elif x == 11:
   ...
```

There will be more edge-cases that we'll need to cover, however, I think for this feature, having something is better than nothing. So this is my general proposal as the starting point.

**Comment by hauntsaninja** [comment] 2020-11-23 06:09
I'm closing this as a duplicate of https://github.com/python/mypy/issues/5818 and https://github.com/python/mypy/issues/6366
It should be possible to get the `assert_never` trick described in those issues to make your enum examples work. mypy's not going to change to enforce that all if statements are exhaustive by default, since there are many good reasons to have non-exhaustive if statements. The range / dependent type stuff you propose isn't covered by those issues, but it would probably be a lot of work to design and implement.
Finally, Python might soon have a match statement (see PEP 636, 634, 635)

**Closed by hauntsaninja** 2020-11-23 06:09 UTC
Labels: feature
