### ISSUE TITLE
mypy does not recognize `+1` as valid for `Literal[-1, 1]`

### ISSUE THREAD

**Issue by bersbersbers** [python/mypy#15829] opened 2023-08-08 07:11 UTC
**Bug Report**

(A clear and concise description of what the bug is.)

**To Reproduce**

```python
from typing import Literal

def fun(value: Literal[-1, 1]) -> None:
    assert value in [-1, 1]

fun(-1)
fun(1)
fun(+1)
```
https://mypy-play.net/?mypy=latest&python=3.11&gist=920815d6afe92346e83262ef07c1c133

**Expected Behavior**

No error

**Actual Behavior**

main.py:8: error: Argument 1 to "fun" has incompatible type "int"; expected "Literal[-1, 1]"  [arg-type]
Found 1 error in 1 file (checked 1 source file)

**Your Environment**

- Mypy version used: 1.4.1
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files):
- Python version used: 3.11.4

**Comment by JBHutson** [comment] 2023-08-08 20:55
I'll give this one a go!

**Comment by hauntsaninja** [comment] 2023-08-09 03:49
This is basically a duplicate of https://github.com/python/mypy/issues/11990

**Closed by hauntsaninja** 2023-08-09 03:49 UTC
Labels: bug

**Comment by ikonst** [comment] 2023-08-09 13:39
@hauntsaninja if you wish to see it this way, but I think this request is far more conservative (we already call out in the docs that we don't support literal math and yet I wouldn't rule out this working)
