### ISSUE TITLE
dataclasses with callbacks mistakenly report wrong number of arguments

### ISSUE THREAD

**Issue by hackaugusto** [python/mypy#10131] opened 2021-02-24 08:34 UTC
**Bug Report**

`mypy` mistakenly reports `Too many arguments` for callables inside a dataclass

**To Reproduce**

minimally reproducible example:

```python
from dataclasses import dataclass
from typing import Callable, Generic, TypeVar

T = TypeVar('T')

@dataclass
class A(Generic[T]):
    callback: Callable[[T, T], bool]

@dataclass
class B:
    callback: Callable[[int, int], bool]

def gt(left: int, right: int) -> bool:
    return left > right

a = A(callback=gt)
a.callback(1, 2)

b = B(callback=gt)
b.callback(1, 2)
```

**Expected Behavior**

I expected it to type check just like this example:

```python
from typing import Callable

def gt(left: int, right: int) -> bool:
    return left > right

callback: Callable[[int, int], bool] = gt
callback(1, 2)
```

**Actual Behavior**

Type checking failed.

**Your Environment**

Tested with:

- mypy-0.800
- mypy-0.812
- mypy 0.820+dev.4827f3adf0acebd2dea7cc0dbf358b8daede6694
- Python 3.8.7
- Fedora 33

**Comment by matteosantama** [comment] 2021-03-01 14:44
Here's another example that demonstrates mypy does not allow you pass around functions as attributes. 

```python
from dataclasses import dataclass                                               
from typing import Callable                                                     
                                                                                
def add(a: int, b: int) -> int:                                                 
    return a + b                                                                
                                                                                
@dataclass                                                                      
class Foo:                                                                      
    attrib_add: Callable[[int, int], int] = add                                 
                                                                                
def invoke(f: Callable[[int, int], int], a: int, b: int) -> int:                
    return f(a, b)                                                              
                                                                                
foo = Foo()                                                                     

# output = 5                                                                       
invoke(foo.attrib_add, 2, 3)                  
````

```
m.py:16:8: error: Invalid self argument "Foo" to attribute function "attrib_add" with type
"Callable[[int, int], int]"  [misc]
    invoke(foo.attrib_add, 2, 3)
           ^
m.py:16:8: error: Argument 1 to "invoke" has incompatible type "Callable[[int], int]"; expected
"Callable[[int, int], int]"  [arg-type]
    invoke(foo.attrib_add, 2, 3)
```

mypy is unable to distinguish that `foo.attrib_add` is not a method, so it inserts `self` into the arguments, overwriting the first `int` argument`.

**Comment by NeilGirdhar** [comment] 2021-04-28 13:44
Duplicate of https://github.com/python/mypy/issues/9975

**Comment by JelleZijlstra** [comment] 2021-04-28 14:00
Yes

**Closed by JelleZijlstra** 2021-04-28 14:00 UTC
Labels: bug
