### ISSUE TITLE
Direct assignment from lambda doesn't narrow type correctly

### ISSUE THREAD

**Issue by jacksonriley** [python/mypy#11029] opened 2021-08-26 17:37 UTC
(Might be a duplicate of #10993)

**Bug Report**

Assigning a lambda function to a variable typed as e.g. `Callable[[], int]` doesn't always work if the lambda returns a variable whose type has been previously narrowed to e.g. `int`. This behaviour does not remain if the lambda returns a literal e.g. `int`, or if an intermediate variable is introduced.
**To Reproduce**

```python
from collections.abc import Callable
from typing import Union

def foo(bar: Union[int, Callable[[], int]]) -> int:
    int_fn: Callable[[], int]
    if callable(bar):
        int_fn = bar
    else:
        reveal_type(bar)
        int_fn = lambda: bar
    return int_fn()
```

**Expected Behavior**

There should be no mypy errors.

**Actual Behavior**

There were mypy errors (I've left the `reveal_type` in for illustration):
```
test.py:9: note: Revealed type is "builtins.int"
test.py:10: error: Incompatible types in assignment (expression has type "Callable[[], Union[int, Callable[[], int]]]", variable has type "Callable[[], int]")
test.py:10: error: Incompatible return value type (got "Union[int, Callable[[], int]]", expected "int")
```

These errors do not remain if line 10 is replaced with e.g. `int_fn = lambda: 1`.
In addition, these errors do not remain if line 10 is replaced with an intermediate assignment, e.g.:
```python
    intermediate = lambda: bar
    int_fn = intermediate
```

**Your Environment**

- Python 3.9.4
- mypy 0.910
- Mypy command-line flags: None
- Mypy configuration options from mypy.ini (and other config files): None
- Operating system and version: Linux, RHEL 7.8

**Comment by hauntsaninja** [comment] 2021-09-26 21:16
The original (not actually a bug) issue is a duplicate of #2608. The actually a bug issue is a duplicate of #10993

**Closed by hauntsaninja** 2021-09-26 21:16 UTC
Labels: bug
