### ISSUE TITLE
Builtin sequence types don't work as constructors with map

### ISSUE THREAD

**Issue by Dentosal** [python/mypy#4584] opened 2018-02-17 13:43 UTC
This is a bug report.

**Minimal reproducible example**

```python
map(list, [[1]])
```

*Expected behavior*

No error message, returns `[[1]]`

*Actual behavior*

```
error: Argument 1 to "map" has incompatible type "Type[List[Any]]"; expected "Callable[[List[int]], List[_T]]"
```

**Versions**

```
$ python --version
Python 3.6.2
$ python -m mypy --version
mypy 0.570-dev-c25dd085a78047a9d5e0909261e8261506505d35
```

(Also tested with mypy 0.560)

**Comment by WillAyd** [comment] 2019-10-16 18:51
Probably related to #6697

**Comment by ilevkivskyi** [comment] 2019-10-17 15:16
Yes, this is essentially a duplicate of #6697

Also, both issues are essentially caused by https://github.com/python/mypy/issues/1317

**Closed by ilevkivskyi** 2019-10-17 15:16 UTC
Labels: bug, false-positive, priority-1-normal
