### ISSUE TITLE
Incorrect line number reported for non-existent variable with property inside literal format string.

### ISSUE THREAD

**Issue by joshstaiger** [python/mypy#5133] opened 2018-06-01 19:36 UTC
Run mypy (0.600) on the following code:

```
#1
#2
#3
#4
#5
f"{a.b}"
```

This returns the error:

`format_string_literal.py:1: error: Name 'a' is not defined`

Note the line number is `1`, not `6`, as it should be.

This only occurs if we are trying to reference a property on `a`.  

The line number is correct for this:

```
#1
#2
#3
#4
#5
f"{a}"
```

`format_string_literal.py:6: error: Name 'a' is not defined`

**Comment by ethanhs** [comment] 2018-06-01 19:44
This is a duplicate of #3562. This will be fixed once typed_ast is updated to be based on 3.7, which has the line number/column fix for fstrings.

**Closed by ethanhs** 2018-06-01 19:44 UTC
