### ISSUE TITLE
missing return statement should not span the entire function

### ISSUE THREAD

**Issue by Hnasar** [python/mypy#17168] opened 2024-04-24 20:06 UTC
**Bug Report**

When using the mypy vscode integration, which underlines the error range in red, if a function is missing a return statement, then the entire function gets underlined, which makes things very hard to read:

```console
$ mypy --show-error-end --strict foo.py  
foo.py:1:1:6:8: error: Missing return statement  [return]
```

<img width="377" alt="Screenshot 2024-04-24 at 3 58 55 PM" src="https://github.com/python/mypy/assets/463274/3b0c3fba-fa3c-45a6-a70f-0147a95e966b">

Compare with pylance which only show an error span with the return annotation
<img width="679" alt="Screenshot 2024-04-24 at 3 57 28 PM" src="https://github.com/python/mypy/assets/463274/ba5a2e0b-ec81-42a6-80aa-b7e9a6ffaa2d">

**To Reproduce**

```python
def foo() -> int:

    x = 1+1
    for unrelated in []:
        pass
    pass
```

**Expected Behavior**

Unrelated lines are not included in the error range. Probably only the function signature should be in the error range.

**Actual Behavior**

See pictures above

**Your Environment**

- Mypy version used: mypy 1.10.0
- Mypy command-line flags: mypy --show-error-end --strict foo.py
- Python version used: 3.11

**Comment by hauntsaninja** [comment] 2024-04-25 05:44
Duplicate of https://github.com/python/mypy/issues/16746

**Closed by hauntsaninja** 2024-04-25 05:44 UTC
Labels: bug
