### ISSUE TITLE
Internal error with SQLAlchemy

### ISSUE THREAD

**Issue by kengruven** [python/mypy#1544] opened 2016-05-17 20:44 UTC
On OS X 10.11.4, with Python 3.5.1, and mypy 0.4.1, I ran:

```
MYPYPATH=/usr/local/lib/python3.5/site-packages/ mypy my_program/foo.py
```

After about 70 seconds (this program isn't _that_ big), it printed this:

```
Traceback (most recent call last):
  File "/usr/local/bin/mypy", line 6, in <module>
    main(__file__)
  File "/usr/local/lib/python3.5/site-packages/mypy/main.py", line 54, in main
    res = type_check_only(sources, bin_dir, options)
  File "/usr/local/lib/python3.5/site-packages/mypy/main.py", line 102, in type_check_only
    python_path=options.python_path)
  File "/usr/local/lib/python3.5/site-packages/mypy/build.py", line 209, in build
    dispatch(sources, manager)
  File "/usr/local/lib/python3.5/site-packages/mypy/build.py", line 1255, in dispatch
    process_graph(graph, manager)
  File "/usr/local/lib/python3.5/site-packages/mypy/build.py", line 1386, in process_graph
    process_stale_scc(graph, scc)
  File "/usr/local/lib/python3.5/site-packages/mypy/build.py", line 1412, in process_stale_scc
    graph[id].semantic_analysis()
  File "/usr/local/lib/python3.5/site-packages/mypy/build.py", line 1222, in semantic_analysis
    self.manager.semantic_analyzer.visit_file(self.tree, self.xpath)
  File "/usr/local/lib/python3.5/site-packages/mypy/semanal.py", line 241, in visit_file
    self.accept(d)
  File "/usr/local/lib/python3.5/site-packages/mypy/semanal.py", line 2233, in accept
    node.accept(self)
  File "/usr/local/lib/python3.5/site-packages/mypy/nodes.py", line 650, in accept
    return visitor.visit_class_def(self)
  File "/usr/local/lib/python3.5/site-packages/mypy/semanal.py", line 557, in visit_class_def
    defn.defs.accept(self)
  File "/usr/local/lib/python3.5/site-packages/mypy/nodes.py", line 715, in accept
    return visitor.visit_block(self)
  File "/usr/local/lib/python3.5/site-packages/mypy/semanal.py", line 1003, in visit_block
    self.accept(s)
  File "/usr/local/lib/python3.5/site-packages/mypy/semanal.py", line 2233, in accept
    node.accept(self)
  File "/usr/local/lib/python3.5/site-packages/mypy/nodes.py", line 753, in accept
    return visitor.visit_assignment_stmt(self)
  File "/usr/local/lib/python3.5/site-packages/mypy/semanal.py", line 1035, in visit_assignment_stmt
    s.rvalue.accept(self)
  File "/usr/local/lib/python3.5/site-packages/mypy/nodes.py", line 1089, in accept
    return visitor.visit_name_expr(self)
  File "/usr/local/lib/python3.5/site-packages/mypy/semanal.py", line 1729, in visit_name_expr
    n = self.lookup(expr.name, expr)
  File "/usr/local/lib/python3.5/site-packages/mypy/semanal.py", line 2032, in lookup
    return self.type[name]
  File "/usr/local/lib/python3.5/site-packages/mypy/nodes.py", line 1793, in __getitem__
    raise KeyError(name)
KeyError: 'Comparator'

*** INTERNAL ERROR ***

/usr/local/lib/python3.5/site-packages/sqlalchemy/sql/type_api.py:559: error: Internal error -- please report a bug at https://github.com/python/mypy/issues
```

This program uses SQLAlchemy, and version 1.0.12 is installed.

**Comment by gvanrossum** [comment] 2016-05-17 22:28
Sounds like you managed to make it analyze the actual sqlalchemy code rather than the stubs. Please don't do that. There's a note specifically in the docs to warn against this:
http://mypy.readthedocs.io/en/latest/basics.html?highlight=MYPYPATH#library-stubs-and-the-typeshed-repo

**Comment by JelleZijlstra** [comment] 2018-05-13 23:17
I can't reproduce this running `mypy` on an installed copy of SQLAlchemy, and the original report doesn't provide the exact code that caused the crash. Let's close this until we have a more concrete code sample that causes a crash.

**Closed by JelleZijlstra** 2018-05-13 23:17 UTC
Labels: bug, crash, priority-2-low
