### ISSUE TITLE
argparse.ArgumentParser.add_argument doesn't allow type=os.path.abspath

### ISSUE THREAD

**Issue by andymwood** [python/mypy#7177] opened 2019-07-09 06:38 UTC
Running mypy on this code:

```python
import argparse,  os
reveal_type(os.path.abspath)
p = argparse.ArgumentParser()
p.add_argument("file", type=os.path.abspath)
```

I get:

```bash
mypy args.py 
args.py:2: note: Revealed type is 'Overload(def [AnyStr in (builtins.str, builtins.bytes)] (path: builtins._PathLike[AnyStr`-1]) -> AnyStr`-1, def [AnyStr in (builtins.str, builtins.bytes)] (path: AnyStr`-1) -> AnyStr`-1)'
args.py:4: error: Argument "type" to "add_argument" of "_ActionsContainer" has incompatible type overloaded function; expected "Union[Callable[[str], AnyStr], FileType]"
```

I originally thought this might be an issue with typeshed and reported it [here](https://github.com/python/typeshed/issues/3107), but it turns out that pytype accepts the code.

**Comment by ilevkivskyi** [comment] 2019-08-12 12:32
It seems to me the mypy problem here is a duplicate of https://github.com/python/mypy/issues/1317.

But there is also a typeshed issue IMO (fixing which will fix this issue), so you might want to open an issue there. The `add_argument` method is needlessly generic, replacing `_T` with `Any` there will not reduce the strictness of the method.

cc @JelleZijlstra

**Closed by ilevkivskyi** 2019-08-12 12:32 UTC

**Comment by andymwood** [comment] 2019-08-12 13:26
> But there is also a typeshed issue IMO (fixing which will fix this issue), so you might want to open an issue there.

I originally reported the issue [here](https://github.com/python/typeshed/issues/3107) but was told it was probably a mypy issue. I'll re-open that issue and let you guys fight it out amongst yourselves.
