### ISSUE TITLE
Commented arguments named `type`

### ISSUE THREAD

**Issue by josephcomisi** [python/mypy#14945] opened 2023-03-23 13:18 UTC
Hello,

I did not dive into the issue but this can still help, so here is what happens:

I use tox to run black, mypy and unittest.

I have dataclasses with several arguments. One of the arguments was commented and was named `type`, such as:
```python
@dataclass
class A:
    first: int
    # type: int

```
Even though it was commented out, I have the following error message:
...: error: expected an indented block after class definition on line 190  [syntax]

I am not sure it is the intended behaviour. If it is, please disregard this issue.

**Comment by hauntsaninja** [comment] 2023-03-25 22:16
Yeah, this is expected behaviour. Closing as a duplicate of #13177

**Closed by hauntsaninja** 2023-03-25 22:16 UTC
Labels: bug
