### ISSUE TITLE
"# type: ignore[no-redef]" causing "Module 'x' has no attribute 'y'" errors.

### ISSUE THREAD

**Issue by jonathanslenders** [python/mypy#8016] opened 2019-11-26 22:13 UTC
This is probably a bug in mypy.

It can be reproduced by creating a directory ``a`` with only two files in there: an ``__init__.py`` and ``b.py``
```
 $ cat a/__init__.py
from .b import X
```
and
```
 $ cat a/b.py
# type: ignore[no-redef]
class X:
    pass
__all__ = ['X']
```

Mypy gives the following output:
```
$ mypy a/
a/__init__.py:1: error: Module 'a.b' has no attribute 'X'
Found 1 error in 1 file (checked 2 source files)
```

Remove the ``type: ignore[no-redef]`` and mypy succeeds.

I would not expect that ignoring something (even leaving ``type: ignore`` in there makes mypy fail), would break the imports.

This is an issue for prompt_toolkit: https://github.com/prompt-toolkit/python-prompt-toolkit/issues/1008

**Comment by ilevkivskyi** [comment] 2019-11-27 15:38
Hm, this is interesting. This is an artefact of how top-level `# type: ignore` is implemented. I assume you are aware that per PEP 484 a `# type: ignore` on line of its own should ignore all errors until the end of file. This is implemented in mypy by marking code after the `# type: ignore` as unreachable.

So this is essentially a duplicate of https://github.com/python/mypy/issues/7839 (there is also a workaround mentioned).

**Closed by ilevkivskyi** 2019-11-27 15:38 UTC

**Comment by jonathanslenders** [comment] 2019-11-27 16:57
Thanks for the quick reply @ilevkivskyi ! I really appreciate it.

So ``# mypy: ignore-errors`` will ignore all typing errors?
Actually, I really want these files to be type checked, except for one single `no-redef` warning.

The code does register key bindings callbacks like this in the snippet below, and I don't like to think of hundreds of different names for functions that are never called by that name.

```python
@handle_key('control-c')
def _():
   ...

@handle_key('control-a')
   ...
```

If I could configure mypy to ignore `no-redef` when functions are named `_`, that would be fine too.

Thanks again. I'll see when a fix arrives. :-)

**Comment by ilevkivskyi** [comment] 2019-11-27 17:06
> Actually, I really want these files to be type checked, except for one single `no-redef` warning.

Yes, support for selectively silencing error codes is planned in near future (see https://github.com/python/mypy/issues/7599)
