### ISSUE TITLE
mypy not inferring that variables cannot be None after if check

### ISSUE THREAD

**Issue by DanBrezeanu** [python/mypy#12957] opened 2022-06-08 12:33 UTC
**Bug Report**

Mypy does not infer that variables cannot be `None` after checking them in an `if` with `or`.

**To Reproduce**

```python
def foo(ab: Union[A, B]):
    pass

a: Optional[A] = None
b: Optional[B] = B()

if a or b:
    foo(a or b)
```

**Expected Behavior**
The expression `a or b` should not be typed as `Union[A, B, None]`, rather as `Union[A, B]` since the `if` check succeeded.

**Actual Behavior**
Actual mypy output:

`error: Argument 1 to "foo" has incompatible type "Union[A, B, None]"; expected "Union[A, B]"`

**Your Environment**

mypy version: `0.910`
python version:  `3.8.10`
OS: `Ubuntu 20.04.2 LTS`

**Comment by AlexWaygood** [comment] 2022-06-08 12:55
Duplicate of #12781. Please see my explanation and provided workarounds in that issue for why mypy can't provide type narrowing here.

**Closed by AlexWaygood** 2022-06-08 12:55 UTC
Labels: bug, topic-type-narrowing
