### ISSUE TITLE
Unreachable (not actually) code allows type errors

### ISSUE THREAD

**Issue by andy-hanson** [python/mypy#6276] opened 2019-01-31 02:35 UTC
Please provide more information to help us understand the issue:

* Are you reporting a bug, or opening a feature request? **Bug**

```py
def f() -> int:
    if False:
        return "".fake_method()

    res = None
    for x in (1, 2, 3):
        if res is not None:
            return ""
        res = x
    return 123


print(f() ** 2)  # Fails at runtime
```

* What is the actual behavior/output?

No errors.

* What is the behavior/output you expect?

At least, an error at `return ""` since this code is reachable (the second time through the loop).
An error in the genuinely unreachable code would be nice too.

* What are the versions of mypy and Python you are using? **mypy 0.670+dev.07440753dd80b6c5144031b4f614f3e7dabe7fcf** (installed from master just now)

* What are the mypy flags you are using? (For example --strict-optional) **None**

**Comment by ilevkivskyi** [comment] 2019-01-31 10:32
Duplicate of https://github.com/python/mypy/issues/5423

**Closed by ilevkivskyi** 2019-01-31 10:32 UTC
