### ISSUE TITLE
Incompatible type with generic dataclasses inheritance

### ISSUE THREAD

**Issue by Eugene-1984** [python/mypy#7715] opened 2019-10-15 09:12 UTC
The following MWE:
```
from typing import Generic, TypeVar
import dataclasses

T = TypeVar('T')

@dataclasses.dataclass()
class A(Generic[T]):
    attr: T

A(attr=0)  # OK!

@dataclasses.dataclass()
class B(A[float]):
    ...

B(attr=float(0))
# Argument "attr" to "B" has incompatible type "float"; expected "T"
```
fails with "Argument "attr" to "B" has incompatible type "float"; expected "T"" error in mypy. But the `B` class specifies `T` to be `float`, how to fix that error?

**Comment by ilevkivskyi** [comment] 2019-10-15 10:32
This is a duplicate of https://github.com/python/mypy/issues/7520

**Closed by ilevkivskyi** 2019-10-15 10:32 UTC
