### ISSUE TITLE
function attributes

### ISSUE THREAD

**Issue by matthiaskramm** [python/mypy#4539] opened 2018-02-03 03:33 UTC
The following code works in Python, but fails in mypy:

```
f = lambda: 1
f.foo = 17
```

This gives:

```
error: "Callable[[], int]" has no attribute "foo"
```

**Comment by matthiaskramm** [comment] 2018-02-03 03:34
mypy version: `mypy 0.570-dev-8ec7046787f92bf7b00d0c70f570fcb5d75e4b53`

**Comment by ilevkivskyi** [comment] 2018-02-03 16:11
I think this is a duplicate of https://github.com/python/mypy/issues/2087

Please re-open if you believe lambdas require special treatment (as compared to named functions).

**Closed by ilevkivskyi** 2018-02-03 16:11 UTC
