### ISSUE TITLE
Return type `AsyncIterable` not correctly deduced for abstract methods

### ISSUE THREAD

**Issue by MaxG87** [python/mypy#17188] opened 2024-04-29 10:13 UTC
**Bug Report**

I am trying to write an abstract class (`Protocol` or `abc.ABC`) with a method that `yield`s values. This concept works well for `def foo(self, args: list[T]) -> Iterable[T]: ...`, but breaks down for `async def foo(self, args: list[T]) -> AsyncIterable[T]: ...`. If `yield` is added to the body of the async method, the return type is correctly deduced.

In order to make the issue self documenting, I add a snippet from the playground example:

```python
import abc
import typing as t


class MyABC(abc.ABC):
    # Putting `yield` instead of `...` in the body would cure the error.
    @abc.abstractmethod
    async def get_strings(self, strings: list[str]) -> t.AsyncIterable[str]: ...


class MyImplementation(MyABC):
    async def get_strings(self, strings: list[str]) -> t.AsyncIterable[str]:
        for string in strings:
            yield string
```

The error is `error: Return type "AsyncIterable[str]" of "get_strings" incompatible with return type "Coroutine[Any, Any, AsyncIterable[str]]" in supertype "MyABC"  [override]`

**To Reproduce**
https://mypy-play.net/?mypy=latest&python=3.12&gist=86f6de6b39e17f87e2c4e46b01aaebc2

**Expected Behavior**

No error, even without `yield`.

**Actual Behavior**

The error is `error: Return type "AsyncIterable[str]" of "get_strings" incompatible with return type "Coroutine[Any, Any, AsyncIterable[str]]" in supertype "MyABC"  [override]`

**Your Environment**
The error is reproduced on mypy 1.10 on the Playground.

**edit:** I found #5385 which describes a very similar problem, maybe the same even. However, I am not too convinced with the proposed solution. I think it should be possible to write a `Protocol` or `abc.ABC` just the way I would write a normal function.

**Comment by MaxG87** [comment] 2024-04-29 13:10
Using the remark in #5385, a "fixed" protocol would look like this:

```python
import abc
import typing as t


class MyABC(abc.ABC):
     @abc.abstractmethod
    def get_strings(self, strings: list[str]) -> t.AsyncIterable[str]: ...


class MyImplementation(MyABC):
    async def get_strings(self, strings: list[str]) -> t.AsyncIterable[str]:
        for string in strings:
            yield string
```
([playground](https://mypy-play.net/?mypy=latest&python=3.12&gist=2bff79eca2fc786e2d1fc35851c66c22))

I still find this unfortunate, though. However, maybe this is a rough edge that has to be accepted.

**Comment by JelleZijlstra** [comment] 2024-04-29 13:20
As you say, a duplicate of #5385.

**Closed by JelleZijlstra** 2024-04-29 13:20 UTC
Labels: bug
