### ISSUE TITLE
Not None checks ignored when passing to a lambda

### ISSUE THREAD

**Issue by ltworf** [python/mypy#9076] opened 2020-07-01 08:49 UTC
```python3

from typing import *

def f(p: Optional[str]) -> Callable[[str], bool]:
    assert p
    if p is None:
        raise Exception('asd')
    return lambda a: p.startswith(a)
```

This doesn't pass, despite the 2 checks to make sure that `p` is indeed a string.

**Comment by ltworf** [comment] 2020-07-01 09:05
It seems to work if instead of the lamda I use functools.partial

**Comment by kaste** [comment] 2020-07-01 11:08
This is a dupe of https://github.com/python/mypy/issues/4297

**Comment by JelleZijlstra** [comment] 2020-07-01 15:26
Closing as a duplicate.

**Closed by JelleZijlstra** 2020-07-01 15:26 UTC
