### ISSUE TITLE
module and types.ModuleType aren't compatible

### ISSUE THREAD

**Issue by JelleZijlstra** [python/mypy#2916] opened 2017-02-27 15:55 UTC
```
$ cat module.py 
from types import ModuleType
import os

def takes_module(mod: ModuleType) -> None:
    pass
takes_module(os)
$ python3.6 -m mypy module.py 
module.py:6: error: Argument 1 to "takes_module" has incompatible type "module"; expected "ModuleType"
```

mypy may need to learn that `types.ModuleType` is the same as `module`. This came up in https://github.com/python/mypy/pull/2910.

**Comment by ilevkivskyi** [comment] 2017-02-27 16:01
I think it might be a duplicate of https://github.com/python/mypy/issues/1498

**Comment by JukkaL** [comment] 2017-02-27 16:03
Yes, this is a duplicate.

**Closed** 2017-02-27 16:04 UTC
