### ISSUE TITLE
Paramspec, protocol and classmethod

### ISSUE THREAD

**Issue by mehdigmira** [python/mypy#13911] opened 2022-10-16 14:33 UTC
**Bug Report**

Mypy doesn't infer the right type in the following example.

**To Reproduce**

https://gist.github.com/94a0c6c7b64ea26e03b9a44ae460c6cb

**Expected Behavior**

mypy infers `Type of "Add.async_func()" is "(x: int, y: int) -> int"` as pyright does

**Actual Behavior**
 
mypy infers `Revealed type is "def (*<nothing>, **<nothing>) -> builtins.int"`

**Your Environment**

- Mypy version used: 0.981
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: 3.10.7

**Comment by AlexWaygood** [comment] 2023-03-03 14:28
So that others don't have to click through, here's the snippet:

```python
from typing import TypeVar, Protocol, Type, Callable
from typing_extensions import ParamSpec

ReturnT = TypeVar("ReturnT", covariant=True)
P = ParamSpec("P")

class AsyncP(Protocol[P]):

    def __init__(self, *args: P.args, **kwargs: P.kwargs) -> None:
        ...

    
class Async:

    @classmethod
    def async_func(cls: Type[AsyncP[P]]) -> Callable[P, int]:
        ...


class Add(Async):

    def __init__(self, x: int, y: int) -> None:
        self.x = x
        self.y = y

        
reveal_type(Add.async_func())
```

And here's a link to mypy playground: https://mypy-play.net/?mypy=latest&python=3.11&gist=34604ea95d10df9b6bcf2de46e8383a2

**Comment by ilevkivskyi** [comment] 2023-08-18 11:52
Note that part of the problem is that you are using `__init__` in protocol, which is very special, see https://github.com/python/mypy/issues/15844. The other part of the problem will be fixed by https://github.com/python/mypy/pull/15903

**Closed** 2023-08-19 13:49 UTC
Labels: bug, topic-paramspec

**Comment by hauntsaninja** [comment] 2023-08-19 21:46
@mehdigmira is the project you were running into this on open source?

**Comment by mehdigmira** [comment] 2023-08-24 07:45
No the project is not open source
