### ISSUE TITLE
mypy crash in tuple unpack

### ISSUE THREAD

**Issue by Hanaasagi** [python/mypy#6612] opened 2019-04-03 03:52 UTC
### Env

- Python 3.7.2
- mypy 0.670

### Test Code

Following code will be ok

```Python
typ = (int, float)
assert (str, *typ) == (str, int, float)
```

But 

```Python
typ = (int, float)
assert isinstance(0, (str, *typ))
```

will crash.

### Except Behavior

mypy do not crash.

### Actual Behavior

mypy crashes.

### Trackback

```
t.py:2: error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues version: 0.670
Traceback (most recent call last):
  File "/root/py37/bin/mypy", line 10, in <module>
    sys.exit(console_entry())
  File "/root/py37/lib/python3.7/site-packages/mypy/__main__.py", line 7, in console_entry
    main(None)
  File "/root/py37/lib/python3.7/site-packages/mypy/main.py", line 91, in main
    res = build.build(sources, options, None, flush_errors, fscache)
  File "/root/py37/lib/python3.7/site-packages/mypy/build.py", line 162, in build
    result = _build(sources, options, alt_lib_path, flush_errors, fscache)
  File "/root/py37/lib/python3.7/site-packages/mypy/build.py", line 217, in _build
    graph = dispatch(sources, manager)
  File "/root/py37/lib/python3.7/site-packages/mypy/build.py", line 2360, in dispatch
    process_graph(graph, manager)
  File "/root/py37/lib/python3.7/site-packages/mypy/build.py", line 2660, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/root/py37/lib/python3.7/site-packages/mypy/build.py", line 2767, in process_stale_scc
    graph[id].type_check_first_pass()
  File "/root/py37/lib/python3.7/site-packages/mypy/build.py", line 1919, in type_check_first_pass
    self.type_checker().check_first_pass()
  File "/root/py37/lib/python3.7/site-packages/mypy/checker.py", line 282, in check_first_pass
    self.accept(d)
  File "/root/py37/lib/python3.7/site-packages/mypy/checker.py", line 393, in accept
    stmt.accept(self)
  File "/root/py37/lib/python3.7/site-packages/mypy/nodes.py", line 1060, in accept
    return visitor.visit_assert_stmt(self)
  File "/root/py37/lib/python3.7/site-packages/mypy/checker.py", line 2775, in visit_assert_stmt
    self.expr_checker.accept(s.expr)
  File "/root/py37/lib/python3.7/site-packages/mypy/checkexpr.py", line 3188, in accept
    typ = node.accept(self)
  File "/root/py37/lib/python3.7/site-packages/mypy/nodes.py", line 1446, in accept
    return visitor.visit_call_expr(self)
  File "/root/py37/lib/python3.7/site-packages/mypy/checkexpr.py", line 244, in visit_call_expr
    return self.visit_call_expr_inner(e, allow_none_return=allow_none_return)
  File "/root/py37/lib/python3.7/site-packages/mypy/checkexpr.py", line 317, in visit_call_expr_inner
    self.check_runtime_protocol_test(e)
  File "/root/py37/lib/python3.7/site-packages/mypy/checkexpr.py", line 394, in check_runtime_protocol_test
    tp = self.chk.type_map[expr]
KeyError: <mypy.nodes.StarExpr object at 0x7fb149630708>
t.py:2: : note: use --pdb to drop into pdb
```

**Comment by ilevkivskyi** [comment] 2019-04-03 14:27
This is a duplicate of https://github.com/python/mypy/issues/4986 (will raise priority to high).

**Closed by ilevkivskyi** 2019-04-03 14:27 UTC
