### ISSUE TITLE
Type-narrowing union of 3 types using generic func leads to `object` type

### ISSUE THREAD

**Issue by Garrett-R** [python/mypy#17500] opened 2024-07-07 02:25 UTC
**Bug Report**

Using a generic that acts as a custom type guard isn't narrowing unions down strangely.

**To Reproduce**

See [this Mypy playground](https://mypy-play.net/?mypy=latest&python=3.12&gist=27924d6ac1425facbdee1cca341d0abb), which contains:

```python
from typing import TypeVar


T = TypeVar('T')


def not_none(obj: T | None) -> T:
    if obj is None:
        raise Exception()
    return obj


class Dog():
    pass


class Cat():
    pass


def func(animal: Dog | Cat | None):
    not_none_animal: Dog | Cat = not_none(animal)
```

**Expected Behavior**

No errors

**Actual Behavior**

Error:

```py
main.py:22: error: Incompatible types in assignment (expression has type "object", variable has type "Dog | Cat")  [assignment]
````

**Your Environment**

- Mypy version used: 1.10.1
- Mypy command-line flags: _none_
- Mypy configuration options: _none_
- Python version used: 3.12

**Comment by hauntsaninja** [comment] 2024-07-07 08:01
Duplicate of https://github.com/python/mypy/issues/17383

**Closed by hauntsaninja** 2024-07-07 08:01 UTC
Labels: bug, topic-join-v-union
