### ISSUE TITLE
False Positive during fixed variable pairs

### ISSUE THREAD

**Issue by ehanhalici** [python/mypy#17913] opened 2024-10-10 10:56 UTC
**Bug Report**

Let's say we have a function that returns a type like this
```python
def f() -> Union[Tuple[Panic, None], Tuple[None, List]]:
```
This function will return Panic and None in case of an error. If there is no error, it will return None and List. 

I then use it like this

```python
err, data = f()
if err is not None:
    ... handle, return or raise 

# now I am sure that data is not None and I use it
data.short()
```
I throw exception or not depending on the situation. but the problem is that mypy says that data.shot() is wrong because data can be None or bytes. but this is wrong i already do it with check err. 

but if I write a code like this
```python
assert data is not None
data.short()
```
then it does not cause problems. i.e. it evaluates each data in its own scope. but not as a group

- Mypy version used: mypy 1.11.2 (compiled: yes)
- Mypy command-line flags:--follow-imports=silent --check-untyped-defs
- Mypy configuration options from `mypy.ini` (and other config files): no conf
- Python version used: Python 3.9.7

**Comment by hauntsaninja** [comment] 2024-10-11 03:58
Duplicate of https://github.com/python/mypy/issues/13218

**Closed by hauntsaninja** 2024-10-11 03:58 UTC
Labels: bug
