### ISSUE TITLE
Mypy does not check bounds of variable type aliases

### ISSUE THREAD

**Issue by harahu** [python/mypy#13086] opened 2022-07-07 14:42 UTC
**Bug Report**

When having defined a `TypeAlias` dependent on a `TypeVar`, `mypy` does not allays that instances of these are actually allowed. That is, that they respect the bounds or restrictions of the used `TypeVar`. This is in contrast to the behavior for generic types, which are checked.

**To Reproduce**

```py
from typing import Generic, TypeVar, TypeAlias

T = TypeVar("T", bound=bytes | str)
U = TypeVar("U", bytes, str)

BoundedTuple: TypeAlias = tuple[T]
RestrictedTuple: TypeAlias = tuple[U]


i_am_illegal1: BoundedTuple[int]  # Passes, even though this type shouldn't be possible!
i_am_illegal2: RestrictedTuple[int]  # Passes, even though this type shouldn't be possible!


class Bounded(Generic[T]):
    pass
    
class Restricted(Generic[U]):
    pass


i_am_illegal3: Bounded[int]  # Behaves as expected, resulting in `error: Type argument "int" of "Bounded" must be a subtype of "Union[bytes, str]"`
i_am_illegal4: Restricted[int]  # Behaves as expected, resulting in `error: Value of type variable "U" of "Restricted" cannot be "int"`

```

https://mypy-play.net/?mypy=latest&python=3.10&flags=strict&gist=f5763650eba54f25b51553dbdd58179f

**Expected Behavior**

I expect four errors instead of two from the example code above.

**Actual Behavior**

As can be seen, I was allowed to define types that shouldn't be allowed, given the restrictions of the type variables in use.

**Your Environment**

- Mypy version used: 0.961
- Mypy command-line flags: --strict
- Python version used: 3.10

**Comment by harahu** [comment] 2022-07-07 20:07
> [...] This explains why mypy does not emit an error for your first and third example.

Good catch! Appreciate it. Changed the example, but the first example also remains faulty, so it seems this is an issue for variable type aliases, but not for generics. Please let me know whether the issue is worded more clearly (and correctly) now.

**Comment by AlexWaygood** [comment] 2022-07-07 20:14
Oh yikes — yup, your revised first example is definitely a bug!

**Comment by AlexWaygood** [comment] 2022-07-07 23:12
> Oh yikes — yup, your revised first example definitely looks like a bug to me!

... But it's a duplicate of #10445. Your example using the constrained `TypeVar` is new, but I'm closing this so that we can keep all the discussion in one place, since it's the same bug :)

**Closed by AlexWaygood** 2022-07-07 23:12 UTC
Labels: bug, topic-type-variables, topic-type-alias

**Comment by harahu** [comment] 2022-07-07 23:58
> ... But it's a duplicate of #10445. Your example using the constrained `TypeVar` is new, but I'm closing this so that we can keep all the discussion in one place, since it's the same bug :)

Thank you for noticing! Not sure how that issue slipped past me.
