### ISSUE TITLE
Mypy installs badly on OSX

### ISSUE THREAD

**Issue by ns-cweber** [python/mypy#5022] opened 2018-05-12 03:03 UTC
I installed via `pip3 install mypy --upgrade`. No errors during install. I also tested inside of a pyenv.

* Are you reporting a bug, or opening a feature request?

Bug

* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.

```py
from typing import List
```

* What is the actual behavior/output?

```
bug.py:1: error: No library stub file for standard library module 'typing'
bug.py:1: note: (Stub files are from https://github.com/python/typeshed)
bug.py:1: error: Cannot find 'builtins' module. Typeshed appears broken!
```

* What is the behavior/output you expect?

No errors, or perhaps an unused import error or something?

* What are the versions of mypy and Python you are using?
  Do you see the same issue after installing mypy from Git master?

mypy 0.600; python 3.6.4; not sure how to check git master

* What are the mypy flags you are using? (For example --strict-optional)

No additional flags

**Comment by gvanrossum** [comment] 2018-05-12 04:26
How's your Python 3.6.4 installed? Homebrew perhaps? (If so, try upgrading it via Homebrew.)

**Comment by ns-cweber** [comment] 2018-05-12 12:39
Python 3.6.4 is installed via pyenv. I also tried with 3.6.2 installed via homebrew.

**Comment by jgirardet** [comment] 2018-05-29 08:49
maybe I have the same problem.
Running in a pyenv virtualenv with virtualenv activated. mypy is installed inside virtualenv.
python 3.6.5

At root repo I have a mapistar directory which own my package.
doing `mypy mapistar` :
I get `error: Cannot find module named <any module>` for all my imports. But There are installed inside the virtualenv.
All the tests are passing.

**Comment by ethanhs** [comment] 2018-05-29 08:57
@jgirardet I think the issue is the modules you are importing don't come from packages that have type annotations, so mypy doesn't look in them. You may want to read https://mypy.readthedocs.io/en/latest/installed_packages.html for more, and consider using `--ignore-missing-imports`.

**Comment by jgirardet** [comment] 2018-05-29 10:14
sorry I did not undertood it was the expected behaviour
thanks

**Comment by ethanhs** [comment] 2018-06-04 04:38
I'm going to go ahead and close this, since we were unable to reproduce this. If someone has steps to reproduce, please feel free to open a new issue.

**Closed by ethanhs** 2018-06-04 04:38 UTC
