### ISSUE TITLE
Incorrect handling of default arguments for type Type with Typevars

### ISSUE THREAD

**Issue by AMDmi3** [python/mypy#6525] opened 2019-03-08 00:30 UTC
Consider a function which takes type and returns instance of that type. This is handled correctly by mypy:

```python
from typing import Type, TypeVar

MyType = TypeVar('MyType', str, int)

def func(t: Type[MyType]) -> MyType:
    return t()
```

However, if I set default argument for t, mypy fails:

```python
from typing import Type, TypeVar

MyType = TypeVar('MyType', str, int)

# error: Incompatible default for argument "t" (default has type "Type[str]", argument has type "Type[int]")
def func(t: Type[MyType] = str) -> MyType:
    return t()
```
```python
from typing import Type, TypeVar

MyType = TypeVar('MyType', str, int)

# error: Incompatible default for argument "t" (default has type "Type[int]", argument has type "Type[str]")
def func(t: Type[MyType] = int) -> MyType:
    return t()
```
```python
from typing import Type, TypeVar

MyType = TypeVar('MyType')

# error: Incompatible default for argument "t" (default has type "Type[int]", argument has type "Type[MyType]")
def func(t: Type[MyType] = int) -> MyType:
    return t()
```

IMO that's a bug. Without TypeVar it works correctly though:

```python
from typing import Type, TypeVar, Union

def func(t: Type[Union[str, int]] = str) -> Union[str, int]:
    return t()
```

**Comment by ethanhs** [comment] 2019-03-08 00:52
This is a duplicate of https://github.com/python/mypy/issues/4236. Please make sure to search the issue tracker when reporting bugs (using a couple of words such as "default" and "generic"/"typevar" then scanning through the listed issues works well).

**Closed by ethanhs** 2019-03-08 00:52 UTC
