### ISSUE TITLE
Crash in has_base()

### ISSUE THREAD

**Issue by JelleZijlstra** [python/mypy#6749] opened 2019-05-01 11:16 UTC
I'm seeing this crash when running mypy on a large codebase:
```
a/app/view/email/digest_email.py:1346: error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues version: 0.701
Traceback (most recent call last):
  File "/home/jelle/ans/venv/bin/mypy", line 10, in <module>
    sys.exit(console_entry())
  File "mypy/checkexpr.py", line 3250, in accept
  File "mypy/checkexpr.py", line 247, in visit_call_expr
  File "mypy/checkexpr.py", line 317, in visit_call_expr_inner
  File "mypy/checkexpr.py", line 658, in check_call_expr_with_callee_type
  File "mypy/checkexpr.py", line 696, in check_call
  File "mypy/checkexpr.py", line 748, in check_callable_call
  File "mypy/types.py", line 921, in is_type_obj
  File "mypy/nodes.py", line 2423, in is_metaclass
  File "mypy/nodes.py", line 2431, in has_base
AttributeError: attribute 'mro' of 'TypeInfo' undefined
```
Haven't tried to minimize or run without dmypy (it will likely take a long time); maybe this stack trace rings a bell for someone already.

**Comment by ilevkivskyi** [comment] 2019-05-01 12:07
You can look in `a/app/view/email/digest_email.py:1346` to see is there anything special about the thing being called. This will likely give a hint for a short repro. Also you can try running with `--new-semantic-analyzer`, this is likely a bug in semantic analysis.

**Comment by JelleZijlstra** [comment] 2019-05-01 16:05
The crash also triggered in another function (slightly simpler than the first one) that looked like this:
```
def strip_component(component: AnswerStoryUserLink) -> str:
    html = a.webnode2.render_component(component)
    return a.view.email.strip_html_tags(html)
```
The argument type is imported from elsewhere and I think there's a big import cycle involved, so maybe the type ends up getting used before it's processed.

**Comment by JelleZijlstra** [comment] 2019-05-02 15:08
With the new semanal I get a different crash:
```
Traceback (most recent call last):
  File "/home/jelle/ans/venv/bin/mypy", line 10, in <module>
    sys.exit(console_entry())
  File "/home/jelle/ans/venv/lib/python3.6/site-packages/mypy/__main__.py", line 7, in console_entry
    main(None)
  File "/home/jelle/ans/venv/lib/python3.6/site-packages/mypy/main.py", line 84, in main
    res = build.build(sources, options, None, flush_errors, fscache)
  File "mypy/build.py", line 163, in build
  File "mypy/build.py", line 218, in _build
  File "mypy/build.py", line 2461, in dispatch
  File "mypy/build.py", line 2761, in process_graph
  File "mypy/build.py", line 2859, in process_stale_scc
  File "mypy/newsemanal/semanal_main.py", line 71, in semantic_analysis_for_scc
  File "mypy/newsemanal/semanal_main.py", line 149, in process_top_levels
  File "mypy/newsemanal/semanal.py", line 4398, in report_hang
  File "mypy/errors.py", line 267, in report
  File "mypy/errors.py", line 213, in current_target
  File "mypy/scope.py", line 31, in current_target
AssertionError
```
The assertion here is that `self.module` is not None. Not clear that the crash has the same root cause.

**Comment by ilevkivskyi** [comment] 2019-05-06 22:32
If none of the objects called is a class object (I mean `a.webnode2.render_component`, `a.view.email.strip_html_tags` and whatever is called at `a/app/view/email/digest_email.py` line 1346), then it means that `function` class is not fully analyzer at this point. May it be that any of your modules shadow a file in the builtin import cycle? (There is a bunch of file now). You can probably use `-vv` to see what files are in the import cycles with `builtins`.

**Comment by JelleZijlstra** [comment] 2019-05-07 02:35
There's a huge import cycle, but it doesn't involve builtins:
```
LOG:  Found 5268 SCCs; largest has 4032 nodes
LOG:  Processing SCC of size 17 (_importlib_modulespec _ast abc types ast typing mmap importlib.abc codecs os.path collections collections.abc io sys posix os builtins) as inherently stale
```
The 4032-module SCC is where the crash happens.

Both `a.webnode2.render_component` and `a.view.email.strip_html_tags` are functions with no decorators.

**Comment by JelleZijlstra** [comment] 2019-05-07 02:44
(So to be clear, it fully analyzed the builtin SCC, as well as many other SSCs, successfully before the crash.)

**Comment by gvanrossum** [comment] 2019-05-07 03:27
Some cycle. Could it be out of memory?
-- 
--Guido (mobile)

**Comment by ilevkivskyi** [comment] 2019-05-20 21:01
This happened internally recently, so set priority to high.

**Comment by warnes** [comment] 2019-10-22 15:32
I'm also seeing this error:
```
/Users/gwarnes/Projects/discoe/apps/categorycompass/backend/app/inventory/inventory_detail/model.py: error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues version: 0.701
Traceback (most recent call last):
  File "/Users/gwarnes/Projects/discoe/venv/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/Users/gwarnes/Projects/discoe/venv/lib/python3.7/site-packages/mypy/__main__.py", line 7, in console_entry
    main(None)
  File "mypy/build.py", line 1767, in __mypyc_generator_helper__
  File "mypy/build.py", line 2052, in finish_passes
  File "mypy/build.py", line 2062, in _patch_indirect_dependencies
  File "mypy/types.py", line 1060, in __hash__
  File "mypy/types.py", line 921, in is_type_obj
  File "mypy/nodes.py", line 2423, in is_metaclass
  File "mypy/nodes.py", line 2431, in has_base
AttributeError: attribute 'mro' of 'TypeInfo' undefined
/Users/gwarnes/Projects/discoe/apps/categorycompass/backend/app/inventory/inventory_detail/model.py: : note: use --pdb to drop into pdb
```

**Comment by warnes** [comment] 2019-10-22 15:47
I also tried running the `master` branch and get a different error message for the same file:

```
$ mypy --version                                                                                                                                                        [11:47:27]
mypy 0.750+dev.6db1663cc2e60889eec037a882baacef7d830194
```

```
/Users/gwarnes/Projects/discoe/apps/categorycompass/backend/app/inventory/inventory_detail/model.py: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.rtfd.io/en/latest/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.750+dev.6db1663cc2e60889eec037a882baacef7d830194
Traceback (most recent call last):
  File "/Users/gwarnes/Projects/discoe/venv/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/Users/gwarnes/Projects/discoe/venv/lib/python3.7/site-packages/mypy/__main__.py", line 8, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "/Users/gwarnes/Projects/discoe/venv/lib/python3.7/site-packages/mypy/main.py", line 88, in main
    res = build.build(sources, options, None, flush_errors, fscache, stdout, stderr)
  File "/Users/gwarnes/Projects/discoe/venv/lib/python3.7/site-packages/mypy/build.py", line 164, in build
    result = _build(sources, options, alt_lib_path, flush_errors, fscache, stdout, stderr)
  File "/Users/gwarnes/Projects/discoe/venv/lib/python3.7/site-packages/mypy/build.py", line 229, in _build
    graph = dispatch(sources, manager, stdout)
  File "/Users/gwarnes/Projects/discoe/venv/lib/python3.7/site-packages/mypy/build.py", line 2566, in dispatch
    process_graph(graph, manager)
  File "/Users/gwarnes/Projects/discoe/venv/lib/python3.7/site-packages/mypy/build.py", line 2875, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/Users/gwarnes/Projects/discoe/venv/lib/python3.7/site-packages/mypy/build.py", line 2968, in process_stale_scc
    mypy.semanal_main.semantic_analysis_for_scc(graph, scc, manager.errors)
  File "/Users/gwarnes/Projects/discoe/venv/lib/python3.7/site-packages/mypy/semanal_main.py", line 83, in semantic_analysis_for_scc
    check_type_arguments(graph, scc, errors)
  File "/Users/gwarnes/Projects/discoe/venv/lib/python3.7/site-packages/mypy/semanal_main.py", line 353, in check_type_arguments
    state.tree.accept(analyzer)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/gwarnes/Projects/discoe/venv/lib/python3.7/site-packages/mypy/build.py", line 1845, in wrap_context
    yield
  File "/Users/gwarnes/Projects/discoe/venv/lib/python3.7/site-packages/mypy/semanal_main.py", line 353, in check_type_arguments
    state.tree.accept(analyzer)
  File "/Users/gwarnes/Projects/discoe/venv/lib/python3.7/site-packages/mypy/nodes.py", line 292, in accept
    return visitor.visit_mypy_file(self)
  File "/Users/gwarnes/Projects/discoe/venv/lib/python3.7/site-packages/mypy/semanal_typeargs.py", line 34, in visit_mypy_file
    super().visit_mypy_file(o)
  File "/Users/gwarnes/Projects/discoe/venv/lib/python3.7/site-packages/mypy/traverser.py", line 35, in visit_mypy_file
    d.accept(self)
  File "/Users/gwarnes/Projects/discoe/venv/lib/python3.7/site-packages/mypy/nodes.py", line 927, in accept
    return visitor.visit_class_def(self)
  File "/Users/gwarnes/Projects/discoe/venv/lib/python3.7/site-packages/mypy/semanal_typeargs.py", line 45, in visit_class_def
    super().visit_class_def(defn)
  File "/Users/gwarnes/Projects/discoe/venv/lib/python3.7/site-packages/mypy/mixedtraverser.py", line 28, in visit_class_def
    super().visit_class_def(o)
  File "/Users/gwarnes/Projects/discoe/venv/lib/python3.7/site-packages/mypy/traverser.py", line 67, in visit_class_def
    o.defs.accept(self)
  File "/Users/gwarnes/Projects/discoe/venv/lib/python3.7/site-packages/mypy/nodes.py", line 992, in accept
    return visitor.visit_block(self)
  File "/Users/gwarnes/Projects/discoe/venv/lib/python3.7/site-packages/mypy/semanal_typeargs.py", line 49, in visit_block
    super().visit_block(o)
  File "/Users/gwarnes/Projects/discoe/venv/lib/python3.7/site-packages/mypy/traverser.py", line 39, in visit_block
    s.accept(self)
  File "/Users/gwarnes/Projects/discoe/venv/lib/python3.7/site-packages/mypy/nodes.py", line 756, in accept
    return visitor.visit_decorator(self)
  File "/Users/gwarnes/Projects/discoe/venv/lib/python3.7/site-packages/mypy/traverser.py", line 72, in visit_decorator
    o.func.accept(self)
  File "/Users/gwarnes/Projects/discoe/venv/lib/python3.7/site-packages/mypy/nodes.py", line 668, in accept
    return visitor.visit_func_def(self)
  File "/Users/gwarnes/Projects/discoe/venv/lib/python3.7/site-packages/mypy/traverser.py", line 54, in visit_func_def
    self.visit_func(o)
  File "/Users/gwarnes/Projects/discoe/venv/lib/python3.7/site-packages/mypy/semanal_typeargs.py", line 41, in visit_func
    super().visit_func(defn)
  File "/Users/gwarnes/Projects/discoe/venv/lib/python3.7/site-packages/mypy/mixedtraverser.py", line 23, in visit_func
    self.visit_optional_type(o.type)
  File "/Users/gwarnes/Projects/discoe/venv/lib/python3.7/site-packages/mypy/mixedtraverser.py", line 91, in visit_optional_type
    t.accept(self)
  File "/Users/gwarnes/Projects/discoe/venv/lib/python3.7/site-packages/mypy/types.py", line 1061, in accept
    return visitor.visit_callable_type(self)
  File "/Users/gwarnes/Projects/discoe/venv/lib/python3.7/site-packages/mypy/typetraverser.py", line 52, in visit_callable_type
    t.fallback.accept(self)
  File "/Users/gwarnes/Projects/discoe/venv/lib/python3.7/site-packages/mypy/types.py", line 758, in accept
    return visitor.visit_instance(self)
  File "/Users/gwarnes/Projects/discoe/venv/lib/python3.7/site-packages/mypy/semanal_typeargs.py", line 55, in visit_instance
    for (i, arg), tvar in zip(enumerate(t.args), info.defn.type_vars):
  File "/Users/gwarnes/Projects/discoe/venv/lib/python3.7/site-packages/mypy/nodes.py", line 2629, in __getattribute__
    raise AssertionError(object.__getattribute__(self, 'msg'))
AssertionError: fallback can't be filled out until semanal
/Users/gwarnes/Projects/discoe/apps/categorycompass/backend/app/inventory/inventory_detail/model.py: : note: use --pdb to drop into pdb
```

**Comment by JelleZijlstra** [comment] 2019-10-22 16:46
For what it's worth the crash no longer happens on our codebase. Most likely something got fixed in mypy but it's hard to tell.

**Comment by JukkaL** [comment] 2020-02-14 15:27
Closing since the issue might already be fixed and there's no simple repro. We'll reopen this if somebody has a way to reproduce this on a recent mypy.

**Closed by JukkaL** 2020-02-14 15:27 UTC
Labels: crash, priority-0-high
