### ISSUE TITLE
exclude is COMPLETELY broken

### ISSUE THREAD

**Issue by chris1248** [python/mypy#11744] opened 2021-12-14 16:58 UTC
**Bug Report**

Given that my source code is in directory `src`, and I want to ignore files in `src/app/models` I should be able to exclude that directory or files.
The docs:
https://mypy.readthedocs.io/en/stable/command_line.html?highlight=exclude#cmdoption-mypy-exclude
give directions that simply do not work.

**To Reproduce**

1. call `mypy --exclude /src/app/models/ src`

**Expected Behavior**

I should see no files in **src/app/models** in the output of warnings/errors from mypy

**Actual Behavior**

I see LOTS Of files in **src/app/models** in the output of warnings/errors from mypy

**Your Environment**

- Mypy version used: 0.910
- Mypy configuration options from `mypy.ini`:
```
# Global section
[mypy]
python_version = 3.8
```
- Python version used: 3.8.7
- Operating system and version: Max OS 11.6

**Attempted work arounds**
I have similarly tried all sorts of attempts at the regex, with no success. 
mypy --exclude /src/app/models/.*$ src
mypy --exclude /src/app/models$ src
exclude = 'src/app/models/$' (in the ini file)
Nothing works.
Don't you unit tests or integration tests for this stuff??

**Comment by intgr** [comment] 2021-12-14 17:28
As documented, the behavior of `--exclude` is:

> A regular expression that matches file names, directory names and paths which mypy should ignore _while recursively discovering files to check._

I think `--exclude` doesn't apply to modules that are checked due to imports from other files: https://mypy.readthedocs.io/en/stable/running_mypy.html#follow-imports (though if true, this should be added to the documentation)

You would be better off specifying this in `mypy.ini` like this, assuming your import path is `app.models`
```ini
[mypy-app.models.*]
ignore_errors = True
```

You might also get away with `--follow-imports=silent`

PS: Check your tone. If you expect people to help you, you should treat them with respect first.

**Comment by hauntsaninja** [comment] 2021-12-14 20:58
Documentation was updated a while ago in #10845 , mypy just hasn't had a release yet. In any case, closing as a duplicate of https://github.com/python/mypy/issues/8584#issuecomment-927361405 or #10820

**Closed by hauntsaninja** 2021-12-14 20:58 UTC
Labels: bug

**Comment by chris1248** [comment] 2021-12-14 21:03
As you quoted the docs above `which mypy should ignore while recursively discovering files` this should work. Because `src/app/models` is under `src`. A recursive search of files under `src` will indeed go through `src/app/models`. 

So the original issue is still valid, and this should not be closed...
