### ISSUE TITLE
Disentangle is_subtype from is_compatible_with

### ISSUE THREAD

**Issue by ddfisher** [python/mypy#2196] opened 2016-09-29 23:46 UTC
Currently mypy confuses subtyping and compatibility, which has been the source of many strange bugs around `Any`.  The `is_subtype` function really means `is_compatible_with`.  Disentangling these two should fix a number of future bugs.

**Comment by gvanrossum** [comment] 2016-09-30 00:45
Duplicate of #2038.

**Closed by gvanrossum** 2016-09-30 00:45 UTC
