### ISSUE TITLE
Bug on circular imports

### ISSUE THREAD

**Issue by dmoisset** [python/mypy#1984] opened 2016-08-04 13:51 UTC
On certain situations with circular imports, some of the types defined on the circular import are not available, even as a comment/forward reference:

```python
# bar.py
from typing import Union

import foo

MyType = Union[int, str]

# foo.py
import bar

x = ""  # type: bar.MyType
```

If I have these two files,  then I get:

```
$ mypy bar.py
bar.py:3: note: In module imported here:
foo.py:3: error: Invalid type "bar.MyType"
```

(Note that this isn't a "MyType is an undefined name error, it's an "Invalid type"). I was expecting the bar.MyType reference to be possible.

This structure is quite similar to the one in #1972 (and came from the same piece of code), these issues might be related

**Comment by gvanrossum** [comment] 2016-08-04 18:49
Yeah, this is a general problem with import cycles. In this example, if you run `mypy -v bar.py` you should see that it processes foo.py entirely before processing bar.py.

The recommended work-around is to break the cycle by putting some imports inside functions. In your example, bar's import of foo seems less fundamental than foo's import of bar, so if you change bar to
```python
def f():
    import foo
MyType = Union[int, str]
```
the error should disappear.

**Comment by gvanrossum** [comment] 2016-10-12 15:22
Let's make this a duplicate of #481.

**Closed by gvanrossum** 2016-10-12 15:22 UTC
Labels: Import Cycle
