### ISSUE TITLE
Exhaustiveness checking fails for Enum with a single value

### ISSUE THREAD

**Issue by eroller** [python/mypy#15761] opened 2023-07-26 02:17 UTC
**Bug Report**

Exhaustiveness checking fails for Enum with a single value

**To Reproduce**

```python
from typing import assert_never
from enum import IntEnum, auto


class SingletonEnum(IntEnum):
    VAL1 = auto()

    
def singleton_fails(x: SingletonEnum) -> int:
    match x:
        case SingletonEnum.VAL1:
            return 0
```
https://mypy-play.net/?mypy=latest&python=3.11&gist=69825e1c0caab559d5ee90cf6ae85527

**Expected Behavior**

No error.

**Actual Behavior**

error: Missing return statement  [return]

**Your Environment**

- Mypy version used: 1.4.1
- Python version used: 3.11

**Comment by erictraut** [comment] 2023-07-26 02:38
I think this is a duplicate of https://github.com/python/mypy/issues/14393.

**Comment by eroller** [comment] 2023-07-26 02:55
definitely a duplicate of https://github.com/python/mypy/issues/14109

**Closed** 2023-07-26 02:56 UTC
Labels: bug
