### ISSUE TITLE
`sys` checks don't work if imported differently

### ISSUE THREAD

**Issue by DetachHead** [python/mypy#12927] opened 2022-06-02 08:21 UTC
```py
import sys as chungus
import sys
from sys import platform, version_info

if sys.platform == "win32":
    1 + "" # no error (because unreachable)
if platform == "win32":
    1 + "" # error
if chungus.platform == "win32":
    1 + "" # error
    
if sys.version_info >= (9, 9):
    1 + "" # no error (because unreachable)
if version_info >= (9, 9):
    1 + "" # error
if chungus.version_info >= (9, 9):
    1 + "" # error
```
[playground](https://mypy-play.net/?mypy=latest&python=3.10&flags=show-error-context%2Cshow-error-codes%2Cstrict%2Ccheck-untyped-defs%2Cdisallow-any-decorated%2Cdisallow-any-expr%2Cdisallow-any-explicit%2Cdisallow-any-generics%2Cdisallow-any-unimported%2Cdisallow-incomplete-defs%2Cdisallow-subclassing-any%2Cdisallow-untyped-calls%2Cdisallow-untyped-decorators%2Cdisallow-untyped-defs%2Cno-implicit-optional%2Cno-implicit-reexport%2Clocal-partial-types%2Cstrict-equality%2Cwarn-incomplete-stub%2Cwarn-redundant-casts%2Cwarn-return-any%2Cwarn-unreachable%2Cwarn-unused-configs%2Cwarn-unused-ignores&gist=19b59ce5fda874db7520fc3c7280a760)

**Comment by AlexWaygood** [comment] 2022-06-02 09:38
Duplicate of #6189

**Closed by AlexWaygood** 2022-06-02 09:38 UTC
Labels: bug
