### ISSUE TITLE
Singledispatch return type only tracks base function

### ISSUE THREAD

**Issue by maxrothman** [python/mypy#8415] opened 2020-02-17 03:42 UTC
Python 3.8
Mypy: 7.6.0
issue type: bug

```python
ffrom functools import singledispatch

@singledispatch
def f(arg) -> str:
    pass

@f.register
def _1(arg: int) -> int:
    return arg

@f.register
def _2(arg: list) -> list:
    return list(map(f, arg))

reveal_type(f(1))
```

[Here's the code in the mypy playground](https://mypy-play.net/?mypy=latest&python=3.8&gist=b94ce983affb3f43db238de1afbf0939)

What is the actual behavior/output?
```
main.py:15: note: Revealed type is 'builtins.str*'
````

What is the behavior/output you expect?

```
main.py:15: note: Revealed type is 'builtins.int*'
```

**Comment by ilevkivskyi** [comment] 2020-02-17 09:47
Duplicate of https://github.com/python/mypy/issues/2904

**Closed by ilevkivskyi** 2020-02-17 09:47 UTC

**Comment by LeuschkeTressa** [comment] 2022-11-06 23:52
Note: this is now tracked in https://github.com/python/mypy/issues/11727.
