### ISSUE TITLE
class decorator could change type of the decorated class

### ISSUE THREAD

**Issue by ZeeD** [python/mypy#7614] opened 2019-10-03 08:53 UTC
Can a class decorator "change" the type of the decorated class?
My issue is with a "wrapper" class that I created, but I can replicate with even this example:

```python
@str
class C: ...
reveal_type(C)
```

if I launch mypy I see

```bash
$ mypy <(echo '@str
> class C: ...
> reveal_type(C)')
/dev/fd/63:3: note: Revealed type is 'def () -> __main__.C'
$
```

while C, actually, has became a `str`!

**Comment by msullivan** [comment] 2019-10-03 22:15
Yeah, we basically don't do any typechecking of class decorators at all. This is definitely a bug (and a duplicate of #3135) but mostly it hasn't seemed to be a problem!

I think it is somewhat unlikely we will ever understand complicated class decorator behaviors, but we could certainly do better here. I think we'd be more likely to just reject this call than to turn C into a variable of type `str`, though.

**Closed by msullivan** 2019-10-03 22:15 UTC

**Comment by ZeeD** [comment] 2019-10-04 05:34
Sorry for the duplicate, I couldn't find similar issues.
As I said, the "str" was just a "minimal reproducible example", my original problem was with a "wrapper class that act as a replacement".
By the way, I remember to have seen (in a private repo) code with a "singleton" decorator that basically instantiated the class
