### ISSUE TITLE
Union of multiple sets idiom broken because member type is not inferred

### ISSUE THREAD

**Issue by cjolowicz** [python/mypy#8087] opened 2019-12-05 12:20 UTC
The idiom `set().union(*sets)` is used to produce the union of multiple sets:

```python
>>> sets = [{1, 2}, {2, 3}]
>>> set().union(*sets)
{1, 2, 3}
```

This does not type check with mypy:

```python
from typing import Set


sets = [{1, 2}, {2, 3}]
union: Set[int] = set().union(*sets)


# main.py:5: error: 
#  Incompatible types in assignment (expression has type "Set[<nothing>]", 
#  variable has type "Set[int]")
# main.py:5: error: 
#  Argument 1 to "union" of "set" has incompatible type "*List[Set[int]]"; 
#  expected "Iterable[<nothing>]"
```

- [Gist](https://gist.github.com/f93c9038c7b45c7969f048fdbc3bf26a)
- [Playground](https://mypy-play.net/?mypy=latest&python=3.8&gist=f93c9038c7b45c7969f048fdbc3bf26a)

Apparently, mypy infers the type of `set()` to be `Set[<nothing>]`. Ideally, it would work out from the context that `set()` should have type `Set[int]`. I would think that an empty set (with no other reference to it) can have any member type, including the one that works in the specific context.

The following code type-checks:

```python
from typing import Set
sets = [{1, 2}, {2, 3}]
zero: Set[int] = set()
union = zero.union(*sets)
```

**Comment by goodmami** [comment] 2020-06-30 14:00
This appears to be a duplicate of #2013. Also I don't think the problem is with the idiom of the union of multiple sets, but just the union on the same line as set instantiation. Here is what I came across:

```python
# error: Incompatible types in assignment (expression has type "Set[str]", variable has type "Set[Optional[str]]")
maybe_strs: Set[Optional[str]] = set('abc').union((None,))
# the following type checks
maybe_strs2: Set[Optional[str]] = set('abc')
maybe_strs2.add(None)
```

**Comment by JukkaL** [comment] 2020-07-03 16:00
Closing as duplicate of #2013, as pointed out by @goodmami.

**Closed by JukkaL** 2020-07-03 16:00 UTC
Labels: false-positive, feature, priority-1-normal
