### ISSUE TITLE
Feature Request: Add AnyOf type

### ISSUE THREAD

**Issue by kreid415** [python/mypy#7216] opened 2019-07-15 14:49 UTC
Check that types are a subset of the types passed to AnyOf. When using abstract base classes, this would allow the user to define which types are allowed for inherited classes. 
Example:
```
Base(ABC):
    @ abstractmethod
    def foo(holy_grail: AnyOf[int, str, HolyHandGrenade]) -> None:
        pass

Child_1(Base):
    def foo(holy_grail: int) -> None:
        # implementation

Child_2(Base):
    def foo(holy_grail: str) -> None:
        # implementation 

Child_3(Base):
    def foo(holy_grail: Union[str, int]) -> None:
        # implementation
```

**Comment by JukkaL** [comment] 2019-07-17 11:19
A similar feature has been proposed before, and I agree that it could be useful sometimes. It's not very likely to be supported (soon), since a full implementation would be a lot of work. 

Closing as essentially a duplicate of https://github.com/python/typing/issues/566. Feel free to continue the discussion there, as your use case is a little different from the existing examples.

**Closed by JukkaL** 2019-07-17 11:19 UTC
