### ISSUE TITLE
support platform and version checks in conditional expressions

### ISSUE THREAD

**Issue by benjaminp** [python/mypy#5671] opened 2018-09-25 22:04 UTC
I wanted to write `os.environb if sys.version_info[0] == 3 else os.environ` to obtain a dictionary of bytes environmental variables. However, this fails to typecheck on Python 2 because mypy doesn't recognize the version in conditional expressions.

**Comment by ethanhs** [comment] 2018-09-25 22:07
We do support platform and version checks, but only `sys.platform` and `sys.version_info`. Considering `six` is used a fair amount for Python2/3 straddling code, I think we should also support it.

**Comment by benjaminp** [comment] 2018-09-25 22:10
Ah, sorry, I didn't mean this to be about `six`. There's the same problem with `sys.version_inf[0] == 3`.

**Comment by ethanhs** [comment] 2018-09-25 22:13
Ah, interesting, with this:

```
import sys
import os
reveal_type(os.environb if sys.version_info > (3, 0, 0) else os.environ)
```
This reveals `builtins.object` on Python 3 and gives an attribute error on Python 2 (since `os.environb` doesn't exist`. This does indeed seem to be a bug.

**Comment by gvanrossum** [comment] 2018-09-25 22:13
(OT: `six.PY3` support is easy: just pass `--always-true=PY3`.)

**Comment by ilevkivskyi** [comment] 2018-09-26 16:32
This is a duplicate of https://github.com/python/mypy/issues/5550.

I will raise the priority of that issue (but still not high probably, since there is a simple workaround).

**Closed by ilevkivskyi** 2018-09-26 16:32 UTC
Labels: bug, needs discussion, priority-0-high
