### ISSUE TITLE
`TypeVar("T")` can be anything, unless a type guard hints at something else

### ISSUE THREAD

**Issue by alexei** [python/mypy#16742] opened 2024-01-03 21:11 UTC
**Bug Report**

According to the docs, a `TypeVar("T")` can be _anything_, but type guards hint at _something_.

**To Reproduce**

```python
from typing import TypeVar


PT = TypeVar("PT")


def f(p: PT) -> PT:
    reveal_type(p)  # Revealed type is "PT`-1"

    if isinstance(p, bool):
        reveal_type(p)  # Revealed type is "builtins.bool"
        return p
    
    if isinstance(p, int):
        reveal_type(p)  # Revealed type is "builtins.int"
        return p
    
    reveal_type(p)  # Revealed type is "PT`-1"
    
    return p


f(False)  # Incompatible return value type (got "bool", expected "PT")
f(0)  # Incompatible return value type (got "int", expected "PT")
f(.0)
```

See https://gist.github.com/mypy-play/72f6621d0539aae2d7a3483ce389919d

**Expected Behavior**

I would expect the above example to pass. But then again, I've opened tickets in the past which proved to be either my own misunderstanding or my own misuse :)

**Actual Behavior**

```
main.py:8: note: Revealed type is "PT`-1"
main.py:11: note: Revealed type is "builtins.bool"
main.py:12: error: Incompatible return value type (got "bool", expected "PT")  [return-value]
main.py:15: note: Revealed type is "builtins.int"
main.py:16: error: Incompatible return value type (got "int", expected "PT")  [return-value]
main.py:18: note: Revealed type is "PT`-1"
Found 2 errors in 1 file (checked 1 source file)
```

**Comment by hauntsaninja** [comment] 2024-01-04 07:35
Thanks for the issue, I think this is a duplicate of #15151. See also #15711 / #15377

**Closed by hauntsaninja** 2024-01-04 07:35 UTC
Labels: bug

**Comment by alexei** [comment] 2024-01-04 08:24
If a fix isn't planned, then what is the recommended workaround? Cast to `T`?

**Comment by hauntsaninja** [comment] 2024-01-04 08:27
Yes, type ignore or cast will work. Definitely a bug so will be fixed

**Comment by alexei** [comment] 2024-01-04 14:48
Ok, thanks
