### ISSUE TITLE
File-level ignore of specific error codes

### ISSUE THREAD

**Issue by jvdwetering** [python/mypy#8712] opened 2020-04-23 11:50 UTC
I think this is a feature request, not a bug

Consider the following code (Python 3.7.4, mypy 0.770):
```
def f(x: int) -> None:
	return x
f("bla")
```
Running `mypy --show-error-codes` gives two errors (as expected):
```
error: No return value expected  [return-value]
error: Argument 1 to "f" has incompatible type "str"; expected "int"  [arg-type]
```
If I add a global ignore statement to the top of the file in the following manner:
```
# type: ignore[return-value]
def f(x: int) -> None:
	return x
f("bla")
```
I would expect only the first error type to be ignored, but instead mypy ignores both errors (which is what you would expect to happen if the first line is `#type: ignore`.

**Comment by brandtbucher** [comment] 2020-04-25 01:55
Seems like a duplicate of #7839, which *is* a bug.

**Comment by msullivan** [comment] 2020-04-29 18:38
Agreed

**Closed by msullivan** 2020-04-29 18:38 UTC
