### ISSUE TITLE
mypy error: Cannot infer type argument 1 of "sum"

### ISSUE THREAD

**Issue by levsa** [python/mypy#3889] opened 2017-08-30 13:16 UTC
When using sum() to concatenate lists, mypy fails to infer the type argument of "sum", even if types are declared explicitly.

`sum([[1],[2],[3]], []`

or
```
foo: List[List[int]] = [[1],[2],[3]]
sum(foo, [])
```
both give:

`error: Cannot infer type argument 1 of "sum"`

**Comment by JukkaL** [comment] 2017-08-30 13:55
This looks like a duplicate of #230. Here are two workarounds:

* You can use a local variable to hold the empty list and annotate the variable (`empty: List[int] = []`) and pass the variable as the second argument to `sum`.
* You can cast the empty list to the desired type: `sum(foo, cast(List[int], []))`

**Closed by JukkaL** 2017-08-30 13:55 UTC
