### ISSUE TITLE
Mypy (running in 3.10) complains that positional-only parameters are only supported in 3.8+

### ISSUE THREAD

**Issue by hjwp** [python/mypy#13639] opened 2022-09-09 08:16 UTC
**Bug Report**

**To Reproduce**

reporting based on current project, will try and find time for a minimal repro later, but in short:
* a python3.10 virtualenv with mypy and numpy (specific versions below)
* start mypy

**Actual Behavior**

```
👉  mypy /path/to/my_file.py
.venv/lib/python3.10/site-packages/numpy/__init__.pyi:642: error: Positional-only parameters are only supported in Python 3.8 and greater
Found 1 error in 1 file (errors prevented further checking)
```

I did also try adding an explict ` --python-version 3.10` flag, same result.

**Your Environment**

debian

- Mypy version used: mypy 0.971 (compiled: yes)
- Mypy command-line flags: (none)
- Mypy configuration options from `mypy.ini` (and other config files):

```
[tool.mypy]

[[tool.mypy.overrides]]
module = [
    "trimesh",
    "gmsh",
    "pyembree.*",
    "scipy.*",  # TODO: surely there are stubs for scipy somewhere?
]
ignore_missing_imports = true
```

- Python version used: Python 3.10.7
- Operating system and version: Debian bullseye
- numpy version 1.22.3

**Comment by AlexWaygood** [comment] 2022-09-09 08:20
Duplicate of #13499, #13635, #13627. A fix will hopefully be out soon.

**Closed by AlexWaygood** 2022-09-09 08:20 UTC
Labels: bug

**Comment by hjwp** [comment] 2022-09-12 08:51
I'm so sorry, i should have searched more thoroughly for existing bugs.  thanks for your help!

**Comment by TheNewThinkTank** [comment] 2023-05-07 18:16
I am hit by the same issue. Running mypy from GitHub Actions, with Python 3.11, on ubuntu-latest. Link to failed run: https://github.com/TheNewThinkTank/Fitness-Tracker/actions/runs/4908617686/jobs/8764498089

**Comment by AlexWaygood** [comment] 2023-05-07 18:20
> I am hit by the same issue. Running mypy from GitHub Actions, with Python 3.11, on ubuntu-latest. Link to failed run: https://github.com/TheNewThinkTank/Fitness-Tracker/actions/runs/4908617686/jobs/8764498089

Looks like you're using a very old mypy: https://github.com/TheNewThinkTank/Fitness-Tracker/blob/422145d17167119d3a4bba75ed24548dcbeba50f/pyproject.toml#L12

Maybe try updating to the latest version (1.2.0)? :)

**Comment by TheNewThinkTank** [comment] 2023-05-07 18:50
@AlexWaygood Thank you for the quick response. Updating mypy to version 1.2 fixed my issue
