### ISSUE TITLE
AttributeError: attribute 'type_vars' of 'TypeInfo' undefined

### ISSUE THREAD

**Issue by avatar-lavventura** [python/mypy#9081] opened 2020-07-01 15:52 UTC
I am using the master mypy. I don't know why but I keep getting followinger error.

```
❯ mypy end_code.py --show-traceback
eblocbroker/transfer_ownership.py:45: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.rtfd.io/en/latest/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.782
Traceback (most recent call last):
  File "mypy/checkexpr.py", line 3761, in accept
  File "mypy/nodes.py", line 1496, in accept
  File "mypy/checkexpr.py", line 1990, in visit_member_expr
  File "mypy/checkexpr.py", line 2008, in analyze_ordinary_member_access
  File "mypy/checkmember.py", line 126, in analyze_member_access
  File "mypy/checkmember.py", line 143, in _analyze_member_access
  File "mypy/checkmember.py", line 219, in analyze_instance_member_access
  File "mypy/maptype.py", line 20, in map_instance_to_supertype
AttributeError: attribute 'type_vars' of 'TypeInfo' undefined
eblocbroker/transfer_ownership.py:45: : note: use --pdb to drop into pdb
```

**Comment by avatar-lavventura** [comment] 2020-07-01 15:58
On a subfolder i had `__init__.py` file. Removing it solved the issue.

**Comment by JelleZijlstra** [comment] 2020-07-01 18:06
hm mypy shouldn't crash though, no matter what you're doing. Do you have a minimal way to reproduce the crash?

**Comment by avatar-lavventura** [comment] 2020-07-02 09:23
Sorry the repo I was working on was get overwritten, I tried to re-create the problem but I couldn't :-( 

I will update you if I can able to re-generate it.

**Comment by hauntsaninja** [comment] 2022-02-25 20:43
Closing since we don't have a repro and we've fixed bugs that could account for this

**Closed by hauntsaninja** 2022-02-25 20:43 UTC
