### ISSUE TITLE
Mypy doesn't understand `dataclass` assigned to a different name

### ISSUE THREAD

**Issue by rshin** [python/mypy#8853] opened 2020-05-20 00:26 UTC
I am using mypy 0.770.

With the following code:
```
from dataclasses import dataclass

@dataclass
class X:
    f: int

@dataclass(eq=True, frozen=True)
class Y:
    f: int

hashable_dataclass = dataclass(eq=True, frozen=True)
@hashable_dataclass
class Z:
    f: int

X(1)
Y(1)
Z(1)
```

I get the following error on mypy:
```
mypy_dataclass.py:18: error: Too many arguments for "Z"
```

**Comment by rshin** [comment] 2020-05-20 00:29
It would also be nice if the following worked:
```
from dataclasses import dataclass
import functools

hashable_dataclass = functools.partial(dataclass, eq=True, frozen=True)
@hashable_dataclass
class Z:
    f: int
Z(1)
```
But intuitively it seems harder to handle than the case in the issue above.

**Comment by JukkaL** [comment] 2020-05-22 14:26
Yeah, it would be kind of nice support the first example. The way `@dataclass` support is implemented in mypy makes supporting this difficult, however. Leaving this open in case somebody comes up with a simple way to do this. 

(The `partial`use case is very unlikely to be supported.)

**Comment by NeilGirdhar** [comment] 2020-11-04 03:13
It would also be nice for mypy to detect that classes decorated with `hashable_dataclass` are `Hashable`.

**Comment by NeilGirdhar** [comment] 2022-03-02 16:17
I think this is a duplicate of https://github.com/python/mypy/issues/5383

**Closed** 2022-03-02 16:27 UTC
Labels: feature, priority-2-low, false-positive
