### ISSUE TITLE
Type annotations on `with` statements

### ISSUE THREAD

**Issue by rwbarton** [python/mypy#1356] opened 2016-04-08 19:21 UTC
We might not always be able to infer the type of the variable bound by a `with` statement, just like we might not always be able to infer the type of a variable being assigned to for the first time. For this minimal example
```
from typing import TypeVar
from contextlib import ContextManager
T = TypeVar('T')
def g() -> ContextManager[T]: ...

with g() as x:
    pass
```
mypy reports
```
with.py:6: error: Need type annotation for variable
```
It would be nice to be able to write, for example,
```
with g() as x:  # type: int
```
declaring the type of `x`. This is currently rejected by mypy as a parse error.

**Comment by gvanrossum** [comment] 2016-04-08 19:30
Yeah, PEP 484 says this should work. (Also for a `for` loop.)

**Comment by gvanrossum** [comment] 2016-04-08 19:31
Actually we already have an issue for this. Closing as dupe of #892.

**Closed by gvanrossum** 2016-04-08 19:31 UTC
Labels: feature, pep484
