### ISSUE TITLE
false positive when type can be inferred by exception raised in called function

### ISSUE THREAD

**Issue by gaetano-guerriero** [python/mypy#8013] opened 2019-11-26 15:08 UTC
I'm not sure this is supposed to work:
```
from typing import Optional


class A:
    def __init__(self):
        self.n: Optional[int] = 1

    def f(self) -> None:
        if self.n is None:
            raise RuntimeError("")
        self.n += 1         # no mypy error here

    def f_false_positive(self) -> None:
        self.check_n()
        self.n += 1         # mypy error here

    def destroy(self) -> None:
        self.n = None

    def check_n(self):
        if self.n is None:
            raise RuntimeError("")
```
The error is at line 16:
``` 
$ mypy /tmp/1.py
/tmp/1.py:16: error: Unsupported operand types for + ("None" and "int")
/tmp/1.py:16: note: Left operand is of type "Optional[int]"
```
Line 11 is correct instead.

**Comment by ilevkivskyi** [comment] 2019-11-26 18:47
This is essentially a duplicate of https://github.com/python/mypy/issues/4063

**Closed by ilevkivskyi** 2019-11-26 18:47 UTC
