### ISSUE TITLE
Make it possible to ignore annotations in certain files/directories

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#562] opened 2015-01-25 17:21 UTC
Maybe we need a configuration option to force certain modules to not be type checked (this would also allow arbitrary expressions in function annotations). This might be useful for legacy code that uses annotations -- and also for legacy code in general. The configuration option could be command line argument or a setting in a mypy configuration file, for example. By default, we could enable this for the Python std lib.

This was mentioned on python-ideas when discussing PEP 484.

An older idea is to not type check modules that don't import `typing`, but maybe that is too restrictive -- again, this was mentioned in the PEP 484 discussion.

**Comment by JelleZijlstra** [comment] 2017-07-01 19:06
Config files now support an `ignore_errors = True` option to ignore all errors in a file, so I think this can be closed.

**Comment by gvanrossum** [comment] 2017-07-01 19:08
No, pep 484 specifies# type: ignore which is still not implemented.

**Comment by JelleZijlstra** [comment] 2017-07-01 19:09
Then this is a dupe of #626.

**Closed** 2017-07-01 19:58 UTC
Labels: needs discussion
