### ISSUE TITLE
0.971: InvocationError and MYPYPATH issue when running "mypy src" with Tox on GitHub Actions

### ISSUE THREAD

**Issue by jakob-bagterp** [python/mypy#13370] opened 2022-08-09 18:50 UTC
**Bug Report**
With 0.961 and earlier versions, I used MyPy with Tox on GitHub Actions to run automated tests for three different projects. It has worked without issues, but after upgrading version 0.971, I'm getting an `InvocationError` even though I'm using the same basic `mypy src` command to scan my files across all projects.

Bug reports from GitHub Actions:

- [Browserist](https://github.com/jakob-bagterp/browserist/runs/7716601731?check_suite_focus=true)
- [Colorist for Python](https://github.com/jakob-bagterp/colorist-for-python/runs/7752521376?check_suite_focus=true)
- [Timer for Python](https://github.com/jakob-bagterp/timer-for-python/runs/7429627214?check_suite_focus=true)

<img width="1003" alt="Screenshot 2022-08-09 at 20 38 17" src="https://user-images.githubusercontent.com/25110864/183736012-8c9d594b-0a2e-4f22-b8b6-8edefe2a21d4.png">

Note that when running version 0.971 on my local machine, I experience no issues:

<img width="637" alt="Screenshot 2022-08-09 at 20 35 23" src="https://user-images.githubusercontent.com/25110864/183735781-24e36dfe-e464-4458-8b19-7cbaa7040c2a.png">

**To Reproduce**
1. Run MyPy version 0.971 with Tox on GitHub Actions
2. Use command `mypy src`

**Expected Behavior**
MyPy should scan the code and exit without issues.

**Actual Behavior**
Error message:

`/home/runner/work/name-of-project/name-of-project is in the MYPYPATH. Please remove it.`

**Your Environment**
- Mypy version used: 0.971
- Mypy command-line flags: See configuration below
- Python version used: 3.10
- Operating system and version: Ubuntu via GitHub Actions
- MyPy configuration options from `setup.cfg`:

```
[mypy]
mypy_path = $MYPY_CONFIG_FILE_DIR/src
disallow_any_unimported = True
no_implicit_reexport = True
show_error_codes = True
strict = True
warn_unreachable = True
```

- MyPy configuration options from `tox.ini`:

```
[testenv:mypy]
basepython = python3.10
deps =
    -r{toxinidir}/requirements_dev.txt
commands = mypy src
```

**Comment by hauntsaninja** [comment] 2022-08-10 01:34
Thanks, duplicate of https://github.com/python/mypy/issues/13214
I fixed on master and asked for a release with the patch here: https://github.com/python/mypy/issues/13089#issuecomment-1193070448

**Closed by hauntsaninja** 2022-08-10 01:34 UTC
Labels: bug
