### ISSUE TITLE
Using a pipe symbol in `typing.Literal` string

### ISSUE THREAD

**Issue by haakonvt** [python/mypy#16368] opened 2023-10-29 21:30 UTC
**Bug Report**

Using `mypy 1.6.1`, I'm unable to use a pipe symbol in a string used in `typing.Literal`:

**To Reproduce**

```python
from typing import Literal

def fn(x: Literal["foo", "bar", "foo|bar"]) -> None:
    reveal_type(x)
```

**Expected Behavior**
No issue with `"foo|bar"`.

**Actual Behavior**

This gives the following output:
```
bb_mypy.py:4: error: Name "foo" is not defined  [name-defined]
    def fn(x: Literal["foo", "bar", "foo|bar"]) -> None:
                                    ^
bb_mypy.py:5: note: Revealed type is "Any"
Found 1 error in 1 file (checked 1 source file)
```

**Your Environment**

- Python version used: 3.8.18
- Mypy version used: 1.6.1
- Mypy command-line flags: None were used.
- Mypy configuration options from `mypy.ini` (and other config files):

1. pretty = true
2. check_untyped_defs = true
3. ignore_missing_imports = false
4. disallow_untyped_defs = true
5. follow_imports = normal
6. namespace_packages = true
7. explicit_package_bases = true
8. show_error_codes = true
9. plugins = numpy.typing.mypy_plugin
10. no_implicit_reexport = true
11. no_implicit_optional = true
12. warn_redundant_casts = true
13. warn_unused_ignores = true

**Comment by AlexWaygood** [comment] 2023-10-30 15:41
Duplicate of #16367

**Closed by AlexWaygood** 2023-10-30 15:41 UTC
Labels: bug, topic-literal-types, topic-pep-604

**Comment by haakonvt** [comment] 2023-10-30 20:09
> Duplicate of #16367

I'd argue #16367 is a duplicate of this one as I was the one to discover this one and the other was created while I slowly typed this one up 😅  But nevermind!

**Comment by AlexWaygood** [comment] 2023-10-30 22:32
> I'd argue #16367 is a duplicate of this one (as I was the one to discover it) and the other was created while I slowly typed this issue up 😅 But nevermind!

It's a dog-eat-dog world out here on the mypy issue tracker, I'm afraid ;)
