### ISSUE TITLE
Allow spreading of a TypedDict into another TypedDict

### ISSUE THREAD

**Issue by r1chardj0n3s** [python/mypy#11108] opened 2021-09-14 23:06 UTC
**Feature**

Currently TypedDict type checking rejects spread keyword arguments as a type violation, even when a TypedDict is provided as the spread source. Typing information is available and the spread operation works at runtime, so the error received is ... misleading at best, but also I think the spread should be possible, leveraging the typing from the source TypedDict.

**Pitch**

I would like to be able to do this (a simplified version of what I *really* want to do, which involves much larger typed dicts):

```
class Spam(TypedDict):
    one: str

x = Spam(one='one')
Spam(**x)
```

This currently results in this error from mypy:

```
x.py:5: error: Expected keyword arguments, {...}, or dict(...) in TypedDict constructor  [misc]
```

(note that the code executes successfully because the spread does work)

**Comment by graingert** [comment] 2022-01-07 11:51
I'd like to be able to use this for typeddicts that extend each other eg

```python
class Spam(TypedDict):
    one: str
    
class Ham(Spam):
    two: str

x = Spam(one='one')
y = Ham(two="two", **x)
```

**Comment by AlexWaygood** [comment] 2022-05-03 17:49
Closing as a duplicate of #9408

**Closed by AlexWaygood** 2022-05-03 17:49 UTC
Labels: feature, topic-typed-dict
