### ISSUE TITLE
Inference on Union types is not propagated to local function closures.

### ISSUE THREAD

**Issue by DerBiasto** [python/mypy#12790] opened 2022-05-14 20:45 UTC
```python
from typing import Union

def foo(key: str, val: dict[str, int] = None) -> int:
    if val is None:
        return 0
    else:
        def bar() -> int:
            return val[key]  # error: Value of type "Optional[Dict[str, int]]" is not indexable  [index]
        return bar()


def foo(val: Union[list[int], int]) -> int:
    if isinstance(val, list):
        def bar() -> int:
            return val[0]  # error: Value of type "Union[List[int], int]" is not indexable  [index]
        return bar()


val: Union[list[int], int] = [1]
assert isinstance(val, list)

def foo() -> int:
    return val[0]  # error: Value of type "Union[List[int], int]" is not indexable  [index]

```

Type information established in the local scope in which a function is defined is not propagated to the closure of the function.

**Comment by erictraut** [comment] 2022-05-14 21:11
This appears to be a duplicate of https://github.com/python/mypy/issues/2608.

**Comment by AlexWaygood** [comment] 2022-05-14 21:30
> This appears to be a duplicate of #2608.

Yup.

**Closed by AlexWaygood** 2022-05-14 21:30 UTC
