### ISSUE TITLE
Lambda properties on objects don't typecheck correctly (mypy assumes self is passed)

### ISSUE THREAD

**Issue by ezyang** [python/mypy#7020] opened 2019-06-18 21:58 UTC
I wanted to store a lambda in an object and then call it. Mypy doesn't like it.

```
from typing import Callable

class A:
    f: Callable[[bool], bool]
    def __init__(self, f):
        self.f = f

def foo(b: bool) -> bool:
    return b

a = A(foo)
print(a.f(True))
```

Running:

```
dhcp-172-31-207-247:~ ezyang$ python3.7 bb.py 
True
dhcp-172-31-207-247:~ ezyang$ mypy --version
mypy 0.660
dhcp-172-31-207-247:~ ezyang$ mypy bb.py
bb.py:12: error: Invalid self argument "A" to attribute function "f" with type "Callable[[bool], bool]"
bb.py:12: error: Too many arguments
```

(The reason I want to do this is because the object is a dataclass and I'm not exactly sure how well inheritance works with dataclasses, so I thought, maybe I can keep things simple by just storing callables on the object.)

**Comment by ilevkivskyi** [comment] 2019-06-19 00:31
This is actually a duplicate of https://github.com/python/mypy/issues/708 (although this may be non-obvious), see also https://github.com/python/mypy/issues/6910

**Closed by ilevkivskyi** 2019-06-19 00:31 UTC
