### ISSUE TITLE
Inheriting from `Generic[_V]` breaks type inference in `__init__` when `_V` has constraints

### ISSUE THREAD

**Issue by rkr-at-dbx** [python/mypy#3264] opened 2017-04-26 22:04 UTC
```
from typing import TypeVar, Generic

_A = TypeVar('_A', int, str)  # or any other constraints

class C(Generic[_A]):
    def __init__(self):
        # type: () -> None
        self.q = 1
        reveal_type(self.q)
```

yields:
```
example.py:9: error: Cannot determine type of 'q'
example.py:9: error: Revealed type is 'Any'
```

Removing the constraints from `_A` allows mypy to deduce `builtins.int`.

**Comment by ilevkivskyi** [comment] 2017-04-26 23:01
I think this is an exact duplicate of #2697 (see especially https://github.com/python/mypy/issues/2697#issuecomment-272962354, it is identical to your example).

**Closed** 2017-04-26 23:01 UTC
