### ISSUE TITLE
Assignment via `def`

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/mypy#12964] opened 2022-06-10 09:49 UTC
In this example MyPy correctly recognizes that variable `callable` is re-assigned with a non-None value:
```python
from typing import Callable, Optional

def f(callable: Optional[Callable[[], bool]]) -> None:
    if callable is None:
        callable = lambda: False

    callable()
```
But in the following example it seems does not recognize the assignment and returns an error at line 8: `error: "None" not callable`:
```python
from typing import Callable, Optional

def f(callable: Optional[Callable[[], bool]]) -> None:
    if callable is None:
        def callable() -> bool:
            return False

    callable()  # line 8
```

mypy 0.950 (compiled: yes)
Python 3.9.12

**Comment by AlexWaygood** [comment] 2022-06-13 14:14
Duplicate of #9870

**Closed by AlexWaygood** 2022-06-13 14:14 UTC
Labels: bug, topic-type-narrowing
