### ISSUE TITLE
Generic classes cannot be shallow copied

### ISSUE THREAD

**Issue by silviogutierrez** [python/mypy#4283] opened 2017-11-24 16:30 UTC
I looked around a lot to see if I could find anything in the docs or in an open issue. But generic classes, however simple, cannot be copied, at least in Python 3.6:

```python
X = TypeVar('X')

class Foo(Generic[X]):
    pass

a = Foo()
b = copy.copy(a)
```

will fail with:
`TypeError: __copy__() takes 1 positional argument but 2 were given`

Curiously, deepcopy does work.

If this is a duplicate or a known issue, my apologies and please close it out.

Thanks for all the work on this proejct.

Silvio

**Comment by ilevkivskyi** [comment] 2017-11-24 16:32
Duplicate of https://github.com/python/typing/issues/498 (I will work on it soon).

**Closed by ilevkivskyi** 2017-11-24 16:32 UTC

**Comment by silviogutierrez** [comment] 2017-11-24 16:37
That was quick! Sorry for the dupe. Thanks.

**Comment by ilevkivskyi** [comment] 2017-11-24 16:40
No problem, it looks like this in an important issue (it appeared few times recently).
