### ISSUE TITLE
Enums produced using function-call syntax lose attribute information for certain value args.

### ISSUE THREAD

**Issue by jenstroeger** [python/mypy#14758] opened 2023-02-22 07:44 UTC
**Bug Report**

We have [two ways](https://docs.python.org/3/library/enum.html) to create an `Enum`: class syntax
```python
class Foo(enum.Enum):
    BLA = 1
    FOO = 2

foo: Foo = Foo.FOO
print(foo)  # Foo.FOO
```
and function-call syntax:
```python
Foo = enum.Enum("Foo", {"BLA": 1, "FOO": 2})  # Or pass a string, list, tuple of values.

foo: Foo = Foo.FOO
print(foo)  # Foo.FOO
```
Both type-check fine with `mypy`.

However, if the value arg is generated and/or passed down rather than being a literal or direct structure of literals, e.g.
```python
_foos = {"BLA": 1, "FOO": 2}
Foo = enum.Enum("Foo", _foos.items())  # Or use even just `_foos` directly.

foo: Foo = Foo.FOO
print(foo)
```
then
```
bla.py:2: error: Enum() expects a string, tuple, list or dict literal as the second argument  [misc]
bla.py:4: error: "Type[Foo]" has no attribute "FOO"  [attr-defined]
Found 2 errors in 1 file (checked 1 source file)
```
Even passing a `dict` won’t silence the first error:
```python
Foo = enum.Enum("Foo", dict(_foos.items()))
```
I understand that it might be outside of `mypy`’s scope to _always_ attempt trying to derive the enumeration values, but even very simple constructs fail to check:
```python
_foos = "BLA FOO"
Foo = enum.Enum("Foo", _foos)  # Passing "BLA FOO" checks just fine.
```

**To Reproduce**

The above examples can be used to reproduce the issue.

**Expected Behavior**

At least for some simple value-flow constructs I’d expect `mypy` to derive the attributes for the `Foo` enumeration.

**Actual Behavior**

See above:
```
error: "Type[Foo]" has no attribute "FOO"  [attr-defined]
```

**Your Environment**

- Mypy version used: `mypy 1.0.1 (compiled: yes)`
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: `Python 3.10.10`

**Comment by hauntsaninja** [comment] 2023-02-22 07:51
Duplicate of https://github.com/python/mypy/issues/8219
Note that mypy will accept Final strs

**Closed by hauntsaninja** 2023-02-22 07:51 UTC
Labels: bug
