### ISSUE TITLE
Suggestion: Add optional command line flag to disable type checking for _

### ISSUE THREAD

**Issue by jcrmatos** [python/mypy#3114] opened 2017-04-03 09:30 UTC
Hello,

I would like to suggest adding an optional command line flag to disable type checking for _.
It is a Python idiom to use _ when the variable will not be used like this
`for _ in range(10):`
or when the return from a function is not needed, like this
`a, b, _ = some_func()`

Right now (mypy 0.501) I get this error
```
data_processing.py:993: error: Incompatible types in assignment (expression has
type List[List[str]], variable has type "str")
```
when running this
`metadata_dic, _, _ = extract_data(data_lst)`
because the return of the extract_data function is
`Tuple[OrderedDict, List[List[str]], List[List[str]]]`
and some code above that assignment also uses _, but it's type is str.
mypy alerts there is an incompatible type assignment, which would be correct it it was a common variable.

Best regards,

JM

**Comment by JukkaL** [comment] 2017-04-03 10:14
Mypy should probably do this by default. It doesn't make sense to just entirely disable type checking based on variable name since it's not uncommon to use `_` for a real function. Also, hiding basic functionality behind a command line option would be questionable. 

This is essentially a dupe of #465 so I'm closing this.

**Closed by JukkaL** 2017-04-03 10:14 UTC
