### ISSUE TITLE
Add certificate to mypy-lang.org

### ISSUE THREAD

**Issue by atombrella** [python/mypy#11792] opened 2021-12-19 10:04 UTC
Could you please add a certificate to [Website](http://www.mypy-lang.org/) ? When Firefox is configured to HTTPS-only, you get a warning before you can proceed. It might not be top-priority. Thank you! 

**Questions and Help**

_Please note that this issue tracker is not a help form and this issue will be closed._

Please check here instead:

- [Website](http://www.mypy-lang.org/)
- [Documentation](https://mypy.readthedocs.io/)
- [Gitter](https://gitter.im/python/typing)

**Comment by ethanhs** [comment] 2021-12-19 14:56
This is a dupe of https://github.com/JukkaL/mypy-website/issues/12. I think Jukka is planning on making it easier for others to update the website, but he is very busy.

**Closed by ethanhs** 2021-12-19 14:56 UTC
Labels: question
